# -*- coding: utf-8 -*-
"""Abgrenzungstabellen zum EPG (Felder wie knowledge/distinctions.py)."""
from .upca import ENTSPRECHUNG_DISTINCTION

DISTINCTIONS = [
    dict(id="d_upc_lokalkammer_zentralkammer", label="Lokal-/Regionalkammer vs. Zentralkammer",
         concepts=["upc_kammerzustaendigkeit", "upc_zentralkammer"],
         frage="Welche Klagen gehören vor die Lokal- oder Regionalkammer, welche vor die Zentralkammer?",
         kriterien=["Zuständige Klagen", "Anknüpfung", "Besetzung", "Sprache", "Sitz/Abteilung", "Verhältnis zueinander"],
         spalten=["Lokal-/Regionalkammer", "Zentralkammer"],
         rows=[
             ["Verletzungsklage, einstweilige Maßnahmen, Schadensersatz, Vorbenutzung, Lizenzvergütung (Art. 32 Abs. 1 lit. a, c, f, g, h EPGÜ); Widerklage auf Nichtigerklärung", "Nichtigkeitsklage, Feststellung der Nichtverletzung (Art. 32 Abs. 1 lit. b, d EPGÜ); Verletzungsklagen gegen Drittstaatenbeklagte wahlweise; Klagen gegen EPA-Entscheidungen"],
             ["Verletzungsort oder Beklagtensitz (Art. 33 Abs. 1 EPGÜ)", "IPC-Klasse des Patents (Anhang II EPGÜ, R. 17.3 VerfO)"],
             ["Drei rechtlich qualifizierte Richter, technisch qualifizierter Richter auf Antrag oder bei Widerklage (Art. 8 Abs. 2 bis 5 EPGÜ)", "Zwei rechtlich und ein technisch qualifizierter Richter (Art. 8 Abs. 6 EPGÜ)"],
             ["Amtssprache des Sitzstaats oder zugelassene EPA-Sprache; Patentsprache auf Antrag (Art. 49 Abs. 1 bis 5 EPGÜ)", "Sprache des Patents (Art. 49 Abs. 6 EPGÜ)"],
             ["Bis zu vier Lokalkammern je Staat (DE: Düsseldorf, Hamburg, Mannheim, München); Regionalkammer Nordisch-Baltisch", "Sitz Paris; Abteilungen München und Mailand (statt London)"],
             ["Anhängige Verletzungsklage zieht Nichtigkeitsklage an sich (Art. 33 Abs. 4 EPGÜ); Optionen bei Widerklage (Abs. 3)", "Feststellungsklage wird bei Verletzungsklage binnen drei Monaten ausgesetzt (Art. 33 Abs. 6 EPGÜ)"],
         ],
         merksatz="Angriff auf das Produkt zur Lokalkammer, Angriff auf das Patent zur Zentralkammer, es sei denn, die Lokalkammer ist schon befasst."),
    dict(id="d_upc_hauptsache_einstweilig", label="Verletzungsklage vs. Antrag auf einstweilige Maßnahmen",
         concepts=["upc_einstweilige_massnahmen", "upc_verfahrensablauf"],
         frage="Worin unterscheiden sich Hauptsacheverfahren und Eilverfahren vor dem EPG?",
         kriterien=["Rechtsgrundlage", "Beweismaß", "Rechtsbestand", "Dringlichkeit", "Anhörung", "Dauer und Ablauf", "Berufung", "Folgen bei Aufhebung"],
         spalten=["Verletzungsklage", "Einstweilige Maßnahmen"],
         rows=[
             ["Art. 32 Abs. 1 lit. a, Art. 63 ff. EPGÜ; R. 12 bis 118 VerfO", "Art. 32 Abs. 1 lit. c, Art. 62 EPGÜ; R. 205 bis 213 VerfO"],
             ["Volle Überzeugung nach Beweisaufnahme (Art. 54 EPGÜ)", "Hinreichende Sicherheit = überwiegende Wahrscheinlichkeit (R. 211.2 VerfO; NanoString/10x)"],
             ["Nur als Widerklage auf Nichtigerklärung (R. 25 VerfO); Optionen des Art. 33 Abs. 3", "Einwand ohne eigene Klage; Beweislast beim Antragsgegner; Verzicht jederzeit möglich (Merz/Viatris)"],
             ["Keine", "Unangemessene Verzögerung schadet (R. 211.4); Hauptsache darf nicht abwartbar sein (Biolitec)"],
             ["Immer schriftliches Verfahren mit Erwiderung (drei Monate)", "Regel: Anhörung; ausnahmsweise ex parte (R. 212) mit Offenlegungspflicht"],
             ["Ziel: mündliche Verhandlung binnen eines Jahres; Zwischenverfahren", "Wenige Wochen bis Monate; Entscheidung durch Spruchkörper oder Einzelrichter"],
             ["Zwei Monate, Endentscheidung (R. 220.1 lit. a)", "15 Tage, Anordnung nach Art. 62 (R. 220.1 lit. c)"],
             ["Aufhebung wirkt zurück; Zwangsgelder entfallen (Kodak/Fujifilm)", "Verschuldensunabhängiger Schadensersatz (Art. 62 Abs. 5, R. 213); Sicherheitsleistung (R. 211.5)"],
         ],
         merksatz="Eilverfahren = Wahrscheinlichkeit statt Gewissheit, Tempo statt Vollständigkeit, Sicherheit statt Rechtskraft."),
    dict(id="d_upc_r262_r262a", label="Akteneinsicht Dritter (R. 262) vs. Schutz vertraulicher Informationen (R. 262A)",
         concepts=["upc_akteneinsicht", "upc_vertraulichkeit"],
         frage="Wann greift R. 262 VerfO, wann R. 262A VerfO?",
         kriterien=["Schutzrichtung", "Antragsteller", "Zeitpunkt", "Prüfungsmaßstab", "Wirkung gegenüber der Gegenpartei", "Rechtsmittel"],
         spalten=["R. 262 VerfO (Öffentlichkeit des Registers)", "R. 262A VerfO (Vertraulichkeit im Verfahren)"],
         rows=[
             ["Zugang der Öffentlichkeit zu Entscheidungen (automatisch) und zu Schriftsätzen/Beweismitteln (auf begründeten Antrag, Abs. 1 lit. b)", "Beschränkung des Zugangs der Gegenpartei und ihrer Vertreter auf einen Personenkreis"],
             ["Dritter (vertreten nach Art. 48 EPGÜ) bzw. Partei für Vertraulichkeitsvermerk (Abs. 2)", "Die Partei, die das Dokument einreicht"],
             ["Jederzeit; Entscheidung des Berichterstatters nach Anhörung der Parteien", "Bei Einreichung des Dokuments (R. 262A.3)"],
             ["Begründetes Interesse des Dritten (auch abstraktes Fortbildungsinteresse einer Kanzlei, Huawei/MediaTek); Vertraulichkeitsinteressen", "Interesse des Antragstellers überwiegt beträchtlich (R. 262A.5); Recht auf faires Verfahren; mindestens eine natürliche Person je Partei (Ericsson/ASUS)"],
             ["Keine: Ein Antrag nach R. 262.2 schützt nicht vor Weitergabe durch die Gegenpartei; Geheimnis geht verloren (EOFlow/Insulet)", "Ja: Zugangsbeschränkung, gilt über die Instanz hinaus (Curio/10x)"],
             ["Überprüfung nach R. 333, dann Berufung nach R. 220.2, 220.3 (EPG-BerG 2026)", "Berufung nach R. 220.2, 220.3 VerfO"],
         ],
         merksatz="R. 262 regelt, was die Welt sieht; R. 262A regelt, was der Gegner sieht."),
    dict(id="d_upc_einspruch_klageerwiderung", label="Einspruch (R. 19) vs. Klageerwiderung (R. 23)",
         concepts=["upc_einspruch_r19", "upc_verfahrensablauf"],
         frage="Was gehört in den Einspruch, was in die Klageerwiderung?",
         kriterien=["Frist", "Zulässige Inhalte", "Folge des Unterlassens", "Entscheidung", "Rechtsmittel", "Wirkung auf die Hauptfrist"],
         spalten=["Einspruch (Preliminary objection, R. 19 VerfO)", "Klageerwiderung (Statement of defence, R. 23 bis 25 VerfO)"],
         rows=[
             ["Ein Monat nach Zustellung der Klageschrift (R. 19.1)", "Drei Monate nach Zustellung (R. 23)"],
             ["Nur: Zuständigkeit des Gerichts (inkl. Opt-out), Zuständigkeit der Kammer, Sprache der Klageschrift; abschließend (Roku/Dolby)", "Alle Einwendungen zur Sache: Nichtverletzung, Schranken, Erschöpfung, FRAND; Nichtigkeit nur als Widerklage (R. 25)"],
             ["Anerkennung der Zuständigkeit (R. 19.7); Rüge in der Berufung ausgeschlossen (Sinocare/Abbott)", "Versäumnisentscheidung (R. 355) auf Antrag des Klägers"],
             ["Berichterstatter, ggf. Verweisung ins Hauptverfahren (R. 20); Verweisung an zuständige Kammer (R. 19.5)", "Spruchkörper in der Endentscheidung"],
             ["Berufung nach R. 21 VerfO (Zulassung); Aussetzung nur bei eingelegter Berufung (Sun Patent/Vivo)", "Berufung gegen die Endentscheidung (R. 220.1 lit. a)"],
             ["Berührt die Frist für die Klageerwiderung nicht (R. 19.6), außer der Berichterstatter entscheidet anders", "Verlängerung nur ausnahmsweise (R. 9.3), etwa bei fehlenden Anlagen (Sanofi/Amgen)"],
         ],
         merksatz="Der Einspruch fragt „darf dieses Gericht?“, die Klageerwiderung fragt „hat der Kläger recht?“."),
    dict(id="d_upc_berufung_entscheidung_anordnung", label="Berufung gegen Endentscheidungen vs. gegen Anordnungen",
         concepts=["upc_berufung", "upc_ermessensueberpruefung"],
         frage="Welche Entscheidungen des Gerichts erster Instanz sind wie anfechtbar?",
         kriterien=["Gegenstand", "Zulassung", "Frist", "Aufschiebende Wirkung", "Beispiele"],
         spalten=["Endentscheidung (R. 220.1 lit. a, b)", "Anordnung nach Art. 73 Abs. 2 lit. a (R. 220.1 lit. c)", "Sonstige Anordnung (R. 220.2 bis 220.4)"],
         rows=[
             ["Entscheidung in der Sache, Kostenentscheidung, Versäumnisentscheidung", "Anordnungen nach Art. 49 Abs. 5, 59, 60, 61, 62, 67 EPGÜ", "Verfahrensleitende Anordnungen, Streitwert, Zwangsgeldfestsetzung (EOFlow/Insulet), Entscheidungen nach R. 333"],
             ["Keine", "Keine", "Zulassung durch das Gericht erster Instanz oder Ermessensüberprüfung durch den Bereitschaftsrichter (R. 220.3, 220.4)"],
             ["Zwei Monate ab Zustellung der begründeten Entscheidung (R. 224.1 lit. a)", "15 Tage (R. 224.1 lit. b)", "15 Tage ab Zulassung bzw. Antrag auf Überprüfung binnen 15 Tagen"],
             ["Nein, außer Nichtigkeitsentscheidungen (Art. 74 Abs. 2); Antrag nach R. 223", "Nein; Antrag nach R. 223", "Nein"],
             ["Urteil über Verletzung und Widerklage", "Einstweilige Maßnahme, Beweissicherung, Sprachwechsel", "Fristverlängerung, Vertraulichkeitsanordnung, Akteneinsicht"],
         ],
         merksatz="Endentscheidung und Eilanordnungen sind frei anfechtbar, alles andere braucht die Zulassung."),
    dict(id="d_upc_beweissicherung_beweisvorlage", label="Beweissicherung (Art. 60) vs. Beweisvorlage (Art. 59)",
         concepts=["upc_beweissicherung", "upc_beweisanordnung"],
         frage="Wann Beweissicherung/Besichtigung, wann Anordnung der Beweisvorlage?",
         kriterien=["Zweck", "Zeitpunkt", "Maßstab", "Verfahren", "Adressat", "Schutz des Gegners"],
         spalten=["Beweissicherung und Besichtigung (Art. 60 EPGÜ, R. 192 ff.)", "Anordnung der Beweisvorlage (Art. 59 EPGÜ, R. 190)"],
         rows=[
             ["Sicherung gefährdeter Beweismittel, Besichtigung von Räumen, Probenahme („saisie“)", "Vorlage bezeichneter Beweismittel in der Verfügungsgewalt der Gegenseite oder Dritter"],
             ["Vor oder während der Hauptsache; oft ex parte", "Im laufenden Verfahren, typisch im Zwischenverfahren"],
             ["Vernünftigerweise verfügbare Beweise, Plausibilität der Verletzung; keine fishing expedition (Centripetal/Palo Alto)", "Substantiierte, erhebliche und bestrittene Tatsachen; keine Ausforschung unbekannter Tatsachen (LK Düsseldorf Ecovacs/Roborock)"],
             ["Gerichtlich bestellter Sachverständiger vollzieht (R. 196); Verwendungsbeschränkung", "Anordnung mit Bedingungen, Vertraulichkeitsschutz (R. 262A)"],
             ["Mutmaßlicher Verletzer, ggf. Dritte", "Gegenpartei oder Dritter"],
             ["Sicherheit (Art. 60 Abs. 7), Schadensersatz bei Aufhebung (Abs. 8), Überprüfung (R. 197.3), Hauptsachefrist (R. 198)", "Rechtliches Gehör vor der Anordnung; Vertraulichkeit (Art. 58)"],
         ],
         merksatz="Art. 60 holt Beweise, bevor sie verschwinden; Art. 59 holt Beweise, die der Gegner hat."),
    dict(id="d_upc_epg_deutsches_verfahren", label="Verletzungsverfahren vor dem EPG vs. vor deutschen Gerichten",
         concepts=["upc_epg", "upc_bifurkation", "upc_verfahrensablauf"],
         frage="Was ist vor dem EPG anders als im deutschen Patentverletzungsprozess?",
         kriterien=["Rechtsbestand", "Territoriale Wirkung", "Verfahrensdauer und Struktur", "Besetzung", "Sprache", "Kosten", "Vollstreckung", "Rechtsmittel"],
         spalten=["EPG", "Deutschland (LG/OLG, BPatG)"],
         rows=[
             ["Widerklage auf Nichtigerklärung vor derselben Kammer möglich (Art. 33 Abs. 3 lit. a); Bifurkation nur als Option", "Trennungsprinzip: Nichtigkeitsklage nur beim BPatG (§ 81 PatG); Verletzungsgericht setzt allenfalls aus (§ 148 ZPO)"],
             ["Alle Vertragsmitgliedstaaten, für die das Patent gilt (Art. 34 EPGÜ)", "Nur der deutsche Teil des europäischen Patents"],
             ["Front-loaded, feste Fristen, mündliche Verhandlung binnen etwa eines Jahres; drei Verfahrensabschnitte", "Klage, Erwiderung, Replik, Duplik nach richterlicher Fristsetzung; Verhandlung meist nach 12 bis 15 Monaten"],
             ["Multinationaler Spruchkörper, technisch qualifizierter Richter aus dem Pool", "Drei Berufsrichter ohne technische Ausbildung; Sachverständige"],
             ["Wählbar: Deutsch oder Englisch vor deutschen Lokalkammern; Patentsprache auf Antrag", "Deutsch (§ 184 GVG)"],
             ["Festgebühr plus Streitwertgebühr, Erstattung bis zur Obergrenze (Art. 69 EPGÜ)", "GKG-Gebühren nach Streitwert, Erstattung nach RVG-Sätzen (§ 91 ZPO)"],
             ["Sofort vollstreckbar, Zwangsgeld durch das Gericht selbst (R. 354)", "Vorläufige Vollstreckbarkeit gegen Sicherheit (§ 709 ZPO), Ordnungsmittel nach § 890 ZPO"],
             ["Berufung zum Berufungsgericht Luxemburg, keine dritte Instanz; Vorlage an den EuGH", "Berufung zum OLG, Nichtzulassungsbeschwerde/Revision zum BGH"],
         ],
         merksatz="Das EPG verbindet Verletzung und Rechtsbestand in einem Verfahren mit Wirkung für den ganzen Vertragsraum – das ist der Systembruch gegenüber Deutschland."),
    ENTSPRECHUNG_DISTINCTION,
]
