# -*- coding: utf-8 -*-
"""Prüfungsschemata zum Verfahren vor dem EPG. Schritt-IDs: step:<schema>.<n>.<m> (Kurse verweisen darauf)."""
from ..schemata import step

SCHEMATA = [
    dict(
        id="upc_schema_einheitliche_wirkung",
        label="Antrag auf einheitliche Wirkung und Verwaltung des Einheitspatents (EPatVO, DOEPS)",
        kategorie="Einheitspatent: Erteilung und Verwaltung",
        beschreibung="Vom erteilten europäischen Patent zum Einheitspatent: Anspruchsberechtigung, Antrag binnen eines Monats mit Übersetzung, Prüfung durch die Abteilung für den einheitlichen Patentschutz, Eintragung mit Rückwirkung, Rechtsbehelf zum EPG – und danach Jahresgebühren, Kompensation und Register. Die Reihenfolge folgt den Teilen 2 bis 8 der UP-Richtlinien.",
        norms=["Art. 3 EPatVO", "Art. 4 EPatVO", "Art. 9 EPatVO", "R. 5 DOEPS", "R. 6 DOEPS", "R. 7 DOEPS", "R. 97 VerfO"],
        steps=[
            step("A. Anspruchsberechtigung (Art. 3 Abs. 1 EPatVO, R. 5 Abs. 2 DOEPS)", "Europäisches Patent, erteilt mit denselben Ansprüchen für alle 25 teilnehmenden Mitgliedstaaten (keine zurückgenommene Benennung, kein unterschiedlicher Anspruchssatz nach R. 138 EPÜ, Anmeldetag ab 1.3.2007); Antrag durch den oder alle Inhaber (R. 5 Abs. 1); kein sanktionierter Inhaber (R. 5 Abs. 2 lit. b).",
                 concepts=["upc_einheitspatent", "upc_up_generationen"], norms=["Art. 3 EPatVO", "R. 5 DOEPS"]),
            step("B. Antrag: Frist, Form, Inhalt (R. 6 DOEPS)", children=[
                step("1. Monatsfrist ab Erteilungshinweis (R. 6 Abs. 1)", "Ein Monat nach Bekanntmachung des Hinweises auf die Erteilung im Europäischen Patentblatt (Art. 97 Abs. 3 EPÜ); nicht verlängerbar; früher Antrag nach der Erteilungsentscheidung möglich; Wiedereinsetzung binnen zwei Monaten nach Fristablauf (R. 22 Abs. 2 DOEPS).",
                     concepts=["upc_antrag_einheitliche_wirkung"], norms=["R. 6 DOEPS", "R. 22 DOEPS"]),
                step("2. Schriftlich, in der Verfahrenssprache, Formblatt 7000 (R. 6 Abs. 2)", "Angaben zu Inhaber und Vertreter nach R. 41 Abs. 2 EPÜ, Patentnummer; Unterschrift des Inhabers (Sitz in einem EPÜ-Staat), Vertreters oder bevollmächtigten Angestellten; kein Fax; gebührenfrei.",
                     concepts=["upc_antrag_einheitliche_wirkung", "upc_up_abteilung"], norms=["R. 6 DOEPS", "R. 20 DOEPS"]),
                step("3. Übersetzung in der Übergangszeit (Art. 6 EPatÜVO, R. 6 Abs. 2 lit. d)", "Vollständige Übersetzung der Patentschrift: ins Englische bei Verfahrenssprache Deutsch oder Französisch, sonst in eine andere EU-Amtssprache; nur Information, keine Rechtswirkung; Übergangszeit sechs Jahre ab 1.6.2023, höchstens zwölf.",
                     concepts=["upc_up_uebersetzung"], norms=["Art. 6 EPatÜVO", "Art. 3 EPatÜVO", "R. 18 DOEPS"]),
                step("4. Zugleich: Antrag auf Kompensation (R. 9 DOEPS)", "Nur zusammen mit dem Antrag auf einheitliche Wirkung; Erklärung über Status (KMU, natürliche Person, Hochschule, öffentliche Forschungseinrichtung, Organisation ohne Gewinnerzielungsabsicht) und Sitz in der EU; Anmeldung in anderer EU-Amtssprache als DE/EN/FR; Pauschale 500 EUR nach Eintragung.",
                     concepts=["upc_up_kompensation"], norms=["Art. 5 EPatÜVO", "R. 8 DOEPS", "R. 9 DOEPS", "R. 10 DOEPS", "Art. 4 GebOEPS"]),
            ]),
            step("C. Prüfung und Eintragung (R. 7 DOEPS)", children=[
                step("1. Eintragung und Wirksamwerden (R. 7 Abs. 1, Art. 4 Abs. 1 EPatVO)", "Erfordernisse erfüllt: Eintragung im Register für den einheitlichen Patentschutz, Mitteilung des Eintragungstags (Formblatt 7030); das Einheitspatent wirkt rückwirkend ab dem Tag des Erteilungshinweises in den Staaten der aktuellen Generation (Art. 18 Abs. 2 EPatVO).",
                     concepts=["upc_up_generationen", "upc_up_register"], norms=["R. 7 DOEPS", "Art. 4 EPatVO", "Art. 18 EPatVO", "R. 16 DOEPS"]),
                step("2. Formmängel: Monatsfrist ohne Wiedereinsetzung (R. 7 Abs. 3)", "Mängel nach R. 6 Abs. 2 sind binnen einer nicht verlängerbaren Frist von einem Monat zu beheben; keine Wiedereinsetzung (R. 22 Abs. 6 DOEPS; Bodycap/EPA); mindestens einmal rechtliches Gehör (Art. 113 Abs. 1 EPÜ).",
                     concepts=["upc_antrag_einheitliche_wirkung"], norms=["R. 7 DOEPS", "R. 22 DOEPS"], cases=["upc_coa_bodycap_epa_r97"]),
                step("3. Zurückweisung (R. 7 Abs. 2, 3)", "Fehlende Anspruchsberechtigung, Fristversäumung ohne Wiedereinsetzung oder nicht behobene Mängel: beabsichtigte Zurückweisung, Gelegenheit zur Stellungnahme, endgültige Entscheidung. Danach nationale Sicherheitsnetze für die Validierung prüfen (Nationale Maßnahmen zum Einheitspatent).",
                     concepts=["upc_antrag_einheitliche_wirkung", "upc_up_abteilung"], norms=["R. 7 DOEPS", "R. 20 DOEPS"]),
            ]),
            step("D. Rechtsbehelf: Klage vor dem EPG (R. 23, 24 DOEPS; R. 85 bis 98 VerfO)", "Gegen die Zurückweisung des Antrags auf einheitliche Wirkung: Antrag auf Aufhebung binnen drei Wochen, Eilrichter (R. 97 VerfO), keine Abhilfe (R. 85 Abs. 2 VerfO). Gegen andere Entscheidungen der Abteilung: Klage binnen zwei Monaten (R. 88 VerfO) mit Abhilfemöglichkeit (R. 91 VerfO). Zuständigkeit Art. 32 Abs. 1 lit. i, Befugnis Art. 66 EPGÜ; kein Vertretungszwang (Art. 48 Abs. 7 EPGÜ).",
                 concepts=["upc_up_rechtsbehelf"], norms=["R. 23 DOEPS", "R. 24 DOEPS", "R. 88 VerfO", "R. 97 VerfO", "Art. 32 Abs. 1 EPGÜ", "Art. 66 EPGÜ"], cases=["upc_coa_bodycap_epa_r97"]),
            step("E. Nach der Eintragung: Jahresgebühren, Register, Lizenzen", children=[
                step("1. Jahresgebühren an das EPA (R. 13, 14 DOEPS; Art. 2 GebOEPS)", "Fällig ab dem Folgejahr des Erteilungshinweises am Monatsletzten des Anmeldemonats; Nachfrist sechs Monate mit 50 % Zuschlag; sonst Erlöschen rückwirkend zum Fälligkeitstag; Wiedereinsetzung binnen eines Jahres; Sicherheitsfristen nach R. 13 Abs. 4, 5.",
                     concepts=["upc_up_jahresgebuehren"], norms=["Art. 11 EPatVO", "R. 13 DOEPS", "R. 14 DOEPS", "Art. 2 GebOEPS"]),
                step("2. Lizenzbereitschaft (Art. 8 EPatVO, R. 12 DOEPS)", "Erklärung gegenüber dem EPA, 15 % Ermäßigung (Art. 3 GebOEPS); ausgeschlossen bei ausschließlicher Lizenz; Rücknahme nur gegen Rückzahlung; Vergütung durch das EPG (Art. 32 Abs. 1 lit. h EPGÜ).",
                     concepts=["upc_up_lizenzbereitschaft"], norms=["Art. 8 EPatVO", "R. 12 DOEPS", "Art. 3 GebOEPS"]),
                step("3. Rechtsübergang, Lizenzen, Vermögensstatut (Art. 3 Abs. 2, Art. 7 EPatVO; R. 16 DOEPS)", "Übertragung nur für alle Staaten, Lizenz auch für Teilgebiete; Eintragung nach R. 22 bis 24 EPÜ gegen Nachweis; anwendbares Recht für das Patent als Vermögensgegenstand nach Art. 7 EPatVO (Wohnsitz/Niederlassung am Anmeldetag, sonst deutsches Recht).",
                     concepts=["upc_up_register", "upc_up_vermoegen"], norms=["Art. 3 EPatVO", "Art. 7 EPatVO", "R. 16 DOEPS", "R. 20 DOEPS"]),
            ]),
        ],
    ),
    dict(
        id="upc_schema_zustaendigkeit",
        label="Zuständigkeit des EPG und Kammerwahl (Art. 31 bis 34 EPGÜ)",
        kategorie="EPG: Zuständigkeit",
        beschreibung="Vor jeder Klage vor dem EPG: Ist das EPG überhaupt zuständig (international, sachlich, Übergangsregelung), und welche Kammer ist die richtige? Die Prüfung ist in der Klageschrift darzulegen (R. 13.1 lit. i VerfO) und der Beklagte kann sie nur mit dem Einspruch nach R. 19 VerfO angreifen.",
        norms=["Art. 31 EPGÜ", "Art. 32 EPGÜ", "Art. 33 EPGÜ", "Art. 83 EPGÜ"],
        steps=[
            step("A. Anwendbarkeit des EPGÜ (Art. 3, 83 EPGÜ)", "Europäisches Patent mit einheitlicher Wirkung, klassisches europäisches Patent oder ESZ mit Wirkung in einem Vertragsmitgliedstaat? Bei klassischen Patenten: kein wirksamer Opt-out (Art. 83 Abs. 3, R. 5 VerfO); während der Übergangszeit bleibt die konkurrierende Zuständigkeit nationaler Gerichte (Art. 83 Abs. 1).",
                 concepts=["upc_epg", "upc_uebergangsregelung", "upc_opt_out", "upc_einheitspatent"], norms=["Art. 3 EPGÜ", "Art. 83 EPGÜ", "R. 5 VerfO"], cases=["upc_coa_silimed_polytech_optout"]),
            step("B. Internationale Zuständigkeit (Art. 31 EPGÜ, Brüssel-Ia-VO)", "Das EPG ist Gericht eines Mitgliedstaats (Art. 71a Brüssel-Ia-VO): Beklagtensitz in einem Mitgliedstaat (Art. 4) oder Verletzung im Gebiet der Vertragsmitgliedstaaten (Art. 7 Nr. 2 i.V.m. Art. 71b Nr. 2); gegen Drittstaatenbeklagte auch für Schäden außerhalb der EU bei Vermögen im Gebiet (Art. 71b Nr. 3). Rügelose Einlassung erst mit dem ersten Schriftsatz.",
                 concepts=["upc_internationale_zustaendigkeit", "upc_einlassung"], norms=["Art. 31 EPGÜ"], cases=["upc_coa_sinocare_abbott_zustaendigkeit", "upc_cfi_dyson_dreame_zustaendigkeit", "upc_coa_nuc_hurom_einlassung"]),
            step("C. Sachliche Zuständigkeit (Art. 32 EPGÜ)", "Fällt die Klage unter den abschließenden Katalog des Art. 32 Abs. 1 (Verletzung, Nichtverletzung, einstweilige Maßnahmen, Nichtigkeit, Widerklage, Schadensersatz nach vorläufigem Schutz, Vorbenutzung, Lizenzvergütung, EPA-Entscheidungen)? Sonst nationale Gerichte (Abs. 2). Auch Altfälle vor dem 1.6.2023 und selbständige Schadensersatzklagen nach nationalem Urteil sind erfasst.",
                 concepts=["upc_sachliche_zustaendigkeit", "upc_altfaelle"], norms=["Art. 32 EPGÜ"], cases=["upc_coa_fives_reel_altfaelle", "upc_coa_knaus_tabbert_altfaelle"]),
            step("D. Zuständige Kammer (Art. 33 EPGÜ)", children=[
                step("1. Verletzungsklage: Lokal-/Regionalkammer (Art. 33 Abs. 1)", "Verletzungsort (lit. a) oder Beklagtensitz (lit. b) ohne Rangfolge; mehrere Beklagte nur bei Geschäftsbeziehung und demselben Verletzungsvorwurf; Beklagte ohne Sitz im Gebiet: auch Zentralkammer; keine Lokalkammer im Staat: Zentralkammer.",
                     concepts=["upc_kammerzustaendigkeit", "upc_anbieten"], norms=["Art. 33 Abs. 1 EPGÜ"], cases=["upc_coa_barco_yealink_kammer"]),
                step("2. Sperre paralleler Klagen (Art. 33 Abs. 2)", "Keine zweite Klage zwischen denselben Parteien zum selben Patent bei einer anderen Kammer; die zuerst angerufene Kammer entscheidet. Bei Verletzung in drei oder mehr Regionalkammern Verweisung an die Zentralkammer auf Antrag des Beklagten.",
                     concepts=["upc_dieselben_parteien"], norms=["Art. 33 Abs. 2 EPGÜ"], cases=["upc_coa_meril_edwards_parteien", "upc_cfi_seoulviosys_emporia_strohmann"]),
                step("3. Widerklage auf Nichtigerklärung: drei Optionen (Art. 33 Abs. 3)", "(a) gemeinsame Verhandlung mit technisch qualifiziertem Richter, (b) Verweisung der Widerklage an die Zentralkammer mit Fortführung oder Aussetzung der Verletzungsklage, (c) Verweisung beider Klagen mit Zustimmung der Parteien. Entscheidung nach R. 37 VerfO.",
                     concepts=["upc_widerklage_nichtigkeit", "upc_bifurkation"], norms=["Art. 33 Abs. 3 EPGÜ", "R. 37 VerfO"], cases=["upc_coa_emboline_aorticlab_bedingte_widerklage"]),
                step("4. Nichtigkeits- und Feststellungsklage: Zentralkammer (Art. 33 Abs. 4 bis 6)", "Zentralkammer, es sei denn, zwischen denselben Parteien ist eine Verletzungsklage bei einer Lokalkammer anhängig. Abteilung nach IPC-Klasse (Anhang II). Feststellungsklage wird bei nachfolgender Verletzungsklage binnen drei Monaten ausgesetzt (Abs. 6).",
                     concepts=["upc_zentralkammer", "upc_nichtigkeitsklage"], norms=["Art. 33 Abs. 4 EPGÜ", "Art. 33 Abs. 6 EPGÜ", "Art. 7 Abs. 2 EPGÜ"], cases=["upc_cfi_pari_philips_klagebefugnis"]),
                step("5. Vereinbarung und Aussetzung (Art. 33 Abs. 7, 10)", "Die Parteien können jede Kammer einschließlich der Zentralkammer vereinbaren (Abs. 7). Bei parallelem EPA-Verfahren kann das Gericht aussetzen, wenn eine rasche Entscheidung zu erwarten ist (Abs. 10, R. 295 lit. a VerfO).",
                     concepts=["upc_aussetzung"], norms=["Art. 33 Abs. 7 EPGÜ", "Art. 33 Abs. 10 EPGÜ", "R. 295 VerfO"]),
            ]),
            step("E. Rüge durch den Beklagten: Einspruch (R. 19 bis 21 VerfO)", "Binnen eines Monats nach Zustellung; nur Zuständigkeit des Gerichts, der Kammer und Sprache; sonst Anerkennung (R. 19.7). Entscheidung des Berichterstatters oder Verweisung ins Hauptverfahren (R. 20); Berufung nach R. 21; Verweisung statt Abweisung bei benannter zuständiger Kammer (R. 19.5, auch im Eilverfahren).",
                 concepts=["upc_einspruch_r19"], norms=["R. 19 VerfO", "R. 20 VerfO", "R. 21 VerfO"], cases=["upc_coa_roku_dolby_einspruch", "upc_coa_vivo_sunpatent_einspruch_hauptverfahren", "upc_coa_sunpatent_vivo_aussetzung"]),
        ],
    ),
    dict(
        id="upc_schema_verletzungsklage",
        label="Verletzungsklage vor dem EPG (Art. 32 Abs. 1 lit. a EPGÜ, R. 12 ff. VerfO)",
        kategorie="EPG: Verfahren",
        beschreibung="Gutachtenaufbau für die Verletzungsklage: Zulässigkeit (Zuständigkeit, Parteien, Vertretung, Klageschrift, Sprache), Begründetheit (Schutzbereich, Verletzungshandlung, Einwendungen, Rechtsbestand über die Widerklage) und Rechtsfolgen (Art. 63 bis 69, 80 EPGÜ).",
        norms=["Art. 25 EPGÜ", "Art. 63 EPGÜ", "R. 13 VerfO"],
        steps=[
            step("A. Zulässigkeit", children=[
                step("1. Zuständigkeit und Kammer", "Prüfung nach dem Schema Zuständigkeit (Art. 31 bis 34 EPGÜ); Angaben in der Klageschrift (R. 13.1 lit. i); Einspruch des Beklagten nach R. 19.",
                     concepts=["upc_kammerzustaendigkeit", "upc_einspruch_r19"], norms=["Art. 33 EPGÜ", "R. 13.1 VerfO", "R. 19 VerfO"]),
                step("2. Parteien und Klagebefugnis (Art. 46, 47 EPGÜ)", "Patentinhaber (Registervermutung, R. 8.5), ausschließlicher Lizenznehmer nach Unterrichtung des Inhabers (Abs. 2), einfacher Lizenznehmer nur mit Zustimmung (Abs. 3); Beklagter: Verletzer, Mittäter, Gehilfe, Mittelsperson.",
                     concepts=["upc_verletzer"], norms=["Art. 46 EPGÜ", "Art. 47 EPGÜ", "R. 8 VerfO"], cases=["upc_coa_belkin_philips_anbieten"]),
                step("3. Vertretung (Art. 48 EPGÜ)", "Anwalt oder europäischer Patentanwalt mit EPLC; keine Vertretung durch Organe der Partei.",
                     concepts=["upc_vertretung"], norms=["Art. 48 EPGÜ"], cases=["upc_coa_suinno_microsoft_vertretung"]),
                step("4. Klageschrift, Gebühr, Zustellung (R. 13 bis 16, 270 ff. VerfO)", "Inhalt nach R. 13.1 lit. a bis q, Anlagen gleichzeitig (R. 13.2), Gebühr (R. 15), Prüfung durch die Kanzlei (R. 16), Zustellung (R. 270 ff.).",
                     concepts=["upc_klageschrift", "upc_zustellung", "upc_gerichtsgebuehren"], norms=["R. 13 VerfO", "R. 15 VerfO", "R. 16 VerfO", "R. 271 VerfO", "R. 274 VerfO"], cases=["upc_coa_sanofi_amgen_zustellung", "upc_coa_nec_tcl_zustellung_china"]),
                step("5. Verfahrenssprache (Art. 49 EPGÜ, R. 14 VerfO)", "Wahl des Klägers nach Art. 49 Abs. 1, 2; Änderung auf Patentsprache (Abs. 3 bis 5, R. 321 bis 323).",
                     concepts=["upc_verfahrenssprache"], norms=["Art. 49 EPGÜ", "R. 14 VerfO", "R. 323 VerfO"], cases=["upc_cfi_tplink_huawei_sprache"]),
                step("6. Keine entgegenstehende Rechtshängigkeit, kein Opt-out", "Art. 33 Abs. 2 EPGÜ; Art. 29 ff. Brüssel-Ia-VO gegenüber nationalen Gerichten in der Übergangszeit (Art. 83); Opt-out sperrt das EPG (Art. 83 Abs. 3).",
                     concepts=["upc_dieselben_parteien", "upc_opt_out"], norms=["Art. 33 Abs. 2 EPGÜ", "Art. 83 Abs. 3 EPGÜ"]),
            ]),
            step("B. Begründetheit: Verletzung", children=[
                step("1. Schutzbereich: Auslegung des Patentanspruchs (Art. 69 EPÜ)", "Anspruch als maßgebliche Grundlage, Beschreibung und Zeichnungen stets heranziehen, Sicht der Fachperson; Merkmalsgliederung (R. 13.1 lit. m).",
                     concepts=["upc_auslegung_patentanspruch", "upc_fachperson"], norms=["Art. 24 EPGÜ"], cases=["upc_coa_nanostring_10x", "upc_coa_amgen_regeneron_auslegung", "upc_coa_dyson_dreame_auslegung"]),
                step("2. Benutzungshandlung (Art. 25, 26 EPGÜ)", "Unmittelbare Verletzung: Herstellen, Anbieten, Inverkehrbringen, Gebrauchen, Einführen, Besitzen (Erzeugnis, Verfahren, Verfahrenserzeugnis); mittelbare Verletzung durch Mittel, die sich auf ein wesentliches Element beziehen.",
                     concepts=["upc_unmittelbare_verletzung", "upc_anbieten", "upc_mittelbare_verletzung"], norms=["Art. 25 EPGÜ", "Art. 26 EPGÜ"], cases=["upc_coa_belkin_philips_anbieten", "upc_coa_onward_niche_mittelbar"]),
                step("3. Wortsinngemäß oder äquivalent", "Verwirklichung aller Merkmale; bei Abweichung Äquivalenzprüfung (Art. 2 Protokoll zu Art. 69 EPÜ; Haager Test Plant-e/Arkyne).",
                     concepts=["upc_aequivalenz"], norms=["Art. 25 EPGÜ"]),
                step("4. Im Gebiet der Vertragsmitgliedstaaten, ohne Zustimmung", "Räumliche Reichweite Art. 34 EPGÜ; Zustimmung durch Lizenz; Erschöpfung Art. 29 EPGÜ.",
                     concepts=["upc_erschoepfung"], norms=["Art. 34 EPGÜ", "Art. 29 EPGÜ"]),
                step("5. Keine Beschränkungen und Einwendungen (Art. 27, 28 EPGÜ)", "Schrankenkatalog (privat, Versuche, Bolar, Landwirte, Schiffe, Software); nationales Vorbenutzungsrecht; FRAND-Einwand bei standardessentiellen Patenten (Art. 102 AEUV, Huawei/ZTE).",
                     concepts=["upc_beschraenkungen_wirkung", "upc_vorbenutzungsrecht"], norms=["Art. 27 EPGÜ", "Art. 28 EPGÜ"], cases=["upc_cfi_dolby_beko_frand"]),
                step("6. Rechtsbestand: Widerklage auf Nichtigerklärung (R. 25 VerfO, Art. 65 EPGÜ)", "Nichtigkeit ist als Widerklage geltend zu machen, nicht als bloße Einrede; Optionen des Art. 33 Abs. 3; Nichtigkeitsgründe nach Art. 138 EPÜ; Änderung des Patents (R. 30).",
                     concepts=["upc_widerklage_nichtigkeit", "upc_nichtigkeitsgruende", "upc_aenderung_patent"], norms=["R. 25 VerfO", "Art. 65 EPGÜ", "R. 30 VerfO"], cases=["upc_coa_fujifilm_kodak_nichtigkeit", "upc_coa_meril_edwards_parteien"]),
            ]),
            step("C. Rechtsfolgen (Art. 63 bis 69, 80 EPGÜ)", children=[
                step("1. Unterlassung und Zwangsgeld (Art. 63 EPGÜ)", "Ermessen, Verhältnismäßigkeit (Art. 42), Reichweite über begangene Handlungen hinaus, Mittelspersonen; Zwangsgeldandrohung (R. 354.3).",
                     concepts=["upc_unterlassungsanordnung", "upc_zwangsgeld"], norms=["Art. 63 EPGÜ", "Art. 42 EPGÜ", "R. 354 VerfO"], cases=["upc_coa_dyson_dreame_auslegung", "upc_coa_kodak_fujifilm_zwangsgeld"]),
                step("2. Abhilfemaßnahmen, Auskunft, Veröffentlichung (Art. 64, 67, 80 EPGÜ)", "Rückruf, Entfernung, Vernichtung; Auskunft über Herkunft und Vertriebswege; Veröffentlichung auf Kosten des Verletzers.",
                     concepts=["upc_abhilfemassnahmen", "upc_auskunft"], norms=["Art. 64 EPGÜ", "Art. 67 EPGÜ", "Art. 80 EPGÜ"]),
                step("3. Schadensersatz (Art. 68 EPGÜ, R. 125 ff. VerfO)", "Verschulden (wusste oder hätte wissen müssen); Berechnung: Schaden inkl. entgangener Gewinn, Verletzergewinn, Lizenzanalogie; gesondertes Festsetzungsverfahren.",
                     concepts=["upc_schadensersatz"], norms=["Art. 68 EPGÜ", "R. 125 VerfO", "R. 131 VerfO"]),
                step("4. Kosten und Vollstreckung (Art. 69, 82 EPGÜ)", "Kostenentscheidung dem Grunde nach, Festsetzung nach R. 150 ff.; sofortige Vollstreckbarkeit, Sicherheit, Vollstreckungsanzeige (R. 118.8, 354).",
                     concepts=["upc_kostenerstattung", "upc_vollstreckung"], norms=["Art. 69 EPGÜ", "Art. 82 EPGÜ", "R. 150 VerfO", "R. 118.8 VerfO"], cases=["upc_coa_sharkninja_kosten"]),
            ]),
        ],
    ),
    dict(
        id="upc_schema_einstweilige_massnahmen",
        label="Antrag auf einstweilige Maßnahmen (Art. 62 EPGÜ, R. 205 bis 213 VerfO)",
        kategorie="EPG: Einstweilige Maßnahmen und Beweis",
        beschreibung="Der Eilrechtsschutz vor dem EPG: summarisches Verfahren mit vier Prüfungssäulen aus R. 211 VerfO (hinreichende Sicherheit, Interessenabwägung, Dringlichkeit, Sicherheitsleistung), ex parte nur ausnahmsweise.",
        norms=["Art. 62 EPGÜ", "R. 206 VerfO", "R. 211 VerfO"],
        steps=[
            step("A. Zulässigkeit des Antrags", children=[
                step("1. Zuständigkeit (Art. 32 Abs. 1 lit. c, Art. 33 EPGÜ)", "Wie die Hauptsache; Verweisung statt Abweisung bei benannter zuständiger Kammer (R. 19.5 analog). Antrag auch vor oder während der Hauptsache (R. 206.1).",
                     concepts=["upc_kammerzustaendigkeit"], norms=["Art. 32 EPGÜ", "Art. 33 EPGÜ", "R. 206.1 VerfO"], cases=["upc_coa_barco_yealink_kammer"]),
                step("2. Inhalt des Antrags (R. 206.2 VerfO)", "Angaben zur Verletzung, zu den beantragten Maßnahmen, zu Rechtsbestand und Verletzung mit Beweismitteln, Dringlichkeitsgründe, vorprozessuale Korrespondenz; Angaben zu Schutzschriften. Die Anforderungen der lit. b bis e betreffen die Begründetheit.",
                     concepts=["upc_einstweilige_massnahmen"], norms=["R. 206 VerfO"], cases=["upc_coa_nanostring_10x"]),
                step("3. Schutzschrift des Antragsgegners (R. 207 VerfO)", "Vorbeugende Verteidigung; vom Gericht bei der Entscheidung über die Anhörung zu berücksichtigen.",
                     concepts=["upc_schutzschrift"], norms=["R. 207 VerfO", "R. 209 VerfO"]),
            ]),
            step("B. Begründetheit (R. 211 VerfO, Art. 62 Abs. 2, 4 EPGÜ)", children=[
                step("1. Hinreichende Sicherheit über Berechtigung und Verletzung (R. 211.2)", "Überwiegende Wahrscheinlichkeit von Aktivlegitimation und Verletzung (Auslegung nach Art. 69 EPÜ); Beweislast beim Antragsteller.",
                     concepts=["upc_hinreichende_sicherheit", "upc_auslegung_patentanspruch"], norms=["R. 211.2 VerfO", "Art. 62 Abs. 4 EPGÜ"], cases=["upc_coa_nanostring_10x", "upc_coa_dyson_dreame_auslegung"]),
                step("2. Rechtsbestand", "Keine hinreichende Sicherheit, wenn die Nichtigkeit überwiegend wahrscheinlich ist; Beweislast beim Antragsgegner; Nichtigkeitseinwand ist keine Widerklage; nicht eingetragene Anspruchsfassung zulässig.",
                     concepts=["upc_hinreichende_sicherheit", "upc_erfinderische_taetigkeit"], norms=["R. 211.2 VerfO"], cases=["upc_coa_merz_viatris_ev_einwand", "upc_coa_onward_niche_mittelbar"]),
                step("3. Notwendigkeit und Interessenabwägung (R. 211.3, Art. 62 Abs. 2)", "Kann die Hauptsache abgewartet werden? Schäden beider Seiten, Zeitfaktor, Marktsituation.",
                     concepts=["upc_einstweilige_massnahmen", "upc_dringlichkeit"], norms=["R. 211.3 VerfO", "Art. 62 Abs. 2 EPGÜ"], cases=["upc_coa_biolitec_lightguide_ev"]),
                step("4. Keine unangemessene Verzögerung (R. 211.4)", "Zügiger Antrag nach Kenntnis; Produktänderungen rechtfertigen kein Zuwarten; drohende Verletzung verlangt konkrete Anhaltspunkte.",
                     concepts=["upc_dringlichkeit"], norms=["R. 211.4 VerfO", "R. 209.2 VerfO"], cases=["upc_coa_barco_yealink_kammer", "upc_cfi_nokia_sunmi_drohende_verletzung"]),
            ]),
            step("C. Verfahren und Entscheidung", children=[
                step("1. Anhörung oder ex parte (R. 209, 212 VerfO)", "Regel: Anhörung des Antragsgegners; ex parte bei drohendem irreparablem Schaden oder Beweisvernichtung; Offenlegungspflicht; Überprüfung auf Antrag (R. 212.3).",
                     concepts=["upc_ex_parte"], norms=["R. 209 VerfO", "R. 212 VerfO", "Art. 60 Abs. 5 EPGÜ"], cases=["upc_coa_ecovacs_roborock_exparte"]),
                step("2. Inhalt der Anordnung (Art. 62 Abs. 1, 3 EPGÜ)", "Unterlassung, Bedingungen, Beschlagnahme, Sicherheiten, Kontensperre (Art. 61); Reichweite nicht auf begangene Handlungen beschränkt.",
                     concepts=["upc_unterlassungsanordnung"], norms=["Art. 62 Abs. 1 EPGÜ", "Art. 62 Abs. 3 EPGÜ", "Art. 61 EPGÜ"], cases=["upc_coa_dyson_dreame_auslegung"]),
                step("3. Sicherheitsleistung und Folgen (R. 211.5, 213 VerfO, Art. 62 Abs. 5 EPGÜ)", "Sicherheit des Antragstellers; Frist zur Hauptsacheklage (31 Kalendertage/20 Arbeitstage); Schadensersatz bei Aufhebung; Kosten bei Erledigung (R. 360).",
                     concepts=["upc_sicherheit_schadensersatz_ev"], norms=["R. 211.5 VerfO", "R. 213 VerfO", "Art. 62 Abs. 5 EPGÜ"], cases=["upc_cfi_dolby_roku_veranlassung"]),
                step("4. Berufung (Art. 73 Abs. 2 lit. a EPGÜ, R. 220.1 lit. c)", "15 Tage; keine aufschiebende Wirkung, Antrag nach R. 223 möglich.",
                     concepts=["upc_berufung", "upc_aufschiebende_wirkung"], norms=["Art. 73 EPGÜ", "R. 220.1 VerfO", "R. 223 VerfO", "R. 224 VerfO"]),
            ]),
        ],
    ),
    dict(
        id="upc_schema_beweissicherung",
        label="Beweissicherung und Besichtigung (Art. 60 EPGÜ, R. 192 bis 199 VerfO)",
        kategorie="EPG: Einstweilige Maßnahmen und Beweis",
        beschreibung="Die „saisie“ des EPG: Sicherung von Beweismitteln und Besichtigung von Räumlichkeiten vor oder während der Hauptsache, häufig ex parte, mit gerichtlich bestelltem Sachverständigen.",
        norms=["Art. 60 EPGÜ", "R. 192 VerfO"],
        steps=[
            step("A. Antrag (R. 192 VerfO)", "Angaben zu Patent, Antragsgegner, den begehrten Maßnahmen und den Gründen; Beweismittel für die (drohende) Verletzung; bei ex parte Offenlegung aller wesentlichen Tatsachen (R. 192.3); Gebühr.",
                 concepts=["upc_beweissicherung", "upc_ex_parte"], norms=["R. 192 VerfO"], cases=["upc_coa_ecovacs_roborock_exparte"]),
            step("B. Voraussetzungen (Art. 60 Abs. 1 EPGÜ, R. 194 VerfO)", children=[
                step("1. Vernünftigerweise verfügbare Beweismittel für die Verletzung", "Niedrigere Hürde als in der Hauptsache: Plausibilität der Verletzung; keine bloße Spekulation, keine fishing expedition.",
                     concepts=["upc_beweissicherung"], norms=["Art. 60 Abs. 1 EPGÜ", "R. 194 VerfO"], cases=["upc_coa_centripetal_paloalto_beweissicherung"]),
                step("2. Ermessen und Verhältnismäßigkeit (R. 194.2, 194.3)", "Dringlichkeit, Beweisgefährdung, Vertraulichkeitsschutz, Grundrechte (Art. 7 GRCh), Sicherheit (Art. 60 Abs. 7).",
                     concepts=["upc_vertraulichkeit"], norms=["R. 194 VerfO", "Art. 60 Abs. 7 EPGÜ"]),
            ]),
            step("C. Anordnung und Vollzug (R. 196, 197 VerfO)", "Beschreibung, Probenahme, Beschlagnahme, Besichtigung; Sachverständiger und Verwendungsbeschränkung (R. 196.2); ex parte mit Überprüfung (R. 197.3); Vollzug innerhalb der Frist.",
                 concepts=["upc_beweissicherung", "upc_ex_parte"], norms=["R. 196 VerfO", "R. 197 VerfO", "Art. 60 Abs. 5 EPGÜ"]),
            step("D. Folgen (R. 198 VerfO, Art. 60 Abs. 8, 9 EPGÜ)", "Hauptsacheklage binnen 31 Kalendertagen/20 Arbeitstagen, sonst Aufhebung; Schadensersatz des Antragsgegners; Berufung binnen 15 Tagen (Art. 73 Abs. 2 lit. a).",
                 concepts=["upc_sicherheit_schadensersatz_ev", "upc_berufung"], norms=["R. 198 VerfO", "Art. 60 Abs. 8 EPGÜ", "Art. 73 EPGÜ"]),
        ],
    ),
    dict(
        id="upc_schema_nichtigkeit",
        label="Nichtigkeitsklage und Widerklage auf Nichtigerklärung (Art. 65 EPGÜ, R. 25, 42 ff. VerfO)",
        kategorie="EPG: Materielles Recht",
        beschreibung="Angriff auf den Rechtsbestand vor dem EPG: als selbständige Klage bei der Zentralkammer oder als Widerklage in der Verletzungsklage; Gründe aus Art. 138 EPÜ; Verteidigung durch Änderung des Patents.",
        norms=["Art. 65 EPGÜ", "R. 42 VerfO", "R. 25 VerfO"],
        steps=[
            step("A. Zulässigkeit", children=[
                step("1. Klageart und Kammer", "Nichtigkeitsklage: Zentralkammer (Art. 33 Abs. 4), Abteilung nach IPC; Widerklage: mit der Klageerwiderung bei der Lokalkammer (R. 25), dann Optionen des Art. 33 Abs. 3.",
                     concepts=["upc_nichtigkeitsklage", "upc_zentralkammer", "upc_widerklage_nichtigkeit"], norms=["Art. 33 Abs. 4 EPGÜ", "Art. 33 Abs. 3 EPGÜ", "R. 25 VerfO", "R. 42 VerfO"]),
                step("2. Klagebefugnis (Art. 47 Abs. 6 EPGÜ)", "Jede Person, die vom Patent betroffen ist (Freedom-to-operate genügt); Opt-out sperrt.",
                     concepts=["upc_nichtigkeitsklage"], norms=["Art. 47 Abs. 6 EPGÜ"], cases=["upc_cfi_pari_philips_klagebefugnis"]),
                step("3. Inhalt und Substantiierung (R. 44, R. 25.1 VerfO)", "Umfang des Angriffs, Gründe, Tatsachen, Beweismittel und Entgegenhaltungen für jeden Anspruch; Gebühr.",
                     concepts=["upc_nichtigkeitsgruende", "upc_front_loaded"], norms=["R. 44 VerfO", "R. 25 VerfO"], cases=["upc_coa_fujifilm_kodak_nichtigkeit"]),
                step("4. Kein Hindernis durch paralleles EPA-Verfahren", "Einspruch beim EPA sperrt nicht; Aussetzung nach Ermessen (R. 295 lit. a, Art. 33 Abs. 10).",
                     concepts=["upc_aussetzung"], norms=["Art. 33 Abs. 10 EPGÜ", "R. 295 VerfO"]),
            ]),
            step("B. Begründetheit: Nichtigkeitsgründe (Art. 65 Abs. 2 EPGÜ, Art. 138 EPÜ)", children=[
                step("1. Auslegung des Anspruchs", "Dieselben Grundsätze wie bei der Verletzung (NanoString/10x).",
                     concepts=["upc_auslegung_patentanspruch"], norms=["Art. 65 EPGÜ"], cases=["upc_coa_nanostring_10x", "upc_coa_amgen_regeneron_auslegung"]),
                step("2. Neuheit und Offenbarungsgehalt", "Unmittelbar und eindeutig Offenbartes; keine Ableitung von Maßen aus schematischen Zeichnungen; Gattungsbegriffe offenbaren nicht alle Arten.",
                     concepts=["upc_offenbarungsgehalt"], norms=["Art. 65 Abs. 2 EPGÜ"], cases=["upc_coa_knaus_tabbert_altfaelle", "upc_cfi_pari_philips_klagebefugnis"]),
                step("3. Erfinderische Tätigkeit", "Realistischer Ausgangspunkt, Aussicht auf Erfolg (could/would), Pointer für Kombinationen, nichttechnische Merkmale im Zusammenwirken.",
                     concepts=["upc_erfinderische_taetigkeit", "upc_fachperson"], norms=["Art. 65 Abs. 2 EPGÜ"], cases=["upc_coa_meril_edwards_parteien", "upc_cfi_meril_edwards_erfinderisch", "upc_coa_fujifilm_kodak_nichtigkeit", "upc_coa_abbott_sinocare_erfinderisch"]),
                step("4. Unzulässige Erweiterung und Ausführbarkeit", "Goldstandard gegenüber jeder früheren Anmeldung; Ausführbarkeit ohne unzumutbaren Aufwand.",
                     concepts=["upc_unzulaessige_erweiterung"], norms=["Art. 65 Abs. 2 EPGÜ"], cases=["upc_coa_expert_seoulviosys_erweiterung", "upc_coa_amgen_regeneron_auslegung"]),
            ]),
            step("C. Verteidigung: Änderung des Patents (R. 30, 50 VerfO)", "Hilfsanträge in angemessener Zahl mit der Erwiderung; spätere Änderungen nur mit Erlaubnis; Verteidigung von Unteransprüchen ohne Hilfsantrag; Erwiderung auf den Änderungsantrag ohne neue Nichtigkeitsgründe.",
                 concepts=["upc_aenderung_patent"], norms=["R. 30 VerfO", "R. 50 VerfO", "R. 43 VerfO"], cases=["upc_coa_meril_edwards_parteien", "upc_coa_vmr_njoy_aenderung", "upc_coa_fujifilm_kodak_nichtigkeit"]),
            step("D. Entscheidung und Wirkung (Art. 65 Abs. 3 bis 5 EPGÜ)", "Teilweise Nichtigerklärung im Umfang der Gründe; Wirkung ex tunc; Übermittlung an das EPA; Berufung mit aufschiebender Wirkung (Art. 74 Abs. 2).",
                 concepts=["upc_nichtigkeitsgruende", "upc_aufschiebende_wirkung"], norms=["Art. 65 Abs. 3 EPGÜ", "Art. 65 Abs. 4 EPGÜ", "Art. 74 Abs. 2 EPGÜ"], cases=["upc_cfi_avago_tesla_teilnichtigkeit"]),
        ],
    ),
    dict(
        id="upc_schema_berufung",
        label="Berufung zum Berufungsgericht (Art. 73 bis 75 EPGÜ, R. 220 bis 243 VerfO)",
        kategorie="EPG: Berufung",
        beschreibung="Statthaftigkeit, Frist, Form, Beschwer und Prüfungsumfang der Berufung sowie aufschiebende Wirkung und Entscheidung des Berufungsgerichts.",
        norms=["Art. 73 EPGÜ", "Art. 74 EPGÜ", "Art. 75 EPGÜ", "R. 220 VerfO"],
        steps=[
            step("A. Statthaftigkeit (Art. 73 EPGÜ, R. 220 VerfO)", children=[
                step("1. Endentscheidungen und Kostenentscheidungen (R. 220.1 lit. a, b)", "Berufung ohne Zulassung binnen zwei Monaten.", concepts=["upc_berufung"], norms=["Art. 73 Abs. 1 EPGÜ", "R. 220.1 VerfO"]),
                step("2. Anordnungen nach Art. 49 Abs. 5, 59 bis 62, 67 EPGÜ (R. 220.1 lit. c)", "Sprache, Beweisvorlage, Beweissicherung, Arrest, einstweilige Maßnahmen, Auskunft: 15 Tage.", concepts=["upc_berufung"], norms=["Art. 73 Abs. 2 EPGÜ", "R. 220.1 VerfO"]),
                step("3. Sonstige Anordnungen: Zulassung oder Ermessensüberprüfung (R. 220.2 bis 220.4)", "Verfahrensleitende Anordnungen, Streitwert, Zwangsgeldfestsetzung, Entscheidungen nach R. 333.", concepts=["upc_ermessensueberpruefung"], norms=["R. 220.2 VerfO", "R. 220.3 VerfO", "R. 333 VerfO"], cases=["upc_coa_eoflow_insulet_zwangsgeld_berufung"]),
            ]),
            step("B. Frist und Form (R. 224 bis 226 VerfO)", "Beginn mit Zustellung der begründeten Entscheidung; Berufungsschrift und Berufungsbegründung mit vollständiger Angabe der Gründe, Tatsachen und Beweise; Gebühr (R. 228).",
                 concepts=["upc_berufungsfrist", "upc_gerichtsgebuehren"], norms=["R. 224 VerfO", "R. 225 VerfO", "R. 226 VerfO", "R. 228 VerfO"], cases=["upc_coa_belkin_philips_berufungsfrist", "upc_coa_roku_dolby_einspruch"]),
            step("C. Beschwer, Anschlussberufung, Streithelfer (R. 237, 313 VerfO)", "Nur beschwerte Partei; Anschlussberufung nicht zur bloßen Änderung der Begründung; bedingte Berufung bei bedingter Widerklage; Streithelfer ohne eigene Position.",
                 concepts=["upc_beschwer", "upc_streithilfe"], norms=["R. 237 VerfO", "R. 313 VerfO"], cases=["upc_coa_abbott_sinocare_erfinderisch", "upc_coa_emboline_aorticlab_bedingte_widerklage", "upc_coa_strabag_swarco_streithilfe"]),
            step("D. Aufschiebende Wirkung (Art. 74 EPGÜ, R. 223 VerfO)", "Grundsatz: keine; Ausnahme Nichtigkeitsentscheidungen; Antrag mit außergewöhnlichen Umständen, vollständig beim ersten Mal.",
                 concepts=["upc_aufschiebende_wirkung"], norms=["Art. 74 EPGÜ", "R. 223 VerfO"], cases=["upc_coa_amycel_aufschiebend", "upc_coa_siemens_hologic_gehoer"]),
            step("E. Prüfungsumfang und neues Vorbringen (R. 222 VerfO)", "Berufung beschränkt auf die angegriffenen Teile; neue Tatsachen und Beweise nur nach Ermessen (Sorgfalt, Relevanz, Stellungnahme); Ermessensentscheidungen der ersten Instanz nur eingeschränkt überprüfbar.",
                 concepts=["upc_neues_vorbringen_berufung"], norms=["R. 222 VerfO"], cases=["upc_coa_hefei_grundfos_neues_vorbringen", "upc_coa_knaus_tabbert_altfaelle"]),
            step("F. Entscheidung (Art. 75 EPGÜ, R. 242 VerfO)", "Zurückweisung, Aufhebung und eigene Entscheidung (Regel) oder ausnahmsweise Zurückverweisung; Aufhebung wirkt zurück; Kosten; Wiederaufnahme (Art. 81) als außerordentlicher Rechtsbehelf.",
                 concepts=["upc_berufung", "upc_vollstreckung", "upc_wiederaufnahme"], norms=["Art. 75 EPGÜ", "R. 242 VerfO", "Art. 81 EPGÜ"], cases=["upc_coa_kodak_fujifilm_aufhebung_zwangsgeld", "upc_coa_aorticlab_emboline_getrennte_klagen"]),
        ],
    ),
    dict(
        id="upc_schema_kosten",
        label="Kosten, Gebühren und Prozesskostensicherheit (Art. 69 EPGÜ, R. 150 bis 158, 370 VerfO)",
        kategorie="EPG: Verfahren",
        beschreibung="Das Kostenrecht des EPG in Prüfungsreihenfolge: Gerichtsgebühren beim Einreichen, Sicherheit während des Verfahrens, Kostengrundentscheidung im Urteil, Festsetzung danach.",
        norms=["Art. 69 EPGÜ", "R. 150 VerfO", "R. 158 VerfO", "R. 370 VerfO"],
        steps=[
            step("A. Gerichtsgebühren (R. 370 VerfO)", "Festgebühr plus streitwertabhängige Gebühr; Streitwert nach Interesse des Klägers (R. 370.6); Ermäßigung für KMU (R. 370.8); Erstattung bei Rücknahme, Einzelrichter, Vergleich (R. 370.9).",
                 concepts=["upc_gerichtsgebuehren", "upc_streitwert"], norms=["R. 370 VerfO"], cases=["upc_coa_juul_njoy_gebuehren", "upc_coa_kodak_fujifilm_aufhebung_zwangsgeld"]),
            step("B. Prozesskostensicherheit (Art. 69 Abs. 4 EPGÜ, R. 158 VerfO)", "Nur gegen den Antragsteller; Gefährdung der Erstattung oder unangemessen beschwerliche Vollstreckung; eigene Finanzlage, Versicherung; Folge der Nichtleistung: Versäumnisentscheidung.",
                 concepts=["upc_prozesskostensicherheit"], norms=["Art. 69 Abs. 4 EPGÜ", "R. 158 VerfO"], cases=["upc_coa_aarke_sodastream_sicherheit", "upc_coa_hefei_grundfos_sicherheit", "upc_coa_syntorr_arthrex_versicherung", "upc_coa_lasiddhi_athena_kmu"]),
            step("C. Kostengrundentscheidung (Art. 69 Abs. 1 bis 3 EPGÜ)", "Unterliegende Partei trägt zumutbare und angemessene Kosten bis zur Obergrenze; Teilung bei teilweisem Obsiegen; Billigkeitsausnahmen; Streithelfer wie Hauptpartei.",
                 concepts=["upc_kostenerstattung"], norms=["Art. 69 EPGÜ"], cases=["upc_coa_sharkninja_kosten", "upc_coa_strabag_swarco_streithilfe"]),
            step("D. Kostenfestsetzung (R. 150 bis 157 VerfO)", "Antrag binnen eines Monats nach der Entscheidung (R. 151); Verfahren vor dem Berichterstatter; Vorschuss im Urteil (R. 150.2); Berufung gegen die Kostenentscheidung (R. 221).",
                 concepts=["upc_kostenerstattung"], norms=["R. 150 VerfO", "R. 151 VerfO", "R. 152 VerfO", "R. 157 VerfO", "R. 221 VerfO"]),
        ],
    ),
    dict(
        id="upc_schema_vertraulichkeit",
        label="Antrag auf Schutz vertraulicher Informationen (Art. 58 EPGÜ, R. 262A VerfO)",
        kategorie="EPG: Einstweilige Maßnahmen und Beweis",
        beschreibung="Prüfungsfolge für den Geheimnisschutz im Verfahren: Antrag bei Einreichung, Substantiierung, Abwägung, Vertraulichkeitskreis, Fortgeltung.",
        norms=["Art. 58 EPGÜ", "R. 262A VerfO"],
        steps=[
            step("A. Antrag (R. 262A.1 bis 262A.3 VerfO)", "Bei Einreichung des Dokuments; unbearbeitete und bearbeitete Fassung; Begründung, warum die Beschränkung nach Art. 58 EPGÜ erforderlich ist; allgemeine Hinweise auf Wettbewerb genügen nicht.",
                 concepts=["upc_vertraulichkeit"], norms=["R. 262A VerfO", "Art. 58 EPGÜ"], cases=["upc_cfi_fujifilm_kodak_vertraulichkeit"]),
            step("B. Anhörung und Abwägung (R. 262A.4, 262A.5 VerfO)", "Stellungnahme der Gegenseite; Stattgabe, wenn die Gründe das Interesse an uneingeschränktem Zugang beträchtlich überwiegen; Recht auf wirksamen Rechtsbehelf und faires Verfahren, Interessen Dritter, mögliche Schäden.",
                 concepts=["upc_vertraulichkeit", "upc_rechtliches_gehoer"], norms=["R. 262A VerfO"], cases=["upc_coa_ericsson_asus_vertraulichkeit"]),
            step("C. Vertraulichkeitskreis (R. 262A.6 VerfO)", "Nicht mehr Personen als nötig, mindestens eine natürliche Person je Partei und die Vertreter; Mitarbeiter in der Regel nicht ausgeschlossen; Aufnahme ausgeschiedener Mitarbeiter unter Bedingungen.",
                 concepts=["upc_vertraulichkeit"], norms=["R. 262A.6 VerfO"], cases=["upc_coa_ericsson_asus_vertraulichkeit"]),
            step("D. Wirkung und Rechtsmittel", "Fortgeltung nach Abschluss der Instanz; Verlust des Geheimnisschutzes bei Offenlegung ohne Anordnung; Abgrenzung zu R. 262.2 (Öffentlichkeit); Berufung nach R. 220.2, 220.3.",
                 concepts=["upc_vertraulichkeit", "upc_akteneinsicht"], norms=["R. 262A VerfO", "R. 262 VerfO", "R. 220.2 VerfO"], cases=["upc_coa_curio_10x_262a", "upc_coa_eoflow_insulet_geheimnis"]),
        ],
    ),
]
