# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k01", gebiet="markeng", titel="Grundlagen des Markenrechts", untertitel="Was eine Marke ist, wie sie entsteht und was sie leistet",
    farbe="#1482e3", icon="marke",
    beschreibung="Der Einstieg: Schutzgegenstände des MarkenG, Markenfunktionen, die drei Entstehungstatbestände des § 4 und das Prioritätsprinzip.",
    kapitel=[
        dict(id="k01a", titel="Schutzgegenstände und Funktionen", einheiten=[
            intro("k01a-0", "Worum geht es im Markenrecht?",
                  "Das MarkenG schützt drei Arten von Kennzeichen (§ 1): **Marken** (für Waren und Dienstleistungen), **geschäftliche Bezeichnungen** (Unternehmenskennzeichen und Werktitel) und **geographische Herkunftsangaben**. Alle drei sind Zeichen, die im geschäftlichen Verkehr etwas voneinander unterscheidbar machen. In diesem Kurs lernst du, was eine Marke ist, welche Funktionen sie hat und wie Markenschutz entsteht.",
                  concepts=["marke", "geschaeftliche_bezeichnung", "geographische_herkunftsangabe"], norms=["§ 1", "§ 2"]),
            fall("k01a-1", "Das Logo auf der Limonade",
                 "Lena stellt Limonade her und druckt auf jede Flasche ein stilisiertes Zitronen-Logo mit dem Wort „ZITRA“. Kunden erkennen die Limonade im Regal daran wieder.",
                 "Ist „ZITRA“ mit dem Logo ein Zeichen, das grundsätzlich als Marke geschützt werden kann?", True,
                 ["**Ja, in der Tat!** Als Marke können alle Zeichen geschützt werden, die geeignet sind, Waren eines Unternehmens von denen anderer Unternehmen zu unterscheiden (§ 3 Abs. 1). Wörter und Abbildungen nennt das Gesetz ausdrücklich.",
                  "Das Zeichen erfüllt hier genau die **Hauptfunktion der Marke**: Es garantiert dem Kunden, dass die Limonade aus einem bestimmten Unternehmen stammt (Herkunftsfunktion). Ob das Zeichen auch eingetragen wird, ist eine andere Frage (§ 8)."],
                 merke="§ 3 Abs. 1 fragt nur abstrakt: Kann ein solches Zeichen überhaupt unterscheiden? Die konkrete Unterscheidungskraft für bestimmte Waren prüft erst § 8 Abs. 2 Nr. 1.",
                 concepts=["marke", "markenfaehigkeit", "herkunftsfunktion"], norms=["§ 3 Abs. 1"]),
            fall("k01a-2", "Die Farbe des Lieferwagens",
                 "Ein Paketdienst lackiert alle Fahrzeuge in einem bestimmten Gelbton und möchte diesen Farbton ohne Form und Umriss als Marke anmelden.",
                 "Kann eine abstrakte Farbe überhaupt markenfähig sein?", True,
                 ["**Ja!** § 3 Abs. 1 nennt „sonstige Aufmachungen einschließlich Farben und Farbzusammenstellungen“. Auch eine konturlose Farbe ist markenfähig, wenn sie eindeutig bestimmt ist, etwa durch einen Farbcode (EuGH Libertel).",
                  "Etwas anderes ist die Frage, ob die Farbe für Paketdienste **unterscheidungskräftig** ist. Das bejaht die Rechtsprechung bei Farben nur ausnahmsweise; meist braucht es Verkehrsdurchsetzung (§ 8 Abs. 3). Dazu später mehr."],
                 merke="Markenfähigkeit (§ 3) und Unterscheidungskraft (§ 8 Abs. 2 Nr. 1) sind zwei Stufen. Farben nehmen die erste fast immer, die zweite selten.",
                 level=2, concepts=["farbmarke", "markenfaehigkeit"], norms=["§ 3 Abs. 1"], cases=["eugh_libertel"]),
            mc("k01a-3", "Die Funktionen der Marke",
               "Welche Funktion der Marke ist nach EuGH und BGH die Hauptfunktion, an die auch der Verletzungstatbestand anknüpft?",
               ["Die Werbefunktion", "Die Herkunftsfunktion", "Die Qualitätsfunktion", "Die Investitionsfunktion"], 1,
               ["Die **Herkunftsfunktion** ist die Hauptfunktion: Die Marke garantiert dem Verbraucher die Ursprungsidentität der Ware. Sie ist der Maßstab für die Unterscheidungskraft (§ 8 Abs. 2 Nr. 1) und für die markenmäßige Benutzung (§ 14 Abs. 2).",
                "Daneben schützt der EuGH auch die Qualitäts-, Kommunikations-, Investitions- und Werbefunktion (L'Oréal/Bellure). Diese spielen vor allem bei der Doppelidentität (§ 14 Abs. 2 Nr. 1) und beim Bekanntheitsschutz (Nr. 3) eine Rolle."],
               concepts=["markenfunktionen", "herkunftsfunktion"], cases=["eugh_loreal_bellure", "eugh_arsenal"]),
            fall("k01a-4", "Der Vereinsname",
                 "Der Fußballverein „FC Sonnenberg e.V.“ tritt unter diesem Namen im Geschäftsverkehr auf (Ticketverkauf, Fanartikel). Er hat keine Marke angemeldet.",
                 "Genießt der Vereinsname trotzdem Kennzeichenschutz nach dem MarkenG?", True,
                 ["**Ja!** Neben Marken schützt das MarkenG **geschäftliche Bezeichnungen** (§ 1 Nr. 2, § 5). Der Name eines Vereins, der im geschäftlichen Verkehr benutzt wird, ist ein Unternehmenskennzeichen nach § 5 Abs. 2.",
                  "Der Schutz entsteht **ohne Eintragung** allein durch die Benutzungsaufnahme, wenn der Name unterscheidungskräftig ist. Verletzungen richten sich dann nach § 15, nicht nach § 14."],
                 merke="Marke = kennzeichnet Produkte. Unternehmenskennzeichen = kennzeichnet das Unternehmen. Beide stehen im MarkenG, haben aber eigene Normen (§§ 4/14 vs. §§ 5/15).",
                 concepts=["geschaeftliche_bezeichnung", "unternehmenskennzeichen"], norms=["§ 1", "§ 5 Abs. 2"]),
        ]),
        dict(id="k01b", titel="Entstehung des Markenschutzes und Priorität", einheiten=[
            schema("k01b-0", "Prüfungsschema: Entstehung und Erlöschen", "schema_entstehung",
                   "Verschaffe dir zuerst einen Überblick über den Lebenszyklus einer Marke. Die folgenden Fälle gehen die Entstehungstatbestände des § 4 durch."),
            fall("k01b-1", "Die angemeldete, noch nicht eingetragene Marke",
                 "Tom meldet am 1. März die Wortmarke „KAFFEEKUSS“ für Kaffee beim DPMA an. Am 15. März bietet Konkurrent Karl Kaffee unter „Kaffeekuss“ an. Die Eintragung erfolgt erst am 20. Mai.",
                 "Hat Tom am 15. März bereits eine Marke im Sinne des § 4 Nr. 1, aus der er gegen Karl vorgehen kann?", False,
                 ["**Nein!** Markenschutz durch Eintragung entsteht erst mit der **Eintragung** in das Register (§ 4 Nr. 1). Die bloße Anmeldung begründet noch kein Ausschließlichkeitsrecht nach § 14.",
                  "Aber: Der **Zeitrang** der Marke bestimmt sich nach dem Anmeldetag (§ 6 Abs. 2, § 33 Abs. 1). Nach der Eintragung kann Tom gegen Benutzungen vorgehen, die nach dem 1. März begonnen haben. Für die Zeit davor bleibt ihm nur das UWG."],
                 merke="Anmeldung sichert den Zeitrang, Eintragung schafft das Recht.",
                 concepts=["entstehung_markenschutz", "prioritaet"], norms=["§ 4", "§ 6 Abs. 2", "§ 33"]),
            fall("k01b-2", "Die Benutzungsmarke",
                 "Bäckerin Bea verkauft seit zwölf Jahren in ganz Deutschland Brote unter der Bezeichnung „KRUSTIS“, ohne je eine Marke angemeldet zu haben. Umfragen zeigen, dass 45 % der Brotkäufer „KRUSTIS“ einem bestimmten Unternehmen zuordnen.",
                 "Kann Bea auch ohne Eintragung Inhaberin einer Marke sein?", True,
                 ["**Ja, in der Tat!** Markenschutz entsteht auch durch Benutzung eines Zeichens im geschäftlichen Verkehr, soweit das Zeichen innerhalb der beteiligten Verkehrskreise als Marke **Verkehrsgeltung** erworben hat (§ 4 Nr. 2).",
                  "Bei einem von Haus aus unterscheidungskräftigen Phantasiewort wie „KRUSTIS“ genügt ein Zuordnungsgrad von etwa 20 bis 25 %. Bea hat also eine Benutzungsmarke mit dem Zeitrang des Zeitpunkts, zu dem die Verkehrsgeltung eingetreten ist (§ 6 Abs. 3)."],
                 merke="Verkehrsgeltung (§ 4 Nr. 2) ist weniger als Verkehrsdurchsetzung (§ 8 Abs. 3): Sie schafft die Marke, statt ein Eintragungshindernis zu überwinden.",
                 level=2, concepts=["verkehrsgeltung", "entstehung_markenschutz"], norms=["§ 4 Nr. 2", "§ 6 Abs. 3"]),
            fall("k01b-3", "Die Weltmarke ohne deutsche Eintragung",
                 "Ein amerikanischer Sportartikelhersteller ist mit seinem Logo weltberühmt, hat es in Deutschland aber weder eingetragen noch je Ware nach Deutschland geliefert. Praktisch jeder Deutsche kennt das Logo.",
                 "Besteht in Deutschland dennoch Markenschutz?", True,
                 ["**Ja!** § 4 Nr. 3 gewährt Markenschutz für Zeichen, die im Inland **notorisch bekannt** im Sinne des Art. 6bis PVÜ sind. Weder Eintragung noch inländische Benutzung sind erforderlich.",
                  "Notorische Bekanntheit verlangt allerdings einen sehr hohen Bekanntheitsgrad, der über die „bekannte Marke“ des § 14 Abs. 2 Nr. 3 hinausgeht. Der Fall ist praktisch selten, in der Klausur aber beliebt."],
                 merke="Drei Wege zur Marke: Eintragung, Verkehrsgeltung, Notorietät (§ 4 Nr. 1 bis 3).",
                 level=2, concepts=["notorische_bekanntheit"], norms=["§ 4 Nr. 3", "§ 10"]),
            fall("k01b-4", "Wer war zuerst?",
                 "Anna hat „SOLARO“ am 3. Januar für Sonnencreme angemeldet, die Eintragung erfolgte im Juni. Ben hat „SOLARO“ für Sonnencreme am 10. Januar angemeldet, die Eintragung erfolgte bereits im April.",
                 "Hat Ben das ältere Recht, weil seine Marke früher eingetragen wurde?", False,
                 ["**Nein!** Für den Vorrang zwischen kollidierenden Rechten kommt es auf den **Zeitrang** an (§ 6 Abs. 1). Bei angemeldeten und eingetragenen Marken ist das der Anmeldetag (§ 6 Abs. 2), nicht der Tag der Eintragung.",
                  "Anna hat mit dem 3. Januar den besseren Zeitrang. Sie kann Bens Marke mit Widerspruch (§ 42) oder Nichtigkeitsantrag (§ 51) angreifen und ihm die Benutzung nach § 14 untersagen."],
                 merke="Prioritätsprinzip: Es zählt der Anmeldetag, nicht die Eintragung.",
                 concepts=["prioritaet"], norms=["§ 6"]),
            mc("k01b-5", "Schutzdauer",
               "Wie lange gilt der Schutz einer eingetragenen Marke und wie wird er verlängert?",
               ["20 Jahre ab Anmeldung, nicht verlängerbar", "10 Jahre ab Anmeldetag, beliebig oft um 10 Jahre verlängerbar", "10 Jahre ab Eintragung, einmal verlängerbar", "Unbegrenzt ohne Verlängerung"], 1,
               ["Die Schutzdauer beträgt **zehn Jahre ab dem Anmeldetag** und kann durch Zahlung der Verlängerungsgebühr beliebig oft um jeweils zehn Jahre verlängert werden (§ 47).",
                "Anders als Patent und Design kann eine Marke also **ewig** leben, solange sie verlängert und rechtserhaltend benutzt wird (§ 26)."],
               norms=["§ 47", "Art. 48 MarkenRL", "Art. 49 MarkenRL"], concepts=["entstehung_markenschutz", "schutzdauer"]),
        ]),
    ],
)
