# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k02", titel="Schutzfähigkeit und absolute Schutzhindernisse", untertitel="§§ 3, 7, 8 MarkenG: Was ins Register darf",
    farbe="#2F6B4F", icon="register",
    beschreibung="Markenfähigkeit, Formausschluss, Unterscheidungskraft, Freihaltebedürfnis, Bösgläubigkeit und die Verkehrsdurchsetzung als Rettungsanker.",
    kapitel=[
        dict(id="k02a", titel="Markenfähigkeit und Formausschluss (§ 3)", einheiten=[
            schema("k02a-0", "Prüfungsschema: Eintragungsfähigkeit", "schema_eintragungsfaehigkeit",
                   "Das DPMA prüft in dieser Reihenfolge. Merke dir vor allem: § 3 Abs. 2 ist nicht durch Verkehrsdurchsetzung überwindbar, § 8 Abs. 2 Nr. 1 bis 3 schon."),
            fall("k02a-1", "Die quadratische Schokolade",
                 "Ein Schokoladenhersteller hat die quadratische Verpackungsform seiner Tafeln als dreidimensionale Marke eingetragen. Ein Konkurrent beantragt die Löschung: Die Form verleihe der Ware ihren wesentlichen Wert, außerdem sei sie durch die Art der Ware bedingt.",
                 "Greift der Formausschluss des § 3 Abs. 2 Nr. 3 (wesentlicher Wert), weil Verbraucher die praktische quadratische Form schätzen?", False,
                 ["**Nein!** Der BGH hat die Ritter-Sport-Verpackung als Marke bestätigt (Quadratische Tafelschokoladenverpackung II). Eine Form verleiht der Ware nur dann einen wesentlichen Wert, wenn die **ästhetische Qualität der Form** die Kaufentscheidung maßgeblich bestimmt.",
                  "Dass Verbraucher die Form als Herkunftshinweis erkennen oder praktisch finden, ist kein „wesentlicher Wert“ im Sinne der Norm. Auch § 3 Abs. 2 Nr. 1 greift nicht: Schokolade muss nicht quadratisch sein.",
                  "Hintergrund des § 3 Abs. 2: Technische und ästhetische Lösungen gehören ins Patent- und Designrecht mit begrenzter Laufzeit, nicht in ein ewiges Markenmonopol."],
                 merke="§ 3 Abs. 2 sperrt drei Formen: warenbedingt, technisch erforderlich, wertverleihend. Keine Heilung durch Verkehrsdurchsetzung.",
                 level=2, concepts=["formausschluss", "formmarke"], norms=["§ 3 Abs. 2"], cases=["bgh_ritter_sport"]),
            fall("k02a-2", "Der Dübel mit Rippen",
                 "Ein Hersteller meldet die Form eines Bodendübels mit charakteristischen Rippen als Marke an. Die Rippen sorgen für besseren Halt im Boden. Es gäbe auch andere Formen, die denselben Halt erreichen.",
                 "Steht § 3 Abs. 2 Nr. 2 der Eintragung entgegen, obwohl alternative Formen dieselbe Wirkung erzielen könnten?", True,
                 ["**Ja, in der Tat!** Ein Zeichen ist ausgeschlossen, wenn alle wesentlichen Merkmale der Form zur Erreichung einer **technischen Wirkung** erforderlich sind. Es genügt, dass die Merkmale eine technische Funktion erfüllen; sie müssen nicht die einzige Möglichkeit sein (BGH Bodendübel, EuGH Philips/Remington).",
                  "Wäre es anders, könnte der Anmelder mit mehreren Formmarken sämtliche Alternativen sperren und so ein zeitlich unbegrenztes Technikmonopol erhalten."],
                 merke="Beim technischen Formausschluss zählt nicht, ob es Alternativen gibt, sondern ob die Form technisch funktioniert.",
                 level=2, concepts=["formausschluss"], norms=["§ 3 Abs. 2 Nr. 2"], cases=["bgh_bodenduebel", "eugh_philips_remington"]),
            fall("k02a-3", "Der variable Slogan",
                 "Ein Unternehmen möchte „ein Slogan, der jeweils den aktuellen Monat nennt“ als Marke schützen lassen, ohne die konkrete Wortfolge festzulegen.",
                 "Ist dieses „Zeichen“ markenfähig?", False,
                 ["**Nein!** Markenfähig ist nur ein Zeichen, das als **einheitlicher Gegenstand** bestimmbar ist. Variable Marken, mit denen Schutz für eine unbestimmte Zahl unterschiedlicher Erscheinungsformen beansprucht wird, fehlt bereits die Markenfähigkeit nach § 3 Abs. 1.",
                  "Zusätzlich fehlt die Darstellbarkeit im Register (§ 8 Abs. 1): Behörden und Publikum müssen den Schutzgegenstand klar und eindeutig bestimmen können."],
                 merke="Ein Zeichen, kein Konzept: Das Register schützt nur konkret bestimmte Zeichen.",
                 concepts=["markenfaehigkeit", "darstellbarkeit"], norms=["§ 3 Abs. 1", "§ 8 Abs. 1"]),
        ]),
        dict(id="k02b", titel="Unterscheidungskraft (§ 8 Abs. 2 Nr. 1)", einheiten=[
            intro("k02b-0", "Was Unterscheidungskraft bedeutet",
                  "Unterscheidungskraft ist die **konkrete** Eignung eines Zeichens, vom Verkehr als Herkunftshinweis für die beanspruchten Waren verstanden zu werden. Der Maßstab ist großzügig: **Jede noch so geringe** Unterscheidungskraft genügt. Sie fehlt bei beschreibenden Angaben, bei gebräuchlichen Wörtern, die immer nur als solche verstanden werden, und bei reinen Werbeaussagen. Maßgeblich ist der Durchschnittsverbraucher im Anmeldezeitpunkt, und zwar für jede Ware gesondert.",
                  concepts=["unterscheidungskraft", "durchschnittsverbraucher"], norms=["§ 8 Abs. 2 Nr. 1"]),
            fall("k02b-1", "„marktfrisch“ für Lebensmittel",
                 "Ein Lebensmittelhändler meldet „marktfrisch“ für Obst, Gemüse und Fleisch an.",
                 "Fehlt dem Zeichen für diese Waren die Unterscheidungskraft?", True,
                 ["**Ja!** Ein Wort mit einem für die Waren **im Vordergrund stehenden beschreibenden Begriffsinhalt** hat keine Unterscheidungskraft. „marktfrisch“ beschreibt die Beschaffenheit der Lebensmittel; der Verkehr sieht darin eine Qualitätsangabe, keinen Herkunftshinweis (BGH marktfrisch).",
                  "Zugleich besteht ein Freihaltebedürfnis nach § 8 Abs. 2 Nr. 2, weil Mitbewerber die Angabe ebenfalls brauchen. Beide Hindernisse sind gesondert zu prüfen, überschneiden sich aber häufig."],
                 merke="Beschreibend für die konkrete Ware = keine Unterscheidungskraft. Immer wareweise prüfen!",
                 concepts=["unterscheidungskraft", "freihaltebeduerfnis"], norms=["§ 8 Abs. 2 Nr. 1"], cases=["bgh_marktfrisch"]),
            fall("k02b-2", "„HOT“ für Ketchup und Massageöl",
                 "„HOT“ wird für Ketchup, Reinigungsmittel, Massageöle und Bekleidung angemeldet. Der Anmelder argumentiert: Das Wort sei mehrdeutig (heiß, scharf, angesagt) und deshalb unterscheidungskräftig.",
                 "Rettet die Mehrdeutigkeit die Unterscheidungskraft?", False,
                 ["**Nein!** Es genügt, dass das Zeichen **in einer seiner möglichen Bedeutungen** ein Merkmal der Waren beschreibt (BGH HOT). Für Ketchup beschreibt „hot“ die Schärfe, für Massageöl die wärmende Wirkung, für Bekleidung liegt eine bloße Anpreisung („angesagt“) nahe.",
                  "Mehrdeutigkeit begründet nur dann Unterscheidungskraft, wenn keine der naheliegenden Bedeutungen beschreibend ist und der Verkehr zum Nachdenken angeregt wird."],
                 merke="Eine beschreibende Bedeutung reicht. Mehrdeutigkeit hilft nur, wenn keine Deutung beschreibt.",
                 level=2, concepts=["unterscheidungskraft"], norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 2 Nr. 2"], cases=["bgh_hot"]),
            fall("k02b-3", "„for you“ für Nahrungsergänzung",
                 "Ein Hersteller meldet die Wortfolge „for you“ für Nahrungsergänzungsmittel und Kosmetik an.",
                 "Ist „for you“ unterscheidungskräftig, weil es die Waren nicht beschreibt?", False,
                 ["**Nein!** Unterscheidungskraft fehlt auch Zeichen, die der Verkehr nur als **werbliche Anpreisung** versteht. „for you“ („für dich“) ist eine allgemeine Kundenansprache ohne Herkunftshinweis (BGH for you).",
                  "Anders liegt es bei Wortfolgen, die originell, mehrdeutig oder interpretationsbedürftig sind (EuGH Vorsprung durch Technik) oder bei denen kein Werbebezug erkennbar ist (BGH OUI für Bekleidung)."],
                 merke="Nicht beschreibend heißt nicht automatisch unterscheidungskräftig: Reine Werbeslogans fallen auch durch.",
                 level=2, concepts=["unterscheidungskraft"], norms=["§ 8 Abs. 2 Nr. 1"], cases=["bgh_for_you", "bgh_oui", "bgh_link_economy"]),
            fall("k02b-4", "„#darferdas?“ auf T-Shirts",
                 "Das Zeichen „#darferdas?“ wird für Bekleidung angemeldet. Auf der Vorderseite eines T-Shirts würde es als Spruch wahrgenommen; im Einnähetikett dagegen als Marke. Beide Verwendungen sind in der Modebranche üblich.",
                 "Darf das DPMA die Unterscheidungskraft allein nach der wahrscheinlichsten Verwendung (Aufdruck vorn) beurteilen?", False,
                 ["**Nein!** Bei der Prüfung sind **alle praktisch bedeutsamen Verwendungsarten** in der Branche zu berücksichtigen. Nur wenn eine einzige Verwendungsart praktisch bedeutsam ist, darf die Prüfung darauf beschränkt werden (EuGH #darferdas?, BGH #darferdas? II).",
                  "Da in der Bekleidungsbranche auch die Kennzeichnung im Etikett praktisch bedeutsam ist und der Verkehr das Zeichen dort als Herkunftshinweis versteht, kann die Eintragung nicht schlechthin versagt werden."],
                 merke="Verwendungsformen: alle praktisch bedeutsamen, nicht nur die wahrscheinlichste.",
                 level=3, concepts=["verwendungsformen", "unterscheidungskraft"], norms=["§ 8 Abs. 2 Nr. 1"], cases=["eugh_darferdas", "bgh_darferdas_ii", "bgh_marlene_dietrich_ii"]),
            fall("k02b-5", "„Pippi Langstrumpf“ für ein Hotel",
                 "Ein Hotelbetreiber meldet „Pippi Langstrumpf“ für Beherbergungsdienstleistungen an. Das DPMA meint, der Verkehr denke sofort an die Romanfigur und ein kindgerechtes Hotel; das Zeichen sei daher beschreibend.",
                 "Fehlt „Pippi Langstrumpf“ für Hotels die Unterscheidungskraft?", False,
                 ["**Nein!** Der Name einer fiktiven Figur beschreibt Beherbergungsdienstleistungen nicht. Assoziationen, die der Verkehr von der Figur auf das Hotel überträgt, erzeugen allenfalls eine **beschreibende Konnotation**, nehmen dem Zeichen aber nicht die Eignung als Herkunftshinweis (BGH Pippi-Langstrumpf-Marke).",
                  "Anders wäre es nur bei einem engen beschreibenden Bezug, etwa „Pippi Langstrumpf“ für Kinderbücher über genau diese Figur."],
                 merke="„Sprechende“ Marken sind erlaubt: Ein Anklang an die Ware schadet nicht, nur ein enger beschreibender Bezug.",
                 level=2, concepts=["unterscheidungskraft"], norms=["§ 8 Abs. 2 Nr. 1"], cases=["bgh_pippi_langstrumpf"]),
            fall("k02b-6", "Die Pralinenkugel",
                 "Ein Hersteller meldet die Form einer runden, mit Nusssplittern besetzten Praline in goldener Folie als 3D-Marke für Pralinen an.",
                 "Hat die Form originäre Unterscheidungskraft, weil sie hübsch und aufwendig ist?", False,
                 ["**Nein!** Der Verkehr schließt aus der Form einer Ware gewöhnlich nicht auf ihre Herkunft, sondern sieht darin die Ware selbst. Originäre Unterscheidungskraft hat eine Warenform nur, wenn sie **erheblich von der Norm oder Branchenüblichkeit** abweicht (BGH ROCHER-Kugel).",
                  "Eine runde, nussbesetzte Praline in Folie bewegt sich im Rahmen des Üblichen. Der Weg ins Register führt hier nur über Verkehrsdurchsetzung (§ 8 Abs. 3), für die der BGH mindestens 50 % Zuordnung verlangt."],
                 merke="Warenformen: Unterscheidungskraft nur bei erheblicher Abweichung vom Branchenüblichen.",
                 level=2, concepts=["formmarke", "unterscheidungskraft", "verkehrsdurchsetzung"], norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 3"], cases=["bgh_rocher_kugel"]),
        ]),
        dict(id="k02c", titel="Freihaltebedürfnis, Bösgläubigkeit, Verkehrsdurchsetzung", einheiten=[
            fall("k02c-1", "„Black Friday“ für Elektronik",
                 "„Black Friday“ wurde 2013 als Wortmarke für Elektronikwaren und Werbedienstleistungen eingetragen. Damals war der Begriff in Deutschland noch wenig verbreitet. Ein Händler beantragt die Löschung wegen Freihaltebedürfnisses.",
                 "Kann ein Freihaltebedürfnis nach § 8 Abs. 2 Nr. 2 bestehen, obwohl die Angabe im Anmeldezeitpunkt noch kaum beschreibend verwendet wurde?", True,
                 ["**Ja!** § 8 Abs. 2 Nr. 2 erfasst Angaben, die zur Beschreibung von Merkmalen der Waren **dienen können**. Es genügt, dass im Anmeldezeitpunkt vernünftigerweise zu erwarten war, dass die Angabe künftig beschreibend verwendet wird (BGH Black Friday, EuGH Chiemsee).",
                  "„Black Friday“ bezeichnet den Zeitpunkt von Rabattaktionen und damit ein Merkmal von Werbedienstleistungen und Elektronikangeboten. Die Marke wurde insoweit gelöscht."],
                 merke="Freihaltebedürfnis auch für die Zukunft: „dienen können“, nicht „schon dienen“.",
                 level=2, concepts=["freihaltebeduerfnis", "nichtigkeit"], norms=["§ 8 Abs. 2 Nr. 2", "§ 50"], cases=["bgh_black_friday", "eugh_chiemsee"]),
            mc("k02c-2", "Nr. 1 oder Nr. 2?",
               "Was ist der eigentliche Schutzzweck des § 8 Abs. 2 Nr. 2 (Freihaltebedürfnis) im Unterschied zu Nr. 1?",
               ["Verbraucherschutz vor Irreführung", "Das Allgemeininteresse der Mitbewerber an der freien Verwendbarkeit beschreibender Angaben", "Der Schutz der Herkunftsfunktion", "Die Vermeidung von Doppeleintragungen"], 1,
               ["Nr. 2 schützt das **Allgemeininteresse der Mitbewerber**: Angaben über Art, Beschaffenheit, Menge, Bestimmung, Herkunft oder Zeit dürfen nicht monopolisiert werden. Nr. 1 schützt dagegen die Herkunftsfunktion aus Sicht des Verbrauchers.",
                "Praktisch fehlt jeder nach Nr. 2 beschreibenden Angabe auch die Unterscheidungskraft nach Nr. 1; umgekehrt gilt das nicht (Beispiel „for you“: nicht beschreibend, aber trotzdem ohne Unterscheidungskraft)."],
               concepts=["freihaltebeduerfnis", "unterscheidungskraft"], norms=["§ 8 Abs. 2 Nr. 2"]),
            fall("k02c-3", "Die Sperrmarke",
                 "Max erfährt, dass ein Start-up unter „NEBULA“ eine Software vertreibt, aber die Marke nicht angemeldet hat. Er meldet „NEBULA“ für Software an, ohne sie selbst benutzen zu wollen, und fordert vom Start-up 50.000 Euro für die Übertragung.",
                 "Kann die Marke wegen Bösgläubigkeit gelöscht werden?", True,
                 ["**Ja, in der Tat!** Bösgläubig handelt, wer ein Zeichen in Kenntnis eines **schutzwürdigen Besitzstands** eines Vorbenutzers ohne sachlichen Grund für gleiche Waren anmeldet, um diesen Besitzstand zu stören oder die Benutzung zu sperren (BGH EROS, GLÜCKSPILZ).",
                  "Die Absicht, die Marke nur als Druckmittel einzusetzen (Hinterhalts- oder Sperrmarke), zeigt, dass Max sie nicht zur Förderung des eigenen Absatzes will. Rechtsfolge: Nichtigkeit nach § 50 i.V.m. § 8 Abs. 2 Nr. 14.",
                  "Die bloße Kenntnis von der Vorbenutzung genügt allerdings nicht; hinzukommen müssen besondere Umstände wie hier die Behinderungsabsicht (BGH Ivadal)."],
                 merke="Bösgläubigkeit = Anmeldung als Waffe statt als Kennzeichen. Maßgeblicher Zeitpunkt: die Anmeldung.",
                 level=2, concepts=["boesglaeubigkeit"], norms=["§ 8 Abs. 2 Nr. 14", "§ 50"], cases=["bgh_eros", "bgh_glueckspilz", "bgh_ivadal"]),
            fall("k02c-4", "Das Gelb der Wörterbücher",
                 "Ein Verlag benutzt seit Jahrzehnten einen bestimmten Gelbton für zweisprachige Wörterbücher, stets zusammen mit seinem Namen. Eine Umfrage ergibt, dass 66 % der Befragten die Farbe dem Verlag zuordnen.",
                 "Kann die abstrakte Farbmarke Gelb trotz fehlender originärer Unterscheidungskraft eingetragen werden?", True,
                 ["**Ja!** Nach § 8 Abs. 3 stehen die Hindernisse der Nr. 1 bis 3 nicht entgegen, wenn sich die Marke infolge ihrer Benutzung **in den beteiligten Verkehrskreisen durchgesetzt** hat. Für Farbmarken verlangt der BGH regelmäßig einen Zuordnungsgrad von über 50 % (Langenscheidt-Gelb, Nivea-Blau).",
                  "Dass die Farbe immer zusammen mit dem Verlagsnamen benutzt wurde, schadet nicht, solange der Verkehr die Farbe selbst als Herkunftshinweis versteht."],
                 merke="Verkehrsdurchsetzung heilt Nr. 1 bis 3, nicht aber § 3 Abs. 2 oder Nr. 4 ff. Richtwert: über 50 %.",
                 level=2, concepts=["verkehrsdurchsetzung", "farbmarke"], norms=["§ 8 Abs. 3"], cases=["bgh_langenscheidt_gelb", "bgh_nivea_blau"]),
            fall("k02c-5", "Die Marke „test“",
                 "Eine Verbraucherorganisation hat „test“ als Wort-Bild-Marke für Testzeitschriften eingetragen. Im Löschungsverfahren ergibt eine Umfrage einen Zuordnungsgrad von 43 %.",
                 "Reicht das für die Verkehrsdurchsetzung einer glatt beschreibenden Angabe aus?", False,
                 ["**Nein!** „test“ beschreibt den Inhalt einer Testzeitschrift. Für die Verkehrsdurchsetzung ist ein Zuordnungsgrad von 43 % regelmäßig **nicht ausreichend** (BGH test). Bei glatt beschreibenden Angaben verlangt der BGH sogar eine deutlich über 50 % liegende Quote.",
                  "Maßgeblicher Zeitpunkt ist der Anmeldetag; im Löschungsverfahren muss die Durchsetzung zudem noch im Entscheidungszeitpunkt fortbestehen (§ 50 Abs. 2)."],
                 merke="Je beschreibender das Zeichen, desto höher die nötige Durchsetzungsquote.",
                 level=2, concepts=["verkehrsdurchsetzung"], norms=["§ 8 Abs. 3", "§ 50 Abs. 2"], cases=["bgh_test", "bgh_kinder_ii"]),
            mc("k02c-6", "Wer trägt die Feststellungslast im Löschungsverfahren?",
               "Ein Dritter beantragt die Löschung der eingetragenen Marke „smartbook“ wegen fehlender Unterscheidungskraft. Ob das Zeichen im Anmeldezeitpunkt beschreibend war, lässt sich nicht sicher klären. Was gilt?",
               ["Die Marke wird gelöscht, weil der Inhaber die Schutzfähigkeit beweisen muss", "Die Marke bleibt bestehen, weil der Antragsteller die Feststellungslast für das Schutzhindernis trägt", "Das DPMA entscheidet nach freiem Ermessen", "Die Marke wird zur Hälfte gelöscht"], 1,
               ["Im Nichtigkeitsverfahren nach § 50 trägt der **Antragsteller die Feststellungslast** für das Vorliegen des Schutzhindernisses im Anmeldezeitpunkt. Verbleibende Zweifel gehen zu seinen Lasten (BGH smartbook, Sparkassen-Rot).",
                "Die eingetragene Marke genießt also einen Bestandsschutz: Was einmal im Register steht, wird nur bei feststellbarem Mangel gelöscht."],
               level=2, concepts=["nichtigkeit", "absolute_schutzhindernisse"], norms=["§ 50"], cases=["bgh_smartbook", "bgh_sparkassen_rot"]),
        ]),
    ],
)
