# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k03", titel="Markenverletzung I: Aufbau und markenmäßige Benutzung", untertitel="§ 14 Abs. 2 MarkenG: Der Verletzungstatbestand",
    farbe="#8A2F1F", icon="verletzung",
    beschreibung="Das zentrale Klausurschema: Aktivlegitimation, geschäftlicher Verkehr, markenmäßige Benutzung, Doppelidentität und die Sonderfälle Keyword-Advertising und Modellbezeichnung.",
    kapitel=[
        dict(id="k03a", titel="Der Aufbau des Verletzungstatbestands", einheiten=[
            schema("k03a-0", "Prüfungsschema: Unterlassungsanspruch aus § 14", "schema_markenverletzung",
                   "Dieses Schema begleitet dich durch die Kurse 3 bis 6. Präge dir die Reihenfolge ein: Marke, Verletzungshandlung, Schranken, Rechtsfolge."),
            fall("k03a-1", "Der private Flohmarktverkauf",
                 "Studentin Sara verkauft auf einem Flohmarkt ihre alte, echte Designerjacke und drei selbstgenähte Taschen, auf die sie zum Spaß das Logo eines Luxuslabels gestickt hat.",
                 "Handelt Sara mit den Taschen im geschäftlichen Verkehr?", False,
                 ["**Nein!** Eine Benutzung im geschäftlichen Verkehr liegt vor, wenn sie im Zusammenhang mit einer auf wirtschaftlichen Vorteil gerichteten Tätigkeit erfolgt und nicht rein privat ist. Ein gelegentlicher Verkauf privater Gegenstände auf dem Flohmarkt ist **Privatbereich**.",
                  "Anders wäre es, wenn Sara regelmäßig, in größerem Umfang oder mit Neuware handelt. An das Merkmal werden zwar keine hohen Anforderungen gestellt, der rein private Bereich bleibt aber frei. Auch die Strafbarkeit nach § 143 setzt geschäftlichen Verkehr voraus."],
                 merke="Kein geschäftlicher Verkehr, keine Markenverletzung. Indizien für Geschäftlichkeit: Häufigkeit, Umfang, Neuware, Gewerbeanmeldung.",
                 concepts=["geschaeftlicher_verkehr"], norms=["§ 14 Abs. 2"], step="step:schema_markenverletzung.3.1"),
            fall("k03a-2", "Der Lizenznehmer klagt",
                 "Die Firma Nova ist Inhaberin der Marke „NOVA“. Sie hat der Firma Lux eine einfache Lizenz erteilt. Lux entdeckt Plagiate und will sofort selbst klagen. Nova antwortet nicht auf Lux' Anfrage.",
                 "Kann Lux als einfache Lizenznehmerin ohne Zustimmung von Nova Klage erheben?", False,
                 ["**Nein!** Der Lizenznehmer kann Klage wegen Verletzung der Marke **nur mit Zustimmung des Inhabers** erheben (§ 30 Abs. 3 S. 1). Eine Ausnahme gilt nur für den **ausschließlichen** Lizenznehmer: Er darf klagen, wenn der Inhaber nach förmlicher Aufforderung nicht innerhalb angemessener Frist selbst klagt (§ 30 Abs. 3 S. 2).",
                  "Lux kann aber einer Klage von Nova beitreten, um eigenen Schaden geltend zu machen (§ 30 Abs. 4)."],
                 merke="Aktivlegitimation: Inhaber (§ 28 Vermutung), Lizenznehmer nur mit Zustimmung, ausschließlicher Lizenznehmer nach Aufforderung.",
                 level=2, concepts=["aktivlegitimation", "lizenz"], norms=["§ 30 Abs. 3", "§ 28"], step="step:schema_markenverletzung.2.2"),
            fall("k03a-3", "Die Bindung an die Eintragung",
                 "Der Inhaber der eingetragenen Marke „SUPERSOFT“ für Toilettenpapier klagt gegen einen Konkurrenten. Dieser wendet ein, „supersoft“ sei glatt beschreibend und hätte nie eingetragen werden dürfen.",
                 "Darf das Verletzungsgericht die Klage abweisen, weil die Marke nicht schutzfähig ist?", False,
                 ["**Nein!** Das Verletzungsgericht ist an die **Eintragung gebunden**. Absolute Schutzhindernisse prüft es nicht; dafür ist das Nichtigkeitsverfahren vor dem DPMA zuständig (§§ 50, 53).",
                  "Der Beklagte kann einen Löschungsantrag stellen und die Aussetzung des Verletzungsprozesses anregen (§ 148 ZPO). Außerdem kann er sich auf § 23 Abs. 1 Nr. 2 berufen, wenn er „supersoft“ nur beschreibend benutzt. Die geringe Kennzeichnungskraft fließt zudem in die Verwechslungsgefahr ein."],
                 merke="Bindung an die Eintragung: Schutzfähigkeit wird im Register geklärt, nicht im Verletzungsprozess.",
                 level=2, concepts=["entstehung_markenschutz", "nichtigkeit", "schranke_23"], norms=["§ 4 Nr. 1", "§ 50"], cases=["bgh_langenscheidt_gelb", "bgh_sparkassen_rot"], step="step:schema_markenverletzung.2.1"),
        ]),
        dict(id="k03b", titel="Markenmäßige Benutzung", einheiten=[
            intro("k03b-0", "Das ungeschriebene Tatbestandsmerkmal",
                  "§ 14 Abs. 2 verbietet nicht jede Verwendung eines fremden Zeichens. Erforderlich ist eine **markenmäßige Benutzung**: Das Zeichen muss so benutzt werden, dass es die Funktionen der Marke, vor allem die Herkunftsfunktion, beeinträchtigt oder beeinträchtigen kann. Der Verkehr muss das Zeichen also als Hinweis auf die betriebliche Herkunft der Ware verstehen. Rein beschreibende, dekorative oder firmenmäßige Verwendungen scheiden aus. Die folgenden Fälle zeigen die Grenzlinie.",
                  concepts=["markenmaessige_benutzung", "herkunftsfunktion"], norms=["§ 14 Abs. 2"]),
            fall("k03b-1", "Der Modellbausatz",
                 "Ein Spielzeughersteller vertreibt originalgetreue Modellautos, auf deren Kühlergrill das eingetragene Logo des Autoherstellers (auch für Spielzeug eingetragen) abgebildet ist.",
                 "Verletzt die Abbildung des Logos die Spielzeugmarke des Autoherstellers?", False,
                 ["**Nein!** Der Verkehr versteht das Logo auf dem Modellauto nur als **originalgetreue Nachbildung** des Vorbilds, nicht als Hinweis auf die Herkunft des Spielzeugs (BGH Opel-Blitz II, EuGH Adam Opel).",
                  "Die Herkunftsfunktion der für Spielzeug eingetragenen Marke wird also nicht beeinträchtigt; es fehlt an der markenmäßigen Benutzung."],
                 merke="Abbildung als Teil der Wirklichkeit ist kein Herkunftshinweis.",
                 level=2, concepts=["markenmaessige_benutzung", "herkunftsfunktion"], norms=["§ 14 Abs. 2 Nr. 1"], cases=["bgh_opel_blitz_ii", "eugh_adam_opel"], step="step:schema_markenverletzung.3.4"),
            fall("k03b-2", "Der Frühstücks-Drink",
                 "Ein Molkereiunternehmen ist Inhaber der Marke „FRÜHSTÜCKS-DRINK“. Ein Konkurrent bewirbt sein Joghurtgetränk mit dem Text „der ideale Frühstücks-Drink für die ganze Familie“, unter seiner eigenen, deutlich hervorgehobenen Marke.",
                 "Benutzt der Konkurrent „Frühstücks-Drink“ markenmäßig?", False,
                 ["**Nein!** Eine markenmäßige Benutzung setzt voraus, dass das Zeichen im Rahmen des Produktabsatzes jedenfalls auch der **Unterscheidung der Waren** eines Unternehmens von denen anderer dient. Hier wird der Begriff rein **beschreibend** als Produktbezeichnung im Fließtext verwendet (BGH FRÜHSTÜCKS-DRINK II).",
                  "Der Verkehr entnimmt der Wendung keine Herkunftsangabe; die eigene Marke des Konkurrenten steht im Vordergrund. Es fehlt bereits am Tatbestand, § 23 muss gar nicht mehr geprüft werden."],
                 merke="Beschreibend im Fließtext = keine markenmäßige Benutzung.",
                 concepts=["markenmaessige_benutzung"], norms=["§ 14 Abs. 2 Nr. 2"], cases=["bgh_fruehstuecks_drink_ii"], step="step:schema_markenverletzung.3.4"),
            fall("k03b-3", "Die Hose „Sam“",
                 "Ein Online-Händler bietet Hosen an. Im Fließtext des Angebots steht klein „Modell: Sam“, während die Herstellermarke groß in der Überschrift erscheint. „SAM“ ist als Wortmarke für Bekleidung eingetragen, aber nicht bekannt.",
                 "Liegt in der Nennung „Modell: Sam“ eine markenmäßige Benutzung?", False,
                 ["**Nein, jedenfalls nicht ohne weiteres!** Ob eine Modellbezeichnung als Herkunftshinweis verstanden wird, hängt von den **Kennzeichnungsgewohnheiten der Branche** und der konkreten Präsentation ab (BGH SAM).",
                  "Bei einer unauffälligen Nennung nur im Bestelltext eines Online-Angebots, ohne Bekanntheit der Marke und mit prominenter Herstellermarke, sieht der Verkehr im Vornamen nur eine Bestellhilfe. Anders bei Anbringung auf der Ware oder dem Etikett: Dort liegt regelmäßig ein Herkunftshinweis vor."],
                 merke="Modellbezeichnungen: Etikett und Ware sprechen für Herkunftshinweis, versteckter Bestelltext dagegen.",
                 level=3, concepts=["markenmaessige_benutzung"], norms=["§ 14 Abs. 2 Nr. 1"], cases=["bgh_sam", "bgh_damen_hose_mo"], step="step:schema_markenverletzung.3.4"),
            fall("k03b-4", "Die Damen-Hose „MO“",
                 "Ein Händler überschreibt sein Angebot mit „Bench Damen Hose MO“. „MO“ ist als Marke für Bekleidung eingetragen. Der Händler meint, wegen der bekannten Herstellermarke „Bench“ könne „MO“ kein Herkunftshinweis sein.",
                 "Schließt die bekannte Herstellermarke aus, dass „MO“ markenmäßig benutzt wird?", False,
                 ["**Nein!** Der Verkehr ist in der Modebranche an **Zweitmarken** neben der Herstellermarke gewöhnt. Erscheint die Modellbezeichnung in der Angebotsüberschrift neben der Herstellermarke, kann sie als eigenständiger Herkunftshinweis verstanden werden (BGH Damen Hose MO).",
                  "Entscheidend ist die Gesamtgestaltung: Position, Größe und Nähe zur Herstellermarke. Das OLG bejahte im Anschluss die markenmäßige Benutzung."],
                 merke="Eine bekannte Herstellermarke schließt eine markenmäßig benutzte Zweitmarke nicht aus.",
                 level=3, concepts=["markenmaessige_benutzung"], norms=["§ 14 Abs. 2 Nr. 2"], cases=["bgh_damen_hose_mo"]),
            fall("k03b-5", "Der Firmenname auf der Rechnung",
                 "Die „Céline GmbH“ verkauft Bekleidung und verwendet ihren Firmennamen nur auf Rechnungen, dem Ladenschild und im Impressum, nie auf der Ware. Inhaberin der Bekleidungsmarke „CÉLINE“ ist ein anderes Unternehmen.",
                 "Ist die bloße Verwendung als Firmenname eine Benutzung „für Waren“ im Sinne des § 14 Abs. 2?", False,
                 ["**Nein!** Die Benutzung einer Firma dient der Bezeichnung des Unternehmens, nicht der Unterscheidung von Waren. Sie ist nur dann eine Benutzung „für Waren“, wenn das Zeichen so verwendet wird, dass der Verkehr eine **Verbindung zwischen Firma und Ware** herstellt, etwa durch Anbringung auf der Ware oder in der Produktwerbung (EuGH Céline).",
                  "Gegen rein firmenmäßigen Gebrauch schützt § 15, wenn der Kläger ein Unternehmenskennzeichen hat, sowie das UWG. Seit dem MaMoG stellt § 14 Abs. 3 Nr. 5 klar, dass die Verwendung als Handelsname eine Verletzungshandlung sein kann, sofern sie „für Waren“ erfolgt; Vorbild ist Art. 10 Abs. 3 lit. d MarkenRL."],
                 merke="Firma ≠ Marke. Firmenmäßiger Gebrauch verletzt § 14 nur mit Warenbezug.",
                 level=2, concepts=["firmenmaessiger_gebrauch", "markenmaessige_benutzung"], norms=["§ 14 Abs. 3 Nr. 5", "§ 15", "Art. 10 MarkenRL"], cases=["eugh_celine"]),
        ]),
        dict(id="k03c", titel="Doppelidentität und Keyword-Advertising", einheiten=[
            fall("k03c-1", "Die Fälschung",
                 "Ein Händler verkauft Sneaker mit dem identischen Logo eines Sportartikelherstellers. Die Schuhe sind Fälschungen, allerdings von so guter Qualität, dass Kunden keinen Unterschied bemerken.",
                 "Muss der Markeninhaber eine Verwechslungsgefahr nachweisen?", False,
                 ["**Nein!** Bei Identität des Zeichens und Identität der Waren gilt der **absolute Schutz** des § 14 Abs. 2 Nr. 1 (Doppelidentität). Eine Verwechslungsgefahr muss nicht festgestellt werden.",
                  "Erforderlich bleibt eine Beeinträchtigung einer Markenfunktion; bei Fälschungen ist die Herkunftsfunktion offensichtlich betroffen. Nach dem EuGH genügt bei Nr. 1 die Beeinträchtigung jeder Funktion, auch der Werbe- oder Investitionsfunktion (L'Oréal/Bellure). § 14 Abs. 2 Nr. 1 setzt Art. 10 Abs. 2 lit. a MarkenRL um; Erwägungsgrund 16 nennt den Schutz bei Doppelidentität ausdrücklich „absolut“."],
                 merke="Identisch + identisch = Nr. 1. Keine Verwechslungsprüfung, aber Funktionsbeeinträchtigung.",
                 concepts=["doppelidentitaet", "markenfunktionen"], norms=["§ 14 Abs. 2 Nr. 1", "Art. 10 MarkenRL"], cases=["eugh_loreal_bellure"], step="step:schema_markenverletzung.3.5.1"),
            fall("k03c-2", "Die AdWords-Anzeige",
                 "Ein Erotikversand bucht die fremde Marke „bananabay“ als Keyword. Bei Google erscheint seine Anzeige im deutlich abgesetzten Anzeigenblock; sie enthält weder das Wort „bananabay“ noch einen Hinweis auf den Markeninhaber, und die Domain lautet „eis.de“.",
                 "Verletzt die Keyword-Buchung die Marke „bananabay“?", False,
                 ["**Nein!** Das Keyword wird zwar im geschäftlichen Verkehr für Waren benutzt (EuGH Google France). Die **Herkunftsfunktion** ist aber nur beeinträchtigt, wenn ein normal informierter Internetnutzer nicht oder nur schwer erkennen kann, ob die beworbenen Waren vom Markeninhaber oder einem Dritten stammen.",
                  "Erscheint die Anzeige in einem abgesetzten Werbeblock, enthält sie die Marke nicht und weist die Domain auf ein anderes Unternehmen hin, ist die Herkunftsfunktion regelmäßig nicht beeinträchtigt (BGH Bananabay II, MOST-Pralinen)."],
                 merke="Keyword-Advertising ist erlaubt, wenn die Anzeige über die fremde Herkunft nicht im Unklaren lässt.",
                 level=2, concepts=["keyword_advertising", "herkunftsfunktion"], norms=["§ 14 Abs. 2 Nr. 1"], cases=["eugh_google_france", "bgh_bananabay_ii", "bgh_most_pralinen"]),
            fall("k03c-3", "Die Blumen-Anzeige",
                 "Ein Blumenversand bucht „Fleurop“ als Keyword. Der Verkehr weiß, dass Fleurop über ein Netz von Partnerfloristen arbeitet. Die Anzeige ist abgesetzt und enthält die Marke nicht; sie stellt aber auch nicht klar, dass der Werbende kein Fleurop-Partner ist.",
                 "Liegt hier ausnahmsweise eine Beeinträchtigung der Herkunftsfunktion vor?", True,
                 ["**Ja!** Weiß der Verkehr, dass der Markeninhaber sein Geschäft über ein Netz **wirtschaftlich verbundener Partner** betreibt, liegt die Vermutung nahe, auch der Werbende gehöre dazu. Dann ist die Herkunftsfunktion beeinträchtigt, wenn die Anzeige eine solche Verbindung nicht ausschließt (BGH Fleurop).",
                  "Die Bananabay-Grundsätze gelten also nicht ausnahmslos; maßgeblich sind die Verkehrsvorstellungen über das konkrete Vertriebssystem."],
                 merke="Ausnahme Fleurop: Bei bekannten Partnernetzen muss die Anzeige die fehlende Verbindung klarstellen.",
                 level=3, concepts=["keyword_advertising"], norms=["§ 14 Abs. 2 Nr. 1"], cases=["bgh_fleurop"]),
            fall("k03c-4", "Amazon und die Fahrradtaschen",
                 "Amazon schaltet Google-Anzeigen mit dem Text „Ortlieb Fahrradtasche“, die auf eine Amazon-Angebotsliste verlinken. Dort erscheinen neben Ortlieb-Taschen auch Taschen anderer Hersteller. Ortlieb verkauft selbst nicht über Amazon.",
                 "Verletzt diese Werbung die Marke „ORTLIEB“?", True,
                 ["**Ja, in der Tat!** Der Nutzer erwartet aufgrund der Anzeige „Ortlieb Fahrradtasche“ **ausschließlich Ortlieb-Produkte**. Führt die Anzeige zu einer Liste mit gemischten Angeboten, wird die Werbewirkung der Marke zu Drittprodukten umgeleitet; die Anzeige ist irreführend und verletzt die Marke (BGH ORTLIEB II).",
                  "Anders bei der plattforminternen Suche: Wer bei Amazon „Ortlieb“ eingibt, rechnet mit Alternativangeboten in der Trefferliste (BGH ORTLIEB I)."],
                 merke="Externe Anzeige mit Markennamen = Erwartung nur dieser Marke. Interne Suche = Alternativen erwartet.",
                 level=3, concepts=["keyword_advertising"], norms=["§ 14 Abs. 2 Nr. 1", "§ 14 Abs. 5"], cases=["bgh_ortlieb_ii", "bgh_ortlieb_i"]),
            fall("k03c-5", "Die satirische Postkarte",
                 "Ein Verlag vertreibt eine lilafarbene Postkarte mit dem Text „Über allen Wipfeln ist Ruh, irgendwo blökt eine Kuh. Muh! Rainer Maria Milka“. Lila und „Milka“ sind bekannte Marken.",
                 "Benutzt der Verlag die Marken markenmäßig, obwohl es sich um Satire handelt?", True,
                 ["**Ja!** Der Verkehr erkennt die Farbe Lila und das Wort „Milka“ auf der Postkarte als Anspielung auf die bekannten Marken; die Zeichen werden **gedanklich verknüpft**. Für den Bekanntheitsschutz nach § 14 Abs. 2 Nr. 3 genügt das, eine Beeinträchtigung der Herkunftsfunktion ist nicht nötig (BGH Lila-Postkarte).",
                  "Der Verlag gewinnt den Fall trotzdem: Die Ausnutzung erfolgt nicht „ohne rechtfertigenden Grund in unlauterer Weise“, weil die **Kunstfreiheit** (Art. 5 Abs. 3 GG) überwiegt und die Marke nicht herabgesetzt wird. Dazu mehr in Kurs 5."],
                 merke="Beim Bekanntheitsschutz reicht die gedankliche Verknüpfung; die Kunstfreiheit greift erst bei der Unlauterkeit.",
                 level=3, concepts=["markenmaessige_benutzung", "bekannte_marke", "unlauterkeit"], norms=["§ 14 Abs. 2 Nr. 3"], cases=["bgh_lila_postkarte"]),
        ]),
    ],
)
