# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k04", titel="Markenverletzung II: Verwechslungsgefahr", untertitel="§ 14 Abs. 2 Nr. 2 MarkenG: Der Kern jeder Markenklausur",
    farbe="#2B5B8A", icon="waage",
    beschreibung="Warenähnlichkeit, Kennzeichnungskraft, Zeichenähnlichkeit und ihre Wechselwirkung. Prägetheorie, selbständig kennzeichnende Stellung und die Arten der Verwechslungsgefahr.",
    kapitel=[
        dict(id="k04a", titel="Die drei Faktoren und ihre Wechselwirkung", einheiten=[
            schema("k04a-0", "Prüfungsschema: Verwechslungsgefahr", "schema_verwechslungsgefahr",
                   "Die Reihenfolge Warenähnlichkeit, Kennzeichnungskraft, Zeichenähnlichkeit, Gesamtabwägung solltest du auswendig können."),
            fall("k04a-1", "Bier und Snacks",
                 "Die Marke „DESPERADO“ ist für Bier eingetragen. Ein Konkurrent meldet „DESPERADOS“ für Knabbergebäck an. Der Inhaber argumentiert: Bier und Snacks würden zusammen konsumiert und ergänzten sich funktionell.",
                 "Genügt die funktionelle Ergänzung, um Warenähnlichkeit zu bejahen?", False,
                 ["**Nein!** Waren sind ähnlich, wenn sie unter Berücksichtigung aller Faktoren (Art, Verwendungszweck, Nutzung, Herstellungsstätten, Vertriebswege, Konkurrenz- oder Ergänzungsverhältnis) so enge Berührungspunkte aufweisen, dass der Verkehr bei identischer Kennzeichnung eine **gemeinsame betriebliche Herkunft** annehmen könnte.",
                  "Der Gesichtspunkt der funktionellen Ergänzung darf die übrigen Faktoren nicht verdrängen (BGH DESPERADOS/DESPERADO). Bier und Snacks stammen aus verschiedenen Betrieben, haben verschiedene Beschaffenheit und werden nur zufällig zusammen konsumiert."],
                 merke="Warenähnlichkeit fragt: Würde der Verkehr bei gleicher Marke denselben Hersteller vermuten?",
                 level=2, concepts=["warenaehnlichkeit"], norms=["§ 9 Abs. 1 Nr. 2", "§ 14 Abs. 2 Nr. 2"], cases=["bgh_desperados", "eugh_canon"], step="step:schema_verwechslungsgefahr.2"),
            fall("k04a-2", "„Kinder“ für Schokolade",
                 "Die Marke „Kinder“ ist für Süßwaren eingetragen. Sie wurde nur aufgrund von Verkehrsdurchsetzung eingetragen, da sie die Zielgruppe beschreibt. Der Inhaber macht gegen „Kinderzeit“ eine gesteigerte Kennzeichnungskraft geltend, weil die Marke sehr bekannt sei.",
                 "Hat „Kinder“ automatisch gesteigerte Kennzeichnungskraft, weil die Marke bekannt ist?", False,
                 ["**Nein!** Eine glatt beschreibende Angabe, die erst durch Verkehrsdurchsetzung eingetragen wurde, hat regelmäßig nur **durchschnittliche** Kennzeichnungskraft (BGH Kinder II). Die Bekanntheit war nötig, um überhaupt ins Register zu kommen; sie führt nicht zusätzlich zu einem erweiterten Schutzbereich.",
                  "Gesteigerte Kennzeichnungskraft setzt voraus, dass die Bekanntheit über das für die Durchsetzung nötige Maß deutlich hinausgeht. Zudem bleibt der Schutz auf die konkrete durchgesetzte Form beschränkt."],
                 merke="Verkehrsdurchsetzung hebt das Zeichen auf Normalniveau, nicht darüber.",
                 level=2, concepts=["kennzeichnungskraft", "verkehrsdurchsetzung"], norms=["§ 14 Abs. 2 Nr. 2"], cases=["bgh_kinder_ii"], step="step:schema_verwechslungsgefahr.3"),
            mc("k04a-3", "Die Skala der Kennzeichnungskraft",
               "Welche Abstufungen der Kennzeichnungskraft unterscheidet der BGH seit „Culinaria/Villa Culinaria“?",
               ["Schwach, normal, stark", "Sehr gering, gering, durchschnittlich, erhöht, sehr hoch", "Vorhanden oder nicht vorhanden", "Beschreibend, suggestiv, willkürlich, fantasievoll"], 1,
               ["Der BGH unterscheidet **fünf Grade**: sehr geringe, geringe (unterdurchschnittliche), durchschnittliche (normale), erhöhte (überdurchschnittliche) und sehr hohe Kennzeichnungskraft.",
                "Ausgangspunkt ist die originäre Kennzeichnungskraft (Phantasiewort: durchschnittlich; beschreibende Anklänge: geringer). Steigerung durch intensive Benutzung, Schwächung durch Drittzeichen im Ähnlichkeitsbereich."],
               concepts=["kennzeichnungskraft"], cases=["bgh_culinaria"]),
            fall("k04a-4", "Die Wechselwirkung",
                 "Die Marke „CANON“ (Kameras, hohe Kennzeichnungskraft) kollidiert mit „CANNON“ für Videokassetten. Die Zeichen sind klanglich identisch, die Waren nur entfernt ähnlich.",
                 "Kann eine hohe Kennzeichnungskraft und Zeichenähnlichkeit eine geringe Warenähnlichkeit ausgleichen?", True,
                 ["**Ja, in der Tat!** Nach der **Wechselwirkungslehre** kann ein geringerer Grad eines Faktors durch einen höheren Grad eines anderen ausgeglichen werden (EuGH Canon). Bei klanglicher Identität und hoher Kennzeichnungskraft reicht schon eine entfernte Warenähnlichkeit.",
                  "Grenze: Absolute Unähnlichkeit der Waren oder der Zeichen lässt sich nicht kompensieren. Dann kommt nur der Bekanntheitsschutz (§ 14 Abs. 2 Nr. 3) in Betracht."],
                 merke="Wechselwirkung: drei Schieberegler, aber keiner darf auf null stehen.",
                 concepts=["wechselwirkung", "kennzeichnungskraft"], norms=["§ 14 Abs. 2 Nr. 2"], cases=["eugh_canon", "eugh_lloyd"], step="step:schema_verwechslungsgefahr.5"),
            fall("k04a-5", "Ärzte und Patienten",
                 "Die Arzneimittelmarken „Maalox“ und „Melox-GRY“ stehen sich gegenüber. Fachkreise (Ärzte, Apotheker) unterscheiden die Zeichen sicher, Endverbraucher könnten sie verwechseln.",
                 "Genügt es für die Verwechslungsgefahr, dass sie bei einer der beiden Verkehrsgruppen besteht?", True,
                 ["**Ja!** Setzen sich die angesprochenen Verkehrskreise aus mehreren Gruppen zusammen, genügt es, dass die Verwechslungsgefahr bei **einer** Gruppe besteht (BGH Maalox/Melox-GRY).",
                  "Im konkreten Fall verneinte der BGH die Verwechslungsgefahr allerdings, weil die Zeichen klanglich („Maa-lox“ gegen „Me-lox-GRY“) und schriftbildlich hinreichend verschieden sind und der Bestandteil „GRY“ den Gesamteindruck mitprägt."],
                 merke="Gespaltene Verkehrsauffassung: Verwechslungsgefahr bei einer Gruppe reicht.",
                 level=2, concepts=["durchschnittsverbraucher", "zeichenaehnlichkeit"], norms=["§ 9 Abs. 1 Nr. 2"], cases=["bgh_maalox", "eugh_lloyd"], step="step:schema_verwechslungsgefahr.1"),
        ]),
        dict(id="k04b", titel="Zeichenähnlichkeit: Gesamteindruck, Prägung, selbständige Stellung", einheiten=[
            fall("k04b-1", "Die springende Raubkatze",
                 "Die Wort-Bild-Marke eines Sportartikelherstellers zeigt eine springende Raubkatze neben dem Firmennamen. Ein Konkurrent verwendet eine ähnliche springende Raubkatze ohne Wort.",
                 "Darf beim Zeichenvergleich allein auf den Bildbestandteil abgestellt werden?", True,
                 ["**Ja, wenn er den Gesamteindruck prägt!** Maßgeblich ist zwar der Gesamteindruck des Zeichens. Ein einzelner Bestandteil kann den Gesamteindruck aber **prägen**, wenn die übrigen Bestandteile für den Verkehr zurücktreten und ihn nicht mitbestimmen (BGH Springende Raubkatze, Prägetheorie).",
                  "Ein rein beschreibender Bestandteil prägt nie. Bei Wort-Bild-Marken orientiert sich der Verkehr im Regelfall am Wort; ein einprägsames Bild kann aber ebenso prägen."],
                 merke="Prägetheorie: Der Vergleich erfolgt mit dem Bestandteil, der im Erinnerungsbild des Verkehrs übrig bleibt.",
                 level=2, concepts=["praegetheorie", "gesamteindruck"], norms=["§ 9 Abs. 1 Nr. 2"], cases=["bgh_springende_raubkatze", "eugh_sabel_puma"], step="step:schema_verwechslungsgefahr.4.2"),
            fall("k04b-2", "THOMSON LIFE",
                 "Medion ist Inhaberin der Marke „LIFE“ für Unterhaltungselektronik. Thomson vertreibt Fernseher unter „THOMSON LIFE“. „THOMSON“ ist ein bekannter Herstellername und prägt das Gesamtzeichen.",
                 "Kann Verwechslungsgefahr bestehen, obwohl „LIFE“ das Gesamtzeichen „THOMSON LIFE“ nicht prägt?", True,
                 ["**Ja!** Wird eine ältere Marke in ein zusammengesetztes jüngeres Zeichen übernommen und behält sie dort eine **selbständig kennzeichnende Stellung**, kann der Verkehr annehmen, die Waren stammten aus wirtschaftlich verbundenen Unternehmen (EuGH THOMSON LIFE).",
                  "Die Prägetheorie ist damit nicht der einzige Weg zur Verwechslungsgefahr. Der BGH betont aber: Die selbständig kennzeichnende Stellung ist die **Ausnahme** und bedarf besonderer Umstände, typischerweise die Kombination einer fremden Marke mit der eigenen Unternehmensbezeichnung (Culinaria/Villa Culinaria)."],
                 merke="Prägung = ein Teil ist das Ganze. Selbständig kennzeichnende Stellung = ein Teil bleibt erkennbar fremd.",
                 level=3, concepts=["selbstaendig_kennzeichnende_stellung", "praegetheorie"], norms=["§ 14 Abs. 2 Nr. 2"], cases=["eugh_thomson_life", "bgh_culinaria", "bgh_interconnect"], step="step:schema_verwechslungsgefahr.4.4"),
            fall("k04b-3", "METRO gegen METROBUS",
                 "Der Handelskonzern METRO klagt gegen Verkehrsbetriebe, die ihre Schnellbuslinien „MetroBus“ nennen. „METRO“ ist für zahlreiche Dienstleistungen eingetragen und bekannt.",
                 "Prägt „Metro“ das Zeichen „MetroBus“, sodass Verwechslungsgefahr besteht?", False,
                 ["**Nein!** Im Zusammenhang mit Verkehrsdienstleistungen versteht der Verkehr „Metro“ in „MetroBus“ als **beschreibenden Hinweis** auf ein städtisches Verkehrsmittel (wie „Metro“ = U-Bahn). Ein beschreibend verstandener Bestandteil prägt nicht und hat auch keine selbständig kennzeichnende Stellung (BGH METROBUS).",
                  "Auch der Bekanntheitsschutz scheiterte: Wer „Metro“ als Sachangabe versteht, verknüpft das Zeichen nicht gedanklich mit dem Handelskonzern."],
                 merke="Ein Bestandteil, der in der konkreten Kombination beschreibend wirkt, verliert seine Kennzeichnungskraft.",
                 level=2, concepts=["praegetheorie", "gedankliche_verknuepfung"], norms=["§ 14 Abs. 2 Nr. 2", "§ 14 Abs. 2 Nr. 3"], cases=["bgh_metrobus"]),
            fall("k04b-4", "Goldbären gegen Schokoteddy",
                 "Haribo ist Inhaberin der Wortmarke „Goldbären“ für Süßwaren. Lindt vertreibt einen in Goldfolie verpackten Schokoladenbären mit rotem Halsband. Bild- oder Klangähnlichkeit scheidet naturgemäß aus.",
                 "Kann zwischen einer Wortmarke und einer dreidimensionalen Produktgestaltung Zeichenähnlichkeit bestehen?", True,
                 ["**Ja, aber nur begrifflich!** Beim Vergleich einer Wortmarke mit einer Produktform kommt nur die **Ähnlichkeit im Sinngehalt** in Betracht. Sie setzt voraus, dass die Wortmarke aus Sicht des Verkehrs die naheliegende, ungezwungene und erschöpfende Bezeichnung der Gestaltung ist (BGH Goldbären).",
                  "Diesen strengen Maßstab verfehlte Haribo: Der Lindt-Teddy lässt sich ebenso gut als „Teddy“ oder „Schokobär“ bezeichnen. Sonst könnte eine Wortmarke ganze Produktformen monopolisieren."],
                 merke="Wort gegen Form: nur begriffliche Ähnlichkeit, und die muss zwingend sein.",
                 level=3, concepts=["zeichenaehnlichkeit"], norms=["§ 14 Abs. 2 Nr. 2", "§ 14 Abs. 2 Nr. 3"], cases=["bgh_goldbaeren"], step="step:schema_verwechslungsgefahr.4.3"),
            fall("k04b-5", "Das Krokodil",
                 "Lacoste ist Inhaberin der Bildmarke eines Krokodils für Bekleidung (hohe Kennzeichnungskraft). Ein Konkurrent meldet ein anders gezeichnetes Krokodil („coccodrillo“) für Bekleidung an.",
                 "Kann Verwechslungsgefahr allein aus der Übereinstimmung im Bedeutungsgehalt (beide zeigen ein Krokodil) folgen?", True,
                 ["**Ja!** Bei Bildmarken kann eine Verwechslungsgefahr auf der **Übereinstimmung im Bedeutungsgehalt** beruhen, wenn die ältere Marke hohe Kennzeichnungskraft besitzt (BGH coccodrillo). Der Verkehr merkt sich „das Krokodil“, nicht die Details der Zeichnung.",
                  "Die gesteigerte Kennzeichnungskraft erweitert den Schutzbereich auch auf abweichend gestaltete Motive desselben Sinngehalts."],
                 merke="Hohe Kennzeichnungskraft macht das Motiv schutzfähig, nicht nur die konkrete Zeichnung.",
                 level=2, concepts=["zeichenaehnlichkeit", "kennzeichnungskraft"], norms=["§ 9 Abs. 1 Nr. 2"], cases=["bgh_lacoste_krokodil"]),
        ]),
        dict(id="k04c", titel="Arten der Verwechslungsgefahr", einheiten=[
            mc("k04c-1", "Drei Arten",
               "Der Verkehr erkennt, dass „Volks-Inspektion“ nicht von Volkswagen stammt, glaubt aber, es handle sich um eine lizenzierte Partnerwerkstatt. Welche Art der Verwechslungsgefahr ist das?",
               ["Unmittelbare Verwechslungsgefahr", "Mittelbare Verwechslungsgefahr (Serienzeichen)", "Verwechslungsgefahr im weiteren Sinne", "Keine Verwechslungsgefahr, sondern nur Assoziation"], 2,
               ["Bei der **Verwechslungsgefahr im weiteren Sinne** erkennt der Verkehr die Unterschiede und die verschiedenen Unternehmen, nimmt aber irrig **wirtschaftliche oder organisatorische Verbindungen** (Lizenz, Konzern) an.",
                "Unmittelbar: Zeichen werden verwechselt. Mittelbar: Zeichen werden unterschieden, aber wegen eines gemeinsamen Stammbestandteils demselben Unternehmen zugeordnet (Serienzeichen). Die bloße gedankliche Assoziation ohne Herkunftsvorstellung genügt nicht (EuGH SABEL/Puma)."],
               level=2, concepts=["verwechslungsgefahr_weiterer_sinn", "serienmarke"], cases=["bgh_volkswagen_volksinspektion", "eugh_sabel_puma"], step="step:schema_verwechslungsgefahr.6"),
            fall("k04c-2", "Sixtyseven by Mustang",
                 "Die Marke „MUSTANG“ ist für Bekleidung eingetragen und zugleich Unternehmenskennzeichen. Ein Konkurrent vertreibt Jeans unter „Sixtyseven by Mustang Bekleidung“.",
                 "Kann eine Verwechslungsgefahr im weiteren Sinne bestehen, obwohl „Sixtyseven“ das Zeichen prägt?", True,
                 ["**Ja!** „Mustang“ behält in dem zusammengesetzten Zeichen eine **selbständig kennzeichnende Stellung**. Da „MUSTANG“ zugleich Unternehmenskennzeichen des Klägers ist, liegt für den Verkehr die Annahme nahe, „Sixtyseven“ sei eine Zweitmarke aus dem Hause Mustang (BGH Mustang).",
                  "Die Verwechslungsgefahr im weiteren Sinne bleibt Ausnahme: Sie setzt besondere Umstände voraus, etwa dass das ältere Zeichen als Unternehmenskennzeichen bekannt ist."],
                 merke="„by“-Kombinationen sind der Klassiker der Verwechslungsgefahr im weiteren Sinne.",
                 level=3, concepts=["verwechslungsgefahr_weiterer_sinn", "selbstaendig_kennzeichnende_stellung"], norms=["§ 14 Abs. 2 Nr. 2", "§ 15"], cases=["bgh_mustang", "bgh_interconnect"]),
            fall("k04c-3", "Ein einziges Zeichen ist keine Serie",
                 "Die Inhaberin der Marke „Sun-Flow“ behauptet, „Sun-Boost“ eines Konkurrenten füge sich in ihre Markenserie mit dem Stamm „Sun-“ ein. Tatsächlich benutzt sie nur „Sun-Flow“.",
                 "Liegt eine mittelbare Verwechslungsgefahr unter dem Gesichtspunkt des Serienzeichens vor?", False,
                 ["**Nein!** Mittelbare Verwechslungsgefahr setzt voraus, dass der Verkehr den gemeinsamen Bestandteil als **Stamm einer benutzten Zeichenserie** kennt und ihm Hinweischarakter auf den Inhaber beimisst. Eine einzige Marke bildet keine Serie.",
                  "Außerdem muss der Stammbestandteil kennzeichnungskräftig sein; „Sun-“ hat für Sonnenprodukte beschreibende Anklänge."],
                 merke="Serienzeichen: mehrere benutzte Marken mit kennzeichnungskräftigem Stamm.",
                 level=2, concepts=["serienmarke", "verwechslungsgefahr_weiterer_sinn"], norms=["§ 14 Abs. 2 Nr. 2"], cases=["bgh_volkswagen_volksinspektion"]),
        ]),
    ],
)
