# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k05", gebiet="markeng", titel="Markenverletzung III: Bekanntheitsschutz", untertitel="§ 14 Abs. 2 Nr. 3 und § 9 Abs. 1 Nr. 3 MarkenG",
    farbe="#c9900a", icon="stern",
    beschreibung="Wann ist eine Marke bekannt, was ist die gedankliche Verknüpfung, welche vier Eingriffe gibt es und wann fehlt der rechtfertigende Grund. Plus: die bekannte Marke im Register.",
    kapitel=[
        dict(id="k05a", titel="Bekanntheit und gedankliche Verknüpfung", einheiten=[
            schema("k05a-0", "Prüfungsschema: Bekanntheitsschutz", "schema_bekanntheitsschutz",
                   "Der Bekanntheitsschutz funktioniert ohne Verwechslungsgefahr und ohne Beeinträchtigung der Herkunftsfunktion. Sein Herzstück ist die gedankliche Verknüpfung."),
            mc("k05a-1", "Wann ist eine Marke bekannt?",
               "Welche Aussage zur Bekanntheit im Sinne des § 14 Abs. 2 Nr. 3 ist richtig?",
               ["Bekannt ist eine Marke ab 50 % Bekanntheit in der Gesamtbevölkerung", "Bekannt ist eine Marke, wenn sie einem bedeutenden Teil des von den Waren angesprochenen Publikums bekannt ist; feste Prozentsätze gibt es nicht", "Bekannt ist nur eine notorisch bekannte Marke nach Art. 6bis PVÜ", "Bekanntheit setzt Eintragung seit mindestens zehn Jahren voraus"], 1,
               ["Bekannt ist eine Marke, wenn sie einem **bedeutenden Teil des Publikums** bekannt ist, das von den durch die Marke erfassten Waren oder Dienstleistungen betroffen ist. Feste Prozentsätze gibt es nicht; maßgeblich sind Marktanteil, Intensität, geographische Ausdehnung, Dauer der Benutzung und Werbeaufwand (EuGH General Motors, BGH TÜV II).",
                "Bekanntheit in einem wesentlichen Teil des Bundesgebiets genügt. Die Bekanntheit muss im Kollisionszeitpunkt bestehen."],
               concepts=["bekannte_marke"], norms=["§ 14 Abs. 2 Nr. 3"], cases=["eugh_general_motors", "bgh_tuev_ii"], step="step:schema_bekanntheitsschutz.1"),
            fall("k05a-2", "OTTO für Caps",
                 "Der Versandhändler OTTO ist Inhaber der bekannten Marke „OTTO“, unter anderem für Bekleidung. Ein Dritter verkauft Baseballcaps mit dem Aufdruck „OTTO“. Verwechslungsgefahr lässt sich nicht sicher feststellen.",
                 "Kann der Bekanntheitsschutz auch dann greifen, wenn die Waren identisch oder ähnlich sind?", True,
                 ["**Ja!** Nach früherem Wortlaut galt § 14 Abs. 2 Nr. 3 nur für „nicht ähnliche“ Waren. Der BGH hat die Norm aber schon lange richtlinienkonform auch auf identische und ähnliche Waren angewandt (OTTO Cap); seit dem MaMoG 2019 steht das ausdrücklich im Gesetz, weil Art. 10 Abs. 2 lit. c MarkenRL den Bekanntheitsschutz „unabhängig davon, ob die Waren identisch, ähnlich oder nicht ähnlich sind“ zwingend vorschreibt.",
                  "Der Bekanntheitsschutz ist damit unabhängig von der Verwechslungsgefahr: Wer die Aufmerksamkeit einer bekannten Marke für eigene Bekleidung ausnutzt, verletzt sie, auch wenn niemand die Herkunft verwechselt."],
                 merke="Bekanntheitsschutz gilt für alle Waren: unähnliche, ähnliche und identische.",
                 level=2, concepts=["bekannte_marke", "ausnutzung_unterscheidungskraft"], norms=["§ 14 Abs. 2 Nr. 3", "Art. 10 MarkenRL"], cases=["bgh_otto_cap"], step="step:schema_bekanntheitsschutz.3"),
            fall("k05a-3", "INTELMARK",
                 "Intel ist Inhaberin der bekannten Marke „INTEL“ für Prozessoren. CPM benutzt „INTELMARK“ für Marketingdienstleistungen. Verbraucher denken bei „INTELMARK“ zwar an Intel, ändern ihr Kaufverhalten bei Prozessoren aber nicht.",
                 "Genügt die bloße gedankliche Verknüpfung für eine Beeinträchtigung der Unterscheidungskraft (Verwässerung)?", False,
                 ["**Nein!** Die gedankliche Verknüpfung ist **notwendige, aber nicht hinreichende** Voraussetzung. Für die Verwässerung ist zusätzlich der Nachweis erforderlich, dass sich das wirtschaftliche Verhalten des Durchschnittsverbrauchers geändert hat oder eine ernsthafte Gefahr einer solchen Änderung besteht (EuGH Intel).",
                  "Der Bekanntheitsschutz setzt also zwei Schritte voraus: erst die Verknüpfung, dann einen der vier Eingriffe."],
                 merke="Verknüpfung + Eingriff: Die Assoziation allein verletzt nicht.",
                 level=3, concepts=["gedankliche_verknuepfung", "verwaesserung"], norms=["§ 14 Abs. 2 Nr. 3"], cases=["eugh_intel"], step="step:schema_bekanntheitsschutz.4"),
        ]),
        dict(id="k05b", titel="Die vier Eingriffe und die Unlauterkeit", einheiten=[
            mc("k05b-1", "Welcher Eingriff?",
               "Ein Parfümhersteller vertreibt Imitate bekannter Luxusdüfte und legt Händlern Vergleichslisten bei („entspricht Chanel No. 5“). Welchen Eingriff bejaht der EuGH hier vorrangig?",
               ["Beeinträchtigung der Unterscheidungskraft (Verwässerung)", "Ausnutzung der Wertschätzung (Rufausbeutung)", "Beeinträchtigung der Wertschätzung (Rufschädigung)", "Keinen, weil vergleichende Werbung erlaubt ist"], 1,
               ["Der EuGH bejaht die **unlautere Ausnutzung der Wertschätzung**: Der Dritte begibt sich in den Bereich der Sogwirkung der bekannten Marke, um von ihrer Anziehungskraft, ihrem Ruf und ihrem Ansehen ohne eigene Anstrengung und ohne finanzielle Gegenleistung zu profitieren (L'Oréal/Bellure).",
                "Die vier Eingriffe: Ausnutzung der Unterscheidungskraft (Aufmerksamkeit), Ausnutzung der Wertschätzung (Image), Beeinträchtigung der Unterscheidungskraft (Verwässerung), Beeinträchtigung der Wertschätzung (Rufschädigung)."],
               level=2, concepts=["ausnutzung_wertschaetzung", "ausnutzung_unterscheidungskraft", "verwaesserung", "rufschaedigung"], cases=["eugh_loreal_bellure"], step="step:schema_bekanntheitsschutz.5"),
            fall("k05b-2", "Der springende Pudel",
                 "Ein Künstler lässt eine Wort-Bild-Marke mit einem springenden Pudel und dem Wort „PUDEL“ für Bekleidung eintragen, die Aufbau und Wortanfang der bekannten Puma-Marke parodiert. Puma verlangt Löschung nach § 9 Abs. 1 Nr. 3.",
                 "Rechtfertigt die Kunst- und Meinungsfreiheit die Eintragung der Parodie als eigene Marke?", False,
                 ["**Nein!** Der Verkehr verknüpft den „springenden Pudel“ gedanklich mit Puma und der Anmelder profitiert von der **Aufmerksamkeit** der bekannten Marke (Ausnutzung der Unterscheidungskraft). Kunst- und Meinungsfreiheit können zwar eine einzelne Benutzung rechtfertigen, nicht aber die Erlangung eines eigenen Ausschließlichkeitsrechts im Register (BGH Springender Pudel).",
                  "Der Inhaber der bekannten Marke muss nicht hinnehmen, dass ein sein Recht verletzendes Zeichen selbst Registerschutz erhält."],
                 merke="Parodie als Benutzung kann gerechtfertigt sein (Lila-Postkarte), Parodie als eigene Marke nicht (Springender Pudel).",
                 level=3, concepts=["ausnutzung_unterscheidungskraft", "relative_schutzhindernis_bekannt", "unlauterkeit"], norms=["§ 9 Abs. 1 Nr. 3", "§ 51"], cases=["bgh_springender_pudel", "bgh_lila_postkarte"], step="step:schema_bekanntheitsschutz.6"),
            fall("k05b-3", "Das Testsiegel ohne Lizenz",
                 "Ein Zahnpastahersteller wirbt auf der Verpackung mit dem bekannten ÖKO-TEST-Siegel („sehr gut“), obwohl er keinen Lizenzvertrag geschlossen hat. Das Siegel ist als Marke für Verbraucherinformationsdienstleistungen eingetragen, nicht für Zahnpasta.",
                 "Verletzt die Werbung die bekannte Marke, obwohl sie für ganz andere Dienstleistungen eingetragen ist?", True,
                 ["**Ja!** Der Bekanntheitsschutz greift gerade bei **unähnlichen Waren**. Wer das Siegel ohne Lizenz verwendet, nutzt die Wertschätzung der bekannten Marke aus, weil er sich das Vertrauen der Verbraucher in das Testinstitut zunutze macht, ohne dessen Bedingungen einzuhalten (BGH ÖKO-TEST II im Anschluss an EuGH C-690/17).",
                  "Die Unlauterkeit liegt darin, dass die Marke als Werbeinstrument für fremde Waren eingesetzt wird, ohne dass der Inhaber die Verwendungsbedingungen kontrollieren kann."],
                 merke="Fremde Siegel und Gütezeichen sind Bekanntheitsschutz in Reinform.",
                 level=2, concepts=["ausnutzung_wertschaetzung", "bekannte_marke"], norms=["§ 14 Abs. 2 Nr. 3"], cases=["bgh_oeko_test_ii"]),
            fall("k05b-4", "Interflora bei Google",
                 "Ein Kaufhaus bucht die bekannte Marke „Interflora“ als Keyword und bewirbt seinen eigenen Blumenlieferservice als Alternative, ohne Nachahmungen anzubieten oder die Marke zu verwässern.",
                 "Ist diese Keyword-Werbung eine unlautere Ausnutzung der Unterscheidungskraft?", False,
                 ["**Nein!** Bietet der Werbende lediglich eine **Alternative** zu den Waren des Markeninhabers an, ohne Nachahmungen zu vertreiben, die Marke zu verwässern oder ihre Funktionen zu beeinträchtigen, fällt die Nutzung unter den gesunden und lauteren Wettbewerb. Ein rechtfertigender Grund liegt vor (EuGH Interflora).",
                  "Anders, wenn Nachahmungen angeboten werden (Trittbrettfahren) oder die Anzeige den Nutzer über eine Verbindung im Unklaren lässt (Beeinträchtigung der Herkunftsfunktion, Fleurop)."],
                 merke="Alternative anbieten = erlaubt. Nachahmung anbieten oder Verbindung vortäuschen = verboten.",
                 level=3, concepts=["unlauterkeit", "keyword_advertising"], norms=["§ 14 Abs. 2 Nr. 3"], cases=["eugh_interflora", "bgh_fleurop"], step="step:schema_bekanntheitsschutz.6"),
        ]),
        dict(id="k05c", titel="Die bekannte Marke im Register (§ 9 Abs. 1 Nr. 3)", einheiten=[
            schema("k05c-0", "Prüfungsschema: Relative Schutzhindernisse im Register", "schema_relative_schutzhindernisse",
                   "§ 9 Abs. 1 Nr. 3 ist das Spiegelbild des § 14 Abs. 2 Nr. 3. Die Unterschiede liegen im Verfahren, im Zeitpunkt und im Prüfungsgegenstand."),
            fall("k05c-1", "Zu spät bekannt",
                 "Die Marke „VELORA“ wurde 2015 angemeldet und ist heute bekannt. Ein Dritter hatte „VELORA“ bereits 2013 für andere Waren angemeldet und eingetragen. Der Inhaber der bekannten Marke beantragt 2024 die Löschung der Marke von 2013 nach § 9 Abs. 1 Nr. 3.",
                 "Hat der Antrag Erfolg?", False,
                 ["**Nein, aus zwei Gründen!** Erstens ist die Marke von 2013 die **prioritätsältere**; § 9 setzt eine ältere bekannte Marke voraus. Zweitens muss die Bekanntheit am **Anmeldetag der angegriffenen Marke** bestanden haben (§ 51 Abs. 3). 2013 war „VELORA“ noch nicht einmal angemeldet.",
                  "Selbst wenn die bekannte Marke die ältere wäre, aber erst nach dem Anmeldetag der jüngeren Marke Bekanntheit erlangt hätte, scheitert die Löschung an § 51 Abs. 3, und § 22 Abs. 1 Nr. 1 sperrt zugleich Unterlassungsansprüche gegen die Benutzung der jüngeren Marke für ihre eingetragenen Waren: Koexistenz."],
                 merke="Bekanntheit zum Prioritätstag der jüngeren Marke, sonst § 51 Abs. 3 und § 22 Abs. 1 Nr. 1.",
                 level=3, concepts=["relative_schutzhindernis_bekannt", "koexistenz_22", "prioritaet"], norms=["§ 9 Abs. 1 Nr. 3", "§ 51 Abs. 3", "§ 22"], cases=["bgh_springender_pudel"], step="step:schema_relative_schutzhindernisse.4.3.1"),
            mc("k05c-2", "Register oder Verletzungsprozess?",
               "Worin liegt der wichtigste Unterschied im Prüfungsgegenstand zwischen § 9 Abs. 1 Nr. 3 und § 14 Abs. 2 Nr. 3?",
               ["§ 9 verlangt Verwechslungsgefahr, § 14 nicht", "§ 9 prüft die hypothetische Benutzung der jüngeren Marke nach Registerlage („würde“), § 14 die konkrete Benutzungshandlung", "§ 9 gilt nur für unähnliche Waren", "§ 9 verlangt keine gedankliche Verknüpfung"], 1,
               ["Im Register wird die **hypothetische Benutzung** der jüngeren Marke für die eingetragenen Waren beurteilt („die Benutzung … würde … ausnutzen“). Im Verletzungsprozess geht es um die **konkrete Benutzungshandlung** in ihrem tatsächlichen Umfeld.",
                "Alles andere ist gleich: Bekanntheit, Zeichenähnlichkeit, gedankliche Verknüpfung, die vier Eingriffe, Unlauterkeit ohne rechtfertigenden Grund; beide gelten seit dem MaMoG auch für ähnliche Waren. Verfahren: Widerspruch (§ 42) oder Nichtigkeit (§ 51) statt Klage nach § 140."],
               level=3, concepts=["relative_schutzhindernis_bekannt"], norms=["§ 9 Abs. 1 Nr. 3", "§ 14 Abs. 2 Nr. 3"]),
            fall("k05c-3", "Glaubhaft machen im Widerspruch",
                 "Die Inhaberin einer bekannten Marke legt Widerspruch nach § 42 gegen eine jüngere Marke ein und stützt sich auf § 9 Abs. 1 Nr. 3. Sie kündigt an, die Bekanntheit durch Zeugen und ein noch einzuholendes Gutachten zu beweisen.",
                 "Ist das Widerspruchsverfahren der richtige Ort für eine solche Beweisaufnahme?", False,
                 ["**Nein!** Das Widerspruchsverfahren ist ein **summarisches Registerverfahren**: Es gibt keine Beweisaufnahme, sondern nur Glaubhaftmachung mit präsenten Beweismitteln (vorhandene Umfragen, Unterlagen). Ist die Bekanntheit nicht amtsbekannt oder liquide belegt, scheitert der Widerspruch.",
                  "Deshalb wird der Bekanntheitsschutz gegen eingetragene Marken praktisch häufig im **Nichtigkeitsverfahren** verfolgt (§ 51, vor dem DPMA nach § 53 oder als Klage vor dem Landgericht nach § 55), wo volle Beweisführung möglich ist."],
                 merke="Widerspruch = schnell und liquide. Bekanntheit ist selten liquide.",
                 level=3, concepts=["widerspruch", "relative_schutzhindernis_bekannt", "nichtigkeit"], norms=["§ 42", "§ 43", "§ 51", "§ 55"]),
        ]),
    ],
)
