# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k06", titel="Schranken des Markenschutzes", untertitel="§§ 20 bis 24 MarkenG: Wann der Markeninhaber nichts verbieten kann",
    farbe="#2f9e44", icon="schranke",
    beschreibung="Beschreibende Benutzung, Ersatzteilhinweise, das Recht der Gleichnamigen, Erschöpfung mit Parallelimport und Beweislast, Verwirkung und Verjährung.",
    kapitel=[
        dict(id="k06a", titel="§ 23: Namen, beschreibende Angaben, Bestimmungshinweis", einheiten=[
            schema("k06a-0", "Prüfungsschema: § 23 MarkenG", "schema_schranke_23",
                   "§ 23 ist eine Einwendung: Er wird erst geprüft, wenn der Tatbestand des § 14 Abs. 2 erfüllt ist. Fehlt schon die markenmäßige Benutzung, brauchst du § 23 nicht."),
            fall("k06a-1", "Filtertüten passend für Vorwerk",
                 "Ein Hersteller verkauft Staubsaugerbeutel unter seiner Eigenmarke „EURO PLUS“, deutlich hervorgehoben, mit dem Zusatz „Filtertüte passend für Vorwerk Kobold 130“. Vorwerk klagt.",
                 "Kann sich der Hersteller auf § 23 Abs. 1 Nr. 3 berufen?", True,
                 ["**Ja, in der Tat!** Der Markeninhaber kann die Benutzung seiner Marke als **Hinweis auf die Bestimmung** einer Ware (insbesondere Zubehör oder Ersatzteil) nicht untersagen, soweit die Benutzung notwendig ist und den anständigen Gepflogenheiten entspricht (§ 23 Abs. 1 Nr. 3, Abs. 2).",
                  "Notwendig ist die Nennung, weil der Kunde sonst nicht erfährt, in welchen Staubsauger die Tüte passt (EuGH Gillette). Anständig ist sie, weil „passend für“ hervorgehoben ist und die Eigenmarke im Vordergrund steht, sodass keine Verbindung zu Vorwerk suggeriert wird (BGH Staubsaugerfiltertüten)."],
                 merke="§ 23 Nr. 3: notwendig + anständig. Eigenmarke groß, „passend für“ deutlich.",
                 concepts=["ersatzteilhinweis", "schranke_23"], norms=["§ 23 Abs. 1 Nr. 3", "§ 23 Abs. 2"], cases=["bgh_staubsaugerfiltertueten", "eugh_gillette"], step="step:schema_schranke_23.2.3"),
            fall("k06a-2", "Der Kühlergrill mit Ringen",
                 "Ein Ersatzteilhändler vertreibt Kühlergrills für Audi-Modelle. In den Grill ist eine Aufnahme eingearbeitet, die exakt die Form der vier Audi-Ringe hat, damit das Original-Emblem eingesetzt werden kann.",
                 "Ist die Nachbildung der Ringform als Bestimmungshinweis nach § 23 Abs. 1 Nr. 3 gerechtfertigt?", False,
                 ["**Nein!** Die Aufnahme in Form des Emblems ist eine markenmäßige Benutzung der bekannten Bildmarke. Sie ist zur Angabe der Bestimmung als Ersatzteil **nicht notwendig**: Eine neutrale Halterung, in die das Original-Emblem eingesetzt werden kann, genügt (BGH Kühlergrill).",
                  "Nur die Nennung der Marke als Information über die Kompatibilität ist privilegiert, nicht die Übernahme des Zeichens selbst in das Produkt."],
                 merke="§ 23 Nr. 3 erlaubt zu informieren, nicht zu imitieren.",
                 level=2, concepts=["ersatzteilhinweis"], norms=["§ 23 Abs. 1 Nr. 3"], cases=["bgh_kuehlergrill", "bgh_grosse_inspektion"]),
            fall("k06a-3", "Große Inspektion für alle",
                 "Eine freie Werkstatt wirbt für Inspektionen an VW-Fahrzeugen und verwendet dazu blickfangmäßig das VW-Logo (Wort-Bild-Marke). Die Bestimmung ließe sich auch mit der Wortmarke „VW“ angeben.",
                 "Entspricht die Verwendung des Logos den anständigen Gepflogenheiten?", False,
                 ["**Nein!** Zur Angabe, dass die Werkstatt VW-Fahrzeuge wartet, genügt die **Wortmarke**. Die zusätzliche Verwendung des Bildzeichens ist nicht notwendig und nutzt die Werbewirkung der bekannten Marke aus; sie beeinträchtigt die Werbefunktion (BGH GROSSE INSPEKTION FÜR ALLE).",
                  "Anständige Gepflogenheiten fehlen nach EuGH Gillette, wenn (1) eine Verbindung suggeriert, (2) die Wertschätzung ausgenutzt, (3) die Marke herabgesetzt oder (4) die eigene Ware als Imitat dargestellt wird."],
                 merke="Wortmarke reicht, Logo ist zu viel.",
                 level=2, concepts=["schranke_23", "ersatzteilhinweis"], norms=["§ 23 Abs. 2"], cases=["bgh_grosse_inspektion", "eugh_gillette"], step="step:schema_schranke_23.3"),
            fall("k06a-4", "Zwei Mal Peek & Cloppenburg",
                 "Zwei wirtschaftlich unabhängige Unternehmen führen seit über hundert Jahren den Namen „Peek & Cloppenburg“, eines in Hamburg für den Norden, eines in Düsseldorf für den Rest. Das Düsseldorfer Unternehmen wirbt jetzt bundesweit in Zeitschriften.",
                 "Muss das Düsseldorfer Unternehmen die Werbung im Norden ganz unterlassen?", False,
                 ["**Nein!** Zwischen den Gleichnamigen besteht eine seit langem gewachsene **Gleichgewichtslage**. Der Störer darf sie nicht einseitig verschieben, muss aber nur das Erforderliche und Zumutbare tun, um Verwechslungen zu vermeiden: einen **aufklärenden Zusatz** (Ortsangabe, Hinweis auf zwei Unternehmen). Der Zusatz muss deutlich sein, aber nicht in gleicher Größe wie die Werbebotschaft erscheinen (BGH Peek & Cloppenburg).",
                  "Grundlage ist § 23 Abs. 1 Nr. 1 in Verbindung mit einer Interessenabwägung, das sogenannte Recht der Gleichnamigen. Beachte: Seit Art. 14 Abs. 1 lit. a MarkenRL gilt die Namensschranke nur für natürliche Personen; für die Unternehmen selbst tragen hier das ältere Unternehmenskennzeichen (§ 5) und die Gleichgewichtslage."],
                 merke="Gleichnamige: Zusatz statt Verbot.",
                 level=3, concepts=["gleichnamigkeit", "unternehmenskennzeichen"], norms=["§ 23 Abs. 1 Nr. 1", "§ 15", "Art. 14 MarkenRL"], cases=["bgh_peek_cloppenburg"], step="step:schema_schranke_23.2.1"),
            fall("k06a-5", "Beschreibend trotz Eintragung",
                 "Die Marke „Kinder“ ist für Süßwaren eingetragen. Ein Bäcker bewirbt seine Muffins mit „Ideal für Kinder und Erwachsene“.",
                 "Kann der Markeninhaber diese Werbung verbieten?", False,
                 ["**Nein!** Schon die markenmäßige Benutzung fehlt: „Kinder“ wird als Zielgruppenangabe im Fließtext verwendet. Selbst wenn man sie bejahte, greift § 23 Abs. 1 Nr. 2: Angaben über Merkmale der Ware (hier die Bestimmung für eine Zielgruppe) dürfen benutzt werden, auch wenn sie mit einer eingetragenen Marke identisch sind.",
                  "Die Verkehrsdurchsetzung verschafft dem Inhaber das Recht am Zeichen als Marke, nicht ein Monopol am beschreibenden Wort."],
                 merke="Eine verkehrsdurchgesetzte Marke verliert nie ihre beschreibende Bedeutung für andere.",
                 concepts=["schranke_23", "markenmaessige_benutzung"], norms=["§ 23 Abs. 1 Nr. 2"], cases=["bgh_kinder_ii", "bgh_tuev_ii"], step="step:schema_schranke_23.2.2"),
        ]),
        dict(id="k06b", titel="§ 24: Erschöpfung", einheiten=[
            schema("k06b-0", "Prüfungsschema: Erschöpfung", "schema_erschoepfung",
                   "Erschöpfung betrifft nur Originalware, die im EWR mit Zustimmung des Inhabers in Verkehr gebracht wurde. Beweislast und berechtigte Gründe sind die Klausurschwerpunkte."),
            fall("k06b-1", "Die Turnschuhe aus den USA",
                 "Ein deutscher Händler importiert Original-Turnschuhe der Marke „Converse“, die der Markeninhaber in den USA in Verkehr gebracht hat, und verkauft sie in Deutschland deutlich günstiger.",
                 "Ist das Markenrecht an den Schuhen erschöpft?", False,
                 ["**Nein!** Erschöpfung tritt nur ein, wenn die Ware vom Inhaber oder mit seiner Zustimmung **im Inland, in der EU oder im EWR** in Verkehr gebracht wurde (§ 24 Abs. 1). Das MarkenG kennt keine internationale Erschöpfung.",
                  "Ware aus Drittstaaten darf der Inhaber also vom EWR-Markt fernhalten, auch wenn sie echt ist. Der Händler müsste nachweisen, dass gerade diese Schuhe im EWR in Verkehr gebracht wurden (BGH Converse I). Art. 15 Abs. 1 MarkenRL lässt den Mitgliedstaaten keinen Spielraum für eine weitergehende internationale Erschöpfung (EuGH Silhouette)."],
                 merke="EWR-weite, keine weltweite Erschöpfung.",
                 concepts=["erschoepfung"], norms=["§ 24 Abs. 1", "Art. 15 MarkenRL"], cases=["bgh_converse_i"], step="step:schema_erschoepfung.2"),
            fall("k06b-2", "Wer muss was beweisen?",
                 "Der Markeninhaber betreibt ein ausschließliches Vertriebssystem mit einem Alleinvertriebshändler pro EU-Land. Ein Parallelhändler kann Erschöpfung nur beweisen, wenn er seine Bezugsquelle innerhalb des Systems offenlegt, die dann vom Inhaber abgeschnitten würde.",
                 "Muss trotzdem der Parallelhändler die Erschöpfung beweisen?", False,
                 ["**Nein!** Grundsätzlich trägt zwar der Dritte die Beweislast für die Erschöpfung. Betreibt der Inhaber aber ein **ausschließliches Vertriebssystem** und droht bei Offenlegung der Bezugsquelle eine **Abschottung der nationalen Märkte**, kehrt sich die Beweislast um: Der Inhaber muss beweisen, dass die Ware außerhalb des EWR in Verkehr gebracht wurde (EuGH Van Doren, BGH stüssy II).",
                  "Ohne Marktabschottungsgefahr bleibt es bei der Beweislast des Händlers, auch wenn die Ware von einem EWR-Lizenznehmer stammt (BGH Converse II)."],
                 merke="Beweislast beim Händler, Umkehr bei Vertriebssystem plus Abschottungsgefahr.",
                 level=3, concepts=["beweislast_erschoepfung"], norms=["§ 24 Abs. 1"], cases=["eugh_van_doren", "bgh_stuessy_ii", "bgh_converse_ii"], step="step:schema_erschoepfung.3"),
            fall("k06b-3", "Der Lizenznehmer verkauft an Discounter",
                 "Ein Lizenznehmer darf Markenware laut Lizenzvertrag nur an Fachhändler verkaufen. Er verkauft dennoch an einen Discounter im EWR, der die Ware weitervertreibt.",
                 "Ist die Ware mit Zustimmung des Markeninhabers in Verkehr gebracht worden?", False,
                 ["**Nein!** Verstößt der Lizenznehmer gegen eine der in § 30 Abs. 2 genannten Beschränkungen (etwa die Qualität der Waren oder das Vertriebsgebiet), kann der Inhaber die Marke gegen ihn geltend machen; das Inverkehrbringen erfolgt dann **ohne Zustimmung** und die Erschöpfung tritt nicht ein (BGH Converse II, EuGH Copad).",
                  "Achtung: Nicht jeder Vertragsverstoß hindert die Erschöpfung, sondern nur ein Verstoß gegen die in § 30 Abs. 2 abschließend genannten Punkte. Ein Verstoß gegen eine reine Preisabsprache wäre unerheblich."],
                 merke="Lizenzverstoß nach § 30 Abs. 2 = keine Zustimmung = keine Erschöpfung.",
                 level=3, concepts=["erschoepfung", "lizenz"], norms=["§ 24 Abs. 1", "§ 30 Abs. 2"], cases=["bgh_converse_ii"]),
            fall("k06b-4", "Umgepackte Arzneimittel",
                 "Ein Parallelimporteur führt Arzneimittel aus Spanien ein, wo sie in 30er-Packungen verkauft werden. In Deutschland sind nur 50er-Packungen verkehrsüblich. Er packt um, gibt sich als Umpacker an, beeinträchtigt die Blister nicht und informiert den Hersteller vorab.",
                 "Kann sich der Markeninhaber dem Vertrieb der umgepackten Ware widersetzen?", False,
                 ["**Nein!** Zwar ist das Umpacken eine Veränderung der Ware (§ 24 Abs. 2). Der Inhaber kann sich dem Vertrieb aber nicht widersetzen, wenn die **BMS-Kriterien** erfüllt sind: (1) Umpacken zur Vermarktung erforderlich, (2) Originalzustand unberührt, (3) Hersteller und Umpacker angegeben, (4) Aufmachung nicht rufschädigend, (5) Vorabinformation des Inhabers (EuGH Bristol-Myers Squibb).",
                  "Die Erforderlichkeit ist streng: Nur wenn der Marktzugang ohne Umpacken tatsächlich behindert wäre (andere Packungsgrößen), ist es erlaubt."],
                 merke="Umpacken erlaubt, wenn nötig, schonend, transparent, nicht rufschädigend und angekündigt.",
                 level=3, concepts=["umverpackung", "berechtigte_gruende"], norms=["§ 24 Abs. 2"], cases=["eugh_bms"], step="step:schema_erschoepfung.4"),
            fall("k06b-5", "Luxusparfum im Discounter-Prospekt",
                 "Ein Drogeriediscounter verkauft erschöpfte Original-Luxusparfums und bildet sie in seinem Wochenprospekt neben Waschmittel und Toilettenpapier ab.",
                 "Kann der Markeninhaber diese Werbung verbieten?", False,
                 ["**Grundsätzlich nein!** Mit der Erschöpfung darf der Wiederverkäufer die Marke auch in seiner **Werbung** benutzen, und zwar in der in seiner Branche üblichen Weise (EuGH Dior/Evora). Ein berechtigter Grund nach § 24 Abs. 2 liegt nur vor, wenn die Werbung den **Ruf der Marke erheblich schädigt**.",
                  "Die bloße Abbildung in einem branchenüblichen Discounter-Prospekt reicht dafür nicht; anders könnte es bei einer gezielt herabwürdigenden Aufmachung liegen."],
                 merke="Wer erschöpfte Ware verkaufen darf, darf sie auch bewerben, solange er den Ruf nicht erheblich schädigt.",
                 level=2, concepts=["berechtigte_gruende", "erschoepfung"], norms=["§ 24 Abs. 2"], cases=["eugh_dior_evora"], step="step:schema_erschoepfung.5"),
        ]),
        dict(id="k06c", titel="Verwirkung, Verjährung und § 22", einheiten=[
            fall("k06c-1", "Zehn Jahre zugeschaut",
                 "Der Inhaber der bekannten Marke „Hard Rock Cafe“ weiß seit über zehn Jahren, dass ein Heidelberger Restaurant unter „Hard Rock Cafe Heidelberg“ Merchandising verkauft, und hat nichts unternommen. Jetzt klagt er auf Unterlassung des Merchandising-Verkaufs.",
                 "Ist der Unterlassungsanspruch verwirkt, weil der Inhaber so lange geduldet hat?", False,
                 ["**Nein, jedenfalls nicht für den Verkauf!** Verwirkung nach § 21 Abs. 4 i.V.m. § 242 BGB verlangt Zeitmoment, Umstandsmoment (schutzwürdiger Besitzstand) und Zurechenbarkeit. Bei **wiederholten, gleichartigen Verletzungshandlungen** entsteht aber mit jeder Handlung ein neuer Unterlassungsanspruch, sodass eine Verwirkung nur für den Fortbestand eines konkret geduldeten Zustands in Betracht kommt (BGH Hard Rock Cafe).",
                  "Der Verkauf neuer Merchandisingartikel ist jeweils eine neue Verletzung. Verwirkt sein kann dagegen der Anspruch gegen die Weiterführung des Restaurantnamens selbst."],
                 merke="Verwirkung schützt den geduldeten Zustand, nicht immer neue Handlungen.",
                 level=3, concepts=["verwirkung", "verhaeltnis_uwg"], norms=["§ 21 Abs. 4"], cases=["bgh_hard_rock_cafe"]),
            mc("k06c-2", "Die Fünfjahresregel des § 21",
               "Der Inhaber einer älteren Marke hat die Benutzung einer eingetragenen jüngeren Marke fünf Jahre lang in Kenntnis geduldet. Die jüngere Marke wurde gutgläubig angemeldet. Was gilt?",
               ["Der ältere Inhaber kann die jüngere Marke weiterhin löschen lassen und verbieten", "Der ältere Inhaber kann die Benutzung nicht mehr untersagen; auch der jüngere Inhaber kann die ältere Marke nicht untersagen (Koexistenz)", "Die jüngere Marke wird automatisch zur älteren", "Der ältere Inhaber verliert seine Marke"], 1,
               ["Nach § 21 Abs. 1 kann der Inhaber des älteren Rechts die Benutzung der jüngeren eingetragenen Marke **nicht mehr untersagen**, wenn er sie fünf aufeinanderfolgende Jahre in Kenntnis geduldet hat, es sei denn, die Anmeldung war bösgläubig. Parallel ist auch die Nichtigkeit nach § 51 Abs. 2 ausgeschlossen.",
                "§ 21 Abs. 3 ordnet Koexistenz an: Auch der Inhaber des jüngeren Rechts kann die Benutzung des älteren nicht untersagen."],
               level=2, concepts=["verwirkung", "koexistenz_22"], norms=["§ 21", "§ 51 Abs. 2"]),
            fall("k06c-3", "Die verspätete Bekanntheit",
                 "Die Marke „ARVO“ wurde 2010 angemeldet und ist seit 2018 bekannt. 2014 hatte ein Dritter „ARVO“ für völlig andere Waren angemeldet und eingetragen und benutzt sie seitdem. Der Inhaber der bekannten Marke klagt 2024 auf Unterlassung nach § 14 Abs. 2 Nr. 3.",
                 "Kann er die Benutzung der jüngeren Marke für deren eingetragene Waren verbieten?", False,
                 ["**Nein!** Nach § 22 Abs. 1 Nr. 1 kann der Inhaber des älteren Zeichens die Benutzung einer eingetragenen jüngeren Marke nicht untersagen, wenn ein Nichtigkeitsantrag zurückzuweisen wäre, weil das ältere Zeichen **am Prioritätstag der jüngeren Marke noch nicht bekannt** war (§ 51 Abs. 3). 2014 war „ARVO“ nicht bekannt.",
                  "Umgekehrt kann auch der Inhaber der jüngeren Marke nichts gegen die ältere unternehmen (§ 22 Abs. 2). Beide koexistieren. Die Bekanntheit muss also zum richtigen Zeitpunkt vorliegen."],
                 merke="§ 22 und § 51 Abs. 3 laufen parallel: Was nicht gelöscht werden kann, darf auch benutzt werden.",
                 level=3, concepts=["koexistenz_22", "relative_schutzhindernis_bekannt"], norms=["§ 22 Abs. 1 Nr. 1", "§ 51 Abs. 3", "Art. 18 MarkenRL", "Art. 8 MarkenRL"], step="step:schema_markenverletzung.4.4"),
            mc("k06c-4", "Verjährung",
               "Wann verjähren Ansprüche aus dem MarkenG?",
               ["Nach 6 Monaten ab Kenntnis (§ 11 UWG analog)", "Nach den allgemeinen Vorschriften des BGB: regelmäßig 3 Jahre ab Ende des Jahres der Kenntnis (§§ 195, 199 BGB)", "Nach 10 Jahren ab Verletzung", "Nie, solange die Marke eingetragen ist"], 1,
               ["§ 20 verweist auf die **allgemeinen Verjährungsvorschriften des BGB**: drei Jahre ab dem Schluss des Jahres, in dem der Anspruch entstanden ist und der Inhaber Kenntnis erlangt hat (§§ 195, 199 BGB). Anders als im UWG (§ 11: sechs Monate) gilt keine kurze Frist.",
                "Bei Dauerverletzungen beginnt die Verjährung des Unterlassungsanspruchs nicht, solange die Verletzung andauert. Der Bereicherungsanspruch bleibt nach § 852 BGB erhalten (§ 20 S. 2)."],
               concepts=["verjaehrung"], norms=["§ 20"]),
        ]),
    ],
)
