# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k07", titel="Benutzungszwang, Widerspruch und Löschung", untertitel="§§ 25, 26, 42, 43, 49 bis 55 MarkenG",
    farbe="#4B6B6B", icon="loeschung",
    beschreibung="Rechtserhaltende Benutzung, Benutzungsschonfrist und Einreden; Verfall und Nichtigkeit mit ihren Verfahren; das Widerspruchsverfahren.",
    kapitel=[
        dict(id="k07a", titel="Rechtserhaltende Benutzung (§ 26)", einheiten=[
            schema("k07a-0", "Prüfungsschema: Benutzungszwang und Verfall", "schema_benutzungszwang",
                   "Nach fünf Jahren muss die Marke benutzt werden, sonst drohen der Verlust der Ansprüche (§ 25) und die Löschung (§ 49)."),
            fall("k07a-1", "Die Vorratsmarke",
                 "Ein Unternehmen hat „VOODOO“ 2015 für Bekleidung eintragen lassen und seit 2016 jährlich etwa 200 T-Shirts mit einem „VOODOO“-Etikett über seinen Onlineshop verkauft. 2024 erhebt ein Verletzer die Einrede der Nichtbenutzung.",
                 "Ist der geringe Umfang eine ernsthafte Benutzung?", True,
                 ["**Ja!** Ernsthaft ist eine Benutzung, die entsprechend der Hauptfunktion der Marke erfolgt, um für die Waren einen **Absatzmarkt zu erschließen oder zu sichern**; nur eine symbolische Benutzung zur Rechtserhaltung genügt nicht (EuGH Ansul). Einen Mindestumfang gibt es nicht; die Benutzung muss nach Art, Umfang und Dauer wirtschaftlich sinnvoll sein (BGH VOODOO).",
                  "Tatsächlicher Absatz von Etikettenware über mehrere Jahre reicht. Die Beweislast trägt im Verletzungsprozess der Markeninhaber, wenn die Einrede nach § 25 Abs. 2 erhoben wird."],
                 merke="Ernsthaft = auf dem Markt, nicht nur im Register. Kein Mindestumsatz.",
                 concepts=["ernsthafte_benutzung", "nichtbenutzungseinrede"], norms=["§ 26 Abs. 1", "§ 25"], cases=["eugh_ansul", "bgh_voodoo"], step="step:schema_benutzungszwang.3.1"),
            fall("k07a-2", "Dorzo-Vision",
                 "Die Marke „Dorzo“ ist für Augentropfen eingetragen. Benutzt wird ausschließlich „Dorzo-Vision“, wobei der Verkehr die Kombination als einheitliches Zeichen wahrnimmt.",
                 "Ist die Benutzung von „Dorzo-Vision“ rechtserhaltend für „Dorzo“?", False,
                 ["**Nein!** Die Benutzung in abweichender Form ist nur rechtserhaltend, wenn die Abweichung den **kennzeichnenden Charakter** der Marke nicht verändert (§ 26 Abs. 3). Erkennt der Verkehr das Markenwort in der Kombination nicht mehr als eigenständigen Herkunftshinweis, ist der kennzeichnende Charakter verändert (BGH Dorzo).",
                  "Anders liegt es bei bloßen beschreibenden oder werblichen Zusätzen und bei graphischer Modernisierung; diese verändern den kennzeichnenden Charakter nicht (BGH Probiotik)."],
                 merke="Zusatz unschädlich, Verschmelzung schädlich.",
                 level=2, concepts=["abweichende_form"], norms=["§ 26 Abs. 3"], cases=["bgh_dorzo", "bgh_probiotik"], step="step:schema_benutzungszwang.3.6"),
            fall("k07a-3", "LOTTO auf der Lottocard",
                 "Die Marke „LOTTO“ ist für Lotteriedienstleistungen eingetragen. Der Inhaber benutzt sie als Bestandteil von „LOTTOCARD“ und auf Annahmestellenschildern. Der Gegner meint, „Lotto“ werde vom Verkehr nur beschreibend verstanden, daher liege keine markenmäßige und keine rechtserhaltende Benutzung vor.",
                 "Kann einer eingetragenen Marke die rechtserhaltende Benutzung abgesprochen werden, weil sie beschreibend sei?", False,
                 ["**Nein!** Die rechtserhaltende Benutzung kann nicht mit der Begründung verneint werden, die Marke sei für die Dienstleistungen beschreibend; das wäre ein Angriff auf die Eintragung selbst, der nur im Löschungsverfahren möglich ist (BGH LOTTOCARD). Es genügt, dass der Verkehr die konkrete Verwendung als Marke auffasst.",
                  "Die Verwendung in Kombination („LOTTOCARD“) kann rechtserhaltend sein, wenn „LOTTO“ seine kennzeichnende Eigenständigkeit behält."],
                 merke="Im Benutzungsstreit wird die Schutzfähigkeit nicht neu aufgerollt.",
                 level=3, concepts=["rechtserhaltende_benutzung"], norms=["§ 26 Abs. 1", "§ 26 Abs. 3"], cases=["bgh_lottocard"]),
            mc("k07a-4", "Wann beginnt die Schonfrist?",
               "Eine Marke wurde am 1. Februar 2020 eingetragen. Ein Widerspruch wurde am 30. November 2021 rechtskräftig zurückgewiesen. Ab wann läuft die fünfjährige Benutzungsschonfrist?",
               ["Ab dem Anmeldetag", "Ab dem 1. Februar 2020 (Eintragung)", "Ab dem 30. November 2021 (Abschluss des Widerspruchsverfahrens)", "Ab der ersten Benutzung"], 2,
               ["Wird gegen die Eintragung Widerspruch erhoben, beginnt die Benutzungsschonfrist erst mit dem **Abschluss des Widerspruchsverfahrens** (§ 26 Abs. 5). Ohne Widerspruch läuft sie ab der Eintragung.",
                "Innerhalb der fünf Jahre ist Nichtbenutzung unschädlich: Weder die Einrede nach § 25 noch der Verfall nach § 49 Abs. 1 greifen."],
               level=2, concepts=["benutzungsschonfrist"], norms=["§ 26 Abs. 5", "§ 25 Abs. 1", "§ 49 Abs. 1"], step="step:schema_benutzungszwang.1"),
        ]),
        dict(id="k07b", titel="Verfall und Nichtigkeit (§§ 49 bis 52)", einheiten=[
            schema("k07b-0", "Prüfungsschema: Löschung eingetragener Marken", "schema_loeschung",
                   "Merke die Grundunterscheidung: Verfall = nachträglich entstandener Mangel, Wirkung ex nunc. Nichtigkeit = ursprünglicher Mangel, Wirkung ex tunc."),
            fall("k07b-1", "Wiederaufnahme in letzter Minute",
                 "Die Marke „ZIRKON“ wurde seit sieben Jahren nicht benutzt. Am 1. März erfährt der Inhaber, dass ein Konkurrent einen Verfallsantrag vorbereitet. Am 15. März startet er hektisch den Vertrieb. Der Antrag geht am 1. Mai beim DPMA ein.",
                 "Rettet die Benutzungsaufnahme im März die Marke?", False,
                 ["**Nein!** Zwar heilt eine Benutzungsaufnahme nach Ablauf der fünf Jahre, aber vor dem Antrag, den Verfall grundsätzlich (§ 49 Abs. 1 S. 2). Das gilt aber nicht, wenn die Benutzung erst **innerhalb von drei Monaten vor dem Antrag** aufgenommen wurde, nachdem der Inhaber vom drohenden Antrag Kenntnis erlangt hatte (§ 49 Abs. 1 S. 3).",
                  "Die Regelung verhindert, dass Inhaber nur auf den Antrag hin Scheinbenutzungen starten."],
                 merke="Heilung ja, aber nicht in den letzten drei Monaten nach Kenntnis vom Antrag.",
                 level=2, concepts=["verfall", "benutzungsschonfrist"], norms=["§ 49 Abs. 1"], step="step:schema_benutzungszwang.2"),
            fall("k07b-2", "TÜV als Gattungsbegriff?",
                 "Ein Wettbewerber beantragt den Verfall der Marke „TÜV“: Der Verkehr verwende „TÜV“ längst als Gattungsbegriff für jede technische Prüfung („den TÜV machen“).",
                 "Ist die Marke wegen Entwicklung zur gebräuchlichen Bezeichnung verfallen?", False,
                 ["**Nein!** Verfall nach § 49 Abs. 2 Nr. 1 setzt voraus, dass die Marke **infolge des Verhaltens oder der Untätigkeit des Inhabers** im geschäftlichen Verkehr zur gebräuchlichen Bezeichnung geworden ist. Der BGH hat für „TÜV“ trotz verbreiteter umgangssprachlicher Verwendung die Entwicklung zum Gattungsbegriff verneint, weil der Verkehr weiterhin die Prüforganisationen dahinter sieht und der Inhaber gegen Verletzungen vorgeht (BGH TÜV II).",
                  "Der Inhaber einer bekannten Marke muss also aktiv gegen generische Verwendung vorgehen, um diesen Verfallsgrund zu vermeiden."],
                 merke="Gattungsbegriff nur bei Untätigkeit des Inhabers und Wandel im geschäftlichen Verkehr.",
                 level=2, concepts=["uebliche_bezeichnung", "verfall"], norms=["§ 49 Abs. 2 Nr. 1"], cases=["bgh_tuev_ii"]),
            mc("k07b-3", "Ex tunc oder ex nunc?",
               "Eine Marke wird wegen Bösgläubigkeit der Anmeldung gelöscht. Ab wann gilt sie als nicht existent?",
               ["Ab dem Löschungsantrag (ex nunc)", "Ab der Eintragung, also rückwirkend (ex tunc)", "Ab dem Tag der Entscheidung", "Ab dem Ende der Benutzungsschonfrist"], 1,
               ["Bösgläubigkeit ist ein absolutes Schutzhindernis (§ 8 Abs. 2 Nr. 14), die Löschung erfolgt wegen **Nichtigkeit** (§ 50). Die Wirkungen der Eintragung gelten dann als **von Anfang an nicht eingetreten** (§ 52 Abs. 2, ex tunc).",
                "Beim Verfall (§ 49) gilt die Marke dagegen erst ab dem Löschungsantrag als erloschen, auf Antrag ab dem früheren Zeitpunkt des Verfallseintritts (§ 52 Abs. 1, ex nunc)."],
               level=2, concepts=["nichtigkeit", "verfall"], norms=["§ 52"]),
            fall("k07b-4", "Wer darf löschen lassen?",
                 "Ein Verbraucher, der keinerlei Geschäftsbeziehung zur Markenbranche hat, beantragt die Löschung der Marke „Black Friday“ wegen Freihaltebedürfnisses. Der Inhaber bestreitet die Antragsbefugnis.",
                 "Kann jedermann einen Nichtigkeitsantrag wegen absoluter Schutzhindernisse stellen?", True,
                 ["**Ja!** Der Antrag auf Nichtigkeit wegen absoluter Schutzhindernisse (§ 50) und der Verfallsantrag (§ 49) sind **Popularanträge**: Jede Person kann sie stellen (§ 53 Abs. 1), ein eigenes Interesse ist nicht nötig, weil absolute Schutzhindernisse im Allgemeininteresse bestehen.",
                  "Anders die Nichtigkeit wegen älterer Rechte (§ 51): Hier ist nur der Inhaber des älteren Rechts antragsbefugt."],
                 merke="§§ 49, 50: jedermann. § 51: nur der Inhaber des älteren Rechts.",
                 concepts=["nichtigkeit", "verfall"], norms=["§ 53", "§ 50", "§ 51"], cases=["bgh_black_friday"]),
        ]),
        dict(id="k07c", titel="Das Widerspruchsverfahren (§§ 42, 43)", einheiten=[
            schema("k07c-0", "Prüfungsschema: Widerspruchsverfahren", "schema_widerspruch",
                   "Der Widerspruch ist das schnelle, günstige Registerverfahren gegen jüngere Marken. Er ist befristet und auf bestimmte ältere Rechte beschränkt."),
            mc("k07c-1", "Die Widerspruchsfrist",
               "Die Eintragung der Marke „NORDLICHT“ wird am 10. Januar veröffentlicht. Bis wann kann der Inhaber einer älteren Marke Widerspruch einlegen?",
               ["Bis 10. Februar", "Bis 10. April", "Bis 10. Juli", "Unbefristet"], 1,
               ["Der Widerspruch ist innerhalb von **drei Monaten** nach dem Tag der Veröffentlichung der Eintragung einzulegen (§ 42 Abs. 1). Danach bleibt nur der Nichtigkeitsantrag nach § 51 (§ 53 oder § 55), der unbefristet ist, aber der Verwirkung (§ 51 Abs. 2) unterliegt.",
                "Widerspruchsgründe sind nur die in § 42 Abs. 2 genannten älteren Rechte; sonstige Rechte (Name, Urheberrecht, Design) können nur im Nichtigkeitsverfahren geltend gemacht werden."],
               concepts=["widerspruch"], norms=["§ 42", "§ 51"], step="step:schema_widerspruch.1"),
            fall("k07c-2", "Die Einrede im Widerspruch",
                 "Die Widersprechende stützt sich auf eine seit acht Jahren eingetragene Marke. Der Inhaber der jüngeren Marke bestreitet die Benutzung. Die Widersprechende legt eine eidesstattliche Versicherung und Rechnungen für nur einen Teil der eingetragenen Waren vor.",
                 "Kann der Widerspruch auf alle eingetragenen Waren der älteren Marke gestützt werden?", False,
                 ["**Nein!** Bestreitet der Gegner die Benutzung, muss die Widersprechende die rechtserhaltende Benutzung **glaubhaft machen** (§ 43 Abs. 1). Bei der Entscheidung werden nur die Waren berücksichtigt, für die die Benutzung glaubhaft gemacht wurde (§ 43 Abs. 1 S. 3).",
                  "Glaubhaftmachung bedeutet überwiegende Wahrscheinlichkeit mit präsenten Beweismitteln (eidesstattliche Versicherung, Rechnungen, Kataloge). Ein Beweis wie im Zivilprozess ist nicht nötig."],
                 merke="Einrede im Widerspruch: Nur die glaubhaft gemachten Waren zählen.",
                 level=2, concepts=["nichtbenutzungseinrede", "widerspruch"], norms=["§ 43 Abs. 1"], step="step:schema_widerspruch.2"),
            fall("k07c-3", "Das Namensrecht als Widerspruchsgrund",
                 "Schauspielerin Nora Stern sieht ihren Namen in der jüngeren Marke „Nora Stern“ für Kosmetik. Sie legt Widerspruch nach § 42 ein und beruft sich auf ihr Namensrecht nach § 12 BGB.",
                 "Ist das Namensrecht ein zulässiger Widerspruchsgrund?", False,
                 ["**Nein!** Der Widerspruch kann nur auf die in § 42 Abs. 2 abschließend genannten Rechte gestützt werden: ältere Marken, notorisch bekannte Marken, Benutzungsmarken und geschäftliche Bezeichnungen, geschützte Ursprungsbezeichnungen und geographische Angaben. Das **Namensrecht** (§ 13 Abs. 2 Nr. 1) gehört nicht dazu.",
                  "Nora kann aber ein Nichtigkeitsverfahren nach § 51 Abs. 1 i.V.m. § 13 Abs. 2 Nr. 1 einleiten, beim DPMA (§ 53) oder mit Klage vor dem Landgericht (§ 55)."],
                 merke="Widerspruch = enger Katalog des § 42 Abs. 2. Alles andere über § 51.",
                 level=2, concepts=["widerspruch", "relative_schutzhindernisse", "nichtigkeit"], norms=["§ 42 Abs. 2", "§ 13", "§ 51"]),
        ]),
    ],
)
