# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k08", titel="Geschäftliche Bezeichnungen und Domains", untertitel="§§ 5, 15 MarkenG: Unternehmenskennzeichen und Werktitel",
    farbe="#d6336c", icon="firma",
    beschreibung="Wie Unternehmenskennzeichen und Werktitel entstehen, wie ihre Verletzung geprüft wird und was für Domainnamen gilt.",
    kapitel=[
        dict(id="k08a", titel="Unternehmenskennzeichen", einheiten=[
            schema("k08a-0", "Prüfungsschema: Schutz geschäftlicher Bezeichnungen", "schema_unternehmenskennzeichen",
                   "§ 15 ist das Pendant zu § 14 für Unternehmenskennzeichen und Werktitel. Statt Warenähnlichkeit prüfst du die Branchennähe."),
            fall("k08a-1", "Die Domain als Kennzeichen",
                 "Ein Softwarehaus betreibt seit Jahren unter „soco.de“ eine Website, über die es sich als Unternehmen präsentiert und Aufträge akquiriert. Einen Firmennamen „soco“ hat es nicht.",
                 "Kann der Domainname als Unternehmenskennzeichen nach § 5 Abs. 2 geschützt sein?", True,
                 ["**Ja!** Ein Domainname kann Unternehmenskennzeichen sein, wenn der Verkehr in ihm einen **Hinweis auf das Unternehmen** und nicht nur eine Adresse sieht (BGH soco.de). Der Schutz entsteht mit der **Benutzungsaufnahme im geschäftlichen Verkehr**, nicht schon mit der Registrierung.",
                  "Voraussetzung ist Unterscheidungskraft: Bei beschreibenden Domains wie „wetter.de“ fehlt sie, dann bleibt nur die Verkehrsgeltung."],
                 merke="Registrieren schafft kein Kennzeichenrecht, Benutzen schon.",
                 concepts=["domain", "unternehmenskennzeichen"], norms=["§ 5 Abs. 2"], cases=["bgh_soco_de"], step="step:schema_unternehmenskennzeichen.1.1"),
            fall("k08a-2", "Das Firmenschlagwort",
                 "Die „defacto marketing GmbH“ tritt seit 1990 auf; Kunden nennen sie einfach „defacto“. Ein anderes Unternehmen registriert „defacto.de“ und bietet dort Marketingdienstleistungen an.",
                 "Genießt der Bestandteil „defacto“ selbständigen Schutz, obwohl die Firma länger lautet?", True,
                 ["**Ja!** Ein Firmenbestandteil ist selbständig geschützt, wenn er **seiner Natur nach geeignet** ist, als schlagwortartiger Hinweis auf das Unternehmen zu wirken. Eine tatsächliche schlagwortartige Verwendung ist nicht erforderlich; „marketing GmbH“ ist beschreibend, „defacto“ kennzeichnend (BGH defacto).",
                  "Die Verwechslungsgefahr nach § 15 Abs. 2 richtet sich nach Branchennähe, Kennzeichnungskraft und Zeichenähnlichkeit. Bei identischer Branche und identischem Schlagwort ist sie gegeben."],
                 merke="Der kennzeichnende Teil der Firma ist für sich geschützt.",
                 level=2, concepts=["firmenschlagwort", "branchennaehe"], norms=["§ 5 Abs. 2", "§ 15 Abs. 2"], cases=["bgh_defacto"], step="step:schema_unternehmenskennzeichen.3"),
            fall("k08a-3", "shell.de",
                 "Herr Andreas Shell registriert „shell.de“ für seine private Homepage und ein kleines Übersetzungsbüro. Der Mineralölkonzern verlangt die Freigabe der Domain.",
                 "Gilt bei Gleichnamigkeit auch hier das Prinzip „wer zuerst registriert“?", False,
                 ["**Nein, ausnahmsweise nicht!** Grundsätzlich gilt bei Gleichnamigen für Domains das **Prioritätsprinzip der Registrierung**. Bei **überragender Bekanntheit** eines der Namensträger erwartet der Verkehr unter „shell.de“ aber den Konzern; der Privatmann muss einen unterscheidenden Zusatz wählen (BGH shell.de).",
                  "Rechtsgrundlage ist hier das Namensrecht (§ 12 BGB), weil die private Nutzung außerhalb des geschäftlichen Verkehrs liegt; im geschäftlichen Verkehr wären §§ 5, 15 vorrangig."],
                 merke="Gleichnamige: Registrierungspriorität, außer einer ist überragend bekannt.",
                 level=3, concepts=["domain", "gleichnamigkeit"], norms=["§ 5", "§ 15"], cases=["bgh_shell_de", "bgh_peek_cloppenburg"]),
            mc("k08a-4", "Was ersetzt die Warenähnlichkeit?",
               "Bei der Verwechslungsgefahr zwischen zwei Unternehmenskennzeichen (§ 15 Abs. 2) tritt an die Stelle der Waren-/Dienstleistungsähnlichkeit …",
               ["die Unternehmensgröße", "die Branchennähe", "die geographische Nähe", "die Rechtsform"], 1,
               ["Statt Waren werden Unternehmen verglichen: Maßgeblich ist die **Branchennähe**, also Berührungspunkte der Unternehmen auf dem Markt nach Art der Waren/Dienstleistungen, Vertriebswegen und Kundenkreisen. Sie steht in Wechselwirkung mit Kennzeichnungskraft und Zeichenähnlichkeit.",
                "Bei absoluter Branchenverschiedenheit scheidet Verwechslungsgefahr aus; dann hilft nur § 15 Abs. 3 (bekannte geschäftliche Bezeichnung)."],
               concepts=["branchennaehe"], norms=["§ 15 Abs. 2", "§ 15 Abs. 3"], cases=["bgh_defacto"]),
        ]),
        dict(id="k08b", titel="Werktitel", einheiten=[
            fall("k08b-1", "Die Wetter-App",
                 "Ein Medienunternehmen bietet seit Jahren unter „wetter.de“ Wetterinformationen im Internet und als App an. Ein Konkurrent bringt die App „wetter DE“ heraus.",
                 "Genießt „wetter.de“ Werktitelschutz nach § 5 Abs. 3?", False,
                 ["**Nein!** Apps und Internet-Informationsangebote sind zwar **titelschutzfähige Werke** (BGH wetter.de, erstmals entschieden). „wetter.de“ fehlt aber die **originäre Unterscheidungskraft**: Die Bezeichnung beschreibt nur den Inhalt.",
                  "Bei Zeitschriften gilt wegen der Verkehrsgewöhnung an beschreibende Titel ein abgesenkter Maßstab. Für Apps und Domains hat der BGH eine solche Gewöhnung nicht festgestellt. Ohne Verkehrsgeltung bleibt der Titel schutzlos."],
                 merke="Apps sind Werke, aber beschreibende Titel bleiben ohne Verkehrsgeltung schutzlos.",
                 level=2, concepts=["werktitel", "unterscheidungskraft"], norms=["§ 5 Abs. 3"], cases=["bgh_wetter_de"], step="step:schema_unternehmenskennzeichen.1.2"),
            fall("k08b-2", "Augsburger gegen Leipziger Puppenkiste",
                 "Die „Augsburger Puppenkiste“ ist als Werktitel und Marke geschützt. Ein Theater nennt sich „Leipziger Puppenkiste“.",
                 "Schützt der Werktitel auch gegen die Annahme, beide Theater seien wirtschaftlich verbunden?", False,
                 ["**Grundsätzlich nein!** Werktitel schützen nur gegen die **unmittelbare Verwechslung der Werke**. Eine Verwechslungsgefahr im weiteren Sinne (Annahme geschäftlicher Verbindungen) kommt nur bei bekannten Titeln in Betracht, denen der Verkehr auch einen Hinweis auf die betriebliche Herkunft entnimmt (BGH Augsburger Puppenkiste).",
                  "Im konkreten Fall verneinte der BGH schon die Zeichenähnlichkeit: Die Ortsangaben prägen mit, „Puppenkiste“ ist kennzeichnungsschwach."],
                 merke="Werktitel unterscheiden Werke, nicht Unternehmen.",
                 level=3, concepts=["werktitel", "verwechslungsgefahr_weiterer_sinn"], norms=["§ 5 Abs. 3", "§ 15 Abs. 2"], cases=["bgh_augsburger_puppenkiste"]),
            fall("k08b-3", "Wem gehört der Songtitel?",
                 "Komponist K und Textdichter T haben das Musikstück „Das Omen (Teil 1)“ geschaffen; der Verlag V hat es vermarktet. Ein Dritter veröffentlicht „Omen – Extended Mix“. V klagt aus dem Werktitel.",
                 "Steht das Werktitelrecht dem Verlag zu, weil er den Titel vermarktet hat?", False,
                 ["**Nein!** Die Inhaberschaft am Werktitel folgt der **Zuordnung des Werks**: Inhaber ist, wem das Werk zuzuordnen ist, bei einem Musikstück also Komponist und Textdichter (BGH Das Omen). Der Verlag kann Rechte nur aus abgeleiteter Berechtigung oder Lizenz geltend machen.",
                  "Der BGH bejahte die Unterscheidungskraft von „Das Omen (Teil 1)“; die Verwechslungsgefahr ist unter Berücksichtigung der Werkähnlichkeit zu prüfen."],
                 merke="Werktitelrecht hängt am Werk, nicht an der Vermarktung.",
                 level=3, concepts=["werktitel"], norms=["§ 5 Abs. 3", "§ 15"], cases=["bgh_das_omen"]),
        ]),
    ],
)
