# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k09", gebiet="markeng", titel="Rechtsfolgen und Durchsetzung", untertitel="§§ 14 Abs. 5 bis 7, 18, 19 MarkenG und Haftung Dritter",
    farbe="#f0801a", icon="hammer",
    beschreibung="Unterlassung, Schadensersatz mit dreifacher Schadensberechnung, Auskunft und Vernichtung; Täter, Teilnehmer und Störer.",
    kapitel=[
        dict(id="k09a", titel="Unterlassung und Schadensersatz", einheiten=[
            fall("k09a-1", "Die einmalige Verletzung",
                 "Händler H hat ein einziges Mal Plagiate verkauft, den Rest vernichtet und schriftlich versichert, es nie wieder zu tun, allerdings ohne Vertragsstrafeversprechen.",
                 "Besteht der Unterlassungsanspruch nach § 14 Abs. 5 weiter?", True,
                 ["**Ja!** Die begangene Verletzung begründet eine **Vermutung der Wiederholungsgefahr**. Diese wird regelmäßig nur durch eine **strafbewehrte Unterlassungserklärung** ausgeräumt; eine bloße Zusicherung reicht nicht.",
                  "Ein Verschulden ist für den Unterlassungsanspruch nicht erforderlich. Der Anspruch besteht auch bei Erstbegehungsgefahr, wenn eine Verletzung ernsthaft droht (§ 14 Abs. 5 S. 2)."],
                 merke="Wiederholungsgefahr wird vermutet und nur mit Vertragsstrafe beseitigt.",
                 concepts=["unterlassungsanspruch"], norms=["§ 14 Abs. 5"], step="step:schema_markenverletzung.5"),
            mc("k09a-2", "Dreifache Schadensberechnung",
               "Der Verletzer hat mit Plagiaten 100.000 Euro Gewinn erzielt; ein üblicher Lizenzsatz wären 5 % vom Umsatz; der Inhaber kann keinen konkreten Umsatzrückgang nachweisen. Welche Berechnungsarten stehen ihm zur Wahl?",
               ["Nur der konkrete Schaden", "Konkreter Schaden, Herausgabe des Verletzergewinns oder angemessene Lizenzgebühr, nach seiner Wahl", "Nur die Lizenzgebühr", "Verletzergewinn plus Lizenzgebühr kumulativ"], 1,
               ["§ 14 Abs. 6 erlaubt die **dreifache Schadensberechnung**: (1) konkreter Schaden einschließlich entgangenem Gewinn, (2) Herausgabe des **Verletzergewinns** (S. 2), (3) **Lizenzanalogie** (S. 3). Die Arten sind alternativ; eine Kumulation ist ausgeschlossen.",
                "Voraussetzung ist Verschulden; Fahrlässigkeit wird im geschäftlichen Verkehr wegen der Prüfpflicht regelmäßig bejaht. Bei der Lizenzanalogie ist zu fragen, was vernünftige Parteien vereinbart hätten (BGH BTK)."],
               level=2, concepts=["schadensersatz", "lizenzanalogie"], norms=["§ 14 Abs. 6"], cases=["bgh_btk"], step="step:schema_markenverletzung.6.1"),
            fall("k09a-3", "Der Chef haftet mit",
                 "Ein Angestellter des Handelsunternehmens H bestellt eigenmächtig Plagiate und verkauft sie über den Laden von H. Der Inhaber von H wusste nichts davon.",
                 "Kann der Markeninhaber Unterlassung und Schadensersatz auch gegen H verlangen?", True,
                 ["**Ja!** Wird die Verletzungshandlung in einem geschäftlichen Betrieb von einem Angestellten oder Beauftragten begangen, kann der Unterlassungsanspruch **und der Schadensersatzanspruch** auch gegen den Inhaber des Betriebs geltend gemacht werden (§ 14 Abs. 7). Eine Exkulpation wie bei § 831 BGB ist nicht möglich.",
                  "Für den Schadensersatzanspruch gegen den Betriebsinhaber ist das Verschulden des Angestellten maßgeblich."],
                 merke="§ 14 Abs. 7: Der Betriebsinhaber haftet ohne Entlastungsmöglichkeit.",
                 level=2, concepts=["schadensersatz", "unterlassungsanspruch"], norms=["§ 14 Abs. 7"]),
            mc("k09a-4", "Annexansprüche",
               "Welcher Anspruch dient dazu, den Schadensersatz überhaupt beziffern zu können, und richtet sich bei offensichtlicher Verletzung auch gegen Spediteure und Lagerhalter?",
               ["Vernichtungsanspruch (§ 18 Abs. 1)", "Auskunftsanspruch (§ 19)", "Rückrufanspruch (§ 18 Abs. 2)", "Urteilsbekanntmachung (§ 19c)"], 1,
               ["Der **Auskunftsanspruch** nach § 19 verpflichtet den Verletzer zur Auskunft über Herkunft und Vertriebsweg der Waren (Abs. 1, 3); bei offensichtlicher Verletzung auch Dritte wie Spediteure, Lagerhalter oder Plattformbetreiber (Abs. 2). Im Eilverfahren durchsetzbar (Abs. 7).",
                "Daneben: Vernichtung und Rückruf (§ 18, mit Verhältnismäßigkeitsvorbehalt in Abs. 3), Vorlage und Besichtigung (§ 19a), Sicherung (§ 19b), Urteilsbekanntmachung (§ 19c). Alle setzen kein Verschulden voraus."],
               concepts=["vernichtung_auskunft"], norms=["§ 18", "§ 19"], step="step:schema_markenverletzung.6.2"),
        ]),
        dict(id="k09b", titel="Täter, Teilnehmer, Störer", einheiten=[
            fall("k09b-1", "Die Auktionsplattform",
                 "Auf einer Internet-Auktionsplattform bieten Dritte gefälschte Uhren an. Der Markeninhaber weist den Betreiber auf ein konkretes, klar erkennbares Fälschungsangebot hin. Der Betreiber sperrt es, unternimmt aber nichts gegen gleichartige neue Angebote.",
                 "Haftet der Plattformbetreiber auf Unterlassung?", True,
                 ["**Ja, als Störer!** Störer ist, wer willentlich und adäquat kausal zur Verletzung beiträgt und **zumutbare Prüfpflichten** verletzt. Nach dem Hinweis auf eine klare Rechtsverletzung muss der Betreiber nicht nur das Angebot sperren, sondern auch dafür sorgen, dass es nicht zu weiteren gleichartigen Verletzungen kommt (BGH Internet-Versteigerung II).",
                  "Der Störer haftet nur auf Unterlassung, nicht auf Schadensersatz. Eine allgemeine Pflicht, alle Angebote manuell zu prüfen, besteht nicht (BGH Kinderhochstühle im Internet)."],
                 merke="Störer: Prüfpflicht erst ab Hinweis, nur Unterlassung.",
                 level=2, concepts=["stoererhaftung"], norms=["§ 14 Abs. 5"], cases=["bgh_internet_versteigerung_ii", "bgh_kinderhochstuehle"]),
            fall("k09b-2", "Nachfüllware für Markenspender",
                 "Hersteller N verkauft Papierhandtücher als „passend auch für Tork-Spender“. Kunden befüllen damit ihre mit der Marke „Tork“ gekennzeichneten Spender in Waschräumen, wo Nutzer die Handtücher dem Markeninhaber zuordnen.",
                 "Ist N Täter einer Markenverletzung?", False,
                 ["**Nein!** Täter ist, wer die Verletzungshandlung selbst begeht. Das Befüllen des markierten Spenders mit Fremdware nehmen die **Kunden** vor; N handelt insoweit nicht selbst (BGH Tork).",
                  "In Betracht kommt aber eine **Teilnahme** (Beihilfe), wenn N vorsätzlich an einer vorsätzlichen Haupttat der Kunden mitwirkt, oder eine Störerhaftung. Für den Hinweis „passend für“ gilt zudem § 23 Abs. 1 Nr. 3."],
                 merke="Wer nur liefert, ist kein Täter; er kann aber Teilnehmer oder Störer sein.",
                 level=3, concepts=["stoererhaftung", "ersatzteilhinweis"], norms=["§ 14 Abs. 2 Nr. 1", "§ 23 Abs. 1 Nr. 3"], cases=["bgh_tork"]),
            mc("k09b-3", "Wer haftet auf Schadensersatz?",
               "Welche Aussage ist richtig?",
               ["Täter, Teilnehmer und Störer haften alle auf Schadensersatz", "Täter und Teilnehmer haften bei Verschulden auf Schadensersatz, der Störer nur auf Unterlassung", "Nur der Täter haftet überhaupt", "Der Störer haftet nur auf Schadensersatz, nicht auf Unterlassung"], 1,
               ["**Täter und Teilnehmer** haften bei Verschulden auf Schadensersatz (§ 14 Abs. 6) und auf die Annexansprüche. Der **Störer** haftet dagegen nur auf Unterlassung und Beseitigung, weil ihm kein eigenes Verschulden an der Haupttat vorgeworfen wird, sondern nur die Verletzung von Prüfpflichten.",
                "Im Lauterkeitsrecht hat der BGH die Störerhaftung aufgegeben, im Markenrecht besteht sie fort (Kinderhochstühle im Internet)."],
               level=2, concepts=["stoererhaftung", "schadensersatz"], cases=["bgh_kinderhochstuehle"]),
        ]),
    ],
)
