# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k10", titel="Unionsmarke und IR-Marke", untertitel="UMV, § 125b ff. und §§ 112 bis 125 MarkenG",
    farbe="#2b3fb4", icon="europa",
    beschreibung="Vorgehen aus einer Unionsmarke oder einer international registrierten Marke in Deutschland: Normketten, Bekanntheit in der Union, Benutzung, Gerichte und Fristen.",
    kapitel=[
        dict(id="k10a", titel="Die Unionsmarke", einheiten=[
            schema("k10a-0", "Prüfungsschema: Vorgehen aus einer Unionsmarke", "schema_unionsmarke",
                   "Die UMV gilt unmittelbar; das MarkenG kommt nur über die Brücke des § 125b ins Spiel."),
            fall("k10a-1", "Bekannt in Österreich",
                 "Die Unionsmarke „PAGO“ für Fruchtsäfte ist in Österreich sehr bekannt, im Rest der EU kaum. Ein österreichischer Konkurrent verwendet ein ähnliches Zeichen.",
                 "Ist „PAGO“ eine in der Union bekannte Marke im Sinne des Art. 9 Abs. 2 lit. c UMV?", True,
                 ["**Ja!** Eine Unionsmarke ist in der Union bekannt, wenn sie einem bedeutenden Teil des Publikums in einem **wesentlichen Teil des Unionsgebiets** bekannt ist. Das Gebiet eines einzigen Mitgliedstaats kann ein wesentlicher Teil sein (EuGH PAGO).",
                  "Der Bekanntheitsschutz der Unionsmarke gilt dann unionsweit, auch in Mitgliedstaaten, in denen die Marke unbekannt ist, sofern dort eine gedankliche Verknüpfung möglich ist."],
                 merke="Ein Mitgliedstaat kann für die Bekanntheit in der Union reichen.",
                 level=2, concepts=["bekanntheit_union", "bekannte_marke"], norms=["§ 125b"], cases=["eugh_pago"]),
            fall("k10a-2", "Bekannt in der Union, unbekannt in Deutschland",
                 "Der Inhaber einer Unionsmarke, die in Italien und Frankreich bekannt ist, in Deutschland aber niemand kennt, geht nach § 9 Abs. 1 Nr. 3 gegen eine jüngere deutsche Marke vor.",
                 "Genügt die Bekanntheit in Italien und Frankreich für den Erfolg des Antrags?", False,
                 ["**Nur für die erste Stufe!** Nach § 125b Nr. 1 tritt an die Stelle der Bekanntheit im Inland die **Bekanntheit in der Union**; ein wesentlicher Teil der Union genügt, auch wenn Deutschland nicht dazugehört (EuGH Iron & Smith).",
                  "Für die Ausnutzung oder Beeinträchtigung **in Deutschland** muss die Unionsmarke aber einem wirtschaftlich nicht unbedeutenden Teil des deutschen Publikums bekannt sein, sonst fehlt die gedankliche Verknüpfung im Kollisionsgebiet. Kennt in Deutschland niemand die Marke, scheitert der Antrag."],
                 merke="Zwei Stufen: Bekanntheit in der Union (Tatbestand) plus Bekanntheit beim deutschen Publikum (Verknüpfung).",
                 level=3, concepts=["bekanntheit_union", "relative_schutzhindernis_bekannt", "gedankliche_verknuepfung"], norms=["§ 125b", "§ 9 Abs. 1 Nr. 3"], cases=["eugh_iron_smith"], step="step:schema_relative_schutzhindernisse.4.3.1"),
            fall("k10a-3", "Benutzung nur in den Niederlanden",
                 "Die Unionsmarke „ONEL“ wird seit Jahren nur in den Niederlanden ernsthaft benutzt. Der Inhaber legt aus ihr Widerspruch gegen eine deutsche Marke ein; der Gegner erhebt die Nichtbenutzungseinrede.",
                 "Genügt die Benutzung in einem einzigen Mitgliedstaat?", True,
                 ["**Ja, grundsätzlich!** Bei der ernsthaften Benutzung einer Unionsmarke nach Art. 18 UMV sind die **Grenzen der Mitgliedstaaten außer Betracht** zu lassen. Die Benutzung in einem Mitgliedstaat kann ausreichen, wenn sie nach Markt, Waren und Umfang geeignet ist, Marktanteile in der Union zu halten oder zu gewinnen (EuGH Leno Merken).",
                  "Im deutschen Widerspruchsverfahren ordnet § 125b Nr. 4 an, dass Art. 18 UMV an die Stelle des § 26 tritt."],
                 merke="Art. 18 UMV: Union ist ein Markt, Landesgrenzen zählen nicht.",
                 level=2, concepts=["benutzung_union"], norms=["§ 125b", "§ 43 Abs. 1"], cases=["eugh_leno_merken"], step="step:schema_unionsmarke.3.2"),
            fall("k10a-4", "Das unionsweite Verbot",
                 "Ein Unionsmarkengericht in Frankreich stellt fest, dass DHL die Unionsmarke „WEBSHIPPING“ von Chronopost verletzt, und spricht ein Verbot aus. DHL meint, das Verbot gelte nur in Frankreich.",
                 "Wirkt das Verbot grundsätzlich für die gesamte Union?", True,
                 ["**Ja!** Ein von einem Unionsmarkengericht ausgesprochenes Verbot erstreckt sich **grundsätzlich auf das gesamte Gebiet der Union**, ebenso die Zwangsmaßnahmen zu seiner Durchsetzung (EuGH DHL/Chronopost). Das folgt aus der Einheitlichkeit der Unionsmarke.",
                  "Grenzen: Das Gericht muss das Verbot beschränken, wenn die Verletzung nur in einem Teil der Union vorliegt, etwa weil Verwechslungsgefahr nur in bestimmten Sprachräumen besteht (EuGH combit), oder wenn der Kläger sein Begehren beschränkt. Zuständig nach Art. 125 Abs. 5 (Handlungsort) ist die Kognition ohnehin auf den Mitgliedstaat beschränkt (Art. 126 Abs. 2)."],
                 merke="Unionsweit ist die Regel, territorial beschränkt die begründete Ausnahme.",
                 level=3, concepts=["unionsmarkengericht"], norms=["§ 125e"], cases=["eugh_dhl_chronopost", "eugh_combit"], step="step:schema_unionsmarke.2.4"),
            mc("k10a-5", "Die Brücke § 125b",
               "Der Inhaber einer Unionsmarke verlangt vor dem Landgericht Vernichtung der Plagiate und Auskunft. Die UMV regelt diese Ansprüche nicht selbst. Woraus ergeben sie sich?",
               ["Aus Art. 9 UMV direkt", "Aus §§ 18, 19 MarkenG über § 125b Nr. 2", "Aus dem UWG", "Gar nicht, nur Unterlassung ist möglich"], 1,
               ["§ 125b Nr. 2 stellt dem Inhaber einer eingetragenen Unionsmarke neben den Ansprüchen aus Art. 9 bis 11 UMV die Ansprüche auf **Schadensersatz, Vernichtung und Rückruf (§ 18), Auskunft (§ 19), Vorlage (§ 19a), Sicherung (§ 19b) und Urteilsbekanntmachung (§ 19c)** zur Verfügung. Art. 129 UMV verweist für nicht geregelte Fragen auf nationales Recht.",
                "Zuständig sind ausschließlich die Unionsmarkengerichte, in Deutschland bestimmte Landgerichte (§ 125e)."],
               level=2, concepts=["unionsmarke", "unionsmarkengericht", "vernichtung_auskunft"], norms=["§ 125b", "§ 125e"], step="step:schema_unionsmarke.2.4"),
        ]),
        dict(id="k10b", titel="Die IR-Marke", einheiten=[
            schema("k10b-0", "Prüfungsschema: Vorgehen aus einer IR-Marke", "schema_ir_marke",
                   "Die IR-Marke mit Schutzerstreckung auf Deutschland wirkt wie eine deutsche Marke. Die Besonderheiten liegen bei Fristen und Schutzverweigerung."),
            fall("k10b-1", "Wirkung wie eine deutsche Marke",
                 "Ein Schweizer Unternehmen hat seine Marke über die WIPO international registriert und auf Deutschland erstreckt. Das DPMA hat keine Schutzverweigerung ausgesprochen. Nun kopiert ein deutscher Händler das Zeichen.",
                 "Kann das Unternehmen direkt aus § 14 gegen den Händler vorgehen?", True,
                 ["**Ja!** Die auf Deutschland erstreckte IR-Marke hat **dieselbe Wirkung**, wie wenn sie am Tag der internationalen Registrierung beim DPMA angemeldet und eingetragen worden wäre (§ 112 Abs. 1, für Protokollmarken über § 124). §§ 14 ff. gelten unmittelbar.",
                  "Zeitrang ist der Tag der internationalen Registrierung bzw. der nachträglichen Schutzerstreckung (Art. 3ter PMMA). Die Wirkung entfällt nur, wenn der Schutz nach §§ 113 bis 115 verweigert wird (§ 112 Abs. 2)."],
                 merke="IR-Marke (DE) = deutsche Marke mit dem Zeitrang der internationalen Registrierung.",
                 concepts=["ir_marke"], norms=["§ 112", "§ 124"], step="step:schema_ir_marke.2"),
            mc("k10b-2", "Wann beginnt die Schonfrist der IR-Marke?",
               "Eine IR-Marke wurde am 1. Juni 2019 international registriert. Die Schutzverweigerungsfrist des DPMA lief am 1. Dezember 2020 ab, ohne dass Schutz verweigert wurde. Ab wann läuft die fünfjährige Benutzungsschonfrist?",
               ["Ab 1. Juni 2019", "Ab 1. Dezember 2020", "Ab Eintragung der Basismarke", "Ab der ersten Benutzung in Deutschland"], 1,
               ["Für IR-Marken tritt an die Stelle des Eintragungstags einer der in **§ 115 Abs. 2** genannten Tage: der Ablauf der Schutzverweigerungsfrist nach Art. 5 Abs. 2 PMMA oder, bei zunächst verweigertem Schutz, der Tag der rechtskräftigen Schutzgewährung. Darauf verweisen § 116 (Widerspruch, Nichtigkeit) und § 117 (Einrede nach § 25).",
                "Die Schonfrist beginnt also nicht mit der internationalen Registrierung, sondern erst, wenn der Schutz in Deutschland feststeht."],
               level=2, concepts=["ir_benutzungsschonfrist"], norms=["§ 115", "§ 116", "§ 117"], step="step:schema_ir_marke.5"),
            fall("k10b-3", "Widerspruch gegen die IR-Marke",
                 "Die Inhaberin einer deutschen Marke will gegen eine auf Deutschland erstreckte IR-Marke vorgehen. Sie sucht im DPMA-Register nach der Veröffentlichung der Eintragung, um die Widerspruchsfrist zu berechnen.",
                 "Läuft die Widerspruchsfrist ab der Veröffentlichung im deutschen Markenblatt?", False,
                 ["**Nein!** Bei IR-Marken tritt an die Stelle der Veröffentlichung der Eintragung die Veröffentlichung in der **WIPO-Gazette** (§ 114 Abs. 1). Die Widerspruchsfrist beginnt mit dem ersten Tag des Monats, der dem Ausgabemonat des Gazette-Hefts folgt (§ 114 Abs. 2).",
                  "Rechtsfolge eines erfolgreichen Widerspruchs ist nicht die Löschung, sondern die **Schutzverweigerung** für Deutschland (§ 114 Abs. 3); bei Verfall oder Nichtigkeit die nachträgliche Schutzentziehung (§ 115)."],
                 merke="IR-Marke: Gazette statt Markenblatt, Schutzverweigerung statt Löschung.",
                 level=2, concepts=["ir_schutzverweigerung", "widerspruch"], norms=["§ 114", "§ 115"], step="step:schema_ir_marke.3.2"),
            fall("k10b-4", "Der Angriff auf die Basismarke",
                 "Drei Jahre nach der internationalen Registrierung wird die Basismarke im Ursprungsland rechtskräftig gelöscht.",
                 "Bleibt die deutsche Schutzerstreckung der IR-Marke davon unberührt?", False,
                 ["**Nein!** Während der ersten **fünf Jahre** ab der internationalen Registrierung ist die IR-Marke von der Basismarke abhängig: Wird diese gelöscht, entfällt auch die internationale Registrierung mit allen Erstreckungen (Art. 6 PMMA, sogenannter „central attack“).",
                  "Der Inhaber kann die IR-Marke dann innerhalb von drei Monaten in nationale Anmeldungen **umwandeln** und den Zeitrang der internationalen Registrierung behalten (Art. 9quinquies PMMA, § 125). Eine IR-Marke mit Benennung EU wird dabei wie eine Unionsmarke behandelt (Art. 189 ff. UMV)."],
                 merke="Fünf Jahre Abhängigkeit, dann Selbständigkeit; Rettung durch Umwandlung.",
                 level=3, concepts=["ir_marke", "senioritaet"], norms=["§ 125"], step="step:schema_ir_marke.3.4"),
        ]),
    ],
)
