# -*- coding: utf-8 -*-
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k11", gebiet="eu", titel="Die Markenrechtsrichtlinie (EU) 2015/2436", untertitel="Der unionsrechtliche Bauplan des MarkenG",
    farbe="#0c8599", icon="europa",
    beschreibung="Aufbau und Inhalt der Richtlinie, ihre Umsetzung durch das MaMoG 2019, richtlinienkonforme Auslegung und die Neuerungen: Transit, Vorbereitungshandlungen, Namensschranke, Schonfrist, Amtsverfahren.",
    kapitel=[
        dict(id="k11a", titel="Struktur, Harmonisierung, Auslegung", einheiten=[
            intro("k11a-0", "Warum du die Richtlinie kennen musst",
                  "Fast jede Norm des MarkenG hat einen Zwilling in der **Markenrechtsrichtlinie (EU) 2015/2436**. Sie harmonisiert das materielle Markenrecht aller Mitgliedstaaten und seit 2019 auch zentrale Verfahren. Deutschland hat sie mit dem Markenrechtsmodernisierungsgesetz (MaMoG) umgesetzt. Praktische Folge: Begriffe wie Unterscheidungskraft, Verwechslungsgefahr oder ernsthafte Benutzung bedeuten in allen Mitgliedstaaten dasselbe, und das letzte Wort hat der EuGH. Dieser Kurs zeigt dir den Aufbau der Richtlinie und die Stellen, an denen sie das MarkenG geprägt oder verändert hat.",
                  concepts=["markenrl", "richtlinienkonforme_auslegung"], norms=["Art. 1 MarkenRL", "Art. 54 MarkenRL"]),
            schema("k11a-1", "Prüfungsschema: Markenrechtsrichtlinie anwenden", "schema_markenrl",
                   "Verschaffe dir zuerst den Überblick über die Kapitel der Richtlinie und die Umsetzungstabelle."),
            fall("k11a-2", "Die Benutzungsmarke und Brüssel",
                 "Bäckerin Bea hat durch jahrelange Benutzung eine Benutzungsmarke „KRUSTIS“ nach § 4 Nr. 2 MarkenG erworben. Ein Konkurrent meint, Benutzungsmarken seien unionsrechtswidrig, weil die MarkenRL nur eingetragene Marken kenne.",
                 "Verstößt § 4 Nr. 2 MarkenG gegen die Markenrechtsrichtlinie?", False,
                 ["**Nein!** Die Richtlinie gilt nach Art. 1 MarkenRL nur für **eingetragene oder angemeldete** Marken und IR-Marken mit Wirkung im Mitgliedstaat. Benutzungsmarken, geschäftliche Bezeichnungen (§ 5) und die Rechtsfolgen der Verletzung sind nicht harmonisiert.",
                  "In diesen Bereichen bleibt das nationale Recht frei; die Richtlinie erwähnt Benutzungsmarken nur als fakultatives relatives Eintragungshindernis (Art. 5 Abs. 4 lit. a MarkenRL, umgesetzt in § 12 MarkenG)."],
                 merke="Harmonisiert ist die Registermarke, nicht das ganze Kennzeichenrecht.",
                 concepts=["markenrl", "verkehrsgeltung"], norms=["Art. 1 MarkenRL", "Art. 5 MarkenRL", "§ 4 Nr. 2", "§ 12"]),
            mc("k11a-3", "Wer legt die Begriffe aus?",
               "Der BGH ist unsicher, ob bei der Prüfung der Unterscheidungskraft eines Zeichens auf T-Shirts nur die wahrscheinlichste Verwendungsform zählt. Was muss er tun?",
               ["Er entscheidet nach deutscher Tradition, weil § 8 MarkenG deutsches Recht ist", "Er muss die Frage dem EuGH vorlegen, weil die Unterscheidungskraft ein unionsrechtlicher Begriff aus Art. 4 MarkenRL ist und er letztinstanzlich entscheidet", "Er fragt das DPMA", "Er setzt das Verfahren aus, bis die Kommission eine Leitlinie erlässt"], 1,
               ["Die Unterscheidungskraft ist in Art. 4 Abs. 1 lit. b MarkenRL geregelt; § 8 Abs. 2 Nr. 1 MarkenG setzt sie um und ist **richtlinienkonform** auszulegen. Als letztinstanzliches Gericht ist der BGH nach Art. 267 Abs. 3 AEUV zur **Vorlage** verpflichtet, wenn die Auslegung nicht offenkundig oder bereits geklärt ist.",
                "Genau das geschah in #darferdas?: EuGH C-541/18 entschied, dass alle praktisch bedeutsamen Verwendungsarten zu berücksichtigen sind; der BGH setzte das um (#darferdas? II)."],
               level=2, concepts=["richtlinienkonforme_auslegung", "verwendungsformen"], norms=["Art. 4 MarkenRL", "§ 8 Abs. 2 Nr. 1"], cases=["eugh_darferdas", "bgh_darferdas_ii"], step="step:schema_markenrl.5"),
            fall("k11a-4", "Ein Urteil zur Unionsmarke für das MarkenG",
                 "Der EuGH hat in einem Fall zur Unionsmarkenverordnung entschieden, wie die selbständig kennzeichnende Stellung zu prüfen ist. Ein Landgericht muss nun einen Fall nach § 14 Abs. 2 Nr. 2 MarkenG entscheiden.",
                 "Darf das Landgericht die EuGH-Rechtsprechung zur UMV auf das MarkenG übertragen?", True,
                 ["**Ja!** Art. 10 Abs. 2 lit. b MarkenRL und Art. 9 Abs. 2 lit. b UMV sind wortgleich formuliert; der EuGH legt beide **einheitlich** aus. Rechtsprechung zur Unionsmarke ist deshalb regelmäßig auf das richtlinienkonform auszulegende MarkenG übertragbar und umgekehrt.",
                  "Beispiel: THOMSON LIFE erging zu Art. 5 Abs. 1 lit. b der alten Markenrichtlinie und prägt seither auch die Auslegung von Art. 9 UMV."],
                 merke="MarkenRL und UMV laufen parallel: EuGH-Urteile gelten für beide Welten.",
                 level=2, concepts=["richtlinienkonforme_auslegung", "unionsmarke", "selbstaendig_kennzeichnende_stellung"], norms=["Art. 10 MarkenRL"], cases=["eugh_thomson_life"], step="step:schema_markenrl.4"),
            mc("k11a-5", "Umsetzungsfristen",
               "Bis wann mussten die Mitgliedstaaten die MarkenRL umsetzen, und welche Ausnahme gab es?",
               ["Bis 15.1.2016 vollständig", "Bis 14.1.2019; nur das Verwaltungsverfahren für Verfall und Nichtigkeit (Art. 45) erst bis 14.1.2023", "Bis 1.5.2020 vollständig", "Es gab keine Frist, Richtlinien gelten unmittelbar"], 1,
               ["Art. 54 MarkenRL setzt die allgemeine Umsetzungsfrist auf den **14. Januar 2019**; für das verwaltungsbehördliche Verfalls- und Nichtigkeitsverfahren nach Art. 45 galt eine verlängerte Frist bis zum **14. Januar 2023**.",
                "Deutschland: MaMoG vom 11.12.2018, in Kraft seit 14.1.2019; das DPMA-Verfahren nach § 53 MarkenG gilt seit 1.5.2020. Richtlinien gelten nicht unmittelbar zwischen Privaten; sie wirken über die Umsetzung und die richtlinienkonforme Auslegung."],
               concepts=["markenrl", "verwaltungsverfahren_loeschung"], norms=["Art. 54 MarkenRL", "Art. 45 MarkenRL", "§ 53"], step="step:schema_markenrl.6"),
        ]),
        dict(id="k11b", titel="Materielles Recht: Art. 3 bis 18", einheiten=[
            fall("k11b-1", "Die Klangmarke als Audiodatei",
                 "Ein Radiosender will seine Erkennungsmelodie als Marke anmelden und reicht statt einer Notenschrift eine MP3-Datei ein.",
                 "Muss die Anmeldung zurückgewiesen werden, weil eine Audiodatei keine graphische Darstellung ist?", False,
                 ["**Nein!** Art. 3 lit. b MarkenRL verlangt nur noch, dass das Zeichen im Register so **dargestellt** werden kann, dass Behörden und Publikum den Schutzgegenstand klar und eindeutig bestimmen können. Das Erfordernis der graphischen Darstellbarkeit ist entfallen; § 8 Abs. 1 MarkenG wurde entsprechend gefasst.",
                  "Maßstab bleiben die Sieckmann-Kriterien (klar, eindeutig, in sich abgeschlossen, leicht zugänglich, verständlich, dauerhaft, objektiv). Eine Audiodatei erfüllt sie für Klangmarken; auch Bewegungs-, Multimedia- und Hologrammmarken sind so anmeldbar."],
                 merke="Darstellbar, nicht mehr graphisch darstellbar: Die Technik darf helfen, die Bestimmtheit bleibt Pflicht.",
                 concepts=["darstellbarkeit", "markenfaehigkeit"], norms=["Art. 3 MarkenRL", "§ 8 Abs. 1"]),
            fall("k11b-2", "Der technisch bedingte Farbverlauf",
                 "Ein Hersteller meldet für Reflektoren ein Zeichen an, das ausschließlich aus einem bestimmten Farbmuster besteht, das die Reflexionswirkung technisch bedingt.",
                 "Greift der Formausschluss, obwohl es sich nicht um eine Form handelt?", True,
                 ["**Ja!** Art. 4 Abs. 1 lit. e MarkenRL erstreckt den Ausschluss ausdrücklich auf Zeichen, die ausschließlich aus der Form **oder einem anderen charakteristischen Merkmal** bestehen, das technisch erforderlich ist. § 3 Abs. 2 MarkenG wurde im MaMoG entsprechend erweitert.",
                  "Damit lässt sich der Ausschluss nicht mehr umgehen, indem man statt der Form ein anderes funktionales Merkmal (Farbe, Muster, Klang) anmeldet. Verkehrsdurchsetzung hilft hier nicht (Art. 4 Abs. 4 gilt nur für lit. b bis d)."],
                 merke="Funktional ist funktional: Form oder anderes Merkmal, beides gesperrt.",
                 level=2, concepts=["formausschluss"], norms=["Art. 4 MarkenRL", "§ 3 Abs. 2"], cases=["eugh_philips_remington", "bgh_bodenduebel"]),
            fall("k11b-3", "Bösgläubigkeit als Pflichtgrund",
                 "Ein Mitgliedstaat hat in seinem Markengesetz keinen Nichtigkeitsgrund für bösgläubige Anmeldungen vorgesehen.",
                 "Ist das mit der Richtlinie vereinbar?", False,
                 ["**Nein!** Nach Art. 4 Abs. 2 MarkenRL **ist** eine Marke für ungültig zu erklären, wenn der Anmelder bösgläubig war; nur die Ausgestaltung als Eintragungshindernis ist fakultativ. In Deutschland: § 8 Abs. 2 Nr. 14 MarkenG (Zurückweisung, wenn ersichtlich, § 37 Abs. 3) und § 50 (Nichtigkeit).",
                  "Fakultativ bleiben nach Art. 4 Abs. 3 nur der Verstoß gegen sonstiges Recht, religiöse Symbole und nationale Embleme."],
                 merke="Bösgläubigkeit: zwingender Nichtigkeitsgrund, optionales Eintragungshindernis.",
                 level=2, concepts=["boesglaeubigkeit"], norms=["Art. 4 MarkenRL", "§ 8 Abs. 2 Nr. 14", "§ 50"], cases=["bgh_glueckspilz"]),
            fall("k11b-4", "Der Container im Hamburger Hafen",
                 "Im Hamburger Hafen wird ein Container mit gefälschten Markenturnschuhen aus China entdeckt, der für Brasilien bestimmt ist. Die Ware soll in Deutschland nicht verkauft werden.",
                 "Kann der Markeninhaber gegen die Durchfuhr vorgehen?", True,
                 ["**Ja, grundsätzlich!** Nach Art. 10 Abs. 4 MarkenRL, umgesetzt in § 14a MarkenG, kann der Inhaber verhindern, dass Waren aus Drittstaaten mit identischer Marke unter zollamtlicher Überwachung ins Inland verbracht werden, auch **ohne Inverkehrbringen** im Inland (Transit). Das korrigiert die frühere EuGH-Linie (Philips/Nokia), nach der bloßer Transit nicht verletzte.",
                  "Das Recht erlischt, wenn der Anmelder oder Besitzer der Ware nachweist, dass der Inhaber die Vermarktung im **Bestimmungsland** (Brasilien) nicht verbieten könnte (§ 14a Abs. 2). Durchsetzung über die Grenzbeschlagnahme (§§ 146 ff.)."],
                 merke="Transit ist Verletzung, es sei denn, im Zielland wäre der Vertrieb legal.",
                 level=2, concepts=["transit", "doppelidentitaet"], norms=["Art. 10 MarkenRL", "§ 14a", "§ 146"]),
            fall("k11b-5", "Der Etikettenhändler",
                 "Ein Händler verkauft gewebte Etiketten mit dem Logo eines Sportartikelherstellers an Textilfabriken, ohne selbst Kleidung zu produzieren. Die Etiketten sind erkennbar für Plagiate bestimmt.",
                 "Verletzt der Etikettenhändler die Marke, obwohl er sie auf keiner Ware anbringt?", True,
                 ["**Ja!** Art. 11 MarkenRL, umgesetzt in § 14 Abs. 4 MarkenG, verbietet **Vorbereitungshandlungen**: das Anbringen der Marke auf Etiketten, Verpackungen, Anhängern oder Echtheitshinweisen sowie deren Anbieten, Inverkehrbringen, Besitz, Ein- und Ausfuhr, wenn die Gefahr besteht, dass sie für eine verletzende Kennzeichnung benutzt werden.",
                  "Der Markenschutz greift damit schon eine Stufe vor der eigentlichen Kennzeichnung der Ware."],
                 merke="Wer die Etiketten liefert, verletzt schon, bevor jemand sie aufnäht.",
                 level=2, concepts=["vorbereitungshandlungen"], norms=["Art. 11 MarkenRL", "§ 14 Abs. 4"]),
            fall("k11b-6", "Die GmbH mit Familiennamen",
                 "Die „Müller Werkzeuge GmbH“ vertreibt Werkzeuge unter ihrem Firmennamen. Inhaberin der älteren Werkzeugmarke „MÜLLER“ ist eine andere Firma. Die GmbH beruft sich auf die Namensschranke.",
                 "Kann sich die GmbH auf § 23 Abs. 1 Nr. 1 MarkenG (Name) berufen?", False,
                 ["**Nein!** Art. 14 Abs. 1 lit. a MarkenRL privilegiert nur den Namen oder die Anschrift des Dritten, **wenn dieser eine natürliche Person ist**. § 23 Abs. 1 Nr. 1 MarkenG wurde entsprechend eingeschränkt. Juristische Personen können ihren Firmennamen nicht über die Namensschranke gegen eine ältere Marke verteidigen.",
                  "Bleibt: die beschreibende Benutzung (Nr. 2), das Recht der Gleichnamigen bei redlichem Namensgebrauch natürlicher Personen und die Prioritätsfrage nach § 6, falls das Unternehmenskennzeichen älter ist."],
                 merke="Die Namensschranke schützt Menschen, nicht Gesellschaften.",
                 level=3, concepts=["schranke_23", "gleichnamigkeit"], norms=["Art. 14 MarkenRL", "§ 23 Abs. 1 Nr. 1"]),
            fall("k11b-7", "Die Schonfrist nach dem Widerspruch",
                 "Die Marke „ORBIS“ wurde am 1.3.2019 eingetragen. Gegen die Eintragung wurde Widerspruch erhoben, der erst am 1.9.2020 rechtskräftig zurückgewiesen wurde. Am 1.6.2024 erhebt ein Verletzer die Nichtbenutzungseinrede.",
                 "Ist die Einrede beachtlich?", False,
                 ["**Nein!** Nach Art. 16 Abs. 2 MarkenRL beginnt die fünfjährige Benutzungsschonfrist bei einem Widerspruchsverfahren erst mit dem Tag, an dem das Verfahren **abgeschlossen** ist. § 26 Abs. 5 MarkenG setzt das um. Die Frist läuft hier also bis zum 1.9.2025.",
                  "Für IR-Marken gilt entsprechend der Ablauf der Schutzverweigerungsfrist oder die rechtskräftige Schutzgewährung (Art. 16 Abs. 3, § 115 Abs. 2 MarkenG). Der Fristbeginn wird im Register vermerkt (Art. 16 Abs. 4)."],
                 merke="Erst wenn die Marke unangreifbar im Register steht, tickt die Benutzungsuhr.",
                 level=2, concepts=["benutzungsschonfrist", "nichtbenutzungseinrede"], norms=["Art. 16 MarkenRL", "§ 26 Abs. 5", "§ 25"]),
            fall("k11b-8", "Zwei Marken, beide eingetragen",
                 "Anna ist Inhaberin der Marke „VELA“ (2012). Ben hat „VELA“ 2016 für ähnliche Waren eingetragen; damals hatte Annas Marke nur geringe Kennzeichnungskraft und es bestand keine Verwechslungsgefahr. Inzwischen ist Annas Marke stark und verwechslungsfähig. Anna klagt auf Unterlassung.",
                 "Kann Anna Ben die Benutzung seiner eingetragenen Marke verbieten?", False,
                 ["**Nein!** Art. 18 MarkenRL (Zwischenrecht) und Art. 8 MarkenRL ordnen an: Der Inhaber der älteren Marke kann die Benutzung einer später eingetragenen Marke nicht verbieten, wenn diese am **Prioritätstag** nicht für ungültig erklärt werden konnte, etwa weil damals noch keine Verwechslungsgefahr bestand. § 22 Abs. 1 Nr. 3 und § 51 Abs. 4 S. 2 MarkenG setzen das um.",
                  "Umgekehrt kann auch Ben Anna nichts verbieten (Art. 18 Abs. 3, § 22 Abs. 2): beide koexistieren. Die Kennzeichnungskraft der älteren Marke wird damit „eingefroren“ auf den Zeitpunkt der jüngeren Anmeldung."],
                 merke="Was am Anmeldetag der jüngeren Marke nicht kollidierte, kollidiert auch später nicht.",
                 level=3, concepts=["koexistenz_22", "kennzeichnungskraft"], norms=["Art. 18 MarkenRL", "Art. 8 MarkenRL", "§ 22", "§ 51 Abs. 4"]),
        ]),
        dict(id="k11c", titel="Verfahren und Umsetzung im MaMoG", einheiten=[
            mc("k11c-1", "Der Klassenkopf",
               "Eine Marke ist für „Klasse 25: Bekleidungsstücke, Schuhwaren, Kopfbedeckungen“ eingetragen. Welche Waren sind erfasst?",
               ["Alle Waren der Klasse 25 nach der alphabetischen Liste", "Nur die Waren, die von der wörtlichen Bedeutung der genannten Begriffe eindeutig erfasst sind", "Alle Textilien in allen Klassen", "Gar keine, weil Klassenüberschriften unzulässig sind"], 1,
               ["Nach Art. 39 Abs. 5 MarkenRL umfassen allgemeine Begriffe einschließlich der Klassenüberschriften **nur die Waren, die eindeutig von ihrer wörtlichen Bedeutung erfasst sind** (Kodifizierung von EuGH IP Translator, C-307/10). Eine Vermutung, dass alle Waren der Klasse gemeint sind, besteht nicht (Abs. 6).",
                "Die Zugehörigkeit zur selben Klasse begründet keine Warenähnlichkeit, verschiedene Klassen keine Unähnlichkeit (Art. 39 Abs. 7, § 9 Abs. 3 MarkenG)."],
               level=2, concepts=["klassifizierung", "warenaehnlichkeit"], norms=["Art. 39 MarkenRL", "§ 32", "§ 9 Abs. 3"]),
            fall("k11c-2", "Cooling-off im Widerspruch",
                 "Im Widerspruchsverfahren vor dem DPMA wollen beide Parteien in Ruhe über eine Abgrenzungsvereinbarung verhandeln und beantragen gemeinsam eine Verfahrensaussetzung.",
                 "Muss das DPMA den Parteien Zeit für eine gütliche Einigung einräumen?", True,
                 ["**Ja!** Art. 43 Abs. 3 MarkenRL verpflichtet die Ämter, den Parteien auf gemeinsamen Antrag eine Frist von **mindestens zwei Monaten** für eine gütliche Einigung einzuräumen. § 42 Abs. 4 MarkenG setzt das um (Cooling-off).",
                  "Weitere Neuerungen des Art. 43: Der Widerspruch kann auf mehrere ältere Rechte desselben Inhabers gestützt werden (§ 42 Abs. 3) und muss auch dem Inhaber einer bekannten Marke und dem Berechtigten einer Ursprungsbezeichnung offenstehen."],
                 merke="Zwei Monate Cooling-off sind Pflicht, wenn beide es wollen.",
                 concepts=["widerspruch"], norms=["Art. 43 MarkenRL", "§ 42 Abs. 4"]),
            fall("k11c-3", "Nichtigkeit ohne Gericht",
                 "Ein Wettbewerber will die Marke „AQUAFRESH“ wegen absoluter Schutzhindernisse löschen lassen und scheut die Kosten eines Gerichtsverfahrens.",
                 "Kann er die Nichtigkeit vollständig vor dem DPMA klären lassen?", True,
                 ["**Ja!** Art. 45 MarkenRL verpflichtet die Mitgliedstaaten zu einem effizienten **Verwaltungsverfahren** vor dem Amt für Verfall und Nichtigkeit. Deutschland hat es zum 1.5.2020 in § 53 MarkenG umgesetzt: Antrag, Zustellung, bei Widerspruch des Inhabers kontradiktorisches Verfahren mit Beschluss, Beschwerde zum BPatG.",
                  "Die Nichtigkeit wegen absoluter Schutzhindernisse (§ 50) ist seither **ausschließlich** dem DPMA zugewiesen; die Klage nach § 55 bleibt nur für Verfall (§ 49) und relative Nichtigkeit (§ 51)."],
                 merke="Art. 45: Löschung als Amtsverfahren, damit nicht jeder Streit vor Gericht muss.",
                 level=2, concepts=["verwaltungsverfahren_loeschung", "nichtigkeit"], norms=["Art. 45 MarkenRL", "§ 53", "§ 55"], cases=["bgh_black_friday"]),
            mc("k11c-4", "Zweimal fünf Jahre",
               "Im Nichtigkeitsverfahren aus einer älteren Marke war deren Schonfrist sowohl bei Antragstellung als auch schon am Anmeldetag der jüngeren Marke abgelaufen. Welche Benutzung muss der Antragsteller nachweisen?",
               ["Nur die fünf Jahre vor Antragstellung", "Nur die fünf Jahre vor dem Anmeldetag der jüngeren Marke", "Beide Zeiträume: fünf Jahre vor Antragstellung und fünf Jahre vor dem Anmeldetag der jüngeren Marke", "Gar keine, im Nichtigkeitsverfahren gibt es keine Einrede"], 2,
               ["Art. 46 Abs. 1 und 2 MarkenRL verlangen bei abgelaufener Schonfrist den Nachweis der ernsthaften Benutzung in den fünf Jahren **vor Antragstellung** und, wenn die Schonfrist schon am Anmeldetag der jüngeren Marke abgelaufen war, zusätzlich in den fünf Jahren **vor diesem Tag**. § 53 Abs. 6 und § 55 Abs. 3 MarkenG setzen das um.",
                "Im Widerspruchsverfahren gilt nach Art. 44 nur der Zeitraum vor dem Anmeldetag der jüngeren Marke (§ 43 Abs. 1 MarkenG)."],
               level=3, concepts=["nichtbenutzungseinrede", "verwaltungsverfahren_loeschung"], norms=["Art. 46 MarkenRL", "Art. 44 MarkenRL", "§ 53", "§ 43 Abs. 1"]),
            fall("k11c-4b", "Das Gütesiegel als Marke",
                 "Ein Prüfinstitut möchte sein Siegel „GEPRÜFTE QUALITÄT“ eintragen lassen. Es stellt selbst keine Waren her, sondern vergibt das Siegel an Hersteller, die seine Prüfkriterien erfüllen.",
                 "Gibt es dafür eine passende Markenkategorie?", True,
                 ["**Ja!** Art. 27 lit. a und Art. 28 MarkenRL ermöglichen die **Gewährleistungsmarke**: eine Marke, die Waren mit vom Inhaber gewährleisteten Eigenschaften (Material, Herstellung, Qualität) von anderen unterscheidet. Der Inhaber darf die gewährleisteten Waren nicht selbst anbieten (Art. 28 Abs. 2).",
                  "Deutschland hat die Option genutzt: §§ 106a ff. MarkenG mit Satzungspflicht (§ 106d). Die Benutzung durch Berechtigte ist rechtserhaltend (Art. 28 Abs. 5, § 106b)."],
                 merke="Gewährleistungsmarke: Neutralität des Inhabers ist Voraussetzung.",
                 level=2, concepts=["kollektivmarke"], norms=["Art. 28 MarkenRL", "§ 106a", "§ 106d"], cases=["bgh_oeko_test_ii"]),
            mc("k11c-5", "Was das MaMoG geändert hat",
               "Welche Aussage über das Markenrechtsmodernisierungsgesetz 2019 ist falsch?",
               ["Es hat die graphische Darstellbarkeit als Eintragungsvoraussetzung abgeschafft", "Es hat die Gewährleistungsmarke eingeführt", "Es hat die internationale Erschöpfung eingeführt", "Es hat die Namensschranke auf natürliche Personen beschränkt"], 2,
               ["Das MaMoG hat **keine** internationale Erschöpfung eingeführt; Art. 15 MarkenRL schreibt die unionsweite Erschöpfung fest und § 24 MarkenG blieb unverändert (keine Erschöpfung durch Inverkehrbringen in Drittstaaten).",
                "Richtig sind: Wegfall der graphischen Darstellbarkeit (Art. 3), Gewährleistungsmarke (Art. 28, §§ 106a ff.), Namensschranke nur für natürliche Personen (Art. 14, § 23). Weitere Änderungen: § 14a Transit, § 14 Abs. 4 Vorbereitungshandlungen, § 26 Abs. 5 Schonfrist, § 42 Abs. 4 Cooling-off, § 53 Amtsverfahren, § 47 tagesgenaue Schutzdauer."],
               level=2, concepts=["markenrl", "erschoepfung"], norms=["Art. 15 MarkenRL", "§ 24"]),
        ]),
    ],
)
