# -*- coding: utf-8 -*-
"""Kurs 13: Wirksamkeit und Zulässigkeit – Verfahrensrecht für die NS-Klausur.

Vertiefung zu Kurs 12: Die Zulässigkeitsprüfung wird für jede Verfahrensart getrennt
durchgespielt (Widerspruch, Erinnerung, Beschwerde, Rechtsbeschwerde, Amtsverfahren nach
§ 53, Klagen vor dem Landgericht). Bewusst mit den Anschlussnormen aus BGB, HGB, GmbHG,
ZPO, GVG, InsO und FamFG, weil die Klausur genau dort die Punkte verteilt.

Konvention: In `norms` stehen nur MarkenG-Normen, weil der Graph sonst abbricht.
Fremdgesetze werden im Fließtext zitiert und von `gesetze.py` automatisch verlinkt.
"""
from ._helpers import intro, schema, fall, mc

KURS = dict(
    id="k13", titel="Wirksamkeit und Zulässigkeit", untertitel="Verfahrensrecht nach Verfahrensart: Widerspruch, Beschwerde, Amtsverfahren, Klage",
    farbe="#4a6d3a", icon="waage",
    beschreibung="Die Zulässigkeitsprüfung im Detail, getrennt nach Verfahrensart, mit den Anschlussnormen aus BGB, HGB, GmbHG, ZPO, GVG und InsO. Am Ende ein Kapitel nur zu Tenorvorschlägen.",
    kapitel=[
        # ==============================================================
        dict(id="k13a", titel="Die drei Ebenen", einheiten=[
            intro("k13a-1", "Wirksamkeit, Zulässigkeit, Begründetheit",
                  "Jede Verfahrenshandlung im Markenrecht wird auf drei Ebenen geprüft, und zwar in dieser Reihenfolge.\n\n"
                  "**1. Wirksamkeit.** Vorgeschaltete Frage: Ist die Gebühr rechtzeitig und vollständig gezahlt? Nach § 64a i.V.m. § 6 Abs. 2 PatKostG gilt die Handlung sonst **als nicht vorgenommen**. Das ist keine Unzulässigkeit, sondern ein Nichtakt: Der Widerspruch gilt als nicht erhoben, die Beschwerde als nicht eingelegt. Deshalb steht diese Prüfung vor allem anderen, und deshalb lautet der Tenor dann nicht „unzulässig“, sondern „Es wird festgestellt, dass die Beschwerde als nicht eingelegt gilt.“\n\n"
                  "**2. Zulässigkeit.** Darf über die Sache überhaupt entschieden werden? Immer dasselbe Raster: Statthaftigkeit, Beteiligten- und Prozessfähigkeit, Berechtigung und Beschwer, Form, Ort, Frist, weitere Zulassungsvoraussetzungen. Die Zulässigkeit ist von Amts wegen zu prüfen (§ 59 Abs. 1); ein Verzicht der Beteiligten hilft nicht.\n\n"
                  "**3. Begründetheit.** Erst hier geht es um Verwechslungsgefahr, Benutzung und Bösgläubigkeit.\n\n"
                  "Das Schema ist bei allen Rechtsbehelfen gleich; nur die Einzelvoraussetzungen wechseln mit der Verfahrensart. Genau das trainiert dieser Kurs.",
                  concepts=["beteiligtenfaehigkeit", "zahlungstag", "amtsermittlung"], norms=["§ 64a", "§ 59 Abs. 1"]),
            fall("k13a-2", "Die Gebühr fehlt",
                 "Die Widersprechende legt fristgerecht Widerspruch ein, zahlt die Gebühr von 250 Euro aber erst zwei Wochen nach Ablauf der Widerspruchsfrist. Die Markenstelle möchte den Widerspruch als unzulässig zurückweisen.",
                 "Ist der Widerspruch als unzulässig zurückzuweisen?", False,
                 ["**Nein!** Wird die Gebühr nicht innerhalb der Frist gezahlt, gilt der Widerspruch nach § 64a i.V.m. § 6 Abs. 2 PatKostG **als nicht erhoben**. Er ist damit gar nicht existent; eine Sachentscheidung über seine Zulässigkeit ergeht nicht. Die Markenstelle stellt dies fest und erstattet die verspätet gezahlte Gebühr.",
                  "Der Unterschied ist kein Wortklauberei: Bei einer Zurückweisung als unzulässig läge eine Entscheidung über den Widerspruch vor, die in Rechtskraft erwüchse. Bei der Fiktion des § 6 Abs. 2 PatKostG bleibt es dabei, dass nie ein Widerspruch vorlag. Wiedereinsetzung ist nach § 91 Abs. 1 S. 2 gerade für die Widerspruchsfrist ausgeschlossen, und das erfasst nach ständiger Rechtsprechung auch die Frist zur Zahlung der Widerspruchsgebühr."],
                 merke="Fehlende Gebühr = Nichtakt, nicht Unzulässigkeit.",
                 level=1, concepts=["zahlungstag", "widerspruch"], norms=["§ 64a", "§ 91 Abs. 1"], step="step:schema_zulaessigkeit_widerspruch.1"),
            mc("k13a-3", "Wo steht die Widerspruchsberechtigung?",
               "Die Widersprechende ist nicht als Inhaberin der Widerspruchsmarke eingetragen; der Umschreibungsantrag ist erst nach Ablauf der Widerspruchsfrist eingegangen. An welcher Stelle des Gutachtens behandeln Sie das?",
               ["Zwingend in der Zulässigkeit; sonst ist das Gutachten falsch aufgebaut",
                "Zwingend in der Begründetheit; sonst ist das Gutachten falsch aufgebaut",
                "Beides ist vertretbar; entscheidend ist, dass die Prüfung überhaupt stattfindet und das Ergebnis konsequent umgesetzt wird",
                "Gar nicht, weil § 28 Abs. 1 eine unwiderlegliche Vermutung aufstellt"], 2,
               ["**Beides ist vertretbar.** Die amtliche Lösungsskizze zur Klausur NS II/2018 prüft die Widerspruchsberechtigung unter der **Begründetheit** (dort Punkt 3.1), weil § 42 Abs. 2 die Berechtigung als materielle Voraussetzung des Löschungsanspruchs formuliert. Viele Bearbeiter und auch das BPatG behandeln sie als Frage der Zulässigkeit, weil sie die Verfahrensführungsbefugnis betrifft.",
                "Wichtig ist die Konsequenz: Wer sie in der Zulässigkeit prüft und verneint, verwirft den Widerspruch als unzulässig; wer sie in der Begründetheit prüft, weist ihn als unbegründet zurück. Beides muss sich im Tenor und in den Kosten widerspiegeln. § 28 Abs. 1 stellt nur eine **widerlegliche** Vermutung auf; nach § 28 Abs. 2 kann der Rechtsnachfolger das Verfahren erst führen, wenn der Umschreibungsantrag beim DPMA eingegangen ist."],
               level=3, concepts=["widerspruch", "beteiligtenfaehigkeit"], norms=["§ 42 Abs. 2", "§ 28"], step="step:schema_zulaessigkeit_widerspruch.4"),
            fall("k13a-4", "Der Gegner rügt nichts",
                 "Im Beschwerdeverfahren stellt sich heraus, dass die Beschwerde einen Tag zu spät eingegangen ist. Die Gegenseite rügt das nicht, sondern verhandelt zur Sache; beide Beteiligte bitten um eine Sachentscheidung.",
                 "Muss das BPatG die Beschwerde trotzdem als unzulässig verwerfen?", True,
                 ["**Ja!** Die Zulässigkeitsvoraussetzungen eines Rechtsbehelfs sind von Amts wegen zu prüfen. Die Beschwerdefrist des § 66 Abs. 2 ist eine gesetzliche Frist, über die die Beteiligten nicht verfügen können; eine rügelose Einlassung wie bei der örtlichen Zuständigkeit im Zivilprozess (§ 39 ZPO) gibt es hier nicht.",
                  "Das Gericht muss den Beteiligten aber rechtliches Gehör gewähren, bevor es die Beschwerde verwirft (§ 59 Abs. 2 entsprechend, Art. 103 Abs. 1 GG), damit ein Wiedereinsetzungsantrag nach § 91 gestellt werden kann. Der Tenor lautet: „Die Beschwerde wird als unzulässig verworfen.“"],
                 merke="Zulässigkeit prüft das Gericht immer selbst, auch ohne Rüge.",
                 level=2, concepts=["beschwerde", "amtsermittlung"], norms=["§ 66 Abs. 2", "§ 59"], step="step:schema_zulaessigkeit_beschwerde.5"),
            mc("k13a-5", "Reihenfolge im Gutachten",
               "In welcher Reihenfolge prüfen Sie bei einer Beschwerde gegen einen Widerspruchsbeschluss?",
               ["Zulässigkeit der Beschwerde, Zulässigkeit des Widerspruchs, Begründetheit des Widerspruchs",
                "Zulässigkeit des Widerspruchs, Zulässigkeit der Beschwerde, Begründetheit",
                "Begründetheit zuerst, weil sie den Schwerpunkt bildet",
                "Nur die Zulässigkeit der Beschwerde; das Amtsverfahren ist abgeschlossen"], 0,
               ["Zuerst die **Zulässigkeit der Beschwerde**: Ohne sie darf das BPatG nicht in der Sache entscheiden. Ist sie zulässig, prüft das Gericht innerhalb der Begründetheit der Beschwerde, ob die Entscheidung des DPMA richtig war. Dazu gehört die vollständige Prüfung des Widerspruchs, also auch dessen **Wirksamkeit und Zulässigkeit**: Das Beschwerdegericht ist volle Tatsacheninstanz und prüft das Amtsverfahren komplett nach.",
                "Merkhilfe für die Gliederung: „Zulässigkeit der Beschwerde – Begründetheit der Beschwerde – darin: Wirksamkeit, Zulässigkeit und Begründetheit des Widerspruchs.“ War der Widerspruch unzulässig, ist die Beschwerde des Markeninhabers begründet, ohne dass es auf die Verwechslungsgefahr ankommt; ein Hilfsgutachten dazu ist aber oft verlangt."],
               level=2, concepts=["beschwerde", "widerspruch"], norms=["§ 66", "§ 70"], step="step:schema_klausur_ns.4"),
        ]),
        # ==============================================================
        dict(id="k13b", titel="Die vier Fähigkeiten", einheiten=[
            intro("k13b-1", "Rechtsfähigkeit, Beteiligtenfähigkeit, Prozessfähigkeit, Postulationsfähigkeit",
                  "Vier Begriffe, die in der Klausur sauber getrennt werden müssen.\n\n"
                  "**Rechtsfähigkeit** ist die Fähigkeit, Träger von Rechten und Pflichten zu sein. Sie folgt für natürliche Personen aus § 1 BGB, für die GmbH aus § 13 Abs. 1 GmbHG, für die AG aus § 1 Abs. 1 AktG, für die OHG seit dem MoPeG aus § 105 Abs. 2 HGB, für die KG aus § 161 Abs. 2 i.V.m. § 105 Abs. 2 HGB, für die GbR aus § 705 Abs. 2 BGB und für die Partnerschaftsgesellschaft aus § 7 Abs. 2 PartGG.\n\n"
                  "**Markenrechtsfähigkeit** ist die Sonderform des § 7: Inhaber können natürliche Personen (Nr. 1), juristische Personen (Nr. 2) und Personengesellschaften sein, sofern sie Rechte erwerben und Verbindlichkeiten eingehen können (Nr. 3). Wer nicht markenrechtsfähig ist, kann auch nicht Beteiligter eines Markenverfahrens sein.\n\n"
                  "**Beteiligtenfähigkeit** entspricht der Parteifähigkeit des § 50 ZPO, die über § 82 Abs. 1 entsprechend gilt: Parteifähig ist, wer rechtsfähig ist.\n\n"
                  "**Prozessfähigkeit** (§§ 51, 52 ZPO) ist die Fähigkeit, Verfahrenshandlungen selbst oder durch einen selbst bestellten Vertreter wirksam vorzunehmen. Juristische Personen sind nie selbst prozessfähig; sie handeln durch ihr Organ (§ 35 GmbHG, § 78 AktG).\n\n"
                  "**Postulationsfähigkeit** ist die Fähigkeit, vor der jeweiligen Instanz selbst aufzutreten. Vor dem DPMA und dem BPatG darf jeder Beteiligte selbst handeln (§ 81 Abs. 1); vor dem BGH herrscht Anwaltszwang (§ 84 Abs. 1, für den Zivilprozess § 78 ZPO). Hinzu tritt § 96 für Beteiligte ohne Sitz im Inland.",
                  concepts=["beteiligtenfaehigkeit", "inlandsvertreter"], norms=["§ 7", "§ 81", "§ 84", "§ 96", "§ 82 Abs. 1"]),
            fall("k13b-2", "Die KG nach dem MoPeG",
                 "Widersprechende ist die A.R. GmbH & Co. KG. Ein Bearbeiter schreibt: „Die Rechtsfähigkeit der KG folgt aus §§ 161 Abs. 2, 124 HGB.“ Die Klausur spielt im Jahr 2025.",
                 "Ist diese Normkette noch richtig?", False,
                 ["**Nein, nicht mehr!** Durch das Gesetz zur Modernisierung des Personengesellschaftsrechts (MoPeG) ist das HGB zum 1. Januar 2024 neu gefasst worden. Die Rechtsfähigkeit der OHG steht jetzt in **§ 105 Abs. 2 HGB** („Die offene Handelsgesellschaft kann Rechte erwerben und Verbindlichkeiten eingehen“). § 124 HGB regelt seither die **Vertretung** der Gesellschaft. Für die KG gilt die Verweisung des § 161 Abs. 2 HGB, so dass die richtige Kette lautet: §§ 161 Abs. 2, 105 Abs. 2 HGB.",
                  "Ältere Lösungsskizzen, etwa die zur Klausur NS II/2018, zitieren noch §§ 161 Abs. 2, 124 HGB; das war bis Ende 2023 richtig. Für die GbR gilt nun § 705 Abs. 2 BGB, für die Partnerschaftsgesellschaft § 7 Abs. 2 PartGG. Markenrechtlich sind alle drei über § 7 Nr. 3 tauglich, weil sie Rechte erwerben und Verbindlichkeiten eingehen können."],
                 merke="Seit dem MoPeG: § 105 Abs. 2 HGB für die Rechtsfähigkeit, § 124 HGB für die Vertretung.",
                 level=3, concepts=["beteiligtenfaehigkeit"], norms=["§ 7"], step="step:schema_zulaessigkeit_widerspruch.3"),
            fall("k13b-3", "Die GbR als Markeninhaberin",
                 "Zwei Fotografen betreiben ein Studio als Gesellschaft bürgerlichen Rechts und wollen die Marke „Lichtbildwerk“ auf die GbR anmelden. Der Prüfer meint, eine GbR könne nicht Markeninhaberin sein, weil sie keine juristische Person ist.",
                 "Kann die GbR Inhaberin der Marke sein?", True,
                 ["**Ja!** § 7 Nr. 3 lässt Personengesellschaften als Markeninhaber zu, sofern sie mit der Fähigkeit ausgestattet sind, Rechte zu erwerben und Verbindlichkeiten einzugehen. Die rechtsfähige GbR erfüllt das seit dem MoPeG ausdrücklich nach § 705 Abs. 2 BGB; sie muss dazu am Rechtsverkehr teilnehmen (Außen-GbR). Eine reine Innengesellschaft ist nicht rechtsfähig und deshalb auch nicht markenrechtsfähig.",
                  "Praxishinweis für die Beratungsklausur: Seit dem MoPeG kann sich die GbR in das Gesellschaftsregister eintragen lassen (§ 707 BGB) und führt dann den Zusatz „eGbR“. Für die Eintragung im Markenregister empfiehlt sich das, weil die Registerfähigkeit die Identifizierung und spätere Umschreibungen erleichtert. Alternativ können die Gesellschafter die Marke als Bruchteilsgemeinschaft halten; dann sind alle gemeinsam Inhaber."],
                 merke="Rechtsfähige Außen-GbR: markenfähig über § 7 Nr. 3 und § 705 Abs. 2 BGB.",
                 level=2, concepts=["beteiligtenfaehigkeit", "entstehung_markenschutz"], norms=["§ 7"], step="step:schema_zulaessigkeit_widerspruch.3"),
            fall("k13b-4", "Die GmbH handelt nicht selbst",
                 "Eine GmbH legt Widerspruch ein. Das Formular ist von einem Sachbearbeiter der Marketingabteilung unterschrieben, der keine Vollmacht vorlegt und nicht Geschäftsführer ist.",
                 "Ist der Widerspruch deshalb unwirksam?", False,
                 ["**Nein, nicht ohne Weiteres!** Die GmbH ist rechtsfähig (§ 13 Abs. 1 GmbHG) und damit beteiligtenfähig, aber nicht prozessfähig; sie handelt durch ihren Geschäftsführer als gesetzlichen Vertreter (§ 35 Abs. 1 GmbHG). Ein Sachbearbeiter kann als **rechtsgeschäftlich Bevollmächtigter** handeln; die Vollmacht kann formlos erteilt und später nachgewiesen werden (§ 81 Abs. 5, § 80 ZPO). Das DPMA fordert den Nachweis an, wenn Zweifel bestehen.",
                  "Wird die Vollmacht nicht nachgewiesen, ist die Handlung schwebend unwirksam und kann genehmigt werden (§ 89 Abs. 2 ZPO entsprechend). Erst wenn die Genehmigung ausbleibt, ist der Widerspruch als unwirksam zu behandeln. Anders liegt es bei einem Prokuristen: Seine Vertretungsmacht folgt unmittelbar aus § 49 Abs. 1 HGB und umfasst alle gerichtlichen und außergerichtlichen Geschäfte, die der Betrieb eines Handelsgewerbes mit sich bringt."],
                 merke="Organ = gesetzliche Vertretung, Prokurist = § 49 HGB, alle anderen brauchen Vollmacht.",
                 level=2, concepts=["beteiligtenfaehigkeit"], norms=["§ 81", "§ 42 Abs. 1"], step="step:schema_zulaessigkeit_widerspruch.3"),
            fall("k13b-5", "Die gelöschte UG",
                 "Die Inhaberin der angegriffenen Marke, eine UG (haftungsbeschränkt), wird wegen Vermögenslosigkeit nach § 394 Abs. 1 FamFG im Handelsregister gelöscht. Ihr früherer Geschäftsführer legt danach auf dem Briefpapier der UG Beschwerde ein.",
                 "Ist die Beschwerde wirksam eingelegt?", False,
                 ["**Nein!** Zu trennen sind zwei Fragen. Die **Beteiligtenfähigkeit** besteht fort, solange die Gesellschaft noch Vermögen hat; die eingetragene Marke ist ein solcher Vermögenswert, so dass die UG als Liquidationsgesellschaft weiterexistiert (§ 5a GmbHG, § 13 Abs. 1 GmbHG). Die Löschung im Register hat insoweit nur deklaratorische Wirkung.",
                  "Die **Prozessfähigkeit** entfällt dagegen: Mit der Löschung endet das Amt des Geschäftsführers, und die UG hat keinen gesetzlichen Vertreter mehr (§ 35 GmbHG). Nach § 82 Abs. 1 i.V.m. § 241 ZPO ist das Verfahren unterbrochen, bis auf Antrag eines Beteiligten ein **Nachtragsliquidator** nach § 66 Abs. 5 GmbHG bestellt ist. Bis dahin sind Verfahrenshandlungen unwirksam und Zustellungen an die Gesellschaft wirkungslos. Ein trotz Unterbrechung ergangener Beschluss ist unwirksam, aber nicht nichtig."],
                 merke="Vermögen erhält die Beteiligtenfähigkeit, der Geschäftsführer die Prozessfähigkeit.",
                 level=3, concepts=["beteiligtenfaehigkeit"], norms=["§ 7", "§ 82 Abs. 1"], cases=["bpatg_blizzard_ug"], step="step:schema_zulaessigkeit_beschwerde.3"),
            fall("k13b-6", "Insolvenz der Markeninhaberin",
                 "Während des Widerspruchsverfahrens wird über das Vermögen der Markeninhaberin das Insolvenzverfahren eröffnet. Der bisherige Verfahrensbevollmächtigte reicht weiter Schriftsätze ein.",
                 "Wird das Verfahren durch die Insolvenzeröffnung unterbrochen?", True,
                 ["**Ja!** Mit der Eröffnung geht das Verwaltungs- und Verfügungsrecht über das zur Masse gehörende Vermögen auf den Insolvenzverwalter über (§ 80 Abs. 1 InsO). Die Marke gehört zur Masse. Nach § 82 Abs. 1 i.V.m. § 240 ZPO wird das Verfahren unterbrochen, bis es der Verwalter aufnimmt oder das Insolvenzverfahren beendet ist.",
                  "Die Prozessvollmacht erlischt nicht automatisch (§ 86 ZPO), doch der Bevollmächtigte kann während der Unterbrechung keine wirksamen Verfahrenshandlungen mehr vornehmen; Zustellungen an ihn sind unwirksam. Nimmt der Verwalter das Verfahren auf, führt er es als Partei kraft Amtes. Für die Klausur ist zusätzlich § 29 Abs. 1 (Marke in der Zwangsvollstreckung) und die Frage relevant, ob der Verwalter die Marke freigibt; dann handelt wieder der Schuldner."],
                 merke="§ 80 InsO plus § 240 ZPO: Unterbrechung bis zur Aufnahme durch den Verwalter.",
                 level=3, concepts=["beteiligtenfaehigkeit"], norms=["§ 82 Abs. 1", "§ 29"], step="step:schema_zulaessigkeit_beschwerde.3"),
            fall("k13b-7", "Der Widersprechende wohnt in London",
                 "Ein deutscher Staatsangehöriger mit Wohnsitz in London erhebt ohne Vertreter Widerspruch. Eine polnische Staatsangehörige mit Wohnsitz in Düsseldorf tut dasselbe.",
                 "Braucht nur der in London Wohnende einen Inlandsvertreter?", True,
                 ["**Ja!** § 96 Abs. 1 knüpft an **Wohnsitz, Sitz oder Niederlassung** an, nicht an die Staatsangehörigkeit. Wer im Inland keinen dieser Anknüpfungspunkte hat, kann an Verfahren vor dem DPMA und dem BPatG nur über einen im Inland niedergelassenen Rechts- oder Patentanwalt teilnehmen. Der Wohnsitz im Vereinigten Königreich hilft seit dem Brexit nicht mehr weiter.",
                  "Die in Düsseldorf wohnende Polin kann dagegen selbst handeln. Fehlt der Inlandsvertreter, ist die Verfahrenshandlung unwirksam; das Amt muss aber zunächst eine Frist zur Bestellung setzen, bevor es den Widerspruch als unzulässig verwirft. Der Inlandsvertreter ist zugleich Zustellungsbevollmächtigter (§ 96 Abs. 2)."],
                 merke="§ 96: Wohnsitz entscheidet, nicht der Pass.",
                 level=2, concepts=["inlandsvertreter"], norms=["§ 96"], step="step:schema_zulaessigkeit_widerspruch.3"),
            mc("k13b-8", "Wer darf wo selbst auftreten?",
               "Ein Markeninhaber ohne Anwalt möchte selbst handeln. Wo geht das?",
               ["Vor dem DPMA, dem BPatG und dem BGH",
                "Vor dem DPMA und dem BPatG, nicht aber vor dem BGH",
                "Nur vor dem DPMA",
                "Nirgends; im gewerblichen Rechtsschutz gilt durchgehend Anwaltszwang"], 1,
               ["Vor dem DPMA gibt es keinen Vertretungszwang. Vor dem BPatG können die Beteiligten den Rechtsstreit ebenfalls selbst führen (§ 81 Abs. 1 S. 1); vertreten lassen können sie sich durch Rechts- oder Patentanwälte (§ 81 Abs. 2). Vor dem BGH herrscht dagegen Anwaltszwang: Die Rechtsbeschwerde ist durch einen beim BGH zugelassenen Rechtsanwalt einzulegen (§ 85 Abs. 1, § 84 Abs. 1).",
                "In Kennzeichenstreitsachen vor dem Landgericht gilt § 78 Abs. 1 ZPO: Vertretung durch einen Rechtsanwalt ist zwingend, weil das Landgericht ausschließlich zuständig ist (§ 140 Abs. 1). Der Patentanwalt kann dort mitwirken; seine Kosten sind nach § 140 Abs. 3 erstattungsfähig, wenn seine Mitwirkung notwendig war. § 96 bleibt in allen Verfahren zu beachten."],
               level=2, concepts=["beteiligtenfaehigkeit", "inlandsvertreter", "rechtsbeschwerde"], norms=["§ 81", "§ 84", "§ 140"], step="step:schema_zulaessigkeit_beschwerde.3"),
        ]),
        # ==============================================================
        dict(id="k13c", titel="Wirksamkeit: Gebühren und Zahlungstag", einheiten=[
            intro("k13c-1", "Die Gebührenprüfung in vier Schritten",
                  "**Schritt 1: Welche Gebühr fällt an?** Widerspruch 250 Euro für das erste Widerspruchskennzeichen und 50 Euro für jedes weitere (Nr. 331 600 und 331 610 des Gebührenverzeichnisses zu § 2 Abs. 1 PatKostG). Erinnerung 150 Euro (Nr. 333 000), Beschwerde 200 Euro (Nr. 401 300), Nichtigkeit 400 Euro und je weiterem älteren Recht 100 Euro (Nr. 333 300, 333 350), Verfall 100 Euro (Nr. 333 400).\n\n"
                  "**Schritt 2: Bis wann?** Die Gebühr ist mit der Vornahme der Handlung fällig (§ 3 Abs. 1 PatKostG) und innerhalb der jeweiligen gesetzlichen Frist zu zahlen.\n\n"
                  "**Schritt 3: Welcher Tag gilt als Zahlungstag?** Nach § 2 PatKostZV: bei Überweisung der Tag der **Gutschrift** bei der Bundeskasse (Nr. 1), bei Bareinzahlung auf deren Konto der Tag der Einzahlung (Nr. 2), beim SEPA-Basislastschriftmandat der Tag des **Eingangs** beim DPMA oder BPatG (Nr. 3), bei Kartenzahlung der Tag der Akzeptanz (Nr. 4).\n\n"
                  "**Schritt 4: Rechtsfolge.** Zahlt der Beteiligte nicht rechtzeitig oder nicht vollständig, gilt die Handlung nach § 64a i.V.m. § 6 Abs. 2 PatKostG als nicht vorgenommen. Die Gebühr wird zurückerstattet.",
                  concepts=["zahlungstag"], norms=["§ 64a", "§ 42 Abs. 3", "§ 66 Abs. 2"]),
            fall("k13c-2", "Überweisung am letzten Tag",
                 "Die Beschwerdefrist endet am Mittwoch, dem 18. März. Die Kanzlei gibt die Überweisung der 200 Euro am 18. März um 9 Uhr als gewöhnliche SEPA-Überweisung frei; dem Konto der Bundeskasse wird der Betrag am 19. März gutgeschrieben.",
                 "Ist die Beschwerdegebühr rechtzeitig gezahlt?", False,
                 ["**Nein!** Bei einer Überweisung gilt nach § 2 Nr. 1 PatKostZV der Tag der **Gutschrift** auf dem Konto der zuständigen Bundeskasse als Zahlungstag, nicht der Tag der Beauftragung oder der Wertstellung beim eigenen Institut. Die Zahlung ist damit einen Tag zu spät; die Beschwerde gilt nach § 6 Abs. 2 PatKostG als nicht eingelegt.",
                  "Wiedereinsetzung nach § 91 ist möglich, scheitert hier aber regelmäßig am Verschulden: Wer am letzten Tag zahlt, muss ein Zahlungsmittel wählen, das den Zahlungstag wahrt, also Echtzeitüberweisung, Bareinzahlung oder SEPA-Mandat. Der Tenor lautet dann: „Der Antrag auf Wiedereinsetzung wird zurückgewiesen. Es wird festgestellt, dass die Beschwerde als nicht eingelegt gilt. Die Rückzahlung der Beschwerdegebühr wird angeordnet.“"],
                 merke="Überweisung = Gutschrift. Am letzten Tag zu langsam.",
                 level=2, concepts=["zahlungstag", "wiedereinsetzung"], norms=["§ 64a", "§ 91"], cases=["bpatg_silver_horse"], step="step:schema_zulaessigkeit_beschwerde.6"),
            fall("k13c-3", "SEPA-Mandat per Telefax",
                 "Die Widersprechende übermittelt am letzten Tag der Widerspruchsfrist per Telefax den Widerspruch und ein SEPA-Basislastschriftmandat über 250 Euro. Das unterschriebene Original des Mandats geht drei Wochen später beim DPMA ein; abgebucht wird noch später.",
                 "Ist die Gebühr fristgerecht gezahlt?", True,
                 ["**Ja!** Beim SEPA-Basislastschriftmandat gilt nach § 2 Nr. 3 S. 1 PatKostZV der Tag des **Eingangs beim DPMA** als Zahlungstag. Wird das Mandat per Telefax übermittelt, bleibt es dabei, sofern das Original innerhalb eines Monats nach dem Faxeingang nachgereicht wird (§ 2 Nr. 3 S. 2 PatKostZV). Drei Wochen liegen innerhalb dieser Frist.",
                  "Fehlt die Nachreichung oder kommt sie zu spät, gilt nach § 2 Nr. 3 S. 3 PatKostZV der Tag des Eingangs des Originals als Zahlungstag, und die Frist ist versäumt. Auf den Zeitpunkt der tatsächlichen Abbuchung kommt es nie an; scheitert die Einziehung allerdings mangels Deckung, gilt die Gebühr als nicht gezahlt."],
                 merke="SEPA-Mandat: Eingang zählt, Original binnen eines Monats nachreichen.",
                 level=2, concepts=["zahlungstag"], norms=["§ 64a", "§ 42 Abs. 1"], cases=["bpatg_vita_lebenskraft"], step="step:schema_zulaessigkeit_widerspruch.1"),
            fall("k13c-4", "Bareinzahlung bei der Hausbank",
                 "Herr K zahlt die Beschwerdegebühr am letzten Tag der Frist bar bei seiner Bank auf das Gebührenkonto des DPMA ein und faxt den Einzahlungsbeleg einen Tag später an das Amt.",
                 "Ist die Gebühr rechtzeitig gezahlt?", True,
                 ["**Ja!** Bei der Bareinzahlung auf das Konto der zuständigen Bundeskasse gilt nach § 2 Nr. 2 PatKostZV der **Tag der Einzahlung** als Zahlungstag. Auf die spätere Gutschrift oder die Übersendung des Belegs kommt es nicht an; der Beleg dient nur dem Nachweis.",
                  "Das ist neben der Echtzeitüberweisung und dem Lastschriftmandat der dritte Weg, eine Frist am letzten Tag noch zu wahren. Für die Klausur lohnt sich der Vergleich: derselbe Sachverhalt, drei Zahlungswege, drei verschiedene Ergebnisse."],
                 merke="Bareinzahlung: Tag der Einzahlung.",
                 level=2, concepts=["zahlungstag"], norms=["§ 64a", "§ 66 Abs. 2"], cases=["bpatg_aussetzung_unionsmarke"], step="step:schema_zulaessigkeit_beschwerde.6"),
            fall("k13c-5", "Zwei Zeichen, eine Gebühr",
                 "B erhebt Widerspruch aus einer Wortmarke und aus einem gleichlautenden Unternehmenskennzeichen, zahlt aber nur 250 Euro. Nach Ablauf der Widerspruchsfrist teilt B auf Nachfrage des Amtes mit, der Widerspruch solle „aus der Wortmarke“ erhoben sein.",
                 "Ist der Widerspruch insgesamt als nicht erhoben zu behandeln?", False,
                 ["**Nein!** Mit 250 Euro ist die Gebühr für **ein** Widerspruchskennzeichen vollständig gezahlt (Nr. 331 600). Nur für das zweite Kennzeichen fehlt der Zusatzbetrag von 50 Euro (Nr. 331 610, § 42 Abs. 3). Das DPMA muss dem Widersprechenden Gelegenheit geben, die Zahlung einem Kennzeichen zuzuordnen; diese Klarstellung ist auch nach Ablauf der Widerspruchsfrist möglich, weil sie nur die Zuordnung einer fristgerecht geleisteten Zahlung betrifft.",
                  "Die Erklärung „aus der Wortmarke“ ist eindeutig, weil ein Unternehmenskennzeichen keine Wortmarke ist. Ergebnis: Der Widerspruch aus der Wortmarke ist wirksam, der aus dem Unternehmenskennzeichen gilt als nicht erhoben. Entscheidet das DPMA stattdessen insgesamt negativ, hebt das BPatG auf, verweist zurück (§ 70 Abs. 3 Nr. 1) und ordnet die Rückzahlung der Beschwerdegebühr an (§ 71 Abs. 3)."],
                 merke="Teilzahlung deckt ein Zeichen; die Zuordnung darf nachgeholt werden.",
                 level=3, concepts=["zahlungstag", "widerspruch"], norms=["§ 42 Abs. 3", "§ 64a", "§ 70 Abs. 3"], cases=["bpatg_silberweide"], step="step:schema_zulaessigkeit_widerspruch.1"),
            mc("k13c-6", "Rechtsfolge der fehlenden Gebühr",
               "Die Erinnerungsgebühr wird nicht gezahlt. Wie lautet die Entscheidung der Markenstelle?",
               ["Die Erinnerung wird als unzulässig verworfen",
                "Es wird festgestellt, dass die Erinnerung als nicht eingelegt gilt; die Gebühr wird zurückgezahlt, soweit sie verspätet einging",
                "Die Erinnerung wird als unbegründet zurückgewiesen",
                "Das Verfahren wird ausgesetzt, bis die Gebühr gezahlt ist"], 1,
               ["§ 64a i.V.m. § 6 Abs. 2 PatKostG ordnet die Fiktion an: Die Handlung **gilt als nicht vorgenommen**. Es ergeht keine Sachentscheidung und keine Verwerfung als unzulässig, sondern eine Feststellung. Eine verspätet oder ohne Rechtsgrund gezahlte Gebühr wird nach § 10 Abs. 1 PatKostG zurückgezahlt.",
                "Die Abgrenzung ist klausurentscheidend, weil sie den Tenor bestimmt. Merkformel: fehlende Gebühr → „gilt als nicht eingelegt“; fehlende sonstige Zulässigkeitsvoraussetzung → „wird als unzulässig verworfen“; Sachprüfung negativ → „wird zurückgewiesen“."],
               level=2, concepts=["zahlungstag", "erinnerung"], norms=["§ 64a", "§ 64"], step="step:schema_zulaessigkeit_beschwerde.6"),
        ]),
        # ==============================================================
        dict(id="k13d", titel="Zulässigkeit des Widerspruchs", einheiten=[
            schema("k13d-1", "Prüfungsschema Zulässigkeit des Widerspruchs", "schema_zulaessigkeit_widerspruch",
                   "Acht Punkte, die in dieser Reihenfolge abzuarbeiten sind. Jeder Prüfungspunkt lässt sich aufklappen."),
            fall("k13d-2", "Widerspruch vor Beginn der Frist",
                 "Die angegriffene Marke wird am 7. August eingetragen; die Veröffentlichung der Eintragung erfolgt am 6. September. Der Widerspruch geht bereits am 23. August beim DPMA ein.",
                 "Ist der Widerspruch zulässig?", True,
                 ["**Ja!** § 42 Abs. 1 bestimmt nur das **Ende** der Widerspruchsfrist, nämlich drei Monate nach der Veröffentlichung der Eintragung. Der Widerspruch kann bereits ab der Eintragung erhoben werden, weil ab diesem Zeitpunkt ein Recht existiert, gegen das sich der Widerspruch richten kann, und der Widersprechende ein Rechtsschutzbedürfnis hat.",
                  "Dasselbe gilt für den Widerspruch gegen einen Verfalls- oder Nichtigkeitsantrag nach § 53 Abs. 5: Er ist ab Eingang des Antrags beim DPMA zulässig, auch vor Zustellung der Mitteilung nach § 53 Abs. 4. Unzulässig ist nur ein Rechtsbehelf, der eingelegt wird, **bevor** es überhaupt einen Angriffsgegenstand gibt."],
                 merke="Frühestens ab Eintragung, spätestens drei Monate nach Veröffentlichung.",
                 level=2, concepts=["widerspruch"], norms=["§ 42 Abs. 1"], cases=["bpatg_engelbrecht", "bpatg_automator"], step="step:schema_zulaessigkeit_widerspruch.2"),
            mc("k13d-3", "Die fünf Widerspruchsgründe",
               "Aus welchem Recht kann kein Widerspruch nach § 42 Abs. 2 erhoben werden?",
               ["Aus einer älteren angemeldeten, aber noch nicht eingetragenen Marke",
                "Aus einer geschützten geografischen Angabe",
                "Aus einem Urheberrecht an einem Werk, das in die jüngere Marke übernommen wurde",
                "Aus einer notorisch bekannten Marke im Sinne des § 10"], 2,
               ["Widerspruchsgründe sind in § 42 Abs. 2 **abschließend** aufgezählt: Nr. 1 ältere angemeldete oder eingetragene Marken (§ 9; die Anmeldung wirkt nach § 9 Abs. 2 nur, wenn sie eingetragen wird), Nr. 2 notorisch bekannte Marken (§ 10), Nr. 3 Agentenmarken (§ 11), Nr. 4 Benutzungsmarken und geschäftliche Bezeichnungen (§§ 4 Nr. 2, 5 i.V.m. § 12) und Nr. 5 Ursprungsbezeichnungen und geografische Angaben.",
                "Sonstige ältere Rechte des § 13 Abs. 2, insbesondere Namensrechte, Urheberrechte, Sortenbezeichnungen und Designs, sind **keine** Widerspruchsgründe. Sie können nur im Nichtigkeitsverfahren nach § 51 geltend gemacht werden, seit dem MaMoG auch beim DPMA nach § 53. Das war der Kern der Klausur zur Öresundbrücke: Das Urheberrecht am Bauwerk gehört nicht in den Widerspruch."],
               level=2, concepts=["widerspruch", "relative_schutzhindernisse", "nichtigkeit"], norms=["§ 42 Abs. 2", "§ 13", "§ 51"], cases=["bpatg_oeresundbruecke"], step="step:schema_zulaessigkeit_widerspruch.4"),
            fall("k13d-4", "Widerspruch des Rechtsnachfolgers",
                 "Die Widerspruchsmarke ist im Register noch auf die Alt-GmbH eingetragen, wurde aber vor Monaten auf die Neu-GmbH übertragen. Die Neu-GmbH erhebt Widerspruch und stellt erst zwei Wochen später den Antrag auf Umschreibung.",
                 "Kann die Neu-GmbH den Widerspruch wirksam führen?", False,
                 ["**Nein, noch nicht!** Nach § 28 Abs. 1 gilt zugunsten des Eingetragenen die Vermutung, dass ihm das Recht zusteht. Der Rechtsnachfolger kann den Anspruch aus der Marke in einem anhängigen Verfahren erst geltend machen, wenn der **Antrag auf Eintragung des Rechtsübergangs beim DPMA eingegangen** ist (§ 28 Abs. 2 S. 1). Bis dahin fehlt ihm die Verfahrensführungsbefugnis.",
                  "Praktische Folge: Geht der Umschreibungsantrag noch innerhalb der Widerspruchsfrist ein, ist der Mangel geheilt. Geht er später ein, ist der Widerspruch der Neu-GmbH unzulässig, und ein neuer Widerspruch scheitert an der abgelaufenen Frist. Deshalb gehört der Umschreibungsantrag in der Beratungsklausur immer zur Handlungsempfehlung. Umgekehrt kann der eingetragene Alt-Inhaber das Verfahren weiterführen; der Erwerber tritt dann nach § 28 Abs. 2 S. 3 ein."],
                 merke="Ohne eingegangenen Umschreibungsantrag führt nur der Eingetragene das Verfahren.",
                 level=3, concepts=["widerspruch", "beteiligtenfaehigkeit"], norms=["§ 28"], step="step:schema_zulaessigkeit_widerspruch.4"),
            fall("k13d-5", "Fristende am Feiertag",
                 "Die Eintragung wird am Montag, dem 20. Oktober, veröffentlicht. Der 20. Januar des Folgejahres ist ein Samstag, der 22. Januar ein gesetzlicher Feiertag im Sitzland der Behörde. Der Widerspruch geht am Dienstag, dem 23. Januar, ein.",
                 "Ist der Widerspruch fristgerecht?", True,
                 ["**Ja!** Die Dreimonatsfrist des § 42 Abs. 1 beginnt nach § 187 Abs. 1 BGB am Tag nach der Veröffentlichung und endet nach § 188 Abs. 2 BGB mit Ablauf des 20. Januar. Weil dieser Tag ein Samstag ist, tritt nach § 193 BGB der nächste Werktag an seine Stelle. Der Montag, 21. Januar, wäre das gewesen; ist der folgende Tag ein Feiertag, verschiebt sich das Fristende weiter auf den nächsten Werktag, hier Dienstag, den 23. Januar.",
                  "Für Verfahren vor dem BPatG folgt dasselbe aus § 82 Abs. 1 i.V.m. § 222 Abs. 2 ZPO. Maßgeblich sind die Feiertage am Sitz der Behörde oder des Gerichts; das DPMA hat Dienststellen in München, Jena und Berlin, das BPatG seinen Sitz in München. Deshalb prüft man in der Klausur die bayerischen Feiertage, sofern nichts anderes angegeben ist. Liegt ein Kalender bei, ist das ein sicheres Zeichen, dass genau hier die Falle steckt."],
                 merke="§§ 187, 188, 193 BGB; bei Feiertagsketten weiterschieben.",
                 level=2, concepts=["fristberechnung", "widerspruch"], norms=["§ 42 Abs. 1", "§ 82 Abs. 1"], step="step:schema_zulaessigkeit_widerspruch.6"),
            fall("k13d-6", "Widerspruch ohne Begründung",
                 "Der Widerspruch nennt die angegriffene Marke, das Widerspruchskennzeichen und den Widersprechenden, enthält aber keine Begründung und keine Angabe, gegen welche Waren er sich richtet.",
                 "Ist der Widerspruch unzulässig?", False,
                 ["**Nein!** § 30 Abs. 1 MarkenV verlangt nur Angaben, die die Identität der angegriffenen Marke, des Widerspruchskennzeichens und des Widersprechenden erkennen lassen. Diese Mindestangaben liegen vor. Eine Begründung ist keine Zulässigkeitsvoraussetzung und kann jederzeit nachgereicht werden.",
                  "Die Angaben des § 30 Abs. 2 MarkenV, darunter die Registernummern und die Waren, gegen die sich der Widerspruch richtet, sind **Sollvorschriften**. Fehlt die Angabe der angegriffenen Waren, richtet sich der Widerspruch im Zweifel gegen die Eintragung insgesamt. Fehlen dagegen die Mindestangaben und lässt sich das Widerspruchskennzeichen auch durch Auslegung nicht bestimmen, ist der Widerspruch unzulässig; eine Nachholung nach Fristablauf ist insoweit ausgeschlossen, weil sie den Verfahrensgegenstand nachträglich schaffen würde."],
                 merke="§ 30 Abs. 1 MarkenV: Identität ja, Begründung nein.",
                 level=2, concepts=["widerspruch"], norms=["§ 42 Abs. 1"], step="step:schema_zulaessigkeit_widerspruch.5"),
            fall("k13d-7", "Wiedereinsetzung in die Widerspruchsfrist",
                 "Die Widerspruchsfrist wird versäumt, weil eine sonst zuverlässige Kanzleiangestellte den Schriftsatz versehentlich nicht zur Post gibt. Die Kanzlei beantragt Wiedereinsetzung und macht das Büroversehen glaubhaft.",
                 "Kann Wiedereinsetzung gewährt werden?", False,
                 ["**Nein!** § 91 Abs. 1 S. 2 schließt die Wiedereinsetzung in die Widerspruchsfrist des § 42 Abs. 1 ausdrücklich aus. Der Gesetzgeber will Rechtssicherheit für den Markeninhaber: Nach Ablauf der drei Monate soll feststehen, ob seine Marke angegriffen ist. Der Ausschluss erfasst nach ständiger Rechtsprechung auch die Frist zur Zahlung der Widerspruchsgebühr, weil diese der Widerspruchsfrist folgt.",
                  "Der Mandant ist deshalb auf andere Wege zu verweisen: Nichtigkeitsantrag wegen älterer Rechte beim DPMA (§ 51 i.V.m. § 53), Löschungsklage (§ 55) oder Verletzungsklage aus dem älteren Recht mit dem Einwand des § 22, sofern die Voraussetzungen vorliegen. Genau diese Alternativenprüfung war die vierte Frage der Klausur NS III/2019."],
                 merke="Widerspruchsfrist: keine Wiedereinsetzung, § 91 Abs. 1 S. 2.",
                 level=2, concepts=["wiedereinsetzung", "widerspruch", "nichtigkeit"], norms=["§ 91 Abs. 1", "§ 51", "§ 53", "§ 55"], step="step:schema_zulaessigkeit_widerspruch.6"),
            fall("k13d-8", "Nur regional geschütztes Kennzeichen",
                 "Eine Bäckerei mit zwölf Filialen in zwei Nachbarstädten erhebt Widerspruch aus ihrem Unternehmenskennzeichen. Unstreitig reicht der Schutzbereich nicht über die Region hinaus.",
                 "Ist der Widerspruch unzulässig?", False,
                 ["**Nein, er ist unbegründet!** Die Unterscheidung ist klausurentscheidend. Zulässig ist der Widerspruch, weil ein Recht nach § 42 Abs. 2 Nr. 4 geltend gemacht wird und die Widersprechende dessen Inhaberin ist. Ob das Kennzeichen den Inhaber berechtigt, die Benutzung der jüngeren Marke **im gesamten Bundesgebiet** zu untersagen, ist eine Frage des § 12 und damit der Begründetheit.",
                  "Ergebnis: Der Widerspruch wird als unbegründet zurückgewiesen, nicht als unzulässig verworfen. Wer hier verwechselt, produziert einen falschen Tenor. Merke die Faustformel: Fragen nach der Person und dem Verfahren gehören in die Zulässigkeit, Fragen nach der Reichweite des Rechts in die Begründetheit."],
                 merke="Reichweite des Rechts = Begründetheit, nicht Zulässigkeit.",
                 level=3, concepts=["unternehmenskennzeichen", "widerspruch"], norms=["§ 42 Abs. 2 Nr. 4", "§ 12"], cases=["bpatg_engelbrecht"], step="step:schema_zulaessigkeit_widerspruch.4.4"),
            mc("k13d-9", "Tenor des DPMA im Widerspruchsverfahren",
               "Der Widerspruch aus einer älteren Marke ist zulässig und für einen Teil der Waren begründet. Wie tenoriert die Markenstelle?",
               ["„Der Widerspruch wird als unzulässig verworfen.“",
                "„Auf den Widerspruch aus der Marke 30 2019 111 333 wird die Eintragung der Marke 30 2021 222 444 für die Waren der Klasse 25 gelöscht. Im Übrigen wird der Widerspruch zurückgewiesen.“",
                "„Die Marke 30 2021 222 444 wird für nichtig erklärt.“",
                "„Der Widerspruch wird zurückgewiesen. Die Kosten trägt die Widersprechende.“"], 1,
               ["Der Widerspruch führt nach § 43 Abs. 2 S. 1 zur **Löschung der Eintragung**, und zwar nur im Umfang der Kollision. Der Tenor ist deshalb warenbezogen zu fassen und muss den zurückgewiesenen Teil ausdrücklich erwähnen, sonst bleibt offen, was mit dem Rest geschieht.",
                "Falsch ist „für nichtig erklärt“: Das ist die Formel des Nichtigkeitsverfahrens nach §§ 50, 51, 53, die ex tunc wirkt. Die Löschung aufgrund eines Widerspruchs beseitigt die Eintragung ebenfalls rückwirkend, wird aber nicht als Nichtigerklärung tenoriert. Eine Kostenentscheidung ergeht nur, wenn Billigkeitsgründe vorliegen (§ 63 Abs. 1); ohne sie trägt jeder Beteiligte seine Kosten selbst, und der Tenor schweigt dazu."],
               level=2, concepts=["widerspruch", "kostenentscheidung"], norms=["§ 43 Abs. 2", "§ 63 Abs. 1"], step="step:schema_widerspruch.4"),
        ]),
        # ==============================================================
        dict(id="k13e", titel="Erinnerung, Beschwerde, Rechtsbeschwerde", einheiten=[
            schema("k13e-1", "Prüfungsschema Zulässigkeit der Beschwerde", "schema_zulaessigkeit_beschwerde",
                   "Neun Punkte. Der häufigste Fehler steckt gleich in Punkt 1: Erinnerung oder Beschwerde?"),
            mc("k13e-2", "Welcher Rechtsbehelf ist statthaft?",
               "Der Widerspruch wird durch Beschluss zurückgewiesen. Prüfen Sie die Statthaftigkeit in vier Varianten: (a) Beschluss eines Beamten des gehobenen Dienstes, (b) Beschluss eines Beamten des höheren Dienstes, (c) Beschluss einer Regierungsdirektorin, (d) Erinnerungsbeschluss.",
               ["In allen vier Fällen die Beschwerde",
                "(a) Erinnerung nach § 64; (b), (c) und (d) Beschwerde nach § 66",
                "(a) und (b) Erinnerung; (c) und (d) Beschwerde",
                "In allen vier Fällen zuerst die Erinnerung"], 1,
               ["§ 64 Abs. 1 eröffnet die Erinnerung **nur** gegen Beschlüsse, die von einem Beamten des gehobenen Dienstes oder einem vergleichbaren Angestellten erlassen worden sind. Gegen alle anderen Beschlüsse der Markenstellen und Markenabteilungen ist unmittelbar die Beschwerde zum BPatG statthaft (§ 66 Abs. 1). Eine Regierungsdirektorin gehört dem höheren Dienst an; auch der Erinnerungsbeschluss selbst ist mit der Beschwerde anzugreifen.",
                "Deshalb steht in jeder Klausur, wer entschieden hat: „Die mit einer Beamtin des höheren Dienstes besetzte Markenstelle …“ oder „Beschluss eines Beamten des gehobenen Dienstes“. Wer den falschen Rechtsbehelf wählt, verliert die Frist. Wird versehentlich Erinnerung statt Beschwerde eingelegt, ist der Schriftsatz nach dem Meistbegünstigungsgrundsatz als Beschwerde auszulegen, wenn der Wille zur Anfechtung erkennbar ist; die Gebührendifferenz bleibt aber ein Problem."],
               level=2, concepts=["erinnerung", "beschwerde"], norms=["§ 64", "§ 66 Abs. 1", "§ 56"], step="step:schema_zulaessigkeit_beschwerde.1"),
            fall("k13e-3", "Das Amt entscheidet nicht",
                 "Über die Erinnerung ist auch nach acht Monaten nicht entschieden. Der Erinnerungsführer setzt dem DPMA schriftlich eine Frist von zwei Monaten; auch danach ergeht kein Beschluss. Er legt Beschwerde ein.",
                 "Ist die Beschwerde statthaft, obwohl kein Erinnerungsbeschluss vorliegt?", True,
                 ["**Ja!** § 66 Abs. 3 eröffnet die sogenannte Durchgriffsbeschwerde: Ist über eine Erinnerung innerhalb von sechs Monaten nach ihrer Einlegung nicht entschieden worden und setzt der Erinnerungsführer danach eine Frist von zwei Monaten, so ist nach fruchtlosem Ablauf die Beschwerde unmittelbar statthaft. Im zweiseitigen Verfahren, in dem auch der Gegner Erinnerung eingelegt hat, verlängert sich die Wartezeit auf zehn Monate und die Beschwerde bedarf der Einwilligung des anderen Beteiligten (§ 66 Abs. 3 S. 2 bis 4).",
                  "Der Lauf der Fristen ist gehemmt, solange das Verfahren ausgesetzt ist oder einem Beteiligten eine Frist gewährt wurde. Nach Erlass des Erinnerungsbeschlusses ist die Durchgriffsbeschwerde nicht mehr möglich; dann gilt wieder § 66 Abs. 1 und 2."],
                 merke="Sechs Monate, zwei Monate Nachfrist, dann Durchgriffsbeschwerde.",
                 level=3, concepts=["erinnerung", "beschwerde"], norms=["§ 66 Abs. 3"], step="step:schema_zulaessigkeit_beschwerde.1"),
            fall("k13e-4", "Der Sieger legt Beschwerde ein",
                 "Der Widerspruch wird vollständig zurückgewiesen. Der Markeninhaber, der damit obsiegt hat, schickt gleichwohl ein mit „Beschwerde“ überschriebenes Schreiben an das Gericht und erhebt darin die Einrede der Nichtbenutzung.",
                 "Ist diese Beschwerde zulässig?", False,
                 ["**Nein!** Es fehlt die **Beschwer**. Ein Rechtsbehelf setzt voraus, dass der Rechtsbehelfsführer durch die angefochtene Entscheidung formell und materiell benachteiligt ist. Wer vollständig obsiegt hat, kann die Entscheidung nicht anfechten; die Beschwerde ist als unzulässig zu verwerfen.",
                  "Das Schreiben ist damit aber nicht wertlos: Es ist als **Verfahrenserklärung im Beschwerdeverfahren des Gegners** auszulegen. Die darin erhobene Nichtbenutzungseinrede nach § 43 Abs. 1 ist wirksam, wenn sie eindeutig erklärt ist; sie kann in jedem Verfahrensstadium und erstmals auch im Beschwerdeverfahren erhoben werden. Vor dem BPatG besteht kein Anwaltszwang (§ 81 Abs. 1), und ein Prokurist ist nach § 49 Abs. 1 HGB zur Abgabe befugt."],
                 merke="Ohne Beschwer keine Beschwerde; der Schriftsatz bleibt als Erklärung wirksam.",
                 level=3, concepts=["beschwer", "nichtbenutzungseinrede"], norms=["§ 66 Abs. 1", "§ 43 Abs. 1"], cases=["bgh_silver_horse", "bpatg_silver_horse"], step="step:schema_zulaessigkeit_beschwerde.2"),
            fall("k13e-5", "Beschwerde per einfacher E-Mail",
                 "Herr L unterschreibt ein Schreiben mit der Überschrift „Beschwerde“, scannt es ein und sendet es als PDF-Anhang einer einfachen E-Mail an das DPMA.",
                 "Wahrt das die Form des § 66 Abs. 2?", False,
                 ["**Nein!** § 66 Abs. 2 verlangt Schriftform. Diese wird durch eine eigenhändig unterschriebene Urkunde gewahrt oder durch eine elektronische Einreichung nach § 95a i.V.m. der ERVDPMAV, also mit qualifizierter elektronischer Signatur oder über einen sicheren Übermittlungsweg wie das besondere elektronische Anwaltspostfach. Eine eingescannte Unterschrift in einer einfachen E-Mail genügt beidem nicht.",
                  "Zwei weitere Fallen im selben Zusammenhang: Die Beschwerde ist **beim DPMA** einzulegen, nicht beim BPatG; ein Eingang beim Gericht wahrt die Frist nicht, auch wenn das Gericht sie später weiterleitet. Und die Unterzeichnung mit dem Zusatz „i.V.“ ist wirksam, wenn die unterzeichnende Person bevollmächtigt ist; das Gericht darf aber einen Nachweis verlangen."],
                 merke="Schriftform oder qualifizierte Signatur, und immer beim DPMA.",
                 level=2, concepts=["beschwerde"], norms=["§ 66 Abs. 2", "§ 95a"], cases=["bpatg_automator"], step="step:schema_zulaessigkeit_beschwerde.4"),
            fall("k13e-6", "Zustellung durch Einschreiben",
                 "Der Beschluss wird am Freitag, dem 5. September, als Übergabeeinschreiben zur Post gegeben; das wird in der Akte vermerkt. Der Empfänger holt die Sendung erst am 12. September ab. Die Beschwerde geht am 8. Oktober beim DPMA ein.",
                 "Ist die Beschwerde fristgerecht?", True,
                 ["**Ja!** Bei der Zustellung durch Einschreiben gilt das Schriftstück am **dritten Tag nach der Aufgabe zur Post** als zugestellt (§ 94 Abs. 1 i.V.m. § 4 Abs. 2 S. 2 VwZG), hier also am Montag, dem 8. September. Die Monatsfrist des § 66 Abs. 2 endet damit mit Ablauf des 8. Oktober; der Eingang an diesem Tag wahrt die Frist.",
                  "Die Fiktion wirkt in beide Richtungen: Ein späteres tatsächliches Abholen verlängert die Frist nicht. Der Empfänger kann aber nachweisen, dass ihm das Schriftstück **gar nicht oder später** zugegangen ist; dann gilt der Tag des tatsächlichen Zugangs (§ 4 Abs. 2 S. 3 VwZG). Fällt der dritte Tag auf ein Wochenende, verschiebt sich nach herrschender Meinung nicht die Zustellungsfiktion, sondern nur ein Fristende nach § 193 BGB."],
                 merke="Einschreiben: dritter Tag nach Aufgabe zur Post.",
                 level=2, concepts=["zustellung", "fristberechnung"], norms=["§ 94", "§ 66 Abs. 2"], step="step:schema_zulaessigkeit_beschwerde.5.1"),
            fall("k13e-7", "Der Beschluss im Abholfach",
                 "Der Beschluss wird am Dienstag, dem 10. Juni, in das Abholfach der Vertreter beim DPMA niedergelegt; die Niederlegung wird vermerkt und eine Mitteilung zu den Akten gegeben. Der Vertreter entnimmt und liest den Beschluss nachweislich schon am 11. Juni.",
                 "Beginnt die Beschwerdefrist mit dem 11. Juni?", False,
                 ["**Nein!** Bei der Niederlegung in einem beim DPMA eingerichteten Abholfach gilt die Zustellung **am dritten Tag nach der Niederlegung** als bewirkt (§ 94 Abs. 1 Nr. 3 S. 4), hier also am Freitag, dem 13. Juni. Die gesetzliche Fiktion legt den Zustellungszeitpunkt abschließend fest; auf die tatsächliche Entnahme kommt es nicht an.",
                  "Die Monatsfrist endet damit am 13. Juli; fällt dieser Tag auf einen Sonntag, verschiebt sie sich nach § 82 Abs. 1 i.V.m. § 222 Abs. 2 ZPO auf Montag, den 14. Juli. Genau diese Konstellation war der Einstieg der Klausur NS III/2018: Die Markeninhaberin rügte, der Vertreter habe den Beschluss früher gelesen, was die Frist aber nicht verkürzt."],
                 merke="Abholfach: dritter Tag nach Niederlegung, früheres Lesen ist unerheblich.",
                 level=3, concepts=["zustellung", "fristberechnung"], norms=["§ 94", "§ 82 Abs. 1"], step="step:schema_zulaessigkeit_beschwerde.5.1"),
            fall("k13e-8", "Öffentliche Zustellung nach Umzug",
                 "Die Widersprechende zieht während des Verfahrens nach London, ohne die neue Anschrift mitzuteilen. Das DPMA stellt den Beschluss öffentlich zu; die Zustellung gilt am 25. November als bewirkt. Die Beschwerde geht am 23. Januar ein.",
                 "Ist die Beschwerde verspätet?", True,
                 ["**Ja!** Die öffentliche Zustellung ist zulässig, wenn der Aufenthaltsort des Empfängers unbekannt ist (§ 94 Abs. 1 i.V.m. § 10 Abs. 1 VwZG); sie gilt zwei Wochen nach der Bekanntmachung als bewirkt (§ 10 Abs. 2 S. 6 VwZG). Steht fest, dass die Zustellung am 25. November wirksam wurde, endete die Monatsfrist des § 66 Abs. 2 mit Ablauf des 25. Dezember, wegen des Feiertags mit dem nächsten Werktag. Der Eingang am 23. Januar ist deutlich zu spät.",
                  "Zwei Ansatzpunkte für die Verteidigung: Erstens die **Wirksamkeit** der öffentlichen Zustellung, die nur als letztes Mittel zulässig ist; hat die Behörde zumutbare Ermittlungen unterlassen, ist die Zustellung unwirksam und die Frist nie angelaufen. Zweitens die **Wiedereinsetzung** nach § 91, die hier anders als bei der Widerspruchsfrist möglich ist; der Beteiligte muss aber darlegen, warum er keine ladungsfähige Anschrift hinterlassen hat, was regelmäßig als Verschulden gewertet wird."],
                 merke="Öffentliche Zustellung: zwei Wochen nach Bekanntmachung, aber nur als letztes Mittel.",
                 level=3, concepts=["zustellung", "wiedereinsetzung"], norms=["§ 94", "§ 91", "§ 66 Abs. 2"], step="step:schema_zulaessigkeit_beschwerde.5.1"),
            fall("k13e-9", "Beschwerde nur gegen einen Teil",
                 "Ein Beschluss entscheidet über zwei Widersprüche und löscht die Marke wegen des ersten teilweise und wegen des zweiten vollständig. Der Markeninhaber legt fristgerecht Beschwerde ein, „soweit die Marke wegen des Widerspruchs 1 gelöscht wurde“. Acht Monate später will er die Beschwerde auf den zweiten Teil erweitern.",
                 "Ist die Erweiterung zulässig?", False,
                 ["**Nein!** Ein Beschluss, der über mehrere Widersprüche gemeinsam entscheidet, ist ein einheitlicher Beschluss; er wird jedem Beteiligten nur **einmal** zugestellt und setzt nur **eine** Beschwerdefrist in Lauf. Wer die Beschwerde ausdrücklich und eindeutig beschränkt, lässt den übrigen Teil in Teilrechtskraft erwachsen. Die spätere Erweiterung ist eine neue, verspätete Beschwerde.",
                  "Umgekehrt gilt: Eine Beschwerde **ohne** erkennbare Einschränkung richtet sich im Zweifel gegen den gesamten Beschluss, auch wenn im Betreff nur eine Marke genannt ist. Wiedereinsetzung scheidet aus, weil der Rechtsirrtum des Vertreters über die Zahl der Zustellungen der Partei nach § 82 Abs. 1 i.V.m. § 85 Abs. 2 ZPO zugerechnet wird."],
                 merke="Ein Beschluss, eine Zustellung, eine Frist; Beschränkung bindet.",
                 level=3, concepts=["beschwerde", "beschwer"], norms=["§ 66 Abs. 2", "§ 91"], step="step:schema_zulaessigkeit_beschwerde.8"),
            mc("k13e-10", "Zulassungsfreie Rechtsbeschwerde",
               "Das BPatG weist die Beschwerde zurück, ohne die Rechtsbeschwerde zuzulassen, obwohl die Sache grundsätzliche Bedeutung hat. Was kann der Beschwerdeführer tun?",
               ["Zulassungsfreie Rechtsbeschwerde, weil das Unterlassen der Zulassung ein Begründungsmangel ist",
                "Nichts über § 83 Abs. 3; die zulassungsfreie Rechtsbeschwerde setzt einen der sechs absoluten Verfahrensmängel voraus, zu denen das Unterlassen der Zulassung nicht gehört",
                "Anhörungsrüge und danach automatisch Rechtsbeschwerde",
                "Beschwerde zum BGH gegen die Nichtzulassung"], 1,
               ["Die Rechtsbeschwerde ist grundsätzlich nur statthaft, wenn das BPatG sie zugelassen hat (§ 83 Abs. 1). Ohne Zulassung ist sie nur bei den sechs absoluten Verfahrensmängeln des § 83 Abs. 3 statthaft: nicht vorschriftsmäßige Besetzung, Mitwirkung eines ausgeschlossenen oder erfolgreich abgelehnten Richters, Versagung rechtlichen Gehörs, fehlende gesetzliche Vertretung, Verletzung der Öffentlichkeit, fehlende Begründung.",
                "Der BGH hat in der Sache Silver Horse/Power Horse klargestellt: Das Unterlassen einer gebotenen Zulassung ist **kein** Begründungsmangel im Sinne der Nr. 6 und deshalb nicht zulassungsfrei rügbar. Eine Nichtzulassungsbeschwerde kennt das Markengesetz nicht. Bleibt nur die Anhörungsrüge nach § 89a, wenn tatsächlich rechtliches Gehör verletzt wurde. Frist der Rechtsbeschwerde: ein Monat ab Zustellung, Einlegung beim BGH durch einen dort zugelassenen Anwalt (§ 85 Abs. 1, § 84)."],
               level=3, concepts=["rechtsbeschwerde"], norms=["§ 83", "§ 84", "§ 85"], cases=["bgh_silver_horse"], step="step:schema_zulaessigkeit_beschwerde.9"),
        ]),
        # ==============================================================
        dict(id="k13f", titel="Wiedereinsetzung und Weiterbehandlung", einheiten=[
            schema("k13f-1", "Prüfungsschema Wiedereinsetzung", "schema_wiedereinsetzung",
                   "Statthaftigkeit, Antragsfrist, Nachholung, Glaubhaftmachung, fehlendes Verschulden."),
            fall("k13f-2", "Wann beginnt die Zwei-Monats-Frist?",
                 "Die Beschwerdegebühr wird versehentlich zu spät gezahlt. Die Kanzlei bemerkt nichts. Erst ein Hinweis der Rechtspflegerin am 2. Juni macht auf die Fristversäumung aufmerksam. Der Wiedereinsetzungsantrag geht am 18. Juni ein.",
                 "Ist der Wiedereinsetzungsantrag rechtzeitig?", True,
                 ["**Ja!** Der Antrag ist innerhalb von zwei Monaten nach **Wegfall des Hindernisses** zu stellen (§ 91 Abs. 2). Das Hindernis fällt weg, sobald der Beteiligte oder sein Vertreter die Fristversäumung erkennt oder bei zumutbarer Sorgfalt erkennen müsste. Das war hier der Hinweis vom 2. Juni; der Antrag vom 18. Juni liegt weit innerhalb der Frist.",
                  "Zusätzlich müssen innerhalb dieser Frist die versäumte Handlung nachgeholt (§ 91 Abs. 4) und die Wiedereinsetzungsgründe glaubhaft gemacht werden (§ 91 Abs. 3). Absolute Grenze ist ein Jahr nach Ablauf der versäumten Frist (§ 91 Abs. 5). Nach Ablauf der Antragsfrist nachgeschobene neue Tatsachen bleiben unberücksichtigt; der Vortrag muss also von Anfang an vollständig sein."],
                 merke="Zwei Monate ab Kenntnis, ein Jahr absolut, Handlung nachholen.",
                 level=2, concepts=["wiedereinsetzung"], norms=["§ 91"], cases=["bpatg_silver_horse"], step="step:schema_wiedereinsetzung.2"),
            fall("k13f-3", "Zurechnung des Anwaltsverschuldens",
                 "Der sachbearbeitende Patentanwalt hat die Frist falsch berechnet, weil er die Zustellungsfiktion des § 94 übersehen hat. Der Mandant selbst hat alles richtig gemacht.",
                 "Kann dem Mandanten Wiedereinsetzung gewährt werden?", False,
                 ["**Nein!** Das Verschulden des Verfahrensbevollmächtigten wird dem Beteiligten über § 82 Abs. 1 i.V.m. § 85 Abs. 2 ZPO wie eigenes Verschulden zugerechnet. Die Fristberechnung bei Rechtsmitteln gehört zu den Kernaufgaben, die der Anwalt nicht delegieren darf; ein Rechtsirrtum über eine gesetzliche Zustellungsfiktion ist vermeidbar und damit verschuldet.",
                  "Anders liegt es beim Verschulden von **Kanzleiangestellten**: Es wird nicht zugerechnet, wenn der Anwalt zuverlässiges Personal sorgfältig ausgewählt, angeleitet und überwacht und eine funktionierende Fristen- und Ausgangskontrolle eingerichtet hat. Der Mandant behält gegen den Anwalt einen Regressanspruch aus dem Anwaltsvertrag (§ 280 Abs. 1 BGB); das ist in der Beratungsklausur zu erwähnen."],
                 merke="Anwaltsfehler schaden, Büroversehen nicht.",
                 level=2, concepts=["wiedereinsetzung"], norms=["§ 91", "§ 82 Abs. 1"], step="step:schema_wiedereinsetzung.4.1"),
            fall("k13f-4", "Die Ausgangskontrolle",
                 "In der Kanzlei werden alle Eingaben an das DPMA in einer nummerierten Amtsliste erfasst; die Frist wird im Kalender erst gestrichen, wenn die vom Amt abgestempelte Liste zurück ist. Die Anwältinnen kontrollieren stichprobenartig. Eine langjährig fehlerfreie Fachangestellte streicht die Frist dennoch, obwohl die Beschwerde in der Liste fehlt; der Schriftsatz verschwindet.",
                 "Ist Wiedereinsetzung zu gewähren?", True,
                 ["**Ja, das ist vertretbar!** Der Anwalt genügt seiner Sorgfaltspflicht, wenn er eine Ausgangskontrolle einrichtet, bei der die Frist erst nach einem Nachweis des tatsächlichen Ausgangs gestrichen wird, und wenn er zuverlässiges, geschultes Personal stichprobenartig überwacht. Beides liegt vor. Das einmalige Versagen einer bisher fehlerfreien Kraft ist ein nicht zurechenbares Büroversehen.",
                  "Zur Glaubhaftmachung gehören eidesstattliche Versicherungen der Anwältin und der Angestellten, Auszüge aus Fristenkalender und Amtsliste sowie ein Ausdruck aus dem Kanzleisystem (§ 91 Abs. 3, § 294 ZPO). Wer das Gegenteil vertritt, muss begründen, warum die Stichprobenkontrolle unzureichend war; auch das ist mit sauberer Argumentation vertretbar. Für den Tenor: Wird die Wiedereinsetzung gewährt, ist das unanfechtbar (§ 91 Abs. 6 S. 2) und es wird in der Sache entschieden."],
                 merke="Ausgangskontrolle mit Rücklaufnachweis genügt der Sorgfaltspflicht.",
                 level=3, concepts=["wiedereinsetzung", "glaubhaftmachung"], norms=["§ 91"], step="step:schema_wiedereinsetzung.4.2"),
            mc("k13f-5", "Wiedereinsetzung oder Weiterbehandlung?",
               "Das DPMA setzt im Anmeldeverfahren eine Frist zur Behebung eines Mangels; die Anmelderin lässt sie ohne Grund verstreichen, die Anmeldung wird zurückgewiesen. Was hilft?",
               ["Wiedereinsetzung nach § 91, wenn kein Verschulden vorliegt",
                "Weiterbehandlung nach § 91a: Antrag binnen eines Monats, Nachholung der Handlung, 100 Euro, ohne Verschuldensprüfung",
                "Beschwerde, weil die Zurückweisung rechtswidrig ist",
                "Nichts; die Anmeldung ist endgültig verloren"], 1,
               ["§ 91a gibt dem Anmelder die **verschuldensunabhängige** Weiterbehandlung: Antrag innerhalb eines Monats nach Zustellung der Zurückweisung, Nachholung der versäumten Handlung und Zahlung der Gebühr von 100 Euro (Nr. 333 050 des Gebührenverzeichnisses). Ein Grund muss nicht dargelegt werden; gerade deshalb ist sie der einfachere Weg, wenn eine Amtsfrist im Anmeldeverfahren versäumt wurde.",
                "Wiedereinsetzung nach § 91 wäre hier zwar nicht ausgeschlossen, scheitert aber am Verschulden. Umgekehrt hilft § 91a nicht bei der Widerspruchsfrist, der Beschwerdefrist oder der Zahlung der Beschwerdegebühr: Die Vorschrift gilt nur für vom DPMA gesetzte Fristen im Anmeldeverfahren. In der Klausur beide Wege nebeneinander prüfen und den passenden empfehlen."],
               level=2, concepts=["weiterbehandlung", "wiedereinsetzung"], norms=["§ 91a", "§ 91"], step="step:schema_wiedereinsetzung.1"),
        ]),
        # ==============================================================
        dict(id="k13g", titel="Klagen vor dem ordentlichen Gericht", einheiten=[
            intro("k13g-1", "Vier Klagearten und ihre Zulässigkeit",
                  "Neben den Amtsverfahren kennt das Markenrecht vier Klagen, die jeweils eigene Zulässigkeitsfragen aufwerfen.\n\n"
                  "**Verletzungsklage** aus § 14 Abs. 5 und 6 auf Unterlassung, Schadensersatz und Annexansprüche. **Negative Feststellungsklage** des Abgemahnten mit dem Antrag festzustellen, dass die geltend gemachten Ansprüche nicht bestehen. **Verfalls- und Nichtigkeitsklage** nach § 55 gegen den eingetragenen Inhaber. **Eintragungsbewilligungsklage** nach § 44, mit der sich der Markeninhaber gegen die Löschung aufgrund eines Widerspruchs wehrt.\n\n"
                  "Für alle gilt das Zulässigkeitsraster der ZPO: deutsche Gerichtsbarkeit und internationale Zuständigkeit, sachliche und örtliche Zuständigkeit, Partei- und Prozessfähigkeit (§§ 50 bis 52 ZPO), Prozessführungsbefugnis, ordnungsgemäße Klageerhebung mit bestimmtem Antrag (§ 253 Abs. 2 Nr. 2 ZPO), Rechtsschutzbedürfnis und, bei der Feststellungsklage, das Feststellungsinteresse (§ 256 Abs. 1 ZPO).\n\n"
                  "Markenrechtliche Besonderheit: Für alle Kennzeichenstreitsachen sind die **Landgerichte ohne Rücksicht auf den Streitwert ausschließlich** zuständig (§ 140 Abs. 1); die Länder können sie bei einzelnen Landgerichten konzentrieren (§ 140 Abs. 2). Damit gilt vor dem Landgericht Anwaltszwang (§ 78 Abs. 1 ZPO).",
                  concepts=["aktivlegitimation", "unterlassungsanspruch", "nichtigkeit"], norms=["§ 140", "§ 55", "§ 44", "§ 14 Abs. 5"]),
            fall("k13g-2", "Klage vor dem Amtsgericht",
                 "Ein Markeninhaber macht wegen einer einmaligen Verletzung Schadensersatz von 3.000 Euro geltend und erhebt Klage beim Amtsgericht, weil der Streitwert unter 5.000 Euro liegt.",
                 "Ist das Amtsgericht zuständig?", False,
                 ["**Nein!** Für alle Klagen, mit denen ein Anspruch aus einem im Markengesetz geregelten Rechtsverhältnis geltend gemacht wird, sind die Landgerichte **ohne Rücksicht auf den Streitwert ausschließlich** zuständig (§ 140 Abs. 1). Die allgemeine Streitwertgrenze des § 23 Nr. 1 GVG gilt nicht; die ausschließliche Zuständigkeit verdrängt auch § 71 Abs. 1 GVG.",
                  "Das Amtsgericht verweist auf Antrag nach § 281 ZPO an das zuständige Landgericht. Beachten Sie zusätzlich die Konzentrationsverordnungen der Länder nach § 140 Abs. 2: In vielen Ländern sind alle Kennzeichenstreitsachen bei einem oder wenigen Landgerichten zusammengefasst. Vor dem Landgericht müssen sich die Parteien anwaltlich vertreten lassen (§ 78 Abs. 1 ZPO); die Kosten eines mitwirkenden Patentanwalts sind nach § 140 Abs. 3 zu erstatten."],
                 merke="§ 140 Abs. 1: immer das Landgericht, unabhängig vom Streitwert.",
                 level=2, concepts=["unterlassungsanspruch"], norms=["§ 140"], step="step:schema_markenverletzung.1"),
            mc("k13g-3", "Örtliche Zuständigkeit",
               "Eine in Hamburg ansässige Händlerin vertreibt bundesweit über einen Online-Shop Waren, die eine Marke verletzen. Der Markeninhaber sitzt in München. Wo kann er klagen?",
               ["Nur in Hamburg am allgemeinen Gerichtsstand der Beklagten",
                "Am allgemeinen Gerichtsstand in Hamburg oder am Gerichtsstand der unerlaubten Handlung, der bei bundesweit abrufbaren Angeboten grundsätzlich überall eröffnet ist",
                "Nur in München am Sitz des Markeninhabers",
                "Nur dort, wo die Marke eingetragen ist, also beim Landgericht München I"], 1,
               ["Neben dem allgemeinen Gerichtsstand des Beklagten (§§ 12, 17 ZPO für juristische Personen) steht der besondere Gerichtsstand der unerlaubten Handlung nach § 32 ZPO zur Verfügung. Markenverletzungen sind unerlaubte Handlungen in diesem Sinne. Bei Angeboten im Internet ist der Erfolgsort grundsätzlich überall dort, wo das Angebot bestimmungsgemäß abrufbar ist, so dass ein weiter „fliegender Gerichtsstand“ entsteht.",
                "Der Kläger hat die Wahl (§ 35 ZPO) und wird ein Gericht mit einschlägiger Spruchpraxis wählen. Grenzen: Bei Unionsmarken bestimmt Art. 125 UMV die internationale Zuständigkeit, wobei nur der Gerichtsstand des Beklagtensitzes unionsweite Kognition eröffnet, der Handlungsortgerichtsstand nach Art. 125 Abs. 5 UMV dagegen auf das Gebiet des Mitgliedstaats beschränkt ist. § 141 stellt klar, dass die Beschränkung des § 14 UWG nicht gilt."],
               level=3, concepts=["unterlassungsanspruch", "unionsmarke"], norms=["§ 140", "§ 141", "§ 125e"], step="step:schema_markenverletzung.1"),
            fall("k13g-4", "Der unbestimmte Klageantrag",
                 "Der Kläger beantragt, es der Beklagten zu untersagen, „Zeichen zu verwenden, die mit der Klagemarke verwechslungsfähig sind“.",
                 "Ist die Klage zulässig?", False,
                 ["**Nein!** Der Klageantrag muss nach § 253 Abs. 2 Nr. 2 ZPO bestimmt sein: Er muss den Streitgegenstand so konkret bezeichnen, dass der Umfang der Rechtskraft feststeht und die Zwangsvollstreckung möglich ist, ohne dass das Vollstreckungsgericht die Verletzungsfrage neu prüfen muss. Ein Antrag, der nur den Gesetzeswortlaut oder einen unbestimmten Rechtsbegriff wie „verwechslungsfähig“ wiederholt, genügt dem nicht.",
                  "Richtig ist die Bezeichnung der konkreten Verletzungsform: das angegriffene Zeichen in seiner konkreten Gestalt, die betroffenen Waren und Dienstleistungen und die Benutzungshandlung. Üblich ist die Einblendung des Zeichens in den Antrag mit dem Zusatz „wie nachstehend wiedergegeben“. Der Unterlassungsantrag darf leicht verallgemeinern, soweit das Charakteristische der Verletzungsform erfasst bleibt. Das Gericht muss vor einer Abweisung als unzulässig nach § 139 ZPO auf die Bedenken hinweisen."],
                 merke="Konkrete Verletzungsform in den Antrag, nicht den Gesetzeswortlaut.",
                 level=3, concepts=["unterlassungsanspruch"], norms=["§ 14 Abs. 5", "§ 140"], step="step:schema_markenverletzung.5"),
            fall("k13g-5", "Negative Feststellungsklage nach Abmahnung",
                 "Die abgemahnte GmbH gibt keine Unterlassungserklärung ab, sondern erhebt negative Feststellungsklage mit dem Antrag festzustellen, dass dem Abmahnenden die geltend gemachten Ansprüche nicht zustehen.",
                 "Besteht das erforderliche Feststellungsinteresse?", True,
                 ["**Ja!** Das Feststellungsinteresse nach § 256 Abs. 1 ZPO folgt aus der Berühmung: Wer sich eines Anspruchs berühmt und damit die Rechtsposition des Gegners gefährdet, begründet dessen Interesse an alsbaldiger Klärung. Eine markenrechtliche Abmahnung ist eine solche Berühmung. Der Abgemahnte muss nicht abwarten, bis der Gegner klagt.",
                  "Grenzen: Das Feststellungsinteresse entfällt, wenn der Abmahnende die Berühmung eindeutig aufgibt. Erhebt er später **Leistungsklage** und ist diese nicht mehr einseitig zurücknehmbar, wird die negative Feststellungsklage unzulässig; der Kläger erklärt sie dann für erledigt. Umgekehrt ist eine Leistungsklage vorrangig, wenn der Feststellungskläger sein Ziel damit vollständig erreichen könnte, was beim Abgemahnten gerade nicht der Fall ist. Begründet ist die Klage, wenn der behauptete Anspruch nicht besteht; die Darlegungs- und Beweislast für die anspruchsbegründenden Tatsachen trägt weiterhin der Abmahnende."],
                 merke="Berühmung begründet das Feststellungsinteresse; Leistungsklage verdrängt es später.",
                 level=3, concepts=["unterlassungsanspruch"], norms=["§ 14 Abs. 5", "§ 140"], step="step:schema_markenverletzung.1"),
            fall("k13g-6", "Erst Antrag beim DPMA, dann Klage",
                 "Ein Wettbewerber stellt beim DPMA einen Antrag auf Erklärung des Verfalls einer Marke. Wenige Wochen später erhebt er wegen desselben Verfallsgrundes Klage nach § 55 vor dem Landgericht.",
                 "Ist die Klage zulässig?", False,
                 ["**Nein!** § 55 Abs. 1 S. 2 Nr. 2 ordnet ausdrücklich an, dass die Klage unzulässig ist, wenn über denselben Streitgegenstand zwischen den Parteien bereits ein Antrag nach § 53 beim DPMA gestellt wurde. Dasselbe gilt nach Nr. 1, wenn über denselben Streitgegenstand bereits nach § 53 entschieden wurde. Der Antragsteller hat also ein **Wahlrecht**, aber nur einmal: Amtsverfahren oder Klage.",
                  "Die Regelung entspricht dem Verbot der doppelten Rechtshängigkeit (§ 261 Abs. 3 Nr. 1 ZPO) und verhindert widersprechende Entscheidungen; § 325 Abs. 1 ZPO gilt nach § 55 Abs. 1 S. 3 entsprechend, so dass die Entscheidung auch gegen Rechtsnachfolger wirkt. In der Beratungsklausur ist deshalb vor dem ersten Schritt zu klären, welcher Weg günstiger ist: Das Amtsverfahren ist billiger und ohne Anwaltszwang, die Klage erlaubt die Verbindung mit Verletzungsansprüchen und eine Beweisaufnahme."],
                 merke="§ 53 oder § 55, nicht beides: einmaliges Wahlrecht.",
                 level=3, concepts=["verfall", "nichtigkeit", "verwaltungsverfahren_loeschung"], norms=["§ 55", "§ 53", "§ 49"], step="step:schema_loeschung.4"),
            fall("k13g-7", "Die Eintragungsbewilligungsklage",
                 "Die Marke der M-GmbH wird aufgrund eines Widerspruchs gelöscht; die Entscheidung wird unanfechtbar. M meint, ihr stehe die Eintragung trotzdem zu, weil die Widerspruchsmarke in Wahrheit nicht benutzt wird, was im Widerspruchsverfahren nicht geklärt werden konnte.",
                 "Kann M die Eintragung noch erreichen?", True,
                 ["**Ja, über § 44!** Der Inhaber der gelöschten Marke kann im Wege der Klage gegen den Widersprechenden geltend machen, dass ihm trotz der Löschung ein Anspruch auf die Eintragung zusteht. Die Klage ist innerhalb von **sechs Monaten nach Unanfechtbarkeit** der Löschungsentscheidung zu erheben (§ 44 Abs. 2); die Eintragung erfolgt dann unter Wahrung des ursprünglichen Zeitrangs (§ 44 Abs. 3).",
                  "Die Eintragungsbewilligungsklage ist das Korrektiv für die sachlich beschränkte Prüfung im Widerspruchsverfahren, in dem etwa eine Beweisaufnahme über die Benutzung nicht stattfindet. Genau deshalb lehnt das BPatG die Aussetzung eines Widerspruchsbeschwerdeverfahrens regelmäßig ab: Eine zu Unrecht erfolgte Löschung lässt sich über § 44 rückgängig machen. Zuständig ist das Landgericht als Kennzeichenstreitsache (§ 140 Abs. 1)."],
                 merke="§ 44: sechs Monate nach Unanfechtbarkeit, Zeitrang bleibt erhalten.",
                 level=3, concepts=["widerspruch", "aussetzung"], norms=["§ 44", "§ 140"], cases=["bpatg_aussetzung_unionsmarke"], step="step:schema_zulaessigkeit_beschwerde.9"),
            mc("k13g-8", "Wer darf klagen?",
               "Ein ausschließlicher Lizenznehmer möchte selbst gegen einen Verletzer vorgehen. Der Markeninhaber schweigt auf seine Aufforderung, tätig zu werden.",
               ["Der Lizenznehmer kann nie klagen; nur der Inhaber ist aktivlegitimiert",
                "Der Lizenznehmer kann Klage erheben, wenn der Inhaber zustimmt; der ausschließliche Lizenznehmer auch dann, wenn der Inhaber nach förmlicher Aufforderung nicht selbst innerhalb angemessener Frist klagt",
                "Der Lizenznehmer kann immer aus eigenem Recht klagen",
                "Der Lizenznehmer braucht eine Abtretung des Anspruchs"], 1,
               ["§ 30 Abs. 3 bestimmt, dass der Lizenznehmer Klage wegen Verletzung nur mit Zustimmung des Inhabers erheben kann. Für den **ausschließlichen** Lizenznehmer eröffnet Art. 25 Abs. 3 S. 2 MarkenRL, umgesetzt in § 30 Abs. 3 S. 2, die Möglichkeit, selbst zu klagen, wenn der Inhaber nach förmlicher Aufforderung nicht innerhalb einer angemessenen Frist selbst Klage erhebt. Daneben kann der Lizenznehmer nach § 30 Abs. 4 einer Klage des Inhabers beitreten, um seinen eigenen Schaden geltend zu machen.",
                "Dogmatisch handelt es sich um eine Frage der **Prozessführungsbefugnis** und damit der Zulässigkeit, nicht der Begründetheit. Der Alternativweg bleibt die gewillkürte Prozessstandschaft: zulässig bei wirksamer Ermächtigung und eigenem schutzwürdigem Interesse des Ermächtigten, das beim Lizenznehmer regelmäßig vorliegt; die Ermächtigung ist offenzulegen."],
               level=3, concepts=["lizenz", "aktivlegitimation"], norms=["§ 30 Abs. 3", "§ 30 Abs. 4"], step="step:schema_markenverletzung.2.2"),
        ]),
        # ==============================================================
        dict(id="k13h", titel="Tenor formulieren", einheiten=[
            intro("k13h-1", "Der Aufbau des Tenors",
                  "Der Tenor wird in fast jeder NS-Klausur verlangt und ist schnell verdientes Punktepolster. Er folgt immer derselben Ordnung:\n\n"
                  "**1. Ausspruch zum Rechtsbehelf**: aufheben, zurückweisen, verwerfen oder feststellen.\n"
                  "**2. Ausspruch zur Sache**: Löschung anordnen, Widerspruch zurückweisen, zurückverweisen.\n"
                  "**3. Nebenentscheidungen** in fester Reihenfolge: Kosten (§§ 63, 71 Abs. 1), Rückzahlung der Beschwerdegebühr (§ 71 Abs. 3), Zulassung der Rechtsbeschwerde (§ 83 Abs. 2), gegebenenfalls Gegenstandswert.\n\n"
                  "Drei Formeln müssen sitzen, weil sie unterschiedliche Rechtsfolgen ausdrücken:\n\n"
                  "„Die Beschwerde wird **zurückgewiesen**.“ – zulässig, aber unbegründet.\n"
                  "„Die Beschwerde wird als unzulässig **verworfen**.“ – Zulässigkeitsmangel.\n"
                  "„Es wird **festgestellt**, dass die Beschwerde als nicht eingelegt gilt.“ – Gebühr nicht rechtzeitig gezahlt.\n\n"
                  "Die Löschung ist stets warenbezogen auszusprechen, weil § 43 Abs. 2 die Teillöschung vorsieht.",
                  concepts=["beschwerde", "kostenentscheidung", "zahlungstag"], norms=["§ 70", "§ 71", "§ 43 Abs. 2", "§ 83"]),
            mc("k13h-2", "Beschwerde der Widersprechenden hat Erfolg",
               "Die Markenstelle hat den Widerspruch zurückgewiesen. Das BPatG bejaht die Verwechslungsgefahr für alle angegriffenen Waren. Wie lautet der Tenor?",
               ["„Die Beschwerde wird zurückgewiesen.“",
                "„Auf die Beschwerde der Widersprechenden wird der Beschluss der Markenstelle für Klasse 32 des Deutschen Patent- und Markenamts vom 30. Mai 2017 aufgehoben und das Deutsche Patent- und Markenamt angewiesen, die Eintragung der angegriffenen Marke wegen des Widerspruchs aus der IR-Marke 1 037 284 zu löschen.“",
                "„Die angegriffene Marke wird für nichtig erklärt.“",
                "„Der Widerspruch ist begründet.“"], 1,
               ["Der Tenor muss zwei Dinge aussprechen: die **Aufhebung** des angefochtenen Beschlusses und die **Sachentscheidung**. Üblich sind zwei Formulierungen, die beide korrekt sind: die Anweisung an das DPMA, die Eintragung zu löschen, oder unmittelbar „… wird die Löschung der Eintragung der Marke … angeordnet“. Der angefochtene Beschluss ist mit Markenstelle, Klasse und Datum zu bezeichnen, die Widerspruchsmarke mit Registernummer.",
                "„Für nichtig erklärt“ ist die Formel des Nichtigkeitsverfahrens nach §§ 50, 51, 53 und hier falsch. Ein bloßer Ausspruch „Der Widerspruch ist begründet“ ist kein vollstreckungsfähiger Tenor; die Begründetheit gehört in die Gründe. Erfasst die Löschung nur einen Teil der Waren, ist dieser Teil im Tenor aufzuzählen und der Rest ausdrücklich zurückzuweisen."],
               level=2, concepts=["beschwerde", "widerspruch"], norms=["§ 70", "§ 43 Abs. 2"], cases=["bpatg_silver_horse"], step="step:schema_klausur_ns.7"),
            mc("k13h-3", "Gebühr zu spät gezahlt",
               "Die Beschwerdegebühr wird einen Tag nach Fristablauf gutgeschrieben; der Wiedereinsetzungsantrag hat keinen Erfolg. Wie lautet der vollständige Tenor?",
               ["„Die Beschwerde wird als unzulässig verworfen.“",
                "„1. Der Antrag auf Wiedereinsetzung in die Frist zur Zahlung der Beschwerdegebühr wird zurückgewiesen. 2. Die Beschwerde gilt als nicht eingelegt. 3. Die Rückzahlung der Beschwerdegebühr wird angeordnet.“",
                "„Die Beschwerde wird zurückgewiesen; die Kosten trägt der Beschwerdeführer.“",
                "„Das Verfahren wird eingestellt.“"], 1,
               ["Drei Aussprüche gehören zusammen. Erstens die Entscheidung über den **Wiedereinsetzungsantrag**, weil er das Schicksal der Beschwerde bestimmt. Zweitens die **Feststellung**, dass die Beschwerde als nicht eingelegt gilt (§ 64a i.V.m. § 6 Abs. 2 PatKostG); manche Senate formulieren „Es wird festgestellt, dass …“, andere knapp „Die Beschwerde gilt als nicht eingelegt“. Drittens die **Rückzahlung** der Gebühr, die ohne Rechtsgrund gezahlt wurde.",
                "„Als unzulässig verworfen“ wäre unrichtig, weil es an einer Beschwerde fehlt, über deren Zulässigkeit entschieden werden könnte. Eine Kostenentscheidung ergeht nur bei Billigkeitsgründen; das bloße Scheitern an der Gebühr ist keiner."],
               level=3, concepts=["zahlungstag", "wiedereinsetzung", "kostenentscheidung"], norms=["§ 64a", "§ 91", "§ 71 Abs. 3"], step="step:schema_klausur_ns.7"),
            mc("k13h-4", "Das DPMA hat ohne Sachprüfung entschieden",
               "Das DPMA hat den Widerspruch zu Unrecht als unzulässig verworfen und über die Verwechslungsgefahr nicht entschieden. Der Beschwerdeführer beantragt ausdrücklich die Zurückverweisung. Wie lautet der Tenor?",
               ["„Der Beschluss wird aufgehoben; die Löschung der angegriffenen Marke wird angeordnet.“",
                "„1. Der Beschluss der Markenstelle … vom … wird aufgehoben und die Sache zur erneuten Entscheidung an das Deutsche Patent- und Markenamt zurückverwiesen. 2. Die Rückzahlung der Beschwerdegebühr wird angeordnet.“",
                "„Die Sache wird an eine andere Markenstelle abgegeben.“",
                "„Die Beschwerde wird zurückgewiesen, weil das BPatG selbst entscheiden muss.“"], 1,
               ["§ 70 Abs. 3 Nr. 1 erlaubt die Zurückverweisung, wenn das DPMA noch nicht in der Sache entschieden hat; daneben nennt Nr. 2 den wesentlichen Verfahrensmangel und Nr. 3 neue Tatsachen oder Beweismittel. Die Entscheidung steht im Ermessen: Für die Zurückverweisung sprechen der drohende Instanzverlust und ein ausdrücklicher Antrag des Beschwerdeführers, dagegen die Verfahrensdauer.",
                "Die Rückzahlung der Beschwerdegebühr nach § 71 Abs. 3 entspricht in dieser Konstellation der Billigkeit, weil das DPMA fehlerhaft gehandelt und dadurch die Beschwerde veranlasst hat. Eine eigene Sachentscheidung des BPatG wäre zwar möglich, nähme den Beteiligten aber eine Instanz."],
               level=3, concepts=["beschwerde", "kostenentscheidung", "amtsermittlung"], norms=["§ 70 Abs. 3", "§ 71 Abs. 3"], cases=["bpatg_automator", "bpatg_silberweide"], step="step:schema_klausur_ns.6"),
            mc("k13h-5", "Kostenauferlegung",
               "Die Widersprechende hält trotz eines gerichtlichen Hinweises an einer Beschwerde fest, die nach gefestigter Rechtsprechung aussichtslos ist. Der Markeninhaber beantragt, ihr die Kosten aufzuerlegen. Welcher Tenor ist richtig?",
               ["„Die Kosten des Verfahrens trägt die unterliegende Widersprechende.“",
                "„Die Widersprechende hat die Kosten des Verfahrens vor dem Bundespatentgericht einschließlich der dem Inhaber der angegriffenen Marke erwachsenen notwendigen Kosten zu tragen.“",
                "„Die Kosten werden gegeneinander aufgehoben.“",
                "„Über die Kosten ist nicht zu entscheiden.“"], 1,
               ["Im markenrechtlichen Beschwerdeverfahren gibt es keine Kostenfolge nach Unterliegen. Grundsatz ist, dass jeder Beteiligte seine Kosten selbst trägt (§ 71 Abs. 1 S. 2); eine Abweichung setzt Billigkeitsgründe voraus, etwa ein Verhalten, das mit der prozessualen Sorgfalt unvereinbar ist. Das Festhalten an einer nach gefestigter Rechtsprechung aussichtslosen Beschwerde trotz Hinweises ist ein solcher Grund.",
                "Der Tenor benennt deshalb nicht das Unterliegen, sondern wer welche Kosten trägt, und schließt die notwendigen außergerichtlichen Kosten des Gegners ein. Ohne Billigkeitsgründe lautet die Formel schlicht: „Der Kostenantrag wird zurückgewiesen.“ Für das Amtsverfahren gilt § 63 Abs. 1 mit demselben Maßstab; über dessen Kosten kann das BPatG nur entscheiden, wenn die Kostenentscheidung des DPMA angefochten ist."],
               level=3, concepts=["kostenentscheidung"], norms=["§ 71 Abs. 1", "§ 63 Abs. 1"], cases=["bpatg_engelbrecht"], step="step:schema_klausur_ns.6"),
            mc("k13h-6", "Teilweiser Erfolg im Amtsverfahren",
               "Das DPMA hält den Widerspruch für die Waren der Klasse 25 für begründet, für die Klasse 28 nicht. Wie tenoriert die Markenstelle?",
               ["„Dem Widerspruch wird teilweise stattgegeben.“",
                "„Auf den Widerspruch aus der Marke 30 2009 012 084 wird die Eintragung der Marke 30 2018 111 222 für die Waren der Klasse 25 gelöscht. Im Übrigen wird der Widerspruch zurückgewiesen.“",
                "„Die Marke wird teilweise für nichtig erklärt.“",
                "„Die Marke wird gelöscht, soweit Verwechslungsgefahr besteht.“"], 1,
               ["Der Tenor muss aus sich heraus vollstreckbar und eindeutig sein. Er nennt das Widerspruchszeichen mit Registernummer, die angegriffene Marke und die konkret zu löschenden Waren; der abgewiesene Teil wird ausdrücklich zurückgewiesen. „Soweit Verwechslungsgefahr besteht“ ist unzulässig, weil es die Prüfung dem Register überließe.",
                "Rechtsgrundlage ist § 43 Abs. 2 S. 1. Der Beschluss ergeht nach § 61 mit Begründung und Rechtsmittelbelehrung. Bei mehreren Widersprüchen entscheidet die Markenstelle regelmäßig in einem Beschluss, der jedem Beteiligten nur einmal zugestellt wird und nur eine Rechtsmittelfrist auslöst."],
               level=2, concepts=["widerspruch"], norms=["§ 43 Abs. 2", "§ 61"], step="step:schema_widerspruch.4"),
            mc("k13h-7", "Aussetzungsantrag im Tenor",
               "Der Markeninhaber hat die Aussetzung des Beschwerdeverfahrens beantragt, weil er die Widerspruchsmarke beim EUIPO angreift. Das BPatG lehnt die Aussetzung ab und weist die Beschwerde in der Sache zurück. Wie sieht der Tenor aus?",
               ["Nur „Die Beschwerde wird zurückgewiesen.“; über den Aussetzungsantrag ist in den Gründen zu entscheiden",
                "„1. Der Antrag des Markeninhabers auf Aussetzung des Verfahrens wird zurückgewiesen. 2. Die Beschwerde des Markeninhabers wird zurückgewiesen.“",
                "„Das Verfahren wird bis zur Entscheidung des EUIPO ausgesetzt.“",
                "„Die Beschwerde wird als unzulässig verworfen.“"], 1,
               ["Über einen ausdrücklich gestellten Antrag ist im Tenor zu entscheiden, damit erkennbar bleibt, dass er beschieden wurde. Das BPatG stellt deshalb den zurückgewiesenen Aussetzungsantrag voran und entscheidet dann über die Beschwerde. Dasselbe gilt für Kostenanträge, Anträge auf Rückzahlung der Beschwerdegebühr und Wiedereinsetzungsanträge.",
                "In der Sache: Ein Nichtigkeitsantrag beim DPMA ist gegen eine Unionsmarke nicht statthaft und deshalb nicht vorgreiflich; ein Antrag beim EUIPO ist zwar vorgreiflich, doch überwiegen regelmäßig die Gründe gegen eine Aussetzung, weil Ausgang und Dauer offen sind und § 44 eine spätere Korrektur erlaubt."],
               level=3, concepts=["aussetzung", "beschwerde"], norms=["§ 82 Abs. 1", "§ 44"], cases=["bpatg_aussetzung_unionsmarke"], step="step:schema_klausur_ns.6"),
            mc("k13h-8", "Prozessunfähige Beschwerdeführerin",
               "Die Beschwerde wurde vom früheren Geschäftsführer einer wegen Vermögenslosigkeit gelöschten UG eingelegt; das DPMA hatte trotz Unterbrechung entschieden. Wie lautet der Tenor?",
               ["„Die Beschwerde wird zurückgewiesen.“",
                "„1. Die Beschwerde der Markeninhaberin wird als unzulässig verworfen. 2. Die Rückzahlung der Beschwerdegebühr wird angeordnet.“",
                "„Das Verfahren wird ausgesetzt, bis ein Nachtragsliquidator bestellt ist.“",
                "„Der Beschluss des Deutschen Patent- und Markenamts wird für nichtig erklärt.“"], 1,
               ["Die Beschwerde ist mangels Prozessfähigkeit der gelöschten UG unwirksam eingelegt und deshalb **als unzulässig zu verwerfen**; der frühere Geschäftsführer konnte sie nicht wirksam erheben, weil sein Amt mit der Löschung endete. Weil das DPMA trotz der Unterbrechung nach § 241 ZPO entschieden hat, entspricht die Rückzahlung der Beschwerdegebühr der Billigkeit (§ 71 Abs. 3).",
                "Eine Aussetzung durch das Gericht ist nicht nötig: Die Unterbrechung tritt kraft Gesetzes ein und dauert an, bis ein Nachtragsliquidator nach § 66 Abs. 5 GmbHG bestellt ist. Der trotz Unterbrechung ergangene Beschluss des DPMA ist unwirksam, aber nicht nichtig; er kann später mit den statthaften Rechtsmitteln angegriffen werden, sobald die Gesellschaft wieder vertreten ist."],
               level=3, concepts=["beteiligtenfaehigkeit", "kostenentscheidung"], norms=["§ 66 Abs. 1", "§ 71 Abs. 3", "§ 82 Abs. 1"], cases=["bpatg_blizzard_ug"], step="step:schema_zulaessigkeit_beschwerde.3"),
        ]),
    ],
)
