# -*- coding: utf-8 -*-
"""Abgrenzungstabellen zum Designrecht (Felder wie knowledge/distinctions.py). Zellen mit Zitaten ohne Gesetzesangabe werden mit
`qualify` auf das Gesetz der Spalte qualifiziert, damit die Verlinkung stimmt; Zitate mit Gesetzesangabe bleiben unverändert."""
from ..gesetze import qualify


def q(text, law="DesignG"):
    return qualify(text, law)


# ------------------------------------------------------------------ Anspruchsgrundlagen: Unionsrecht -> nationale Schutzgesetze
# Spalten: Grundlage im Unionsrecht | MarkenG | PatG | GebrMG | DesignG | UrhG | Unionsmarke, Unionsgeschmacksmuster | EPGÜ
_AG_SPALTEN = ["Unionsrecht (Richtlinie)", "MarkenG", "PatG", "GebrMG", "DesignG", "UrhG", "UMV / GGV (Unionsschutzrechte)", "EPGÜ und VerfO (europäisches Patent vor dem EPG)"]
_AG_LAWS = [None, "MarkenG", "PatG", "GebrMG", "DesignG", "UrhG", None, None]
_AG = [
    ("Verbotsrecht / Verletzungstatbestand",
     ["Art. 10 MarkenRL; Art. 12 DesignRL (ab 2027 Art. 16 DesignRL 2024); Patente: nicht harmonisiert (Art. 25 bis 27 EPGÜ)", "§ 14 Abs. 2 bis 4, § 15 Abs. 2, 3", "§ 9, § 10", "§ 11", "§ 38 Abs. 1, 2", "§ 15 bis 23, § 97 Abs. 1", "Art. 9 UMV; Art. 19, 10 GGV", "Art. 25 bis 27 EPGÜ (unmittelbare und mittelbare Verletzung, Schranken Art. 27 EPGÜ)"]),
    ("Unterlassung",
     ["Art. 11 DurchsetzungsRL", "§ 14 Abs. 5, § 15 Abs. 4", "§ 139 Abs. 1", "§ 24 Abs. 1", "§ 42 Abs. 1", "§ 97 Abs. 1", "Art. 130 Abs. 1 UMV; Art. 89 Abs. 1 lit. a GGV", "Art. 63 EPGÜ; R. 118.1 VerfO (Entscheidung in der Sache)"]),
    ("Beseitigung",
     ["Art. 10, 11 DurchsetzungsRL", "§ 14 Abs. 5 (Beseitigung), § 18", "§ 139 Abs. 1 (Beseitigung über § 1004 BGB analog), § 140a", "§ 24 Abs. 1, § 24a", "§ 42 Abs. 1, § 43", "§ 97 Abs. 1, § 98", "Art. 130 UMV i.V.m. § 125b MarkenG; Art. 89 Abs. 1 lit. d GGV i.V.m. § 62a DesignG", "Art. 64 EPGÜ; R. 118.1 VerfO"]),
    ("Schadensersatz (dreifache Berechnung)",
     ["Art. 13 DurchsetzungsRL", "§ 14 Abs. 6, § 15 Abs. 5", "§ 139 Abs. 2", "§ 24 Abs. 2", "§ 42 Abs. 2", "§ 97 Abs. 2", "Art. 129 Abs. 2, 130 Abs. 2 UMV i.V.m. § 125b Nr. 2 MarkenG, § 14 Abs. 6 MarkenG; Art. 88 Abs. 2, 89 Abs. 1 lit. d GGV i.V.m. § 62a, § 42 Abs. 2 DesignG", "Art. 68 EPGÜ; R. 118.1 VerfO (Grund), R. 125 bis 144 VerfO (gesondertes Verfahren zur Festsetzung der Höhe)"]),
    ("Entschädigung des schuldlosen Verletzers",
     ["Art. 12 DurchsetzungsRL (fakultativ)", "nicht umgesetzt", "nicht umgesetzt (Verhältnismäßigkeit § 139 Abs. 1 S. 3, 4)", "nicht umgesetzt (§ 24 Abs. 1 S. 3, 4)", "§ 45", "§ 100", "über das nationale Recht: § 45 DesignG (Art. 88 Abs. 2 GGV)", "nicht vorgesehen"]),
    ("Vernichtung",
     ["Art. 10 Abs. 1 lit. c DurchsetzungsRL", "§ 18 Abs. 1", "§ 140a Abs. 1, 2", "§ 24a Abs. 1", "§ 43 Abs. 1", "§ 98 Abs. 1", "Art. 130 UMV i.V.m. § 125b MarkenG, § 18 MarkenG; Art. 89 Abs. 1 lit. c GGV", "Art. 64 Abs. 2 lit. e EPGÜ; R. 118.1 VerfO"]),
    ("Rückruf und Entfernen aus den Vertriebswegen",
     ["Art. 10 Abs. 1 lit. a, b DurchsetzungsRL", "§ 18 Abs. 2", "§ 140a Abs. 3", "§ 24a Abs. 2", "§ 43 Abs. 2", "§ 98 Abs. 2", "§ 18 Abs. 2 MarkenG bzw. § 43 Abs. 2 DesignG über das nationale Recht", "Art. 64 Abs. 2 lit. b, c EPGÜ; R. 118.1 VerfO"]),
    ("Überlassung gegen Vergütung",
     ["Art. 10 DurchsetzungsRL (Alternative zur Vernichtung)", "–", "–", "–", "§ 43 Abs. 3", "§ 98 Abs. 3", "über das nationale Recht: § 43 Abs. 3 DesignG", "–"]),
    ("Auskunft gegen den Verletzer",
     ["Art. 8 Abs. 1 DurchsetzungsRL", "§ 19 Abs. 1, 3", "§ 140b Abs. 1, 3", "§ 24b Abs. 1, 3", "§ 46 Abs. 1, 3", "§ 101 Abs. 1, 3", "§ 19 MarkenG (§ 125b Nr. 2 MarkenG); § 46 DesignG (§ 62a DesignG)", "Art. 67 EPGÜ; R. 191 VerfO (Antrag auf Anordnung der Auskunftserteilung)"]),
    ("Drittauskunft (gewerbliches Ausmaß)",
     ["Art. 8 Abs. 1 lit. a bis d DurchsetzungsRL", "§ 19 Abs. 2", "§ 140b Abs. 2", "§ 24b Abs. 2", "§ 46 Abs. 2", "§ 101 Abs. 2", "§ 19 Abs. 2 MarkenG; § 46 Abs. 2 DesignG", "Art. 67 Abs. 2 EPGÜ; R. 191 VerfO"]),
    ("Rechnungslegung zur Bezifferung",
     ["nicht harmonisiert", "§ 242 BGB (unselbständiger Anspruch)", "§ 242 BGB", "§ 242 BGB", "§ 242 BGB", "§ 242 BGB", "§ 242 BGB über das nationale Recht", "Art. 68 Abs. 3 EPGÜ; R. 191 VerfO (Auskunft über Umsätze und Gewinn), R. 131 VerfO (Vorlage im Schadensersatzverfahren)"]),
    ("Vorlage und Besichtigung",
     ["Art. 6, 7 DurchsetzungsRL", "§ 19a", "§ 140c", "§ 24c", "§ 46a", "§ 101a", "§ 19a MarkenG; § 46a DesignG", "Art. 59 EPGÜ, R. 190 VerfO (Beweisvorlage); Art. 60 EPGÜ, R. 192 bis 198 VerfO (Beweissicherung, saisie), R. 199 VerfO (Inspektion)"]),
    ("Sicherung von Schadensersatzansprüchen",
     ["Art. 9 Abs. 2 DurchsetzungsRL", "§ 19b", "§ 140d", "§ 24d", "§ 46b", "§ 101b", "§ 19b MarkenG; § 46b DesignG", "Art. 61 EPGÜ; R. 200 VerfO (Arrest von Vermögenswerten)"]),
    ("Urteilsbekanntmachung",
     ["Art. 15 DurchsetzungsRL", "§ 19c", "§ 140e", "§ 24e", "§ 47", "§ 103", "§ 19c MarkenG; § 47 DesignG", "Art. 80 EPGÜ; R. 118.1 VerfO"]),
    ("Haftung des Unternehmensinhabers",
     ["nicht harmonisiert", "§ 14 Abs. 7, § 15 Abs. 6", "– (§ 831 BGB)", "–", "§ 44", "§ 99", "§ 14 Abs. 7 MarkenG; § 44 DesignG", "–"]),
    ("Einstweilige Maßnahmen",
     ["Art. 9 DurchsetzungsRL", "§§ 935 ff. ZPO (Dringlichkeitsvermutung nur nach § 12 Abs. 1 UWG)", "§§ 935 ff. ZPO", "§§ 935 ff. ZPO", "§§ 935 ff. ZPO; Auskunft § 46 Abs. 7", "§§ 935 ff. ZPO; § 101 Abs. 7", "Art. 131 UMV; Art. 90 GGV, jeweils nach nationalem Verfahrensrecht", "Art. 62 EPGÜ; R. 205 bis 213 VerfO (summarisches Verfahren, R. 212 VerfO ohne Anhörung des Antragsgegners)"]),
    ("Verjährung / Restschadensersatz",
     ["nicht harmonisiert", "§ 20; § 852 BGB", "§ 141; § 852 BGB", "§ 24f", "§ 49; § 852 BGB", "§ 102; § 852 BGB", "Art. 129 UMV bzw. Art. 88 Abs. 2 GGV: nationales Recht (§ 20 MarkenG, § 49 DesignG)", "Art. 72 EPGÜ (fünf Jahre ab Kenntnis)"]),
    ("Erschöpfung",
     ["Art. 15 MarkenRL; Art. 15 DesignRL", "§ 24", "nicht kodifiziert (Rechtsprechung, unionsweit)", "nicht kodifiziert", "§ 48", "§ 17 Abs. 2", "Art. 15 UMV; Art. 21 GGV", "Art. 29 EPGÜ; Vorbenutzung Art. 28 EPGÜ"]),
    ("Zuständiges Gericht",
     ["nicht harmonisiert", "§ 140 (Kennzeichenstreitsachen, Landgerichte)", "§ 143 (Patentstreitsachen)", "§ 27", "§ 52 (Designstreitsachen); § 63 (Unionsgeschmacksmustergerichte)", "§ 104, § 105", "Art. 123 ff. UMV (Unionsmarkengerichte, § 119 MarkenG); Art. 80 ff. GGV (§ 63 DesignG)", "Art. 32, 33 EPGÜ (EPG ausschließlich, Übergangszeit und Opt-out Art. 83 EPGÜ, R. 5 VerfO); Vollstreckung Art. 82 EPGÜ, R. 354 VerfO"]),
    ("Patentanwaltskosten",
     ["Art. 14 DurchsetzungsRL", "§ 140 Abs. 4 (nur bei Notwendigkeit, EuGH NovaText)", "§ 143 Abs. 3", "§ 27 Abs. 3", "§ 52 Abs. 4", "§ 97a Abs. 3 (Abmahnkosten)", "§ 140 Abs. 4 MarkenG bzw. § 52 Abs. 4 DesignG über das nationale Verfahrensrecht", "Art. 69 EPGÜ; R. 150 bis 157 VerfO (Kostenfestsetzung, R. 152 VerfO Obergrenzen für Vertreterkosten)"]),
    ("Strafbarkeit",
     ["Art. 16 DurchsetzungsRL (nationale Sanktionen), Art. 61 TRIPS", "§ 143, § 143a (Unionsmarke)", "§ 142", "§ 25", "§ 51, § 65 (Unionsgeschmacksmuster)", "§§ 106 bis 108b", "§ 143a MarkenG; § 65 DesignG", "–"]),
    ("Grenzbeschlagnahme",
     ["VO (EU) Nr. 608/2013", "§§ 146 bis 149", "§§ 142a, 142b", "§§ 25a, 25b", "§§ 55 bis 57a", "§ 111b", "VO (EU) Nr. 608/2013 unmittelbar", "–"]),
]

ANSPRUCHSGRUNDLAGEN = dict(
    id="d_des_anspruchsgrundlagen_eu",
    label="Anspruchsgrundlagen nach der Durchsetzungsrichtlinie: MarkenG, PatG, GebrMG, DesignG, UrhG, Unionsschutzrechte, EPGÜ und VerfO",
    concepts=["des_anspruchsgrundlagen_eu", "des_unterlassung", "des_schadensersatz", "des_vernichtung_rueckruf", "des_auskunft", "des_ggm_anwendbares_recht"],
    frage="Wo steht die Anspruchsgrundlage für Unterlassung, Schadensersatz, Vernichtung, Auskunft und die übrigen Rechtsfolgen einer Schutzrechtsverletzung – im Unionsrecht, in jedem der deutschen Schutzgesetze und vor dem Einheitlichen Patentgericht (EPGÜ mit den zugehörigen Regeln der VerfO)?",
    kriterien=[k for k, _ in _AG],
    spalten=list(_AG_SPALTEN),
    rows=[[qualify(cell, law) if law else cell for cell, law in zip(r, _AG_LAWS)] for _, r in _AG],
    merksatz="Eine Richtlinie, ein Bauplan: Verbotsrecht (§ 14 MarkenG, § 9 PatG, § 38 DesignG) plus Unterlassung/Schadensersatz (§ 14 Abs. 5, 6 MarkenG = § 139 PatG = § 24 GebrMG = § 42 DesignG = § 97 UrhG), dann Vernichtung – Auskunft – Vorlage – Sicherung – Bekanntmachung in immer derselben Reihenfolge (§§ 18 bis 19c MarkenG = §§ 140a bis 140e PatG = §§ 24a bis 24e GebrMG = §§ 43, 46 bis 47 DesignG = §§ 98, 101 bis 103 UrhG). Unionsschutzrechte: Verordnung für das Verbot, nationales Recht für die Folgen (Art. 129, 130 UMV, Art. 88, 89 GGV).",
)

# ------------------------------------------------------------------ Umsetzungstabelle DesignRL -> DesignG -> GGV -> DesignRL 2024
_UM_SPALTEN = ["Richtlinie 98/71/EG", "DesignG", "GGV (Unionsgeschmacksmuster)", "Richtlinie (EU) 2024/2823 (ab 9.12.2027)"]
_UM_LAWS = ["DesignRL", "DesignG", "GGV", "DesignRL 2024"]
_UM = [
    ("Begriffe: Design, Erzeugnis, komplexes Erzeugnis", ["Art. 1", "§ 1", "Art. 3", "Art. 2 (neu: Bewegung, Animation, nicht körperliche Erzeugnisse)"]),
    ("Schutz nur durch Eintragung; Bauelemente nur bei Sichtbarkeit", ["Art. 3", "§ 2 Abs. 1, § 4, § 27 Abs. 1", "Art. 1, Art. 4 (daneben nicht eingetragenes Muster, Art. 11)", "Art. 3 („übliche Verwendung“)"]),
    ("Neuheit", ["Art. 4", "§ 2 Abs. 2", "Art. 5", "Art. 4"]),
    ("Eigenart, informierter Benutzer, Gestaltungsfreiheit", ["Art. 5", "§ 2 Abs. 3", "Art. 6", "Art. 5"]),
    ("Offenbarung, Fachkreisklausel, Neuheitsschonfrist zwölf Monate", ["Art. 6", "§ 5, § 6", "Art. 7", "Art. 6"]),
    ("Technisch bedingte Merkmale, Verbindungselemente, modulare Systeme", ["Art. 7", "§ 3 Abs. 1 Nr. 1, 2, Abs. 2", "Art. 8", "Art. 7"]),
    ("Öffentliche Ordnung, gute Sitten", ["Art. 8", "§ 3 Abs. 1 Nr. 3", "Art. 9", "Art. 8"]),
    ("Schutzumfang: kein anderer Gesamteindruck", ["Art. 9", "§ 38 Abs. 2", "Art. 10", "Art. 9"]),
    ("Schutzdauer 5 × 5 Jahre bis 25 Jahre", ["Art. 10", "§ 27 Abs. 2, § 28", "Art. 12 (nicht eingetragen: drei Jahre, Art. 11)", "Art. 10"]),
    ("Recht auf das Design, Arbeitnehmerdesign, Vindikation", ["nicht harmonisiert (Art. 11 Abs. 1 lit. c: Nichtberechtigung)", "§ 7, § 9", "Art. 14, Art. 15", "Art. 11, Art. 12"]),
    ("Eintragungshindernisse und Nichtigkeitsgründe", ["Art. 11", "§ 18, § 33, § 34, § 35", "Art. 25, Art. 47", "Art. 13, Art. 14"]),
    ("Schutzgegenstand: sichtbar wiedergegebene Merkmale", ["nicht harmonisiert", "§ 37", "Art. 18a (neu 2024)", "Art. 15 (neu)"]),
    ("Rechte aus dem Design, Benutzungshandlungen", ["Art. 12", "§ 38 Abs. 1", "Art. 19 (2024: 3D-Druck-Dateien, Durchfuhr)", "Art. 16 (3D-Druck-Dateien, Durchfuhr)"]),
    ("Vermutung der Rechtsgültigkeit", ["nicht harmonisiert", "§ 39, § 52a", "Art. 85", "Art. 17 (neu)"]),
    ("Schranken", ["Art. 13", "§ 40", "Art. 20 (2024: Referenznutzung, Kommentar, Kritik, Parodie)", "Art. 18 (Referenznutzung, Kommentar, Kritik, Parodie)"]),
    ("Reparaturklausel", ["Art. 14 (Übergangsregelung „freeze plus“)", "§ 40a (seit 2.12.2020), § 73 Abs. 2 (Altrechte)", "Art. 20a (früher Art. 110)", "Art. 19 (zwingend; Bestandsschutz bis 9.12.2032)"]),
    ("Erschöpfung", ["Art. 15", "§ 48", "Art. 21", "Art. 20"]),
    ("Vorbenutzungsrecht", ["nicht harmonisiert", "§ 41", "Art. 22", "Art. 21 (neu)"]),
    ("Verhältnis zu anderen Schutzformen, Urheberrecht", ["Art. 16, Art. 17", "§ 50", "Art. 96", "Art. 22, Art. 23"]),
    ("Anmeldung, Wiedergabe, Sammelanmeldung, Anmeldetag", ["nicht harmonisiert", "§ 11, § 12, § 13; §§ 3 bis 12 DesignV", "Art. 35 bis 38", "Art. 25 bis 28 (neu: Video, 3D, Disclaimer)"]),
    ("Aufschiebung der Bekanntmachung", ["nicht harmonisiert", "§ 21 (30 Monate)", "Art. 50 (30 Monate)", "Art. 30 (mindestens 30 Monate)"]),
    ("Nichtigkeitsverfahren vor dem Amt", ["nicht harmonisiert", "§ 34a bis 34c (seit 2014)", "Art. 52 bis 54 (EUIPO)", "Art. 31 (Pflicht zum Amtsverfahren)"]),
    ("Zivilrechtliche Ansprüche bei Verletzung", ["nicht harmonisiert (DurchsetzungsRL 2004/48/EG)", "§§ 42 bis 47, 49", "Art. 88, 89 i.V.m. § 62a DesignG", "nicht harmonisiert (DurchsetzungsRL)"]),
    ("Zuständige Gerichte", ["nicht harmonisiert", "§ 52 (Landgerichte)", "Art. 80 bis 83 (§ 63 DesignG)", "nicht harmonisiert"]),
    ("Umsetzungsfrist / Geltung", ["28.10.2001 (Deutschland: 1.6.2004)", "Geschmacksmusterreformgesetz 2004, Modernisierung 2014, Reparaturklausel 2020", "seit 6.3.2002; Reform 2024 gilt seit 1.5.2025 (Teile 1.7.2026)", "Umsetzung bis 9.12.2027; Richtlinie 98/71/EG wird aufgehoben"]),
]

DISTINCTIONS = [
    ANSPRUCHSGRUNDLAGEN,
    dict(id="d_des_designrl_umsetzung", label="Umsetzungstabelle: Designrichtlinie, DesignG, GGV und die Neufassung 2024",
         concepts=["des_designrl", "des_designrl_2024", "des_unionsreform_2024", "des_ggm_eingetragen"],
         frage="Welcher Artikel der Richtlinie 98/71/EG steckt in welcher Vorschrift des DesignG, wo steht die Parallelvorschrift für das Unionsgeschmacksmuster, und was ändert die Richtlinie (EU) 2024/2823?",
         kriterien=[k for k, _ in _UM], spalten=list(_UM_SPALTEN),
         rows=[[qualify(cell, law) for cell, law in zip(r, _UM_LAWS)] for _, r in _UM],
         merksatz="Materielles Designrecht ist Unionsrecht in nationalem Gewand: Art. 1 bis 17 DesignRL = §§ 1 bis 6, 27, 33, 38, 40, 48, 50 DesignG = Art. 3 bis 25 GGV. National bleiben Verfahren, Ansprüche und Gerichte; ab 2027 harmonisiert die Neufassung auch Schutzgegenstand, Vermutung, Vorbenutzung und Reparaturklausel."),
    dict(id="d_des_neuheit_eigenart", label="Neuheit vs. Eigenart",
         concepts=["des_neuheit", "des_eigenart", "des_informierter_benutzer", "des_gestaltungsfreiheit"],
         frage="Worin unterscheiden sich die beiden Schutzvoraussetzungen des § 2 DesignG, und warum entscheidet fast immer die Eigenart?",
         kriterien=["Norm", "Frage", "Maßstab", "Vergleichsmaßstab", "Schwelle", "Rolle der Gestaltungsfreiheit", "Rolle der Erzeugnisart", "Praktische Bedeutung", "Spiegelbild im Verletzungsprozess"],
         spalten=["Neuheit", "Eigenart"],
         rows=[
             [q("§ 2 Abs. 2") + ", Art. 5 GGV", q("§ 2 Abs. 3") + ", Art. 6 GGV"],
             ["Gibt es ein identisches älteres Design?", "Ruft das Design beim informierten Benutzer einen anderen Gesamteindruck hervor als jedes ältere Design?"],
             ["Objektiver Merkmalsvergleich", "Informierter Benutzer (zwischen Verbraucher und Fachmann)"],
             ["Jedes einzelne offenbarte Design", "Jedes einzelne offenbarte Design; keine Merkmalscollage (EuGH Karen Millen)"],
             ["Identisch, wenn Unterschiede nur in unwesentlichen Einzelheiten", "Anderer Gesamteindruck; bei dichter Musterlage und geringer Gestaltungsfreiheit genügen kleine Unterschiede"],
             ["Keine", "Zentral: großer Spielraum verlangt großen Abstand"],
             ["Gleichgültig (EuGH Easy Sanitary)", "Gleichgültig für den Formenschatz; das Erzeugnis bestimmt aber den informierten Benutzer"],
             ["Selten entscheidend, weil die Identitätsschwelle eng ist", "Der Hauptgrund für Nichtigkeit (§ 33 Abs. 1 Nr. 2 DesignG)"],
             ["–", "Der Schutzumfang (§ 38 Abs. 2 DesignG) wird mit demselben Maßstab bestimmt: Abstand zum Formenschatz (BGH Untersetzer)"],
         ],
         merksatz="Neuheit fragt nach dem Doppelgänger, Eigenart nach dem anderen Gesamteindruck; wer die Eigenart bejaht, hat die Neuheit meist schon mitgeprüft."),
    dict(id="d_des_schutzrechte_produktdesign", label="Schutzrechte am Produktdesign: eingetragenes Design, Unionsgeschmacksmuster, Formmarke, Urheberrecht, UWG",
         concepts=["des_abgrenzung_schutzrechte", "des_urheberrecht_kumulation", "des_uwg_nachahmung", "des_ggm_nicht_eingetragen"],
         frage="Welches Schutzrecht schützt die Gestalt eines Produkts wovor, wie lange und unter welchen Voraussetzungen?",
         kriterien=["Rechtsgrundlage", "Entstehung", "Schutzvoraussetzung", "Schutzgegenstand", "Schutz gegen", "Dauer", "Prüfung durch das Amt", "Angriff auf den Bestand", "Typische Schwäche"],
         spalten=["Eingetragenes Design (DesignG)", "Unionsgeschmacksmuster (GGV)", "Formmarke (MarkenG/UMV)", "Urheberrecht (UrhG)", "Nachahmungsschutz (§ 4 Nr. 3 UWG)"],
         rows=[
             [q("§ 2, § 27, § 38"), "Art. 1, 4, 10, 11, 19 GGV", "§ 3, § 8, § 14 MarkenG; Art. 4, 7, 9 UMV", "§ 2 Abs. 1 Nr. 4, § 97 UrhG", "§ 3, § 4 Nr. 3, § 8, § 9 UWG"],
             ["Eintragung beim DPMA", "Eintragung beim EUIPO oder (nicht eingetragen) erste Offenbarung in der Union", "Eintragung beim DPMA/EUIPO oder Verkehrsgeltung", "Formlos mit der Schöpfung", "Formlos, solange Mitbewerb besteht"],
             ["Neuheit und Eigenart (ungeprüft)", "Neuheit und Eigenart", "Unterscheidungskraft, keine technisch oder wertbedingte Form (§ 3 Abs. 2 MarkenG)", "Eigene geistige Schöpfung, freie kreative Entscheidungen (EuGH Cofemel)", "Wettbewerbliche Eigenart plus Herkunftstäuschung, Rufausbeutung oder unredliche Kenntniserlangung"],
             ["Sichtbar wiedergegebene Erscheinungsform (§ 37 DesignG)", "Erscheinungsform (eingetragen: Wiedergabe; nicht eingetragen: wie offenbart)", "Form als Herkunftshinweis", "Individuelle Züge des Werks", "Konkrete Produktgestaltung, nicht die Idee (BGH Glück)"],
             ["Jede Gestaltung ohne anderen Gesamteindruck, auch unabhängige Parallelschöpfung", "Eingetragen wie DesignG; nicht eingetragen nur gegen Nachahmung", "Verwechslungsgefahr, Bekanntheitsschutz; nur kennzeichenmäßige Benutzung", "Übernahme der originalen Elemente; nur bei Kenntnis (bewusste oder unbewusste Entlehnung)", "Unlautere Nachahmung unter Mitbewerbern"],
             ["25 Jahre ab Anmeldung", "25 Jahre; nicht eingetragen drei Jahre", "Unbegrenzt bei Verlängerung und Benutzung", "70 Jahre nach dem Tod des Urhebers", "Solange wettbewerbliche Eigenart und Unlauterkeit bestehen"],
             ["Nur Formalien und § 18 DesignG", "Nur Formalien und Art. 47 GGV", "Absolute Schutzhindernisse (§ 8 MarkenG)", "Keine", "Keine"],
             ["Nichtigkeitsantrag beim DPMA, Widerklage (§§ 34a, 52b DesignG)", "EUIPO-Antrag oder Widerklage (Art. 52, 84 GGV); nicht eingetragen: Einrede", "Löschung, Nichtigkeit (§§ 49 ff. MarkenG)", "Bestreiten der Werkqualität im Prozess", "Bestreiten der Eigenart und der Unlauterkeit"],
             ["Ungeprüft, Wiedergabe legt den Schutz fest", "Kurze Dauer und Beweislast beim nicht eingetragenen Muster", "Hohe Hürde der Unterscheidungskraft bei Warenformen", "Hohe Hürde bei Gebrauchsgegenständen, Beweis der Kenntnis", "Kein absolutes Recht, Bekanntheit des Originals nötig"],
         ],
         merksatz="Design schützt das Aussehen, die Marke die Herkunft, das Urheberrecht die Persönlichkeit des Schöpfers, das UWG die Lauterkeit des Wettbewerbs; alle vier können kumulieren (§ 50 DesignG)."),
    dict(id="d_des_eingetragen_nicht_eingetragen", label="Eingetragenes Design vs. eingetragenes und nicht eingetragenes Unionsgeschmacksmuster",
         concepts=["des_ggm_eingetragen", "des_ggm_nicht_eingetragen", "des_ggm_gericht", "des_ggm_anwendbares_recht"],
         frage="Wann wähle ich das nationale Design, wann das Unionsgeschmacksmuster, und was leistet das nicht eingetragene Muster?",
         kriterien=["Rechtsgrundlage", "Entstehung", "Gebiet", "Schutzdauer", "Schutzumfang", "Nachahmung erforderlich?", "Vermutung der Rechtsgültigkeit", "Nichtigkeit", "Gericht", "Folgeansprüche", "Kosten"],
         spalten=["Eingetragenes Design (DesignG)", "Eingetragenes Unionsgeschmacksmuster", "Nicht eingetragenes Unionsgeschmacksmuster"],
         rows=[
             [q("§ 27, § 38"), "Art. 1 Abs. 2 lit. b, 12, 19 Abs. 1 GGV", "Art. 1 Abs. 2 lit. a, 11, 19 Abs. 2 GGV"],
             ["Eintragung beim DPMA", "Eintragung beim EUIPO", "Erste Offenbarung in der Union (Art. 11 GGV, EuGH Gautzsch)"],
             ["Deutschland", "Gesamte Union, einheitlich (Art. 1 Abs. 3 GGV)", "Gesamte Union"],
             ["25 Jahre ab Anmeldung", "25 Jahre ab Anmeldung", "3 Jahre ab Offenbarung"],
             ["Kein anderer Gesamteindruck (§ 38 Abs. 2 DesignG)", "Kein anderer Gesamteindruck (Art. 10 GGV)", "Kein anderer Gesamteindruck (Art. 10 GGV)"],
             ["Nein (Ausnahme: Aufschiebung, § 38 Abs. 3 DesignG)", "Nein (Ausnahme: Aufschiebung, Art. 19 Abs. 5 GGV)", "Ja: Nachahmung, Kenntnis vermutet bei Kennenkönnen (Art. 19 Abs. 2 GGV)"],
             [q("§ 39") + "; Angriff nur per Widerklage oder DPMA-Antrag (§ 52a DesignG)", "Art. 85 Abs. 1 GGV; Widerklage oder EUIPO", "Art. 85 Abs. 2 GGV nur bei Darlegung von Offenbarung und Eigenart; Einrede zulässig (EuGH Karen Millen)"],
             [q("§ 33, § 34a, § 52b"), "Art. 24, 25, 52, 84 GGV", "Nur Widerklage oder Einrede (Art. 24 Abs. 3 GGV)"],
             [q("§ 52") + " (Landgericht)", "Unionsgeschmacksmustergericht (Art. 80 GGV, § 63 DesignG), unionsweit im Sitzgerichtsstand (Art. 83 GGV)", "Unionsgeschmacksmustergericht"],
             [q("§§ 42 bis 47"), "Art. 89 GGV; Folgeansprüche nach dem Recht des Verletzungsstaats (Art. 88 Abs. 2 GGV, § 62a DesignG)", "Art. 89 GGV; § 62a DesignG"],
             ["60 EUR, Aufrechterhaltung ab dem 6. Jahr", "EUIPO-Gebühren je Muster und Verlängerung", "Keine"],
         ],
         merksatz="National für den Heimatmarkt, eingetragenes Unionsmuster für die Union, nicht eingetragenes als kostenloser Kurzschutz gegen Nachahmung, der zugleich die zwölfmonatige Schonfrist für die Eintragung startet."),
    dict(id="d_des_nichtigkeit_wege", label="Wege zur Nichtigkeit: DPMA-Antrag, Widerklage, EUIPO",
         concepts=["des_nichtigkeitsverfahren_dpma", "des_widerklage_nichtigkeit", "des_nichtigkeit", "des_beschwerde_bpatg"],
         frage="Wo und wie wird ein eingetragenes Design oder Unionsgeschmacksmuster angegriffen, und wie verhalten sich die Verfahren zueinander?",
         kriterien=["Rechtsgrundlage", "Zuständigkeit", "Antragsbefugnis", "Gründe", "Gebühr", "Besonderheit", "Rechtsmittel", "Verhältnis zum Verletzungsprozess", "Wirkung"],
         spalten=["Nichtigkeitsantrag beim DPMA", "Widerklage vor dem Designgericht", "Antrag beim EUIPO (Unionsgeschmacksmuster)"],
         rows=[
             [q("§ 34a"), q("§ 52b"), "Art. 52, 53 GGV"],
             ["Designabteilung mit drei rechtskundigen Mitgliedern (§ 23 Abs. 2 DesignG)", "Landgericht als Designgericht (§ 52 DesignG) oder Unionsgeschmacksmustergericht (Art. 84 GGV)", "Nichtigkeitsabteilung des EUIPO (Art. 105 GGV)"],
             ["Jedermann (absolute Gründe), Rechtsinhaber (relative), § 34 DesignG", "Beklagter des Verletzungsprozesses, § 34 DesignG entsprechend", "Jedermann bzw. Rechtsinhaber (Art. 52 Abs. 1 GGV)"],
             [q("§ 33 Abs. 1, 2"), q("§ 33 Abs. 1, 2"), "Art. 25 GGV"],
             ["300 EUR je Design", "Gerichtskosten nach Streitwert", "EUIPO-Gebühr"],
             ["Säumnisprinzip: ohne Widerspruch binnen eines Monats wird die Nichtigkeit ohne Sachprüfung ausgesprochen (§ 34a Abs. 2 DesignG)", "Nur im Zusammenhang mit einer Verletzungsklage; Aussetzung und Verweisung ins DPMA auf Antrag des Inhabers (§ 52b Abs. 3 DesignG)", "Beteiligung des angeblichen Verletzers (Art. 54 GGV); Aussetzung des Verletzungsprozesses nach Art. 91 GGV nur bei früherem Antrag (BGH Kinderwagen I)"],
             ["Beschwerde zum BPatG (30. Senat), Rechtsbeschwerde zum BGH bei Zulassung (§ 23 Abs. 4, 5 DesignG)", "Berufung zum OLG, Revision zum BGH", "Beschwerdekammer, EuG, EuGH"],
             ["Aussetzung im Ermessen, zwingend bei Nichtigkeitsüberzeugung (§ 34b DesignG); Beitritt Abgemahnter (§ 34c DesignG)", "Bloße Einrede ausgeschlossen (§ 52a DesignG), außer im Verfügungsverfahren", "Beim nicht eingetragenen Muster kein Amtsverfahren: nur Widerklage oder Einrede (Art. 24 Abs. 3, 85 Abs. 2 GGV)"],
             ["Ex tunc und inter omnes mit Unanfechtbarkeit (§ 33 Abs. 4 DesignG)", "Ex tunc mit Rechtskraft; Mitteilung an das DPMA (§ 52b Abs. 4 DesignG)", "Ex tunc für die gesamte Union (Art. 26 GGV)"],
         ],
         merksatz="Amt oder Widerklage, nie bloße Einrede: Seit 2014 ist das Design ein Registerrecht wie die Marke, das nur in einem förmlichen Verfahren fällt."),
    dict(id="d_des_reparaturklausel", label="Reparaturklausel im Wandel: § 73 DesignG, § 40a DesignG, Art. 110 und 20a GGV, Art. 19 DesignRL 2024",
         concepts=["des_reparaturklausel", "des_bauelement_sichtbarkeit", "des_unionsreform_2024", "des_designrl_2024"],
         frage="Welche Regel gilt für Ersatzteile komplexer Erzeugnisse (Kotflügel, Felgen, Scheinwerfer) in welchem Zeitraum und für welches Schutzrecht?",
         kriterien=["Rechtsgrundlage", "Zeitlicher Geltungsbereich", "Erfasste Bauelemente", "Zweckbindung", "Unterrichtung und Sorgfaltspflichten", "Bestandsschutz für Altrechte", "Leitentscheidung"],
         spalten=["DesignG bis 2020", "§ 40a DesignG (seit 2.12.2020)", "Art. 110 GGV a.F. (bis 30.4.2025)", "Art. 20a GGV (seit 1.5.2025)", "Art. 19 DesignRL 2024 (Umsetzung bis 9.12.2027)"],
         rows=[
             ["Keine Klausel; nur § 73 Abs. 1 DesignG für Handlungen, die nach dem GeschmMG 1988 zulässig waren", q("§ 40a, § 73 Abs. 2"), "Art. 110 GGV a.F. (Übergangsbestimmung)", "Art. 20a GGV", "Art. 19 DesignRL 2024"],
             ["Bis 1.12.2020", "Designs mit Anmeldung ab 2.12.2020", "Handlungen bis 30.4.2025 (BGH Schlüsselgehäuse)", "Handlungen ab 1.5.2025", "Nationales Recht ab spätestens 9.12.2027"],
             ["Voller Ersatzteilschutz", "Formgebundene Bauelemente, von deren Erscheinungsform das Design abhängt („must match“)", "Alle Bauelemente, auch formungebundene wie Felgen (EuGH Acacia/Audi)", "Formgebundene Bauelemente", "Formgebundene Bauelemente"],
             ["–", "Allein zur Reparatur, um das ursprüngliche Erscheinungsbild wiederherzustellen", "Zur Reparatur; optische Identität mit dem Original", "Allein zur Reparatur", "Ausschließlich zur Reparatur (Art. 16 Abs. 1 DesignRL 2024)"],
             ["–", "Ordnungsgemäße Unterrichtung der Verbraucher über den Ursprung (§ 40a Abs. 2 DesignG)", "Hinweis- und Sorgfaltspflichten des Herstellers und Anbieters (EuGH Acacia, BGH Kraftfahrzeugfelgen II)", "Klare, sichtbare Angabe des gewerblichen Ursprungs; keine Erfolgsgarantie für den Endgebrauch (Abs. 2, 3)", "Wie Art. 20a GGV (Abs. 2, 3)"],
             ["–", "Kein Anwendung auf Designs mit Anmeldung vor dem 2.12.2020 (§ 73 Abs. 2 DesignG)", "–", "Übergangsschutz für vor dem 8.12.2024 angemeldete Muster bis 9.12.2032", "Mitgliedstaaten dürfen Altrechte bis 9.12.2032 weiter schützen (Abs. 4)"],
             ["BGH Kraftfahrzeugfelgen (Vorlage)", "–", "EuGH Acacia/Audi und Porsche; BGH Kraftfahrzeugfelgen II; BGH Schlüsselgehäuse", "–", "–"],
         ],
         merksatz="Must fit ist immer frei (§ 3 Abs. 1 Nr. 2 DesignG), must match nur unter der Reparaturklausel: seit 2020 national, seit 2025 dauerhaft im Unionsmuster, ab 2027 überall in der Union."),
]
