# -*- coding: utf-8 -*-
"""Normtexte des Wissenspakets Designrecht: DesignG und DesignV.

Wortlaut aus data/designg.json und designv.json (gesetze-im-internet.de, XML; erzeugt von tools/fetch_design.py). Beide Gesetze
sind wie PatG und PatV als Normfamilien registriert (build_graph.RICHTLINIEN, Knoten `eunorm:designg:<nr>`, `eunorm:designv:<nr>`),
Zitierform in `norms`-Feldern: `§ 2 Abs. 3 DesignG`, `§ 7 Abs. 1 DesignV`. Der Slug des DesignG auf gesetze-im-internet.de ist
weiterhin `geschmmg_2004` (das Gesetz von 2004 wurde 2014 nur umbenannt; die Paragraphenzählung ist gleich geblieben).

Hier nur die Anreicherung: `HINWEISE_*` (Lern- und Klausurhinweis je Vorschrift), `BEZUG_DESIGNV` (Kante `konkretisiert`: welche
DesignG-Vorschrift die Verordnung ausfüllt) und `ENTSPRICHT_DESIGNG` (Kante `entspricht`: Vorschrift gleicher Funktion in der
Verordnung über Unionsgeschmacksmuster, Zitierform `Art. 8 GGV`). Die Umsetzung der Richtlinie 98/71/EG (`implements`) steht in
eurecht.py an den Richtlinienartikeln, die der Durchsetzungsrichtlinie erzeugt build_graph aus durchsetzungsrl.umsetzung_weitere.
"""
import json
from pathlib import Path

_DATA = Path(__file__).resolve().parents[3] / "data"

HINWEISE_DESIGNG = {
    "1": "Legaldefinitionen: Design = zwei- oder dreidimensionale Erscheinungsform eines ganzen Erzeugnisses oder eines Teils davon (Nr. 1; auch Teildesigns, Verzierungen, Farben, Oberflächen); Erzeugnis = jeder industrielle oder handwerkliche Gegenstand einschließlich Verpackung, Ausstattung, grafischer Symbole und Schriftbilder, nicht aber Computerprogramme (Nr. 2); komplexes Erzeugnis (Nr. 3); bestimmungsgemäße Verwendung durch den Endbenutzer ohne Wartung und Reparatur (Nr. 4). Entspricht Art. 1 DesignRL, Art. 3 GGV.",
    "2": "Die beiden Schutzvoraussetzungen: Neuheit (Abs. 2: kein identisches Design vor dem Anmeldetag offenbart; identisch auch bei nur unwesentlichen Unterschieden) und Eigenart (Abs. 3: anderer Gesamteindruck beim informierten Benutzer als jedes einzelne vorbekannte Design; Gestaltungsfreiheit des Entwerfers berücksichtigen). Das DPMA prüft beides nicht (§ 16); sie werden erst im Nichtigkeitsverfahren (§ 33 Abs. 1 Nr. 2) oder per Widerklage relevant. Leitentscheidungen: BGH Untersetzer, Kinderwagen II, EuGH PepsiCo, Karen Millen.",
    "3": "Schutzausschlüsse: ausschließlich technisch bedingte Merkmale (Abs. 1 Nr. 1; EuGH DOCERAM: objektiv, ohne Mehrheit-der-Formen-Test, auch wenn andere Formen möglich wären), Verbindungselemente „must fit“ (Nr. 2), Verstoß gegen öffentliche Ordnung oder gute Sitten (Nr. 3), missbräuchliche Benutzung staatlicher Hoheitszeichen (Nr. 4, Art. 6ter PVÜ). Abs. 2: Rückausnahme für modulare Systeme (Bausteine, EuG Lego). Nr. 3 und 4 prüft das DPMA (§ 18), Nr. 1 und 2 nur im Nichtigkeitsverfahren.",
    "4": "Bauelemente komplexer Erzeugnisse (Ersatzteile) sind nur schutzfähig, soweit sie bei bestimmungsgemäßer Verwendung des komplexen Erzeugnisses sichtbar bleiben und die sichtbaren Merkmale selbst neu sind und Eigenart haben. EuGH Monz/Büchel (Sattelunterseite): Sichtbarkeit aus Sicht des Endbenutzers oder eines außenstehenden Beobachters, auch bei Lagern oder Transport; BGH und BPatG Sattelunterseite II: bei mehreren komplexen Erzeugnissen genügt Sichtbarkeit bei einem.",
    "5": "Offenbarung = der Öffentlichkeit zugänglich gemacht (Bekanntmachung, Ausstellung, Verwendung im Verkehr), es sei denn, die in der Union tätigen Fachkreise des Sektors konnten das im normalen Geschäftsverlauf nicht kennen (Fachkreisklausel; EuGH Gautzsch/Duna: auch Offenbarung außerhalb der EU oder an ein einzelnes Unternehmen kann genügen, Tatfrage). Vertrauliche Mitteilung ist keine Offenbarung. Maßstab für Neuheit, Eigenart und die Priorität des nicht eingetragenen Gemeinschaftsgeschmacksmusters.",
    "6": "Neuheitsschonfrist: Eigene Offenbarungen des Entwerfers oder seines Rechtsnachfolgers (und Dritter als Folge davon) in den zwölf Monaten vor dem Anmeldetag schaden nicht; ebenso missbräuchliche Offenbarungen gegen den Entwerfer. Klausurklassiker: Messe im Januar, Anmeldung im Dezember ist noch rechtzeitig; nach zwölf Monaten bleibt nur das nicht eingetragene Gemeinschaftsgeschmacksmuster (drei Jahre ab erster Offenbarung in der Union, Art. 11 GGV).",
    "7": "Recht auf das eingetragene Design steht dem Entwerfer oder seinem Rechtsnachfolger zu (Abs. 1); Arbeitnehmerdesigns gehören kraft Gesetzes dem Arbeitgeber, wenn sie in Ausübung der Aufgaben oder nach Weisung entstehen (Abs. 2), ohne Inanspruchnahme und ohne Vergütung nach dem ArbnErfG. Freie Mitarbeiter und Designagenturen sind keine Arbeitnehmer: Übertragung muss vertraglich vereinbart werden.",
    "8": "Formelle Berechtigung: Anmelder und eingetragener Rechtsinhaber gelten in Amts- und Gerichtsverfahren als berechtigt; die materielle Berechtigung (§ 7) prüft niemand von Amts wegen. Der wahre Entwerfer ist auf § 9 verwiesen.",
    "9": "Vindikation: Der Berechtigte kann vom Nichtberechtigten Übertragung des eingetragenen Designs oder Einwilligung in die Löschung verlangen (Abs. 1), nur durch Klage binnen drei Jahren ab Bekanntmachung, außer bei Bösgläubigkeit (Abs. 2). Bei Rechtsinhaberwechsel erlöschen Lizenzen; der frühere Inhaber erhält ein Weiterbenutzungsrecht gegen Vergütung (Abs. 3). Parallel: § 8 PatG, Art. 15 GGV.",
    "10": "Entwerferbenennung: Anspruch des Entwerfers gegen Anmelder und Rechtsinhaber, im Verfahren und im Register genannt zu werden (Designerpersönlichkeitsrecht); bei Gemeinschaftsarbeit jeder einzelne. Nur für Anmeldungen ab 1.6.2004 (§ 73 Abs. 4). Parallel: § 37 PatG (Erfindernennung), Art. 18 GGV.",
    "11": "Anmeldegebühr 60 EUR elektronisch, 70 EUR in Papierform (Nr. 341 000, 341 100 GV PatKostG), bei Aufschiebung 30 EUR (Nr. 341 400). Mindestinhalt der Anmeldung (Abs. 2): Eintragungsantrag, Identität des Anmelders, bekanntmachungsfähige Wiedergabe (bis zu zehn Darstellungen je Design, § 7 DesignV); Erzeugnisangabe ist Pflicht (Abs. 3), bestimmt aber nicht den Schutzumfang (Abs. 6). Zusatzangaben: Beschreibung (max. 100 Wörter, § 10 DesignV), Aufschiebungsantrag, Warenklassen, Entwerfer. Details in der DesignV (§ 26). Die Wiedergabe bestimmt den Schutzgegenstand (§ 37): Was nicht abgebildet ist, ist nicht geschützt (BGH Sporthelm, Sportbrille).",
    "12": "Sammelanmeldung: bis zu 100 Designs in einer Anmeldung, seit 2014 ohne Bindung an eine Warenklasse (Gebühr: 60 EUR elektronisch für 2 bis 10 Designs, je weiteres 6 EUR, Nr. 341 200 GV PatKostG); Teilung jederzeit möglich, Anmeldetag bleibt, Differenzgebühr nachzuzahlen (Abs. 2).",
    "13": "Anmeldetag = Eingang der Unterlagen nach § 11 Abs. 2 beim DPMA oder einem bestimmten Patentinformationszentrum (Abs. 1). Bei Priorität (§§ 14, 15) tritt der Prioritätstag für Neuheit, Eigenart, Neuheitsschonfrist, Aufschiebung, ältere Rechte und Vorbenutzungsrecht an die Stelle des Anmeldetags (Abs. 2).",
    "14": "Ausländische Priorität (Art. 4 PVÜ): sechs Monate ab der ersten Anmeldung; Zeit, Land, Aktenzeichen und Abschrift bis zum Ende des 16. Monats nach dem Prioritätstag nachreichen (Abs. 1). Für Nicht-Verbandsstaaten nach Bekanntmachung des BMJ (Abs. 2). Prioritätsnachweis-Frist ist keine Ausschlussfrist für die Priorität selbst, aber ohne Angaben keine Eintragung der Priorität.",
    "15": "Ausstellungspriorität: Zurschaustellung auf amtlichen oder amtlich anerkannten Ausstellungen (Nr. 1) oder im Bundesanzeiger bestimmten sonstigen Ausstellungen (Nr. 2); Anmeldung binnen sechs Monaten nach erstmaliger Zurschaustellung; sie verlängert die Prioritätsfrist des § 14 nicht (Abs. 5). Praktisch selten; wichtiger ist die Neuheitsschonfrist des § 6.",
    "16": "Prüfungsumfang des DPMA: Gebühren, Anmeldetagserfordernisse, sonstige Formerfordernisse (Abs. 1); Neuheit und Eigenart werden nicht geprüft (reines Registerrecht). Mängelrüge mit Frist (Abs. 3), bei Nichtbehebung Zurückweisung; Rechtsbehelf: Weiterbehandlung (§ 17) oder Beschwerde (§ 23 Abs. 4). Bei unzureichender Gebührenzahlung einer Sammelanmeldung entscheidet die Reihenfolge (Abs. 2).",
    "17": "Weiterbehandlung nach Zurückweisung wegen Versäumung einer vom DPMA gesetzten Frist: Antrag und Nachholung binnen eines Monats nach Zustellung plus Gebühr (100 EUR, Nr. 346 000 GV PatKostG); kein Verschuldensmaßstab; keine Wiedereinsetzung in die Weiterbehandlungsfrist (Abs. 3). Wiedereinsetzung für andere Fristen über § 23 Abs. 5 i.V.m. § 123 PatG.",
    "18": "Absolute Eintragungshindernisse, die das DPMA prüft: kein Design im Sinne des § 1 Nr. 1 (etwa bloße Idee, Computerprogramm) und Ausschluss nach § 3 Abs. 1 Nr. 3 oder 4 (Sittenverstoß, Hoheitszeichen). Alles andere (Neuheit, Eigenart, technische Bedingtheit) bleibt dem Nichtigkeitsverfahren vorbehalten.",
    "19": "Registerführung und Eintragung ohne Prüfung der Berechtigung und der Richtigkeit der Angaben (Abs. 2); das DPMA bestimmt die Warenklassen (Locarno-Klassifikation). Mit der Eintragung entsteht der Schutz (§ 27 Abs. 1).",
    "20": "Bekanntmachung der Eintragung mit Wiedergabe, ohne Gewähr für Vollständigkeit der Abbildung; ab Bekanntmachung laufen die Dreijahresfrist der Vindikation (§ 9 Abs. 2) und die Sechsmonatsfrist der Schutzverweigerung bei internationalen Eintragungen. Kann elektronisch erfolgen (DPMAregister).",
    "21": "Aufschiebung der Bildbekanntmachung um 30 Monate ab Anmeldetag auf Antrag mit der Anmeldung (Abs. 1; Geheimhaltung für Saisonware, Modelle vor Markteinführung). Während der Aufschiebung nur Nachahmungsschutz (§ 38 Abs. 3). Erstreckung auf die volle Schutzdauer nur gegen Erstreckungsgebühr (40 EUR je Design, Nr. 341 600 GV PatKostG) innerhalb der Aufschiebungsfrist (Abs. 2), sonst endet der Schutz mit Ablauf der 30 Monate (Abs. 4).",
    "22": "Registereinsicht für jedermann; Einsicht in Wiedergabe und Akten erst nach Bildbekanntmachung, mit Zustimmung oder bei berechtigtem Interesse (Abs. 1). Bei Aufschiebung bleibt die Wiedergabe geheim.",
    "23": "Organisation und Rechtsmittel: Designstellen (Eintragungsverfahren, Abs. 1) und Designabteilungen mit drei rechtskundigen Mitgliedern (Nichtigkeitsverfahren nach § 34a, Abs. 2). Gegen Beschlüsse des DPMA Beschwerde zum BPatG (Abs. 4: 30. Senat für Nichtigkeitssachen, Frist ein Monat über § 73 PatG entsprechend, Gebühr 200 EUR, Nr. 401 300 GV PatKostG), Rechtsbeschwerde zum BGH nur bei Zulassung (Abs. 5). Verweisung auf PatG-Vorschriften (§§ 100 bis 109, 123, 124, 128b PatG).",
    "24": "Verfahrenskostenhilfe im Eintragungs- und Nichtigkeitsverfahren entsprechend §§ 114 ff. ZPO bei hinreichender Aussicht auf Erfolg.",
    "25": "Elektronische Verfahrensführung: Schriftform ersetzt durch § 130a ZPO entsprechend; Einzelheiten in der ERVDPMAV (Anmeldung über DPMAdirekt, § 4 DesignV).",
    "26": "Verordnungsermächtigung für die DesignV (Anmeldeerfordernisse, Wiedergabe, Register, Nichtigkeitsverfahren) und für die Übertragung von Geschäften auf Beamte des gehobenen Dienstes.",
    "27": "Schutz entsteht mit Eintragung (Abs. 1; nicht mit Anmeldung, kein vorläufiger Schutz wie § 33 PatG). Schutzdauer 25 Jahre ab Anmeldetag (Abs. 2) in fünf Fünfjahresabschnitten (§ 28). Gemeinschaftsgeschmacksmuster: ebenfalls 25 Jahre (Art. 12 GGV), nicht eingetragenes drei Jahre (Art. 11 GGV).",
    "28": "Aufrechterhaltung durch Gebührenzahlung jeweils für das 6. bis 10., 11. bis 15., 16. bis 20. und 21. bis 25. Jahr (90, 120, 150 und 180 EUR je Design, Nr. 342 100 bis 342 400 GV PatKostG, Verspätungszuschlag 50 EUR; Fälligkeit und Zuschlagsfrist § 7 PatKostG). Ohne Zahlung endet der Schutz (Abs. 3), Löschung nach § 36 Abs. 1 Nr. 1.",
    "29": "Rechtsnachfolge: Übertragung und Übergang frei möglich, im Zweifel mit dem Unternehmen (Abs. 2); Registereintragung deklaratorisch auf Antrag mit Nachweis (Abs. 3). Legitimation im Verfahren aber nur für den Eingetragenen (§ 8).",
    "30": "Dingliche Rechte (Pfandrecht), Zwangsvollstreckung und Insolvenz: Eintragung im Register auf Antrag mit Nachweis; Verweise auf § 30 PatG.",
    "31": "Lizenzen ausschließlich oder einfach, räumlich beschränkbar (Abs. 1); Verstoß gegen Dauer, Nutzungsform, Erzeugnisse, Gebiet oder Qualität ist Designverletzung (Abs. 2). Klagebefugnis: Lizenznehmer nur mit Zustimmung, ausschließlicher Lizenznehmer nach fruchtloser Aufforderung (Abs. 3); Beitritt zur Verletzungsklage für eigenen Schaden (Abs. 4); Sukzessionsschutz (Abs. 5). Umsetzung von Art. 4 Abs. 1 lit. b DurchsetzungsRL für Lizenznehmer.",
    "32": "Schon die Anmeldung ist übertragbar, verpfändbar und lizenzierbar (entsprechende Anwendung der §§ 29 bis 31).",
    "33": "Nichtigkeitsgründe: absolute (Abs. 1: kein Design, fehlende Neuheit oder Eigenart, Ausschluss nach § 3), Feststellung auf Antrag jedermanns (§ 34 S. 1); relative (Abs. 2: Urheberrechtsverletzung, älteres Design, Zeichen mit Unterscheidungskraft), Erklärung nur auf Antrag des Rechtsinhabers (§ 34 S. 2). Wege: Beschluss des DPMA (§ 34a) oder Urteil auf Widerklage (§ 52b) (Abs. 3); Wirkung ex tunc (Abs. 4); auch nach Ende der Schutzdauer (Abs. 5). Parallel Art. 25 GGV.",
    "34": "Antragsbefugnis: Popularantrag für absolute Nichtigkeitsgründe; relative Gründe nur durch den Inhaber des kollidierenden Rechts; Hoheitszeichen nur durch den Betroffenen. Entspricht Art. 11 Abs. 3 bis 5 DesignRL.",
    "34a": "Nichtigkeitsverfahren vor dem DPMA (seit 1.1.2014, vorher nur Löschungsklage vor den Landgerichten): schriftlicher, begründeter Antrag mit Gebühr (300 EUR je Design, Nr. 346 100 GV PatKostG), Zustellung und einmonatige Widerspruchsfrist des Inhabers; ohne Widerspruch wird die Nichtigkeit ohne Sachprüfung festgestellt oder erklärt (Abs. 2 S. 2, Säumnisprinzip). Bei Widerspruch streitiges Verfahren mit Anhörung, Beschluss mit Kostenentscheidung (Abs. 4, 5); Beschwerde zum BPatG (§ 23 Abs. 4). Sperre bei rechtskräftiger Entscheidung über denselben Streitgegenstand (Abs. 1 S. 4). Meistzitierte Vorschrift des Gesetzes im BPatG-Korpus.",
    "34b": "Aussetzung des Verletzungsprozesses während eines Nichtigkeitsverfahrens im Ermessen des Gerichts; zwingend, wenn das Gericht das Design für nichtig hält. Spiegelbild des § 148 ZPO im Patentverletzungsprozess.",
    "34c": "Beitritt eines Dritten zum laufenden Nichtigkeitsverfahren, wenn er wegen Verletzung desselben Designs verklagt oder abgemahnt wurde (Abs. 1); im Beschwerdeverfahren wird der Beitretende Beschwerdeführer. Parallel § 59 Abs. 2 PatG.",
    "35": "Teilweise Aufrechterhaltung in geänderter Form (Teilnichtigkeit oder Teilverzicht), wenn Neuheit, Eigenart oder Ausschluss nur Teile betreffen oder ältere Rechte nur teilweise entgegenstehen; die Identität des Designs muss gewahrt bleiben (Art. 11 Abs. 7 DesignRL). Geänderte Wiedergabe einreichen (Abs. 2).",
    "36": "Löschungstatbestände: Ende der Schutzdauer, Verzicht (mit Zustimmung eingetragener Rechtsinhaber und Vindikationskläger), Antrag eines Dritten mit Einwilligung, Einwilligung bei Nichtigkeit, rechtskräftige Nichtigkeit (Abs. 1). Teilverzicht führt zu geänderter Eintragung (Abs. 2).",
    "37": "Schutzgegenstand: nur die in der Anmeldung sichtbar wiedergegebenen Erscheinungsmerkmale (Abs. 1). Alles, was die Abbildung nicht zeigt (Rückseite, Farbe bei Schwarz-Weiß-Foto, Material), ist nicht geschützt; Erzeugnisangabe und Beschreibung dienen nur der Auslegung (§ 11 Abs. 6). BGH Sporthelm, Sportbrille, Schalungsbrett (BPatG): Widersprüche zwischen mehreren Darstellungen gehen zu Lasten des Anmelders.",
    "38": "Ausschließliches Benutzungsrecht mit Beispielskatalog (Abs. 1: Herstellen, Anbieten, Inverkehrbringen, Ein- und Ausfuhr, Gebrauch, Besitz zu diesen Zwecken) ohne Verwechslungs- oder Nachahmungserfordernis (objektiver Schutz, außer bei Aufschiebung, Abs. 3). Schutzumfang (Abs. 2): jedes Design, das beim informierten Benutzer keinen anderen Gesamteindruck erweckt; Gestaltungsfreiheit und Abstand zum vorbekannten Formenschatz bestimmen die Reichweite (BGH Untersetzer, Kinderwagen II, Weinkaraffe: großer Abstand = großer Schutzumfang).",
    "39": "Vermutung der Rechtsgültigkeit: Im Verletzungsprozess muss der Beklagte die Nichtigkeit durch Widerklage oder Antrag beim DPMA geltend machen (§ 52a); die bloße Einrede fehlender Neuheit genügt nicht mehr (Ausnahme: einstweilige Verfügung). Umsetzung von Art. 85 GGV in das nationale Recht.",
    "40": "Schranken: private nichtgewerbliche Handlungen (Nr. 1), Versuche (Nr. 2), Zitat und Lehre unter Quellenangabe und ohne unangemessene Beeinträchtigung (Nr. 3; EuGH Nintendo/BigBen: Abbildung des Originalzubehörs zur Erläuterung der Kompatibilität ist zulässig), Schiffe und Luftfahrzeuge im vorübergehenden Inlandsaufenthalt (Nr. 4, 5). Entspricht Art. 13 DesignRL, Art. 20 GGV.",
    "40a": "Reparaturklausel (seit 2.12.2020): kein Schutz für Bauelemente komplexer Erzeugnisse, die allein zur Reparatur zwecks Wiederherstellung des ursprünglichen Erscheinungsbilds verwendet werden (Abs. 1: formgebundene Ersatzteile, „must match“, etwa Kotflügel, Scheinwerfer, Felgen); Voraussetzung: Verbraucher werden über den Ursprung des Teils unterrichtet (Abs. 2). Gilt nicht für Designs, die vor dem 2.12.2020 angemeldet wurden (§ 73 Abs. 2; Bestandsschutz bis 2032 nach Art. 19 Abs. 4 DesignRL 2024). Unionsrecht: Art. 20a GGV (EuGH Acacia/Audi und Porsche: unabhängig von der Formgebundenheit; Sorgfaltspflichten des Herstellers).",
    "41": "Vorbenutzungsrecht: Wer vor dem Anmeldetag im Inland ein identisches, unabhängig entwickeltes Design gutgläubig benutzt oder ernsthafte Anstalten dazu getroffen hat, darf es weiterbenutzen; nicht übertragbar außer mit dem Unternehmensteil (Abs. 2). Parallel § 12 PatG, Art. 22 GGV.",
    "42": "Zentrale Anspruchsgrundlage: Beseitigung und Unterlassung bei Wiederholungs- oder Erstbegehungsgefahr, verschuldensunabhängig (Abs. 1); Schadensersatz bei Vorsatz oder Fahrlässigkeit nach dreifacher Berechnung (Abs. 2: konkreter Schaden, Verletzergewinn, Lizenzanalogie). Aktivlegitimiert: Rechtsinhaber und andere Berechtigte (ausschließlicher Lizenznehmer nach § 31 Abs. 3). Gleichlautend § 14 Abs. 5, 6 MarkenG, § 139 PatG, § 97 UrhG; Umsetzung von Art. 11, 13 DurchsetzungsRL. Für Gemeinschaftsgeschmacksmuster über § 62a und Art. 88 Abs. 2, 89 GGV anwendbar.",
    "43": "Vernichtung der rechtswidrigen Erzeugnisse und Vorrichtungen (Abs. 1), Rückruf und Entfernen aus den Vertriebswegen (Abs. 2), alternativ Überlassung gegen Vergütung bis zu den Herstellungskosten (Abs. 3, Besonderheit des DesignG und UrhG), Verhältnismäßigkeitsvorbehalt (Abs. 4). Art. 10 DurchsetzungsRL; parallel § 18 MarkenG, § 140a PatG, § 98 UrhG.",
    "44": "Haftung des Unternehmensinhabers für Verletzungen durch Arbeitnehmer und Beauftragte auf Unterlassung, Beseitigung und Vernichtung, nicht auf Schadensersatz (dafür § 831 BGB, § 31 BGB). Parallel § 14 Abs. 7 MarkenG, § 99 UrhG; im PatG ohne Entsprechung.",
    "45": "Entschädigung in Geld statt Unterlassung und Vernichtung für den schuldlosen Verletzer bei unverhältnismäßigem Schaden und Zumutbarkeit für den Verletzten (Art. 12 DurchsetzungsRL, nur im DesignG und in § 100 UrhG umgesetzt). Höhe: angemessene Lizenzgebühr; mit Zahlung gilt die Benutzung als erlaubt.",
    "46": "Auskunft über Herkunft und Vertriebsweg gegen den Verletzer (Abs. 1) und bei offensichtlicher Verletzung oder erhobener Klage gegen Dritte in gewerblichem Ausmaß (Abs. 2: Besitzer, Dienstleister, Erbringer von Dienstleistungen); Inhalt (Abs. 3), Verhältnismäßigkeit (Abs. 4), einstweilige Verfügung (Abs. 7), Richtervorbehalt bei Verkehrsdaten (Abs. 9). Art. 8 DurchsetzungsRL; gleichlautend § 19 MarkenG, § 140b PatG, § 101 UrhG. Daneben unselbständiger Rechnungslegungsanspruch aus § 242 BGB.",
    "46a": "Vorlage und Besichtigung bei hinreichender Wahrscheinlichkeit einer Verletzung (Abs. 1), auch per einstweiliger Verfügung mit Geheimnisschutz (Abs. 3); Schadensersatz bei unberechtigtem Begehren (Abs. 5). Art. 6, 7 DurchsetzungsRL; parallel § 19a MarkenG, § 140c PatG.",
    "46b": "Sicherung von Schadensersatzansprüchen: Vorlage von Bank-, Finanz- und Handelsunterlagen bei Verletzung in gewerblichem Ausmaß und gefährdeter Erfüllung (Art. 9 Abs. 2 DurchsetzungsRL); parallel § 19b MarkenG, § 140d PatG.",
    "47": "Urteilsbekanntmachung auf Kosten des Unterlegenen bei berechtigtem Interesse; Befugnis erlischt drei Monate nach Rechtskraft. Art. 15 DurchsetzungsRL; parallel § 19c MarkenG, § 140e PatG.",
    "48": "Erschöpfung: Rechte erstrecken sich nicht auf Erzeugnisse, die vom Rechtsinhaber oder mit seiner Zustimmung im EWR in Verkehr gebracht wurden (unionsweite, keine internationale Erschöpfung). Entspricht Art. 15 DesignRL, Art. 21 GGV; parallel § 24 MarkenG.",
    "49": "Verjährung nach §§ 194 ff. BGB (drei Jahre ab Kenntnis, zehn Jahre absolut); danach Restschadensersatz nach § 852 BGB. Parallel § 20 MarkenG, § 141 PatG.",
    "50": "Ansprüche aus anderen Vorschriften bleiben unberührt: ergänzender wettbewerbsrechtlicher Leistungsschutz (§ 4 Nr. 3 UWG), Urheberrecht (Kumulation, Art. 17 DesignRL; BGH Geburtstagszug, EuGH Cofemel), Markenrecht (Formmarke), Gebrauchsmuster bei technischer Lehre. Art. 16 DesignRL, Art. 96 GGV.",
    "51": "Strafbarkeit der vorsätzlichen Designverletzung (bis drei Jahre, gewerbsmäßig bis fünf Jahre), Antragsdelikt (Abs. 4), Einziehung (Abs. 5), Bekanntmachung der Verurteilung (Abs. 6). Parallel § 143 MarkenG, § 142 PatG; für Gemeinschaftsgeschmacksmuster § 65.",
    "52": "Designstreitsachen: ausschließliche Zuständigkeit der Landgerichte ohne Rücksicht auf den Streitwert (Abs. 1), Konzentration durch Landesverordnung (Abs. 2; Designgerichte wie Düsseldorf, Frankfurt, Hamburg, München), Erstattung der Patentanwaltskosten nach § 13 RVG ohne Notwendigkeitsprüfung (Abs. 4; anders § 140 Abs. 4 MarkenG nach EuGH NovaText). Ausnahme: Nichtigkeit (§ 33) gehört zum DPMA oder zur Widerklage.",
    "52a": "Nichtigkeit nur durch Widerklage oder Antrag beim DPMA, nicht als bloße Einrede (Umsetzung des Registerprinzips wie Art. 85 GGV); Ausnahme im Verfügungsverfahren. Gilt für Streitigkeiten ab 2014 (§ 74 Abs. 3).",
    "52b": "Widerklage auf Nichtigkeit vor dem Designgericht im Verletzungsprozess (Abs. 1); unzulässig nach rechtskräftigem DPMA-Beschluss über denselben Streitgegenstand (Abs. 2); auf Antrag des Inhabers Aussetzung und Verweisung ins DPMA-Verfahren (Abs. 3); Mitteilung an das DPMA und Registervermerk (Abs. 4). Parallel Art. 84 ff. GGV.",
    "53": "Gerichtsstand: Ansprüche, die zugleich auf das UWG gestützt werden (Nachahmungsschutz nach § 4 Nr. 3 UWG), können beim Designgericht geltend gemacht werden, abweichend von § 14 UWG.",
    "54": "Streitwertbegünstigung wie § 142 MarkenG und § 144 PatG: Antrag vor Verhandlung zur Hauptsache bei erheblicher Gefährdung der wirtschaftlichen Lage.",
    "55": "Grenzbeschlagnahme bei offensichtlicher Verletzung auf Antrag und gegen Sicherheitsleistung, soweit nicht die Verordnung (EU) Nr. 608/2013 gilt (Drittlandsware); Verfahren §§ 56, 57. Parallel §§ 146 ff. MarkenG, §§ 142a, 142b PatG.",
    "58": "Inlandsvertreter: Wer im Inland weder Wohnsitz noch Sitz noch Niederlassung hat, braucht für Verfahren vor DPMA und BPatG und zur Geltendmachung der Rechte einen Rechts- oder Patentanwalt (Abs. 1); Gerichtsstand am Geschäftsraum des Vertreters (Abs. 2). Parallel § 25 PatG, § 96 MarkenG.",
    "59": "Designberühmung: Wer den Eindruck eines Designschutzes erweckt („geschütztes Design“, ®-ähnliche Hinweise), muss jedem mit berechtigtem Interesse Auskunft über das Design geben. Parallel § 146 PatG.",
    "62": "Anmeldungen von Gemeinschaftsgeschmacksmustern können beim DPMA eingereicht werden (Art. 35 Abs. 2 GGV); das DPMA vermerkt den Eingangstag und leitet an das EUIPO weiter.",
    "62a": "Für Ansprüche aus Gemeinschaftsgeschmacksmustern gelten, soweit deutsches Recht anwendbar ist (Art. 88 Abs. 2 GGV, EuGH Acacia/BMW: Recht des Verletzungsorts nach Art. 8 Abs. 2 Rom II), die §§ 42 bis 47 und 49 entsprechend: Beseitigung, Schadensersatz, Vernichtung, Rückruf, Auskunft, Vorlage, Sicherung, Urteilsbekanntmachung, Verjährung. Unterlassung folgt direkt aus Art. 89 Abs. 1 lit. a GGV.",
    "63": "Gemeinschaftsgeschmacksmustergerichte (Art. 80 GGV) sind die Landgerichte (Abs. 1), Konzentration wie bei Designstreitsachen; § 52 Abs. 4 (Patentanwaltskosten) und §§ 53, 54 gelten entsprechend (Abs. 4). Internationale Zuständigkeit: Art. 82 GGV; unionsweite Reichweite bei Sitzgerichtsstand (Art. 83 GGV, EuGH Nintendo/BigBen).",
    "65": "Strafbare Verletzung eines Gemeinschaftsgeschmacksmusters (Art. 19 Abs. 1 GGV) wie § 51.",
    "66": "Haager Abkommen (Genfer Akte 1999): internationale Eintragung mit Benennung Deutschlands wird wie eine nationale Anmeldung behandelt (§§ 67 bis 71); die EU ist selbst Vertragspartei (Benennung „EM“ führt zum Gemeinschaftsgeschmacksmuster, Art. 106a ff. GGV).",
    "69": "Prüfung internationaler Eintragungen nur auf Eintragungshindernisse nach § 18; Schutzverweigerung binnen sechs Monaten ab Veröffentlichung an das Internationale Büro (Abs. 2), Stellungnahmefrist vier Monate (Abs. 3, § 23 DesignV).",
    "71": "Wirkung der internationalen Eintragung mit Schutzerstreckung auf Deutschland ab dem Tag der internationalen Eintragung wie ein eingetragenes Design (Abs. 1); entfällt bei Schutzverweigerung oder nachträglicher Schutzentziehung (Abs. 2).",
    "72": "Übergangsrecht: Altmuster vor 1988 nach altem GeschmMG; für Muster vor dem 28.10.2001 (Umsetzungsfrist der DesignRL) gelten die alten Schutzvoraussetzungen (Eigentümlichkeit statt Eigenart) weiter (Abs. 2). Relevant für Nichtigkeitsanträge gegen alte Eintragungen (BGH Sattelunterseite: Design von 2011, neues Recht).",
    "73": "Rechtsbeschränkungen im Übergang: Reparaturfreiheit für Altfälle nach dem GeschmMG 1988 (Abs. 1); § 40a gilt nicht für Designs, die vor dem 2.12.2020 angemeldet wurden (Abs. 2, Bestandsschutz); Entwerferbenennung erst für Anmeldungen ab 1.6.2004 (Abs. 4).",
    "74": "Modernisierungsgesetz 2014: Geschmacksmuster heißen eingetragene Designs (Abs. 1); das DPMA-Nichtigkeitsverfahren gilt auch für Altrechte (Abs. 2); § 52a nur für ab 2014 anhängige Streitigkeiten (Abs. 3).",
}

HINWEISE_DESIGNV = {
    "1": "Die DesignV regelt die Form der Verfahren vor dem DPMA nach dem DesignG (Ermächtigung § 26 DesignG) neben der DPMAV; für die elektronische Einreichung gilt die ERVDPMAV.",
    "3": "Pflichtinhalt der Anmeldung (§ 11 Abs. 2, 3 DesignG): Antrag auf dem Formblatt (§ 5), Identität des Anmelders (§ 6), Wiedergabe (§ 7), Erzeugnisangabe (§ 9); optional Beschreibung (§ 10), Aufschiebungsantrag, Warenklasse, Entwerfer, Priorität (§ 11).",
    "4": "Einreichung schriftlich oder elektronisch (DPMAdirekt); Wiedergaben abweichend von § 11 DPMAV nur im Original oder elektronisch, nicht per Telefax, weil die Bildqualität den Schutzgegenstand bestimmt.",
    "5": "Formblattzwang für den Antrag; bei Sammelanmeldungen zusätzlich Zahl der Designs und Zuordnung der Wiedergaben (Abs. 2); ein Aufschiebungsantrag erfasst alle Designs der Sammelanmeldung (Abs. 3).",
    "6": "Angaben zu Anmelder (Name, Anschrift, bei Gesellschaften Rechtsform und Vertreter), Vertreter und Entwerfer.",
    "7": "Wiedergabe: fotografische oder grafische Darstellungen, bis zu zehn je Design (Abs. 1), Dezimalnummerierung (Abs. 2: 1.1, 1.2 …), neutraler Hintergrund, mindestens 3 × 3 cm, ohne Beiwerk und erläuternden Text (Abs. 3); Flächendesigns mit Rapport (Abs. 6), Schriftzeichen mit vollständigem Zeichensatz und fünf Zeilen Text (Abs. 7). Die Wiedergabe legt den Schutzgegenstand fest (§ 37 DesignG): Unterschiedliche Ausführungen in einem Design sind unzulässig und gehen zu Lasten des Anmelders (BGH Sporthelm).",
    "8": "Flächenmäßige Designabschnitte (Stoffmuster, Tapeten) ersetzen bei Aufschiebung die Wiedergabe (§ 11 Abs. 2 S. 2 DesignG): zwei Exemplare, DIN A4, mit vollständigem Rapport.",
    "9": "Erzeugnisangabe nach der amtlichen Warenliste (Locarno-Klassifikation), bis zu fünf Warenbegriffe, recherchetauglich; das DPMA klassifiziert von Amts wegen. Ohne Einfluss auf den Schutzumfang (§ 11 Abs. 6 DesignG), aber Indiz für das Erzeugnis und den informierten Benutzer.",
    "10": "Beschreibung zur Erläuterung der Wiedergabe: höchstens 100 Wörter, nur zu Merkmalen, die aus der Wiedergabe ersichtlich sind, keine Angaben zu Neuheit oder Wert; sie kann den Schutz nicht erweitern, aber die Auslegung der Wiedergabe stützen (BPatG Schalungsbrett: Hell-Dunkel-Kontrast als Merkmal).",
    "11": "Prioritätsangaben (Zeit, Land, Aktenzeichen, Abschrift; bei Ausstellungspriorität Tag und Nachweis) binnen 16 Monaten (§ 14 Abs. 1, § 15 Abs. 4 DesignG).",
    "12": "Teilung einer Sammelanmeldung durch Erklärung mit Aktenzeichen und Designnummern; wirksam mit Zahlung des Differenzbetrags (§ 12 Abs. 2 DesignG).",
    "13": "Inhalt des Weiterbehandlungsantrags (§ 17 DesignG): Aktenzeichen, Antrag, nachgeholte Handlung; Gebühr 100 EUR, Nr. 346 000 GV PatKostG.",
    "14": "Fremdsprachige Schriftstücke: Übersetzung auf Aufforderung; ohne Übersetzung gilt das Schriftstück als nicht eingegangen (Abs. 2), verspätete Übersetzung verschiebt den Eingangstag.",
    "15": "Registerinhalt: Aktenzeichen, Registernummer, Wiedergabe, Anmeldetag, Erzeugnisangabe, Warenklassen, Inhaber, Vertreter, Entwerfer, Priorität, Aufschiebung; bei Aufschiebung ohne Wiedergabe (Abs. 4).",
    "19": "Angaben bei Erstreckung nach Aufschiebung (§ 21 Abs. 2 DesignG) und bei Aufrechterhaltungsgebühren (§ 28 DesignG), auch für einzelne Designs einer Sammeleintragung.",
    "20": "Verzichtserklärung (§ 36 Abs. 1 Nr. 2 DesignG) mit Designnummer; Teilverzicht mit geänderter Wiedergabe; Zustimmung eingetragener Dritter.",
    "21": "Nichtigkeitsantrag (§ 34a DesignG): Formblatt, Designnummer, Antragsteller, Nichtigkeitsgrund nach § 33 Abs. 1 oder 2 DesignG, Tatsachen und Beweismittel; mehrere Gründe kumulierbar (Abs. 3). Entgegenhaltungen mit Datum und Nachweis der Offenbarung beifügen.",
    "22": "Verfahrensgrundsätze des Nichtigkeitsverfahrens: Verbindung und Aussetzung (Abs. 1), Hinweispflicht des DPMA (Abs. 2), Hinwirken auf vollständigen Vortrag (Abs. 3); gilt für Anträge ab 1.1.2014 (§ 27 Abs. 2).",
    "23": "Stellungnahme zur Schutzverweigerung bei internationalen Eintragungen binnen vier Monaten (§ 69 Abs. 3 DesignG).",
    "25": "Nachträgliche Schutzentziehung internationaler Eintragungen (§ 70 DesignG) im Verfahren nach §§ 21, 22.",
}

# ------------------------------------------------------------------ Brücken
# DesignV -> DesignG (Kante `konkretisiert`): welche Vorschrift des Gesetzes die Verordnung ausfüllt
BEZUG_DESIGNV = {
    "1": ["§ 26 DesignG"], "3": ["§ 11 DesignG"], "4": ["§ 11 DesignG", "§ 25 DesignG"], "5": ["§ 11 DesignG", "§ 12 DesignG"], "6": ["§ 11 DesignG"],
    "7": ["§ 11 DesignG", "§ 37 DesignG"], "8": ["§ 11 DesignG", "§ 21 DesignG"], "9": ["§ 11 DesignG"], "10": ["§ 11 DesignG"], "11": ["§ 14 DesignG", "§ 15 DesignG"],
    "12": ["§ 12 DesignG"], "13": ["§ 17 DesignG"], "15": ["§ 19 DesignG"], "16": ["§ 19 DesignG"], "17": ["§ 19 DesignG"], "18": ["§ 12 DesignG"],
    "19": ["§ 21 DesignG", "§ 28 DesignG"], "20": ["§ 36 DesignG"], "21": ["§ 34a DesignG"], "22": ["§ 34a DesignG"], "23": ["§ 69 DesignG"], "25": ["§ 70 DesignG"],
}
# DesignG -> GGV (Kante `entspricht`): Vorschrift gleicher Funktion in der Verordnung über Unionsgeschmacksmuster
ENTSPRICHT_DESIGNG = {
    "1": ["Art. 3 GGV"], "2": ["Art. 4 GGV", "Art. 5 GGV", "Art. 6 GGV"], "3": ["Art. 8 GGV", "Art. 9 GGV"], "4": ["Art. 4 GGV"], "5": ["Art. 7 GGV"], "6": ["Art. 7 GGV"],
    "7": ["Art. 14 GGV"], "9": ["Art. 15 GGV"], "10": ["Art. 18 GGV"], "11": ["Art. 36 GGV"], "12": ["Art. 37 GGV"], "13": ["Art. 38 GGV"], "14": ["Art. 41 GGV", "Art. 42 GGV"],
    "15": ["Art. 44 GGV"], "16": ["Art. 45 GGV"], "17": ["Art. 67a GGV"], "18": ["Art. 47 GGV"], "19": ["Art. 48 GGV", "Art. 72 GGV"], "20": ["Art. 49 GGV"], "21": ["Art. 50 GGV"],
    "22": ["Art. 74 GGV"], "27": ["Art. 12 GGV"], "28": ["Art. 50d GGV"], "29": ["Art. 28 GGV"], "30": ["Art. 29 GGV", "Art. 30 GGV", "Art. 31 GGV"], "31": ["Art. 32 GGV"],
    "33": ["Art. 25 GGV", "Art. 26 GGV"], "34": ["Art. 52 GGV"], "34a": ["Art. 52 GGV", "Art. 53 GGV"], "35": ["Art. 25 GGV"], "36": ["Art. 51 GGV"],
    "37": ["Art. 18a GGV"], "38": ["Art. 10 GGV", "Art. 19 GGV"], "39": ["Art. 85 GGV"], "40": ["Art. 20 GGV"], "40a": ["Art. 20a GGV"], "41": ["Art. 22 GGV"],
    "42": ["Art. 89 GGV"], "48": ["Art. 21 GGV"], "50": ["Art. 96 GGV"], "52": ["Art. 80 GGV", "Art. 81 GGV"], "52a": ["Art. 85 GGV"], "52b": ["Art. 84 GGV", "Art. 86 GGV"],
    "58": ["Art. 78 GGV"], "62a": ["Art. 88 GGV"], "63": ["Art. 80 GGV", "Art. 82 GGV", "Art. 83 GGV"], "66": ["Art. 106a GGV"],
}

_FAM = [
    dict(key="designg", datei="designg.json", kurz="DesignG", aliase=(), hinweise=HINWEISE_DESIGNG, bezug={}, entspricht=ENTSPRICHT_DESIGNG,
         titel="Designgesetz (DesignG)", gesetz="DesignG (Gesetz über den rechtlichen Schutz von Design; Neufassung 2014, zuletzt geändert 10.8.2021)",
         hinweis="Amtlicher Wortlaut von gesetze-im-internet.de (XML-Fassung; Slug geschmmg_2004, weil das Geschmacksmustergesetz 2004 zum 1.1.2014 nur umbenannt wurde). Die Richtlinie (EU) 2024/2823 ist bis zum 9.12.2027 umzusetzen; das DesignG ist noch nicht angepasst."),
    dict(key="designv", datei="designv.json", kurz="DesignV", aliase=(), hinweise=HINWEISE_DESIGNV, bezug=BEZUG_DESIGNV, entspricht={},
         titel="Designverordnung (DesignV)", gesetz="DesignV (Verordnung zur Ausführung des Designgesetzes, zuletzt geändert 24.6.2026)",
         hinweis="Amtlicher Wortlaut von gesetze-im-internet.de; Fassung mit den zum 1.7.2026 geänderten §§ 10 und 11."),
]

FAMILIEN = []
META = {}
for _f in _FAM:
    _j = json.loads((_DATA / _f["datei"]).read_text(encoding="utf-8"))
    META[_f["key"]] = _j["meta"]
    arts = []
    for _i, _p in enumerate(_j["paragraphen"]):
        nr = _p["nr"]
        arts.append(dict(
            nr=nr, label=_p["label"] + " " + _f["kurz"], titel=_p["titel"], kapitel=_p["teil"] or "Allgemeines", abschnitt=_p["abschnitt"],
            absaetze=[dict(nr=a["nr"], text=a["text"]) for a in _p["absaetze"]], order=_i + 1,
            umsetzung=[], umsetzung_weitere={}, concepts=[], cases=[],
            entspricht=_f["entspricht"].get(nr, []), bezug=_f["bezug"].get(nr, []), hinweis=_f["hinweise"].get(nr, ""), url=_p["url"],
        ))
    FAMILIEN.append(dict(key=_f["key"], kurz=_f["kurz"], aliase=_f["aliase"], titel=_f["titel"], gesetz=_f["gesetz"], artikel=arts,
                         erwaegungsgruende=[], url=_j["meta"]["quelle"], url_pdf=_j["meta"]["quelle_xml"], paraphrase=False,
                         zitat="§", hinweis=_f["hinweis"], stand="; ".join(_j["meta"]["stand"]), korpus="design"))
