# -*- coding: utf-8 -*-
"""Prüfungsschemata zum Designrecht. Schritt-IDs: step:<schema>.<n>.<m>."""
from ..schemata import step

SCHEMATA = [
    dict(
        id="des_schema_schutzfaehigkeit",
        label="Schutzfähigkeit und Nichtigkeit eines eingetragenen Designs (§§ 1 bis 6, 33 DesignG)",
        kategorie="Design: Schutzvoraussetzungen",
        beschreibung="Gutachtenaufbau für den Nichtigkeitsantrag (§ 34a DesignG), die Nichtigkeitswiderklage (§ 52b DesignG) und die Vorfrage im Verletzungsprozess: Schutzgegenstand aus der Wiedergabe, Designbegriff, Ausschlüsse, Sichtbarkeit von Bauelementen, dann Neuheit und Eigenart im Einzelvergleich mit dem offenbarten Formenschatz unter Beachtung der Neuheitsschonfrist. Gleicher Aufbau für Unionsgeschmacksmuster (Art. 3 bis 9, 25 GGV).",
        norms=["§ 1 DesignG", "§ 2 DesignG", "§ 3 DesignG", "§ 4 DesignG", "§ 5 DesignG", "§ 6 DesignG", "§ 33 DesignG"],
        steps=[
            step("A. Schutzgegenstand bestimmen (§ 37 DesignG)", "Welche Merkmale zeigt die Wiedergabe sichtbar? Mehrere Darstellungen auslegen; Erzeugnisangabe und Beschreibung nur als Auslegungshilfe. Zeigen die Darstellungen verschiedene Ausführungsformen, fehlt ein einheitlicher Schutzgegenstand.",
                 concepts=["des_schutzgegenstand", "des_wiedergabe"], norms=["§ 37 Abs. 1 DesignG", "§ 7 DesignV"], cases=["des_bgh_weinkaraffe", "des_bgh_sporthelm", "des_bgh_schneidebrett"]),
            step("B. Design und Erzeugnis (§ 1 DesignG, § 33 Abs. 1 Nr. 1 DesignG)", children=[
                step("1. Erscheinungsform eines Erzeugnisses oder Teils", "Zwei- oder dreidimensionale Erscheinungsform; Erzeugnis ist jeder industrielle oder handwerkliche Gegenstand einschließlich Verpackung, grafischer Symbole und Schriftbilder, nicht Computerprogramme.",
                     concepts=["des_design_begriff", "des_erzeugnis"], norms=["§ 1 DesignG"], cases=["des_eugh_ferrari"]),
                step("2. Bauelement eines komplexen Erzeugnisses: Sichtbarkeit (§ 4 DesignG)", "Bleibt das Bauelement bei bestimmungsgemäßer Verwendung durch den Endbenutzer sichtbar (Sicht des Benutzers und eines außenstehenden Beobachters, auch bei Lagerung und Transport, nicht bei Wartung und Reparatur)? Nur die sichtbaren Merkmale sind zu prüfen.",
                     concepts=["des_bauelement_sichtbarkeit"], norms=["§ 4 DesignG", "§ 1 DesignG"], cases=["des_eugh_monz", "des_bgh_sattelunterseite_ii", "des_bpatg_sattelunterseite_ii"]),
            ]),
            step("C. Ausschlüsse (§ 3 DesignG, § 33 Abs. 1 Nr. 3 DesignG)", children=[
                step("1. Ausschließlich technisch bedingte Merkmale (§ 3 Abs. 1 Nr. 1 DesignG)", "Merkmal für Merkmal objektiv prüfen, ob allein die technische Funktion die Gestaltung bestimmt hat (keine ästhetische Erwägung); Mehrheit der Formen ist nur Indiz. Nichtig nur, wenn alle prägenden Merkmale technisch bedingt sind.",
                     concepts=["des_technisch_bedingt"], norms=["§ 3 Abs. 1 DesignG"], cases=["des_eugh_doceram", "des_bgh_tellerschleifgeraet", "des_bgh_papierspender"],
                     hinweis="Patentschriften, Werbung und Gestaltungsalternativen sind die objektiven Umstände; die Sicht eines objektiven Beobachters ist nicht maßgeblich."),
                step("2. Verbindungselemente und modulare Systeme (§ 3 Abs. 1 Nr. 2, Abs. 2 DesignG)", "Must-fit-Merkmale ausgeschlossen, es sei denn, sie ermöglichen den Zusammenbau austauschbarer Teile in einem Bauteilesystem.",
                     concepts=["des_verbindungselemente"], norms=["§ 3 Abs. 1 DesignG", "§ 3 Abs. 2 DesignG"], cases=["des_eug_lego"]),
                step("3. Öffentliche Ordnung, gute Sitten, Hoheitszeichen (§ 3 Abs. 1 Nr. 3, 4 DesignG)", "Einzige Ausschlüsse, die das DPMA schon bei der Eintragung prüft (§ 18 DesignG); Nr. 4 kann nur der Betroffene geltend machen (§ 34 S. 3 DesignG).",
                     concepts=["des_ordre_public"], norms=["§ 3 Abs. 1 DesignG", "§ 18 DesignG", "§ 34 DesignG"]),
            ]),
            step("D. Formenschatz: Offenbarung vor dem maßgeblichen Tag (§§ 5, 6, 13 DesignG)", children=[
                step("1. Maßgeblicher Tag", "Anmeldetag oder Prioritätstag (§ 13 Abs. 2 DesignG); beim nicht eingetragenen Unionsgeschmacksmuster der Tag der ersten Offenbarung in der Union.",
                     concepts=["des_anmeldetag", "des_prioritaet"], norms=["§ 13 DesignG", "§ 14 DesignG"]),
                step("2. Offenbarung der Entgegenhaltung (§ 5 DesignG)", "Bekanntmachung, Ausstellung, Verwendung im Verkehr; Ausnahme, wenn die Fachkreise des Sektors in der Union das im normalen Geschäftsverlauf nicht kennen konnten; Vertraulichkeit schließt Offenbarung aus. Beweislast beim Angreifer.",
                     concepts=["des_offenbarung", "des_formenschatz"], norms=["§ 5 DesignG", "Art. 7 GGV"], cases=["des_eugh_gautzsch", "des_bgh_ballerinaschuh", "des_bgh_verlaengerte_limousinen"]),
                step("3. Neuheitsschonfrist (§ 6 DesignG)", "Eigene Offenbarungen des Entwerfers oder seines Rechtsnachfolgers (und darauf beruhende Dritter) in den zwölf Monaten vor dem Anmeldetag bleiben außer Betracht; ebenso missbräuchliche Offenbarungen.",
                     concepts=["des_neuheitsschonfrist"], norms=["§ 6 DesignG"]),
            ]),
            step("E. Neuheit (§ 2 Abs. 2 DesignG, § 33 Abs. 1 Nr. 2 DesignG)", "Einzelvergleich mit jeder Entgegenhaltung: identisch, wenn sich die Merkmale nur in unwesentlichen Einzelheiten unterscheiden; Erzeugnisart der Entgegenhaltung ist gleichgültig.",
                 concepts=["des_neuheit"], norms=["§ 2 Abs. 2 DesignG"], cases=["des_eugh_easy_sanitary"]),
            step("F. Eigenart (§ 2 Abs. 3 DesignG, § 33 Abs. 1 Nr. 2 DesignG)", children=[
                step("1. Informierter Benutzer", "Benutzer des Erzeugnisses mit Kenntnis der Designs des Sektors und erhöhter Aufmerksamkeit; zwischen Durchschnittsverbraucher und Fachmann.",
                     concepts=["des_informierter_benutzer"], norms=["§ 2 Abs. 3 DesignG"], cases=["des_eugh_pepsico"]),
                step("2. Gestaltungsfreiheit und Musterdichte", "Technische und gesetzliche Vorgaben, Sättigung des Formenschatzes; geringe Freiheit lässt kleine Unterschiede genügen.",
                     concepts=["des_gestaltungsfreiheit", "des_formenschatz"], norms=["§ 2 Abs. 3 DesignG"], cases=["des_bgh_untersetzer", "des_eugh_pepsico"]),
                step("3. Gesamteindruck im Einzelvergleich", "Vergleich mit jedem einzelnen älteren Design, keine Merkmalscollage; prägende Merkmale gewichten, technisch bedingte zurückstellen, Farbe allein reicht selten.",
                     concepts=["des_gesamteindruck", "des_eigenart"], norms=["§ 2 Abs. 3 DesignG"], cases=["des_eugh_karen_millen", "des_bgh_meda_gate", "des_bgh_verlaengerte_limousinen", "des_bpatg_violette_trittleiter"],
                     hinweis="Formel: „Das Design ruft beim informierten Benutzer einen anderen Gesamteindruck hervor als das Design X, weil …“ – kein Wort von Eigentümlichkeit oder Gestaltungshöhe."),
            ]),
            step("G. Relative Nichtigkeitsgründe (§ 33 Abs. 2 DesignG)", "Nur auf Antrag des Rechtsinhabers: Urheberrechtsverletzung, älteres eingetragenes Design (auch erst nach dem Anmeldetag bekannt gemacht), Zeichen mit Unterscheidungskraft.",
                 concepts=["des_nichtigkeit"], norms=["§ 33 Abs. 2 DesignG", "§ 34 DesignG"]),
            step("H. Ergebnis", "Schutzfähig: Vermutung der Rechtsgültigkeit bleibt (§ 39 DesignG). Nichtig: Feststellung oder Erklärung durch DPMA oder Urteil, Wirkung ex tunc (§ 33 Abs. 3, 4 DesignG); teilweise Aufrechterhaltung in geänderter Form (§ 35 DesignG).",
                 concepts=["des_nichtigkeit", "des_teilweise_aufrechterhaltung", "des_vermutung_rechtsgueltigkeit"], norms=["§ 33 Abs. 3 DesignG", "§ 33 Abs. 4 DesignG", "§ 35 DesignG", "§ 39 DesignG"]),
        ],
    ),
    dict(
        id="des_schema_designverletzung",
        label="Designverletzung (§§ 38 bis 49 DesignG)",
        kategorie="Design: Schutzwirkung und Schranken",
        beschreibung="Anspruchsaufbau für Unterlassung, Schadensersatz und die Annexansprüche: Aktivlegitimation, Bestand und Schutzgegenstand des Klagedesigns, Benutzungshandlung, Schutzumfang nach dem Gesamteindruck, Einwendungen (Schranken, Vorbenutzung, Erschöpfung, Reparaturklausel, Nichtigkeit nur per Widerklage), Rechtsfolgen und Verjährung. Für Unionsgeschmacksmuster über Art. 19, 10, 20 bis 22, 89 GGV und § 62a DesignG.",
        norms=["§ 38 DesignG", "§ 39 DesignG", "§ 40 DesignG", "§ 41 DesignG", "§ 42 DesignG", "§ 43 DesignG", "§ 46 DesignG", "§ 48 DesignG", "§ 49 DesignG"],
        steps=[
            step("A. Aktivlegitimation", "Eingetragener Rechtsinhaber (§ 8 DesignG) oder anderer Berechtigter: ausschließlicher Lizenznehmer nach Aufforderung (§ 31 Abs. 3 DesignG); beim nicht eingetragenen Unionsgeschmacksmuster Inhaberschaft nach Art. 14 GGV beweisen.",
                 concepts=["des_entwerfer_recht", "des_lizenz"], norms=["§ 8 DesignG", "§ 31 Abs. 3 DesignG", "§ 42 Abs. 1 DesignG"], cases=["des_bgh_bolerojaeckchen"]),
            step("B. Klagedesign: Bestand und Schutzgegenstand", children=[
                step("1. Eingetragen und in Kraft", "Eintragung (§ 27 Abs. 1 DesignG), Aufrechterhaltung (§ 28 DesignG), keine Löschung; bei Aufschiebung nur Nachahmungsschutz (§ 38 Abs. 3 DesignG). Vermutung der Rechtsgültigkeit (§ 39 DesignG).",
                     concepts=["des_schutzdauer", "des_vermutung_rechtsgueltigkeit", "des_aufschiebung"], norms=["§ 27 DesignG", "§ 28 DesignG", "§ 39 DesignG", "§ 38 Abs. 3 DesignG"]),
                step("2. Schutzgegenstand aus der Wiedergabe (§ 37 DesignG)", "Nur die sichtbar wiedergegebenen Merkmale; Schwarz-Weiß-Eintragung schützt die Form ohne Farbe.",
                     concepts=["des_schutzgegenstand"], norms=["§ 37 Abs. 1 DesignG"], cases=["des_bgh_weinkaraffe", "des_bgh_schreibgeraete"]),
            ]),
            step("C. Benutzungshandlung des Beklagten (§ 38 Abs. 1 DesignG)", "Herstellen, Anbieten, Inverkehrbringen, Ein- oder Ausfuhr, Gebrauch oder Besitz eines Erzeugnisses mit dem Design ohne Zustimmung; Erstbegehungsgefahr genügt für Unterlassung.",
                 concepts=["des_benutzung"], norms=["§ 38 Abs. 1 DesignG", "Art. 19 GGV"], cases=["des_bgh_kinderwagen_i", "des_eugh_celaya"]),
            step("D. Schutzumfang: kein anderer Gesamteindruck (§ 38 Abs. 2 DesignG)", children=[
                step("1. Formenschatz und Gestaltungsfreiheit", "Abstand des Klagedesigns zum vorbekannten Formenschatz und Musterdichte bestimmen die Reichweite; der Beklagte muss den Formenschatz vortragen.",
                     concepts=["des_schutzumfang", "des_gestaltungsfreiheit", "des_formenschatz"], norms=["§ 38 Abs. 2 DesignG"], cases=["des_bgh_untersetzer", "des_bgh_kinderwagen_ii", "des_bgh_ballerinaschuh"]),
                step("2. Gesamteindruck beim informierten Benutzer", "Merkmalsvergleich zwischen eingetragenem Design und angegriffener Ausführungsform bei bestimmungsgemäßer Verwendung; Übereinstimmungen und Unterschiede gewichten; keine Verwechslungsgefahr und keine Kenntnis erforderlich.",
                     concepts=["des_gesamteindruck", "des_informierter_benutzer"], norms=["§ 38 Abs. 2 DesignG"], cases=["des_bgh_armbanduhr", "des_bgh_meda_gate", "des_eugh_pepsico"],
                     hinweis="Formel: „Die angegriffene Ausführungsform erweckt beim informierten Benutzer keinen anderen Gesamteindruck als das Klagedesign, weil …“"),
            ]),
            step("E. Einwendungen und Einreden", children=[
                step("1. Schranken (§ 40 DesignG)", "Privater Bereich, Versuche, Zitat und Lehre, Schiffe und Luftfahrzeuge.",
                     concepts=["des_schranken", "des_zitierschranke"], norms=["§ 40 DesignG"], cases=["des_bgh_ice", "des_eugh_nintendo"]),
                step("2. Reparaturklausel (§ 40a DesignG, Art. 20a GGV)", "Formgebundenes Bauelement allein zur Reparatur des komplexen Erzeugnisses, Unterrichtung der Verbraucher, Sorgfaltspflichten; Bestandsschutz für Designs vor dem 2.12.2020 (§ 73 Abs. 2 DesignG).",
                     concepts=["des_reparaturklausel"], norms=["§ 40a DesignG", "§ 73 DesignG", "Art. 20a GGV"], cases=["des_eugh_acacia_audi", "des_bgh_kraftfahrzeugfelgen_ii", "des_bgh_schluesselgehaeuse"]),
                step("3. Vorbenutzungsrecht (§ 41 DesignG)", "Gutgläubige Benutzung oder ernsthafte Anstalten im Inland vor dem Anmeldetag mit unabhängig entwickeltem identischem Design.",
                     concepts=["des_vorbenutzungsrecht"], norms=["§ 41 DesignG"], cases=["des_bgh_bettgestell"]),
                step("4. Erschöpfung (§ 48 DesignG)", "Inverkehrbringen im EWR durch den Rechtsinhaber oder mit seiner Zustimmung; keine internationale Erschöpfung.",
                     concepts=["des_erschoepfung"], norms=["§ 48 DesignG"]),
                step("5. Nichtigkeit nur per Widerklage oder DPMA-Antrag (§ 52a DesignG)", "Bloße Einrede fehlender Neuheit oder Eigenart ist unzulässig (Ausnahme: einstweilige Verfügung); Aussetzung nach § 34b DesignG.",
                     concepts=["des_widerklage_nichtigkeit"], norms=["§ 52a DesignG", "§ 52b DesignG", "§ 34b DesignG"], cases=["des_eugh_karen_millen"]),
            ]),
            step("F. Rechtsfolgen", children=[
                step("1. Beseitigung und Unterlassung (§ 42 Abs. 1 DesignG)", "Verschuldensunabhängig; Wiederholungsgefahr vermutet; auch gegen den Unternehmensinhaber (§ 44 DesignG).",
                     concepts=["des_unterlassung"], norms=["§ 42 Abs. 1 DesignG", "§ 44 DesignG"]),
                step("2. Schadensersatz (§ 42 Abs. 2 DesignG)", "Vorsatz oder Fahrlässigkeit; dreifache Schadensberechnung; Auskunft und Rechnungslegung zur Bezifferung (§ 46 DesignG, § 242 BGB); Entschädigung des schuldlosen Verletzers (§ 45 DesignG).",
                     concepts=["des_schadensersatz", "des_auskunft"], norms=["§ 42 Abs. 2 DesignG", "§ 45 DesignG", "§ 46 DesignG"]),
                step("3. Vernichtung, Rückruf, Überlassung (§ 43 DesignG)", "Verhältnismäßigkeitsvorbehalt (§ 43 Abs. 4 DesignG); Überlassung gegen Vergütung als Alternative.",
                     concepts=["des_vernichtung_rueckruf"], norms=["§ 43 DesignG"]),
                step("4. Auskunft, Vorlage, Sicherung, Urteilsbekanntmachung (§§ 46 bis 47 DesignG)", "Drittauskunft in gewerblichem Ausmaß; Vorlage und Besichtigung; Bank- und Handelsunterlagen; Bekanntmachung bei berechtigtem Interesse.",
                     concepts=["des_auskunft", "des_vorlage_besichtigung"], norms=["§ 46 DesignG", "§ 46a DesignG", "§ 46b DesignG", "§ 47 DesignG"]),
            ]),
            step("G. Verjährung und Verfahren", "Drei Jahre ab Kenntnis, zehn absolut, Restschadensersatz nach § 852 BGB (§ 49 DesignG); Designstreitsache vor dem Landgericht (§ 52 DesignG), Patentanwaltskosten erstattungsfähig (§ 52 Abs. 4 DesignG); Eilverfahren nach §§ 935 ff. ZPO.",
                 concepts=["des_verjaehrung", "des_designstreitsachen"], norms=["§ 49 DesignG", "§ 52 DesignG"], cases=["des_bgh_griffleiste"]),
        ],
    ),
    dict(
        id="des_schema_nichtigkeitsverfahren",
        label="Nichtigkeitsverfahren vor dem DPMA (§§ 34 bis 34c DesignG) und Beschwerde",
        kategorie="Design: Nichtigkeit",
        beschreibung="Zulässigkeit und Begründetheit des Antrags auf Feststellung oder Erklärung der Nichtigkeit, Säumnisprinzip bei fehlendem Widerspruch, Beschwerde zum BPatG und Rechtsbeschwerde; daneben die Widerklage im Verletzungsprozess und der Antrag beim EUIPO für Unionsgeschmacksmuster.",
        norms=["§ 33 DesignG", "§ 34 DesignG", "§ 34a DesignG", "§ 34b DesignG", "§ 34c DesignG", "§ 23 DesignG", "§ 52b DesignG"],
        steps=[
            step("A. Zulässigkeit des Antrags", children=[
                step("1. Form und Inhalt (§ 34a Abs. 1 DesignG, § 21 DesignV)", "Schriftlich beim DPMA, Designnummer, Nichtigkeitsgrund nach § 33 Abs. 1 oder Abs. 2 DesignG, Tatsachen und Beweismittel (Entgegenhaltungen mit Offenbarungsnachweis); Formblatt.",
                     concepts=["des_nichtigkeitsverfahren_dpma"], norms=["§ 34a Abs. 1 DesignG", "§ 21 DesignV"]),
                step("2. Gebühr", "300 EUR je Design (Nr. 346 100 GV PatKostG), fällig mit Antrag; Zahlungsfrist drei Monate (§ 6 Abs. 1 PatKostG), sonst gilt der Antrag als zurückgenommen (§ 6 Abs. 2 PatKostG).",
                     concepts=["des_nichtigkeitsverfahren_dpma"], norms=["§ 34a DesignG", "§ 6 PatKostG"]),
                step("3. Antragsbefugnis (§ 34 DesignG)", "Absolute Gründe: jedermann; relative Gründe: nur der Inhaber des betroffenen Rechts; Hoheitszeichen: nur der Betroffene.",
                     concepts=["des_nichtigkeit"], norms=["§ 34 DesignG"]),
                step("4. Keine entgegenstehende Entscheidung", "Unzulässig, soweit über denselben Streitgegenstand zwischen den Parteien unanfechtbar durch DPMA oder rechtskräftig durch Urteil entschieden wurde (§ 34a Abs. 1 S. 4 DesignG).",
                     concepts=["des_nichtigkeitsverfahren_dpma", "des_widerklage_nichtigkeit"], norms=["§ 34a Abs. 1 DesignG", "§ 52b Abs. 2 DesignG"]),
            ]),
            step("B. Zustellung und Widerspruch (§ 34a Abs. 2 DesignG)", "Der Inhaber muss binnen eines Monats nach Zustellung widersprechen; sonst wird die Nichtigkeit ohne Sachprüfung festgestellt oder erklärt (Säumnisprinzip). Kostenentscheidung dann nur auf Antrag (§ 34a Abs. 5 DesignG).",
                 concepts=["des_nichtigkeitsverfahren_dpma"], norms=["§ 34a Abs. 2 DesignG", "§ 34a Abs. 5 DesignG"],
                 hinweis="Klausurfalle: Die Monatsfrist ist eine gesetzliche Frist; Weiterbehandlung nach § 17 DesignG gibt es hier nicht, nur Wiedereinsetzung nach § 23 Abs. 3 S. 3 DesignG i.V.m. § 123 PatG."),
            step("C. Begründetheit: Nichtigkeitsgründe (§ 33 DesignG)", children=[
                step("1. Absolute Gründe (§ 33 Abs. 1 DesignG)", "Kein Design (auch: kein einheitlicher Schutzgegenstand), fehlende Neuheit oder Eigenart, Ausschluss nach § 3 DesignG. Prüfung nach dem Schema Schutzfähigkeit.",
                     concepts=["des_nichtigkeit", "des_neuheit", "des_eigenart", "des_technisch_bedingt"], norms=["§ 33 Abs. 1 DesignG", "§ 2 DesignG", "§ 3 DesignG"], cases=["des_bgh_sporthelm", "des_bpatg_violette_trittleiter", "des_bpatg_sattelunterseite_ii"]),
                step("2. Relative Gründe (§ 33 Abs. 2 DesignG)", "Urheberrecht, älteres eingetragenes Design (auch nachveröffentlicht), Zeichen mit Unterscheidungskraft; Widerspruch des Inhabers des kollidierenden Rechts.",
                     concepts=["des_nichtigkeit"], norms=["§ 33 Abs. 2 DesignG"]),
                step("3. Teilweise Aufrechterhaltung (§ 35 DesignG)", "Änderung unter Wahrung der Identität, geänderte Wiedergabe einreichen.",
                     concepts=["des_teilweise_aufrechterhaltung"], norms=["§ 35 DesignG"]),
            ]),
            step("D. Entscheidung (§ 34a Abs. 3 bis 6 DesignG)", "Designabteilung mit drei rechtskundigen Mitgliedern (§ 23 Abs. 2 DesignG), Anhörung auf Antrag oder bei Sachdienlichkeit, Beschluss mit Begründung, Kosten nach § 62 Abs. 2, § 84 Abs. 2 S. 2 PatG entsprechend, Gegenstandswert auf Antrag.",
                 concepts=["des_nichtigkeitsverfahren_dpma", "des_beschwerde_bpatg"], norms=["§ 34a Abs. 3 DesignG", "§ 34a Abs. 4 DesignG", "§ 34a Abs. 5 DesignG", "§ 23 Abs. 2 DesignG"]),
            step("E. Beschwerde und Rechtsbeschwerde (§ 23 Abs. 4, 5 DesignG)", "Beschwerde zum BPatG (30. Senat) binnen eines Monats, Gebühr 200 EUR; Rechtsbeschwerde zum BGH bei Zulassung oder absoluten Verfahrensmängeln (§ 100 Abs. 3 PatG); rechtliches Gehör wahren.",
                 concepts=["des_beschwerde_bpatg"], norms=["§ 23 Abs. 4 DesignG", "§ 23 Abs. 5 DesignG", "§ 100 PatG"], cases=["des_bgh_heizkoerperdesign", "des_bgh_sattelunterseite_ii"]),
            step("F. Nebenverfahren", children=[
                step("1. Aussetzung des Verletzungsprozesses (§ 34b DesignG)", "Ermessen; zwingend, wenn das Gericht das Design für nichtig hält.",
                     concepts=["des_nichtigkeitsverfahren_dpma"], norms=["§ 34b DesignG"]),
                step("2. Beitritt (§ 34c DesignG)", "Wer wegen desselben Designs verklagt oder abgemahnt wurde, kann beitreten; im Beschwerdeverfahren als Beschwerdeführer.",
                     concepts=["des_nichtigkeitsverfahren_dpma"], norms=["§ 34c DesignG"]),
                step("3. Alternative: Widerklage (§ 52b DesignG) oder EUIPO-Antrag (Art. 52 GGV)", "Widerklage vor dem Designgericht im Verletzungsprozess; für Unionsgeschmacksmuster Antrag bei der Nichtigkeitsabteilung des EUIPO oder Widerklage (Art. 84 GGV).",
                     concepts=["des_widerklage_nichtigkeit", "des_ggm_eingetragen"], norms=["§ 52b DesignG", "Art. 52 GGV", "Art. 84 GGV"], cases=["des_bgh_kinderwagen_i"]),
            ]),
        ],
    ),
    dict(
        id="des_schema_anmeldung",
        label="Anmeldung und Eintragung eines Designs (§§ 11 bis 28 DesignG, DesignV)",
        kategorie="Design: Anmeldung und Eintragung (DPMA)",
        beschreibung="Vom Entwurf zum eingetragenen Design: Berechtigung, Anmeldeunterlagen und Wiedergabe, Anmeldetag, Priorität und Neuheitsschonfrist, Gebühren, Prüfung durch das DPMA, Rechtsbehelfe, Eintragung und Bekanntmachung, Aufschiebung, Schutzdauer und Aufrechterhaltung. Klausurtypisch: Fristenketten und die Frage, wann welcher Schutz besteht.",
        norms=["§ 7 DesignG", "§ 11 DesignG", "§ 12 DesignG", "§ 13 DesignG", "§ 14 DesignG", "§ 16 DesignG", "§ 17 DesignG", "§ 21 DesignG", "§ 27 DesignG", "§ 28 DesignG"],
        steps=[
            step("A. Berechtigung (§§ 7, 8 DesignG)", "Entwerfer oder Rechtsnachfolger; Arbeitnehmerdesign dem Arbeitgeber; freie Designer nur mit Übertragung. Das DPMA prüft die Berechtigung nicht; Nichtberechtigte trifft § 9 DesignG.",
                 concepts=["des_entwerfer_recht", "des_arbeitnehmerdesign", "des_vindikation"], norms=["§ 7 DesignG", "§ 8 DesignG", "§ 9 DesignG"]),
            step("B. Anmeldeunterlagen (§ 11 DesignG, §§ 3 bis 10 DesignV)", children=[
                step("1. Mindestinhalt für den Anmeldetag (§ 11 Abs. 2 DesignG)", "Eintragungsantrag, Identität des Anmelders, bekanntmachungsfähige Wiedergabe; Eingang beim DPMA oder Patentinformationszentrum (§ 13 DesignG).",
                     concepts=["des_anmeldung", "des_anmeldetag"], norms=["§ 11 Abs. 2 DesignG", "§ 13 DesignG"]),
                step("2. Wiedergabe (§ 7 DesignV)", "Bis zu zehn Darstellungen eines einheitlichen Designs, neutraler Hintergrund; sie bestimmt den Schutzgegenstand (§ 37 DesignG). Varianten gehören in die Sammelanmeldung.",
                     concepts=["des_wiedergabe", "des_schutzgegenstand"], norms=["§ 7 DesignV", "§ 37 Abs. 1 DesignG"], cases=["des_bgh_sporthelm", "des_bgh_sportbrille"]),
                step("3. Erzeugnisangabe und Zusatzangaben", "Erzeugnisangabe Pflicht (§ 11 Abs. 3 DesignG), ohne Einfluss auf den Schutzumfang; Beschreibung, Warenklassen, Entwerfer, Aufschiebungsantrag optional (§ 11 Abs. 5 DesignG).",
                     concepts=["des_erzeugnisangabe"], norms=["§ 11 Abs. 3 DesignG", "§ 11 Abs. 5 DesignG", "§ 9 DesignV", "§ 10 DesignV"]),
                step("4. Sammelanmeldung (§ 12 DesignG)", "Bis zu 100 Designs, keine Klassenbindung, Teilung jederzeit.",
                     concepts=["des_sammelanmeldung"], norms=["§ 12 DesignG"]),
            ]),
            step("C. Zeitrang: Priorität und Neuheitsschonfrist", children=[
                step("1. Ausländische und Ausstellungspriorität (§§ 14, 15 DesignG)", "Sechs Monate; Angaben und Nachweis binnen 16 Monaten; Prioritätstag ersetzt den Anmeldetag (§ 13 Abs. 2 DesignG).",
                     concepts=["des_prioritaet"], norms=["§ 14 DesignG", "§ 15 DesignG", "§ 13 Abs. 2 DesignG"]),
                step("2. Neuheitsschonfrist (§ 6 DesignG)", "Eigene Offenbarungen in den zwölf Monaten vor dem Anmeldetag sind unschädlich; danach nur noch das nicht eingetragene Unionsgeschmacksmuster.",
                     concepts=["des_neuheitsschonfrist", "des_ggm_nicht_eingetragen"], norms=["§ 6 DesignG", "Art. 11 GGV"]),
            ]),
            step("D. Gebühren (PatKostG)", "Anmeldung 60 EUR elektronisch, 70 EUR Papier; Sammelanmeldung 60 EUR für 2 bis 10, je weiteres 6 EUR; Aufschiebung 30 EUR; fällig mit Einreichung, Zahlungsfrist drei Monate (§ 6 PatKostG), sonst Rücknahmefiktion; bei Teilzahlung der Sammelanmeldung bestimmt der Anmelder, sonst das DPMA, welche Designs gedeckt sind (§ 16 Abs. 2 DesignG).",
                 concepts=["des_anmeldung", "des_sammelanmeldung"], norms=["§ 16 Abs. 1 DesignG", "§ 16 Abs. 2 DesignG", "§ 6 PatKostG", "§ 3 PatKostG"]),
            step("E. Prüfung und Rechtsbehelfe", children=[
                step("1. Prüfungsumfang (§§ 16, 18 DesignG)", "Formalien, Anmeldetagserfordernisse, Eintragungshindernisse (kein Design, Sittenverstoß, Hoheitszeichen); keine Prüfung von Neuheit und Eigenart.",
                     concepts=["des_pruefung_dpma", "des_ordre_public"], norms=["§ 16 DesignG", "§ 18 DesignG"]),
                step("2. Mängelrüge, Zurückweisung, Weiterbehandlung (§ 16 Abs. 3, § 17 DesignG)", "Frist zur Mängelbeseitigung; nach Zurückweisung wegen Fristversäumung Weiterbehandlung binnen eines Monats mit Nachholung und 100 EUR; sonst Beschwerde (§ 23 Abs. 4 DesignG).",
                     concepts=["des_weiterbehandlung", "des_beschwerde_bpatg"], norms=["§ 16 Abs. 3 DesignG", "§ 17 DesignG", "§ 23 Abs. 4 DesignG"]),
            ]),
            step("F. Eintragung, Bekanntmachung, Aufschiebung (§§ 19 bis 21 DesignG)", "Eintragung ohne Berechtigungsprüfung, Bekanntmachung mit Wiedergabe; auf Antrag Aufschiebung um 30 Monate mit bloßem Nachahmungsschutz und Erstreckungsgebühr (40 EUR) innerhalb der Frist.",
                 concepts=["des_pruefung_dpma", "des_aufschiebung"], norms=["§ 19 DesignG", "§ 20 DesignG", "§ 21 DesignG", "§ 38 Abs. 3 DesignG"]),
            step("G. Schutzbeginn, Schutzdauer, Aufrechterhaltung (§§ 27, 28 DesignG)", "Schutz ab Eintragung, 25 Jahre ab Anmeldetag, Aufrechterhaltungsgebühren je Fünfjahresabschnitt (90/120/150/180 EUR) mit Zuschlagsfrist; ohne Zahlung Löschung (§ 36 DesignG).",
                 concepts=["des_schutzdauer"], norms=["§ 27 DesignG", "§ 28 DesignG", "§ 36 DesignG", "§ 7 PatKostG"]),
            step("H. Alternativen: Unionsgeschmacksmuster und Haager Abkommen", "Anmeldung beim EUIPO (Art. 35 Abs. 1 GGV; die Weiterleitung über das DPMA nach § 62 DesignG ist seit 1.5.2025 entfallen) für unionsweiten Schutz; internationale Eintragung nach dem Haager Abkommen (§§ 66 ff. DesignG) mit Benennung Deutschlands oder der EU.",
                 concepts=["des_ggm_eingetragen", "des_haager_abkommen"], norms=["Art. 35 GGV", "§ 62 DesignG", "§ 67 DesignG", "§ 71 DesignG"]),
        ],
    ),
    dict(
        id="des_schema_unionsgeschmacksmuster",
        label="Anspruch aus einem Unionsgeschmacksmuster (GGV, § 62a DesignG)",
        kategorie="Design: Unionsgeschmacksmuster und internationales Design",
        beschreibung="Prüfung einer Verletzungsklage aus einem eingetragenen oder nicht eingetragenen Unionsgeschmacksmuster vor einem deutschen Unionsgeschmacksmustergericht: Schutzentstehung, Inhaberschaft, Verletzung (beim nicht eingetragenen Muster Nachahmung), Zuständigkeit und Reichweite, anwendbares Recht und Rechtsfolgen mit Doppelzitat aus GGV und DesignG.",
        norms=["Art. 1 GGV", "Art. 11 GGV", "Art. 19 GGV", "Art. 80 GGV", "Art. 82 GGV", "Art. 88 GGV", "Art. 89 GGV", "§ 62a DesignG", "§ 63 DesignG"],
        steps=[
            step("A. Schutzrecht", children=[
                step("1. Eingetragenes Unionsgeschmacksmuster (Art. 1 Abs. 2 lit. b, 12 GGV)", "Eintragung beim EUIPO, fünf Jahre ab Anmeldung, verlängerbar bis 25; Vermutung der Rechtsgültigkeit (Art. 85 Abs. 1 GGV), Nichtigkeit nur durch Widerklage oder EUIPO-Antrag.",
                     concepts=["des_ggm_eingetragen", "des_vermutung_rechtsgueltigkeit"], norms=["Art. 1 GGV", "Art. 12 GGV", "Art. 85 GGV"]),
                step("2. Nicht eingetragenes Unionsgeschmacksmuster (Art. 11 GGV)", "Erste Offenbarung in der Union, drei Jahre; Kläger legt Offenbarung, Zeitpunkt und Merkmale der Eigenart dar (Art. 85 Abs. 2 GGV); Einrede der Nichtigkeit zulässig.",
                     concepts=["des_ggm_nicht_eingetragen", "des_offenbarung"], norms=["Art. 11 GGV", "Art. 85 GGV", "Art. 7 GGV"], cases=["des_eugh_karen_millen", "des_eugh_gautzsch", "des_eugh_ferrari"]),
            ]),
            step("B. Inhaberschaft und Aktivlegitimation (Art. 14, 32 GGV)", "Entwerfer, Rechtsnachfolger oder Arbeitgeber; beim nicht eingetragenen Muster volle Beweislast des Klägers; Lizenznehmer nach Art. 32 Abs. 3 GGV.",
                 concepts=["des_entwerfer_recht", "des_lizenz"], norms=["Art. 14 GGV", "Art. 32 GGV"], cases=["des_bgh_bolerojaeckchen"]),
            step("C. Verletzung (Art. 10, 19 GGV)", children=[
                step("1. Benutzungshandlung in der Union (Art. 19 Abs. 1, 2 GGV)", "Herstellen, Anbieten, Inverkehrbringen, Ein- und Ausfuhr, Benutzen, Besitz; seit 2024 auch 3D-Druck-Dateien (Art. 19 Abs. 2 lit. d GGV) und Durchfuhr (Art. 19 Abs. 3 GGV).",
                     concepts=["des_benutzung"], norms=["Art. 19 GGV"], cases=["des_bgh_kinderwagen_i"]),
                step("2. Schutzumfang: kein anderer Gesamteindruck (Art. 10 GGV)", "Wie § 38 Abs. 2 DesignG: Formenschatz, Gestaltungsfreiheit, informierter Benutzer.",
                     concepts=["des_schutzumfang", "des_gesamteindruck"], norms=["Art. 10 GGV"], cases=["des_bgh_untersetzer", "des_eugh_pepsico"]),
                step("3. Beim nicht eingetragenen Muster: Nachahmung (Art. 19 Abs. 4 GGV)", "Der Verletzer muss das Muster gekannt haben; Vermutung, wenn er es vernünftigerweise kennen konnte; unabhängige Parallelschöpfung ist frei.",
                     concepts=["des_ggm_nicht_eingetragen"], norms=["Art. 19 GGV"], cases=["des_eugh_gautzsch"]),
                step("4. Schranken und Reparaturklausel (Art. 20 bis 22, 20a GGV)", "Privat, Versuche, Zitat, Referenz, Parodie; Erschöpfung; Vorbenutzung; Reparaturklausel mit Sorgfaltspflichten.",
                     concepts=["des_schranken", "des_reparaturklausel"], norms=["Art. 20 GGV", "Art. 20a GGV", "Art. 21 GGV", "Art. 22 GGV"], cases=["des_eugh_nintendo", "des_eugh_acacia_audi"]),
            ]),
            step("D. Zuständigkeit (Art. 80 bis 83 GGV, § 63 DesignG)", "Unionsgeschmacksmustergericht (Landgericht); international: Sitz des Beklagten, hilfsweise Kläger, hilfsweise Spanien, alternativ Verletzungsort; unionsweite Reichweite nur im Sitzgerichtsstand; Streitgenossenschaft nach Brüssel-Ia.",
                 concepts=["des_ggm_gericht"], norms=["Art. 80 GGV", "Art. 81 GGV", "Art. 82 GGV", "Art. 83 GGV", "§ 63 DesignG"], cases=["des_eugh_nintendo"]),
            step("E. Anwendbares Recht und Rechtsfolgen (Art. 88, 89 GGV, § 62a DesignG)", children=[
                step("1. Unterlassung aus der Verordnung (Art. 89 Abs. 1 GGV)", "Unmittelbar aus der GGV, unionsweit im Sitzgerichtsstand; Zwangsmittel nach nationalem Recht (Art. 89 Abs. 1 S. 2 GGV). Beschlagnahme und Vernichtung standen bis 30.4.2025 in Art. 89 Abs. 1 lit. b, c GGV a.F.; heute folgen sie nach Art. 89 Abs. 2 GGV aus dem anwendbaren Recht.",
                     concepts=["des_ggm_anwendbares_recht", "des_unterlassung"], norms=["Art. 89 GGV"]),
                step("2. Folgeansprüche nach dem Recht des Verletzungsstaats (Art. 88 Abs. 2, 89 Abs. 2 GGV)", "Art. 8 Abs. 2 Rom-II-VO: Recht des Staates der Verletzungshandlung; in Deutschland § 62a DesignG mit § 42 Abs. 2, §§ 43, 46, 46a, 46b, 47, 49 DesignG (Schadensersatz, Rückruf, Auskunft, Vorlage, Sicherung, Bekanntmachung, Verjährung).",
                     concepts=["des_ggm_anwendbares_recht", "des_schadensersatz", "des_anspruchsgrundlagen_eu"], norms=["Art. 88 GGV", "§ 62a DesignG", "§ 42 Abs. 2 DesignG", "§ 46 DesignG"], cases=["des_eugh_acacia_bmw", "des_eugh_nintendo"],
                     hinweis="Zitierweise in der Klausur: „Art. 89 Abs. 2, Art. 88 Abs. 2 GGV i.V.m. § 62a, § 42 Abs. 2 DesignG“."),
                step("3. Einstweilige Maßnahmen (Art. 90 GGV)", "Vor jedem Gericht eines Mitgliedstaats; unionsweite Wirkung nur beim nach Art. 82 Abs. 1 bis 4 GGV zuständigen Gericht; Verfahren nach §§ 935 ff. ZPO.",
                     concepts=["des_ggm_gericht"], norms=["Art. 90 GGV"]),
            ]),
        ],
    ),
]
