# -*- coding: utf-8 -*-
"""Leitentscheidungen (BGH, ergänzend EuGH) zum Markenrecht.

Recherchiert per Websuche (dejure.org, bundesgerichtshof.de, juris, Fachblogs, IPWiki).
Felder:
  id         eindeutige Kennung
  name       Entscheidungsname (BGH-Schlagwort)
  court      BGH / EuGH
  date       Entscheidungsdatum (ISO)
  az         Aktenzeichen
  fundstelle Fundstelle (soweit bekannt)
  norms      betroffene Normen
  concepts   Begriffs-IDs (siehe concepts.py)
  kern       Kernaussage / Leitsatz in eigenen Worten (für Karteikarten)
  tags       Themen
"""

CASES = [
    # ------------------------------------------------------------------
    # Markenfähigkeit / Formmarken / § 3
    # ------------------------------------------------------------------
    dict(id="bgh_rocher_kugel", name="ROCHER-Kugel", court="BGH", date="2009-07-09", az="I ZB 88/07",
         fundstelle="GRUR 2010, 138", norms=["§ 3", "§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 3"],
         concepts=["formmarke", "verkehrsdurchsetzung", "unterscheidungskraft"],
         kern="Eine dreidimensionale Warenformmarke (Ferrero-Rocher-Praline) besitzt nur dann originäre Unterscheidungskraft, wenn sie erheblich von der Norm oder Branchenüblichkeit abweicht. Für die Verkehrsdurchsetzung nach § 8 Abs. 3 MarkenG ist im Regelfall ein Zuordnungsgrad von mindestens 50 % erforderlich.",
         tags=["Formmarke", "Verkehrsdurchsetzung"]),
    dict(id="bgh_ritter_sport", name="Quadratische Tafelschokoladenverpackung II", court="BGH", date="2020-07-23", az="I ZB 42/19",
         fundstelle="GRUR 2020, 1089", norms=["§ 3 Abs. 2 Nr. 1", "§ 3 Abs. 2 Nr. 3", "§ 50"],
         concepts=["formausschluss", "formmarke", "nichtigkeit"],
         kern="Die quadratische Ritter-Sport-Verpackung bleibt als Formmarke geschützt. Das Schutzhindernis der wertverleihenden Form (§ 3 Abs. 2 Nr. 3 MarkenG) greift nicht, wenn die Kaufentscheidung nicht durch die ästhetische Qualität der Form, sondern durch andere Merkmale (hier: Herkunftshinweis, Praktikabilität) bestimmt wird. Die Form ist auch nicht durch die Art der Ware selbst bedingt (§ 3 Abs. 2 Nr. 1).",
         tags=["Formmarke", "§ 3 Abs. 2"]),
    dict(id="bgh_bodenduebel", name="Bodendübel", court="BGH", date="2017-10-18", az="I ZB 105/16",
         fundstelle="GRUR 2018, 404", norms=["§ 3 Abs. 2 Nr. 2"],
         concepts=["formausschluss", "formmarke"],
         kern="Ein Zeichen ist von der Eintragung ausgeschlossen, wenn alle wesentlichen Merkmale der Form zur Erreichung einer technischen Wirkung erforderlich sind. Es genügt, dass die Merkmale eine technische Funktion erfüllen; sie müssen nicht die einzige Möglichkeit sein, diese Funktion zu erreichen (Anschluss an EuGH Philips/Remington und Lego).",
         tags=["Formmarke", "technische Wirkung"]),
    dict(id="bgh_traubenzucker", name="Traubenzuckertäfelchen", court="BGH", date="2017-10-18", az="I ZB 3/17",
         fundstelle="GRUR 2018, 411", norms=["§ 3 Abs. 2 Nr. 2", "§ 8 Abs. 2 Nr. 1"],
         concepts=["formausschluss", "formmarke"],
         kern="Eine technische Wirkung i.S.d. § 3 Abs. 2 Nr. 2 MarkenG kann auch durch formgebende Merkmale eines Zeichens erreicht werden, das für nichttechnische Produkte wie Lebensmittel (Dextro-Energy-Täfelchen) beansprucht wird.",
         tags=["Formmarke"]),
    dict(id="eugh_philips_remington", name="Philips/Remington", court="EuGH", date="2002-06-18", az="C-299/99",
         fundstelle="GRUR 2002, 804", norms=["§ 3 Abs. 2 Nr. 2"],
         concepts=["formausschluss"],
         kern="Ein Zeichen, das ausschließlich aus der Form einer Ware besteht, ist nicht eintragungsfähig, wenn die wesentlichen funktionellen Merkmale nur der technischen Wirkung zuzuschreiben sind. Der Ausschluss kann nicht durch den Nachweis überwunden werden, dass es andere Formen gibt, mit denen dieselbe Wirkung erzielt werden kann; auch nicht durch Verkehrsdurchsetzung.",
         tags=["Formmarke", "technische Wirkung"]),
    dict(id="eugh_libertel", name="Libertel", court="EuGH", date="2003-05-06", az="C-104/01",
         fundstelle="GRUR 2003, 604", norms=["§ 3 Abs. 1", "§ 8 Abs. 1", "§ 8 Abs. 2 Nr. 1"],
         concepts=["farbmarke", "markenfaehigkeit", "unterscheidungskraft"],
         kern="Eine abstrakte Farbe ohne räumliche Begrenzung kann markenfähig sein, wenn sie durch einen international anerkannten Farbcode eindeutig bestimmt ist. Originäre Unterscheidungskraft kommt einer Farbe nur unter außergewöhnlichen Umständen zu; regelmäßig ist Verkehrsdurchsetzung nötig. Das Allgemeininteresse an der Verfügbarkeit von Farben ist zu berücksichtigen.",
         tags=["Farbmarke"]),

    # ------------------------------------------------------------------
    # Unterscheidungskraft § 8 Abs. 2 Nr. 1
    # ------------------------------------------------------------------
    dict(id="bgh_hot", name="HOT", court="BGH", date="2014-02-19", az="I ZB 3/13",
         fundstelle="GRUR 2014, 569", norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 2 Nr. 2"],
         concepts=["unterscheidungskraft", "freihaltebeduerfnis"],
         kern="Ein Zeichen mit mehreren Bedeutungen ('HOT' = heiß/scharf/angesagt) fehlt die Unterscheidungskraft, wenn es in einer seiner möglichen Bedeutungen ein Merkmal der Waren beschreibt. Die Mehrdeutigkeit begründet keine Unterscheidungskraft. Zugleich: Freihaltebedürfnis für Waren, bei denen 'hot' die Beschaffenheit beschreibt.",
         tags=["Unterscheidungskraft", "Mehrdeutigkeit"]),
    dict(id="bgh_link_economy", name="Link economy", court="BGH", date="2011-12-21", az="I ZB 56/09",
         fundstelle="GRUR 2012, 270", norms=["§ 8 Abs. 2 Nr. 1"],
         concepts=["unterscheidungskraft"],
         kern="Unterscheidungskraft fehlt einer Wortfolge, die sich in einer beschreibenden Sachaussage erschöpft; der Verkehr darf aber nicht zu einer analysierenden Betrachtung angehalten werden. Eine Wortneubildung mit unklarem Begriffsinhalt kann unterscheidungskräftig sein. Großzügiger Maßstab: jede noch so geringe Unterscheidungskraft genügt.",
         tags=["Unterscheidungskraft", "Wortfolgen"]),
    dict(id="bgh_marlene_dietrich_ii", name="Marlene-Dietrich-Bildnis II", court="BGH", date="2010-03-31", az="I ZB 62/09",
         fundstelle="GRUR 2010, 825", norms=["§ 8 Abs. 2 Nr. 1"],
         concepts=["unterscheidungskraft", "verwendungsformen"],
         kern="Für die Unterscheidungskraft genügt es, wenn es praktisch bedeutsame und naheliegende Möglichkeiten gibt, das Zeichen bei den beanspruchten Waren so zu verwenden, dass der Verkehr es ohne weiteres als Marke versteht (z.B. auf dem Etikett statt als Dekor). Zeichen, die sonst als Werbemittel eingesetzt werden, kann die Eintragung nicht allein deshalb versagt werden.",
         tags=["Unterscheidungskraft", "Verwendungsformen"]),
    dict(id="bgh_darferdas_ii", name="#darferdas? II", court="BGH", date="2020-01-30", az="I ZB 61/17",
         fundstelle="GRUR 2020, 411", norms=["§ 8 Abs. 2 Nr. 1"],
         concepts=["unterscheidungskraft", "verwendungsformen"],
         kern="Im Anschluss an EuGH C-541/18: Bei der Prüfung der Unterscheidungskraft sind alle wahrscheinlichen, praktisch bedeutsamen Verwendungsarten in der Branche zu berücksichtigen (bei Bekleidung: Aufdruck UND Einnähetikett). Nur wenn eine einzige Verwendungsart praktisch bedeutsam ist, darf die Prüfung darauf beschränkt werden. Die BGH-Rechtsprechung 'Marlene-Dietrich-Bildnis II' wurde damit modifiziert.",
         tags=["Unterscheidungskraft", "Verwendungsformen", "Hashtag"]),
    dict(id="eugh_darferdas", name="AS/DPMA (#darferdas?)", court="EuGH", date="2019-09-12", az="C-541/18",
         fundstelle="GRUR 2019, 1194", norms=["§ 8 Abs. 2 Nr. 1"],
         concepts=["unterscheidungskraft", "verwendungsformen"],
         kern="Die Unterscheidungskraft eines Zeichens ist unter Berücksichtigung aller relevanten Tatsachen und Umstände, einschließlich sämtlicher wahrscheinlicher Verwendungsarten der angemeldeten Marke, zu prüfen. Praktisch nicht bedeutsame Verwendungsarten bleiben außer Betracht.",
         tags=["Unterscheidungskraft"]),
    dict(id="bgh_pippi_langstrumpf", name="Pippi-Langstrumpf-Marke", court="BGH", date="2017-10-05", az="I ZB 97/16",
         fundstelle="GRUR 2018, 301", norms=["§ 8 Abs. 2 Nr. 1", "§ 50"],
         concepts=["unterscheidungskraft"],
         kern="Der Name einer fiktiven Romanfigur ('Pippi Langstrumpf') ist für Beherbergungsdienstleistungen unterscheidungskräftig. Eine 'sprechende' Marke, die neben der Herkunft auch Assoziationen zur Dienstleistung weckt, ist nur dann nicht unterscheidungskräftig, wenn ein enger beschreibender Bezug besteht.",
         tags=["Unterscheidungskraft", "Personenname"]),
    dict(id="bgh_for_you", name="for you", court="BGH", date="2014-07-10", az="I ZB 18/13",
         fundstelle="GRUR 2014, 872", norms=["§ 8 Abs. 2 Nr. 1"],
         concepts=["unterscheidungskraft"],
         kern="Die Wortfolge 'for you' ist für Nahrungsergänzungsmittel und Kosmetik nicht unterscheidungskräftig: Der Verkehr versteht sie nur als werbliche Anpreisung ('für dich'), nicht als Herkunftshinweis. Maßgeblich ist die Sicht des Durchschnittsverbrauchers im Anmeldezeitpunkt.",
         tags=["Unterscheidungskraft", "Werbeslogan"]),
    dict(id="bgh_oui", name="OUI", court="BGH", date="2016-05-31", az="I ZB 39/15",
         fundstelle="GRUR 2016, 934", norms=["§ 8 Abs. 2 Nr. 1"],
         concepts=["unterscheidungskraft"],
         kern="'OUI' ist für Bekleidung eintragungsfähig. Ein fremdsprachiges Wort ohne beschreibenden Bezug zu den Waren ist unterscheidungskräftig; allgemeine Zustimmungsbekundungen ('ja') werden nicht ohne weiteres als bloße Werbeaussage verstanden.",
         tags=["Unterscheidungskraft"]),
    dict(id="bgh_duesseldorfcongress", name="DüsseldorfCongress", court="BGH", date="2014-05-15", az="I ZB 29/13",
         fundstelle="GRUR 2014, 1204", norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 2 Nr. 2"],
         concepts=["unterscheidungskraft", "freihaltebeduerfnis"],
         kern="Die Kombination einer Ortsangabe mit einer beschreibenden Gattungsbezeichnung ('DüsseldorfCongress') fehlt für Veranstaltungsdienstleistungen die Unterscheidungskraft; die Zusammenschreibung ändert den beschreibenden Charakter nicht.",
         tags=["Unterscheidungskraft", "geographische Angabe"]),
    dict(id="bgh_die_vision", name="Die Vision", court="BGH", date="2010-07-01", az="I ZB 35/09",
         fundstelle="GRUR 2010, 935", norms=["§ 8 Abs. 2 Nr. 1"],
         concepts=["unterscheidungskraft"],
         kern="Für Druckereierzeugnisse und Verlagsdienstleistungen fehlt 'Die Vision' die Unterscheidungskraft, weil der Verkehr die Angabe als Hinweis auf den thematischen Inhalt versteht. Der Umstand, dass der Verkehr an beschreibende Zeitschriftentitel gewöhnt ist, betrifft den Werktitelschutz (§ 5 Abs. 3), nicht die markenrechtliche Unterscheidungskraft.",
         tags=["Unterscheidungskraft", "Zeitschriftentitel"]),
    dict(id="bgh_marktfrisch", name="marktfrisch", court="BGH", date="2001-03-01", az="I ZB 42/98",
         fundstelle="GRUR 2001, 1151", norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 2 Nr. 2"],
         concepts=["unterscheidungskraft", "freihaltebeduerfnis"],
         kern="'marktfrisch' ist für Lebensmittel eine beschreibende Angabe (Beschaffenheit) und daher weder unterscheidungskräftig noch vom Freihaltebedürfnis ausgenommen. Grundsatz: Unterscheidungskraft fehlt bei Wörtern mit für die Ware im Vordergrund stehendem beschreibenden Begriffsinhalt.",
         tags=["Unterscheidungskraft"]),

    # ------------------------------------------------------------------
    # Freihaltebedürfnis / Verkehrsdurchsetzung
    # ------------------------------------------------------------------
    dict(id="bgh_black_friday", name="Black Friday", court="BGH", date="2021-05-27", az="I ZB 21/20",
         fundstelle="GRUR 2021, 1195", norms=["§ 8 Abs. 2 Nr. 2", "§ 50"],
         concepts=["freihaltebeduerfnis", "nichtigkeit"],
         kern="Ein Freihaltebedürfnis nach § 8 Abs. 2 Nr. 2 MarkenG setzt nicht voraus, dass das Zeichen im Anmeldezeitpunkt bereits beschreibend verwendet wird; es genügt, dass eine beschreibende Verwendung vernünftigerweise für die Zukunft zu erwarten ist. 'Black Friday' wurde für Elektronikwaren und Werbedienstleistungen teilweise gelöscht.",
         tags=["Freihaltebedürfnis", "Löschung"]),
    dict(id="eugh_chiemsee", name="Windsurfing Chiemsee", court="EuGH", date="1999-05-04", az="C-108/97",
         fundstelle="GRUR 1999, 723", norms=["§ 8 Abs. 2 Nr. 2", "§ 8 Abs. 3"],
         concepts=["freihaltebeduerfnis", "verkehrsdurchsetzung"],
         kern="Geographische Herkunftsangaben sind freizuhalten, wenn sie gegenwärtig oder vernünftigerweise in Zukunft mit den Waren in Verbindung gebracht werden können. Für die Verkehrsdurchsetzung gibt es keine feste Prozentzahl; maßgeblich ist, ob ein erheblicher Teil der beteiligten Verkehrskreise die Ware aufgrund der Marke einem bestimmten Unternehmen zuordnet (Gesamtbetrachtung: Marktanteil, Intensität, Dauer, Werbeaufwand, Umfragen).",
         tags=["Freihaltebedürfnis", "Verkehrsdurchsetzung"]),
    dict(id="bgh_test", name="test (Stiftung Warentest)", court="BGH", date="2013-10-17", az="I ZB 65/12",
         fundstelle="GRUR 2014, 483", norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 3", "§ 50"],
         concepts=["verkehrsdurchsetzung", "unterscheidungskraft"],
         kern="Die Wort-Bild-Marke 'test' ist für Testzeitschriften beschreibend. Für die Verkehrsdurchsetzung reicht ein Zuordnungsgrad von 43 % regelmäßig nicht aus. Maßgeblicher Zeitpunkt der Verkehrsdurchsetzung ist der Anmeldetag; im Löschungsverfahren muss sie zusätzlich im Entscheidungszeitpunkt fortbestehen.",
         tags=["Verkehrsdurchsetzung"]),
    dict(id="bgh_langenscheidt_gelb", name="Langenscheidt-Gelb", court="BGH", date="2014-10-23", az="I ZB 61/13",
         fundstelle="GRUR 2015, 581", norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 3"],
         concepts=["farbmarke", "verkehrsdurchsetzung"],
         kern="Eine abstrakte Farbmarke (Gelb für zweisprachige Wörterbücher) hat sich im Verkehr durchgesetzt, wenn über 50 % der Verkehrskreise die Farbe einem Unternehmen zuordnen. Die Verkehrsdurchsetzung setzt nicht voraus, dass die Farbe isoliert, ohne Wort- und Bildzeichen benutzt wurde.",
         tags=["Farbmarke", "Verkehrsdurchsetzung"]),
    dict(id="bgh_nivea_blau", name="Nivea-Blau", court="BGH", date="2015-07-09", az="I ZB 65/13",
         fundstelle="GRUR 2015, 1012", norms=["§ 8 Abs. 2 Nr. 1", "§ 8 Abs. 3", "§ 50"],
         concepts=["farbmarke", "verkehrsdurchsetzung"],
         kern="Für die Verkehrsdurchsetzung einer abstrakten Farbmarke genügt regelmäßig ein Zuordnungsgrad von über 50 %; ein höherer Grad (75 %) ist nicht erforderlich. Verkehrsbefragungen müssen die konkrete Farbe für die konkreten Waren abfragen; eine Verwendung zusammen mit anderen Kennzeichen steht der Durchsetzung nicht entgegen.",
         tags=["Farbmarke", "Verkehrsdurchsetzung"]),
    dict(id="bgh_gelbe_woerterbuecher", name="Gelbe Wörterbücher", court="BGH", date="2014-09-18", az="I ZR 228/12",
         fundstelle="GRUR 2015, 1101", norms=["§ 14 Abs. 2 Nr. 2", "§ 14 Abs. 5"],
         concepts=["farbmarke", "markenmaessige_benutzung", "verwechslungsgefahr", "kennzeichnungskraft"],
         kern="Verletzung der abstrakten Farbmarke Gelb (Langenscheidt) durch gelbe Verpackungen von Sprachlernsoftware: Eine markenmäßige Benutzung der Farbe setzt keine gesteigerte Kennzeichnungskraft der Farbmarke voraus; nimmt der Verkehr die Farbe als eigenständiges Zeichen (Zweitmarke) wahr, ist sie isoliert in den Zeichenvergleich einzustellen. Hohe Ähnlichkeit zwischen Wörterbüchern und Sprachlernsoftware.",
         tags=["Farbmarke", "Verletzung"]),
    dict(id="bgh_sparkassen_rot", name="Sparkassen-Rot", court="BGH", date="2016-07-21", az="I ZB 52/15",
         fundstelle="GRUR 2016, 1167", norms=["§ 8 Abs. 3", "§ 50"],
         concepts=["farbmarke", "verkehrsdurchsetzung"],
         kern="Im Löschungsverfahren trägt der Antragsteller die Feststellungslast für das Fehlen der Verkehrsdurchsetzung im Anmeldezeitpunkt; verbleibende Zweifel gehen zu seinen Lasten. Das Sparkassen-Rot blieb als Farbmarke eingetragen.",
         tags=["Farbmarke", "Verkehrsdurchsetzung", "Löschung"]),

    # ------------------------------------------------------------------
    # Bösgläubigkeit § 8 Abs. 2 Nr. 14
    # ------------------------------------------------------------------
    dict(id="bgh_glueckspilz", name="GLÜCKSPILZ", court="BGH", date="2015-10-15", az="I ZB 69/14",
         fundstelle="GRUR 2016, 380", norms=["§ 8 Abs. 2 Nr. 14", "§ 50"],
         concepts=["boesglaeubigkeit"],
         kern="Bösgläubigkeit kann sich aus dem sonstigen Verhalten des Anmelders ergeben, etwa wenn die Marke in erster Linie als Mittel des Wettbewerbskampfes (Sperrmarke) und nicht zur Förderung des eigenen Absatzes angemeldet wird. Maßgeblicher Zeitpunkt ist die Anmeldung; späteres Verhalten kann Indiz sein.",
         tags=["Bösgläubigkeit"]),
    dict(id="bgh_eros", name="EROS", court="BGH", date="2008-06-26", az="I ZR 190/05",
         fundstelle="GRUR 2008, 917", norms=["§ 8 Abs. 2 Nr. 14", "§ 50", "§ 51"],
         concepts=["boesglaeubigkeit"],
         kern="Bösgläubig handelt, wer ein Zeichen in Kenntnis eines schutzwürdigen Besitzstands eines Vorbenutzers ohne hinreichenden sachlichen Grund für gleiche Waren anmeldet, um den Besitzstand zu stören oder die Benutzung zu sperren. Die Sperrabsicht muss nicht der einzige Beweggrund sein.",
         tags=["Bösgläubigkeit"]),
    dict(id="bgh_ivadal", name="Ivadal", court="BGH", date="2009-04-02", az="I ZB 8/06",
         fundstelle="GRUR 2009, 780", norms=["§ 8 Abs. 2 Nr. 14"],
         concepts=["boesglaeubigkeit"],
         kern="Die Anmeldung einer Marke, die ein Dritter (hier: ausländischer Vorbenutzer) benutzt, ist nicht schon deshalb bösgläubig, weil der Anmelder von der Vorbenutzung weiß; hinzukommen müssen besondere Umstände, etwa Behinderungsabsicht ohne eigenen Benutzungswillen.",
         tags=["Bösgläubigkeit"]),

    # ------------------------------------------------------------------
    # Markenmäßige / rechtsverletzende Benutzung, Funktionen
    # ------------------------------------------------------------------
    dict(id="eugh_arsenal", name="Arsenal Football Club", court="EuGH", date="2002-11-12", az="C-206/01",
         fundstelle="GRUR 2003, 55", norms=["§ 14 Abs. 2 Nr. 1"],
         concepts=["markenmaessige_benutzung", "herkunftsfunktion", "doppelidentitaet"],
         kern="Der Markeninhaber kann eine Benutzung verbieten, die die Funktionen der Marke, insbesondere die Herkunftsfunktion, beeinträchtigt oder beeinträchtigen kann. Auch die Verwendung als 'Fanartikel' (Zeichen der Verbundenheit) kann rechtsverletzend sein, wenn der Eindruck einer Verbindung zum Markeninhaber entsteht.",
         tags=["Markenmäßige Benutzung", "Funktionenlehre"]),
    dict(id="eugh_loreal_bellure", name="L'Oréal/Bellure", court="EuGH", date="2009-06-18", az="C-487/07",
         fundstelle="GRUR 2009, 756", norms=["§ 14 Abs. 2 Nr. 1", "§ 14 Abs. 2 Nr. 3"],
         concepts=["markenfunktionen", "ausnutzung_wertschaetzung", "doppelidentitaet"],
         kern="Geschützt sind neben der Herkunftsfunktion auch Qualitäts-, Kommunikations-, Investitions- und Werbefunktion. Bei Doppelidentität genügt die Beeinträchtigung einer dieser Funktionen. Unlautere Ausnutzung der Wertschätzung (Duftvergleichslisten) liegt vor, wenn sich der Dritte in den Bereich der Sogwirkung der bekannten Marke begibt, um von ihrer Anziehungskraft ohne eigene Anstrengung zu profitieren.",
         tags=["Funktionenlehre", "Bekanntheitsschutz"]),
    dict(id="bgh_opel_blitz_ii", name="Opel-Blitz II", court="BGH", date="2010-01-14", az="I ZR 88/08",
         fundstelle="GRUR 2010, 726", norms=["§ 14 Abs. 2 Nr. 1", "§ 14 Abs. 2 Nr. 3"],
         concepts=["markenmaessige_benutzung", "herkunftsfunktion"],
         kern="Die Anbringung des Opel-Blitzes auf Spielzeugmodellautos verletzt die für Spielzeug eingetragene Marke nicht: Der Verkehr sieht darin nur die originalgetreue Nachbildung des Vorbilds, keinen Hinweis auf die Herkunft des Spielzeugs. Die Herkunftsfunktion wird nicht beeinträchtigt (Umsetzung von EuGH C-48/05 Adam Opel).",
         tags=["Markenmäßige Benutzung"]),
    dict(id="bgh_sam", name="SAM", court="BGH", date="2019-03-07", az="I ZR 195/17",
         fundstelle="GRUR 2019, 522", norms=["§ 14 Abs. 2 Nr. 1"],
         concepts=["markenmaessige_benutzung", "doppelidentitaet"],
         kern="Ob eine Modellbezeichnung (Vorname 'Sam' für Hosen) markenmäßig benutzt wird, hängt von den Kennzeichnungsgewohnheiten der Branche und der konkreten Präsentation ab. Bei Anbringung auf der Ware oder dem Etikett liegt regelmäßig ein Herkunftshinweis vor; bei einer unauffälligen Nennung nur im Bestelltext eines Online-Angebots dagegen nicht ohne weiteres.",
         tags=["Markenmäßige Benutzung", "Modellbezeichnung"]),
    dict(id="bgh_damen_hose_mo", name="Damen Hose MO", court="BGH", date="2019-04-11", az="I ZR 108/18",
         fundstelle="GRUR 2019, 1289", norms=["§ 14 Abs. 2 Nr. 1", "§ 14 Abs. 2 Nr. 2"],
         concepts=["markenmaessige_benutzung"],
         kern="Die Verwendung von 'MO' in der Angebotsüberschrift 'Bench Damen Hose MO' kann als Herkunftshinweis (Zweitmarke) verstanden werden. Die Beurteilung erfolgt anhand der Kennzeichnungsgewohnheiten der Branche und der Gestaltung des konkreten Angebots; ein bekannter Herstellername schließt eine markenmäßige Benutzung der Modellbezeichnung nicht aus.",
         tags=["Markenmäßige Benutzung", "Modellbezeichnung"]),
    dict(id="bgh_fruehstuecks_drink_ii", name="FRÜHSTÜCKS-DRINK II", court="BGH", date="2001-12-20", az="I ZR 135/99",
         fundstelle="GRUR 2002, 812", norms=["§ 14 Abs. 2 Nr. 2"],
         concepts=["markenmaessige_benutzung"],
         kern="Eine Markenverletzung setzt eine markenmäßige Benutzung voraus, d.h. das Zeichen muss im Rahmen des Produktabsatzes jedenfalls auch der Unterscheidung der Waren eines Unternehmens von denen anderer dienen. Rein beschreibende Verwendung ('Frühstücks-Drink' als Produktbeschreibung) genügt nicht.",
         tags=["Markenmäßige Benutzung"]),
    dict(id="eugh_celine", name="Céline", court="EuGH", date="2007-09-11", az="C-17/06",
         fundstelle="GRUR 2007, 971", norms=["§ 14 Abs. 2", "§ 23"],
         concepts=["markenmaessige_benutzung", "firmenmaessiger_gebrauch"],
         kern="Die bloße Benutzung einer Firma oder Geschäftsbezeichnung ist keine Benutzung 'für Waren oder Dienstleistungen'. Anders, wenn das Zeichen so benutzt wird, dass eine Verbindung zwischen der Firma und den vertriebenen Waren hergestellt wird und dadurch die Herkunftsfunktion beeinträchtigt werden kann.",
         tags=["Firmenmäßiger Gebrauch"]),
    dict(id="eugh_google_france", name="Google France und Google", court="EuGH", date="2010-03-23", az="C-236/08 bis C-238/08",
         fundstelle="GRUR 2010, 445", norms=["§ 14 Abs. 2 Nr. 1"],
         concepts=["keyword_advertising", "herkunftsfunktion"],
         kern="Die Buchung einer fremden Marke als AdWords-Keyword ist eine Benutzung im geschäftlichen Verkehr. Die Herkunftsfunktion wird beeinträchtigt, wenn aus der Anzeige für einen normal informierten Internetnutzer nicht oder nur schwer zu erkennen ist, ob die beworbenen Waren vom Markeninhaber, einem verbundenen Unternehmen oder einem Dritten stammen. Google selbst benutzt die Marke nicht.",
         tags=["Keyword-Advertising"]),
    dict(id="bgh_bananabay_ii", name="Bananabay II", court="BGH", date="2011-01-13", az="I ZR 125/07",
         fundstelle="GRUR 2011, 828", norms=["§ 14 Abs. 2 Nr. 1"],
         concepts=["keyword_advertising"],
         kern="Keyword-Advertising mit einer fremden Marke verletzt die Herkunftsfunktion regelmäßig nicht, wenn die Anzeige in einem deutlich abgesetzten, als 'Anzeigen' gekennzeichneten Werbeblock erscheint, die Marke in der Anzeige selbst nicht enthalten ist und die Domain des Werbenden auf ein anderes Unternehmen hinweist.",
         tags=["Keyword-Advertising"]),
    dict(id="bgh_most_pralinen", name="MOST-Pralinen", court="BGH", date="2012-12-13", az="I ZR 217/10",
         fundstelle="GRUR 2013, 290", norms=["§ 14 Abs. 2 Nr. 1", "§ 14 Abs. 2 Nr. 2"],
         concepts=["keyword_advertising"],
         kern="Bestätigung und Präzisierung von Bananabay II: Auch wenn die Anzeige nicht ausdrücklich darauf hinweist, dass keine Verbindung zum Markeninhaber besteht, fehlt die Beeinträchtigung der Herkunftsfunktion, sofern die Anzeige klar abgesetzt ist und keine Angaben zu einer wirtschaftlichen Verbindung enthält. Anders, wenn die Anzeige eine Verbindung nahelegt.",
         tags=["Keyword-Advertising"]),
    dict(id="bgh_fleurop", name="Fleurop", court="BGH", date="2013-06-27", az="I ZR 53/12",
         fundstelle="GRUR 2014, 182", norms=["§ 14 Abs. 2 Nr. 1"],
         concepts=["keyword_advertising"],
         kern="Ausnahme zur Bananabay-Rechtsprechung: Weiß der Verkehr, dass der Markeninhaber (Fleurop) sein Geschäft über ein Netz von Partnerfloristen betreibt, liegt bei einer Anzeige auf das Keyword 'Fleurop' die Vermutung einer wirtschaftlichen Verbindung nahe; die Herkunftsfunktion ist beeinträchtigt, wenn die Anzeige nicht klarstellt, dass keine solche Verbindung besteht.",
         tags=["Keyword-Advertising"]),
    dict(id="bgh_ortlieb_ii", name="ORTLIEB II", court="BGH", date="2019-07-25", az="I ZR 29/18",
         fundstelle="GRUR 2019, 1053", norms=["§ 14 Abs. 2 Nr. 1", "§ 14 Abs. 5"],
         concepts=["keyword_advertising", "markenmaessige_benutzung"],
         kern="Amazon-Anzeigen mit der Marke 'ORTLIEB', die auf Angebotslisten verlinken, in denen auch Produkte anderer Hersteller erscheinen, sind irreführend und verletzen die Marke: Der Verkehr erwartet aufgrund der Anzeige ausschließlich Produkte des Markeninhabers. Die Werbewirkung der Marke wird zu Drittprodukten umgeleitet.",
         tags=["Keyword-Advertising", "Online-Handel"]),
    dict(id="bgh_ortlieb_i", name="ORTLIEB I", court="BGH", date="2018-02-15", az="I ZR 138/16",
         fundstelle="GRUR 2018, 924", norms=["§ 14 Abs. 2 Nr. 1", "§ 23"],
         concepts=["keyword_advertising", "markenmaessige_benutzung"],
         kern="Die Anzeige von Konkurrenzprodukten in der internen Suchergebnisliste von Amazon bei Eingabe der Marke 'Ortlieb' verletzt die Marke nicht ohne weiteres: Der Nutzer erkennt bei einer Plattform-Suche, dass ihm auch Alternativangebote gezeigt werden, sofern die Ergebnisse nicht als Produkte des Markeninhabers ausgegeben werden.",
         tags=["Keyword-Advertising", "Online-Handel"]),
    dict(id="bgh_tork", name="Tork", court="BGH", date="2018-10-17", az="I ZR 136/17",
         fundstelle="GRUR 2019, 79", norms=["§ 14 Abs. 2 Nr. 1", "§ 23 Abs. 1 Nr. 3"],
         concepts=["doppelidentitaet", "ersatzteilhinweis"],
         kern="Wird ein mit der Marke des Originalherstellers gekennzeichneter Papierhandtuchspender mit Handtüchern eines Dritten befüllt, kann darin eine markenmäßige Benutzung (Doppelidentität) liegen, wenn der Verkehr die Nachfüllware dem Markeninhaber zuordnet. Der Lieferant der Nachfüllware, der die Spender nicht selbst befüllt, ist nicht Täter, kommt aber als Teilnehmer in Betracht; der Hinweis 'passend auch für Tork-Spender' ist an § 23 Nr. 3 zu messen.",
         tags=["Doppelidentität", "Ersatzteil", "§ 23"]),

    # ------------------------------------------------------------------
    # Verwechslungsgefahr / Kennzeichnungskraft / Zeichenähnlichkeit
    # ------------------------------------------------------------------
    dict(id="eugh_sabel_puma", name="SABEL/Puma", court="EuGH", date="1997-11-11", az="C-251/95",
         fundstelle="GRUR 1998, 387", norms=["§ 14 Abs. 2 Nr. 2", "§ 9 Abs. 1 Nr. 2"],
         concepts=["verwechslungsgefahr", "gesamteindruck", "kennzeichnungskraft"],
         kern="Die Verwechslungsgefahr ist umfassend unter Berücksichtigung aller Umstände des Einzelfalls zu beurteilen. Maßgeblich ist der Gesamteindruck der Zeichen beim Durchschnittsverbraucher; die bloße gedankliche Verbindung genügt nicht. Je höher die Kennzeichnungskraft der älteren Marke, desto größer die Verwechslungsgefahr.",
         tags=["Verwechslungsgefahr"]),
    dict(id="eugh_canon", name="Canon", court="EuGH", date="1998-09-29", az="C-39/97",
         fundstelle="GRUR 1998, 922", norms=["§ 14 Abs. 2 Nr. 2", "§ 9 Abs. 1 Nr. 2"],
         concepts=["wechselwirkung", "warenaehnlichkeit", "kennzeichnungskraft"],
         kern="Wechselwirkungslehre: Ein geringerer Grad der Warenähnlichkeit kann durch einen höheren Grad der Zeichenähnlichkeit oder eine erhöhte Kennzeichnungskraft ausgeglichen werden und umgekehrt. Bei der Warenähnlichkeit sind Art, Verwendungszweck, Nutzung, Eigenart als konkurrierende oder ergänzende Waren zu berücksichtigen. Verwechslungsgefahr umfasst auch die Annahme wirtschaftlicher Verbindungen.",
         tags=["Verwechslungsgefahr", "Warenähnlichkeit"]),
    dict(id="eugh_lloyd", name="Lloyd Schuhfabrik Meyer", court="EuGH", date="1999-06-22", az="C-342/97",
         fundstelle="GRUR Int. 1999, 734", norms=["§ 14 Abs. 2 Nr. 2"],
         concepts=["verwechslungsgefahr", "kennzeichnungskraft", "durchschnittsverbraucher"],
         kern="Maßstab ist der durchschnittlich informierte, aufmerksame und verständige Durchschnittsverbraucher, der die Marken selten gleichzeitig wahrnimmt und sich auf sein unvollkommenes Erinnerungsbild verlässt. Die Kennzeichnungskraft ist anhand aller Umstände (Marktanteil, Intensität, Dauer, Werbeaufwand, Bekanntheitsgrad) zu bestimmen; feste Prozentsätze gibt es nicht.",
         tags=["Verwechslungsgefahr", "Durchschnittsverbraucher"]),
    dict(id="eugh_thomson_life", name="THOMSON LIFE (Medion)", court="EuGH", date="2005-10-06", az="C-120/04",
         fundstelle="GRUR 2005, 1042", norms=["§ 14 Abs. 2 Nr. 2"],
         concepts=["selbstaendig_kennzeichnende_stellung", "praegetheorie", "gesamteindruck"],
         kern="Verwechslungsgefahr kann auch dann bestehen, wenn eine ältere Marke ('LIFE') in ein zusammengesetztes jüngeres Zeichen ('THOMSON LIFE') übernommen wird und dort eine selbständig kennzeichnende Stellung behält, ohne den Gesamteindruck zu dominieren. Der Verkehr kann annehmen, die Waren stammten aus wirtschaftlich verbundenen Unternehmen.",
         tags=["Verwechslungsgefahr", "Zusammengesetzte Zeichen"]),
    dict(id="bgh_culinaria", name="Culinaria/Villa Culinaria", court="BGH", date="2012-12-05", az="I ZR 85/11",
         fundstelle="GRUR 2013, 833", norms=["§ 14 Abs. 2 Nr. 2"],
         concepts=["selbstaendig_kennzeichnende_stellung", "praegetheorie", "kennzeichnungskraft", "verwechslungsgefahr"],
         kern="Grundlegende Klärung: Bei der Verwechslungsgefahr ist zwischen der Prägung des Gesamteindrucks (Prägetheorie) und der selbständig kennzeichnenden Stellung eines Bestandteils zu unterscheiden. Eine selbständig kennzeichnende Stellung ist die Ausnahme und bedarf besonderer Umstände. Systematik der Kennzeichnungskraft: fünf Grade (sehr gering, gering, durchschnittlich, erhöht, sehr hoch).",
         tags=["Verwechslungsgefahr", "Kennzeichnungskraft"]),
    dict(id="bgh_interconnect", name="INTERCONNECT/T-InterConnect", court="BGH", date="2007-06-28", az="I ZR 132/04",
         fundstelle="GRUR 2008, 258", norms=["§ 14 Abs. 2 Nr. 2"],
         concepts=["selbstaendig_kennzeichnende_stellung", "verwechslungsgefahr_weiterer_sinn"],
         kern="Ein Bestandteil, der in einem zusammengesetzten Zeichen neben einem bekannten Stammbestandteil ('T-') die konkrete Dienstleistung bezeichnet, kann auch bei geringer Kennzeichnungskraft eine selbständig kennzeichnende Stellung haben und Verwechslungsgefahr im weiteren Sinne begründen.",
         tags=["Verwechslungsgefahr", "Zusammengesetzte Zeichen"]),
    dict(id="bgh_metrobus", name="METROBUS", court="BGH", date="2009-02-05", az="I ZR 167/06",
         fundstelle="GRUR 2009, 484", norms=["§ 14 Abs. 2 Nr. 2", "§ 14 Abs. 2 Nr. 3", "§ 15"],
         concepts=["verwechslungsgefahr", "praegetheorie", "bekannte_marke", "markenmaessige_benutzung"],
         kern="Keine Verwechslungsgefahr zwischen 'METRO' und 'METROBUS' für Verkehrsdienstleistungen: 'Metro' wird in 'Metrobus' als beschreibender Hinweis auf ein städtisches Verkehrsmittel verstanden und prägt das Zeichen nicht; auch keine selbständig kennzeichnende Stellung. Schutz der bekannten Marke scheitert an fehlender gedanklicher Verknüpfung.",
         tags=["Verwechslungsgefahr"]),
    dict(id="bgh_kinder_ii", name="Kinder II", court="BGH", date="2007-09-20", az="I ZR 94/04",
         fundstelle="GRUR 2007, 1066", norms=["§ 14 Abs. 2 Nr. 2", "§ 8 Abs. 3"],
         concepts=["kennzeichnungskraft", "verkehrsdurchsetzung", "verwechslungsgefahr"],
         kern="Der Wortbestandteil 'Kinder' ist für Süßwaren glatt beschreibend; er hat seine Schutzfähigkeit erst durch Verkehrsdurchsetzung erlangt und besitzt daher nur durchschnittliche, nicht gesteigerte Kennzeichnungskraft. Die durch Verkehrsdurchsetzung erworbene Kennzeichnungskraft beschränkt sich auf die konkrete durchgesetzte Form.",
         tags=["Kennzeichnungskraft", "Verkehrsdurchsetzung"]),
    dict(id="bgh_maalox", name="Maalox/Melox-GRY", court="BGH", date="2011-06-01", az="I ZB 52/09",
         fundstelle="GRUR 2012, 64", norms=["§ 9 Abs. 1 Nr. 2"],
         concepts=["verwechslungsgefahr", "zeichenaehnlichkeit", "durchschnittsverbraucher"],
         kern="Setzen sich die angesprochenen Verkehrskreise aus mehreren Gruppen (Fachkreise und Endverbraucher) zusammen, genügt für die Verwechslungsgefahr, dass sie bei einer der Gruppen besteht. Die Zeichen 'Maalox' und 'Melox-GRY' sind klanglich und schriftbildlich hinreichend verschieden.",
         tags=["Verwechslungsgefahr", "Verkehrskreise"]),
    dict(id="bgh_goldbaeren", name="Goldbären", court="BGH", date="2015-09-23", az="I ZR 105/14",
         fundstelle="GRUR 2016, 197", norms=["§ 14 Abs. 2 Nr. 2", "§ 14 Abs. 2 Nr. 3"],
         concepts=["zeichenaehnlichkeit", "bekannte_marke", "gedankliche_verknuepfung"],
         kern="Beim Vergleich einer Wortmarke ('Goldbären') mit einer dreidimensionalen Produktgestaltung (Lindt-Teddy) kann Zeichenähnlichkeit nur in begrifflicher Hinsicht bestehen. Sie setzt voraus, dass die Wortmarke aus Sicht des Verkehrs die naheliegende, ungezwungene und erschöpfende Bezeichnung der Gestaltung ist – strenger Maßstab, hier verneint.",
         tags=["Zeichenähnlichkeit", "Bekanntheitsschutz"]),
    dict(id="bgh_lacoste_krokodil", name="coccodrillo (Lacoste-Krokodil)", court="BGH", date="2005-09-22", az="I ZB 40/03",
         fundstelle="GRUR 2006, 60", norms=["§ 9 Abs. 1 Nr. 2"],
         concepts=["kennzeichnungskraft", "zeichenaehnlichkeit", "verwechslungsgefahr"],
         kern="Bei Bildmarken kann Verwechslungsgefahr auf einer Übereinstimmung im Bedeutungsgehalt beruhen (Krokodil), wenn die ältere Marke hohe Kennzeichnungskraft besitzt. Die gesteigerte Kennzeichnungskraft (Lacoste-Krokodil für Bekleidung) erweitert den Schutzbereich auch gegenüber unterschiedlich gestalteten Motiven.",
         tags=["Kennzeichnungskraft", "Bildmarke"]),
    dict(id="bgh_mustang", name="Mustang", court="BGH", date="2004-07-22", az="I ZR 204/01",
         fundstelle="GRUR 2004, 865", norms=["§ 14 Abs. 2 Nr. 2", "§ 15"],
         concepts=["verwechslungsgefahr_weiterer_sinn", "unternehmenskennzeichen"],
         kern="Wird eine ältere Marke ('MUSTANG') als Bestandteil in ein zusammengesetztes Zeichen ('Sixtyseven by Mustang') übernommen, kann sie dort eine selbständig kennzeichnende Stellung behalten, ohne den Gesamteindruck zu prägen. Eine Verwechslungsgefahr im weiteren Sinne (Annahme wirtschaftlicher Verbindungen) kommt in Betracht, wenn das ältere Zeichen zugleich Unternehmenskennzeichen ist; sie bleibt die Ausnahme.",
         tags=["Verwechslungsgefahr"]),
    dict(id="bgh_springende_raubkatze", name="Springende Raubkatze", court="BGH", date="1995-06-29", az="I ZB 22/93",
         fundstelle="GRUR 1996, 198", norms=["§ 9 Abs. 1 Nr. 2"],
         concepts=["praegetheorie", "gesamteindruck"],
         kern="Grundentscheidung zur Prägetheorie: Bei mehrgliedrigen Zeichen ist auf den Gesamteindruck abzustellen; ein einzelner Bestandteil kann den Gesamteindruck aber prägen, wenn die übrigen Bestandteile für den Verkehr in den Hintergrund treten. Ein rein beschreibender Bestandteil prägt nicht.",
         tags=["Prägetheorie"]),
    dict(id="bgh_desperados", name="DESPERADOS/DESPERADO", court="BGH", date="2013-11-06", az="I ZB 63/12",
         fundstelle="GRUR 2014, 488", norms=["§ 9 Abs. 1 Nr. 2"],
         concepts=["warenaehnlichkeit"],
         kern="Zur Warenähnlichkeit (Bier vs. Spirituosen/alkoholfreie Getränke): Maßgeblich sind Herstellungsstätten, Vertriebswege, stoffliche Beschaffenheit, Verwendungszweck sowie ob die Waren einander ergänzen oder miteinander konkurrieren; die Verkehrsauffassung über eine gemeinsame betriebliche Herkunft ist entscheidend.",
         tags=["Warenähnlichkeit"]),
    dict(id="bgh_bogner_b", name="Bogner B/Barbie B", court="BGH", date="2012-02-02", az="I ZR 50/11",
         fundstelle="GRUR 2012, 930", norms=["§ 14 Abs. 2 Nr. 2"],
         concepts=["kennzeichnungskraft", "zeichenaehnlichkeit"],
         kern="Einzelbuchstabenmarken haben originär durchschnittliche Kennzeichnungskraft, sofern kein beschreibender Bezug besteht. Bei der Zeichenähnlichkeit zweier Buchstabenmarken kommt es maßgeblich auf die graphische Gestaltung an.",
         tags=["Kennzeichnungskraft", "Buchstabenmarke"]),
    dict(id="bgh_ips_isp", name="IPS/ISP", court="BGH", date="2015-03-05", az="I ZR 161/13",
         fundstelle="GRUR 2015, 1004", norms=["§ 14 Abs. 2 Nr. 2"],
         concepts=["zeichenaehnlichkeit", "kennzeichnungskraft"],
         kern="Die Ähnlichkeit von Buchstabenfolgen ist nach Klang, Schriftbild und Sinngehalt zu beurteilen; eine Übereinstimmung in nur einer Hinsicht kann Verwechslungsgefahr begründen. Kennzeichnungsschwäche einer Buchstabenfolge wegen beschreibender Anklänge ist zu berücksichtigen.",
         tags=["Zeichenähnlichkeit"]),

    # ------------------------------------------------------------------
    # Bekanntheitsschutz § 14 Abs. 2 Nr. 3
    # ------------------------------------------------------------------
    dict(id="eugh_general_motors", name="General Motors/Yplon (Chevy)", court="EuGH", date="1999-09-14", az="C-375/97",
         fundstelle="GRUR Int. 2000, 73", norms=["§ 14 Abs. 2 Nr. 3"],
         concepts=["bekannte_marke"],
         kern="Eine Marke ist bekannt, wenn sie einem bedeutenden Teil des Publikums bekannt ist, das von den durch die Marke erfassten Waren oder Dienstleistungen betroffen ist. Feste Prozentsätze gibt es nicht; zu berücksichtigen sind Marktanteil, Intensität, geographische Ausdehnung, Dauer der Benutzung und Werbeaufwand. Bekanntheit in einem wesentlichen Teil des Gebiets genügt.",
         tags=["Bekanntheitsschutz"]),
    dict(id="eugh_intel", name="Intel/CPM (INTELMARK)", court="EuGH", date="2008-11-27", az="C-252/07",
         fundstelle="GRUR 2009, 56", norms=["§ 14 Abs. 2 Nr. 3"],
         concepts=["gedankliche_verknuepfung", "verwaesserung", "bekannte_marke"],
         kern="Die gedankliche Verknüpfung zwischen den Zeichen ist notwendige, aber nicht hinreichende Voraussetzung des Bekanntheitsschutzes. Eine Beeinträchtigung der Unterscheidungskraft (Verwässerung) erfordert den Nachweis einer Änderung des wirtschaftlichen Verhaltens des Durchschnittsverbrauchers oder die ernsthafte Gefahr einer solchen Änderung.",
         tags=["Bekanntheitsschutz", "Verwässerung"]),
    dict(id="bgh_lila_postkarte", name="Lila-Postkarte", court="BGH", date="2005-02-03", az="I ZR 159/02",
         fundstelle="GRUR 2005, 583", norms=["§ 14 Abs. 2 Nr. 3"],
         concepts=["bekannte_marke", "ausnutzung_wertschaetzung", "markenmaessige_benutzung"],
         kern="Die Verwendung der bekannten Milka-Marken (Farbe Lila, 'Milka') auf einer satirischen Postkarte ist markenmäßige Benutzung. Die Ausnutzung der Unterscheidungskraft/Wertschätzung ist aber nicht 'ohne rechtfertigenden Grund in unlauterer Weise' erfolgt, wenn die Kunstfreiheit (Art. 5 Abs. 3 GG) überwiegt und die Marke nicht herabgesetzt wird.",
         tags=["Bekanntheitsschutz", "Kunstfreiheit"]),
    dict(id="bgh_springender_pudel", name="Springender Pudel", court="BGH", date="2015-04-02", az="I ZR 59/13",
         fundstelle="GRUR 2015, 1114", norms=["§ 14 Abs. 2 Nr. 3", "§ 9 Abs. 1 Nr. 3", "§ 51"],
         concepts=["bekannte_marke", "ausnutzung_unterscheidungskraft", "gedankliche_verknuepfung"],
         kern="Die Parodie einer bekannten Marke (springender Pudel statt Puma-Raubkatze) nutzt deren Unterscheidungskraft in unlauterer Weise aus, wenn der Verkehr die Zeichen gedanklich verknüpft und der Parodist von der Aufmerksamkeit der bekannten Marke profitiert. Kunst- und Meinungsfreiheit rechtfertigen nicht die Eintragung als eigene Marke; der Inhaber der bekannten Marke kann die Löschung verlangen.",
         tags=["Bekanntheitsschutz", "Markenparodie"]),
    dict(id="bgh_otto_cap", name="OTTO Cap", court="BGH", date="2013-10-31", az="I ZR 49/12",
         fundstelle="GRUR 2014, 378", norms=["§ 14 Abs. 2 Nr. 3", "§ 14 Abs. 2 Nr. 2"],
         concepts=["bekannte_marke", "ausnutzung_unterscheidungskraft", "warenaehnlichkeit"],
         kern="Der Bekanntheitsschutz gilt auch bei Waren-/Dienstleistungsidentität oder -ähnlichkeit (richtlinienkonforme Auslegung). Unlautere Ausnutzung der Unterscheidungskraft ('OTTO' für Caps): Der Verkehr verknüpft die Zeichen gedanklich; der Versandhändler kann die Verwendung für Bekleidung verbieten, auch ohne Verwechslungsgefahr.",
         tags=["Bekanntheitsschutz"]),
    dict(id="bgh_oeko_test_ii", name="ÖKO-TEST II", court="BGH", date="2019-12-12", az="I ZR 117/17",
         fundstelle="GRUR 2020, 405", norms=["§ 14 Abs. 2 Nr. 3"],
         concepts=["bekannte_marke", "ausnutzung_wertschaetzung"],
         kern="Die Verwendung des bekannten ÖKO-TEST-Siegels in der Produktwerbung ohne Lizenz nutzt die Wertschätzung der bekannten Marke unlauter aus, auch wenn das Testsiegel für Dienstleistungen (Verbraucherinformation) und nicht für die beworbenen Waren eingetragen ist (im Anschluss an EuGH C-690/17).",
         tags=["Bekanntheitsschutz", "Testsiegel"]),
    dict(id="bgh_volkswagen_volksinspektion", name="VOLKSWAGEN/Volks.Inspektion", court="BGH", date="2013-04-11", az="I ZR 214/11",
         fundstelle="GRUR 2013, 1239", norms=["§ 14 Abs. 2 Nr. 3", "§ 14 Abs. 2 Nr. 2"],
         concepts=["bekannte_marke", "gedankliche_verknuepfung", "serienmarke"],
         kern="Zur Beeinträchtigung/Ausnutzung der bekannten Marke VOLKSWAGEN durch 'Volks.Inspektion' u.a. (ATU): Verwechslungsgefahr wurde verneint; für den Bekanntheitsschutz genügt die gedankliche Verknüpfung, die bei Übernahme des charakteristischen Bestandteils 'Volks' in Verbindung mit Kfz-Dienstleistungen naheliegt – Zurückverweisung.",
         tags=["Bekanntheitsschutz"]),
    dict(id="bgh_tuev_ii", name="TÜV II", court="BGH", date="2011-08-17", az="I ZR 108/09",
         fundstelle="GRUR 2011, 1043", norms=["§ 14 Abs. 2 Nr. 3", "§ 23"],
         concepts=["bekannte_marke", "ausnutzung_unterscheidungskraft", "schranke_23"],
         kern="Die Verwendung der bekannten Marke 'TÜV' durch einen Wettbewerber ('TÜV-Service' ohne Berechtigung) nutzt die Unterscheidungskraft und Wertschätzung in unlauterer Weise aus; eine Rechtfertigung als beschreibende Angabe (§ 23 Nr. 2) scheidet aus, wenn 'TÜV' nicht generisch für Prüfdienstleistungen geworden ist.",
         tags=["Bekanntheitsschutz"]),

    # ------------------------------------------------------------------
    # Schranken §§ 23, 24
    # ------------------------------------------------------------------
    dict(id="eugh_gillette", name="Gillette/LA-Laboratories", court="EuGH", date="2005-03-17", az="C-228/03",
         fundstelle="GRUR 2005, 509", norms=["§ 23 Abs. 1 Nr. 3"],
         concepts=["ersatzteilhinweis", "schranke_23"],
         kern="Die Benutzung einer fremden Marke als Bestimmungshinweis (Rasierklingen 'passend für Gillette Sensor') ist notwendig, wenn sie praktisch das einzige Mittel ist, dem Publikum eine verständliche und vollständige Information über die Bestimmung zu geben. Sie muss den anständigen Gepflogenheiten entsprechen: keine Verbindung suggerieren, Wertschätzung nicht unlauter ausnutzen, Marke nicht herabsetzen, kein Imitat.",
         tags=["§ 23", "Ersatzteil"]),
    dict(id="bgh_staubsaugerfiltertueten", name="Staubsaugerfiltertüten", court="BGH", date="2005-01-20", az="I ZR 34/02",
         fundstelle="GRUR 2005, 423", norms=["§ 23 Abs. 1 Nr. 3"],
         concepts=["ersatzteilhinweis", "schranke_23"],
         kern="Die Angabe 'Filtertüte passend für Vorwerk Kobold 130' ist als notwendiger Bestimmungshinweis zulässig, wenn der Zusatz 'passend für' deutlich hervorgehoben ist und die eigene Marke des Anbieters im Vordergrund steht, so dass keine Verbindung zum Markeninhaber suggeriert wird.",
         tags=["§ 23", "Ersatzteil"]),
    dict(id="bgh_kuehlergrill", name="Kühlergrill", court="BGH", date="2019-03-07", az="I ZR 61/18",
         fundstelle="GRUR 2019, 953", norms=["§ 14 Abs. 2 Nr. 1", "§ 23 Abs. 1 Nr. 3"],
         concepts=["ersatzteilhinweis", "markenmaessige_benutzung", "doppelidentitaet"],
         kern="Ein Kühlergrill mit einer Aufnahme, die die Form des Audi-Emblems (Ringe) hat, benutzt die Marke markenmäßig. Die Schranke des § 23 Nr. 3 greift nicht, weil die Nachbildung des Emblems zur Angabe der Bestimmung als Ersatzteil nicht notwendig ist – eine neutrale Halterung genügt.",
         tags=["§ 23", "Ersatzteil"]),
    dict(id="bgh_grosse_inspektion", name="GROSSE INSPEKTION FÜR ALLE", court="BGH", date="2011-04-14", az="I ZR 33/10",
         fundstelle="GRUR 2011, 1135", norms=["§ 14 Abs. 2 Nr. 1", "§ 23 Abs. 1 Nr. 3"],
         concepts=["schranke_23", "ersatzteilhinweis", "doppelidentitaet"],
         kern="Die Verwendung der Wort-Bild-Marke (VW-Logo) einer Kfz-Werkstatt in der Werbung für Inspektionen ist nicht nach § 23 Nr. 3 gerechtfertigt, wenn die Angabe der Bestimmung auch durch die Wortmarke 'VW' möglich wäre; die Verwendung des Bildzeichens ist nicht notwendig und verstößt gegen die anständigen Gepflogenheiten.",
         tags=["§ 23"]),
    dict(id="eugh_bms", name="Bristol-Myers Squibb/Paranova", court="EuGH", date="1996-07-11", az="C-427/93 u.a.",
         fundstelle="GRUR Int. 1996, 1144", norms=["§ 24 Abs. 2"],
         concepts=["erschoepfung", "berechtigte_gruende", "umverpackung"],
         kern="Der Markeninhaber kann sich dem Vertrieb umgepackter Arzneimittel (Parallelimport) nicht widersetzen, wenn (1) das Umpacken zur Vermarktung im Einfuhrstaat erforderlich ist, (2) der Originalzustand nicht beeinträchtigt wird, (3) Umpacker und Hersteller angegeben sind, (4) die Aufmachung den Ruf nicht schädigt und (5) der Inhaber vorab unterrichtet wird (BMS-Kriterien).",
         tags=["Erschöpfung", "Parallelimport"]),
    dict(id="eugh_van_doren", name="Van Doren + Q. (stüssy)", court="EuGH", date="2003-04-08", az="C-244/00",
         fundstelle="GRUR 2003, 512", norms=["§ 24 Abs. 1"],
         concepts=["erschoepfung", "beweislast_erschoepfung"],
         kern="Grundsätzlich trägt der Dritte, der sich auf Erschöpfung beruft, die Beweislast für das Inverkehrbringen im EWR mit Zustimmung des Inhabers. Bei einem ausschließlichen Vertriebssystem und tatsächlicher Gefahr der Marktabschottung muss jedoch der Markeninhaber beweisen, dass die Ware außerhalb des EWR in Verkehr gebracht wurde.",
         tags=["Erschöpfung", "Beweislast"]),
    dict(id="bgh_stuessy_ii", name="stüssy II", court="BGH", date="2003-10-23", az="I ZR 193/97",
         fundstelle="GRUR 2004, 156", norms=["§ 24 Abs. 1"],
         concepts=["erschoepfung", "beweislast_erschoepfung"],
         kern="Umsetzung von Van Doren: Der Beklagte trägt grundsätzlich die Beweislast für die Erschöpfung; eine Beweislastumkehr zugunsten des Beklagten tritt ein, wenn der Markeninhaber ein ausschließliches Vertriebssystem betreibt und bei Offenlegung der Bezugsquelle Marktabschottung droht.",
         tags=["Erschöpfung", "Beweislast"]),
    dict(id="bgh_converse_i", name="Converse I", court="BGH", date="2012-03-15", az="I ZR 52/10",
         fundstelle="GRUR 2012, 626", norms=["§ 24 Abs. 1"],
         concepts=["erschoepfung", "beweislast_erschoepfung"],
         kern="Behauptet der Beklagte, es handle sich um Originalware, für die Erschöpfung eingetreten sei, und bestreitet der Markeninhaber die Echtheit, trägt der Beklagte die Beweislast für die Echtheit und das Inverkehrbringen im EWR, sofern keine Gefahr der Marktabschottung besteht.",
         tags=["Erschöpfung", "Beweislast"]),
    dict(id="bgh_converse_ii", name="Converse II", court="BGH", date="2012-03-15", az="I ZR 137/10",
         fundstelle="GRUR 2012, 630", norms=["§ 24 Abs. 1"],
         concepts=["erschoepfung", "beweislast_erschoepfung"],
         kern="Stammt die Ware von einem ehemaligen Lizenznehmer des Markeninhabers im EWR, gilt: Das Inverkehrbringen durch einen Lizenznehmer unter Verstoß gegen den Lizenzvertrag (§ 30 Abs. 2) erfolgt ohne Zustimmung; Erschöpfung tritt nicht ein. Keine Beweislastumkehr ohne Marktabschottungsgefahr.",
         tags=["Erschöpfung", "Lizenz"]),
    dict(id="eugh_dior_evora", name="Parfums Christian Dior/Evora", court="EuGH", date="1997-11-04", az="C-337/95",
         fundstelle="GRUR Int. 1998, 140", norms=["§ 24 Abs. 2"],
         concepts=["erschoepfung", "berechtigte_gruende"],
         kern="Nach Erschöpfung darf der Wiederverkäufer die Marke auch in seiner Werbung benutzen. Ein berechtigter Grund i.S.d. § 24 Abs. 2 liegt nur vor, wenn die Werbung den Ruf der Marke (Luxusimage) erheblich schädigt – Abwägung zwischen dem berechtigten Interesse des Inhabers und dem Interesse des Händlers an branchenüblicher Werbung.",
         tags=["Erschöpfung", "Werbung"]),

    # ------------------------------------------------------------------
    # Benutzungszwang §§ 25, 26, 49
    # ------------------------------------------------------------------
    dict(id="eugh_ansul", name="Ansul/Ajax", court="EuGH", date="2003-03-11", az="C-40/01",
         fundstelle="GRUR 2003, 425", norms=["§ 26 Abs. 1"],
         concepts=["ernsthafte_benutzung", "rechtserhaltende_benutzung"],
         kern="Ernsthafte Benutzung liegt vor, wenn die Marke entsprechend ihrer Hauptfunktion benutzt wird, um für die Waren einen Absatzmarkt zu erschließen oder zu sichern; rein symbolische Benutzung zur Rechtserhaltung genügt nicht. Auch die Benutzung für Ersatzteile oder im Rahmen des Kundendienstes kann ausreichen.",
         tags=["Benutzungszwang"]),
    dict(id="bgh_voodoo", name="VOODOO", court="BGH", date="2013-02-06", az="I ZR 106/11",
         fundstelle="GRUR 2013, 925", norms=["§ 26 Abs. 1", "§ 25", "§ 49"],
         concepts=["ernsthafte_benutzung", "rechtserhaltende_benutzung"],
         kern="Ernsthafte Benutzung setzt keinen Mindestumfang voraus; entscheidend ist, ob die Benutzung wirtschaftlich sinnvoll ist, um Marktanteile zu gewinnen oder zu halten. Bei einer Wortmarke reicht die Benutzung auf Etiketten und in Katalogen mit tatsächlichem Absatz; die Beweislast trägt im Verletzungsprozess der Markeninhaber, wenn die Einrede erhoben wird.",
         tags=["Benutzungszwang"]),
    dict(id="bgh_lottocard", name="LOTTOCARD", court="BGH", date="2008-04-10", az="I ZR 167/05",
         fundstelle="GRUR 2009, 60", norms=["§ 26 Abs. 1", "§ 26 Abs. 3"],
         concepts=["rechtserhaltende_benutzung"],
         kern="Einer Marke ('LOTTO' für Lotteriedienstleistungen) kann die rechtserhaltende Benutzung nicht mit der Begründung abgesprochen werden, sie werde nur beschreibend verstanden; es genügt, dass der Verkehr die konkrete Verwendung als Marke auffasst. Die Verwendung in Kombination mit anderen Zeichen ('LOTTOCARD') kann rechtserhaltend sein, wenn 'LOTTO' seine kennzeichnende Eigenständigkeit behält.",
         tags=["Benutzungszwang"]),
    dict(id="bgh_probiotik", name="Probiotik", court="BGH", date="2014-01-08", az="I ZR 38/13",
         fundstelle="GRUR 2014, 662", norms=["§ 26 Abs. 3"],
         concepts=["abweichende_form", "rechtserhaltende_benutzung"],
         kern="Wird eine Wortmarke graphisch gestaltet oder mit Bildelementen ergänzt, ist zu prüfen, ob die Zusätze einen Bezug zur Herkunftsfunktion haben oder nur allgemeine Sachhinweise/Werbemittel sind; letztere verändern den kennzeichnenden Charakter nicht (§ 26 Abs. 3).",
         tags=["Benutzungszwang", "Abweichende Form"]),
    dict(id="bgh_dorzo", name="Dorzo", court="BGH", date="2017-05-11", az="I ZB 6/16",
         fundstelle="GRUR 2017, 1043", norms=["§ 26 Abs. 3"],
         concepts=["abweichende_form", "rechtserhaltende_benutzung"],
         kern="Die Benutzung 'Dorzo-Vision' für die Marke 'Dorzo' ist nicht rechtserhaltend, wenn der Verkehr die Kombination als einheitliches Zeichen wahrnimmt und 'Dorzo' nicht mehr als eigenständigen Herkunftshinweis erkennt: Der kennzeichnende Charakter ist dann verändert.",
         tags=["Benutzungszwang", "Abweichende Form"]),
    dict(id="bgh_castell", name="Castell/VIN CASTEL", court="BGH", date="2012-05-31", az="I ZR 112/10",
         fundstelle="GRUR 2013, 68", norms=["§ 5 Abs. 2", "§ 26 Abs. 3"],
         concepts=["firmenschlagwort", "abweichende_form", "rechtserhaltende_benutzung"],
         kern="Zum Schutz eines Firmenbestandteils ('Castell') als Unternehmenskennzeichen nach § 5 Abs. 2: Erforderlich ist ein unterscheidungskräftiger Bestandteil, der sich seiner Natur nach als schlagwortartiger Hinweis auf das Unternehmen eignet. Zur rechtserhaltenden Benutzung einer Marke in Kombination mit weiteren Bestandteilen ('Castell' in 'Castell Castell'): unschädlich, wenn der Verkehr die Marke als eigenständigen Herkunftshinweis erkennt.",
         tags=["Benutzungszwang"]),

    # ------------------------------------------------------------------
    # Geschäftliche Bezeichnungen §§ 5, 15
    # ------------------------------------------------------------------
    dict(id="bgh_wetter_de", name="wetter.de", court="BGH", date="2016-01-28", az="I ZR 202/14",
         fundstelle="GRUR 2016, 939", norms=["§ 5 Abs. 3", "§ 15"],
         concepts=["werktitel", "unterscheidungskraft"],
         kern="Apps und Internet-Informationsangebote können titelschutzfähige Werke i.S.d. § 5 Abs. 3 sein. 'wetter.de' fehlt jedoch die originäre Unterscheidungskraft, weil die Bezeichnung nur den Inhalt (Wetterinformationen) beschreibt; eine Verkehrsgewöhnung an beschreibende Titel wie bei Zeitschriften ist für Apps/Domains nicht festgestellt.",
         tags=["Werktitel", "Domain", "App"]),
    dict(id="bgh_das_omen", name="Das Omen", court="BGH", date="2019-01-31", az="I ZR 97/17",
         fundstelle="GRUR 2019, 535", norms=["§ 5 Abs. 3", "§ 15 Abs. 2"],
         concepts=["werktitel"],
         kern="Der Titel eines Musikstücks ('Das Omen (Teil 1)') genießt Werktitelschutz; Inhaber ist, wem das Werk zuzuordnen ist (Komponist/Textdichter). Die Verwechslungsgefahr ist unter Berücksichtigung der Besonderheiten des Werks (Werkähnlichkeit) zu prüfen.",
         tags=["Werktitel"]),
    dict(id="bgh_augsburger_puppenkiste", name="Augsburger Puppenkiste", court="BGH", date="2008-12-18", az="I ZR 200/06",
         fundstelle="GRUR 2009, 772", norms=["§ 5 Abs. 3", "§ 15 Abs. 2"],
         concepts=["werktitel"],
         kern="Keine Verwechslungsgefahr zwischen 'Augsburger Puppenkiste' und 'Leipziger Puppenkiste': Die Ortsangaben prägen die Gesamtbezeichnungen mit, der gemeinsame Bestandteil 'Puppenkiste' ist kennzeichnungsschwach. Werktitel schützen grundsätzlich nur gegen unmittelbare Werkverwechslung; eine Verwechslungsgefahr im weiteren Sinne kommt nur bei bekannten Titeln mit Herkunftshinweisfunktion in Betracht.",
         tags=["Werktitel"]),
    dict(id="bgh_peek_cloppenburg", name="Peek & Cloppenburg", court="BGH", date="2010-03-31", az="I ZR 174/07",
         fundstelle="GRUR 2010, 738", norms=["§ 5 Abs. 2", "§ 15 Abs. 2", "§ 23 Abs. 1 Nr. 1"],
         concepts=["unternehmenskennzeichen", "gleichnamigkeit"],
         kern="Recht der Gleichnamigen: Zwei seit langem koexistierende Unternehmen gleichen Namens müssen die Verwechslungsgefahr durch aufklärende Zusätze (Ortsangabe) reduzieren; bundesweite Werbung ist zulässig, wenn ein deutlicher, nicht notwendig gleich großer Hinweis auf die Unternehmensidentität erfolgt.",
         tags=["Unternehmenskennzeichen", "Gleichnamigkeit"]),
    dict(id="bgh_baumann_ii", name="Baumann II", court="BGH", date="2016-06-23", az="I ZR 241/14",
         fundstelle="GRUR 2016, 965", norms=["§ 5 Abs. 2", "§ 15", "§ 21"],
         concepts=["unternehmenskennzeichen", "verwirkung"],
         kern="Der Schutz eines Unternehmenskennzeichens entsteht mit Benutzungsaufnahme; die Priorität bestimmt sich nach § 6. Zur Verwirkung und zum Fortbestand des Kennzeichenrechts bei Änderungen der Firma; bei mehreren Bestandteilen kann der prägende Bestandteil ('Baumann') selbständig geschützt sein.",
         tags=["Unternehmenskennzeichen"]),
    dict(id="bgh_soco_de", name="soco.de", court="BGH", date="2004-07-22", az="I ZR 135/01",
         fundstelle="GRUR 2005, 262", norms=["§ 5 Abs. 2", "§ 15"],
         concepts=["unternehmenskennzeichen", "domain"],
         kern="Ein Domainname kann als Unternehmenskennzeichen geschützt sein, wenn der Verkehr ihn als Hinweis auf ein Unternehmen versteht. Der Schutz einer Domain als Kennzeichen entsteht erst mit Benutzungsaufnahme im geschäftlichen Verkehr, nicht schon mit der Registrierung.",
         tags=["Unternehmenskennzeichen", "Domain"]),
    dict(id="bgh_shell_de", name="shell.de", court="BGH", date="2001-11-22", az="I ZR 138/99",
         fundstelle="GRUR 2002, 622", norms=["§ 5 Abs. 2", "§ 15"],
         concepts=["domain", "unternehmenskennzeichen", "gleichnamigkeit"],
         kern="Bei Gleichnamigkeit (Privatperson Shell vs. Shell-Konzern) gilt für Domains grundsätzlich Priorität der Registrierung. Ausnahme bei überragender Bekanntheit eines Namensträgers: Der Verkehr erwartet unter 'shell.de' den bekannten Konzern; der Privatmann muss einen unterscheidenden Zusatz wählen.",
         tags=["Domain", "Namensrecht"]),
    dict(id="bgh_defacto", name="defacto", court="BGH", date="2002-02-21", az="I ZR 230/99",
         fundstelle="GRUR 2002, 898", norms=["§ 5 Abs. 2", "§ 15 Abs. 2"],
         concepts=["unternehmenskennzeichen", "branchennaehe", "firmenschlagwort"],
         kern="Für die Verwechslungsgefahr bei Unternehmenskennzeichen kommt es auf die Branchennähe, die Kennzeichnungskraft des älteren Zeichens und die Zeichenähnlichkeit an (Wechselwirkung). Firmenschlagworte ('defacto') sind selbständig schutzfähig, wenn sie ihrer Natur nach geeignet sind, als Schlagwort zu wirken.",
         tags=["Unternehmenskennzeichen"]),

    # ------------------------------------------------------------------
    # Verwirkung / Verhältnis zum UWG / Verfahren / Haftung
    # ------------------------------------------------------------------
    dict(id="bgh_hard_rock_cafe", name="Hard Rock Cafe", court="BGH", date="2013-08-15", az="I ZR 188/11",
         fundstelle="GRUR 2013, 1161", norms=["§ 21", "§ 14 Abs. 5"],
         concepts=["verwirkung", "verhaeltnis_uwg"],
         kern="Verwirkung nach § 21 Abs. 4 MarkenG i.V.m. § 242 BGB: Bei wiederholten, gleichartigen Verletzungshandlungen entsteht mit jeder Handlung ein neuer Unterlassungsanspruch, so dass Verwirkung nur bei Duldung des konkreten Zustands in Betracht kommt. Aufgabe der Vorrangthese: Lauterkeitsrechtliche Ansprüche (§ 5 Abs. 2 UWG) bestehen neben markenrechtlichen; Wertungswidersprüche sind zu vermeiden.",
         tags=["Verwirkung", "UWG"]),
    dict(id="bgh_internet_versteigerung_ii", name="Internet-Versteigerung II", court="BGH", date="2007-04-19", az="I ZR 35/04",
         fundstelle="GRUR 2007, 708", norms=["§ 14 Abs. 5"],
         concepts=["stoererhaftung"],
         kern="Der Betreiber einer Internet-Handelsplattform (eBay) haftet als Störer auf Unterlassung, wenn er nach Hinweis auf eine klare Markenverletzung das Angebot nicht sperrt und keine zumutbaren Vorkehrungen gegen gleichartige Verletzungen trifft. Die Haftungsprivilegierung des TMG gilt nicht für Unterlassungsansprüche.",
         tags=["Störerhaftung", "Plattform"]),
    dict(id="bgh_kinderhochstuehle", name="Kinderhochstühle im Internet", court="BGH", date="2010-07-22", az="I ZR 139/08",
         fundstelle="GRUR 2011, 152", norms=["§ 14 Abs. 5", "§ 14 Abs. 2 Nr. 2"],
         concepts=["stoererhaftung"],
         kern="Ein Plattformbetreiber muss nicht alle Angebote mit einer Marke manuell auf Fälschungen prüfen; Prüfpflichten bestehen erst nach konkretem Hinweis und im zumutbaren Umfang. Teilnehmerhaftung (Beihilfe) setzt Vorsatz bezüglich der Haupttat voraus; die Störerhaftung wurde für das Lauterkeitsrecht aufgegeben, im Markenrecht beibehalten.",
         tags=["Störerhaftung", "Plattform"]),
    dict(id="bgh_btk", name="BTK", court="BGH", date="2009-07-29", az="I ZR 169/07",
         fundstelle="GRUR 2010, 239", norms=["§ 14 Abs. 6"],
         concepts=["schadensersatz", "lizenzanalogie"],
         kern="Zur Schadensberechnung nach der Lizenzanalogie bei Kennzeichenverletzungen: Der Verletzer schuldet, was vernünftige Vertragsparteien als Lizenzgebühr vereinbart hätten; maßgeblich sind Bekanntheit und Ruf des Kennzeichens, Grad der Verwechslungsgefahr und Umfang der Benutzung.",
         tags=["Schadensersatz"]),
    dict(id="bgh_smartbook", name="smartbook", court="BGH", date="2013-11-06", az="I ZB 59/12",
         fundstelle="GRUR 2014, 565", norms=["§ 8 Abs. 2 Nr. 1", "§ 50", "§ 8 Abs. 2 Nr. 2"],
         concepts=["nichtigkeit", "unterscheidungskraft", "freihaltebeduerfnis"],
         kern="Im Löschungsverfahren wegen absoluter Schutzhindernisse ist auf den Anmeldezeitpunkt abzustellen; die Feststellungslast für das Vorliegen des Schutzhindernisses trägt der Löschungsantragsteller. Verbleibende Zweifel gehen zu Lasten des Antragstellers ('smartbook' für Computer: Schutzhindernis nicht sicher feststellbar).",
         tags=["Löschung", "Nichtigkeit"]),
    dict(id="eugh_interflora", name="Interflora/Marks & Spencer", court="EuGH", date="2011-09-22", az="C-323/09",
         fundstelle="GRUR 2011, 1124", norms=["§ 14 Abs. 2 Nr. 1", "§ 14 Abs. 2 Nr. 3"],
         concepts=["keyword_advertising", "markenfunktionen", "verwaesserung"],
         kern="Keyword-Werbung mit einer bekannten Marke beeinträchtigt die Investitionsfunktion, wenn sie die Nutzung der Marke zum Erwerb/zur Wahrung eines Rufs wesentlich stört. Sie ist als 'Trittbrettfahren' unlauter, wenn Nachahmungen angeboten werden; nicht aber, wenn lediglich eine Alternative zum Markenprodukt angeboten wird (gesunder Wettbewerb).",
         tags=["Keyword-Advertising", "Bekanntheitsschutz"]),
    dict(id="eugh_adam_opel", name="Adam Opel/Autec", court="EuGH", date="2007-01-25", az="C-48/05",
         fundstelle="GRUR 2007, 318", norms=["§ 14 Abs. 2 Nr. 1", "§ 23"],
         concepts=["markenmaessige_benutzung", "herkunftsfunktion"],
         kern="Die Anbringung eines für Kraftfahrzeuge und Spielzeug eingetragenen Zeichens auf Modellautos ist nur dann untersagbar, wenn sie die Funktionen der Marke als für Spielzeug eingetragene Marke beeinträchtigt. Für Kraftfahrzeuge liegt keine Benutzung 'für Waren' vor, die identisch oder ähnlich sind.",
         tags=["Markenmäßige Benutzung"]),
]

CASE_INDEX = {c["id"]: c for c in CASES}
