# -*- coding: utf-8 -*-
"""Abgrenzungen häufig verwechselter Begriffe (für Karteikarten und Vergleichstabellen).

Felder: id, label, concepts (IDs), frage, rows: Liste von (Kriterium, Wert für Begriff A, Wert für Begriff B[, ...]),
merksatz.
"""

DISTINCTIONS = [
    dict(id="d_kennzeichnungskraft_unterscheidungskraft", label="Kennzeichnungskraft vs. Unterscheidungskraft",
         concepts=["kennzeichnungskraft", "unterscheidungskraft"],
         frage="Worin unterscheiden sich Unterscheidungskraft und Kennzeichnungskraft?",
         kriterien=["Rechtliche Ebene", "Norm", "Prüfungsfrage", "Maßstab", "Ergebnis", "Zeitpunkt", "Beispiel"],
         spalten=["Unterscheidungskraft", "Kennzeichnungskraft"],
         rows=[
             ["Schutzvoraussetzung (Eintragungsfähigkeit)", "Schutzumfang (Kollisionsprüfung)"],
             ["§ 8 Abs. 2 Nr. 1 MarkenG", "§ 14 Abs. 2 Nr. 2, § 9 Abs. 1 Nr. 2 MarkenG (ungeschrieben, Faktor der Verwechslungsgefahr)"],
             ["Ist das Zeichen überhaupt geeignet, als Herkunftshinweis für die beanspruchten Waren zu dienen?", "Wie stark prägt sich das Zeichen dem Verkehr als Marke ein – wie weit reicht sein Schutzbereich?"],
             ["Ja/Nein-Entscheidung; großzügig: jede noch so geringe Unterscheidungskraft genügt", "Graduell: sehr gering – gering – durchschnittlich – erhöht – sehr hoch (Culinaria)"],
             ["Fehlt sie: Zurückweisung / Nichtigkeit (§ 50)", "Je höher, desto größer die Verwechslungsgefahr und der Schutzbereich (Wechselwirkung)"],
             ["Anmeldetag (§ 37 Abs. 2, § 50 Abs. 2)", "Kollisionszeitpunkt (Verletzung) bzw. Anmeldetag der jüngeren Marke; kann durch Benutzung steigen oder durch Drittzeichen sinken"],
             ["'marktfrisch' für Lebensmittel: keine Unterscheidungskraft", "'Kinder' für Süßwaren: durch Verkehrsdurchsetzung eingetragen, aber nur durchschnittliche Kennzeichnungskraft (Kinder II)"],
         ],
         merksatz="Unterscheidungskraft = Eintrittskarte ins Register (ob). Kennzeichnungskraft = Reichweite des Schutzes im Streit (wie stark)."),
    dict(id="d_unterscheidungskraft_freihaltebeduerfnis", label="Fehlende Unterscheidungskraft (Nr. 1) vs. Freihaltebedürfnis (Nr. 2)",
         concepts=["unterscheidungskraft", "freihaltebeduerfnis"],
         frage="Wie unterscheiden sich § 8 Abs. 2 Nr. 1 und Nr. 2 MarkenG?",
         kriterien=["Schutzzweck", "Perspektive", "Erfasste Zeichen", "Verhältnis", "Überwindung"],
         spalten=["§ 8 Abs. 2 Nr. 1 (Unterscheidungskraft)", "§ 8 Abs. 2 Nr. 2 (Freihaltebedürfnis)"],
         rows=[
             ["Herkunftsfunktion: Verbraucher soll Zeichen als Marke erkennen können", "Allgemeininteresse der Mitbewerber an freier Verwendbarkeit beschreibender Angaben"],
             ["Sicht des Durchschnittsverbrauchers", "Sicht der Mitbewerber / des Verkehrs (auch künftige Verwendung)"],
             ["Beschreibende Angaben, gebräuchliche Wörter, reine Werbeaussagen, Dekor", "Nur Angaben über Merkmale der Waren (Art, Beschaffenheit, Menge, Bestimmung, Herkunft, Zeit …)"],
             ["Jede nach Nr. 2 beschreibende Angabe fehlt regelmäßig auch die Unterscheidungskraft; nicht umgekehrt (z.B. 'for you')", "Engerer Anwendungsbereich; eigenständig zu prüfen, auch wenn Nr. 1 bejaht"],
             ["Verkehrsdurchsetzung (§ 8 Abs. 3)", "Verkehrsdurchsetzung (§ 8 Abs. 3), aber höhere Anforderungen bei glatt beschreibenden Angaben"],
         ],
         merksatz="Nr. 1 fragt: Sieht der Verbraucher eine Marke? Nr. 2 fragt: Brauchen die Konkurrenten das Wort?"),
    dict(id="d_markenfaehigkeit_unterscheidungskraft", label="Markenfähigkeit (§ 3) vs. Unterscheidungskraft (§ 8 Abs. 2 Nr. 1)",
         concepts=["markenfaehigkeit", "unterscheidungskraft"],
         frage="Abstrakte vs. konkrete Unterscheidungseignung – was ist der Unterschied?",
         kriterien=["Bezugspunkt", "Prüfung", "Praktische Bedeutung", "Sonderfall"],
         spalten=["Markenfähigkeit (§ 3 Abs. 1)", "Unterscheidungskraft (§ 8 Abs. 2 Nr. 1)"],
         rows=[
             ["Abstrakt: Zeichen als solches, unabhängig von Waren", "Konkret: Zeichen in Bezug auf die beanspruchten Waren/Dienstleistungen"],
             ["Kann ein Zeichen dieser Art überhaupt Marke sein?", "Wird dieses Zeichen für diese Waren als Herkunftshinweis verstanden?"],
             ["Nur selten verneint (variable Zeichen, bloße Idee/Konzept)", "Häufigstes Eintragungshindernis"],
             ["§ 3 Abs. 2 Formausschluss: nicht überwindbar", "§ 8 Abs. 3: durch Verkehrsdurchsetzung überwindbar"],
         ],
         merksatz="§ 3 = Türsteher für Zeichenarten, § 8 Abs. 2 Nr. 1 = Prüfung des konkreten Zeichens für konkrete Waren."),
    dict(id="d_verkehrsgeltung_verkehrsdurchsetzung_bekanntheit", label="Verkehrsgeltung vs. Verkehrsdurchsetzung vs. Bekanntheit vs. notorische Bekanntheit",
         concepts=["verkehrsgeltung", "verkehrsdurchsetzung", "bekannte_marke", "notorische_bekanntheit"],
         frage="Welche Bekanntheitsstufen kennt das MarkenG und wofür sind sie relevant?",
         kriterien=["Norm", "Funktion", "Bezugsgröße", "Richtwert"],
         spalten=["Verkehrsgeltung", "Verkehrsdurchsetzung", "Bekannte Marke", "Notorische Bekanntheit"],
         rows=[
             ["§ 4 Nr. 2", "§ 8 Abs. 3", "§ 14 Abs. 2 Nr. 3, § 9 Abs. 1 Nr. 3", "§ 4 Nr. 3, § 10 (Art. 6bis PVÜ)"],
             ["Entstehung einer Benutzungsmarke ohne Eintragung", "Überwindung der Schutzhindernisse § 8 Abs. 2 Nr. 1-3 bei Eintragung", "Erweiterter Schutzbereich über Verwechslungsgefahr hinaus", "Entstehung von Markenschutz ohne Eintragung und Inlandsbenutzung"],
             ["Beteiligte Verkehrskreise (kann regional beschränkt sein)", "Beteiligte Verkehrskreise, bundesweit", "Bedeutender Teil des von den Waren angesprochenen Publikums, wesentlicher Teil des Inlands", "Allgemeine Bekanntheit im Inland (auch außerhalb der Fachkreise)"],
             ["Bei unterscheidungskräftigen Zeichen ca. 20-25 %; bei beschreibenden wie Verkehrsdurchsetzung", "Regelmäßig über 50 % Zuordnung; bei glatt beschreibenden Angaben mehr", "Keine feste Quote (General Motors); Faktoren Marktanteil, Intensität, Werbung", "Sehr hoher Bekanntheitsgrad; praktisch selten"],
         ],
         merksatz="Verkehrsgeltung schafft die Marke, Verkehrsdurchsetzung öffnet das Register, Bekanntheit erweitert den Schutz, Notorietät ersetzt Eintragung und Benutzung."),
    dict(id="d_kollisionstatbestaende", label="Doppelidentität vs. Verwechslungsgefahr vs. Bekanntheitsschutz (§ 14 Abs. 2 Nr. 1-3)",
         concepts=["doppelidentitaet", "verwechslungsgefahr", "bekannte_marke"],
         frage="Welche Voraussetzungen haben die drei Kollisionstatbestände des § 14 Abs. 2 MarkenG?",
         kriterien=["Zeichen", "Waren/Dienstleistungen", "Zusätzliche Voraussetzung", "Betroffene Markenfunktion", "Typische Fälle"],
         spalten=["Nr. 1 Doppelidentität", "Nr. 2 Verwechslungsgefahr", "Nr. 3 Bekanntheitsschutz"],
         rows=[
             ["Identisch", "Identisch oder ähnlich", "Identisch oder ähnlich"],
             ["Identisch", "Identisch oder ähnlich", "Beliebig (auch unähnlich; auch identisch/ähnlich nach OTTO Cap)"],
             ["Keine (absoluter Schutz); aber Beeinträchtigung irgendeiner Markenfunktion", "Verwechslungsgefahr (Wechselwirkung)", "Bekanntheit, gedankliche Verknüpfung, Ausnutzung/Beeinträchtigung, Unlauterkeit ohne rechtfertigenden Grund"],
             ["Herkunfts-, Qualitäts-, Kommunikations-, Investitions- oder Werbefunktion (L'Oréal/Bellure)", "Herkunftsfunktion", "Werbe-/Investitionsfunktion, Ruf (keine Beeinträchtigung der Herkunftsfunktion erforderlich)"],
             ["Produktpiraterie, Keyword-Advertising, Ersatzteilhinweise", "Ähnliche Zeichen auf Konkurrenzprodukten", "Markenparodie, Imagetransfer, Rufausbeutung, Verwässerung"],
         ],
         merksatz="Nr. 1: identisch + identisch. Nr. 2: ähnlich + ähnlich + Verwechslung. Nr. 3: bekannt + Verknüpfung + unlauter."),
    dict(id="d_verwechslungsgefahr_arten", label="Unmittelbare vs. mittelbare Verwechslungsgefahr vs. Verwechslungsgefahr im weiteren Sinne",
         concepts=["verwechslungsgefahr", "verwechslungsgefahr_weiterer_sinn", "serienmarke"],
         frage="Welche Arten der Verwechslungsgefahr gibt es?",
         kriterien=["Fehlvorstellung des Verkehrs", "Voraussetzung", "Beispiel"],
         spalten=["Unmittelbare Verwechslungsgefahr", "Mittelbare Verwechslungsgefahr", "Verwechslungsgefahr im weiteren Sinne"],
         rows=[
             ["Verkehr hält die Zeichen für dasselbe Zeichen", "Verkehr erkennt die Unterschiede, ordnet beide Zeichen aber demselben Unternehmen zu (Serienzeichen)", "Verkehr erkennt verschiedene Unternehmen, nimmt aber wirtschaftliche/organisatorische Verbindungen an"],
             ["Zeichenähnlichkeit nach Klang, Bild, Sinn im Gesamteindruck", "Gemeinsamer kennzeichnungskräftiger Stammbestandteil einer benutzten Zeichenserie", "Ältere Marke als selbständig kennzeichnender Bestandteil oder zugleich Unternehmenskennzeichen; Ausnahmefall"],
             ["'Maalox' / 'Melox' (verneint)", "'Volkswagen' – 'Volks.Inspektion' (Stamm 'Volks')", "'LIFE' – 'THOMSON LIFE'; 'Sixtyseven by Mustang'"],
         ],
         merksatz="Unmittelbar: gleiches Zeichen. Mittelbar: gleiche Familie. Im weiteren Sinne: gleiche Firma dahinter."),
    dict(id="d_praegetheorie_selbstaendige_stellung", label="Prägetheorie vs. selbständig kennzeichnende Stellung",
         concepts=["praegetheorie", "selbstaendig_kennzeichnende_stellung"],
         frage="Wann prägt ein Bestandteil den Gesamteindruck, wann hat er nur eine selbständig kennzeichnende Stellung?",
         kriterien=["Frage", "Voraussetzung", "Folge für Zeichenvergleich", "Art der Verwechslungsgefahr", "Leitentscheidung"],
         spalten=["Prägetheorie", "Selbständig kennzeichnende Stellung"],
         rows=[
             ["Welcher Bestandteil bestimmt den Gesamteindruck des mehrgliedrigen Zeichens?", "Behält die übernommene ältere Marke im jüngeren Kombinationszeichen ihre eigenständige Kennzeichnungsfunktion?"],
             ["Übrige Bestandteile treten so zurück, dass sie den Gesamteindruck nicht mitbestimmen", "Bestandteil dominiert nicht, wirkt aber neben den anderen Bestandteilen (z.B. neben einer Unternehmensbezeichnung) eigenständig; besondere Umstände"],
             ["Vergleich der älteren Marke mit dem prägenden Bestandteil", "Verkehr nimmt an, die Waren stammten aus verbundenen Unternehmen"],
             ["Unmittelbare Verwechslungsgefahr", "Verwechslungsgefahr im weiteren Sinne"],
             ["BGH Springende Raubkatze; Culinaria", "EuGH THOMSON LIFE; BGH INTERCONNECT, Culinaria"],
         ],
         merksatz="Prägung = ein Teil ist das Ganze. Selbständig kennzeichnende Stellung = ein Teil bleibt erkennbar fremd."),
    dict(id="d_markenmaessig_rechtserhaltend", label="Markenmäßige Benutzung (§ 14) vs. rechtserhaltende Benutzung (§ 26)",
         concepts=["markenmaessige_benutzung", "rechtserhaltende_benutzung"],
         frage="Was unterscheidet die rechtsverletzende von der rechtserhaltenden Benutzung?",
         kriterien=["Kontext", "Wer benutzt", "Kernfrage", "Zusätzliche Anforderungen", "Gemeinsamkeit"],
         spalten=["Markenmäßige (rechtsverletzende) Benutzung", "Rechtserhaltende Benutzung"],
         rows=[
             ["Verletzungstatbestand § 14 Abs. 2", "Benutzungszwang §§ 25, 26, 43, 49"],
             ["Der Dritte (Verletzer)", "Der Markeninhaber oder Lizenznehmer"],
             ["Beeinträchtigt die Benutzung eine Markenfunktion (Herkunftshinweis)?", "Wird die Marke ernsthaft, funktionsgemäß, im Inland, für die eingetragenen Waren und in unveränderter Form benutzt?"],
             ["Geschäftlicher Verkehr, ohne Zustimmung, Kollisionstatbestand", "Ernsthaftigkeit (Absatzmarkt), Fünfjahreszeitraum, § 26 Abs. 3 abweichende Form"],
             ["Beide setzen eine Benutzung als Herkunftshinweis (funktionsgemäß) voraus – rein beschreibende oder firmenmäßige Verwendung genügt in beiden Fällen nicht", ""],
         ],
         merksatz="Gleiche Grundfrage (Herkunftshinweis?), verschiedene Richtung: Eingriff des Dritten vs. Pflicht des Inhabers."),
    dict(id="d_schranken_23_24", label="§ 23 vs. § 24 MarkenG",
         concepts=["schranke_23", "erschoepfung"],
         frage="Wie unterscheiden sich die Schranken der §§ 23 und 24 MarkenG?",
         kriterien=["Gegenstand", "Fallgruppen", "Grenze", "Beweislast", "Typischer Fall"],
         spalten=["§ 23 (beschreibende/referierende Benutzung)", "§ 24 (Erschöpfung)"],
         rows=[
             ["Benutzung der Marke für eigene Waren des Dritten zur Information", "Weitervertrieb von Originalware des Markeninhabers"],
             ["Name/Anschrift, beschreibende Angaben, Bestimmungshinweis (Ersatzteile)", "Inverkehrbringen im EWR durch Inhaber oder mit Zustimmung"],
             ["Anständige Gepflogenheiten (Abs. 2)", "Berechtigte Gründe (Abs. 2): Veränderung, Rufschädigung"],
             ["Dritter für Voraussetzungen; Markeninhaber für Verstoß gegen anständige Gepflogenheiten", "Dritter; Umkehr bei Marktabschottungsgefahr (Van Doren)"],
             ["'passend für Vorwerk' (Staubsaugerfiltertüten)", "Parallelimport (BMS), Gebrauchtwarenhandel, Converse"],
         ],
         merksatz="§ 23 = fremde Marke für eigene Ware erwähnen. § 24 = fremde Marke auf fremder Originalware weiterverkaufen."),
    dict(id="d_verfall_nichtigkeit", label="Verfall (§ 49) vs. Nichtigkeit (§§ 50, 51)",
         concepts=["verfall", "nichtigkeit"],
         frage="Wie unterscheiden sich Verfall und Nichtigkeit einer Marke?",
         kriterien=["Grund", "Zeitpunkt des Mangels", "Wirkung", "Antragsbefugnis", "Zuständigkeit"],
         spalten=["Verfall (§ 49)", "Nichtigkeit absolut (§ 50)", "Nichtigkeit relativ (§ 51)"],
         rows=[
             ["Nachträglich: Nichtbenutzung, Gattungsbezeichnung, Täuschung, § 7", "Ursprünglich: Verstoß gegen §§ 3, 7, 8 bei Eintragung", "Ursprünglich: entgegenstehendes älteres Recht (§§ 9-13)"],
             ["Nach der Eintragung entstanden", "Bereits am Anmeldetag (bei Nr. 1-3 fortbestehend)", "Bereits am Anmeldetag"],
             ["Ex nunc (§ 52 Abs. 1): ab Antrag oder früherem Verfallszeitpunkt", "Ex tunc (§ 52 Abs. 2): Eintragung gilt als von Anfang an nicht erfolgt", "Ex tunc (§ 52 Abs. 2)"],
             ["Jedermann (Popularantrag)", "Jedermann (Popularantrag); Zehnjahresfrist bei Nr. 1-3", "Nur Inhaber des älteren Rechts"],
             ["DPMA (§ 53) oder Landgericht (§ 55)", "DPMA (§ 53)", "DPMA (§ 53) oder Landgericht (§ 55)"],
         ],
         merksatz="Verfall = später kaputt (ex nunc). Nichtigkeit = von Anfang an falsch (ex tunc)."),
    dict(id="d_marke_ukz_werktitel", label="Marke vs. Unternehmenskennzeichen vs. Werktitel",
         concepts=["marke", "unternehmenskennzeichen", "werktitel"],
         frage="Was kennzeichnen Marke, Unternehmenskennzeichen und Werktitel jeweils und wie entstehen sie?",
         kriterien=["Kennzeichnungsgegenstand", "Norm", "Entstehung", "Unterscheidungskraft", "Verletzungstatbestand", "Verwechslungsgefahr"],
         spalten=["Marke", "Unternehmenskennzeichen", "Werktitel"],
         rows=[
             ["Waren/Dienstleistungen (betriebliche Herkunft)", "Unternehmen/Geschäftsbetrieb", "Werk (Individualisierung des geistigen Produkts)"],
             ["§§ 3, 4, 14", "§§ 5 Abs. 2, 15", "§§ 5 Abs. 3, 15"],
             ["Eintragung, Verkehrsgeltung, Notorietät (§ 4)", "Benutzungsaufnahme (bei originärer Unterscheidungskraft), sonst Verkehrsgeltung", "Benutzungsaufnahme/Erscheinen (Titelschutzanzeige)"],
             ["Konkret für Waren; großzügig", "Namensfunktion; beschreibende Angaben nur mit Verkehrsgeltung", "Abgesenkter Maßstab bei Verkehrsgewöhnung (Zeitschriften), nicht bei Apps/Domains ohne Gewöhnung (wetter.de)"],
             ["§ 14 Abs. 2 Nr. 1-3", "§ 15 Abs. 2 (Verwechslungsgefahr), Abs. 3 (bekannt)", "§ 15 Abs. 2, Abs. 3"],
             ["Warenähnlichkeit × Kennzeichnungskraft × Zeichenähnlichkeit", "Branchennähe × Kennzeichnungskraft × Zeichenähnlichkeit", "Grundsätzlich nur unmittelbare Werkverwechslung; weiterer Sinn nur bei bekannten Titeln"],
         ],
         merksatz="Marke → Produkt, Unternehmenskennzeichen → Firma, Werktitel → Werk."),
    dict(id="d_widerspruch_nichtigkeitsklage", label="Widerspruch (§ 42) vs. Nichtigkeitsantrag wegen älterer Rechte (§ 51)",
         concepts=["widerspruch", "nichtigkeit"],
         frage="Wann Widerspruch, wann Nichtigkeitsverfahren?",
         kriterien=["Frist", "Geltend machbare Rechte", "Verfahren", "Beweismaß", "Instanzenzug"],
         spalten=["Widerspruch (§§ 42, 43)", "Nichtigkeit (§ 51 i.V.m. §§ 53, 55)"],
         rows=[
             ["Drei Monate nach Veröffentlichung der Eintragung", "Unbefristet (Grenze: Verwirkung § 51 Abs. 2, § 21)"],
             ["Nur ältere Marken, notorisch bekannte Marken, Benutzungsmarken/geschäftliche Bezeichnungen, Ursprungsbezeichnungen (§ 42 Abs. 2)", "Alle älteren Rechte der §§ 9-13 (auch Namensrecht, Urheberrecht, Design)"],
             ["Summarisches Registerverfahren vor dem DPMA", "Kontradiktorisches Verfahren vor DPMA (§ 53) oder Klage vor dem Landgericht (§ 55)"],
             ["Glaubhaftmachung, präsente Beweismittel", "Voller Beweis (Zivilprozess) bzw. Amtsermittlung mit Beibringung"],
             ["DPMA → BPatG (§ 66) → BGH (§ 83)", "DPMA → BPatG → BGH bzw. LG → OLG → BGH"],
         ],
         merksatz="Widerspruch = schnell, billig, aber nur für Kennzeichenrechte und nur drei Monate. Nichtigkeit = unbefristet, alle Rechte, volles Verfahren."),
    dict(id="d_ausnutzung_beeintraechtigung", label="Die vier Eingriffstatbestände des Bekanntheitsschutzes",
         concepts=["ausnutzung_unterscheidungskraft", "ausnutzung_wertschaetzung", "verwaesserung", "rufschaedigung"],
         frage="Welche vier Eingriffe erfasst § 14 Abs. 2 Nr. 3 MarkenG?",
         kriterien=["Was wird ausgenutzt/beeinträchtigt?", "Mechanismus", "Nachweis", "Beispiel"],
         spalten=["Ausnutzung der Unterscheidungskraft", "Ausnutzung der Wertschätzung", "Beeinträchtigung der Unterscheidungskraft", "Beeinträchtigung der Wertschätzung"],
         rows=[
             ["Aufmerksamkeit/Bekanntheit", "Ruf/Image (Qualität, Prestige)", "Kennzeichnungskraft/Einzigartigkeit", "Ruf/Image"],
             ["Trittbrettfahren: Aufmerksamkeit auf eigenes Angebot lenken", "Imagetransfer auf eigene Ware", "Verwässerung: Marke verliert Eignung als eindeutiger Herkunftshinweis", "Verunglimpfung: negative Assoziationen"],
             ["Gedankliche Verknüpfung + Nutzen für den Dritten", "Übertragung des Rufs; Sogwirkung (L'Oréal/Bellure)", "Änderung des Verbraucherverhaltens oder ernsthafte Gefahr (Intel)", "Unvereinbares Umfeld/minderwertige Ware"],
             ["'OTTO' für Caps; Springender Pudel", "Duftvergleichslisten; ÖKO-TEST-Siegel ohne Lizenz", "Massenhafte Verwendung ähnlicher Zeichen für beliebige Waren", "Luxusmarke auf Billig- oder anstößigem Produkt"],
         ],
         merksatz="Ausnutzen = der Dritte gewinnt. Beeinträchtigen = der Inhaber verliert. Jeweils bezogen auf Unterscheidungskraft oder Wertschätzung."),
    dict(id="d_taeter_stoerer", label="Täter vs. Teilnehmer vs. Störer",
         concepts=["stoererhaftung"],
         frage="Wer haftet wie für Markenverletzungen?",
         kriterien=["Voraussetzung", "Verschulden", "Rechtsfolgen", "Beispiel"],
         spalten=["Täter", "Teilnehmer", "Störer"],
         rows=[
             ["Eigene Verwirklichung des Tatbestands (auch Mittäter)", "Vorsätzliche Anstiftung/Beihilfe zu vorsätzlicher Haupttat", "Willentlicher, adäquat-kausaler Beitrag + Verletzung zumutbarer Prüfpflichten"],
             ["Für Unterlassung nicht; für Schadensersatz Vorsatz/Fahrlässigkeit", "Doppelter Vorsatz", "Kein Verschulden, aber Prüfpflichtverletzung"],
             ["Unterlassung, Schadensersatz, Auskunft, Vernichtung", "Wie Täter", "Nur Unterlassung (und Beseitigung), kein Schadensersatz"],
             ["Hersteller/Händler von Plagiaten", "Lieferant von Nachfüllware, der um Befüllung weiß (Tork)", "eBay/Amazon nach Hinweis auf klare Verletzung (Internet-Versteigerung II)"],
         ],
         merksatz="Störer haften nur auf Unterlassung und nur nach Hinweis."),
    dict(id="d_9_1_3_vs_14_2_3", label="§ 9 Abs. 1 Nr. 3 vs. § 14 Abs. 2 Nr. 3 MarkenG",
         concepts=["relative_schutzhindernis_bekannt", "bekannte_marke"],
         frage="Worin unterscheiden sich der Bekanntheitsschutz im Register (§ 9 Abs. 1 Nr. 3) und im Verletzungsprozess (§ 14 Abs. 2 Nr. 3)?",
         kriterien=["Funktion", "Verfahren", "Angreifer / Gegner", "Prüfungsgegenstand", "Zeitpunkt der Bekanntheit", "Beweismaß", "Rechtsfolge", "Gemeinsam"],
         spalten=["§ 9 Abs. 1 Nr. 3 (relatives Schutzhindernis)", "§ 14 Abs. 2 Nr. 3 (Verletzungstatbestand)"],
         rows=[
             ["Angriff auf den Bestand der jüngeren Registermarke", "Verbot der Benutzung eines Zeichens im Markt"],
             ["Widerspruch (§ 42) vor DPMA oder Nichtigkeitsverfahren (§ 51; DPMA § 53 / Landgericht § 55)", "Verletzungsklage vor dem Landgericht (§ 140), einstweilige Verfügung"],
             ["Nur Inhaber der älteren bekannten Marke gegen eine eingetragene jüngere Marke", "Markeninhaber (oder Lizenznehmer) gegen jeden Benutzer, auch ohne Registermarke"],
             ["Hypothetische Benutzung der jüngeren Marke für die eingetragenen Waren nach Registerlage ('würde')", "Konkrete, tatsächliche Benutzungshandlung in ihrem Marktumfeld"],
             ["Anmelde-/Prioritätstag der jüngeren Marke (§ 51 Abs. 3) und Fortbestehen bei der Entscheidung", "Zeitpunkt der Verletzungshandlung; gegen eingetragene jüngere Marke zusätzlich deren Prioritätstag (§ 22 Abs. 1 Nr. 1)"],
             ["Widerspruch: Glaubhaftmachung mit präsenten Beweismitteln; Nichtigkeit: Beweis / Amtsermittlung", "Voller Beweis nach ZPO (Umfragen, Marktdaten)"],
             ["Löschung (ex tunc, § 52 Abs. 2) ganz oder teilweise", "Unterlassung, Schadensersatz, Vernichtung, Auskunft (§§ 14 Abs. 5-7, 18, 19)"],
             ["Gleiche Voraussetzungen: Bekanntheit, Zeichenähnlichkeit, gedankliche Verknüpfung, vier Eingriffsalternativen, Unlauterkeit ohne rechtfertigenden Grund; seit MaMoG beide auch bei identischen/ähnlichen Waren", ""],
         ],
         merksatz="§ 9 fragt: Darf die Marke im Register stehen? § 14 fragt: Darf das Zeichen benutzt werden? Gleicher Tatbestand, andere Perspektive und anderer Zeitpunkt."),
    dict(id="d_bekanntheit_inland_union", label="Bekanntheit im Inland vs. Bekanntheit in der Union",
         concepts=["bekannte_marke", "bekanntheit_union"],
         frage="Welche Bekanntheit ist maßgeblich, wenn die ältere Marke eine deutsche Marke bzw. eine Unionsmarke ist?",
         kriterien=["Norm", "Räumlicher Bezug", "Wesentlicher Teil", "Zusatzvoraussetzung im Kollisionsgebiet", "Leitentscheidungen"],
         spalten=["Deutsche Marke / IR-Marke (DE)", "Unionsmarke / IR-Marke (EU)"],
         rows=[
             ["§ 9 Abs. 1 Nr. 3, § 14 Abs. 2 Nr. 3 MarkenG", "§ 125b Nr. 1 MarkenG, Art. 9 Abs. 2 lit. c, Art. 8 Abs. 5 UMV"],
             ["Bekanntheit im Inland (Bundesgebiet)", "Bekanntheit in der Union"],
             ["Ein wesentlicher Teil des Bundesgebiets genügt", "Ein wesentlicher Teil der Union; das Gebiet eines einzigen Mitgliedstaats kann genügen (PAGO)"],
             ["Keine", "Für Ausnutzung/Beeinträchtigung in Deutschland muss ein wirtschaftlich nicht unbedeutender Teil des deutschen Publikums die Marke kennen (Iron & Smith)"],
             ["EuGH General Motors; BGH TÜV II", "EuGH PAGO; EuGH Iron & Smith"],
         ],
         merksatz="Unionsmarke: bekannt in der Union reicht für den Tatbestand, aber ohne Bekanntheit beim deutschen Publikum keine Verknüpfung in Deutschland."),
    dict(id="d_marke_unionsmarke_irmarke", label="Deutsche Marke vs. Unionsmarke vs. IR-Marke",
         concepts=["marke", "unionsmarke", "ir_marke"],
         frage="Welche Normen gelten, wenn aus einer deutschen Marke, einer Unionsmarke oder einer IR-Marke vorgegangen wird?",
         kriterien=["Rechtsgrundlage", "Amt / Entstehung", "Zeitrang", "Verletzungstatbestand", "Annexansprüche", "Gericht", "Bekanntheit", "Rechtserhaltende Benutzung", "Beginn der Benutzungsschonfrist", "Angriff auf die Marke", "Besonderheiten"],
         spalten=["Deutsche Marke", "Unionsmarke", "IR-Marke (Benennung DE)"],
         rows=[
             ["MarkenG", "UMV (VO (EU) 2017/1001) + § 125b ff. MarkenG", "PMMA/MMA + §§ 107-125 MarkenG (v.a. §§ 112-117 über § 124)"],
             ["DPMA, Eintragung (§ 4 Nr. 1)", "EUIPO, Eintragung mit einheitlicher Wirkung in der EU", "WIPO auf Basis einer Basismarke; Schutzerstreckung auf DE durch Benennung"],
             ["Anmeldetag (§ 6 Abs. 2, § 33)", "Anmeldetag beim EUIPO; Seniorität nationaler Marken (Art. 39, 40 UMV)", "Tag der internationalen Registrierung bzw. nachträglichen Schutzerstreckung (§ 112)"],
             ["§ 14 Abs. 2 Nr. 1-3", "Art. 9 Abs. 2 lit. a-c UMV", "§ 14 Abs. 2 Nr. 1-3 (Wirkung wie deutsche Marke, § 112)"],
             ["§§ 14 Abs. 5-7, 18-19c", "Art. 130 UMV + §§ 14 Abs. 6, 7, 18-19c über § 125b Nr. 2", "§§ 14 Abs. 5-7, 18-19c; Einrede § 25 mit § 117"],
             ["Landgericht, Kennzeichenstreitsache (§ 140)", "Unionsmarkengericht (§ 125e, Art. 123 ff. UMV); Verbot grundsätzlich unionsweit", "Landgericht (§ 140)"],
             ["Im Inland", "In der Union (§ 125b Nr. 1; PAGO, Iron & Smith)", "Im Inland"],
             ["§ 26: im Inland", "Art. 18 UMV: in der Union, Grenzen der Mitgliedstaaten unbeachtlich (Leno Merken); § 125b Nr. 4, 5", "§ 26: im Inland"],
             ["Eintragung (§ 26 Abs. 5: ggf. Ende des Widerspruchsverfahrens)", "Eintragung der Unionsmarke (Art. 18 Abs. 1 UMV)", "Ablauf der Schutzverweigerungsfrist oder rechtskräftige Schutzgewährung (§ 115 Abs. 2, §§ 116, 117)"],
             ["Widerspruch § 42, Verfall § 49, Nichtigkeit §§ 50, 51", "Widerspruch Art. 46/Art. 8, Verfall Art. 58, Nichtigkeit Art. 59, 60 UMV (EUIPO) oder Widerklage Art. 128", "Schutzverweigerung § 113, Widerspruch § 114, Schutzentziehung § 115; 'central attack' auf die Basismarke (Art. 6 PMMA)"],
             ["–", "Umwandlung in nationale Anmeldungen (Art. 139 ff. UMV, § 125d); Koexistenz mit nationalen Marken", "Benennung EU = Unionsmarke (Art. 189 ff. UMV); Umwandlung § 125"],
         ],
         merksatz="Deutsche Marke: MarkenG pur. Unionsmarke: UMV plus Brücke § 125b. IR-Marke: wie deutsche Marke (§ 112), aber eigene Fristen (§ 115 Abs. 2) und Schutzverweigerung statt Löschung."),
]

DISTINCTION_INDEX = {d["id"]: d for d in DISTINCTIONS}
