# -*- coding: utf-8 -*-
"""IPWiki-Artikel (www.ipwiki.de) zum Markenrecht.

Die Seiten konnten aus dieser Umgebung nicht direkt heruntergeladen werden (Netzwerk-
Egress zu ipwiki.de gesperrt). Die Liste wurde per Websuche über die Domain ipwiki.de
ermittelt; `summary` gibt den in den Suchergebnissen sichtbaren Kerninhalt wieder.
URL-Schema: https://www.ipwiki.de/<seite>
"""

IPWIKI_BASE = "https://www.ipwiki.de/"

IPWIKI = [
    dict(page="markenrecht:markenrecht", title="Markenrecht (Übersicht)", summary="Einstiegsseite des IPWiki zum Markenrecht mit Verweisen auf MarkenG, Unionsmarke und Markenrechtsrichtlinie."),
    dict(page="markenrecht:markengesetz", title="Markengesetz", summary="Übersicht über Aufbau und Inhalt des MarkenG."),
    dict(page="markenrecht:pruefung", title="Prüfung (Eintragungsverfahren)", summary="Prüfung der Anmeldung durch das DPMA auf Anmeldeerfordernisse und absolute Schutzhindernisse (§§ 36, 37 MarkenG)."),
    dict(page="markenrecht:markenfaehigkeit", title="Markenfähigkeit", summary="Ein Zeichen muss über die Grundform der Ware hinausreichende Elemente aufweisen; variablen Marken mit unbestimmter Zahl von Erscheinungsformen fehlt die Markenfähigkeit. Bedeutung der Darstellbarkeit: festgelegte Form, Registereintragung, Information der Allgemeinheit."),
    dict(page="markenrecht:einheitlichkeit", title="Einheitlichkeit des Zeichens", summary="Anforderung, dass das Zeichen als einheitlicher Schutzgegenstand bestimmbar ist."),
    dict(page="markenrecht:warenformmarken", title="Warenformmarken", summary="Schutz einer dreidimensionalen Formmarke bezieht sich auf die konkrete Ausgestaltung der formgebenden Merkmale, nicht auf eine abstrakte Grundform."),
    dict(page="markenrecht:technisch_bedingte_warenformen", title="Technisch bedingte Warenformen", summary="§ 3 Abs. 2 Nr. 2 MarkenG: Ausschluss von Formen, deren wesentliche Merkmale zur Erreichung einer technischen Wirkung erforderlich sind; auch bei nichttechnischen Produkten (Bodendübel, Traubenzuckertäfelchen)."),
    dict(page="markenrecht:freihaltebeduerfnis_an_produktformen", title="Freihaltebedürfnis an Produktformen", summary="Das unüberwindbare Freihaltebedürfnis an Produktformen (§ 3 Abs. 2) ist systematisch ein absolutes Schutzhindernis, das nicht durch Verkehrsdurchsetzung überwunden werden kann."),
    dict(page="markenrecht:bildmarken", title="Bildmarken", summary="Schutzfähigkeit und Unterscheidungskraft von Bildzeichen."),
    dict(page="markenrecht:absolute_schutzhindernisse", title="Absolute Schutzhindernisse", summary="Übersicht der Eintragungshindernisse des § 8 Abs. 2 MarkenG."),
    dict(page="markenrecht:unterscheidungskraft", title="Unterscheidungskraft", summary="Konkrete Eignung, vom Verkehr als Unterscheidungsmittel aufgefasst zu werden; Hauptfunktion Herkunftsgarantie; fehlt nur bei engem beschreibenden Bezug; großzügiger Maßstab auch für Wortfolgen; 'jegliche' bedeutet nicht, dass jede Marke unterscheidungskräftig ist."),
    dict(page="markenrecht:schutzhindernis_der_fehlenden_unterscheidungskraft", title="Schutzhindernis der fehlenden Unterscheidungskraft", summary="Systematik und Prüfung des § 8 Abs. 2 Nr. 1 MarkenG."),
    dict(page="markenrecht:beurteilung_der_unterscheidungskraft_eines_angemeldeten_zeichens", title="Beurteilung der Unterscheidungskraft eines angemeldeten Zeichens", summary="Maßstab (Durchschnittsverbraucher), Zeitpunkt, Berücksichtigung der Verwendungsformen."),
    dict(page="markenrecht:unterscheidungskraft_von_wortfolgen", title="Unterscheidungskraft von Wortfolgen", summary="Keine strengeren Anforderungen als bei anderen Wortmarken; fehlt nur bei beschreibenden Angaben oder allgemeinen Werbeaussagen."),
    dict(page="markenrecht:fehlende_unterscheidungskraft_aufgrund_eines_beschreibended_begriffsinhaltes", title="Fehlende Unterscheidungskraft aufgrund beschreibenden Begriffsinhalts", summary="Fallgruppe des im Vordergrund stehenden beschreibenden Begriffsinhalts."),
    dict(page="markenrecht:unterscheidungskraft_einer_farbmarke", title="Unterscheidungskraft einer Farbmarke", summary="Abstrakte Farben sind originär regelmäßig nicht unterscheidungskräftig (Libertel)."),
    dict(page="markenrecht:unterscheidungskraft_einer_warenform", title="Unterscheidungskraft einer Warenform", summary="Erhebliche Abweichung von der Branchenüblichkeit erforderlich."),
    dict(page="markenrecht:freihaltebeduerfnis_an_beschreibenden_angaben", title="Freihaltebedürfnis an beschreibenden Angaben", summary="§ 8 Abs. 2 Nr. 2 MarkenG: Allgemeininteresse an der freien Verwendbarkeit von Merkmalsangaben."),
    dict(page="markenrecht:verkehrsdurchsetzung", title="Verkehrsdurchsetzung", summary="Ein erheblicher Teil der beteiligten Verkehrskreise muss die Marke einem bestimmten Marktteilnehmer zuordnen; Beibringungsgrundsatz für die Tatsachen der Verkehrsdurchsetzung."),
    dict(page="markenrecht:verkehrsdurchsetzungsgrad", title="Verkehrsdurchsetzungsgrad", summary="Erforderliche Zuordnungsquote (Richtwert 50 %)."),
    dict(page="markenrecht:feststellung_der_verkehrsdurchsetzung", title="Feststellung der Verkehrsdurchsetzung", summary="Nachweis durch demoskopische Gutachten und sonstige Umstände."),
    dict(page="markenrecht:verkehrsdurchsetzung_einer_farbmarke", title="Verkehrsdurchsetzung einer Farbmarke", summary="Langenscheidt-Gelb, Nivea-Blau, Sparkassen-Rot."),
    dict(page="markenrecht:verkehrsdurchsetzung_eines_werktitels", title="Verkehrsdurchsetzung eines Werktitels", summary="Werktitel und Verkehrsgeltung."),
    dict(page="markenrecht:zeitrangverschiebung_bei_verkehrsdurchsetzung_nach_anmeldung_der_marke", title="Zeitrangverschiebung bei Verkehrsdurchsetzung nach Anmeldung", summary="Folgen einer erst nach dem Anmeldetag eingetretenen Verkehrsdurchsetzung."),
    dict(page="markenrecht:verkehrsgeltung", title="Verkehrsgeltung", summary="Entstehung der Benutzungsmarke nach § 4 Nr. 2 MarkenG."),
    dict(page="markenrecht:entstehung_des_markenschutzes_durch_notorische_bekanntheit", title="Entstehung des Markenschutzes durch notorische Bekanntheit", summary="§ 4 Nr. 3 MarkenG, Art. 6bis PVÜ."),
    dict(page="markenrecht:boesglaeubige_markenanmeldung", title="Bösgläubige Markenanmeldung", summary="Fallgruppen der Bösgläubigkeit (Sperrmarke, Störung fremden Besitzstands)."),
    dict(page="markenrecht:boesglaeubige_markenanmeldung_als_nichtigkeitsgrund", title="Bösgläubige Markenanmeldung als Nichtigkeitsgrund", summary="Löschung nach § 50 i.V.m. § 8 Abs. 2 Nr. 14; im Löschungsverfahren muss die Bösgläubigkeit nicht ersichtlich sein."),
    dict(page="markenrecht:funktionen_der_marke", title="Funktionen der Marke", summary="Herkunfts-, Garantie-, Werbe-, Kommunikations- und Investitionsfunktion."),
    dict(page="markenrecht:herkunftsfunktion", title="Herkunftsfunktion", summary="Der Markenschutz richtet sich gegen die Beeinträchtigung der Herkunftsfunktion, nicht gegen die Übernahme technischer oder ästhetischer Gestaltungselemente."),
    dict(page="markenrecht:benutzung_im_geschaeftlichen_verkehr", title="Benutzung im geschäftlichen Verkehr", summary="Tätigkeit im Zusammenhang mit einer auf wirtschaftlichen Vorteil gerichteten Tätigkeit, nicht im privaten Bereich; keine hohen Anforderungen."),
    dict(page="markenrecht:markenmaessige_benutzung", title="Markenmäßige Benutzung", summary="Rechtsverletzende Benutzung setzt Beeinträchtigung der Markenfunktionen, insbesondere der Herkunftsfunktion, voraus."),
    dict(page="markenrecht:markenmaessige_benutzung_durch_firmenmaessigen_gebrauch", title="Markenmäßige Benutzung durch firmenmäßigen Gebrauch", summary="Firmengebrauch ist zugleich markenmäßig, wenn die Herkunftsfunktion beeinträchtigt werden kann."),
    dict(page="markenrecht:firmenmaessiger_gebrauch", title="Firmenmäßiger Gebrauch", summary="Benutzung als Unternehmensbezeichnung vs. Benutzung für Waren."),
    dict(page="markenrecht:rechte_des_markeninhabers", title="Rechte des Markeninhabers", summary="Ausschließliches Recht nach § 14 Abs. 1 MarkenG."),
    dict(page="markenrecht:verbietungsrechte", title="Verbietungsrechte", summary="Die drei Kollisionstatbestände des § 14 Abs. 2 MarkenG."),
    dict(page="markenrecht:verbot_identischer_benutzung", title="Verbot identischer Benutzung", summary="§ 14 Abs. 2 Nr. 1: Unterlassungsanspruch bei Doppelidentität."),
    dict(page="markenrecht:verbot_verwechselbarer_benutzung", title="Verbot verwechselbarer Benutzung", summary="§ 14 Abs. 2 Nr. 2: Beurteilung unter Berücksichtigung aller Umstände des Einzelfalls."),
    dict(page="markenrecht:markenverletzung", title="Markenverletzung", summary="Voraussetzungen und Ansprüche bei Verletzung; markenmäßige Benutzung; Inlandsbezug."),
    dict(page="markenrecht:verwechslungsgefahr", title="Verwechslungsgefahr", summary="Wechselwirkung von Zeichenähnlichkeit, Waren-/Dienstleistungsähnlichkeit und Kennzeichnungskraft; je höher die Kennzeichnungskraft, desto größer die Verwechslungsgefahr."),
    dict(page="markenrecht:verwechslungsgefahr_mit_einer_aelteren_marke", title="Verwechslungsgefahr mit einer älteren Marke", summary="§ 9 Abs. 1 Nr. 2 MarkenG im Widerspruchs-/Nichtigkeitsverfahren."),
    dict(page="markenrecht:verwechslungsgefahr_bei_unternehmenskennzeichen", title="Verwechslungsgefahr bei Unternehmenskennzeichen", summary="Branchennähe, Kennzeichnungskraft, Zeichenähnlichkeit (§ 15 Abs. 2)."),
    dict(page="markenrecht:verwechslungsgefahr_bei_werktiteln", title="Verwechslungsgefahr bei Werktiteln", summary="Grundsätzlich nur unmittelbare Werkverwechslung."),
    dict(page="markenrecht:eu:verwechslungsgefahr", title="Verwechslungsgefahr (Unionsmarke)", summary="Art. 8 Abs. 1 lit. b, Art. 9 UMV."),
    dict(page="markenrecht:kennzeichnungskraft", title="Kennzeichnungskraft", summary="Marken mit hoher originärer oder erworbener Kennzeichnungskraft genießen umfassenderen Schutz als Marken mit geringer Kennzeichnungskraft."),
    dict(page="markenrecht:originaere_kennzeichnungskraft", title="Originäre Kennzeichnungskraft", summary="Kennzeichnungskraft von Haus aus aufgrund der Eigenart des Zeichens."),
    dict(page="markenrecht:zeichenaehnlichkeit", title="Zeichenähnlichkeit", summary="Klang, Bild, Sinngehalt; Gesamteindruck."),
    dict(page="markenrecht:gesamteindruck", title="Gesamteindruck", summary="Maßgeblichkeit des Gesamteindrucks; Prägung durch Bestandteile."),
    dict(page="markenrecht:praegetheorie", title="Prägetheorie", summary="Unmittelbare Verwechslungsgefahr durch prägenden Bestandteil; Anwendung vor allem bei klanglicher Verwechslungsgefahr mehrteiliger Wort- und Wort-Bild-Marken; selbständig kennzeichnende Stellung (Thomson Life)."),
    dict(page="markenrecht:waren-_und_dienstleistungsaehnlichkeit", title="Waren- und Dienstleistungsähnlichkeit", summary="Faktoren der Ähnlichkeit (Canon)."),
    dict(page="markenrecht:bekannte_marke", title="Bekannte Marke", summary="Bekanntheit bei einem bedeutenden Teil des Publikums; Faktoren."),
    dict(page="markenrecht:bekanntheitsschutz", title="Bekanntheitsschutz", summary="Umfassende Interessenabwägung; gedankliche Verknüpfung erforderlich; keine Beeinträchtigung der Herkunftsfunktion nötig; unlautere Ausnutzung bei Sogwirkung ohne eigene Anstrengung."),
    dict(page="markenrecht:unlautere_ausnutzung_der_unterscheidungskraft_einer_bekannten_marke", title="Unlautere Ausnutzung der Unterscheidungskraft einer bekannten Marke", summary="Trittbrettfahren / Aufmerksamkeitsausbeutung."),
    dict(page="markenrecht:kollission_mit_einer_aelteren_bekannten_marke", title="Kollision mit einer älteren bekannten Marke", summary="§ 9 Abs. 1 Nr. 3 MarkenG."),
    dict(page="markenrecht:schranken_des_schutzes", title="Schranken des Schutzes", summary="Übersicht §§ 20-26 MarkenG."),
    dict(page="markenrecht:schranken_des_markenschutzes", title="Schranken des Markenschutzes", summary="§§ 23, 24 MarkenG."),
    dict(page="markenrecht:schutzschranken", title="Schutzschranken", summary="Einwendungen gegen Ansprüche aus der Marke."),
    dict(page="markenrecht:recht_zur_benutzung_beschreibender_angaben", title="Recht zur Benutzung beschreibender Angaben", summary="§ 23 Abs. 1 Nr. 2 MarkenG."),
    dict(page="markenrecht:recht_zur_benutzung_von_notwendigen_bestimmungsangaben", title="Recht zur Benutzung von notwendigen Bestimmungsangaben", summary="§ 23 Abs. 1 Nr. 3 MarkenG: Zubehör, Ersatzteile (Gillette, Staubsaugerfiltertüten)."),
    dict(page="markenrecht:erschoepfung", title="Erschöpfung", summary="§ 24 MarkenG: Ausgleich zwischen Markenschutz und Warenverkehrsfreiheit."),
    dict(page="markenrecht:erschoepfung_des_markenrechts", title="Erschöpfung des Markenrechts", summary="Voraussetzungen und Beweislast (stüssy II, Converse)."),
    dict(page="markenrecht:umfang_der_erschoepfung", title="Umfang der Erschöpfung", summary="Erschöpfung für das konkrete Warenstück; Werbung des Wiederverkäufers."),
    dict(page="markenrecht:inverkehrbringen_der_markenware", title="Inverkehrbringen der Markenware", summary="Begriff des Inverkehrbringens im EWR."),
    dict(page="markenrecht:ausnahmen_vom_erschoepfungsgrundsatz", title="Ausnahmen vom Erschöpfungsgrundsatz", summary="§ 24 Abs. 2: Veränderung oder Verschlechterung der Ware, berechtigte Gründe."),
    dict(page="markenrecht:benutzungszwang", title="Benutzungszwang", summary="Obliegenheit zur Benutzung nach Ablauf der Schonfrist."),
    dict(page="markenrecht:rechtserhaltende_benutzung", title="Rechtserhaltende Benutzung", summary="Ernsthafte Benutzung zur Gewinnung oder Erhaltung von Marktanteilen; funktionsgemäße Benutzung."),
    dict(page="markenrecht:voraussetzungen_der_rechtserhaltenden_benutzung", title="Voraussetzungen der rechtserhaltenden Benutzung", summary="Inland, ernsthaft, für die eingetragenen Waren, durch den Inhaber oder mit Zustimmung."),
    dict(page="markenrecht:benutzung_einer_marke_in_abweichender_form", title="Benutzung einer Marke in abweichender Form", summary="§ 26 Abs. 3: kennzeichnender Charakter darf nicht verändert werden."),
    dict(page="markenrecht:rechtserhaltende_benutzung_einer_dienstleistungsmarke", title="Rechtserhaltende Benutzung einer Dienstleistungsmarke", summary="Besonderheiten bei Dienstleistungen."),
    dict(page="markenrecht:benutzungsschonfrist", title="Benutzungsschonfrist", summary="Fünf Jahre ab Eintragung."),
    dict(page="markenrecht:nichtbenutzungseinrede", title="Nichtbenutzungseinrede", summary="§§ 25, 43 Abs. 1 MarkenG."),
    dict(page="markenrecht:markenbenutzung", title="Markenbenutzung", summary="Übersicht zu Benutzungsformen."),
    dict(page="markenrecht:verfall", title="Verfall", summary="§ 49 MarkenG."),
    dict(page="markenrecht:verfall_wegen_nichtbenutzung", title="Verfall wegen Nichtbenutzung", summary="Löschung nach fünf Jahren ununterbrochener Nichtbenutzung."),
    dict(page="markenrecht:nichtigkeit_wegen_absoluter_schutzhindernisse", title="Nichtigkeit wegen absoluter Schutzhindernisse", summary="§ 50 MarkenG."),
    dict(page="markenrecht:voraussetzungen_einer_loeschung_wegen_absoluter_schutzhindernisse", title="Voraussetzungen einer Löschung wegen absoluter Schutzhindernisse", summary="Anmeldezeitpunkt, Fortbestehen, Feststellungslast."),
    dict(page="markenrecht:loeschung_aufgrund_verfalls_oder_nichtigkeit", title="Löschung aufgrund Verfalls oder Nichtigkeit", summary="Verfahren nach §§ 53, 55; Antrag beim DPMA."),
    dict(page="markenrecht:loeschungsverfahren_vor_den_ordentlichen_gerichten", title="Löschungsverfahren vor den ordentlichen Gerichten", summary="§ 55 MarkenG."),
    dict(page="markenrecht:widerspruch_gegen_den_antrag_auf_loeschung_wegen_verfalls_oder_nichtigkeit", title="Widerspruch gegen den Löschungsantrag", summary="§ 53 Abs. 4, 5 MarkenG."),
    dict(page="markenrecht:einwand_der_unlauterkeit", title="Einwand der Unlauterkeit", summary="Rechtsmissbrauch bei Geltendmachung von Markenrechten."),
    dict(page="markenrecht:widerspruchsverfahren", title="Widerspruchsverfahren", summary="§§ 42, 43 MarkenG."),
    dict(page="markenrecht:uebergangsvorschriften", title="Übergangsvorschriften", summary="§§ 152 ff. MarkenG."),
    dict(page="markenrecht:geschaeftliche_bezeichnungen", title="Geschäftliche Bezeichnungen", summary="§ 5 Abs. 1: Unternehmenskennzeichen und Werktitel."),
    dict(page="markenrecht:unternehmenskennzeichen", title="Unternehmenskennzeichen", summary="Name, Firma, besondere Bezeichnung eines Geschäftsbetriebs; ausschließliches Recht nach § 15 Abs. 1; daneben Namensrecht § 12 BGB."),
    dict(page="markenrecht:entstehen_der_rechte_aus_einem_unternehmenskennzeichen", title="Entstehen der Rechte aus einem Unternehmenskennzeichen", summary="Benutzungsaufnahme, Unterscheidungskraft, Verkehrsgeltung."),
    dict(page="markenrecht:schutz_von_firmenschlagworten_-bestandteilen_und_-abkuerzungen", title="Schutz von Firmenschlagworten, -bestandteilen und -abkürzungen", summary="Selbständiger Schutz unterscheidungskräftiger Firmenbestandteile."),
    dict(page="markenrecht:domainnamen_als_unternehmenskennzeichen", title="Domainnamen als Unternehmenskennzeichen", summary="Schutz durch Benutzung im geschäftlichen Verkehr (soco.de)."),
    dict(page="markenrecht:verletzung_von_unternehmenskennzeichen", title="Verletzung von Unternehmenskennzeichen", summary="§ 15 Abs. 2 MarkenG."),
    dict(page="markenrecht:werktitel", title="Werktitel", summary="Namen oder besondere Bezeichnungen von Druckschriften, Film-, Ton-, Bühnenwerken oder vergleichbaren Werken; Individualisierung des Werks."),
    dict(page="markenrecht:werktitelschutz", title="Werktitelschutz", summary="Entstehung und Umfang des Titelschutzes."),
    dict(page="markenrecht:kennzeichenrechtlicher_werkbegriff", title="Kennzeichenrechtlicher Werkbegriff", summary="Weiter als der urheberrechtliche Werkbegriff; auch Apps und Software."),
    dict(page="markenrecht:lizenzanalogie", title="Lizenzanalogie", summary="Schadensberechnung nach angemessener Lizenzgebühr (BTK)."),
    dict(page="markenrecht:markenrechtsrichtlinie:rechte_aus_der_marke", title="Markenrechtsrichtlinie: Rechte aus der Marke", summary="Art. 10 RL (EU) 2015/2436."),
]

IPWIKI_INDEX = {i["page"]: i for i in IPWIKI}
