# -*- coding: utf-8 -*-
"""Prüfungsschemata (Klausur-/Gutachtenaufbau) als Bäume.

Jeder Schritt: dict(label, text?, concepts=[...], norms=[...], cases=[...], children=[...]).
Begriffe in `concepts` werden in der HTML-Ansicht inline (aufklappbar) angezeigt.
"""

def step(label, text="", concepts=None, norms=None, cases=None, children=None, hinweis=""):
    return dict(label=label, text=text, concepts=concepts or [], norms=norms or [],
                cases=cases or [], children=children or [], hinweis=hinweis)


SCHEMATA = [
    dict(
        id="schema_markenverletzung",
        label="Unterlassungsanspruch wegen Markenverletzung (§ 14 Abs. 2, 5 MarkenG)",
        kategorie="Verletzung",
        beschreibung="Zentrales Klausurschema: Anspruch des Markeninhabers gegen den Verletzer auf Unterlassung. Schadensersatz (§ 14 Abs. 6) und Annexansprüche (§§ 18, 19) bauen auf dem gleichen Tatbestand auf.",
        norms=["§ 14"],
        steps=[
            step("A. Anspruchsgrundlage", "§ 14 Abs. 5 S. 1 i.V.m. Abs. 2 Nr. 1, 2 oder 3 MarkenG.", norms=["§ 14 Abs. 5"]),
            step("B. Schutzfähige Marke des Anspruchstellers", concepts=["marke", "entstehung_markenschutz", "aktivlegitimation"], children=[
                step("1. Bestehen des Markenschutzes", "Eintragung (§ 4 Nr. 1), Verkehrsgeltung (§ 4 Nr. 2) oder notorische Bekanntheit (§ 4 Nr. 3). Bei der eingetragenen Marke ist das Verletzungsgericht an die Eintragung gebunden – absolute Schutzhindernisse werden nicht geprüft (Einwand nur über Löschungsverfahren/Widerklage, ggf. Aussetzung).",
                     concepts=["entstehung_markenschutz", "verkehrsgeltung", "notorische_bekanntheit"], norms=["§ 4"], cases=["bgh_langenscheidt_gelb"]),
                step("2. Aktivlegitimation", "Markeninhaber (§ 28 Abs. 1 Vermutung) oder Lizenznehmer mit Zustimmung (§ 30 Abs. 3).", concepts=["aktivlegitimation", "lizenz"], norms=["§ 28", "§ 30 Abs. 3"]),
                step("3. Zeitrang / Priorität", "Die Klagemarke muss gegenüber dem angegriffenen Zeichen prioritätsälter sein (§ 6); der Beklagte kann ein eigenes älteres Recht einwenden.", concepts=["prioritaet"], norms=["§ 6"]),
            ]),
            step("C. Verletzungshandlung (§ 14 Abs. 2)", children=[
                step("1. Benutzung im geschäftlichen Verkehr", concepts=["geschaeftlicher_verkehr"], norms=["§ 14 Abs. 2"]),
                step("2. Ohne Zustimmung des Markeninhabers", "Zustimmung z.B. durch Lizenz (§ 30); Grenzen des § 30 Abs. 2 beachten.", concepts=["lizenz"]),
                step("3. Benutzungshandlung", "Benutzung für Waren/Dienstleistungen, insbesondere die Handlungen des § 14 Abs. 3 (Anbringen, Anbieten, Inverkehrbringen, Ein-/Ausfuhr, Verwendung in Geschäftspapieren und Werbung, Verwendung als Handelsname) und Vorbereitungshandlungen nach § 14 Abs. 4.", norms=["§ 14 Abs. 3", "§ 14 Abs. 4"]),
                step("4. Markenmäßige (rechtsverletzende) Benutzung", "Beeinträchtigung einer Markenfunktion, insbesondere der Herkunftsfunktion: Der Verkehr versteht das Zeichen als Herkunftshinweis. Abgrenzung zur rein beschreibenden, dekorativen oder firmenmäßigen Verwendung.",
                     concepts=["markenmaessige_benutzung", "herkunftsfunktion", "markenfunktionen", "firmenmaessiger_gebrauch", "keyword_advertising"],
                     cases=["eugh_arsenal", "bgh_opel_blitz_ii", "bgh_sam", "bgh_damen_hose_mo", "bgh_fruehstuecks_drink_ii", "eugh_google_france"]),
                step("5. Kollisionstatbestand", children=[
                    step("a) § 14 Abs. 2 Nr. 1 – Doppelidentität", "Zeichenidentität + Waren-/Dienstleistungsidentität. Keine Verwechslungsgefahr erforderlich; Beeinträchtigung irgendeiner Markenfunktion genügt.",
                         concepts=["doppelidentitaet", "markenfunktionen"], norms=["§ 14 Abs. 2 Nr. 1"], cases=["eugh_loreal_bellure", "bgh_kuehlergrill", "bgh_grosse_inspektion"]),
                    step("b) § 14 Abs. 2 Nr. 2 – Verwechslungsgefahr", "Zeichenidentität/-ähnlichkeit + Waren-/Dienstleistungsidentität/-ähnlichkeit + Verwechslungsgefahr (siehe eigenes Schema).",
                         concepts=["verwechslungsgefahr", "wechselwirkung"], norms=["§ 14 Abs. 2 Nr. 2"], cases=["eugh_sabel_puma", "eugh_canon", "bgh_culinaria"]),
                    step("c) § 14 Abs. 2 Nr. 3 – Bekanntheitsschutz", "Bekannte Marke + Zeichenidentität/-ähnlichkeit + gedankliche Verknüpfung + Ausnutzung/Beeinträchtigung der Unterscheidungskraft oder Wertschätzung + ohne rechtfertigenden Grund in unlauterer Weise (siehe eigenes Schema).",
                         concepts=["bekannte_marke", "gedankliche_verknuepfung", "unlauterkeit"], norms=["§ 14 Abs. 2 Nr. 3"], cases=["bgh_otto_cap", "bgh_lila_postkarte"]),
                ]),
            ]),
            step("D. Keine Schranken / Einwendungen", children=[
                step("1. § 23 – Namen, beschreibende Angaben, Bestimmungshinweis", concepts=["schranke_23", "ersatzteilhinweis", "gleichnamigkeit"], norms=["§ 23"], cases=["eugh_gillette", "bgh_staubsaugerfiltertueten", "bgh_kuehlergrill"]),
                step("2. § 24 – Erschöpfung", concepts=["erschoepfung", "berechtigte_gruende", "beweislast_erschoepfung"], norms=["§ 24"], cases=["eugh_van_doren", "bgh_stuessy_ii", "eugh_bms"]),
                step("3. § 25 – Einrede der Nichtbenutzung", "Nach Ablauf der Benutzungsschonfrist: Inhaber muss rechtserhaltende Benutzung nachweisen (§ 26).", concepts=["nichtbenutzungseinrede", "rechtserhaltende_benutzung", "benutzungsschonfrist"], norms=["§ 25", "§ 26"], cases=["bgh_voodoo"]),
                step("4. § 21 – Verwirkung; § 22 – Bestandskraft jüngerer Marke", "§ 22: keine Untersagung einer eingetragenen jüngeren Marke, wenn die Klagemarke an deren Prioritätstag noch nicht bekannt war, löschungsreif war oder noch keine Verwechslungsgefahr bestand.", concepts=["verwirkung", "koexistenz_22"], norms=["§ 21", "§ 22"], cases=["bgh_hard_rock_cafe"]),
                step("5. Älteres Recht des Beklagten (§ 6) / Löschungsreife der Klagemarke", "Einrede des besseren Zeitrangs; Löschungsreife der Klagemarke wegen Verfalls (§ 49) oder Nichtigkeit (§§ 50, 51) – im Verletzungsprozess über Widerklage bzw. § 52.", concepts=["prioritaet", "verfall", "nichtigkeit"], norms=["§ 6", "§ 49", "§ 50", "§ 51", "§ 52"]),
                step("6. Verjährung (§ 20)", concepts=["verjaehrung"], norms=["§ 20"]),
            ]),
            step("E. Rechtsfolge: Unterlassung (§ 14 Abs. 5)", "Wiederholungsgefahr (vermutet nach Verletzung; Wegfall nur durch strafbewehrte Unterlassungserklärung) oder Erstbegehungsgefahr (§ 14 Abs. 5 S. 2). Kein Verschulden erforderlich. Passivlegitimation: Täter, Teilnehmer, Störer.",
                 concepts=["unterlassungsanspruch", "stoererhaftung"], norms=["§ 14 Abs. 5"], cases=["bgh_internet_versteigerung_ii", "bgh_kinderhochstuehle"]),
            step("F. Weitere Ansprüche", children=[
                step("Schadensersatz (§ 14 Abs. 6)", "Zusätzlich: Verschulden (Vorsatz/Fahrlässigkeit). Dreifache Schadensberechnung: konkreter Schaden, Verletzergewinn, Lizenzanalogie. Haftung für Angestellte/Beauftragte (§ 14 Abs. 7).", concepts=["schadensersatz", "lizenzanalogie"], norms=["§ 14 Abs. 6", "§ 14 Abs. 7"], cases=["bgh_btk"]),
                step("Vernichtung/Rückruf (§ 18), Auskunft (§ 19), Vorlage (§ 19a), Urteilsbekanntmachung (§ 19c)", concepts=["vernichtung_auskunft"], norms=["§ 18", "§ 19", "§ 19a", "§ 19c"]),
                step("Bereicherung (§ 812 BGB), GoA; Ansprüche aus anderen Vorschriften (§ 19d): UWG, § 12 BGB", concepts=["verhaeltnis_uwg"], norms=["§ 19d", "§ 2"]),
            ]),
        ],
    ),
    dict(
        id="schema_verwechslungsgefahr",
        label="Verwechslungsgefahr (§ 14 Abs. 2 Nr. 2 / § 9 Abs. 1 Nr. 2 MarkenG)",
        kategorie="Verletzung",
        beschreibung="Umfassende Beurteilung aller Umstände des Einzelfalls unter Berücksichtigung der Wechselwirkung zwischen Waren-/Dienstleistungsähnlichkeit, Kennzeichnungskraft der älteren Marke und Zeichenähnlichkeit.",
        norms=["§ 14 Abs. 2 Nr. 2", "§ 9 Abs. 1 Nr. 2"],
        steps=[
            step("1. Maßgebliche Verkehrskreise und Aufmerksamkeitsgrad", "Normal informierter, angemessen aufmerksamer und verständiger Durchschnittsverbraucher der konkreten Waren; bei gespaltener Verkehrsauffassung genügt Verwechslungsgefahr in einer Gruppe.",
                 concepts=["durchschnittsverbraucher"], cases=["eugh_lloyd", "bgh_maalox"]),
            step("2. Waren-/Dienstleistungsidentität oder -ähnlichkeit", "Registerlage der Klagemarke vs. konkret benutzte Waren. Faktoren: Art, Verwendungszweck, Nutzung, Konkurrenz-/Ergänzungsverhältnis, Herstellungsstätten, Vertriebswege. Bei absoluter Unähnlichkeit: Ende der Prüfung (ggf. Nr. 3).",
                 concepts=["warenaehnlichkeit"], cases=["eugh_canon", "bgh_desperados"]),
            step("3. Kennzeichnungskraft der älteren Marke", "Originäre Kennzeichnungskraft (Eigenart des Zeichens; beschreibende Anklänge schwächen) → Steigerung durch Benutzung/Bekanntheit → Schwächung durch Drittzeichen. Ergebnis: sehr gering / gering / durchschnittlich / erhöht / sehr hoch. Bei verkehrsdurchgesetzten Marken: regelmäßig durchschnittlich.",
                 concepts=["kennzeichnungskraft", "verkehrsdurchsetzung"], cases=["bgh_culinaria", "bgh_kinder_ii", "bgh_lacoste_krokodil"]),
            step("4. Zeichenidentität oder -ähnlichkeit", children=[
                step("a) Gesamteindruck", "Vergleich der Zeichen in ihrer Gesamtheit aus dem Erinnerungsbild; keine zergliedernde Betrachtung.", concepts=["gesamteindruck"], cases=["eugh_sabel_puma"]),
                step("b) Prägung durch einzelne Bestandteile", "Prägetheorie: Ein Bestandteil prägt, wenn die anderen zurücktreten; beschreibende Bestandteile prägen nicht; bekannte Herstellerangaben treten regelmäßig zurück.", concepts=["praegetheorie"], cases=["bgh_springende_raubkatze", "bgh_metrobus"]),
                step("c) Ähnlichkeit nach Klang, Bild, Sinngehalt", "Ähnlichkeit in einer Richtung genügt; Neutralisierung klanglicher Ähnlichkeit durch abweichenden Sinngehalt möglich. Wortmarke vs. 3D-Gestaltung: nur begriffliche Ähnlichkeit.", concepts=["zeichenaehnlichkeit"], cases=["bgh_goldbaeren", "bgh_ips_isp", "bgh_maalox"]),
                step("d) Selbständig kennzeichnende Stellung", "Übernahme der älteren Marke in ein zusammengesetztes Zeichen (THOMSON LIFE) – Ausnahmefall, besondere Umstände erforderlich.", concepts=["selbstaendig_kennzeichnende_stellung"], cases=["eugh_thomson_life", "bgh_culinaria", "bgh_interconnect"]),
            ]),
            step("5. Gesamtabwägung (Wechselwirkung)", "Geringere Warenähnlichkeit kann durch höhere Zeichenähnlichkeit oder erhöhte Kennzeichnungskraft ausgeglichen werden und umgekehrt.", concepts=["wechselwirkung"], cases=["eugh_canon", "bgh_culinaria"]),
            step("6. Art der Verwechslungsgefahr", "Unmittelbar (Zeichen werden verwechselt) – mittelbar (Serienzeichen, gemeinsamer Stammbestandteil) – im weiteren Sinne (Annahme wirtschaftlicher/organisatorischer Verbindungen; Ausnahme, besondere Umstände).",
                 concepts=["verwechslungsgefahr_weiterer_sinn", "serienmarke"], cases=["bgh_mustang", "bgh_volkswagen_volksinspektion"]),
        ],
    ),
    dict(
        id="schema_bekanntheitsschutz",
        label="Bekanntheitsschutz (§ 14 Abs. 2 Nr. 3 MarkenG)",
        kategorie="Verletzung",
        beschreibung="Erweiterter Schutz bekannter Marken über die Herkunftsfunktion hinaus – auch außerhalb des Ähnlichkeitsbereichs der Waren und ohne Verwechslungsgefahr.",
        norms=["§ 14 Abs. 2 Nr. 3", "§ 9 Abs. 1 Nr. 3"],
        steps=[
            step("1. Bekannte Marke im Inland", "Bekanntheit bei einem bedeutenden Teil des von den Waren/Dienstleistungen angesprochenen Publikums; keine festen Prozentsätze; Faktoren: Marktanteil, Intensität, Dauer, Werbeaufwand. Maßgeblicher Zeitpunkt: Kollisionszeitpunkt (Verletzung) bzw. Anmeldetag des jüngeren Zeichens (§ 22 Abs. 1 Nr. 1, § 51 Abs. 3). Bei Unionsmarken: Bekanntheit in der Union (Art. 9 Abs. 2 lit. c UMV, § 125b Nr. 1).",
                 concepts=["bekannte_marke", "bekanntheit_union", "koexistenz_22"], cases=["eugh_general_motors", "bgh_tuev_ii", "eugh_pago", "eugh_iron_smith"]),
            step("2. Zeichenidentität oder -ähnlichkeit", "Gleiche Maßstäbe wie bei Nr. 2, aber es genügt ein Grad der Ähnlichkeit, der zur gedanklichen Verknüpfung führt.", concepts=["zeichenaehnlichkeit"], cases=["bgh_goldbaeren", "bgh_springender_pudel"]),
            step("3. Benutzung für Waren/Dienstleistungen (auch bei Identität/Ähnlichkeit)", "Nach richtlinienkonformer Auslegung auch im Ähnlichkeitsbereich anwendbar (OTTO Cap). Markenmäßige Benutzung: gedankliche Verknüpfung genügt; Beeinträchtigung der Herkunftsfunktion nicht erforderlich.", concepts=["markenmaessige_benutzung"], cases=["bgh_otto_cap", "bgh_lila_postkarte"]),
            step("4. Gedankliche Verknüpfung", "Der Verkehr bringt das Zeichen mit der bekannten Marke in Verbindung (Assoziation), ohne sie zu verwechseln. Notwendige, aber nicht hinreichende Voraussetzung.", concepts=["gedankliche_verknuepfung"], cases=["eugh_intel", "bgh_metrobus"]),
            step("5. Eingriffstatbestand (eine Alternative genügt)", children=[
                step("a) Ausnutzung der Unterscheidungskraft (Aufmerksamkeitsausbeutung)", concepts=["ausnutzung_unterscheidungskraft"], cases=["bgh_otto_cap", "bgh_springender_pudel"]),
                step("b) Ausnutzung der Wertschätzung (Rufausbeutung, Imagetransfer)", concepts=["ausnutzung_wertschaetzung"], cases=["eugh_loreal_bellure", "bgh_oeko_test_ii"]),
                step("c) Beeinträchtigung der Unterscheidungskraft (Verwässerung)", "Nachweis der (Gefahr einer) Änderung des wirtschaftlichen Verhaltens der Verbraucher (Intel).", concepts=["verwaesserung"], cases=["eugh_intel"]),
                step("d) Beeinträchtigung der Wertschätzung (Rufschädigung/Verunglimpfung)", concepts=["rufschaedigung"], cases=["bgh_lila_postkarte"]),
            ]),
            step("6. Ohne rechtfertigenden Grund in unlauterer Weise", "Umfassende Interessenabwägung; Grundrechte (Kunst-, Meinungsfreiheit), zulässige vergleichende Werbung, Alternativangebot bei Keyword-Werbung als rechtfertigende Gründe.", concepts=["unlauterkeit"], cases=["bgh_lila_postkarte", "eugh_interflora", "eugh_loreal_bellure"]),
            step("7. Keine Schranken (§§ 23, 24)", concepts=["schranke_23", "erschoepfung"], cases=["bgh_tuev_ii"]),
        ],
    ),
    dict(
        id="schema_eintragungsfaehigkeit",
        label="Schutzfähigkeit / Eintragungsfähigkeit einer Marke (§§ 3, 7, 8 MarkenG)",
        kategorie="Schutzvoraussetzungen",
        beschreibung="Prüfung im Eintragungsverfahren (§§ 36, 37) und im Nichtigkeitsverfahren (§ 50). Reihenfolge: Markenfähigkeit → Inhaberschaft → Darstellbarkeit → absolute Schutzhindernisse → Verkehrsdurchsetzung.",
        norms=["§ 3", "§ 7", "§ 8", "§ 37", "§ 50"],
        steps=[
            step("1. Markenfähigkeit (§ 3 Abs. 1)", "Abstrakte Unterscheidungseignung des Zeichens (losgelöst von den konkreten Waren). Nur ausnahmsweise zu verneinen.", concepts=["markenfaehigkeit"], cases=["eugh_libertel"]),
            step("2. Kein Formausschluss (§ 3 Abs. 2)", "Form/charakteristisches Merkmal durch Art der Ware bedingt (Nr. 1), technisch erforderlich (Nr. 2) oder wertverleihend (Nr. 3)? Nicht durch Verkehrsdurchsetzung überwindbar.", concepts=["formausschluss", "formmarke"], cases=["bgh_ritter_sport", "bgh_bodenduebel", "eugh_philips_remington"]),
            step("3. Inhaberschaft (§ 7)", "Natürliche Personen, juristische Personen, rechtsfähige Personengesellschaften.", norms=["§ 7"]),
            step("4. Darstellbarkeit im Register (§ 8 Abs. 1)", "Klare und eindeutige Bestimmbarkeit des Schutzgegenstands (Sieckmann-Kriterien); graphische Darstellbarkeit nicht mehr erforderlich.", concepts=["darstellbarkeit"]),
            step("5. Keine absoluten Schutzhindernisse (§ 8 Abs. 2)", concepts=["absolute_schutzhindernisse"], children=[
                step("Nr. 1 – Fehlende Unterscheidungskraft", "Konkrete Eignung als Herkunftshinweis für die beanspruchten Waren; großzügiger Maßstab; alle praktisch bedeutsamen Verwendungsformen; Sicht des Durchschnittsverbrauchers im Anmeldezeitpunkt.", concepts=["unterscheidungskraft", "verwendungsformen"], cases=["bgh_hot", "bgh_darferdas_ii", "bgh_link_economy", "bgh_for_you", "bgh_pippi_langstrumpf"]),
                step("Nr. 2 – Freihaltebedürfnis an beschreibenden Angaben", "Kann die Angabe zur Beschreibung von Merkmalen der Waren dienen (auch künftig)? Allgemeininteresse der Mitbewerber.", concepts=["freihaltebeduerfnis"], cases=["bgh_black_friday", "eugh_chiemsee"]),
                step("Nr. 3 – Üblich gewordene Bezeichnungen", concepts=["uebliche_bezeichnung"]),
                step("Nr. 4 – Täuschungseignung (nur wenn ersichtlich, § 37 Abs. 3)", concepts=["taeuschung"]),
                step("Nr. 5 – Verstoß gegen öffentliche Ordnung / gute Sitten", norms=["§ 8 Abs. 2 Nr. 5"]),
                step("Nr. 6-8 – Hoheitszeichen, amtliche Prüfzeichen, Kennzeichen internationaler Organisationen", norms=["§ 8 Abs. 2 Nr. 6", "§ 8 Abs. 2 Nr. 7", "§ 8 Abs. 2 Nr. 8"]),
                step("Nr. 9-13 – Sonstige gesetzliche Verbote, geschützte Ursprungsbezeichnungen, traditionelle Bezeichnungen, Sortenbezeichnungen", norms=["§ 8 Abs. 2 Nr. 9"]),
                step("Nr. 14 – Bösgläubige Anmeldung (nur wenn ersichtlich, § 37 Abs. 3)", concepts=["boesglaeubigkeit"], cases=["bgh_glueckspilz", "bgh_eros"]),
            ]),
            step("6. Überwindung von Nr. 1-3 durch Verkehrsdurchsetzung (§ 8 Abs. 3)", "Durchsetzung in den beteiligten Verkehrskreisen vor dem Anmeldetag; Richtwert mind. 50 % Zuordnung; Nachweis v.a. durch demoskopisches Gutachten.", concepts=["verkehrsdurchsetzung"], cases=["eugh_chiemsee", "bgh_test", "bgh_nivea_blau", "bgh_rocher_kugel"]),
            step("7. Verfahren", "Prüfung von Amts wegen (§ 37); Zurückweisung; Beschwerde BPatG (§ 66); Rechtsbeschwerde BGH (§ 83). Nach Eintragung: Nichtigkeit § 50 (Feststellungslast beim Antragsteller; Zehnjahresfrist für Nr. 1-3).", concepts=["nichtigkeit"], norms=["§ 37", "§ 66", "§ 83", "§ 50"], cases=["bgh_smartbook", "bgh_sparkassen_rot"]),
        ],
    ),
    dict(
        id="schema_schranke_23",
        label="Schranke des § 23 MarkenG (Namen, beschreibende Angaben, Bestimmungshinweis)",
        kategorie="Schranken",
        beschreibung="Einwendung des Verletzers: Auch eine an sich tatbestandsmäßige Benutzung kann nicht untersagt werden, wenn sie einer der drei Fallgruppen unterfällt und den anständigen Gepflogenheiten entspricht.",
        norms=["§ 23"],
        steps=[
            step("1. Tatbestand des § 14 Abs. 2 erfüllt", "§ 23 ist erst zu prüfen, wenn eine rechtsverletzende Benutzung vorliegt (bei rein beschreibender Verwendung fehlt bereits die markenmäßige Benutzung).", concepts=["markenmaessige_benutzung"]),
            step("2. Fallgruppe", children=[
                step("Nr. 1 – Name oder Anschrift des Dritten", "Nur natürliche Personen (nach MaMoG). Recht der Gleichnamigen.", concepts=["gleichnamigkeit"], cases=["bgh_peek_cloppenburg"]),
                step("Nr. 2 – Zeichen ohne Unterscheidungskraft / beschreibende Angaben", "Benutzung von Angaben über Art, Beschaffenheit, Bestimmung usw. – auch wenn sie mit einer (verkehrsdurchgesetzten) Marke identisch sind.", concepts=["freihaltebeduerfnis", "schranke_23"], cases=["bgh_tuev_ii"]),
                step("Nr. 3 – Bestimmungshinweis (Zubehör, Ersatzteile, Kompatibilität)", "Benutzung muss notwendig sein: praktisch einziges Mittel, um über die Bestimmung zu informieren (Gillette). Wortmarke statt Logo; keine Emblem-Nachbildung.", concepts=["ersatzteilhinweis"], cases=["eugh_gillette", "bgh_staubsaugerfiltertueten", "bgh_kuehlergrill", "bgh_grosse_inspektion"]),
            ]),
            step("3. Anständige Gepflogenheiten in Gewerbe oder Handel (§ 23 Abs. 2)", "Verstoß, wenn (a) eine geschäftliche Verbindung zum Markeninhaber suggeriert wird, (b) die Unterscheidungskraft/Wertschätzung unlauter ausgenutzt wird, (c) die Marke herabgesetzt wird oder (d) die eigene Ware als Imitation dargestellt wird. Die Eigenmarke muss im Vordergrund stehen.", concepts=["schranke_23"], cases=["eugh_gillette", "bgh_staubsaugerfiltertueten"]),
        ],
    ),
    dict(
        id="schema_erschoepfung",
        label="Erschöpfung (§ 24 MarkenG)",
        kategorie="Schranken",
        beschreibung="Einwendung gegen Ansprüche wegen des Weitervertriebs von Originalware.",
        norms=["§ 24"],
        steps=[
            step("1. Originalware (Echtheit)", "Die konkrete Ware wurde vom Markeninhaber oder mit seiner Zustimmung mit der Marke versehen. Bei Bestreiten: Beweislast beim Beklagten (Converse I).", concepts=["beweislast_erschoepfung"], cases=["bgh_converse_i"]),
            step("2. Inverkehrbringen im Inland, in der EU oder im EWR", "Übertragung der tatsächlichen Verfügungsgewalt mit Verwertungsmöglichkeit innerhalb des EWR. Keine internationale Erschöpfung: Ware aus Drittstaaten ist nicht erschöpft.", concepts=["erschoepfung"], cases=["eugh_van_doren", "bgh_stuessy_ii"]),
            step("3. Durch den Inhaber oder mit seiner Zustimmung", "Zustimmung durch Lizenz; Verstoß des Lizenznehmers gegen § 30 Abs. 2 = ohne Zustimmung (Converse II). Beweislast grundsätzlich beim Beklagten; Umkehr bei ausschließlichem Vertriebssystem und Marktabschottungsgefahr.", concepts=["lizenz", "beweislast_erschoepfung"], cases=["bgh_converse_ii", "eugh_van_doren"]),
            step("4. Keine berechtigten Gründe (§ 24 Abs. 2)", "Veränderung/Verschlechterung der Ware; Umverpacken nur nach den BMS-Kriterien; erhebliche Rufschädigung durch Werbung (Dior/Evora); Suggestion einer Vertragshändlerbeziehung.", concepts=["berechtigte_gruende", "umverpackung"], cases=["eugh_bms", "eugh_dior_evora"]),
            step("5. Reichweite", "Erschöpfung erfasst Weitervertrieb und Werbung für die konkreten Warenstücke; nicht die Verwendung der Marke für andere Waren oder als Unternehmenskennzeichen.", concepts=["erschoepfung"]),
        ],
    ),
    dict(
        id="schema_benutzungszwang",
        label="Rechtserhaltende Benutzung und Verfall (§§ 25, 26, 49 MarkenG)",
        kategorie="Benutzungszwang",
        beschreibung="Prüfung der Nichtbenutzungseinrede (§ 25 im Verletzungsprozess, § 43 Abs. 1 im Widerspruchsverfahren) und des Verfallsantrags (§ 49 Abs. 1).",
        norms=["§ 25", "§ 26", "§ 49"],
        steps=[
            step("1. Ablauf der Benutzungsschonfrist", "Fünf Jahre seit Eintragung bzw. seit Abschluss des Widerspruchsverfahrens (§ 26 Abs. 5). Vorher ist die Einrede unbeachtlich.", concepts=["benutzungsschonfrist"]),
            step("2. Maßgeblicher Fünfjahreszeitraum", "§ 25 Abs. 2: fünf Jahre vor Klageerhebung (und ggf. vor Schluss der mündlichen Verhandlung); § 49 Abs. 1: ununterbrochene fünf Jahre vor dem Löschungsantrag; Heilung durch Benutzungsaufnahme (§ 49 Abs. 1 S. 2, 3).", concepts=["nichtbenutzungseinrede", "verfall"]),
            step("3. Voraussetzungen der rechtserhaltenden Benutzung (§ 26)", children=[
                step("a) Ernsthafte Benutzung", "Benutzung entsprechend der Hauptfunktion zur Erschließung/Sicherung eines Absatzmarkts; keine Scheinbenutzung; kein Mindestumfang.", concepts=["ernsthafte_benutzung"], cases=["eugh_ansul", "bgh_voodoo"]),
                step("b) Benutzung als Marke (funktionsgemäß)", "Der Verkehr muss die Verwendung als Herkunftshinweis für die Waren verstehen; rein firmenmäßige oder beschreibende Verwendung genügt nicht (aber: LOTTOCARD).", concepts=["rechtserhaltende_benutzung", "markenmaessige_benutzung"], cases=["bgh_lottocard"]),
                step("c) Für die eingetragenen Waren/Dienstleistungen", "Teilbenutzung: Bei Oberbegriffen bleibt der Schutz für die Untergruppe erhalten, der die benutzten Waren angehören (Integrationsfrage, § 49 Abs. 3).", norms=["§ 49 Abs. 3"]),
                step("d) Im Inland", "Auch Anbringen auf Waren/Verpackungen allein für den Export genügt (§ 26 Abs. 4).", norms=["§ 26 Abs. 1", "§ 26 Abs. 4"]),
                step("e) Durch den Inhaber oder mit seiner Zustimmung (§ 26 Abs. 2)", "Lizenznehmer, Konzernunternehmen.", concepts=["lizenz"]),
                step("f) In eingetragener oder nur unwesentlich abweichender Form (§ 26 Abs. 3)", "Kennzeichnender Charakter darf nicht verändert werden; unschädliche Zusätze vs. Verschmelzung zu neuem Gesamtzeichen.", concepts=["abweichende_form"], cases=["bgh_probiotik", "bgh_dorzo"]),
            ]),
            step("4. Berechtigte Gründe für die Nichtbenutzung", "Hindernisse außerhalb des Einflussbereichs des Inhabers (z.B. Zulassungsverfahren, Einfuhrverbote), nicht bloße wirtschaftliche Schwierigkeiten.", norms=["§ 26 Abs. 1"]),
            step("5. Beweis-/Glaubhaftmachungslast", "Verletzungsprozess: voller Beweis durch den Markeninhaber; Widerspruchsverfahren: Glaubhaftmachung (§ 43 Abs. 1); Verfallsverfahren: Inhaber muss Benutzung darlegen (§ 53 Abs. 5, § 55 Abs. 3).", concepts=["nichtbenutzungseinrede"], norms=["§ 43 Abs. 1", "§ 53", "§ 55"], cases=["bgh_voodoo"]),
            step("6. Rechtsfolge", "Einrede: Ansprüche ausgeschlossen (§ 25). Verfall: Löschung mit Wirkung ab Antrag oder früherem Verfallszeitpunkt (§ 52 Abs. 1).", concepts=["verfall"], norms=["§ 52"]),
        ],
    ),
    dict(
        id="schema_unternehmenskennzeichen",
        label="Schutz geschäftlicher Bezeichnungen (§§ 5, 15 MarkenG)",
        kategorie="Geschäftliche Bezeichnungen",
        beschreibung="Unterlassungsanspruch aus § 15 Abs. 4 i.V.m. Abs. 2 (Verwechslungsgefahr) oder Abs. 3 (bekannte geschäftliche Bezeichnung).",
        norms=["§ 5", "§ 15"],
        steps=[
            step("1. Schutzfähige geschäftliche Bezeichnung (§ 5)", children=[
                step("a) Unternehmenskennzeichen (§ 5 Abs. 2)", "Name, Firma, besondere Geschäftsbezeichnung; Firmenschlagwort/-bestandteil; Domain. Entstehung: Benutzungsaufnahme im Inland + originäre Unterscheidungskraft, sonst Verkehrsgeltung (§ 5 Abs. 2 S. 2 für Geschäftsabzeichen).", concepts=["unternehmenskennzeichen", "firmenschlagwort", "domain"], cases=["bgh_soco_de", "bgh_defacto", "bgh_baumann_ii"]),
                step("b) Werktitel (§ 5 Abs. 3)", "Titelschutzfähiges Werk (Druckschrift, Film, Ton, Bühne, Software, App, Website); Unterscheidungskraft (abgesenkter Maßstab bei Verkehrsgewöhnung); Benutzungsaufnahme / Titelschutzanzeige.", concepts=["werktitel"], cases=["bgh_wetter_de", "bgh_das_omen"]),
            ]),
            step("2. Priorität (§ 6)", "Zeitpunkt der Benutzungsaufnahme bzw. des Erwerbs der Verkehrsgeltung; Vergleich mit dem Zeitrang des angegriffenen Zeichens.", concepts=["prioritaet"]),
            step("3. Verletzungshandlung (§ 15 Abs. 2)", "Unbefugte Benutzung im geschäftlichen Verkehr in einer Weise, die geeignet ist, Verwechslungen hervorzurufen: Wechselwirkung von Branchennähe, Kennzeichnungskraft und Zeichenähnlichkeit. Kennzeichenmäßige Benutzung erforderlich.", concepts=["branchennaehe", "kennzeichnungskraft", "zeichenaehnlichkeit", "verwechslungsgefahr"], cases=["bgh_defacto", "bgh_augsburger_puppenkiste"]),
            step("4. Alternativ: Bekannte geschäftliche Bezeichnung (§ 15 Abs. 3)", "Parallel zu § 14 Abs. 2 Nr. 3: Ausnutzung/Beeinträchtigung der Unterscheidungskraft oder Wertschätzung ohne rechtfertigenden Grund.", concepts=["bekannte_marke"]),
            step("5. Schranken", "§ 23 (insb. Gleichnamigkeit), § 21 Verwirkung, § 20 Verjährung; Recht der Gleichnamigen bei redlichem Namensgebrauch.", concepts=["gleichnamigkeit", "verwirkung"], cases=["bgh_peek_cloppenburg", "bgh_shell_de"]),
            step("6. Rechtsfolgen (§ 15 Abs. 4-6)", "Unterlassung, Schadensersatz bei Verschulden, Haftung für Angestellte; §§ 18, 19 entsprechend.", concepts=["unterlassungsanspruch", "schadensersatz"]),
        ],
    ),
    dict(
        id="schema_widerspruch",
        label="Widerspruchsverfahren (§§ 42, 43 MarkenG) und relative Schutzhindernisse (§ 9)",
        kategorie="Verfahren",
        beschreibung="Registerrechtliche Kollisionsprüfung nach Eintragung der jüngeren Marke.",
        norms=["§ 42", "§ 43", "§ 9"],
        steps=[
            step("1. Zulässigkeit des Widerspruchs", "Frist: drei Monate ab Veröffentlichung der Eintragung (§ 42 Abs. 1); Widerspruchsberechtigung: Inhaber eines in § 42 Abs. 2 genannten älteren Rechts (Marke, notorisch bekannte Marke, Benutzungsmarke/geschäftliche Bezeichnung, Ursprungsbezeichnung); Gebühr. Ältere Unionsmarken (§ 125b Nr. 1) und IR-Marken (§ 112, § 116) sind gleichgestellt; gegen IR-Marken gilt § 114.", concepts=["widerspruch", "relative_schutzhindernisse", "unionsmarke", "ir_marke"], norms=["§ 125b", "§ 114", "§ 116"]),
            step("2. Einrede der Nichtbenutzung (§ 43 Abs. 1)", "Wenn die Widerspruchsmarke seit mehr als fünf Jahren eingetragen ist: Glaubhaftmachung der rechtserhaltenden Benutzung; nur die glaubhaft gemachten Waren werden berücksichtigt (§ 43 Abs. 1 S. 3).", concepts=["nichtbenutzungseinrede", "rechtserhaltende_benutzung"]),
            step("3. Begründetheit: Kollisionstatbestand des § 9 Abs. 1", children=[
                step("Nr. 1 – Identität von Marke und Waren", concepts=["doppelidentitaet"]),
                step("Nr. 2 – Verwechslungsgefahr (Registerlage)", "Vergleich nach den Verzeichnissen beider Marken; sonst wie § 14 Abs. 2 Nr. 2.", concepts=["verwechslungsgefahr", "wechselwirkung"], cases=["bgh_maalox", "bgh_desperados", "bgh_culinaria"]),
                step("Nr. 3 – Bekannte ältere Marke", "Bekanntheit am Anmeldetag der jüngeren Marke (§ 51 Abs. 3), Prognose der hypothetischen Benutzung nach Registerlage; Details im Schema „Relative Schutzhindernisse im Register“. Aus Unionsmarke: Bekanntheit in der Union (§ 125b Nr. 1).", concepts=["relative_schutzhindernis_bekannt", "bekannte_marke", "bekanntheit_union"], norms=["§ 9 Abs. 1 Nr. 3", "§ 51 Abs. 3"], cases=["bgh_springender_pudel", "eugh_iron_smith"]),
            ]),
            step("4. Entscheidung und Rechtsmittel", "Löschung der jüngeren Marke ganz oder teilweise (§ 43 Abs. 2); Beschwerde zum BPatG (§ 66), Rechtsbeschwerde zum BGH (§ 83); alternativ Nichtigkeitsverfahren nach § 51 (auch mit Rechten aus § 13) vor DPMA (§ 53) oder Gericht (§ 55).", concepts=["nichtigkeit"], norms=["§ 43 Abs. 2", "§ 51", "§ 53", "§ 55", "§ 66", "§ 83"]),
        ],
    ),
    dict(
        id="schema_loeschung",
        label="Löschung eingetragener Marken: Verfall (§ 49) und Nichtigkeit (§§ 50, 51)",
        kategorie="Verfahren",
        beschreibung="Angriffe gegen den Bestand einer eingetragenen Marke.",
        norms=["§ 49", "§ 50", "§ 51", "§ 52", "§ 53", "§ 55"],
        steps=[
            step("1. Verfall (§ 49) – ex nunc, Popularantrag", children=[
                step("Abs. 1 – Nichtbenutzung über fünf Jahre", concepts=["verfall", "rechtserhaltende_benutzung", "benutzungsschonfrist"], cases=["bgh_voodoo"]),
                step("Abs. 2 Nr. 1 – Entwicklung zur gebräuchlichen Bezeichnung infolge Verhaltens/Untätigkeit des Inhabers", concepts=["uebliche_bezeichnung"], cases=["bgh_tuev_ii"]),
                step("Abs. 2 Nr. 2 – Täuschungseignung infolge der Benutzung", concepts=["taeuschung"]),
                step("Abs. 2 Nr. 3 – Wegfall der Inhabervoraussetzungen (§ 7)", norms=["§ 7"]),
            ]),
            step("2. Nichtigkeit wegen absoluter Schutzhindernisse (§ 50) – ex tunc, Popularantrag", "Verstoß gegen §§ 3, 7, 8 im Anmeldezeitpunkt; bei § 8 Abs. 2 Nr. 1-3 muss das Hindernis noch im Entscheidungszeitpunkt fortbestehen und der Antrag innerhalb von zehn Jahren gestellt werden (§ 50 Abs. 2). Feststellungslast: Antragsteller.", concepts=["nichtigkeit", "absolute_schutzhindernisse", "boesglaeubigkeit"], cases=["bgh_smartbook", "bgh_sparkassen_rot", "bgh_black_friday", "bgh_ritter_sport", "bgh_test"]),
            step("3. Nichtigkeit wegen älterer Rechte (§ 51) – ex tunc, nur Inhaber des älteren Rechts", "Kollision nach §§ 9-13; Ausschluss bei Verwirkung (§ 51 Abs. 2), Zustimmung (§ 51 Abs. 3) und Löschungsreife des älteren Rechts (§ 51 Abs. 4).", concepts=["nichtigkeit", "relative_schutzhindernisse", "verwirkung"], cases=["bgh_springender_pudel"]),
            step("4. Verfahren", "Antrag beim DPMA (§ 53; bei Widerspruch des Inhabers Weiterführung als kontradiktorisches Verfahren) oder Klage vor dem Landgericht (§ 55; für § 50 seit MaMoG nur DPMA). Wirkung: § 52.", concepts=["verfall", "nichtigkeit"], norms=["§ 52", "§ 53", "§ 55"]),
        ],
    ),
    dict(
        id="schema_entstehung",
        label="Entstehung und Erlöschen des Markenschutzes (§§ 4, 32 ff., 47 ff.)",
        kategorie="Grundlagen",
        beschreibung="Lebenszyklus einer Marke vom Erwerb bis zum Erlöschen.",
        norms=["§ 4", "§ 32", "§ 33", "§ 47", "§ 48"],
        steps=[
            step("1. Entstehung (§ 4)", children=[
                step("Nr. 1 – Eintragung", "Anmeldung (§ 32: Antrag, Wiedergabe, Waren-/Dienstleistungsverzeichnis) → Anmeldetag (§ 33) → Prüfung (§§ 36, 37) → Eintragung und Veröffentlichung (§ 41) → Widerspruchsfrist (§ 42).", concepts=["entstehung_markenschutz", "absolute_schutzhindernisse"], norms=["§ 32", "§ 33", "§ 36", "§ 37", "§ 41"]),
                step("Nr. 2 – Verkehrsgeltung durch Benutzung", concepts=["verkehrsgeltung"]),
                step("Nr. 3 – Notorische Bekanntheit", concepts=["notorische_bekanntheit"]),
            ]),
            step("2. Zeitrang (§ 6) und Priorität (§§ 34, 35)", "Anmeldetag; ausländische Priorität (PVÜ, 6 Monate); Ausstellungspriorität.", concepts=["prioritaet"]),
            step("3. Schutzdauer und Verlängerung (§ 47)", "Zehn Jahre ab Anmeldetag, beliebig oft um zehn Jahre verlängerbar durch Gebührenzahlung.", norms=["§ 47"]),
            step("4. Marke als Vermögensgegenstand (§§ 27-31)", "Rechtsübergang (§ 27), Vermutung der Inhaberschaft (§ 28), dingliche Rechte/Zwangsvollstreckung (§ 29), Lizenzen (§ 30).", concepts=["lizenz", "aktivlegitimation"], norms=["§ 27", "§ 28", "§ 29", "§ 30"]),
            step("5. Erlöschen", "Verzicht (§ 48), Nichtverlängerung (§ 47 Abs. 6), Verfall (§ 49), Nichtigkeit (§§ 50, 51), Löschung im Widerspruchsverfahren (§ 43 Abs. 2).", concepts=["verfall", "nichtigkeit"], norms=["§ 48", "§ 47"]),
        ],
    ),
    dict(
        id="schema_relative_schutzhindernisse",
        label="Relative Schutzhindernisse im Register (§ 9 Abs. 1 Nr. 1-3 MarkenG)",
        kategorie="Verfahren",
        beschreibung="Kollisionsprüfung nach der Registerlage im Widerspruch (§ 42) und im Nichtigkeitsverfahren (§ 51). Schwerpunkt: die bekannte Marke als relatives Schutzhindernis (§ 9 Abs. 1 Nr. 3) mit ihren registerrechtlichen Besonderheiten.",
        norms=["§ 9", "§ 42", "§ 51", "§ 22"],
        steps=[
            step("1. Verfahrensrahmen", "Nur auf Antrag des Inhabers des älteren Rechts: Widerspruch (§ 42 Abs. 2 Nr. 1, drei Monate) oder Nichtigkeitsantrag/-klage (§ 51 Abs. 1 mit §§ 53, 55). Keine Prüfung von Amts wegen (§ 37 prüft nur absolute Hindernisse).",
                 concepts=["relative_schutzhindernisse", "widerspruch", "nichtigkeit"], norms=["§ 42", "§ 51", "§ 53", "§ 55"]),
            step("2. Ältere Marke mit besserem Zeitrang", "Angemeldete oder eingetragene Marke (§ 9 Abs. 1); Anmeldung nur, wenn sie eingetragen wird (§ 9 Abs. 2). Zeitrang nach § 6 (Anmeldetag, Priorität). Aus Unionsmarke: § 125b Nr. 1; aus IR-Marke: § 112, § 116.",
                 concepts=["prioritaet", "unionsmarke", "ir_marke"], norms=["§ 9 Abs. 2", "§ 6", "§ 125b", "§ 112"]),
            step("3. Nichtbenutzungseinrede gegen die ältere Marke", "§ 43 Abs. 1 (Widerspruch: Glaubhaftmachung) bzw. § 53 Abs. 6 (Nichtigkeit). Unionsmarke: Art. 18 UMV (§ 125b Nr. 4, 5); IR-Marke: Fristbeginn nach § 115 Abs. 2 (§ 116).",
                 concepts=["nichtbenutzungseinrede", "benutzung_union", "ir_benutzungsschonfrist"], norms=["§ 43 Abs. 1", "§ 53", "§ 116"]),
            step("4. Kollisionstatbestand", children=[
                step("Nr. 1 – Doppelidentität", "Zeichen- und Warenidentität nach den Verzeichnissen.", concepts=["doppelidentitaet"], norms=["§ 9 Abs. 1 Nr. 1"]),
                step("Nr. 2 – Verwechslungsgefahr", "Registerlage beider Marken; Kennzeichnungskraft der älteren Marke am Anmeldetag der jüngeren (§ 51 Abs. 4 S. 2). Im Übrigen wie § 14 Abs. 2 Nr. 2.", concepts=["verwechslungsgefahr", "wechselwirkung"], norms=["§ 9 Abs. 1 Nr. 2", "§ 51 Abs. 4"], cases=["bgh_maalox", "bgh_desperados", "bgh_culinaria"]),
                step("Nr. 3 – Bekannte ältere Marke", "Spiegelbild des § 14 Abs. 2 Nr. 3 mit registerrechtlichen Besonderheiten.", concepts=["relative_schutzhindernis_bekannt"], norms=["§ 9 Abs. 1 Nr. 3"], cases=["bgh_springender_pudel"], children=[
                    step("a) Bekanntheit im Inland zum maßgeblichen Zeitpunkt", "Bekannt bei einem bedeutenden Teil des angesprochenen Publikums (General Motors). Zeitpunkt: Anmelde-/Prioritätstag der jüngeren Marke (§ 51 Abs. 3); Fortbestehen bei der Entscheidung. Aus Unionsmarke: Bekanntheit in der Union (§ 125b Nr. 1; PAGO, Iron & Smith).", concepts=["bekannte_marke", "bekanntheit_union"], norms=["§ 51 Abs. 3", "§ 125b"], cases=["eugh_general_motors", "eugh_pago", "eugh_iron_smith"]),
                    step("b) Zeichenidentität oder -ähnlichkeit", "Vergleich der eingetragenen Zeichen; ein zur Verknüpfung ausreichender Ähnlichkeitsgrad genügt (Goldbären: Wortmarke vs. 3D nur begrifflich).", concepts=["zeichenaehnlichkeit"], cases=["bgh_goldbaeren", "bgh_springender_pudel"]),
                    step("c) Waren/Dienstleistungen der jüngeren Marke", "Seit dem MaMoG 2019 ohne Einschränkung: auch identische und ähnliche Waren (Linie OTTO Cap ist Gesetz geworden).", cases=["bgh_otto_cap"]),
                    step("d) Gedankliche Verknüpfung", "Ungeschriebene Voraussetzung: Der Verkehr bringt die jüngere Marke mit der bekannten in Verbindung (Intel). Aus Unionsmarke: Bekanntheit bei einem wirtschaftlich nicht unbedeutenden Teil des inländischen Publikums erforderlich (Iron & Smith).", concepts=["gedankliche_verknuepfung"], cases=["eugh_intel", "eugh_iron_smith", "bgh_metrobus"]),
                    step("e) Prognose: Benutzung 'würde' ausnutzen oder beeinträchtigen", "Hypothetische Benutzung der jüngeren Marke für die eingetragenen Waren, nicht der tatsächliche Marktauftritt. Vier Alternativen: Ausnutzung/Beeinträchtigung der Unterscheidungskraft oder der Wertschätzung.", concepts=["ausnutzung_unterscheidungskraft", "ausnutzung_wertschaetzung", "verwaesserung", "rufschaedigung"], cases=["bgh_springender_pudel", "eugh_loreal_bellure"]),
                    step("f) Ohne rechtfertigenden Grund in unlauterer Weise", "Interessenabwägung; Kunst-/Meinungsfreiheit rechtfertigt keine Eintragung als eigene Marke (Springender Pudel).", concepts=["unlauterkeit"], cases=["bgh_springender_pudel", "bgh_lila_postkarte"]),
                ]),
            ]),
            step("5. Ausschlussgründe (nur Nichtigkeitsverfahren)", "Duldung über fünf Jahre (§ 51 Abs. 2 S. 1), Zustimmung (§ 51 Abs. 2 S. 3), fehlende Bekanntheit am Prioritätstag der jüngeren Marke (§ 51 Abs. 3), Löschungsreife der älteren Marke am Prioritätstag der jüngeren wegen Verfalls oder absoluter Schutzhindernisse (§ 51 Abs. 4).",
                 concepts=["verwirkung", "koexistenz_22"], norms=["§ 51 Abs. 2", "§ 51 Abs. 3", "§ 51 Abs. 4"]),
            step("6. Rechtsfolge und Wechselwirkung mit dem Verletzungsprozess", "Löschung ganz oder für Teile der Waren (§ 43 Abs. 2, § 51 Abs. 5), Wirkung ex tunc (§ 52 Abs. 2). Greift § 51 Abs. 3 oder 4, sperrt § 22 Abs. 1 zugleich Unterlassungsansprüche gegen die Benutzung der jüngeren Marke für ihre eingetragenen Waren; es entsteht Koexistenz (§ 22 Abs. 2).",
                 concepts=["koexistenz_22", "nichtigkeit"], norms=["§ 22", "§ 52", "§ 43 Abs. 2"]),
        ],
    ),
    dict(
        id="schema_unionsmarke",
        label="Vorgehen aus einer Unionsmarke in Deutschland (UMV, § 125b ff. MarkenG)",
        kategorie="EU- und IR-Marken",
        beschreibung="Normketten für Verletzungsklage, Widerspruch und Nichtigkeitsantrag aus einer Unionsmarke sowie Angriffe gegen die Unionsmarke selbst.",
        norms=["§ 125b", "§ 125c", "§ 125d", "§ 125e", "§ 125g"],
        steps=[
            step("1. Rechtsgrundlagen", "Unionsmarkenverordnung (VO (EU) 2017/1001, UMV) unmittelbar; das MarkenG gilt nur, soweit § 125b es anordnet (Nr. 1, 2 unmittelbar; Nr. 3-6 entsprechend) oder Art. 129 UMV auf nationales Recht verweist. IR-Marken mit Benennung EU stehen der Unionsmarke gleich (Art. 189 ff. UMV).",
                 concepts=["unionsmarke"], norms=["§ 125b"]),
            step("2. Verletzungsklage aus der Unionsmarke", children=[
                step("a) Anspruch", "Art. 9 Abs. 2 lit. a (Doppelidentität), lit. b (Verwechslungsgefahr), lit. c (bekannte Marke – Bekanntheit in der Union) UMV; Benutzungshandlungen Art. 9 Abs. 3, Transit Art. 9 Abs. 4. Auslegung wie § 14 Abs. 2 Nr. 1-3.", concepts=["doppelidentitaet", "verwechslungsgefahr", "bekannte_marke", "bekanntheit_union"], cases=["eugh_pago", "eugh_iron_smith"]),
                step("b) Schranken", "Art. 14 UMV (= § 23), Art. 15 UMV (Erschöpfung, = § 24), Art. 16 UMV (Zwischenrecht des Inhabers einer jüngeren Marke, ≈ § 22), Verwirkung Art. 61 UMV / § 21 Abs. 1 entsprechend (§ 125b Nr. 3).", concepts=["schranke_23", "erschoepfung", "verwirkung", "koexistenz_22"], norms=["§ 125b", "§ 21"]),
                step("c) Einwand der Nichtbenutzung und Widerklage", "Vermutung der Gültigkeit (Art. 127 Abs. 1); Einwand des Verfalls wegen Nichtbenutzung ohne Widerklage zulässig (Art. 127 Abs. 3); sonstige Verfalls-/Nichtigkeitsgründe nur per Widerklage (Art. 128); Aussetzung bei EUIPO-Verfahren (Art. 132).", concepts=["benutzung_union", "unionsmarkengericht"], cases=["eugh_leno_merken"]),
                step("d) Rechtsfolgen", "Unterlassung und Sanktionen nach Art. 130 UMV; Schadensersatz, Vernichtung/Rückruf, Auskunft, Vorlage, Sicherung, Urteilsbekanntmachung nach §§ 14 Abs. 6, 7, 18-19c MarkenG (§ 125b Nr. 2). Verbot grundsätzlich unionsweit (DHL/Chronopost), Beschränkung bei nur regionaler Verwechslungsgefahr (combit).", concepts=["unterlassungsanspruch", "schadensersatz", "vernichtung_auskunft", "unionsmarkengericht"], norms=["§ 125b", "§ 14 Abs. 6", "§ 18", "§ 19"], cases=["eugh_dhl_chronopost", "eugh_combit"]),
                step("e) Zuständigkeit", "Unionsmarkengerichte (Art. 123, 124 UMV; § 125e); international: Beklagtensitz (Art. 125 Abs. 1-4, unionsweite Kognition) oder Handlungsort (Art. 125 Abs. 5, beschränkt nach Art. 126 Abs. 2); örtlich § 125g; Kennzeichenstreitsache § 140.", concepts=["unionsmarkengericht"], norms=["§ 125e", "§ 125g", "§ 140"]),
            ]),
            step("3. Angriff auf eine deutsche Marke aus der Unionsmarke", children=[
                step("a) Widerspruch (§ 42) und Nichtigkeit (§ 51)", "Unionsmarke ist ältere Marke i.S.d. § 9 (§ 125b Nr. 1); Bekanntheit in der Union statt im Inland (§ 9 Abs. 1 Nr. 3).", concepts=["relative_schutzhindernis_bekannt", "bekanntheit_union", "relative_schutzhindernisse"], norms=["§ 125b", "§ 9", "§ 42", "§ 51"], cases=["eugh_iron_smith"]),
                step("b) Nichtbenutzungseinrede", "Benutzung der Unionsmarke nach Art. 18 UMV statt § 26 (§ 125b Nr. 4 für § 43 Abs. 1, Nr. 5 für § 53 Abs. 6); Verwirkung § 51 Abs. 2 S. 1 entsprechend.", concepts=["benutzung_union"], norms=["§ 125b", "§ 43 Abs. 1", "§ 53"], cases=["eugh_leno_merken"]),
            ]),
            step("4. Angriff auf die Unionsmarke aus einer deutschen Marke oder IR-Marke (DE)", "Vor dem EUIPO: Widerspruch nach Art. 46 i.V.m. Art. 8 Abs. 1 (Identität/Verwechslungsgefahr), Abs. 5 (bekannte Marke, hier genügt Bekanntheit im Mitgliedstaat) UMV; ältere Rechte nach Art. 8 Abs. 2 (nationale Marken, IR-Marken mit Wirkung im Mitgliedstaat, Anmeldungen); Nichtigkeit Art. 60 Abs. 1 lit. a, Abs. 2 (sonstige ältere Rechte); Benutzungsnachweis Art. 47 Abs. 2, 3. Sonst Widerklage vor dem Unionsmarkengericht (Art. 128).",
                 concepts=["relative_schutzhindernisse", "bekannte_marke", "rechtserhaltende_benutzung"]),
            step("5. Seniorität, Umwandlung, Koexistenz", "Seniorität Art. 39, 40 UMV (§ 125c: nachträgliche Feststellung der Löschungsreife); Umwandlung Art. 139 ff. UMV (§ 125d); Koexistenz von Unions- und nationaler Marke, Prioritätsprinzip nach Zeitrang.",
                 concepts=["senioritaet", "prioritaet"], norms=["§ 125c", "§ 125d"]),
        ],
    ),
    dict(
        id="schema_ir_marke",
        label="Vorgehen aus einer IR-Marke in Deutschland (PMMA, §§ 112-125 MarkenG)",
        kategorie="EU- und IR-Marken",
        beschreibung="Internationale Registrierung nach dem Madrider System mit Schutzerstreckung auf Deutschland: Wirkung, Zeitrang, Angriff und Verteidigung.",
        norms=["§ 112", "§ 113", "§ 114", "§ 115", "§ 116", "§ 117", "§ 119", "§ 124", "§ 125"],
        steps=[
            step("1. Rechtsgrundlagen", "Madrider Markenabkommen (MMA, §§ 107-118) und Protokoll (PMMA, §§ 119-125); § 124 erklärt §§ 112-117 auf Protokollmarken für entsprechend anwendbar. Basismarke oder -anmeldung im Ursprungsland erforderlich; internationale Registrierung durch die WIPO; Schutzerstreckung durch Benennung (Art. 3ter PMMA).",
                 concepts=["ir_marke"], norms=["§ 119", "§ 124"]),
            step("2. Wirkung und Zeitrang (§ 112)", "Wie eine am Tag der internationalen Registrierung bzw. der nachträglichen Schutzerstreckung angemeldete und eingetragene deutsche Marke; PVÜ-Priorität (Art. 4 PVÜ) bleibt möglich. Wirkung entfällt bei Schutzverweigerung (§ 112 Abs. 2).",
                 concepts=["ir_marke", "prioritaet", "entstehung_markenschutz"], norms=["§ 112", "§ 6"]),
            step("3. Verteidigung der Erstreckung in Deutschland", children=[
                step("a) Prüfung absoluter Schutzhindernisse (§ 113)", "Wie bei Anmeldungen (§§ 37, 8); Schutzverweigerung muss innerhalb der Frist des Art. 5 Abs. 2 PMMA mitgeteilt werden.", concepts=["ir_schutzverweigerung", "absolute_schutzhindernisse"], norms=["§ 113", "§ 37"]),
                step("b) Widerspruch Dritter (§ 114)", "Veröffentlichung in der WIPO-Gazette ersetzt § 41; Frist ab dem ersten Tag des Folgemonats des Ausgabemonats; statt Löschung: Schutzverweigerung (§ 114 Abs. 3).", concepts=["ir_schutzverweigerung", "widerspruch"], norms=["§ 114", "§ 42"]),
                step("c) Verfall und Nichtigkeit (§ 115)", "§§ 49-51 gelten; Rechtsfolge ist die nachträgliche Schutzentziehung. § 115 Abs. 2 legt den Ersatzzeitpunkt für den Eintragungstag fest.", concepts=["ir_schutzverweigerung", "verfall", "nichtigkeit"], norms=["§ 115", "§ 49", "§ 50", "§ 51"]),
                step("d) Abhängigkeit von der Basismarke und Umwandlung", "Fünf Jahre 'central attack' (Art. 6 PMMA); danach Umwandlung in nationale Anmeldung unter Wahrung des Zeitrangs (Art. 9quinquies PMMA, § 125).", concepts=["ir_marke", "senioritaet"], norms=["§ 125"]),
            ]),
            step("4. Angriff aus der IR-Marke", children=[
                step("a) Verletzungsklage", "§§ 14 ff. gelten unmittelbar (§ 112: Wirkung wie eingetragene Marke); Nichtbenutzungseinrede nach § 25 mit Fristbeginn nach § 115 Abs. 2 (§ 117).", concepts=["unterlassungsanspruch", "ir_benutzungsschonfrist"], norms=["§ 14", "§ 117", "§ 25"]),
                step("b) Widerspruch und Nichtigkeitsantrag gegen deutsche Marken (§ 116)", "§ 9 gilt unverändert (Bekanntheit im Inland); Nichtbenutzungseinrede nach § 43 Abs. 1 bzw. § 53 Abs. 6 mit Fristbeginn nach § 115 Abs. 2.", concepts=["relative_schutzhindernisse", "relative_schutzhindernis_bekannt", "ir_benutzungsschonfrist"], norms=["§ 116", "§ 9", "§ 43 Abs. 1"]),
                step("c) IR-Marke mit Benennung EU", "Gilt als Unionsmarke (Art. 189 ff. UMV): dann § 125b, Unionsmarkengerichte, Bekanntheit und Benutzung in der Union.", concepts=["unionsmarke", "bekanntheit_union", "benutzung_union"], norms=["§ 125b"]),
            ]),
            step("5. Benutzungsschonfrist (§§ 115 Abs. 2, 116, 117)", "Fünf Jahre ab Ablauf der Schutzverweigerungsfrist (Art. 5 Abs. 2 PMMA) oder ab rechtskräftiger Schutzgewährung – nicht ab dem Tag der internationalen Registrierung.",
                 concepts=["ir_benutzungsschonfrist", "benutzungsschonfrist"], norms=["§ 115", "§ 116", "§ 117"]),
        ],
    ),
    dict(
        id="schema_markenrl",
        label="Unionsrechtlicher Rahmen: Markenrechtsrichtlinie anwenden",
        kategorie="EU- und IR-Marken",
        beschreibung="Wie die MarkenRL (EU) 2015/2436 in der Fallbearbeitung wirkt: Aufbau der Richtlinie, Zuordnung der MarkenG-Normen, richtlinienkonforme Auslegung und EuGH-Vorlage.",
        norms=["Art. 1 MarkenRL", "Art. 10 MarkenRL", "Art. 54 MarkenRL"],
        steps=[
            step("1. Anwendungsbereich prüfen", "Erfasst sind eingetragene und angemeldete Marken sowie IR-Marken mit Wirkung im Mitgliedstaat (Art. 1). Nicht harmonisiert: Benutzungsmarken (§ 4 Nr. 2), geschäftliche Bezeichnungen (§ 5), Rechtsfolgen (§§ 14 Abs. 5 ff., 18, 19: Durchsetzungs-RL 2004/48/EG).",
                 concepts=["markenrl"], norms=["Art. 1 MarkenRL", "§ 1"]),
            step("2. Aufbau der Richtlinie kennen", children=[
                step("Kapitel 2 Abschnitt 1 und 2: Markenformen, Eintragungshindernisse", "Art. 3 (Markenformen), Art. 4 (absolute), Art. 5 (relative Gründe), Art. 6 (Seniorität), Art. 7 (Teilzurückweisung), Art. 8 (Zeitpunkt), Art. 9 (Duldung).", concepts=["markenfaehigkeit", "absolute_schutzhindernisse", "relative_schutzhindernisse", "koexistenz_22", "verwirkung"], norms=["Art. 3 MarkenRL", "Art. 4 MarkenRL", "Art. 5 MarkenRL", "Art. 8 MarkenRL", "Art. 9 MarkenRL"]),
                step("Kapitel 2 Abschnitt 3: Rechte und Schranken", "Art. 10 (Rechte, Transit), Art. 11 (Vorbereitungshandlungen), Art. 12 (Nachschlagewerke), Art. 13 (Agentenmarke), Art. 14 (Schranken), Art. 15 (Erschöpfung), Art. 16 (Benutzung), Art. 17 (Einrede), Art. 18 (Zwischenrecht).", concepts=["doppelidentitaet", "verwechslungsgefahr", "bekannte_marke", "transit", "vorbereitungshandlungen", "schranke_23", "erschoepfung", "rechtserhaltende_benutzung"], norms=["Art. 10 MarkenRL", "Art. 14 MarkenRL", "Art. 15 MarkenRL", "Art. 16 MarkenRL", "Art. 18 MarkenRL"]),
                step("Kapitel 2 Abschnitt 4 bis 6: Verfall, Vermögen, Kollektivmarken", "Art. 19 bis 21 (Verfall), Art. 22 bis 26 (Übertragung, Lizenz), Art. 27 bis 36 (Gewährleistungs- und Kollektivmarken).", concepts=["verfall", "lizenz", "kollektivmarke"], norms=["Art. 19 MarkenRL", "Art. 25 MarkenRL", "Art. 28 MarkenRL"]),
                step("Kapitel 3: Verfahren", "Art. 37 bis 42 (Anmeldung, Klassifizierung), Art. 43 bis 47 (Widerspruch, Verfall/Nichtigkeit vor dem Amt, Wirkungen), Art. 48, 49 (Schutzdauer).", concepts=["klassifizierung", "widerspruch", "verwaltungsverfahren_loeschung", "schutzdauer"], norms=["Art. 39 MarkenRL", "Art. 43 MarkenRL", "Art. 45 MarkenRL", "Art. 48 MarkenRL"]),
            ]),
            step("3. Zugehörige MarkenG-Norm zuordnen", "Umsetzungstabelle: Art. 3 → §§ 3, 8 Abs. 1; Art. 4 → § 8 Abs. 2; Art. 5 → §§ 9 ff.; Art. 10 → § 14; Art. 14 → § 23; Art. 15 → § 24; Art. 16 → § 26; Art. 18 → § 22; Art. 19/20 → § 49; Art. 43 → § 42; Art. 45 → § 53; Art. 48/49 → § 47.",
                 concepts=["markenrl"], norms=["§ 14", "§ 23", "§ 24", "§ 26"]),
            step("4. Richtlinienkonform auslegen", "Unionsrechtliche Begriffe (Unterscheidungskraft, Verwechslungsgefahr, Bekanntheit, ernsthafte Benutzung) haben die vom EuGH gegebene Bedeutung; EuGH-Urteile zur UMV sind wegen des Gleichlaufs übertragbar. Nationale Spielräume nur bei Optionen der Richtlinie (Art. 4 Abs. 3, Art. 5 Abs. 4, Art. 28 Abs. 1).",
                 concepts=["richtlinienkonforme_auslegung"], cases=["bgh_darferdas_ii", "bgh_otto_cap", "eugh_thomson_life"]),
            step("5. Bei Zweifeln: Vorlage an den EuGH", "Art. 267 AEUV: Vorlagerecht jedes Gerichts, Vorlagepflicht des BGH als letztinstanzliches Gericht, sofern die Frage nicht bereits geklärt (acte éclairé) oder offenkundig (acte clair) ist. Beispiele: #darferdas? (C-541/18), Thomson Life (C-120/04), Iron & Smith (C-125/14).",
                 concepts=["richtlinienkonforme_auslegung"], cases=["eugh_darferdas", "eugh_thomson_life", "eugh_iron_smith"]),
            step("6. Übergangsrecht beachten", "Umsetzung bis 14.1.2019 (Art. 54), für Art. 45 bis 14.1.2023; MaMoG in Kraft seit 14.1.2019, DPMA-Nichtigkeitsverfahren seit 1.5.2020. Für Altfälle gilt § 158 MarkenG.",
                 concepts=["markenrl"], norms=["Art. 54 MarkenRL", "§ 158"]),
        ],
    ),
    dict(
        id="schema_durchsetzung",
        label="Durchsetzung einer Markenverletzung: Ansprüche und Verfahren nach der Durchsetzungsrichtlinie",
        kategorie="Verletzung",
        beschreibung="Der Weg vom Verdacht zum vollstreckten Urteil, geordnet nach der Richtlinie 2004/48/EG: Aufklärung (Art. 6 bis 8), Eilrechtsschutz (Art. 9), Hauptsacheansprüche (Art. 10, 11, 13, 15), Mittelspersonen (Art. 11 S. 3) und Kosten (Art. 14). Jeder Schritt nennt die umsetzende MarkenG-Norm; die Parallelnormen der anderen Gesetze stehen in der Umsetzungstabelle.",
        norms=["§ 18", "§ 19", "§ 19a", "§ 19b", "§ 19c", "§ 140", "Art. 3 DurchsetzungsRL"],
        steps=[
            step("1. Verletzung und Aktivlegitimation", "Verletzung nach §§ 14, 15 oder 17 (Prüfung im Schema Markenverletzung). Antragsbefugt: Inhaber (§ 28 Abs. 1), Lizenznehmer nach § 30 Abs. 3, 4 (Art. 4 DurchsetzungsRL); auch der Zessionar (EuGH Mircom).",
                 concepts=["aktivlegitimation", "lizenz", "durchsetzungsrl"], norms=["§ 14 Abs. 1", "§ 28 Abs. 1", "§ 30 Abs. 3", "Art. 4 DurchsetzungsRL"], cases=["eugh_mircom"]),
            step("2. Aufklärung vor und neben dem Prozess", children=[
                step("a) Vorlage und Besichtigung (§ 19a; Art. 6, 7)", "Hinreichende Wahrscheinlichkeit der Verletzung, Erforderlichkeit, Verhältnismäßigkeit; bei gewerblichem Ausmaß auch Bank-, Finanz-, Handelsunterlagen. Einstweilige Verfügung ohne Anhörung mit Geheimnisschutz (Düsseldorfer Verfahren). Schadensersatz nach Abs. 5, wenn keine Verletzung vorlag.",
                     concepts=["vorlage_besichtigung", "gewerbliches_ausmass"], norms=["§ 19a", "Art. 6 DurchsetzungsRL", "Art. 7 DurchsetzungsRL"], cases=["bgh_faxkarte"]),
                step("b) Auskunft (§ 19; Art. 8)", "Gegen den Verletzer (Abs. 1) über Herkunft und Vertriebsweg; gegen Dritte in der Kette (Abs. 2 Nr. 1 bis 4) bei offensichtlicher Verletzung oder nach Klageerhebung, wenn sie in gewerblichem Ausmaß handelten. Inhalt Abs. 3: Namen, Anschriften (nur Postanschrift), Mengen, Preise. Grenzen: §§ 383 bis 385 ZPO, aber kein pauschales Bankgeheimnis; Verkehrsdaten nur mit richterlicher Anordnung (Abs. 9); Verhältnismäßigkeit (Abs. 4); Eilauskunft (Abs. 7).",
                     concepts=["drittauskunft", "gewerbliches_ausmass"], norms=["§ 19", "Art. 8 DurchsetzungsRL"], cases=["eugh_coty_stadtsparkasse", "bgh_davidoff_hot_water_ii", "eugh_constantin_film", "eugh_new_wave"]),
                step("c) Sicherung des Schadensersatzes (§ 19b; Art. 9 Abs. 2)", "Bei gewerblichem Ausmaß Vorlage von Bank-, Finanz-, Handelsunterlagen, wenn die Erfüllung des Schadensersatzanspruchs fraglich ist; Kontosperre über den dinglichen Arrest (§§ 916 ff. ZPO).",
                     concepts=["sicherung_schadensersatz"], norms=["§ 19b", "Art. 9 Abs. 2 DurchsetzungsRL"]),
            ]),
            step("3. Eilrechtsschutz (Art. 9)", "Einstweilige Verfügung auf Unterlassung (§§ 935 ff. ZPO) ohne Glaubhaftmachung des Verfügungsgrundes (§ 140 Abs. 3), aber zügig nach Kenntnis; Sequestration (§ 938 Abs. 2 ZPO); ohne Anhörung bei Dringlichkeit (§ 937 Abs. 2 ZPO); Anordnung der Klageerhebung (§ 926 ZPO); Schadensersatz bei Aufhebung verschuldensunabhängig (§ 945 ZPO; EuGH Bayer/Richter). Auch gegen Mittelspersonen (Art. 9 Abs. 1 lit. a).",
                 concepts=["einstweilige_verfuegung"], norms=["§ 140 Abs. 3", "Art. 9 DurchsetzungsRL"], cases=["eugh_bayer_richter"]),
            step("4. Ansprüche in der Hauptsache", children=[
                step("a) Unterlassung (§ 14 Abs. 5; Art. 11 S. 1, 2)", "Wiederholungs- oder Erstbegehungsgefahr, kein Verschulden; Vollstreckung durch Ordnungsgeld (§ 890 ZPO).",
                     concepts=["unterlassungsanspruch"], norms=["§ 14 Abs. 5", "Art. 11 DurchsetzungsRL"]),
                step("b) Vernichtung, Rückruf, Entfernen (§ 18; Art. 10)", "Vernichtung der gekennzeichneten Waren und vorwiegend dazu genutzten Materialien und Geräte (Abs. 1), Rückruf und endgültiges Entfernen aus den Vertriebswegen (Abs. 2); Verhältnismäßigkeit unter Berücksichtigung der Interessen Dritter (Abs. 3 = Art. 10 Abs. 3); auf Kosten des Verletzers.",
                     concepts=["vernichtung_auskunft"], norms=["§ 18", "Art. 10 DurchsetzungsRL"]),
                step("c) Schadensersatz (§ 14 Abs. 6; Art. 13)", "Verschulden („wusste oder hätte wissen müssen“); dreifache Berechnung: konkreter Schaden, Verletzergewinn (S. 2), Lizenzanalogie (S. 3); die Pauschale ist Untergrenze, immaterieller Schaden daneben (EuGH Liffers); strengere nationale Regeln zulässig (EuGH OTK). Schuldloser Verletzer: § 812 BGB, § 852 BGB über § 20 S. 2.",
                     concepts=["schadensersatz", "lizenzanalogie"], norms=["§ 14 Abs. 6", "§ 20", "Art. 13 DurchsetzungsRL"], cases=["bgh_btk", "eugh_liffers", "eugh_otk"]),
                step("d) Urteilsbekanntmachung (§ 19c; Art. 15)", "Befugnis der obsiegenden Partei bei berechtigtem Interesse; drei Monate nach Rechtskraft; nicht vorläufig vollstreckbar.",
                     concepts=["urteilsbekanntmachung"], norms=["§ 19c", "Art. 15 DurchsetzungsRL"]),
            ]),
            step("5. Anordnungen gegen Mittelspersonen (Art. 11 S. 3)", "Plattformen, Marktplätze, Provider: Störerhaftung auf Unterlassung nach Hinweis auf eine klare Verletzung, gerichtet auch auf die Verhinderung gleichartiger künftiger Verletzungen, ohne allgemeine Überwachungspflicht (EuGH L'Oréal/eBay, Tommy Hilfiger; BGH Internet-Versteigerung II). Kein Schadensersatz; Auskunft aus § 19 Abs. 2 Nr. 3.",
                 concepts=["mittelsperson_anordnung", "stoererhaftung"], norms=["§ 14 Abs. 5", "§ 19 Abs. 2", "Art. 11 DurchsetzungsRL"], cases=["eugh_loreal_ebay", "eugh_tommy_hilfiger", "bgh_internet_versteigerung_ii"]),
            step("6. Kosten (Art. 14)", "Unterlegener trägt zumutbare und angemessene Kosten (§§ 91 ff. ZPO); Patentanwaltskosten nach § 140 Abs. 4 nur bei Notwendigkeit der Mitwirkung (EuGH NovaText, BGH Kosten des Patentanwalts VII); Abmahnkosten als sonstige Kosten (EuGH Koch Media); Streitwertbegünstigung § 142.",
                 concepts=["prozesskosten_erstattung"], norms=["§ 140 Abs. 4", "§ 142", "Art. 14 DurchsetzungsRL"], cases=["eugh_novatext", "bgh_kosten_patentanwalt_vii", "eugh_koch_media"]),
            step("7. Querschnitt: Verhältnismäßigkeit und Missbrauch (Art. 3)", "Jede Maßnahme muss wirksam, verhältnismäßig und abschreckend sein und darf den rechtmäßigen Handel nicht behindern; Missbrauchskontrolle bei Serienabmahnern (EuGH Mircom); Verhältnismäßigkeitsvorbehalte in § 18 Abs. 3, § 19 Abs. 4, § 19a Abs. 2, § 19b Abs. 2. Nicht harmonisiert: Verjährung (§ 20), Haftung des Betriebsinhabers (§ 14 Abs. 7).",
                 concepts=["durchsetzungsrl", "verjaehrung"], norms=["§ 18 Abs. 3", "§ 19 Abs. 4", "§ 20", "Art. 3 DurchsetzungsRL"], cases=["eugh_mircom", "eugh_novatext"]),
        ],
    ),
    # ------------------------------------------------------------------
    # Klausurschemata für die Aufsichtsarbeit „Nichttechnische Schutzrechte“
    # ------------------------------------------------------------------
    dict(
        id="schema_klausur_ns",
        label="Aufbau der NS-Klausur (Patentanwaltsprüfung)",
        kategorie="Klausur",
        beschreibung="Gliederungsgerüst der Aufsichtsarbeit „Nichttechnische Schutzrechte“ (§ 40 Abs. 1 S. 2 Nr. 2 PatAnwAPrV, vier Stunden). In rund zwei Dritteln der Klausuren ist ein Beschwerdegutachten zu schreiben; die Prüfung läuft immer über Wirksamkeit, Zulässigkeit und Begründetheit.",
        norms=["§ 42", "§ 66", "§ 70", "§ 71"],
        steps=[
            step("A. Vorüberlegung: Welche Perspektive verlangt die Aufgabe?",
                 "Drei Formate kommen vor. Gerichtsgutachten: „Wie wird das BPatG über die Beschwerde entscheiden?“ – Prüfung aus Sicht des Senats, am Ende ein Tenorvorschlag. Amtsgutachten: „Wie wird das DPMA über den Widerspruch entscheiden?“. Anwaltsgutachten: Mandantenschreiben mit Handlungsempfehlung, offenen Fragen und Alternativen. Der Bearbeitervermerk ist wörtlich zu befolgen; wird ein Hilfsgutachten verlangt, ist auch die unbegründete Variante durchzuprüfen.",
                 concepts=["widerspruch", "beschwerde"], norms=["§ 66", "§ 42"]),
            step("B. Verfahrensgang aus dem Sachverhalt herausschreiben",
                 "Vor dem Gutachten eine Zeitleiste anlegen: Anmeldung, Eintragung, Veröffentlichung, Widerspruch, Gebührenzahlung, Beschluss, Zustellung, Rechtsbehelf, Gebühr. Jedes Datum im Sachverhalt hat einen Zweck; beigefügte Kalender sind ein Hinweis auf eine Fristenfalle. Ebenso notieren: Waren- und Dienstleistungsverzeichnisse beider Marken, Zeichenformen und die Besetzung der entscheidenden Stelle.",
                 concepts=["fristberechnung", "zustellung"], norms=["§ 94", "§ 82 Abs. 1"]),
            step("C. Wirksamkeit der Verfahrenshandlung",
                 "Vorgeschaltete Frage vor der Zulässigkeit: Ist die Gebühr rechtzeitig und vollständig gezahlt? Sonst gilt die Handlung als nicht vorgenommen (§ 64a i.V.m. § 6 Abs. 2 PatKostG) – der Widerspruch gilt als nicht erhoben, die Beschwerde als nicht eingelegt. Zahlungstag nach § 2 PatKostZV.",
                 concepts=["zahlungstag"], norms=["§ 64a"], cases=["bpatg_silberweide"]),
            step("D. Zulässigkeit", "Nach dem immer gleichen Raster; Einzelheiten in den Schemata zur Zulässigkeit des Widerspruchs und der Beschwerde.",
                 concepts=["beteiligtenfaehigkeit", "beschwer", "inlandsvertreter"], norms=["§ 42 Abs. 1", "§ 66 Abs. 2", "§ 96"], children=[
                step("1. Statthaftigkeit", "Richtiger Rechtsbehelf gegen die richtige Entscheidung: Erinnerung bei Beschlüssen des gehobenen Dienstes (§ 64), sonst Beschwerde (§ 66 Abs. 1).", concepts=["erinnerung", "beschwerde"], norms=["§ 64", "§ 66 Abs. 1"]),
                step("2. Beteiligten-, Prozess- und Postulationsfähigkeit", "§ 7 MarkenG, §§ 50, 51 ZPO über § 82 Abs. 1; Vertretung juristischer Personen; Inlandsvertreter nach § 96.", concepts=["beteiligtenfaehigkeit", "inlandsvertreter"], norms=["§ 7", "§ 96"], cases=["bpatg_blizzard_ug"]),
                step("3. Berechtigung und Beschwer", "Widerspruchsberechtigung nach § 42 Abs. 2 in Verbindung mit § 28 Abs. 1; Beschwerdeberechtigung nur für Beteiligte, die beschwert sind.", concepts=["beschwer"], norms=["§ 42 Abs. 2", "§ 28 Abs. 1"]),
                step("4. Form und Ort", "Schriftform mit eigenhändiger Unterschrift oder elektronisch nach § 95a; Eingang beim DPMA. Inhalt des Widerspruchs nach § 30 MarkenV.", concepts=["beschwerde"], norms=["§ 95a", "§ 66 Abs. 2"]),
                step("5. Frist", "Fristauslösendes Ereignis, Zustellungsfiktionen (§ 94), Berechnung nach §§ 187 ff. BGB, § 193 BGB; bei Versäumung Wiedereinsetzung prüfen.", concepts=["fristberechnung", "zustellung", "wiedereinsetzung"], norms=["§ 42 Abs. 1", "§ 66 Abs. 2", "§ 91"]),
                step("6. Zwischenergebnis", "Ausdrücklich formulieren: „Der Widerspruch ist zulässig.“ Erst dann zur Begründetheit."),
            ]),
            step("E. Begründetheit", "Reihenfolge im Kollisionsverfahren: Bestand und Zeitrang des älteren Rechts, Nichtbenutzungseinrede als Vorfrage, dann der Kollisionstatbestand.",
                 concepts=["nichtbenutzungseinrede", "verwechslungsgefahr"], norms=["§ 43 Abs. 1", "§ 9 Abs. 1"], children=[
                step("1. Älteres Recht und Zeitrang", "Bestehen, Inhaberschaft (§ 28), Priorität (§ 6), bei Unionsmarken § 125b, bei IR-Marken §§ 112 ff.", concepts=["prioritaet", "unionsmarke", "ir_marke"], norms=["§ 6", "§ 28", "§ 125b"]),
                step("2. Nichtbenutzungseinrede", "Zulässigkeit der Einrede, maßgeblicher Zeitraum, Glaubhaftmachung, Rechtsfolge des § 43 Abs. 1 Satz 3.", concepts=["nichtbenutzungseinrede", "glaubhaftmachung"], norms=["§ 43 Abs. 1", "§ 26"], cases=["bpatg_silver_horse"]),
                step("3. Kollisionstatbestand", "§ 9 Abs. 1 Nr. 1 bis 3 oder § 12 in Verbindung mit § 5; Verwechslungsgefahr nach der Registerlage.", concepts=["verwechslungsgefahr", "unternehmenskennzeichen"], norms=["§ 9 Abs. 1", "§ 12"]),
                step("4. Ergebnis je Ware und Dienstleistung", "Die Löschung wird für einzelne Waren ausgesprochen; das Ergebnis ist deshalb warenbezogen zu formulieren (§ 43 Abs. 2).", norms=["§ 43 Abs. 2"]),
            ]),
            step("F. Nebenentscheidungen", "Kosten (§§ 63, 71 Abs. 1), Rückzahlung der Beschwerdegebühr (§ 71 Abs. 3), Zurückverweisung (§ 70 Abs. 3), Zulassung der Rechtsbeschwerde (§ 83 Abs. 2), Aussetzung (§ 148 ZPO), Gegenstandswert.",
                 concepts=["kostenentscheidung", "aussetzung", "rechtsbeschwerde"], norms=["§ 63", "§ 71", "§ 70 Abs. 3", "§ 83"], cases=["bpatg_engelbrecht"]),
            step("G. Tenorvorschlag", "Wird fast immer verlangt. Aufbau: Aufhebung oder Zurückweisung, dann Anordnung, dann Nebenentscheidungen. Formulierungen im Abschnitt „Tenor“ der Klausur-Sektion.",
                 norms=["§ 70", "§ 43 Abs. 2"]),
        ],
    ),
    dict(
        id="schema_zulaessigkeit_widerspruch",
        label="Zulässigkeit des Widerspruchs (§ 42 MarkenG)",
        kategorie="Klausur",
        beschreibung="Vollständige Zulässigkeitsprüfung des Widerspruchs, wie sie die amtliche Lösungsskizze verlangt: Wirksamkeit, Statthaftigkeit, Beteiligtenfähigkeit, Berechtigung, Form, Frist und die weiteren Zulassungsvoraussetzungen.",
        norms=["§ 42", "§ 64a", "§ 7", "§ 96"],
        steps=[
            step("1. Wirksamkeit: Gebühr", "Grundbetrag 250 Euro für ein Widerspruchskennzeichen (Nr. 331 600 GV PatKostG), 50 Euro für jedes weitere (Nr. 331 610, § 42 Abs. 3). Die Gebühr muss innerhalb der Widerspruchsfrist gezahlt sein, sonst gilt der Widerspruch als nicht erhoben (§ 64a i.V.m. § 6 Abs. 2 PatKostG). Zahlungstag nach § 2 PatKostZV. Deckt die Zahlung nur einen Teil der Kennzeichen, ist dem Widersprechenden Gelegenheit zur Zuordnung zu geben; die Klarstellung ist auch nach Fristablauf möglich.",
                 concepts=["zahlungstag"], norms=["§ 64a", "§ 42 Abs. 3"], cases=["bpatg_silberweide"]),
            step("2. Statthaftigkeit", "Der Widerspruch richtet sich gegen die Eintragung einer Marke (§ 42 Abs. 1); er ist ab Eintragung möglich, auch schon vor Beginn der Widerspruchsfrist. Bei IR-Marken tritt die Schutzverweigerung an die Stelle der Löschung (§ 114). Gegen eine bloße Anmeldung gibt es keinen Widerspruch, sondern nur die Eingabe Dritter nach § 37 Abs. 6.",
                 concepts=["widerspruch", "ir_marke"], norms=["§ 42 Abs. 1", "§ 114"], cases=["bpatg_engelbrecht"]),
            step("3. Beteiligten-, Prozess- und Postulationsfähigkeit",
                 "Markenrechtsfähigkeit nach § 7 (natürliche und juristische Personen, rechtsfähige Personengesellschaften); Rechtsfähigkeit der GmbH aus § 13 Abs. 1 GmbHG, der KG aus §§ 161 Abs. 2, 124 HGB. Prozessfähigkeit über § 82 Abs. 1 in Verbindung mit § 51 ZPO; die GmbH handelt durch den Geschäftsführer (§ 35 GmbHG), Prokuristen sind nach § 49 HGB befugt. Kein Anwaltszwang vor dem DPMA; bei Sitz im Ausland Inlandsvertreter nach § 96.",
                 concepts=["beteiligtenfaehigkeit", "inlandsvertreter"], norms=["§ 7", "§ 96", "§ 82 Abs. 1"], cases=["bpatg_blizzard_ug"]),
            step("4. Widerspruchsberechtigung", "Nur der Inhaber eines der in § 42 Abs. 2 genannten Rechte:",
                 concepts=["widerspruch", "relative_schutzhindernisse"], norms=["§ 42 Abs. 2", "§ 28"], children=[
                step("Nr. 1 – ältere angemeldete oder eingetragene Marke (§ 9)", "Auch Unionsmarke (§ 125b Nr. 1) und IR-Marke (§ 112, § 116). Formale Berechtigung folgt aus der Eintragung (§ 28 Abs. 1); bei Rechtsübergang muss der Umschreibungsantrag beim DPMA eingegangen sein (§ 28 Abs. 2).",
                     concepts=["unionsmarke", "ir_marke", "prioritaet"], norms=["§ 9", "§ 125b", "§ 28 Abs. 2"]),
                step("Nr. 2 – notorisch bekannte Marke (§ 10)", concepts=["notorische_bekanntheit"], norms=["§ 10"]),
                step("Nr. 3 – Agentenmarke (§ 11)", concepts=["agentenmarke"], norms=["§ 11"]),
                step("Nr. 4 – Benutzungsmarke und geschäftliche Bezeichnung (§§ 4 Nr. 2, 5, 12)",
                     "Voraussetzung ist, dass das Recht den Inhaber berechtigt, die Benutzung der jüngeren Marke im gesamten Bundesgebiet zu untersagen (§ 12). Ein nur regional geschütztes Unternehmenskennzeichen genügt nicht; der Widerspruch ist dann unbegründet, nicht unzulässig.",
                     concepts=["unternehmenskennzeichen", "verkehrsgeltung", "branchennaehe"], norms=["§ 12", "§ 5", "§ 4"], cases=["bpatg_engelbrecht"]),
                step("Nr. 5 – Ursprungsbezeichnung oder geografische Angabe (§ 13 Abs. 2 Nr. 5)", "Seit dem MaMoG eigener Widerspruchsgrund.", concepts=["geographische_herkunftsangabe"], norms=["§ 42 Abs. 2", "§ 13"]),
            ]),
            step("5. Form und Inhalt", "Schriftlich oder elektronisch (§ 95a); der Widerspruch muss die Identität der angegriffenen Marke, des Widerspruchskennzeichens und des Widersprechenden erkennen lassen (§ 30 Abs. 1 MarkenV). Die Sollangaben des § 30 Abs. 2 MarkenV (Registernummern, Waren, gegen die sich der Widerspruch richtet) sind keine Zulässigkeitsvoraussetzung, sollten aber angesprochen werden. Eine Begründung ist nicht erforderlich und kann nachgereicht werden.",
                 concepts=["widerspruch"], norms=["§ 95a", "§ 42 Abs. 1"]),
            step("6. Widerspruchsfrist", "Drei Monate nach dem Tag der Veröffentlichung der Eintragung (§ 42 Abs. 1). Berechnung: § 187 Abs. 1 BGB (Tag der Veröffentlichung zählt nicht mit), § 188 Abs. 2 BGB, § 193 BGB für Wochenenden und Feiertage. Die Frist ist nicht verlängerbar; Wiedereinsetzung ist ausgeschlossen (§ 91 Abs. 1 Satz 2), auch für die Gebührenzahlung.",
                 concepts=["fristberechnung", "wiedereinsetzung"], norms=["§ 42 Abs. 1", "§ 91 Abs. 1"]),
            step("7. Weitere Zulassungsvoraussetzungen", "Rechtsschutzbedürfnis; keine Rechtskraft eines früheren Widerspruchs zwischen denselben Beteiligten aus demselben Zeichen; Verfahrenssprache Deutsch (§ 93). Auf eigenen Antrag beider Parteien ist eine Cooling-off-Frist von mindestens zwei Monaten einzuräumen (§ 42 Abs. 4).",
                 norms=["§ 42 Abs. 4", "§ 93"]),
            step("8. Zwischenergebnis", "„Der Widerspruch aus der Marke … ist zulässig.“ Bei mehreren Widersprüchen jeden gesondert prüfen und das Ergebnis gesondert formulieren."),
        ],
    ),
    dict(
        id="schema_zulaessigkeit_beschwerde",
        label="Zulässigkeit der Beschwerde zum BPatG (§ 66 MarkenG)",
        kategorie="Klausur",
        beschreibung="Prüfungsraster für den Beschwerdeteil, der in fast jeder NS-Klausur vorkommt: Statthaftigkeit gegenüber der Erinnerung, Beschwer, Form, Frist, Gebühr und Wiedereinsetzung.",
        norms=["§ 66", "§ 64", "§ 91", "§ 94"],
        steps=[
            step("1. Statthaftigkeit", "Beschwerde gegen Beschlüsse der Markenstellen und Markenabteilungen (§ 66 Abs. 1). Entscheidend ist die Besetzung der Ausgangsstelle: Beamter des gehobenen Dienstes oder vergleichbarer Angestellter → zuerst Erinnerung (§ 64); Beamter des höheren Dienstes oder Rechtspfleger → unmittelbar Beschwerde. Sonderfall Durchgriffsbeschwerde: Ist über eine Erinnerung nach sechs Monaten nicht entschieden und wird nach Fristsetzung nicht innerhalb von zwei Monaten entschieden, ist die Beschwerde ohne Erinnerungsbeschluss statthaft (§ 66 Abs. 3).",
                 concepts=["beschwerde", "erinnerung"], norms=["§ 66 Abs. 1", "§ 64", "§ 66 Abs. 3"]),
            step("2. Beschwerdeberechtigung und Beschwer", "Die Beschwerde steht den am Verfahren vor dem DPMA Beteiligten zu (§ 66 Abs. 1 Satz 2). Erforderlich ist eine Beschwer: Wer vollständig obsiegt hat, kann nicht anfechten; sein Schriftsatz ist als Verfahrenserklärung auszulegen. Dritte, auch der Geschäftsführer einer beteiligten Gesellschaft, sind nicht beschwerdeberechtigt.",
                 concepts=["beschwer", "beteiligtenfaehigkeit"], norms=["§ 66 Abs. 1"], cases=["bpatg_blizzard_ug", "bpatg_silver_horse"]),
            step("3. Beteiligten- und Prozessfähigkeit", "Wie im Amtsverfahren; besonders zu prüfen bei gelöschten Gesellschaften (Nachtragsliquidation), Insolvenz (Unterbrechung nach § 240 ZPO) und Tod eines Beteiligten. Erlischt die Vollmacht des Vertreters, sind Zustellungen an ihn unwirksam.",
                 concepts=["beteiligtenfaehigkeit", "inlandsvertreter"], norms=["§ 82 Abs. 1", "§ 96"], cases=["bpatg_blizzard_ug"]),
            step("4. Form und Ort", "Schriftlich beim DPMA einzulegen (§ 66 Abs. 2); erforderlich ist eine eigenhändige Unterschrift oder eine elektronische Einreichung nach § 95a in Verbindung mit der ERVDPMAV (qualifizierte elektronische Signatur oder sicherer Übermittlungsweg wie beA). Nicht ausreichend: einfache E-Mail mit eingescannter Unterschrift. Ein Eingang beim BPatG statt beim DPMA wahrt die Frist nicht. Unterzeichnung mit „i.V.“ durch einen bevollmächtigten Anwalt genügt.",
                 concepts=["beschwerde"], norms=["§ 66 Abs. 2", "§ 95a"], cases=["bpatg_automator"]),
            step("5. Frist", "Ein Monat ab Zustellung des Beschlusses (§ 66 Abs. 2). Zuerst den Zustellungszeitpunkt bestimmen:",
                 concepts=["fristberechnung", "zustellung"], norms=["§ 66 Abs. 2", "§ 94"], children=[
                step("a) Zustellungsart und Fiktion", "Übergabeeinschreiben: dritter Tag nach Aufgabe zur Post (§ 4 Abs. 2 VwZG). Abholfach beim DPMA: dritter Tag nach Niederlegung (§ 94 Abs. 1 Nr. 3), auch wenn früher abgeholt wurde. Empfangsbekenntnis bei Anwälten: Tag der Entgegennahme. Öffentliche Zustellung: zwei Wochen nach Bekanntmachung (§ 10 VwZG).",
                     concepts=["zustellung"], norms=["§ 94"]),
                step("b) Empfänger", "Zuzustellen ist dem bestellten Vertreter (§ 81, § 96 Abs. 2). Bei Rechtsübergang bleibt die Zustellung an den eingetragenen Inhaber wirksam, solange kein Umschreibungsantrag vorliegt (§ 28 Abs. 2).",
                     norms=["§ 81", "§ 28 Abs. 2"]),
                step("c) Fristende", "§§ 187 Abs. 1, 188 Abs. 2 BGB; Verschiebung auf den nächsten Werktag nach § 193 BGB, § 222 Abs. 2 ZPO. Feiertage richten sich nach dem Recht des Behördensitzes.",
                     concepts=["fristberechnung"], norms=["§ 82 Abs. 1"]),
            ]),
            step("6. Beschwerdegebühr", "200 Euro (Nr. 401 300 GV PatKostG), zu zahlen innerhalb der Beschwerdefrist; sonst gilt die Beschwerde als nicht eingelegt (§ 6 Abs. 2 PatKostG). Zahlungstag: Überweisung erst mit Gutschrift, Bareinzahlung am Einzahlungstag, SEPA-Basislastschriftmandat mit seinem Eingang (§ 2 PatKostZV).",
                 concepts=["zahlungstag"], norms=["§ 66 Abs. 2", "§ 64a"], cases=["bpatg_silver_horse"]),
            step("7. Bei Versäumung: Wiedereinsetzung", "Voraussetzungen und Fristen im eigenen Schema; im Beschwerdeverfahren ist die Wiedereinsetzung anders als bei der Widerspruchsfrist möglich.",
                 concepts=["wiedereinsetzung"], norms=["§ 91"]),
            step("8. Umfang der Beschwerde", "Eine Beschwerde ohne Einschränkung richtet sich im Zweifel gegen den gesamten Beschluss. Eine Beschränkung muss eindeutig erklärt sein; danach erwächst der übrige Teil in Teilrechtskraft und kann nach Fristablauf nicht mehr durch Beschwerdeerweiterung angegriffen werden. Ein Beschluss über mehrere Widersprüche wird nur einmal zugestellt und löst nur eine Frist aus.",
                 concepts=["beschwer"], norms=["§ 66 Abs. 2"]),
            step("9. Zwischenergebnis und weiterer Aufbau", "„Die Beschwerde ist zulässig.“ Danach Begründetheit: Prüfung der Sachentscheidung des DPMA, gegebenenfalls Zurückverweisung (§ 70 Abs. 3), Kosten (§ 71) und Zulassung der Rechtsbeschwerde (§ 83 Abs. 2).",
                 concepts=["kostenentscheidung", "rechtsbeschwerde"], norms=["§ 70", "§ 71", "§ 83"]),
        ],
    ),
    dict(
        id="schema_wiedereinsetzung",
        label="Wiedereinsetzung in den vorigen Stand (§ 91 MarkenG)",
        kategorie="Klausur",
        beschreibung="Kommt in Klausuren regelmäßig als eingebauter Fristfehler vor: Kanzleiorganisation, verspätete Überweisung, verlorene Postsendung. Zu prüfen sind Statthaftigkeit, Antragsfrist, Nachholung, Glaubhaftmachung und fehlendes Verschulden.",
        norms=["§ 91", "§ 91a", "§ 82 Abs. 1"],
        steps=[
            step("1. Statthaftigkeit", "Versäumt sein muss eine Frist gegenüber dem DPMA oder dem BPatG, deren Versäumung nach gesetzlicher Vorschrift einen Rechtsnachteil zur Folge hat (§ 91 Abs. 1 Satz 1). Ausgeschlossen ist die Wiedereinsetzung in die Widerspruchsfrist des § 42 Abs. 1 und in die Frist zur Zahlung der Widerspruchsgebühr (§ 91 Abs. 1 Satz 2) sowie in die Prioritätsfrist. Für versäumte Amtsfristen im Anmeldeverfahren gibt es alternativ die verschuldensunabhängige Weiterbehandlung (§ 91a).",
                 concepts=["wiedereinsetzung", "weiterbehandlung"], norms=["§ 91 Abs. 1", "§ 91a", "§ 42 Abs. 1"]),
            step("2. Antragsfrist und Form", "Antrag innerhalb von zwei Monaten nach Wegfall des Hindernisses (§ 91 Abs. 2); das Hindernis fällt weg, wenn der Beteiligte die Fristversäumung erkennt oder bei zumutbarer Sorgfalt hätte erkennen müssen, etwa mit einem Hinweis des Gerichts. Absolute Grenze: ein Jahr nach Ablauf der versäumten Frist (§ 91 Abs. 5). Die versäumte Handlung ist innerhalb der Antragsfrist nachzuholen (§ 91 Abs. 4); geschieht das, kann die Wiedereinsetzung auch ohne Antrag gewährt werden.",
                 concepts=["wiedereinsetzung", "fristberechnung"], norms=["§ 91 Abs. 2", "§ 91 Abs. 4", "§ 91 Abs. 5"]),
            step("3. Glaubhaftmachung", "Die Tatsachen zur Begründung sind glaubhaft zu machen (§ 91 Abs. 3), regelmäßig durch eidesstattliche Versicherungen der beteiligten Personen, Auszüge aus dem Fristenkalender, Postausgangsbuch und Sendungsnachweise. Nachgeschobene neue Tatsachen nach Ablauf der Antragsfrist bleiben unberücksichtigt.",
                 concepts=["glaubhaftmachung"], norms=["§ 91 Abs. 3"]),
            step("4. Fehlendes Verschulden", "Kernpunkt der Klausur.", concepts=["wiedereinsetzung"], norms=["§ 91 Abs. 1", "§ 82 Abs. 1"], children=[
                step("a) Zurechnung", "Eigenes Verschulden des Beteiligten und Verschulden seines Vertreters (§ 85 Abs. 2 ZPO über § 82 Abs. 1) schaden; Verschulden von Kanzleiangestellten wird nicht zugerechnet.",
                     norms=["§ 82 Abs. 1"]),
                step("b) Sorgfaltspflichten des Anwalts", "Sorgfältige Auswahl, Anleitung und Überwachung des Personals; klare Anweisungen; Ausgangskontrolle, bei der die Frist erst nach Nachweis des Ausgangs gestrichen wird; stichprobenartige Kontrolle. Eigenständig zu erledigen sind die Fristberechnung bei Rechtsmitteln und die Entscheidung über das Zahlungsmittel bei Fristablauf.",
                     cases=["bpatg_silver_horse"]),
                step("c) Anerkannte Entschuldigungsgründe", "Einmaliges Versagen einer bisher zuverlässigen, geschulten Kraft; unvorhersehbare Erkrankung; Postverlust trotz nachgewiesener Absendung; unrichtige Auskunft der Behörde."),
                step("d) Nicht entschuldigt", "Vergessen oder Nichtkennen der Frist; Rechtsirrtum über die Zuständigkeit oder das Zahlungsverfahren; Arbeitsüberlastung; Wahl einer einfachen Überweisung am letzten Tag; fehlende Kontrolle der Postausgangsliste.",
                     concepts=["zahlungstag"]),
            ]),
            step("5. Entscheidung", "Über die Wiedereinsetzung entscheidet die Stelle, die über die versäumte Handlung zu befinden hat (§ 91 Abs. 6); die Entscheidung ist unanfechtbar, wenn die Wiedereinsetzung gewährt wird. Wird sie versagt, ist die Beschwerde als unzulässig zu verwerfen oder festzustellen, dass sie als nicht eingelegt gilt.",
                 norms=["§ 91 Abs. 6", "§ 66"], cases=["bpatg_blizzard_ug"]),
        ],
    ),
]

SCHEMA_INDEX = {s["id"]: s for s in SCHEMATA}
