# -*- coding: utf-8 -*-
"""Leitentscheidungen zum deutschen Patentrecht: BGH (X. und Xa. Zivilsenat) und BPatG.

Quelle: Tabellen BghDecision und BpatgDecision der RheinIP-Datenbank (data/patent_decisions.json). Jede Entscheidung wird beim
Import gegen den Korpus geprüft: Aktenzeichen und Datum müssen dort vorkommen, URL (bundesgerichtshof.de bzw.
bundespatentgericht.de) und ECLI kommen aus der Datenbank. `kern` fasst den Leitsatz in eigenen Worten zusammen.
Felder wie knowledge/cases.py plus `url`; Zitierweise in `norms`: `§ 3 PatG`, `Art. II § 6 IntPatÜG`, `§ 6 PatKostG`.
"""
from . import entscheidungen as _k


def e(id, name, court, date, az, kern, norms=(), concepts=(), tags=(), fundstelle=""):
    rec = _k.by_az(az, date)
    if rec is None:
        raise ValueError(f"Entscheidung {az} vom {date} ({name}) nicht im Korpus data/patent_decisions.json")
    fund = fundstelle or (f"{court}, {rec['typ']} vom {date[8:]}.{date[5:7]}.{date[:4]} – {az}" + (f" – {rec['name']}" if rec.get("name") and rec["name"] != name else ""))
    return dict(id=id, name=name, court=court, date=date, az=az, fundstelle=fund, ecli=rec.get("ecli", ""),
                norms=list(norms), concepts=list(concepts), kern=kern, tags=list(tags), url=rec["url"])


BGH, BPATG = "BGH", "BPatG"

CASES = [
    # ------------------------------------------------------------------ Patentfähigkeit: Technizität, Neuheit, erfinderische Tätigkeit
    e("pat_bgh_steuerungseinrichtung", "Steuerungseinrichtung für Untersuchungsmodalitäten", BGH, "2009-01-20", "X ZB 22/07",
      "Ein Verfahren, das sich einer Datenverarbeitungsanlage bedient, ist jedenfalls dann technisch, wenn es in den Ablauf einer technischen Einrichtung eingebettet ist. Ob die Lehre patentfähig ist, entscheidet sich erst bei Neuheit und erfinderischer Tätigkeit, wo nur die Merkmale zählen, die die Lösung eines technischen Problems mit technischen Mitteln bestimmen.",
      norms=["§ 1 Abs. 1 PatG", "§ 1 Abs. 3 PatG", "§ 1 Abs. 4 PatG"], concepts=["pat_technizitaet", "pat_programme"], tags=["Patentfähigkeit", "Software"]),
    e("pat_bgh_dynamische_dokumentengenerierung", "Dynamische Dokumentengenerierung", BGH, "2010-04-22", "Xa ZB 20/08",
      "Ein Verfahren über das unmittelbare Zusammenwirken der Elemente eines Datenverarbeitungssystems (Server und Client) ist stets technisch. Ob es als Programm „als solches“ vom Patentschutz ausgeschlossen ist, hängt davon ab, ob die Lehre Anweisungen enthält, die die Lösung eines konkreten technischen Problems mit technischen Mitteln zum Gegenstand haben.",
      norms=["§ 1 Abs. 3 Nr. 3 PatG", "§ 1 Abs. 4 PatG"], concepts=["pat_programme", "pat_technizitaet"], tags=["Patentfähigkeit", "Software"]),
    e("pat_bgh_webseitenanzeige", "Webseitenanzeige", BGH, "2011-02-24", "X ZR 121/09",
      "Bei Erfindungen mit Bezug zur Datenverarbeitung ist zweistufig zu prüfen: erst, ob der Gegenstand zumindest mit einem Teilaspekt auf technischem Gebiet liegt (§ 1 Abs. 1), dann, ob er nicht als Programm als solches ausgeschlossen ist, was verlangt, dass ein konkretes technisches Problem mit technischen Mitteln gelöst wird. Nur solche Anweisungen tragen die erfinderische Tätigkeit.",
      norms=["§ 1 Abs. 1 PatG", "§ 1 Abs. 3 Nr. 3 PatG", "§ 4 PatG"], concepts=["pat_programme", "pat_technizitaet", "pat_erfinderische_taetigkeit"], tags=["Patentfähigkeit", "Software"]),
    e("pat_bgh_rezeptortyrosinkinase", "Rezeptortyrosinkinase", BGH, "2016-01-19", "X ZR 141/13",
      "Eine Lehre zum technischen Handeln, die die Nutzung einer Entdeckung zur Herbeiführung eines bestimmten Erfolgs lehrt, ist keine bloße Entdeckung und damit dem Patentschutz zugänglich. Der Ausschluss des § 1 Abs. 3 Nr. 1 greift nur für die Erkenntnis als solche.",
      norms=["§ 1 Abs. 3 Nr. 1 PatG", "§ 1a PatG"], concepts=["pat_technizitaet", "pat_biotech"], tags=["Patentfähigkeit", "Entdeckung"]),
    e("pat_bgh_olanzapin", "Olanzapin", BGH, "2008-12-16", "X ZR 89/07",
      "Neuheitsschädlich ist nur, was dem Fachmann in der Vorveröffentlichung unmittelbar und eindeutig offenbart wird, einschließlich dessen, was er als selbstverständlich mitliest; eine Ergänzung durch Fachwissen ist keine Offenbarung. Eine allgemeine Strukturformel offenbart die darunter fallenden Einzelverbindungen grundsätzlich nicht.",
      norms=["§ 3 Abs. 1 PatG"], concepts=["pat_neuheit", "pat_offenbarung"], tags=["Neuheit", "Offenbarung", "Chemie"]),
    e("pat_bgh_glasfasern", "Glasfasern", BGH, "2011-12-20", "X ZR 53/11",
      "Eine Veröffentlichung, die für eine Produktgruppe nur die Vermutung einer Gesundheitsgefahr äußert, nimmt die Verwendung eines dieser Produkte für einen bestimmten Zweck nicht neuheitsschädlich vorweg, wenn sie dem Fachmann keine Lehre zur Verwendung vermittelt.",
      norms=["§ 3 Abs. 1 PatG"], concepts=["pat_neuheit", "pat_offenbarung"], tags=["Neuheit"]),
    e("pat_bgh_hohlfaserdialysator", "Hohlfaserdialysator", BGH, "2025-05-13", "X ZR 50/23",
      "Verlangt der Anspruch, dass Abmessungen einer mathematischen Formel genügen, ist die Neuheit schon dann genommen, wenn ein vorbekanntes Erzeugnis die Formel erfüllt, auch ohne dass die Formel im Stand der Technik genannt ist. Eine beliebige Auswahl aus mehreren Möglichkeiten begründet keine erfinderische Tätigkeit.",
      norms=["§ 3 PatG", "§ 4 PatG"], concepts=["pat_neuheit", "pat_erfinderische_taetigkeit"], tags=["Neuheit", "Erfinderische Tätigkeit"]),
    e("pat_bgh_fischbissanzeiger", "Fischbissanzeiger", BGH, "2009-06-18", "Xa ZR 138/05",
      "Maßgeblicher Fachmann ist der Konstrukteur mit Erfahrung im betroffenen Gerätebau, nicht der Anwender. Die erfinderische Tätigkeit fehlt nur, wenn der Fachmann eine Veranlassung hatte, den Stand der Technik in Richtung der Erfindung weiterzuentwickeln; das bloße Vorhandensein der Einzelmerkmale im Stand der Technik genügt nicht.",
      norms=["§ 4 PatG"], concepts=["pat_erfinderische_taetigkeit", "pat_fachmann"], tags=["Erfinderische Tätigkeit", "Fachmann"]),
    e("pat_bgh_airbag_ausloesesteuerung", "Airbag-Auslösesteuerung", BGH, "2009-04-30", "Xa ZR 56/05",
      "Dass ein technischer Sachverhalt zum allgemeinen Fachwissen gehört, belegt noch nicht, dass der Fachmann Veranlassung hatte, ihn zur Lösung des Problems heranzuziehen. Es bedarf eines Anlasses im Stand der Technik oder im Fachwissen, der das Naheliegen begründet.",
      norms=["§ 4 PatG"], concepts=["pat_erfinderische_taetigkeit", "pat_fachmann"], tags=["Erfinderische Tätigkeit"]),
    e("pat_bgh_kinderbett", "Kinderbett", BGH, "2018-03-27", "X ZR 59/16",
      "Die generelle Eignung eines zum allgemeinen Fachwissen zählenden Lösungsmittels reicht als Veranlassung nur aus, wenn der Fachmann ohne weiteres erkennt, dass es für den konkreten Fall passt und keine besonderen Umstände entgegenstehen; eine Einzelfallbewertung ist stets erforderlich.",
      norms=["§ 4 PatG"], concepts=["pat_erfinderische_taetigkeit"], tags=["Erfinderische Tätigkeit"]),
    e("pat_bgh_papiermaschinengewebe", "Papiermaschinengewebe", BGH, "2007-05-15", "X ZR 273/02",
      "Die Erfindung darf bei der Prüfung der erfinderischen Tätigkeit nicht anhand von Teilaufgaben in Merkmalsgruppen zerlegt und gruppenweise als naheliegend beurteilt werden; maßgeblich ist, ob der Fachmann die Gesamtheit der Merkmale nahegelegt bekam.",
      norms=["§ 4 PatG"], concepts=["pat_erfinderische_taetigkeit", "pat_aufgabe_loesung"], tags=["Erfinderische Tätigkeit"]),
    e("pat_bgh_gleitlagerueberwachung", "Gleitlagerüberwachung", BGH, "2010-08-31", "X ZR 73/08",
      "Kritik in der Beschreibung des Streitpatents am Lösungsweg einer Vorveröffentlichung kann darauf hindeuten, dass der Fachmann Anlass hatte, diesen Weg zu verlassen; die Beschreibung darf aber nicht als Beleg für das Naheliegen missbraucht werden (Rückschau).",
      norms=["§ 4 PatG"], concepts=["pat_erfinderische_taetigkeit"], tags=["Erfinderische Tätigkeit"]),
    e("pat_bgh_einteilige_oese", "Einteilige Öse", BGH, "2009-12-08", "X ZR 65/05",
      "Das Auffinden einer neuen technischen Lehre ist nicht schon deshalb naheliegend, weil der Fachmann die Lösung im Wege einfacher Überlegungen hätte finden können; es kommt darauf an, ob er Grund hatte, diese Überlegungen anzustellen.",
      norms=["§ 4 PatG"], concepts=["pat_erfinderische_taetigkeit"], tags=["Erfinderische Tätigkeit"]),
    e("pat_bgh_farbversorgungssystem", "Farbversorgungssystem", BGH, "2014-03-11", "X ZR 139/10",
      "Gehört eine maschinenbautechnische Lösung als generelles, für viele Anwendungsfälle in Betracht zu ziehendes Mittel zum allgemeinen Fachwissen, kann ihre Heranziehung naheliegend sein, wenn sich aus der Aufgabe der Anlass ergibt, nach solchen Mitteln zu suchen.",
      norms=["§ 4 PatG"], concepts=["pat_erfinderische_taetigkeit", "pat_fachmann"], tags=["Erfinderische Tätigkeit"]),
    e("pat_bgh_escitalopram", "Escitalopram", BGH, "2009-09-10", "Xa ZR 130/07",
      "Ein Stoff, der als Enantiomer eines bekannten Racemats gewünscht war, ist neu und erfinderisch, wenn der Fachmann keinen gangbaren Weg zu seiner Bereitstellung kannte; die Bereitstellung selbst ist dann die erfinderische Leistung, nicht nur das Verfahren.",
      norms=["§ 3 PatG", "§ 4 PatG", "§ 16a PatG"], concepts=["pat_erfinderische_taetigkeit", "pat_neuheit", "pat_schutzzertifikat"], tags=["Erfinderische Tätigkeit", "Chemie", "ESZ"]),
    e("pat_bgh_carvedilol_ii", "Carvedilol II", BGH, "2006-12-19", "X ZR 236/01",
      "Die Verabreichung eines Arzneimittels zur Behandlung einer Krankheit ist ein therapeutisches Verfahren und als solches vom Patentschutz ausgeschlossen; geschützt werden kann nur der zweckgebundene Stoff (zweite medizinische Indikation) oder die sinnfällige Herrichtung.",
      norms=["§ 5 Abs. 2 PatG", "§ 2a Abs. 1 Nr. 2 PatG", "§ 3 Abs. 4 PatG"], concepts=["pat_therapeutische_verfahren", "pat_zweite_indikation"], tags=["Patentfähigkeit", "Medizin"]),
    # ------------------------------------------------------------------ Schutzbereich, Auslegung, Äquivalenz
    e("pat_bgh_schneidmesser_i", "Schneidmesser I", BGH, "2002-03-12", "X ZR 168/00",
      "Zahlen- und Maßangaben im Patentanspruch begrenzen den Schutzgegenstand mit; sie sind wie jedes Merkmal auszulegen. Eine Verletzung mit äquivalenten Mitteln setzt voraus, dass die Abwandlung gleichwirkend ist, der Fachmann sie aufgrund seiner Fachkenntnisse auffinden konnte und seine Überlegungen am Sinngehalt des Anspruchs orientiert waren (drei Schneidmesser-Fragen).",
      norms=["§ 14 PatG"], concepts=["pat_schutzbereich", "pat_aequivalenz"], tags=["Schutzbereich", "Äquivalenz"]),
    e("pat_bgh_custodiol_ii", "Custodiol II", BGH, "2002-03-12", "X ZR 73/01",
      "Zahlen- und Maßangaben sind nicht von vornherein einer äquivalenten Verletzung entzogen; auch hier gelten die Schneidmesser-Fragen, doch wird der Fachmann die Angabe regelmäßig als abschließende Festlegung verstehen, so dass Abweichungen selten gleichwertig sind.",
      norms=["§ 14 PatG"], concepts=["pat_aequivalenz", "pat_schutzbereich"], tags=["Schutzbereich", "Äquivalenz"]),
    e("pat_bgh_kunststoffrohrteil", "Kunststoffrohrteil", BGH, "2002-03-12", "X ZR 43/01",
      "Für den Schutzbereich kommt es grundsätzlich nicht auf Vorgänge im Erteilungsverfahren an; Beschränkungen im Erteilungsverfahren wirken nur, soweit sie in der Patentschrift Niederschlag gefunden haben. Die Patentschrift ist ihr eigenes Lexikon.",
      norms=["§ 14 PatG"], concepts=["pat_schutzbereich", "pat_auslegung"], tags=["Schutzbereich", "Auslegung"]),
    e("pat_bgh_bodenseitige_vereinzelungseinrichtung", "Bodenseitige Vereinzelungseinrichtung", BGH, "2004-09-07", "X ZR 255/01",
      "Ein Ausführungsbeispiel erlaubt regelmäßig keine einschränkende Auslegung eines allgemein gefassten Patentanspruchs; die Beschreibung dient der Erläuterung, nicht der Beschränkung des Anspruchs.",
      norms=["§ 14 PatG"], concepts=["pat_auslegung", "pat_schutzbereich"], tags=["Auslegung"]),
    e("pat_bgh_drehzahlermittlung", "Drehzahlermittlung", BGH, "2004-06-03", "X ZR 82/03",
      "Die Feststellung, welchen Sinngehalt der Fachmann den Anspruchsmerkmalen entnimmt, muss stets den Gesamtzusammenhang des Anspruchs und die Funktion der Merkmale im Kontext der erfindungsgemäßen Lösung berücksichtigen (funktionsorientierte Auslegung).",
      norms=["§ 14 PatG"], concepts=["pat_auslegung"], tags=["Auslegung"]),
    e("pat_bgh_okklusionsvorrichtung", "Okklusionsvorrichtung", BGH, "2011-05-10", "X ZR 16/09",
      "Bei Widersprüchen zwischen Anspruch und Beschreibung haben die Ansprüche Vorrang. Offenbart die Beschreibung mehrere Wege zu einer Wirkung, von denen nur einer beansprucht ist, fehlt für den nicht beanspruchten Weg die Gleichwertigkeit: Die Auswahlentscheidung des Patentinhabers schließt die Äquivalenz aus.",
      norms=["§ 14 PatG"], concepts=["pat_aequivalenz", "pat_auslegung", "pat_schutzbereich"], tags=["Äquivalenz", "Auslegung"]),
    e("pat_bgh_diglycidverbindung", "Diglycidverbindung", BGH, "2011-09-13", "X ZR 69/10",
      "Offenbart die Beschreibung mehrere Möglichkeiten, eine technische Wirkung zu erzielen, ist aber nur eine in den Anspruch aufgenommen, so ist die Benutzung einer anderen Möglichkeit regelmäßig keine äquivalente Verletzung (Bestätigung von Okklusionsvorrichtung).",
      norms=["§ 14 PatG"], concepts=["pat_aequivalenz"], tags=["Äquivalenz"]),
    e("pat_bgh_pemetrexed", "Pemetrexed", BGH, "2016-06-14", "X ZR 29/15",
      "Eine äquivalente Verletzung ist in der Regel zu verneinen, wenn die Beschreibung mehrere Wege offenbart und nur einer beansprucht ist. Anders liegt es, wenn die Beschreibung nur beispielhaft einen Weg nennt und der Fachmann die Abwandlung als gleichwertig erkennt; der Ausschluss gilt nicht für Abwandlungen, die die Beschreibung gar nicht anspricht.",
      norms=["§ 14 PatG"], concepts=["pat_aequivalenz", "pat_schutzbereich"], tags=["Äquivalenz", "Pharma"]),
    e("pat_bgh_v_foermige_fuehrungsanordnung", "V-förmige Führungsanordnung", BGH, "2016-08-23", "X ZR 76/14",
      "Die Überlegungen des Fachmanns zum Auffinden eines gleichwirkenden Austauschmittels müssen am Patentanspruch orientiert sein; ein Mittel, das der Fachmann nur aufgrund einer abweichenden, vom Anspruch wegführenden Lösungsidee findet, ist nicht gleichwertig.",
      norms=["§ 14 PatG"], concepts=["pat_aequivalenz"], tags=["Äquivalenz"]),
    e("pat_bgh_palettenbehaelter_iii", "Palettenbehälter III", BGH, "2012-07-17", "X ZR 113/11",
      "Gleichwirkend ist eine abweichende Lösung nur, wenn sie nicht nur die Gesamtwirkung der Erfindung im Wesentlichen erreicht, sondern gerade auch die Wirkung, die das nicht wortsinngemäß verwirklichte Merkmal beitragen soll.",
      norms=["§ 14 PatG"], concepts=["pat_aequivalenz"], tags=["Äquivalenz"]),
    e("pat_bgh_kreuzgestaenge", "Kreuzgestänge", BGH, "2015-06-02", "X ZR 103/13",
      "Das Verletzungsgericht legt das Klagepatent selbständig aus und ist an die Auslegung im Nichtigkeitsverfahren weder rechtlich noch tatsächlich gebunden; es muss sich aber mit ihr auseinandersetzen.",
      norms=["§ 14 PatG", "§ 143 PatG"], concepts=["pat_auslegung", "pat_trennungsprinzip"], tags=["Auslegung", "Trennungsprinzip"]),
    e("pat_bgh_scheinwerferbelueftungssystem", "Scheinwerferbelüftungssystem", BGH, "2018-11-27", "X ZR 16/17",
      "Bei der Auslegung ist zu berücksichtigen, dass sich ein Patent mit seiner Lehre vom beschriebenen Stand der Technik abgrenzen will; ein Merkmal ist im Zweifel so zu verstehen, dass es diese Abgrenzung leistet.",
      norms=["§ 14 PatG"], concepts=["pat_auslegung"], tags=["Auslegung"]),
    e("pat_bgh_referenzkontur", "Referenzkontur", BGH, "2026-06-09", "X ZR 35/24",
      "Zweck-, Wirkungs- und Funktionsangaben in Verfahrensansprüchen führen nicht zwingend dazu, dass das Verfahren zu dem angegebenen Zweck eingesetzt werden muss; ob eine Angabe das Verfahren definiert oder nur beispielhaft ist, ist durch Auslegung zu klären.",
      norms=["§ 14 PatG"], concepts=["pat_auslegung", "pat_zweckangabe"], tags=["Auslegung"]),
    e("pat_bgh_bildunterstuetzung_katheternavigation", "Bildunterstützung bei Katheternavigation", BGH, "2010-08-31", "X ZB 9/09",
      "Zweck-, Wirkungs- oder Funktionsangaben im Anspruch beziehen sich nicht zwangsläufig auf den Gegenstand des Anspruchs; sie können ihn aber mittelbar definieren, indem sie verlangen, dass die Vorrichtung so ausgebildet ist, dass sie die Funktion erfüllen kann.",
      norms=["§ 14 PatG", "§ 34 Abs. 3 Nr. 3 PatG"], concepts=["pat_zweckangabe", "pat_auslegung"], tags=["Auslegung"]),
    # ------------------------------------------------------------------ Wirkung, Verletzung, Schranken, Erschöpfung
    e("pat_bgh_fluegelradzaehler", "Flügelradzähler", BGH, "2004-05-04", "X ZR 48/03",
      "Ein Mittel bezieht sich auf ein wesentliches Element der Erfindung, wenn es geeignet ist, mit einem oder mehreren Anspruchsmerkmalen bei der Verwirklichung der Lehre funktional zusammenzuwirken; die subjektiven Voraussetzungen der mittelbaren Verletzung (Wissen oder Offensichtlichkeit) sind aus der Sicht des Anbieters zu prüfen.",
      norms=["§ 10 Abs. 1 PatG", "§ 9 PatG"], concepts=["pat_mittelbare_verletzung"], tags=["Verletzung", "Mittelbare Verletzung"]),
    e("pat_bgh_fraesverfahren", "Fräsverfahren", BGH, "2013-05-07", "X ZR 69/11",
      "Bei mittelbarer Patentverletzung setzt die Feststellung der Schadensersatzpflicht die Wahrscheinlichkeit voraus, dass der Abnehmer die Erfindung unmittelbar benutzt hat; der Schaden liegt in der unmittelbaren Benutzung, nicht schon in der Lieferung.",
      norms=["§ 10 Abs. 1 PatG", "§ 139 Abs. 2 PatG"], concepts=["pat_mittelbare_verletzung", "pat_schadensersatz"], tags=["Mittelbare Verletzung", "Schadensersatz"]),
    e("pat_bgh_abgasreinigungsvorrichtung", "Abgasreinigungsvorrichtung", BGH, "2005-07-05", "X ZR 14/03",
      "Die sinnfällige Herrichtung einer Vorrichtung zur Ausübung eines patentierten Verfahrens ist noch keine Anwendung des Verfahrens (§ 9 S. 2 Nr. 2); sie kann aber Anbieten zur Anwendung oder mittelbare Verletzung sein.",
      norms=["§ 9 PatG", "§ 10 PatG"], concepts=["pat_benutzungshandlungen", "pat_mittelbare_verletzung"], tags=["Verletzung", "Verfahrensanspruch"]),
    e("pat_bgh_palettenbehaelter_ii", "Palettenbehälter II", BGH, "2012-07-17", "X ZR 97/11",
      "Erschöpfung: Gehört der Austausch eines Bestandteils zum bestimmungsgemäßen Gebrauch eines in Verkehr gebrachten Erzeugnisses, darf ihn auch ein Dritter vornehmen. Anders, wenn sich gerade in dem ausgetauschten Teil die technischen Wirkungen der Erfindung widerspiegeln; dann liegt eine unzulässige Neuherstellung vor.",
      norms=["§ 9 PatG"], concepts=["pat_erschoepfung", "pat_benutzungshandlungen"], tags=["Erschöpfung", "Reparatur"]),
    e("pat_bgh_trommeleinheit", "Trommeleinheit", BGH, "2017-10-24", "X ZR 55/16",
      "Beim Austausch von Teilen eines patentgeschützten Erzeugnisses entscheidet zunächst die Verkehrsauffassung, ob der Austausch üblicher Erhalt oder Neuherstellung ist; bei Verbrauchsmaterial kommt es darauf an, ob die technischen Wirkungen der Erfindung gerade im ausgetauschten Teil liegen.",
      norms=["§ 9 PatG"], concepts=["pat_erschoepfung"], tags=["Erschöpfung", "Reparatur"]),
    e("pat_bgh_rezeptortyrosinkinase_ii", "Rezeptortyrosinkinase II", BGH, "2016-09-27", "X ZR 124/15",
      "Eine Datenfolge kommt nur dann als unmittelbares Verfahrenserzeugnis in Betracht, wenn sie als körperlich fassbares Erzeugnis mit technischen Eigenschaften anzusehen ist; das Ergebnis eines Analyseverfahrens (Information) ist kein Erzeugnis im Sinne des § 9 S. 2 Nr. 3.",
      norms=["§ 9 PatG", "§ 1 Abs. 3 Nr. 4 PatG"], concepts=["pat_benutzungshandlungen", "pat_verfahrenserzeugnis"], tags=["Verletzung", "Verfahrenserzeugnis"]),
    e("pat_bgh_wasserdichter_lederschuh", "Wasserdichter Lederschuh", BGH, "2018-01-30", "X ZR 27/16",
      "Ist nach dem geschützten Verfahren ein Halbzeug in bestimmter Weise zu bearbeiten, erstreckt sich der Schutz des unmittelbaren Verfahrenserzeugnisses auf das bearbeitete Halbzeug, nicht ohne weiteres auf das aus ihm hergestellte Endprodukt.",
      norms=["§ 9 PatG"], concepts=["pat_verfahrenserzeugnis"], tags=["Verletzung", "Verfahrenserzeugnis"]),
    e("pat_bgh_tintenpatrone", "Tintenpatrone", BGH, "2008-05-20", "X ZR 180/05",
      "Der Unterlassungsanspruch aus dem Patent besteht auch gegen den Vertrieb von Erzeugnissen, die der Patentinhaber oder mit seiner Zustimmung ein Dritter außerhalb des EWR in Verkehr gebracht hat; die Erschöpfung ist auf das Inverkehrbringen im EWR beschränkt.",
      norms=["§ 9 PatG", "§ 139 Abs. 1 PatG"], concepts=["pat_erschoepfung", "pat_unterlassung"], tags=["Erschöpfung", "Parallelimport"]),
    e("pat_bgh_raffvorhang", "Raffvorhang", BGH, "2011-01-25", "X ZR 69/08",
      "Gleichartig im Sinne der Klagekonzentration des § 145 PatG sind nur Handlungen, die gegenüber der zuerst angegriffenen Handlung zusätzliche oder abgewandelte Merkmale aufweisen; die Vorschrift ist eng auszulegen.",
      norms=["§ 145 PatG"], concepts=["pat_klagekonzentration"], tags=["Verletzungsprozess"]),
    e("pat_bgh_restschadstoffentfernung", "Restschadstoffentfernung", BGH, "2006-08-01", "X ZR 114/03",
      "Die Vorlageanordnung nach § 142 ZPO ist im Patentverletzungsprozess auch im Licht der Durchsetzungsrichtlinie großzügig anzuwenden; Geschäftsgeheimnisse rechtfertigen keine generelle Verweigerung, sondern sind durch Verfahrensgestaltung zu schützen.",
      norms=["§ 140c PatG"], concepts=["pat_besichtigung"], tags=["Beweis", "Besichtigung"]),
    e("pat_bgh_klimaschrank", "Klimaschrank", BGH, "2011-09-28", "X ZR 68/10",
      "Auch im Verfahren über die Nichtzulassungsbeschwerde kann der Verletzungsprozess nach § 148 ZPO im Hinblick auf eine Nichtigkeitsklage ausgesetzt werden; maßgeblich ist, ob die Vernichtung des Klagepatents hinreichend wahrscheinlich ist.",
      norms=["§ 81 PatG", "§ 139 PatG"], concepts=["pat_trennungsprinzip", "pat_aussetzung"], tags=["Trennungsprinzip", "Aussetzung"]),
    e("pat_bgh_adalimumab", "Adalimumab", BGH, "2026-08-07", "X ZR 36/25",
      "Auch wenn die Nichtigkeitsklage erst nach dem Berufungsurteil im Verletzungsprozess erhoben wurde, kommt eine Aussetzung des Nichtzulassungsbeschwerdeverfahrens ausnahmsweise in Betracht, wenn besondere Umstände dies rechtfertigen.",
      norms=["§ 81 PatG"], concepts=["pat_aussetzung", "pat_trennungsprinzip"], tags=["Aussetzung"]),
    # ------------------------------------------------------------------ Anmeldung, Offenbarung, unzulässige Erweiterung, Priorität
    e("pat_bgh_hubgliedertor_i", "Hubgliedertor I", BGH, "2009-12-22", "X ZR 27/06",
      "Eine unzulässige Erweiterung liegt vor, wenn sich der Gegenstand des Patents für den Fachmann erst aufgrund eigener, von seinem Fachwissen getragener Überlegungen aus den ursprünglichen Unterlagen ergibt; Maßstab ist, was als zur Erfindung gehörend unmittelbar und eindeutig offenbart war.",
      norms=["§ 21 Abs. 1 Nr. 4 PatG", "§ 22 Abs. 1 PatG", "§ 38 PatG"], concepts=["pat_unzulaessige_erweiterung", "pat_offenbarung"], tags=["Unzulässige Erweiterung"]),
    e("pat_bgh_winkelmesseinrichtung", "Winkelmesseinrichtung", BGH, "2010-10-21", "Xa ZB 14/09",
      "Ein nicht ursprünglich offenbartes Merkmal, das den Anspruch nur beschränkt (Aliud ausgeschlossen), führt nicht zwingend zum Widerruf: Das Merkmal bleibt im Anspruch, darf aber bei der Prüfung der Patentfähigkeit nicht zugunsten des Inhabers berücksichtigt werden (uneigentliche Erweiterung).",
      norms=["§ 21 Abs. 1 Nr. 4 PatG", "§ 21 Abs. 2 PatG"], concepts=["pat_unzulaessige_erweiterung"], tags=["Unzulässige Erweiterung", "Einspruch"]),
    e("pat_bgh_rotorelemente", "Rotorelemente", BGH, "2015-05-12", "X ZR 43/13",
      "Der Prüfung einer unzulässigen Erweiterung muss die Auslegung des geänderten Anspruchs vorausgehen. Bei der Ermittlung des Offenbarungsgehalts der Anmeldung ist wie bei der Auslegung zu fragen, was der Fachmann der Gesamtheit der Unterlagen als zur Erfindung gehörend entnimmt.",
      norms=["§ 38 PatG", "§ 14 PatG", "§ 21 Abs. 1 Nr. 4 PatG"], concepts=["pat_unzulaessige_erweiterung", "pat_offenbarung", "pat_auslegung"], tags=["Unzulässige Erweiterung"]),
    e("pat_bgh_wundbehandlungsvorrichtung", "Wundbehandlungsvorrichtung", BGH, "2015-02-17", "X ZR 161/12",
      "Ein europäisches Patent ist nicht wegen unzulässiger Erweiterung für nichtig zu erklären, wenn der Anspruch ein ursprünglich nicht offenbartes beschränkendes Merkmal enthält; das Merkmal bleibt im Anspruch und ist bei der Prüfung der Patentfähigkeit außer Acht zu lassen (Übertragung von Winkelmesseinrichtung auf Art. II § 6 IntPatÜG).",
      norms=["Art. II § 6 Abs. 1 Nr. 3 IntPatÜG", "§ 21 Abs. 1 Nr. 4 PatG"], concepts=["pat_unzulaessige_erweiterung", "pat_nichtigkeit_ep"], tags=["Unzulässige Erweiterung", "Europäisches Patent"]),
    e("pat_bgh_ueberbruecktes_netzwerk", "Überbrücktes Netzwerk", BGH, "2026-07-28", "X ZR 98/24",
      "Der Hinweis in der Anmeldung, dass einzelne Verfahrensschritte eines Ausführungsbeispiels nicht zwingend sind, offenbart nicht ein Verfahren, bei dem diese Schritte durch eine konkrete andere Vorgehensweise ersetzt werden; Weglassen ist nicht Ersetzen.",
      norms=["Art. II § 6 Abs. 1 Nr. 3 IntPatÜG", "§ 21 Abs. 1 Nr. 4 PatG"], concepts=["pat_unzulaessige_erweiterung", "pat_offenbarung"], tags=["Unzulässige Erweiterung"]),
    e("pat_bgh_einkaufswagen_ii", "Einkaufswagen II", BGH, "2005-07-05", "X ZR 30/02",
      "Ob der Gegenstand der erteilten Ansprüche über den Inhalt der Anmeldung hinausgeht, ist durch Vergleich des Anspruchsgegenstands mit dem Gesamtinhalt der ursprünglichen Unterlagen zu ermitteln; auch Verallgemeinerungen von Ausführungsbeispielen sind zulässig, wenn sie als zur Erfindung gehörend erkennbar waren.",
      norms=["Art. II § 6 Abs. 1 Nr. 3 IntPatÜG", "§ 38 PatG"], concepts=["pat_unzulaessige_erweiterung", "pat_offenbarung"], tags=["Unzulässige Erweiterung"]),
    e("pat_bgh_phosphatidylcholin", "Phosphatidylcholin", BGH, "2017-07-25", "X ZB 5/16",
      "Eine Anmeldung ist zurückzuweisen, wenn der zur Prüfung gestellte Anspruch über den Inhalt der ursprünglichen Anmeldung hinausgeht; der Anmelder kann nicht verlangen, dass das DPMA das Patent mit einem anderen, zulässigen Anspruch erteilt.",
      norms=["§ 38 PatG", "§ 48 PatG"], concepts=["pat_unzulaessige_erweiterung", "pat_pruefungsverfahren"], tags=["Erteilungsverfahren"]),
    e("pat_bgh_sammelhefter", "Sammelhefter", BGH, "2002-09-30", "X ZB 18/01",
      "Die wirksame Teilung eines Patents setzt nicht voraus, dass die Teilungserklärung einen gegenständlich bestimmten Teil des Patents definiert; die Teilanmeldung wird mit der Erklärung selbständig und kann später mit Ansprüchen aus dem Gesamtinhalt der Stammanmeldung weiterverfolgt werden.",
      norms=["§ 60 Abs. 1 PatG", "§ 39 PatG"], concepts=["pat_teilung"], tags=["Teilung", "Einspruch"]),
    e("pat_bgh_fahrzeugscheibe", "Fahrzeugscheibe", BGH, "2013-04-16", "X ZR 49/12",
      "Das Recht auf Inanspruchnahme der Priorität einer deutschen Anmeldung kann formlos übertragen werden, auch für eine europäische Nachanmeldung; die Übertragung muss aber vor der Nachanmeldung erfolgt sein.",
      norms=["§ 41 PatG", "§ 40 PatG"], concepts=["pat_prioritaet"], tags=["Priorität"]),
    e("pat_bgh_kommunikationskanal", "Kommunikationskanal", BGH, "2014-02-11", "X ZR 107/12",
      "Die Priorität einer Voranmeldung kann in Anspruch genommen werden, wenn sich die Erfindung der Nachanmeldung für den Fachmann aus der Voranmeldung als zur Erfindung gehörend ergibt; es gilt derselbe Offenbarungsmaßstab wie bei der unzulässigen Erweiterung, kein „Photographie“-Erfordernis.",
      norms=["§ 41 PatG", "§ 40 PatG"], concepts=["pat_prioritaet", "pat_offenbarung"], tags=["Priorität"]),
    e("pat_bgh_thermoplastische_zusammensetzung", "Thermoplastische Zusammensetzung", BGH, "2010-02-25", "Xa ZR 100/05",
      "Die Ausführbarkeit fehlt, wenn der Fachmann den beanspruchten Gegenstand nur mit unzumutbarem Aufwand oder nur durch eigene erfinderische Leistung verwirklichen kann; ein durch Parameter definierter Stoff ist ausführbar offenbart, wenn der Fachmann die Parameter mit den Angaben der Patentschrift einstellen kann.",
      norms=["Art. II § 6 Abs. 1 Nr. 2 IntPatÜG", "§ 21 Abs. 1 Nr. 2 PatG"], concepts=["pat_ausfuehrbarkeit"], tags=["Ausführbarkeit"]),
    e("pat_bpatg_imidazolinpyrimidon", "Imidazolinpyrimidon-Verbindung", BPATG, "2026-04-28", "3 Ni 7/24 (EP)",
      "Ist ein neuer Stoff beansprucht, ist ein weiterer Anspruch auf dessen medizinische Verwendung schon deshalb ausführbar, weil er durch den absoluten Stoffschutz unterlegt ist; eines gesonderten Wirksamkeitsnachweises bedarf es nicht.",
      norms=["Art. II § 6 Abs. 1 Nr. 2 IntPatÜG"], concepts=["pat_ausfuehrbarkeit", "pat_nichtigkeit_ep"], tags=["Ausführbarkeit", "Pharma"]),
    # ------------------------------------------------------------------ Einspruch, Nichtigkeit, Beschränkung
    e("pat_bgh_ratschenschluessel", "Ratschenschlüssel", BGH, "2017-08-29", "X ZB 3/15",
      "Dem Einspruchsverfahren kann auch beitreten, gegen wen der Patentinhaber wegen Verletzung den Erlass einer einstweiligen Verfügung beantragt hat; die Verletzungsklage im Sinne des § 59 Abs. 2 umfasst das Verfügungsverfahren.",
      norms=["§ 59 Abs. 2 PatG"], concepts=["pat_einspruch", "pat_beitritt"], tags=["Einspruch"]),
    e("pat_bgh_leistungshalbleiterbauelement", "Leistungshalbleiterbauelement", BGH, "2009-07-30", "Xa ZB 28/08",
      "Ein auf mangelnde Patentfähigkeit gestützter Einspruch ist zulässig, wenn er die Tatsachen, aus denen sich der Widerrufsgrund ergibt, so vollständig angibt, dass Patentabteilung und Inhaber daraus abschließende Folgerungen ziehen können; die Berufung auf eine ältere Anmeldung nach § 3 Abs. 2 genügt.",
      norms=["§ 59 Abs. 1 PatG", "§ 61 Abs. 2 PatG", "§ 100 Abs. 1 PatG"], concepts=["pat_einspruch"], tags=["Einspruch", "Zulässigkeit"]),
    e("pat_bgh_ventileinrichtung", "Ventileinrichtung", BGH, "2016-11-08", "X ZB 1/16",
      "Das Patentgericht darf im Einspruchsbeschwerdeverfahren nicht von Amts wegen neue Widerrufsgründe einführen, die nicht Gegenstand des Einspruchs oder des Beschwerdevorbringens waren; der Streitgegenstand wird durch die geltend gemachten Widerrufsgründe begrenzt.",
      norms=["§ 21 Abs. 1 PatG", "§ 59 PatG", "§ 73 PatG", "§ 79 PatG"], concepts=["pat_einspruch", "pat_beschwerde"], tags=["Einspruch", "Beschwerde"]),
    e("pat_bgh_schwingungsdaempfer", "Schwingungsdämpfer", BGH, "2009-09-22", "Xa ZB 36/08",
      "Verteidigt der Patentinhaber im Einspruch nur einen von zwei nebengeordneten Ansprüchen, muss das Gericht ihn darauf hinweisen, wenn es den verteidigten Anspruch für nicht schutzfähig hält; sonst verletzt es das rechtliche Gehör (absoluter Rechtsbeschwerdegrund).",
      norms=["§ 100 Abs. 3 Nr. 3 PatG"], concepts=["pat_rechtsbeschwerde", "pat_rechtliches_gehoer"], tags=["Rechtsbeschwerde", "Rechtliches Gehör"]),
    e("pat_bgh_sensoranordnung", "Sensoranordnung", BGH, "2011-09-29", "X ZR 109/08",
      "Erweist sich der Gegenstand eines Anspruchs als nicht patentfähig, führt das nicht ohne weiteres zur Nichtigkeit nebengeordneter Ansprüche; der Patentinhaber kann das Patent mit den übrigen Ansprüchen verteidigen, und das Gericht muss über jeden angegriffenen Anspruch entscheiden.",
      norms=["§ 22 PatG", "§ 81 PatG", "§ 84 PatG", "Art. II § 6 IntPatÜG"], concepts=["pat_nichtigkeitsklage", "pat_beschraenkte_verteidigung"], tags=["Nichtigkeit"]),
    e("pat_bgh_fugenband", "Fugenband", BGH, "2015-10-27", "X ZR 11/13",
      "Mangelnde Klarheit ist kein Nichtigkeitsgrund. Verteidigt der Patentinhaber das Patent im Nichtigkeitsverfahren beschränkt, ist die Klarheit des beschränkten Anspruchs jedenfalls dann nicht zu prüfen, wenn die aufgenommenen Merkmale bereits in erteilten Ansprüchen enthalten waren.",
      norms=["Art. II § 6 Abs. 3 IntPatÜG", "§ 22 PatG"], concepts=["pat_nichtigkeitsklage", "pat_beschraenkte_verteidigung", "pat_nichtigkeitsgruende"], tags=["Nichtigkeit", "Klarheit"]),
    e("pat_bgh_polymerschaum", "Polymerschaum", BGH, "2012-07-17", "X ZR 117/11",
      "Die Prüfung der Patentfähigkeit im Nichtigkeitsverfahren setzt regelmäßig eine Auslegung des Anspruchs voraus, die seinen Sinngehalt in der Gesamtheit und den Beitrag der einzelnen Merkmale zum Leistungsergebnis bestimmt; das Nichtigkeitsurteil muss diese Auslegung erkennen lassen.",
      norms=["§ 81 PatG", "§ 14 PatG"], concepts=["pat_nichtigkeitsklage", "pat_auslegung"], tags=["Nichtigkeit", "Auslegung"]),
    e("pat_bgh_walzstrasse", "Walzstraße", BGH, "2013-05-28", "X ZR 21/12",
      "Lässt das Patentgericht im Hinweis nach § 83 Abs. 1 erkennen, dass es einen Angriff des Nichtigkeitsklägers für unbegründet hält, muss der Kläger neue Angriffsmittel innerhalb der gesetzten Frist vorbringen; in der Berufung sind sie nach § 117 ausgeschlossen, wenn die Verspätung auf Nachlässigkeit beruht.",
      norms=["§ 83 PatG", "§ 117 PatG"], concepts=["pat_nichtigkeitsklage", "pat_qualifizierter_hinweis", "pat_nichtigkeitsberufung"], tags=["Nichtigkeit", "Präklusion"]),
    e("pat_bgh_fahrzeugscheibe_ii", "Fahrzeugscheibe II", BGH, "2016-06-21", "X ZR 41/14",
      "Die hilfsweise Verteidigung mit geänderten Ansprüchen in der Berufungsinstanz ist sachdienlich, wenn das Patentgericht den Beklagten erst in der mündlichen Verhandlung mit einer vom Hinweis abweichenden Beurteilung konfrontiert hat.",
      norms=["§ 116 Abs. 2 PatG", "§ 83 PatG"], concepts=["pat_nichtigkeitsberufung", "pat_beschraenkte_verteidigung"], tags=["Nichtigkeit", "Berufung"]),
    e("pat_bgh_benutzerauthentifizierung", "Benutzerauthentifizierung", BGH, "2026-06-02", "X ZR 65/24",
      "Eine Nichtigkeitsklage ist nicht schon deshalb rechtsmissbräuchlich, weil sich der Kläger einem anhängigen Verfahren gegen dasselbe Patent hätte anschließen können; die Popularklage steht jedem offen. Kostenfolgen bei parallelen Klagen richten sich nach § 84 Abs. 2 und § 121 Abs. 2.",
      norms=["§ 81 PatG", "§ 84 Abs. 2 PatG", "§ 121 Abs. 2 PatG"], concepts=["pat_nichtigkeitsklage"], tags=["Nichtigkeit", "Popularklage"]),
    e("pat_bgh_pemetrexed_ii", "Pemetrexed II", BGH, "2020-07-07", "X ZR 150/18",
      "Im Nichtigkeitsverfahren ist die Nebenintervention auf Seiten des Klägers auch in der Berufungsinstanz zulässig; sie scheitert nicht daran, dass der Nebenintervenient das Patent mit eigener Klage angreifen könnte.",
      norms=["§ 81 PatG", "§ 99 Abs. 1 PatG"], concepts=["pat_nichtigkeitsklage", "pat_nebenintervention"], tags=["Nichtigkeit", "Nebenintervention"]),
    e("pat_bgh_streitwert_nichtigkeitsberufung", "Streitwert im Nichtigkeitsberufungsverfahren", BGH, "2005-07-12", "X ZR 56/04",
      "Der Streitwert der Nichtigkeitsberufung bemisst sich nach dem gemeinen Wert des Patents im angegriffenen Umfang; wird nach teilweiser Nichtigerklärung nur noch der aufrechterhaltene Teil angegriffen, ist der Wert entsprechend geringer anzusetzen.",
      norms=["§ 121 PatG", "§ 2 Abs. 2 PatKostG"], concepts=["pat_streitwert"], tags=["Streitwert", "Kosten"]),
    e("pat_bgh_raltegravir", "Raltegravir", BGH, "2017-07-11", "X ZB 2/17",
      "Zwangslizenz im Verfügungsverfahren: Der Lizenzsucher muss sich innerhalb angemessener Zeit ernsthaft um eine Lizenz zu angemessenen Bedingungen bemüht haben; das öffentliche Interesse kann bei einem Arzneimittel bejaht werden, das für bestimmte Patientengruppen ohne gleichwertige Alternative ist (Isentress).",
      norms=["§ 24 Abs. 1 PatG", "§ 85 Abs. 1 PatG"], concepts=["pat_zwangslizenz"], tags=["Zwangslizenz", "Pharma"]),
    e("pat_bgh_alirocumab", "Alirocumab", BGH, "2019-06-04", "X ZB 2/19",
      "Umfang und Dauer der Bemühungen des Lizenzsuchers hängen vom Einzelfall ab; ein erst kurz vor dem Verfügungsantrag unterbreitetes Angebot genügt in der Regel nicht. Das öffentliche Interesse verlangt, dass das Arzneimittel therapeutische Eigenschaften hat, die andere Mittel nicht bieten.",
      norms=["§ 24 Abs. 1 PatG", "§ 85 PatG"], concepts=["pat_zwangslizenz"], tags=["Zwangslizenz", "Pharma"]),
    e("pat_bgh_carvedilol_nebenintervention", "Carvedilol (Nebenintervention)", BGH, "2006-01-17", "X ZR 236/01",
      "Für die Nebenintervention im Nichtigkeitsverfahren genügt es, wenn der Nebenintervenient ein Unternehmen betreibt, das durch das Patent behindert wird; das rechtliche Interesse nach § 66 ZPO ist weit zu verstehen.",
      norms=["§ 81 PatG", "§ 99 Abs. 1 PatG"], concepts=["pat_nebenintervention", "pat_nichtigkeitsklage"], tags=["Nichtigkeit", "Nebenintervention"]),
    e("pat_bpatg_torasemid", "Torasemid", BPATG, "2006-10-20", "3 Ni 7/06 (EU)",
      "Die Klagesperre des § 81 Abs. 2 PatG (Unzulässigkeit der Nichtigkeitsklage während eines anhängigen Einspruchs) gilt auch für Nichtigkeitsklagen gegen europäische Patente, solange ein Einspruchsverfahren vor dem EPA läuft.",
      norms=["§ 81 Abs. 2 PatG", "Art. II § 6 Abs. 1 IntPatÜG"], concepts=["pat_nichtigkeitsklage", "pat_nichtigkeit_ep"], tags=["Nichtigkeit", "Europäisches Patent"]),
    e("pat_bpatg_kaffeemaschine", "Kaffeemaschine", BPATG, "2012-03-27", "4 Ni 24/10 (EU)",
      "Ist mit der beschränkten Verteidigung keine inhaltliche Änderung der Patentansprüche verbunden, sondern nur eine Klarstellung, liegt keine Beschränkung vor; die Klarheit ist im Nichtigkeitsverfahren nur zu prüfen, soweit die Änderung sie berührt.",
      norms=["Art. II § 6 Abs. 1 IntPatÜG", "Art. II § 6 Abs. 3 IntPatÜG"], concepts=["pat_beschraenkte_verteidigung"], tags=["Nichtigkeit"]),
    # ------------------------------------------------------------------ Verfahren vor dem DPMA und BPatG: Fristen, Gebühren, Wiedereinsetzung
    e("pat_bpatg_weiterbehandlung_ii", "Weiterbehandlung II", BPATG, "2012-10-16", "10 W (pat) 22/10",
      "Bei der Weiterbehandlung nach § 123a PatG muss die versäumte Handlung innerhalb eines Monats nach Zustellung des Zurückweisungsbeschlusses vollständig nachgeholt und die Gebühr gezahlt werden; eine Nachholung nach Fristablauf ist nicht möglich, Wiedereinsetzung in die Weiterbehandlungsfrist bleibt möglich.",
      norms=["§ 123a PatG", "§ 6 Abs. 1 PatKostG"], concepts=["pat_weiterbehandlung"], tags=["Weiterbehandlung", "Fristen"]),
    e("pat_bpatg_weiterbehandlung", "Weiterbehandlung", BPATG, "2008-01-17", "10 W (pat) 42/06",
      "Ein innerhalb der Weiterbehandlungsfrist gestellter Antrag auf Verlängerung der Frist zur Nachholung der Handlung ist unbeachtlich; die Monatsfrist des § 123a Abs. 2 PatG ist nicht verlängerbar. Verhältnis zur Wiedereinsetzung (§ 123 PatG).",
      norms=["§ 123a PatG", "§ 123 PatG"], concepts=["pat_weiterbehandlung", "pat_wiedereinsetzung"], tags=["Weiterbehandlung", "Fristen"]),
    e("pat_bpatg_mehrfach_funkgeraet", "Mehrfach-Funkgerät", BPATG, "2008-01-31", "10 W (pat) 36/06",
      "Wiedereinsetzung in die Prioritätsfrist ist im Anmeldeverfahren vor dem DPMA ausgeschlossen (§ 123 Abs. 1 S. 2 PatG); Art. 4 PVÜ eröffnet keine Ausnahme.",
      norms=["§ 123 Abs. 1 PatG", "§ 41 PatG"], concepts=["pat_wiedereinsetzung", "pat_prioritaet"], tags=["Wiedereinsetzung", "Priorität"]),
    e("pat_bgh_verdickerpolymer_ii", "Verdickerpolymer II", BGH, "2015-07-07", "X ZB 4/14",
      "Am einseitigen Verfahren über einen Wiedereinsetzungsantrag des Patentinhabers (etwa nach Erlöschen wegen Nichtzahlung der Jahresgebühr) ist ein wegen Verletzung in Anspruch genommener Dritter nicht beteiligt; er kann die Wiedereinsetzung nicht anfechten, sondern nur das Zwischenbenutzungsrecht nach § 123 Abs. 5 geltend machen.",
      norms=["§ 123 PatG", "§ 20 Abs. 1 Nr. 3 PatG"], concepts=["pat_wiedereinsetzung", "pat_jahresgebuehren"], tags=["Wiedereinsetzung", "Jahresgebühren"]),
    e("pat_bpatg_saegeblatt", "Sägeblatt", BPATG, "2007-01-30", "10 W (pat) 13/05",
      "Die Frist zur Zahlung einer Jahresgebühr nach § 7 Abs. 1 PatKostG wird durch die Eröffnung des Insolvenzverfahrens über das Vermögen des Patentinhabers nicht unterbrochen; § 240 ZPO gilt nicht für Zahlungsfristen des PatKostG.",
      norms=["§ 7 Abs. 1 PatKostG", "§ 3 Abs. 2 PatKostG", "§ 17 PatG"], concepts=["pat_jahresgebuehren", "pat_zahlungsfristen"], tags=["Jahresgebühren", "PatKostG"]),
    e("pat_bpatg_jahresgebuehren_rueckzahlung", "Jahresgebühren (keine Rückzahlung)", BPATG, "2006-10-26", "10 W (pat) 45/05",
      "Mit Rechtsgrund entrichtete Jahresgebühren (hier 19. und 20. Jahr) werden nicht zurückgezahlt, auch wenn das Patent später für nichtig erklärt wird; § 10 PatKostG erfasst nur Zahlungen ohne Rechtsgrund oder für nicht vorgenommene Handlungen.",
      norms=["§ 10 PatKostG", "§ 17 PatG"], concepts=["pat_jahresgebuehren", "pat_gebuehren"], tags=["Jahresgebühren", "PatKostG"]),
    e("pat_bpatg_einspruchsgebuehren_gemeinsam", "Einspruchsgebühren bei gemeinsamem Einspruch", BPATG, "2008-04-30", "19 W (pat) 303/05",
      "Legen mehrere Personen gemeinsam Einspruch ein, ist die Einspruchsgebühr für jeden Einsprechenden gesondert zu entrichten (Vorbemerkung zum Gebührenverzeichnis); wird nur eine Gebühr gezahlt, gilt der Einspruch der übrigen als nicht erhoben (§ 6 Abs. 2 PatKostG).",
      norms=["§ 59 PatG", "§ 6 Abs. 1 PatKostG", "§ 6 Abs. 2 PatKostG", "Anlage PatKostG"], concepts=["pat_einspruch", "pat_gebuehren", "pat_zahlungsfristen"], tags=["Einspruch", "PatKostG"]),
    e("pat_bpatg_pruefungsgebuehr_ausscheidung", "Prüfungsgebühr für Ausscheidungsanmeldung", BPATG, "2006-04-20", "10 W (pat) 9/03",
      "Wird wegen Uneinheitlichkeit ein Teil ausgeschieden, ist für die Ausscheidungsanmeldung eine eigene Prüfungsgebühr zu zahlen, wenn in der Stammanmeldung bereits Prüfungsantrag gestellt war; die Zahlungsfrist des § 6 Abs. 1 PatKostG läuft ab Fälligkeit mit der Ausscheidungserklärung.",
      norms=["§ 34 Abs. 5 PatG", "§ 44 PatG", "§ 6 Abs. 1 PatKostG", "§ 3 Abs. 1 PatKostG"], concepts=["pat_gebuehren", "pat_teilung", "pat_zahlungsfristen"], tags=["Gebühren", "Teilung"]),
    e("pat_bpatg_nationale_gebuehr_pct", "Nationale Gebühr einer internationalen Anmeldung", BPATG, "2013-07-25", "10 W (pat) 2/13",
      "Für den Eintritt in die nationale Phase beim DPMA als Bestimmungsamt ist die nationale Gebühr binnen der Frist des Art. III § 4 Abs. 2 IntPatÜG (30 Monate ab Priorität) zu zahlen; sie wird mit Ablauf dieser Frist fällig, § 6 Abs. 1 PatKostG gewährt keine zusätzliche Zahlungsfrist.",
      norms=["Art. III § 4 IntPatÜG", "§ 3 Abs. 1 PatKostG", "§ 6 Abs. 1 PatKostG"], concepts=["pat_pct_nationale_phase", "pat_zahlungsfristen"], tags=["PCT", "PatKostG"]),
    e("pat_bpatg_ethylenische_hauptketten", "Ethylenische Hauptketten", BPATG, "2010-09-09", "10 W (pat) 19/09",
      "Für europäische Patente mit Erteilungshinweis vor dem 1.5.2008 bleibt das Übersetzungserfordernis des Art. II § 3 IntPatÜG bestehen (Art. XI § 4 IntPatÜG); ohne fristgerechte Übersetzung gelten die Wirkungen des Patents in Deutschland als von Anfang an nicht eingetreten.",
      norms=["Art. II § 3 IntPatÜG", "Art. XI § 4 IntPatÜG"], concepts=["pat_ep_validierung"], tags=["Europäisches Patent", "Übersetzung"]),
    e("pat_bpatg_aufreissdeckel", "Aufreißdeckel", BPATG, "2011-01-20", "10 W (pat) 21/06",
      "Ausnahmsweise kann eine Anmeldung trotz fehlender Beschreibung im Sinne des § 10 PatV erteilt werden, wenn der sachliche Zusammenhang aus Ansprüchen und Zeichnungen eindeutig hervorgeht; die Formvorschriften der PatV dienen der Verständlichkeit, nicht dem Selbstzweck.",
      norms=["§ 10 PatV", "§ 34 Abs. 3 Nr. 4 PatG", "§ 49 PatG"], concepts=["pat_anmeldung", "pat_beschreibung"], tags=["Anmeldung", "PatV"]),
    e("pat_bpatg_mobilfunknetzwerk", "Mobilfunknetzwerk", BPATG, "2009-06-16", "10 W (pat) 43/07",
      "Zeichnungen gehören nicht zu den Mindesterfordernissen für den Anmeldetag (§ 35 Abs. 1 PatG); werden sie nachgereicht, verschiebt sich der Anmeldetag nur, wenn der Anmelder darauf besteht, dass die Zeichnungen Teil der Anmeldung sind.",
      norms=["§ 35 Abs. 1 PatG", "§ 35a PatG"], concepts=["pat_anmeldetag", "pat_anmeldung"], tags=["Anmeldetag"]),
    e("pat_bpatg_teilbeschluss", "Teilbeschluss", BPATG, "2011-03-08", "15 W (pat) 11/07",
      "Die Prüfungsstelle darf den Hauptantrag nicht durch Teilbeschluss zurückweisen und über den Hilfsantrag später entscheiden; über Haupt- und Hilfsanträge ist einheitlich zu entscheiden, sonst ist der Beschluss verfahrensfehlerhaft.",
      norms=["§ 48 PatG", "§ 80 Abs. 3 PatG"], concepts=["pat_pruefungsverfahren", "pat_beschwerde"], tags=["Erteilungsverfahren", "Beschwerde"]),
    e("pat_bpatg_syndikusanwalt_kosten", "Syndikusanwalt im Nichtigkeitsverfahren", BPATG, "2026-04-02", "3 Ni 10/22 / KoF 4/25",
      "Ein Syndikusrechtsanwalt, der im Nichtigkeitsverfahren für seinen Arbeitgeber oder ein konzernverbundenes Unternehmen auftritt, kann seine Tätigkeit nicht nach dem RVG als erstattungsfähige Kosten abrechnen; er tritt in seiner Funktion als Angestellter auf.",
      norms=["§ 82 PatG", "§ 84 Abs. 2 PatG"], concepts=["pat_kostenerstattung"], tags=["Kosten", "Nichtigkeit"]),
    e("pat_bgh_feldmausbekaempfung", "Feldmausbekämpfung", BGH, "2018-03-27", "X ZB 18/16",
      "Im Gebrauchsmustereintragungsverfahren prüft die Gebrauchsmusterstelle, ob ein Schutzhindernis des § 2 GebrMG vorliegt (hier: Verfahren); die Prüfung ist auf die Schutzhindernisse beschränkt, Neuheit und erfinderischer Schritt bleiben dem Löschungsverfahren vorbehalten.",
      norms=["§ 1 PatG"], concepts=["pat_gebrauchsmuster_abzweigung"], tags=["Gebrauchsmuster"]),
]
