# -*- coding: utf-8 -*-
"""Abgrenzungstabellen zum deutschen Patentrecht (Felder wie knowledge/distinctions.py). Zellen mit Zitaten ohne
Gesetzesangabe werden mit `qualify` auf das PatG qualifiziert, damit die Verlinkung stimmt."""
from ..gesetze import qualify


def q(text, law="PatG"):
    return qualify(text, law)


DISTINCTIONS = [
    dict(id="d_pat_einspruch_nichtigkeit", label="Einspruch vs. Nichtigkeitsklage",
         concepts=["pat_einspruch", "pat_nichtigkeitsklage", "pat_widerrufsgruende", "pat_nichtigkeitsgruende"],
         frage="Mit welchem Verfahren wird der Rechtsbestand eines Patents angegriffen, und worin unterscheiden sich Einspruch und Nichtigkeitsklage?",
         kriterien=["Rechtsgrundlage", "Zuständigkeit", "Frist", "Antragsberechtigung", "Gründe", "Gebühr", "Verfahren", "Rechtsmittel", "Verhältnis zueinander", "Europäisches Patent"],
         spalten=["Einspruch", "Nichtigkeitsklage"],
         rows=[
             [q("§ 59 bis § 62"), q("§ 81 bis § 84") + ", " + q("Art. II § 6", "IntPatÜG")],
             ["Patentabteilung des DPMA; Beschwerde zum Technischen Beschwerdesenat", "Nichtigkeitssenat des BPatG (zwei rechtskundige, drei technische Richter); Berufung zum BGH"],
             ["Neun Monate ab Veröffentlichung der Erteilung, keine Wiedereinsetzung", "Keine Frist, solange das Patent besteht (auch nach Erlöschen bei Rechtsschutzinteresse)"],
             ["Jedermann; bei widerrechtlicher Entnahme nur der Verletzte", "Jedermann (Popularklage); bei widerrechtlicher Entnahme nur der Verletzte; kein Rechtsmissbrauch bei paralleler Klage"],
             [q("Widerrufsgründe des § 21 Abs. 1") + " (abschließend)", q("§ 22 Abs. 1") + ": Widerrufsgründe plus Erweiterung des Schutzbereichs; beim europäischen Patent Art. 138 EPÜ"],
             ["200 EUR (Nr. 313 600), je Einsprechender, binnen der Einspruchsfrist", "4,5 Wertgebühren nach dem Streitwert (Nr. 402 100), Vorauszahlung, Sicherheitsleistung ausländischer Kläger"],
             ["Amtsverfahren mit Untersuchungsgrundsatz, Beschluss, Kosten jeder selbst", "Kontradiktorisches Verfahren nach ZPO-Regeln, qualifizierter Hinweis (§ 83), Urteil, Kosten nach §§ 91 ff. ZPO"],
             ["Beschwerde (ein Monat, 500 EUR), dann Rechtsbeschwerde bei Zulassung", "Berufung zum BGH (ein Monat, Begründung drei Monate), Präklusion nach § 117"],
             ["Während Einspruchsfrist und -verfahren ist die Nichtigkeitsklage unzulässig (§ 81 Abs. 2)", "Nach Ablauf der Einspruchsfrist einziger Angriff; Beitritt zum laufenden Einspruch als Alternative (§ 59 Abs. 2)"],
             ["Einspruch beim EPA (Art. 99 EPÜ), neun Monate, Wirkung für alle Staaten", "Deutscher Teil: BPatG nach Art. II § 6 IntPatÜG bei Opt-out oder Übergangszeit; sonst EPG (Art. 32 EPGÜ); Einheitspatent nur EPG"],
         ],
         merksatz="Neun Monate Einspruch beim Amt, danach Nichtigkeitsklage beim Gericht: Gleiche Gründe, andere Bühne, und während der Einspruch läuft, ist die Klage gesperrt."),
    dict(id="d_pat_neuheit_erfinderische_taetigkeit", label="Neuheit vs. erfinderische Tätigkeit",
         concepts=["pat_neuheit", "pat_erfinderische_taetigkeit", "pat_offenbarung", "pat_fachmann"],
         frage="Wie unterscheiden sich die Prüfung der Neuheit (§ 3 PatG) und der erfinderischen Tätigkeit (§ 4 PatG)?",
         kriterien=["Frage", "Stand der Technik", "Vergleichsmethode", "Maßstab", "Rolle des Fachwissens", "Ältere Anmeldungen (§ 3 Abs. 2)", "Leitentscheidungen"],
         spalten=["Neuheit (§ 3 PatG)", "Erfinderische Tätigkeit (§ 4 PatG)"],
         rows=[
             ["Ist die Lehre schon bekannt?", "Lag die Lehre für den Fachmann nahe?"],
             ["Alles öffentlich Zugängliche vor dem Zeitrang, einschließlich älterer nachveröffentlichter Anmeldungen", "Nur das vor dem Zeitrang Veröffentlichte; ältere nachveröffentlichte Anmeldungen bleiben außer Betracht (§ 4 S. 2)"],
             ["Einzelvergleich mit jeder Entgegenhaltung; keine Kombination", "Gesamtschau; Kombination mehrerer Quellen und des Fachwissens zulässig, wenn der Fachmann Anlass dazu hatte"],
             ["Unmittelbar und eindeutig offenbart, einschließlich des selbstverständlich Mitgelesenen", "Veranlassung und angemessene Erfolgserwartung; keine rückschauende Betrachtung"],
             ["Nur zum Verständnis der Quelle, nicht zur Ergänzung", "Vollständig; allgemeines Fachwissen allein ist aber noch kein Anlass"],
             ["Neuheitsschädlich", "Nicht zu berücksichtigen"],
             ["Olanzapin, Glasfasern, Hohlfaserdialysator", "Fischbissanzeiger, Airbag-Auslösesteuerung, Kinderbett, Papiermaschinengewebe"],
         ],
         merksatz="Neuheit: eine Quelle, Wort für Wort. Erfinderische Tätigkeit: alle Quellen, aber nur mit Anlass."),
    dict(id="d_pat_wortsinn_aequivalenz", label="Wortsinngemäße vs. äquivalente Patentverletzung",
         concepts=["pat_schutzbereich", "pat_aequivalenz", "pat_auslegung"],
         frage="Wann liegt eine wortsinngemäße und wann eine äquivalente Benutzung der patentierten Lehre vor?",
         kriterien=["Prüfungsgegenstand", "Maßstab", "Prüfungsschritte", "Auswahlentscheidung", "Stand der Technik", "Rechtsgrundlage"],
         spalten=["Wortsinngemäße Verletzung", "Äquivalente Verletzung"],
         rows=[
             ["Jedes Merkmal des Anspruchs im ausgelegten Sinn verwirklicht", "Ein oder mehrere Merkmale nicht wortsinngemäß, aber durch abgewandelte Mittel ersetzt"],
             ["Sinngehalt des Anspruchs aus der Sicht des Fachmanns (§ 14 PatG, Art. 69 EPÜ)", "Drei Schneidmesser-Fragen: Gleichwirkung, Auffindbarkeit, Gleichwertigkeit (Orientierung am Anspruch)"],
             ["Merkmalsgliederung, Auslegung, Subsumtion", "Für jedes abweichende Merkmal alle drei Fragen; Gleichwirkung meint gerade die Wirkung des ersetzten Merkmals (Palettenbehälter III)"],
             ["Unerheblich", "Offenbart die Beschreibung mehrere Wege und beansprucht nur einen, ist der andere nicht gleichwertig (Okklusionsvorrichtung, Diglycidverbindung, Pemetrexed)"],
             ["Kein Einwand (Rechtsbestand nur im Nichtigkeitsverfahren)", "Formstein-Einwand: keine Äquivalenz, wenn die Ausführung zum Stand der Technik gehört oder ihm nahegelegt war"],
             [q("§ 14"), q("§ 14") + ", Art. 2 Auslegungsprotokoll zu Art. 69 EPÜ"],
         ],
         merksatz="Erst Wortsinn für alle Merkmale, dann Äquivalenz nur für die Lücken; wer in der Beschreibung die Wahl hatte und im Anspruch gewählt hat, bekommt den anderen Weg nicht mehr."),
    dict(id="d_pat_weiterbehandlung_wiedereinsetzung", label="Weiterbehandlung vs. Wiedereinsetzung",
         concepts=["pat_weiterbehandlung", "pat_wiedereinsetzung", "pat_fristen"],
         frage="Welcher Rechtsbehelf hilft nach einer versäumten Frist: Weiterbehandlung nach § 123a PatG oder Wiedereinsetzung nach § 123 PatG?",
         kriterien=["Anwendungsbereich", "Erfasste Fristen", "Verschulden", "Frist für den Antrag", "Erfordernisse", "Gebühr", "Ausgeschlossen bei", "Wirkung gegenüber Dritten"],
         spalten=["Weiterbehandlung (§ 123a PatG)", "Wiedereinsetzung (§ 123 PatG)"],
         rows=[
             ["Nur das Patentanmeldeverfahren nach Zurückweisung wegen Fristversäumung", "Alle Verfahren vor DPMA und BPatG, jede Frist mit Rechtsnachteil"],
             ["Vom DPMA gesetzte Fristen (Bescheidfristen)", "Gesetzliche und amtsseitige Fristen, Zahlungsfristen"],
             ["Unerheblich", "Ohne Verschulden; Vertreterverschulden wird zugerechnet (§ 85 Abs. 2 ZPO)"],
             ["Ein Monat nach Zustellung des Zurückweisungsbeschlusses, nicht verlängerbar", "Zwei Monate nach Wegfall des Hindernisses, spätestens ein Jahr nach Fristablauf"],
             ["Antrag, vollständige Nachholung der Handlung, Gebühr innerhalb der Frist (BPatG Weiterbehandlung II)", "Antrag mit Begründung, Glaubhaftmachung, Nachholung der Handlung innerhalb der Antragsfrist"],
             ["100 EUR (Nr. 313 000)", "Gebührenfrei"],
             ["Gesetzlichen Fristen (Prüfungsantrag, Beschwerde), Einspruch, Zahlungsfristen des PatKostG", "Einspruchsfrist, Prioritätsfrist, Nachfrist der Erfinderbenennung, Wiedereinsetzungsfrist selbst (§ 123 Abs. 1 S. 2)"],
             ["Keine Sonderregel", "Zwischenbenutzungsrecht des gutgläubigen Dritten (§ 123 Abs. 5); Dritter am Verfahren nicht beteiligt (Verdickerpolymer II)"],
         ],
         merksatz="Weiterbehandlung: schnell, ohne Entschuldigung, nur bei Amtsfristen der Anmeldung. Wiedereinsetzung: überall, aber nur ohne Verschulden und nie beim Einspruch oder bei der Priorität."),
    dict(id="d_pat_zahlungsfristen_patkostg", label="Zahlungsfristen nach § 6 und § 7 PatKostG",
         concepts=["pat_zahlungsfristen", "pat_jahresgebuehren", "pat_faelligkeit", "pat_gebuehren"],
         frage="Wann ist welche Gebühr fällig, bis wann kann gezahlt werden, und was passiert bei Nichtzahlung?",
         kriterien=["Anmelde-, Prüfungs-, Antragsgebühr", "Einspruchs-, Beschwerde-, Erinnerungsgebühr", "Jahresgebühr", "Nationale Gebühr PCT", "Wertgebühr Nichtigkeitsklage", "Zahlungstag"],
         spalten=["Fälligkeit", "Zahlungsfrist", "Folge der Nichtzahlung", "Rechtsbehelf"],
         rows=[
             [q("Mit Einreichung (§ 3 Abs. 1)", "PatKostG"), q("Drei Monate (§ 6 Abs. 1 S. 1)", "PatKostG"), q("Anmeldung gilt als zurückgenommen, Antrag als nicht gestellt (§ 6 Abs. 2)", "PatKostG"), q("Wiedereinsetzung (§ 123)") + "; Weiterbehandlung nur bei amtsseitiger Frist"],
             [q("Mit Einlegung (§ 3 Abs. 1)", "PatKostG"), q("Innerhalb der Rechtsbehelfsfrist (§ 6 Abs. 1 S. 2)", "PatKostG"), q("Rechtsbehelf gilt als nicht erhoben (§ 6 Abs. 2)", "PatKostG"), "Wiedereinsetzung bei Beschwerde; beim Einspruch ausgeschlossen"],
             [q("Letzter Tag des Monats, der dem Anmeldemonat entspricht (§ 3 Abs. 2)", "PatKostG"), q("Zwei Monate ohne, sechs Monate mit Zuschlag von 50 EUR (§ 7 Abs. 1)", "PatKostG"), q("Erlöschen rückwirkend zum Fälligkeitstag (§ 20 Abs. 1 Nr. 3)"), q("Wiedereinsetzung (§ 123)") + " mit Zwischenbenutzungsrecht"],
             ["Mit Ablauf der 30-Monats-Frist (Art. III § 4 Abs. 2 IntPatÜG; BPatG Nationale Gebühr)", "Keine zusätzliche Frist", "Wirkung der Anmeldung für Deutschland endet", q("Wiedereinsetzung (§ 123)")],
             [q("Mit Einreichung der Klage; Vorauszahlung (§ 5)", "PatKostG"), "Vom Gericht gesetzte Frist", "Klage wird nicht zugestellt (§ 81 Abs. 5 PatG)", "Nachzahlung; Wiedereinsetzung"],
             ["§ 2 PatKostZV: Überweisung am Tag der Gutschrift beim DPMA, SEPA-Lastschrift am Tag des Mandatseingangs (Zahlung bei Antragseingang), Bareinzahlung am Einzahlungstag", "", "", ""],
         ],
         merksatz="Drei Monate für Anträge, Rechtsbehelfsfrist für Rechtsbehelfe, sechs Monate mit Zuschlag für Jahresgebühren: Wer die drei Regeln kennt, löst jede Gebührenklausur."),
    dict(id="d_pat_widerruf_nichtigkeit_beschraenkung", label="Widerruf, Nichtigerklärung, Beschränkung, Erlöschen",
         concepts=["pat_widerrufsgruende", "pat_nichtigkeitsgruende", "pat_beschraenkungsverfahren", "pat_laufzeit_jahresgebuehren"],
         frage="Auf welchen Wegen endet oder schrumpft ein Patent, und mit welcher Wirkung?",
         kriterien=["Rechtsgrundlage", "Auslöser", "Entscheidende Stelle", "Zeitliche Wirkung", "Teilweise möglich?"],
         spalten=["Widerruf", "Nichtigerklärung", "Beschränkung auf Antrag", "Erlöschen"],
         rows=[
             [q("§ 21, § 61"), q("§ 22, § 81 ff.") + "; Art. II § 6 IntPatÜG", q("§ 64"), q("§ 20")],
             ["Einspruch eines Dritten binnen neun Monaten", "Nichtigkeitsklage jederzeit", "Antrag des Patentinhabers", "Verzicht, fehlende Erfinderbenennung, Nichtzahlung der Jahresgebühr"],
             ["Patentabteilung, Beschwerde BPatG", "BPatG, Berufung BGH (oder EPG)", "Patentabteilung des DPMA", "Kraft Gesetzes, Eintragung im Register"],
             ["Ex tunc (§ 21 Abs. 3)", "Ex tunc, gegen jedermann (§ 22 Abs. 2 i.V.m. § 21 Abs. 3)", "Ex tunc auf den Anmeldetag", "Ex nunc (Verzicht) bzw. rückwirkend zum Fälligkeitstag (Jahresgebühr)"],
             ["Ja, beschränkte Aufrechterhaltung (§ 21 Abs. 2)", "Ja, teilweise Nichtigerklärung mit beschränkten Ansprüchen", "Ja, Änderung der Ansprüche ohne Erweiterung", "Nein (nur Verzicht auf einzelne Ansprüche als Beschränkung)"],
         ],
         merksatz="Widerruf und Nichtigkeit wirken zurück, Erlöschen wirkt nach vorn; die Beschränkung ist der freiwillige Rückzug auf sicheres Gelände."),
    dict(id="d_pat_deutsches_europaeisches_einheitspatent", label="Deutsches Patent, europäisches Patent (DE-Teil), Einheitspatent",
         concepts=["pat_ep_validierung", "pat_einheitspatent_national", "pat_doppelschutz", "pat_nichtigkeit_ep"],
         frage="Welche Regeln gelten in Deutschland für das nationale Patent, den deutschen Teil eines europäischen Patents und das Einheitspatent?",
         kriterien=["Erteilung", "Materielles Recht", "Verletzungsgericht", "Rechtsbestand", "Jahresgebühren", "Übersetzung", "Doppelschutz", "Vollstreckung"],
         spalten=["Deutsches Patent (PatG)", "Europäisches Patent, deutscher Teil (IntPatÜG)", "Einheitspatent (EPatVO, IntPatÜG Art. II §§ 15 ff.)"],
         rows=[
             ["DPMA nach §§ 34 ff. PatG, Prüfungsantrag binnen sieben Jahren", "EPA nach dem EPÜ, Wirkung für Deutschland mit Erteilungshinweis (Art. 64 EPÜ)", "EPA; Antrag auf einheitliche Wirkung binnen eines Monats (R. 6 DOEPS)"],
             [q("§ 9 bis § 14, § 139 ff."), "Art. 64, 69 EPÜ; §§ 9 ff., 139 ff. PatG (Art. II IntPatÜG); vor dem EPG Art. 25 bis 30 EPGÜ", "Art. 25 bis 30 EPGÜ über Art. 5 Abs. 3 EPatVO, einheitlich für alle teilnehmenden Staaten"],
             ["Patentstreitkammern der Landgerichte (§ 143 PatG)", "Landgerichte bei Opt-out oder in der Übergangszeit; sonst EPG (Art. 32, 83 EPGÜ)", "Ausschließlich EPG (Art. 32 EPGÜ)"],
             ["Einspruch (§ 59), Nichtigkeitsklage BPatG (§ 81)", "Einspruch EPA (Art. 99 EPÜ); Nichtigkeitsklage BPatG (Art. II § 6 IntPatÜG) oder EPG", "Einspruch EPA; Nichtigkeitsklage nur EPG (Art. II § 15 IntPatÜG)"],
             ["An das DPMA, § 17 PatG, § 7 PatKostG", "An das DPMA ab dem Jahr nach dem Erteilungshinweis (Art. II § 7 IntPatÜG)", "An das EPA nach Art. 2 GebOEPS, R. 13 DOEPS"],
             ["Deutsch (§ 126 PatG, § 35 Abs. 2)", "Seit dem Londoner Übereinkommen keine (Art. XI § 4 IntPatÜG); Altpatente Art. II § 3", "Übergangszeit: eine Übersetzung zur Information (Art. 6 EPatÜVO)"],
             ["–", "Doppelschutzverbot (Art. II § 8), es sei denn das EP unterliegt dem EPG (Art. II § 18: Doppelschutz mit Einrede)", "Doppelschutz neben deutschem Patent zulässig, Einrede der doppelten Inanspruchnahme (Art. II § 18)"],
             ["ZPO", "ZPO; EPG-Entscheidungen nach Art. II § 19 IntPatÜG, Art. 82 EPGÜ", "EPG-Entscheidungen nach Art. II § 19 IntPatÜG, Art. 82 EPGÜ"],
         ],
         merksatz="Das IntPatÜG ist die Brücke: Art. II § 6 macht das europäische Patent vor dem BPatG angreifbar, Art. II §§ 15 bis 20 holen das Einheitspatent und das EPG ins deutsche Recht."),
    dict(id="d_pat_teilung_ausscheidung_abzweigung", label="Teilung, Ausscheidung, Abzweigung",
         concepts=["pat_teilung", "pat_gebrauchsmuster_abzweigung", "pat_prioritaet"],
         frage="Wie unterscheiden sich Teilung, Ausscheidung und Abzweigung, und was gilt für Zeitrang und Gebühren?",
         kriterien=["Rechtsgrundlage", "Anlass", "Zeitpunkt", "Zeitrang", "Gebühren", "Widerruflich?"],
         spalten=["Teilung", "Ausscheidung", "Abzweigung (Gebrauchsmuster)"],
         rows=[
             [q("§ 39") + " (Anmeldung), " + q("§ 60") + " (Einspruch)", q("§ 34 Abs. 5"), "§ 5 GebrMG, " + q("§ 145a")],
             ["Freie Entscheidung des Anmelders", "Uneinheitlichkeit, vom DPMA beanstandet", "Wunsch nach schnellem, ungeprüftem Schutz neben der Patentanmeldung"],
             ["Jederzeit bis zur Erteilung; im Einspruchsverfahren bis zum Abschluss", "Auf Aufforderung im Prüfungsverfahren", "Bis zum Ablauf von zwei Monaten nach Erledigung der Patentanmeldung, höchstens zehn Jahre"],
             ["Anmeldetag und Priorität der Stammanmeldung", "Anmeldetag und Priorität der Stammanmeldung", "Anmeldetag und Priorität der Patentanmeldung (§ 5 Abs. 1 GebrMG)"],
             ["Anmelde- und Jahresgebühren für die Teilanmeldung nachzahlen (§ 39 Abs. 2)", "Zusätzlich eigene Prüfungsgebühr (BPatG Prüfungsgebühr für Ausscheidungsanmeldung)", "Anmeldegebühr Gebrauchsmuster (30 EUR)"],
             ["Nein (§ 39 Abs. 3), Teilungserklärung ohne gegenständliche Festlegung (Sammelhefter)", "Nein", "Abzweigungserklärung wirkt mit der Anmeldung"],
         ],
         merksatz="Teilung ist freiwillig, Ausscheidung erzwungen, Abzweigung wechselt das Schutzrecht: In allen drei Fällen bleibt der Zeitrang, aber die Gebühren fallen neu an."),
    dict(id="d_pat_patent_gebrauchsmuster", label="Patent vs. Gebrauchsmuster",
         concepts=["pat_gebrauchsmuster", "pat_gebrauchsmuster_abzweigung", "pat_gebrauchsmuster_loeschung", "pat_erfindung"],
         frage="Worin unterscheiden sich Patent und Gebrauchsmuster in Schutzgegenstand, Entstehung, Rechtsbestand und Durchsetzung?",
         kriterien=["Schutzgegenstand", "Prüfung vor Eintragung", "Neuheit", "Erfinderische Höhe", "Laufzeit", "Angriff auf den Rechtsbestand", "Verletzungsprozess", "Gebühren (Anmeldung)", "Brücke"],
         spalten=["Patent (PatG)", "Gebrauchsmuster (GebrMG)"],
         rows=[
             ["Erzeugnisse, Verfahren, Verwendungen, biotechnologische Erfindungen (" + q("§ 1, § 1a") + ")", "Nur Erzeugnisse und Anordnungen; keine Verfahren, keine biotechnologischen Erfindungen (§ 2 GebrMG)"],
             ["Vollprüfung auf Prüfungsantrag (" + q("§ 44") + ")", "Nur Formal- und Ausschlussprüfung (§ 8 GebrMG); Recherche auf Antrag (§ 7 GebrMG)"],
             ["Absolut: alles weltweit Zugängliche, ältere Anmeldungen (" + q("§ 3") + "); Schonfrist nur bei Missbrauch oder Ausstellung", "Relativ: schriftliche Beschreibungen weltweit, Benutzung nur im Inland; sechs Monate Schonfrist für eigene Offenbarungen (§ 3 Abs. 1 GebrMG)"],
             ["Erfinderische Tätigkeit (" + q("§ 4") + ")", "Erfinderischer Schritt (§ 1 GebrMG), nach BGH Demonstrationsschrank gleicher Maßstab"],
             ["20 Jahre ab Anmeldetag (" + q("§ 16") + ")", "3 Jahre, verlängerbar auf 6, 8 und 10 Jahre (§ 23 GebrMG)"],
             ["Einspruch neun Monate (" + q("§ 59") + "), danach Nichtigkeitsklage BPatG (" + q("§ 81") + ")", "Löschungsantrag beim DPMA jederzeit (§ 15 GebrMG), Beschwerde zum BPatG"],
             ["Rechtsbestand wird nicht geprüft (Trennungsprinzip), Aussetzung nach § 148 ZPO", "Schutzfähigkeit als Einwand im Verletzungsprozess prüfbar; Aussetzung bei Löschungsantrag (§ 19 GebrMG)"],
             ["40 EUR elektronisch, Recherche 300 EUR, Prüfung 350 EUR", "30 EUR elektronisch, Recherche 250 EUR, keine Prüfungsgebühr"],
             ["Abzweigung aus der Patentanmeldung mit deren Zeitrang (" + q("§ 145a") + ", § 5 GebrMG); Priorität gegenseitig (§ 6 GebrMG)", "Gebrauchsmuster als Prioritätsgrundlage für ein Patent (" + q("§ 40") + " über § 6 GebrMG)"],
         ],
         merksatz="Das Gebrauchsmuster ist das schnelle, ungeprüfte Erzeugnisschutzrecht mit Schonfrist: ideal als Abzweigung neben der Patentanmeldung, riskant im Prozess."),
]
