# -*- coding: utf-8 -*-
"""Prüfungsschemata zum deutschen Patentrecht. Schritt-IDs: step:<schema>.<n>.<m>."""
from ..schemata import step

SCHEMATA = [
    dict(
        id="pat_schema_patentfaehigkeit",
        label="Patentfähigkeit (§§ 1 bis 5 PatG)",
        kategorie="Patent: Patentfähigkeit",
        beschreibung="Gutachtenaufbau für Erteilung, Einspruch (§ 21 Abs. 1 Nr. 1 PatG) und Nichtigkeit (§ 22 PatG, Art. II § 6 Abs. 1 Nr. 1 IntPatÜG): Erst Technizität und Ausschlüsse, dann Neuheit im Einzelvergleich, dann erfinderische Tätigkeit aus der Sicht des Fachmanns, zuletzt gewerbliche Anwendbarkeit. Vorab immer die Merkmalsgliederung des Anspruchs und dessen Auslegung.",
        norms=["§ 1 PatG", "§ 3 PatG", "§ 4 PatG", "§ 5 PatG"],
        steps=[
            step("A. Anspruch auslegen und gliedern", "Merkmalsgliederung des Hauptanspruchs; Sinngehalt der Merkmale aus der Sicht des Fachmanns unter Heranziehung der Beschreibung (§ 14 PatG); Anspruchskategorie (Erzeugnis, Verfahren, Verwendung).",
                 concepts=["pat_auslegung", "pat_patentanspruch", "pat_fachmann"], norms=["§ 14 PatG", "§ 9 PatV"], cases=["pat_bgh_polymerschaum"]),
            step("B. Erfindung: Technizität und Ausschlüsse (§ 1, § 1a, § 2, § 2a PatG)", children=[
                step("1. Technische Lehre (§ 1 Abs. 1 PatG)", "Lehre zum planmäßigen Handeln unter Einsatz beherrschbarer Naturkräfte; bei Datenverarbeitung genügt ein technischer Teilaspekt.",
                     concepts=["pat_technizitaet"], norms=["§ 1 Abs. 1 PatG"], cases=["pat_bgh_steuerungseinrichtung"]),
                step("2. Kein Ausschluss „als solches“ (§ 1 Abs. 3, 4 PatG)", "Entdeckungen, wissenschaftliche Theorien, ästhetische Formschöpfungen, Pläne, Regeln, Programme, Wiedergabe von Informationen nur als solche ausgeschlossen; bei Programmen: Lösung eines konkreten technischen Problems mit technischen Mitteln.",
                     concepts=["pat_programme"], norms=["§ 1 Abs. 3 PatG", "§ 1 Abs. 4 PatG"], cases=["pat_bgh_webseitenanzeige", "pat_bgh_dynamische_dokumentengenerierung", "pat_bgh_rezeptortyrosinkinase"],
                     hinweis="Nichttechnische Merkmale werden bei § 4 PatG nicht berücksichtigt; das ist der praktische Hebel bei Software- und Geschäftsmethodenpatenten."),
                step("3. Biotechnologie, ordre public, Sorten und Behandlungsverfahren (§§ 1a, 2, 2a PatG)", "Menschlicher Körper und bloße Gensequenzen (§ 1a PatG), Verstoß gegen öffentliche Ordnung (§ 2 PatG), Pflanzensorten, Tierrassen, im Wesentlichen biologische Verfahren, chirurgische/therapeutische/diagnostische Verfahren (§ 2a PatG).",
                     concepts=["pat_biotech", "pat_therapeutische_verfahren"], norms=["§ 1a PatG", "§ 2 PatG", "§ 2a PatG"], cases=["pat_bgh_carvedilol_ii"]),
            ]),
            step("C. Neuheit (§ 3 PatG)", children=[
                step("1. Stand der Technik bestimmen (§ 3 Abs. 1, 2 PatG)", "Alles, was vor dem Zeitrang (Anmelde- oder Prioritätstag) öffentlich zugänglich war; ältere nachveröffentlichte deutsche, europäische und PCT-Anmeldungen nur für die Neuheit (§ 3 Abs. 2 PatG); Neuheitsschonfrist nur bei Missbrauch oder Ausstellung (§ 3 Abs. 5 PatG).",
                     concepts=["pat_neuheit", "pat_prioritaet"], norms=["§ 3 Abs. 1 PatG", "§ 3 Abs. 2 PatG", "§ 3 Abs. 5 PatG"]),
                step("2. Einzelvergleich: unmittelbar und eindeutig offenbart?", "Jede Entgegenhaltung für sich; neuheitsschädlich nur, was der Fachmann ihr als technische Information einschließlich des selbstverständlich Mitgelesenen entnimmt; keine Ergänzung aus dem Fachwissen, keine Kombination mehrerer Quellen.",
                     concepts=["pat_offenbarung", "pat_neuheit"], norms=["§ 3 Abs. 1 PatG"], cases=["pat_bgh_olanzapin", "pat_bgh_glasfasern", "pat_bgh_hohlfaserdialysator"],
                     hinweis="Allgemeine Formeln offenbaren nicht die Einzelverbindung (Olanzapin); Bereichsangaben nicht jeden Einzelwert; implizite Merkmale zählen, wenn sie zwangsläufig verwirklicht sind."),
                step("3. Sonderfall: zweckgebundener Stoffschutz (§ 3 Abs. 3, 4 PatG)", "Bekannter Stoff für erste oder weitere medizinische Indikation ist neu, wenn die Verwendung nicht bekannt war.",
                     concepts=["pat_zweite_indikation"], norms=["§ 3 Abs. 3 PatG", "§ 3 Abs. 4 PatG"]),
            ]),
            step("D. Erfinderische Tätigkeit (§ 4 PatG)", children=[
                step("1. Fachmann und Fachwissen bestimmen", "Fiktiver Durchschnittsfachmann des Gebiets, auf dem das Problem liegt (Konstrukteur, nicht Anwender); bei interdisziplinären Aufgaben ein Team.",
                     concepts=["pat_fachmann"], norms=["§ 4 PatG"], cases=["pat_bgh_fischbissanzeiger"]),
                step("2. Nächstliegender Stand der Technik und objektives Problem", "Ausgangspunkt frei wählbar; objektive Aufgabe aus dem, was die Erfindung tatsächlich leistet, ohne Lösungshinweise; keine Zerlegung in Teilaufgaben.",
                     concepts=["pat_aufgabe_loesung"], norms=["§ 4 PatG"], cases=["pat_bgh_papiermaschinengewebe"]),
                step("3. Veranlassung des Fachmanns (Naheliegen)", "Hatte der Fachmann Anlass, den Stand der Technik in Richtung der Erfindung weiterzuentwickeln, und eine angemessene Erfolgserwartung? Allgemeines Fachwissen allein ist kein Anlass; generelle Lösungsmittel können es sein. Keine rückschauende Betrachtung.",
                     concepts=["pat_erfinderische_taetigkeit"], norms=["§ 4 PatG"], cases=["pat_bgh_airbag_ausloesesteuerung", "pat_bgh_kinderbett", "pat_bgh_farbversorgungssystem", "pat_bgh_gleitlagerueberwachung", "pat_bgh_einteilige_oese"],
                     hinweis="Formel: „Der Fachmann hatte Veranlassung, …, weil …“; Hilfsindizien (Bedürfnis, Zeitfaktor, Vorurteil, Erfolg) nur ergänzend."),
            ]),
            step("E. Gewerbliche Anwendbarkeit (§ 5 PatG)", "Herstellbar oder benutzbar auf irgendeinem gewerblichen Gebiet einschließlich Landwirtschaft; praktisch nur bei nicht wiederholbaren oder nutzlosen Lehren zu verneinen.",
                 concepts=["pat_gewerbliche_anwendbarkeit"], norms=["§ 5 PatG"]),
            step("F. Ergebnis und Folgen", "Patentfähig: Erteilung (§ 49 PatG) bzw. Aufrechterhaltung; nicht patentfähig: Zurückweisung (§ 48 PatG), Widerruf (§ 21 Abs. 1 Nr. 1 PatG) oder Nichtigerklärung (§ 22 PatG), gegebenenfalls beschränkt mit Hilfsanträgen.",
                 concepts=["pat_widerrufsgruende", "pat_beschraenkte_verteidigung"], norms=["§ 21 Abs. 1 PatG", "§ 22 PatG", "§ 48 PatG", "§ 49 PatG"]),
        ],
    ),
    dict(
        id="pat_schema_patentverletzung",
        label="Patentverletzung (§§ 9, 10, 14, 139 ff. PatG)",
        kategorie="Patent: Wirkung, Verletzung, Schranken",
        beschreibung="Aufbau der Verletzungsklage vor der Patentstreitkammer: Aktivlegitimation, Schutzbereich (Auslegung, wortsinngemäße Benutzung, Äquivalenz), Benutzungshandlung, Einwendungen (Schranken, Vorbenutzung, Erschöpfung, Lizenz, Verjährung, Verhältnismäßigkeit), Rechtsfolgen. Der Rechtsbestand wird nicht geprüft (Trennungsprinzip), nur die Aussetzung nach § 148 ZPO.",
        norms=["§ 9 PatG", "§ 10 PatG", "§ 14 PatG", "§ 139 PatG", "§ 143 PatG"],
        steps=[
            step("A. Zulässigkeit: Patentstreitkammer, Aktivlegitimation", "Landgericht als Patentstreitkammer (§ 143 PatG), Konzentration; Kläger ist Inhaber (Registerfiktion § 30 Abs. 3 PatG), ausschließlicher Lizenznehmer aus eigenem Recht, einfacher Lizenznehmer mit Ermächtigung; Klagekonzentration § 145 PatG.",
                 concepts=["pat_lizenz", "pat_register", "pat_klagekonzentration"], norms=["§ 143 PatG", "§ 30 Abs. 3 PatG", "§ 15 Abs. 2 PatG", "§ 145 PatG"], cases=["pat_bgh_raffvorhang"]),
            step("B. Schutzbereich (§ 14 PatG)", children=[
                step("1. Merkmalsgliederung und Auslegung", "Sinngehalt jedes Merkmals aus der Sicht des Fachmanns im Gesamtzusammenhang; Beschreibung als Lexikon, Ausführungsbeispiele nicht beschränkend; Verletzungsgericht legt selbständig aus.",
                     concepts=["pat_auslegung", "pat_zweckangabe"], norms=["§ 14 PatG"], cases=["pat_bgh_drehzahlermittlung", "pat_bgh_bodenseitige_vereinzelungseinrichtung", "pat_bgh_kreuzgestaenge", "pat_bgh_scheinwerferbelueftungssystem"]),
                step("2. Wortsinngemäße Benutzung", "Verwirklicht die angegriffene Ausführungsform jedes Merkmal im ausgelegten Sinn? Merkmal für Merkmal subsumieren; Zahlen- und Maßangaben begrenzen.",
                     concepts=["pat_schutzbereich"], norms=["§ 14 PatG"], cases=["pat_bgh_schneidmesser_i", "pat_bgh_kunststoffrohrteil"]),
                step("3. Äquivalente Benutzung (Schneidmesser-Fragen)", "Für jedes nicht wortsinngemäß verwirklichte Merkmal: Gleichwirkung (gerade die Wirkung dieses Merkmals), Auffindbarkeit ohne erfinderische Überlegungen, Gleichwertigkeit (Orientierung am Anspruch); Auswahlentscheidung schließt Äquivalenz aus; Formstein-Einwand.",
                     concepts=["pat_aequivalenz"], norms=["§ 14 PatG"], cases=["pat_bgh_schneidmesser_i", "pat_bgh_okklusionsvorrichtung", "pat_bgh_pemetrexed", "pat_bgh_v_foermige_fuehrungsanordnung", "pat_bgh_palettenbehaelter_iii"],
                     hinweis="Reihenfolge einhalten: erst Wortsinn aller Merkmale, dann Äquivalenz nur für die abweichenden Merkmale; die dritte Frage scheitert, wenn die Patentschrift den anderen Weg offenbart, aber nicht beansprucht."),
            ]),
            step("C. Benutzungshandlung im Inland (§§ 9, 10 PatG)", children=[
                step("1. Unmittelbare Benutzung (§ 9 S. 2 PatG)", "Erzeugnis: Herstellen, Anbieten, Inverkehrbringen, Gebrauchen, Einführen, Besitzen; Verfahren: Anwenden, Anbieten zur Anwendung; unmittelbares Verfahrenserzeugnis (Nr. 3).",
                     concepts=["pat_benutzungshandlungen", "pat_verfahrenserzeugnis"], norms=["§ 9 PatG"], cases=["pat_bgh_abgasreinigungsvorrichtung", "pat_bgh_rezeptortyrosinkinase_ii", "pat_bgh_wasserdichter_lederschuh"]),
                step("2. Mittelbare Benutzung (§ 10 PatG)", "Anbieten oder Liefern von Mitteln, die sich auf ein wesentliches Element beziehen, an Nichtberechtigte; Kenntnis oder Offensichtlichkeit der Bestimmung; doppelter Inlandsbezug; Ausnahme allgemein erhältlicher Erzeugnisse.",
                     concepts=["pat_mittelbare_verletzung"], norms=["§ 10 PatG"], cases=["pat_bgh_fluegelradzaehler", "pat_bgh_fraesverfahren"]),
            ]),
            step("D. Einwendungen und Einreden", children=[
                step("1. Schranken (§ 11 PatG), Vorbenutzungsrecht (§ 12 PatG), Staatsbenutzung (§ 13 PatG)", "Privater Bereich, Versuchsprivileg, Bolar, Apotheken, Transit; Vorbenutzung mit Erfindungsbesitz und Benutzung zum Prioritätstag.",
                     concepts=["pat_schranken", "pat_vorbenutzungsrecht"], norms=["§ 11 PatG", "§ 12 PatG", "§ 13 PatG"]),
                step("2. Erschöpfung", "Inverkehrbringen im EWR durch den Inhaber oder mit Zustimmung; bestimmungsgemäßer Gebrauch und Reparatur frei, Neuherstellung nicht; keine internationale Erschöpfung.",
                     concepts=["pat_erschoepfung"], norms=["§ 9 PatG"], cases=["pat_bgh_palettenbehaelter_ii", "pat_bgh_trommeleinheit", "pat_bgh_tintenpatrone"]),
                step("3. Lizenz, Zwangslizenz, kartellrechtlicher Einwand", "Vertragliche Lizenz (§ 15 PatG), Lizenzbereitschaft (§ 23 PatG), Zwangslizenz (§ 24 PatG, nur durch Urteil des BPatG); FRAND-Einwand bei standardessentiellen Patenten aus Art. 102 AEUV.",
                     concepts=["pat_lizenz", "pat_zwangslizenz"], norms=["§ 15 PatG", "§ 23 PatG", "§ 24 PatG"]),
                step("4. Rechtsbestand und Aussetzung (§ 148 ZPO)", "Nichtigkeit ist kein Einwand im Verletzungsprozess; Aussetzung bei überwiegender Wahrscheinlichkeit der Vernichtung, in höheren Instanzen großzügiger.",
                     concepts=["pat_trennungsprinzip", "pat_aussetzung"], norms=["§ 81 PatG"], cases=["pat_bgh_klimaschrank", "pat_bgh_adalimumab"]),
                step("5. Verjährung und Verwirkung (§ 141 PatG)", "Drei Jahre ab Kenntnis, zehn Jahre absolut; Restschadensersatz nach § 852 BGB.",
                     concepts=["pat_schadensersatz"], norms=["§ 141 PatG"]),
            ]),
            step("E. Rechtsfolgen (§§ 139 bis 140e PatG)", children=[
                step("1. Unterlassung (§ 139 Abs. 1 PatG)", "Wiederholungs- oder Erstbegehungsgefahr; verschuldensunabhängig; Verhältnismäßigkeitseinwand mit Geldausgleich (S. 3, 4).",
                     concepts=["pat_unterlassung"], norms=["§ 139 Abs. 1 PatG"], cases=["pat_bgh_tintenpatrone"]),
                step("2. Schadensersatz (§ 139 Abs. 2 PatG) und Bezifferung", "Verschulden; drei Berechnungsarten; Feststellungsklage plus Auskunft und Rechnungslegung (§ 140b PatG, § 242 BGB) als Stufenklage.",
                     concepts=["pat_schadensersatz"], norms=["§ 139 Abs. 2 PatG", "§ 140b PatG"], cases=["pat_bgh_fraesverfahren"]),
                step("3. Vernichtung, Rückruf, Auskunft, Besichtigung, Urteilsbekanntmachung", "§§ 140a bis 140e PatG mit Verhältnismäßigkeitsvorbehalt; Besichtigung auch vorprozessual per einstweiliger Verfügung.",
                     concepts=["pat_rechtsfolgen_nebenanspruche", "pat_besichtigung"], norms=["§ 140a PatG", "§ 140b PatG", "§ 140c PatG", "§ 140d PatG", "§ 140e PatG"], cases=["pat_bgh_restschadstoffentfernung"]),
                step("4. Kosten und Streitwert", "Patentanwaltskosten erstattungsfähig (§ 143 Abs. 3 PatG); Streitwertbegünstigung (§ 144 PatG); Strafbarkeit (§ 142 PatG) und Zollbeschlagnahme (§§ 142a, 142b PatG) daneben.",
                     concepts=["pat_kostenerstattung"], norms=["§ 143 Abs. 3 PatG", "§ 144 PatG", "§ 142 PatG"]),
            ]),
        ],
    ),
    dict(
        id="pat_schema_einspruch",
        label="Einspruch und Einspruchsbeschwerde (§§ 59 bis 62, 73 ff. PatG)",
        kategorie="Patent: Einspruch und Beschränkung",
        beschreibung="Zulässigkeit (Frist, Form, Gebühr, Begründung, Einspruchsberechtigung), Begründetheit anhand der Widerrufsgründe des § 21 PatG, Entscheidung der Patentabteilung und Beschwerde zum Technischen Beschwerdesenat mit Rechtsbeschwerde. Klausurschwerpunkt: Fristen und Gebühren nach dem PatKostG.",
        norms=["§ 59 PatG", "§ 61 PatG", "§ 21 PatG", "§ 73 PatG", "§ 6 PatKostG"],
        steps=[
            step("A. Zulässigkeit des Einspruchs (§ 59 Abs. 1 PatG)", children=[
                step("1. Frist: neun Monate ab Veröffentlichung der Erteilung", "Fristbeginn mit Veröffentlichung im Patentblatt (§ 58 Abs. 1 PatG); Berechnung nach §§ 187 ff. BGB; keine Wiedereinsetzung (§ 123 Abs. 1 S. 2 Nr. 1 PatG).",
                     concepts=["pat_einspruch", "pat_fristen"], norms=["§ 59 Abs. 1 PatG", "§ 58 PatG", "§ 123 Abs. 1 PatG"]),
                step("2. Form und Gebühr", "Schriftlich beim DPMA; Gebühr 200 EUR (Nr. 313 600) innerhalb der Einspruchsfrist, für jeden Einsprechenden gesondert; sonst gilt der Einspruch als nicht erhoben (§ 6 Abs. 2 PatKostG).",
                     concepts=["pat_zahlungsfristen", "pat_gebuehren"], norms=["§ 6 Abs. 1 PatKostG", "§ 6 Abs. 2 PatKostG", "Anlage PatKostG"], cases=["pat_bpatg_einspruchsgebuehren_gemeinsam"],
                     hinweis="Beliebte Klausurfalle: Einspruch am letzten Tag per Fax, Gebühr erst nach Fristablauf überwiesen."),
                step("3. Begründung: Tatsachen im Einzelnen", "Angabe der Tatsachen, die den Einspruch rechtfertigen, innerhalb der Frist so vollständig, dass Patentabteilung und Inhaber abschließende Folgerungen ziehen können; Nachschieben von Beweismitteln zulässig, neuer Widerrufsgrund nur innerhalb der Frist.",
                     concepts=["pat_einspruch"], norms=["§ 59 Abs. 1 PatG"], cases=["pat_bgh_leistungshalbleiterbauelement"]),
                step("4. Einspruchsberechtigung und Beitritt", "Jedermann (Popularrechtsbehelf), bei widerrechtlicher Entnahme nur der Verletzte (§ 59 Abs. 1 S. 1 Hs. 2 PatG); Beitritt des Verletzungsbeklagten binnen drei Monaten (§ 59 Abs. 2 PatG), auch bei einstweiliger Verfügung.",
                     concepts=["pat_beitritt"], norms=["§ 59 Abs. 2 PatG"], cases=["pat_bgh_ratschenschluessel"]),
            ]),
            step("B. Begründetheit: Widerrufsgründe (§ 21 Abs. 1 PatG)", children=[
                step("1. Fehlende Patentfähigkeit (Nr. 1)", "Prüfung nach dem Schema Patentfähigkeit; Streitgegenstand sind die geltend gemachten Gründe; keine neuen Widerrufsgründe von Amts wegen in der Beschwerde.",
                     concepts=["pat_widerrufsgruende"], norms=["§ 21 Abs. 1 Nr. 1 PatG"], cases=["pat_bgh_ventileinrichtung"]),
                step("2. Mangelnde Ausführbarkeit (Nr. 2)", "Fachmann kann die Lehre nicht ohne unzumutbaren Aufwand nacharbeiten; Klarheit ist kein Widerrufsgrund.",
                     concepts=["pat_ausfuehrbarkeit"], norms=["§ 21 Abs. 1 Nr. 2 PatG"], cases=["pat_bgh_thermoplastische_zusammensetzung"]),
                step("3. Widerrechtliche Entnahme (Nr. 3)", "Nur der Verletzte; danach Nachanmeldung mit Priorität (§ 7 Abs. 2 PatG).",
                     concepts=["pat_recht_auf_patent"], norms=["§ 21 Abs. 1 Nr. 3 PatG", "§ 7 Abs. 2 PatG"]),
                step("4. Unzulässige Erweiterung (Nr. 4)", "Gegenstand geht über die ursprüngliche Anmeldung hinaus; Aliud führt zum Widerruf, beschränkendes Merkmal bleibt ohne Berücksichtigung bei der Patentfähigkeit.",
                     concepts=["pat_unzulaessige_erweiterung"], norms=["§ 21 Abs. 1 Nr. 4 PatG"], cases=["pat_bgh_hubgliedertor_i", "pat_bgh_winkelmesseinrichtung"]),
            ]),
            step("C. Entscheidung der Patentabteilung (§ 61 PatG)", "Widerruf, Aufrechterhaltung oder beschränkte Aufrechterhaltung mit Hilfsanträgen (§ 21 Abs. 2 PatG); die Teilung des Patents (§ 60 PatG a.F.) ist seit 2009 abgeschafft; Kosten jeder selbst, Billigkeit (§ 62 PatG); Wirkung des Widerrufs ex tunc (§ 21 Abs. 3 PatG).",
                 concepts=["pat_beschraenkte_verteidigung", "pat_teilung"], norms=["§ 61 PatG", "§ 21 Abs. 2 PatG", "§ 62 PatG"], cases=["pat_bgh_sammelhefter"]),
            step("D. Beschwerde zum Technischen Beschwerdesenat (§§ 73 ff. PatG)", children=[
                step("1. Zulässigkeit: Monatsfrist, Gebühr, Beschwer", "Ein Monat ab Zustellung; Gebühr 500 EUR (Nr. 401 100) innerhalb der Frist, sonst gilt die Beschwerde als nicht eingelegt; Beteiligter mit Beschwer.",
                     concepts=["pat_beschwerde", "pat_zahlungsfristen"], norms=["§ 73 PatG", "§ 74 PatG", "§ 6 Abs. 1 PatKostG"]),
                step("2. Abhilfe und Vorlage (§ 73 Abs. 3 PatG)", "Patentabteilung hilft binnen eines Monats ab oder legt vor; in mehrseitigen Verfahren keine Abhilfe.",
                     concepts=["pat_beschwerde"], norms=["§ 73 Abs. 3 PatG"]),
                step("3. Entscheidung (§ 79 PatG) und Kosten (§ 80 PatG)", "Entscheidung in der Sache oder Zurückverweisung; Rückzahlung der Beschwerdegebühr bei Verfahrensfehlern; Rechtsbeschwerde bei Zulassung oder absoluten Gründen (§ 100 PatG).",
                     concepts=["pat_beschwerde", "pat_rechtsbeschwerde", "pat_rechtliches_gehoer"], norms=["§ 79 PatG", "§ 80 PatG", "§ 100 PatG"], cases=["pat_bgh_schwingungsdaempfer", "pat_bpatg_teilbeschluss"]),
            ]),
        ],
    ),
    dict(
        id="pat_schema_nichtigkeitsklage",
        label="Nichtigkeitsklage (§§ 81 bis 84, 110 ff. PatG; Art. II § 6 IntPatÜG)",
        kategorie="Patent: Nichtigkeit und Zwangslizenz",
        beschreibung="Zulässigkeit (Zuständigkeit des BPatG oder des EPG, Klagebefugnis, Klagesperre, Form, Gebühr, Sicherheitsleistung), Nichtigkeitsgründe, Verfahrensablauf mit qualifiziertem Hinweis, beschränkte Verteidigung, Urteil und Berufung zum BGH.",
        norms=["§ 81 PatG", "§ 22 PatG", "§ 83 PatG", "§ 84 PatG", "§ 110 PatG", "Art. II § 6 IntPatÜG"],
        steps=[
            step("A. Zulässigkeit", children=[
                step("1. Zuständigkeit: BPatG oder EPG?", "Deutsches Patent: Nichtigkeitssenat des BPatG. Europäisches Patent: BPatG nach Art. II § 6 IntPatÜG nur bei Opt-out oder in der Übergangszeit (Art. 83 EPGÜ), sonst EPG (Art. 32 Abs. 1 lit. d EPGÜ); Einheitspatent: nur EPG (Art. II § 15 IntPatÜG).",
                     concepts=["pat_nichtigkeit_ep", "pat_einheitspatent_national"], norms=["§ 81 Abs. 4 PatG", "Art. II § 6 IntPatÜG", "Art. II § 15 IntPatÜG", "Art. 32 EPGÜ", "Art. 83 EPGÜ"]),
                step("2. Klagebefugnis und Klagesperre (§ 81 Abs. 1, 2 PatG)", "Popularklage; bei widerrechtlicher Entnahme nur der Verletzte; unzulässig, solange Einspruch (auch beim EPA) möglich oder anhängig ist; kein Rechtsmissbrauch bei paralleler Klage.",
                     concepts=["pat_nichtigkeitsklage"], norms=["§ 81 Abs. 1 PatG", "§ 81 Abs. 2 PatG"], cases=["pat_bpatg_torasemid", "pat_bgh_benutzerauthentifizierung"]),
                step("3. Klageschrift, Gebühr, Sicherheitsleistung", "Klage gegen den eingetragenen Inhaber (§ 81 Abs. 1 S. 2, § 30 Abs. 3 PatG); Gebühr 4,5 Wertgebühren vorab (§ 5 Abs. 1 PatKostG), Streitwert nach § 2 Abs. 2 S. 4 PatKostG i.V.m. § 51 Abs. 1 GKG; Sicherheitsleistung ausländischer Kläger (§ 81 Abs. 6 PatG).",
                     concepts=["pat_streitwert", "pat_gebuehren"], norms=["§ 81 Abs. 5 PatG", "§ 81 Abs. 6 PatG", "§ 2 Abs. 2 PatKostG", "§ 5 PatKostG"]),
            ]),
            step("B. Nichtigkeitsgründe (§ 22 PatG; Art. II § 6 Abs. 1 IntPatÜG)", "Fehlende Patentfähigkeit, mangelnde Ausführbarkeit, widerrechtliche Entnahme, unzulässige Erweiterung, Erweiterung des Schutzbereichs; abschließend, Klarheit kein Grund; anspruchsweise Prüfung bei nebengeordneten Ansprüchen.",
                 concepts=["pat_nichtigkeitsgruende", "pat_unzulaessige_erweiterung", "pat_ausfuehrbarkeit"], norms=["§ 22 PatG", "Art. II § 6 Abs. 1 IntPatÜG"], cases=["pat_bgh_fugenband", "pat_bgh_sensoranordnung", "pat_bgh_wundbehandlungsvorrichtung"]),
            step("C. Verfahren vor dem Nichtigkeitssenat", children=[
                step("1. Zustellung und Widerspruch (§ 82 PatG)", "Widerspruch binnen eines Monats; ohne Widerspruch Entscheidung ohne mündliche Verhandlung, behauptete Tatsachen gelten als erwiesen (§ 82 Abs. 2 PatG).",
                     concepts=["pat_nichtigkeitsklage"], norms=["§ 82 PatG"]),
                step("2. Qualifizierter Hinweis, Fristen, Präklusion (§ 83 PatG)", "Hinweis auf entscheidungserhebliche Gesichtspunkte, Fristsetzung, Zurückweisung verspäteten Vorbringens mit Bindung in der Berufung (§ 117 PatG).",
                     concepts=["pat_qualifizierter_hinweis"], norms=["§ 83 PatG", "§ 117 PatG"], cases=["pat_bgh_walzstrasse"]),
                step("3. Beschränkte Verteidigung und Hilfsanträge", "Änderung der Ansprüche ohne Erweiterung; Klarheit nur bei geänderten Merkmalen; Reihenfolge der Hilfsanträge bindet.",
                     concepts=["pat_beschraenkte_verteidigung"], norms=["§ 22 Abs. 2 PatG", "Art. II § 6 Abs. 3 IntPatÜG"], cases=["pat_bpatg_kaffeemaschine", "pat_bgh_fugenband"]),
                step("4. Nebenintervention und Aussetzung des Verletzungsprozesses", "Beitritt nach § 66 ZPO bei weitem rechtlichem Interesse; parallel Aussetzung des Verletzungsverfahrens nach § 148 ZPO.",
                     concepts=["pat_nebenintervention", "pat_aussetzung"], norms=["§ 99 Abs. 1 PatG"], cases=["pat_bgh_carvedilol_nebenintervention", "pat_bgh_klimaschrank"]),
            ]),
            step("D. Urteil, Kosten (§ 84 PatG), Wirkung", "Nichtigerklärung ganz oder teilweise mit Wirkung ex tunc und gegen jedermann (§ 22 Abs. 2, § 21 Abs. 3 PatG); Kosten nach §§ 91 ff. ZPO, Billigkeit bei erst im Verfahren erklärter Beschränkung; Patentanwaltskosten erstattungsfähig, Syndikusanwälte nicht.",
                 concepts=["pat_streitwert", "pat_kostenerstattung"], norms=["§ 84 PatG", "§ 21 Abs. 3 PatG"], cases=["pat_bpatg_syndikusanwalt_kosten"]),
            step("E. Berufung zum BGH (§§ 110 ff. PatG)", "Ein Monat Einlegung (§ 110 Abs. 3 PatG), drei Monate Begründung (§ 112 Abs. 2 PatG); Prüfung im Rahmen der Anträge (§ 116 PatG), neue Angriffs- und Verteidigungsmittel nur nach § 117 PatG; sachdienliche geänderte Verteidigung bei Abweichung vom Hinweis; Streitwert der Berufung nach angegriffenem Umfang.",
                 concepts=["pat_nichtigkeitsberufung"], norms=["§ 110 PatG", "§ 116 PatG", "§ 117 PatG"], cases=["pat_bgh_fahrzeugscheibe_ii", "pat_bgh_pemetrexed_ii", "pat_bgh_streitwert_nichtigkeitsberufung"]),
        ],
    ),
    dict(
        id="pat_schema_anmeldung_erteilung",
        label="Anmeldung und Erteilungsverfahren (§§ 34 bis 49 PatG, PatV, PatKostG)",
        kategorie="Patent: Anmeldung und Erteilung",
        beschreibung="Vom Anmeldetag bis zur Erteilung: Mindesterfordernisse, Anmeldeunterlagen nach der PatV, Gebühren und Zahlungsfristen nach dem PatKostG, Priorität, Erfinderbenennung, Offensichtlichkeitsprüfung, Recherche und Prüfungsantrag, Prüfungsverfahren mit Änderungen und Teilung, Erteilung oder Zurückweisung mit Rechtsbehelfen (Beschwerde, Weiterbehandlung, Wiedereinsetzung).",
        norms=["§ 34 PatG", "§ 35 PatG", "§ 44 PatG", "§ 49 PatG", "§ 6 PatKostG", "§ 123a PatG"],
        steps=[
            step("A. Anmeldetag (§ 35 PatG)", "Erteilungsantrag, Identität des Anmelders, Beschreibung (auch fremdsprachig); Übersetzung binnen drei bzw. zwölf Monaten (§ 35a PatG); fehlende Zeichnungen und Beschreibungsteile nach § 35 Abs. 2, 3 PatG.",
                 concepts=["pat_anmeldetag"], norms=["§ 35 PatG", "§ 35a PatG"], cases=["pat_bpatg_mobilfunknetzwerk"]),
            step("B. Anmeldeunterlagen und Form (§ 34 PatG, PatV)", children=[
                step("1. Antrag, Ansprüche, Beschreibung, Zeichnungen, Zusammenfassung", "§ 34 Abs. 3 PatG; Form nach §§ 4 bis 13 PatV; Einheitlichkeit (§ 34 Abs. 5 PatG), Ausführbarkeit (§ 34 Abs. 4 PatG).",
                     concepts=["pat_anmeldung", "pat_patentanspruch", "pat_beschreibung"], norms=["§ 34 Abs. 3 PatG", "§ 4 PatV", "§ 9 PatV", "§ 10 PatV", "§ 12 PatV", "§ 13 PatV"], cases=["pat_bpatg_aufreissdeckel"]),
                step("2. Anmeldegebühr (Nr. 311 000) binnen drei Monaten", "Fälligkeit mit Einreichung (§ 3 Abs. 1 PatKostG), Zahlungsfrist drei Monate (§ 6 Abs. 1 S. 2 PatKostG), sonst Rücknahmefiktion (§ 6 Abs. 2 PatKostG); elektronisch 40 EUR, Papier 60 EUR.",
                     concepts=["pat_gebuehren", "pat_faelligkeit", "pat_zahlungsfristen"], norms=["§ 3 Abs. 1 PatKostG", "§ 6 PatKostG", "Anlage PatKostG"]),
                step("3. Priorität (§§ 40, 41 PatG) und Erfinderbenennung (§ 37 PatG)", "Prioritätserklärung binnen zwei Monaten (§ 40 Abs. 4 PatG) bzw. 16 Monaten (§ 41 Abs. 1 PatG); keine Wiedereinsetzung in die Zwölfmonatsfrist der inneren Priorität (§ 123 Abs. 1 S. 2 Nr. 3 PatG); Erfinderbenennung binnen 15 Monaten (§ 37 Abs. 1 PatG) nach § 7 PatV.",
                     concepts=["pat_prioritaet", "pat_erfinderbenennung"], norms=["§ 40 PatG", "§ 41 PatG", "§ 37 PatG", "§ 7 PatV"], cases=["pat_bgh_fahrzeugscheibe", "pat_bpatg_mehrfach_funkgeraet"]),
            ]),
            step("C. Offensichtlichkeitsprüfung, Recherche, Prüfungsantrag (§§ 42 bis 44 PatG)", "Formmängel und offensichtliche Schutzunfähigkeit (§ 42 PatG); Rechercheantrag 300 EUR (§ 43 PatG); Prüfungsantrag binnen sieben Jahren (§ 44 Abs. 2 PatG), 350/150 EUR, sonst Rücknahmefiktion (§ 58 Abs. 3 PatG); Offenlegung nach 18 Monaten (§ 31 Abs. 2 Nr. 2, § 32 Abs. 5 PatG).",
                 concepts=["pat_pruefungsverfahren", "pat_akteneinsicht"], norms=["§ 42 PatG", "§ 43 PatG", "§ 44 PatG", "§ 58 Abs. 3 PatG", "§ 32 PatG"]),
            step("D. Prüfungsverfahren (§§ 45 bis 48 PatG)", children=[
                step("1. Bescheide, rechtliches Gehör, Änderungen (§ 38 PatG)", "Beanstandung mit Fristsetzung; Änderungen bis zum Prüfungsantrag nur zur Berichtigung offensichtlicher Unrichtigkeiten, zur Mängelbeseitigung und an den Ansprüchen, danach bis zum Erteilungsbeschluss frei, nie über die ursprüngliche Offenbarung hinaus (§ 38 S. 1 PatG).",
                     concepts=["pat_unzulaessige_erweiterung", "pat_rechtliches_gehoer"], norms=["§ 45 PatG", "§ 38 PatG"], cases=["pat_bgh_phosphatidylcholin"]),
                step("2. Teilung und Ausscheidung (§ 39, § 34 Abs. 5 PatG)", "Teilung jederzeit bis zur Erteilung, unwiderruflich, Gebühren nachzahlen; Ausscheidung bei Uneinheitlichkeit mit eigener Prüfungsgebühr.",
                     concepts=["pat_teilung"], norms=["§ 39 PatG", "§ 34 Abs. 5 PatG"], cases=["pat_bpatg_pruefungsgebuehr_ausscheidung"]),
                step("3. Zurückweisung (§ 48 PatG) und Rechtsbehelfe", "Beschwerde binnen eines Monats mit Gebühr (§ 73 PatG, § 6 PatKostG); bei Fristversäumung Weiterbehandlung (§ 123a PatG) oder Wiedereinsetzung (§ 123 PatG); einheitliche Entscheidung über Haupt- und Hilfsanträge.",
                     concepts=["pat_beschwerde", "pat_weiterbehandlung", "pat_wiedereinsetzung"], norms=["§ 48 PatG", "§ 73 PatG", "§ 123 PatG", "§ 123a PatG"], cases=["pat_bpatg_teilbeschluss", "pat_bpatg_weiterbehandlung_ii"]),
            ]),
            step("E. Erteilung (§ 49 PatG), Veröffentlichung (§ 58 PatG), Jahresgebühren (§ 17 PatG)", "Erteilungsbeschluss, Veröffentlichung im Patentblatt mit Wirkungseintritt und Beginn der Einspruchsfrist; Jahresgebühren ab dem dritten Jahr nach § 3 Abs. 2, § 7 PatKostG; Lizenzbereitschaft (§ 23 PatG) halbiert sie.",
                 concepts=["pat_laufzeit_jahresgebuehren", "pat_jahresgebuehren"], norms=["§ 49 PatG", "§ 58 PatG", "§ 17 PatG", "§ 7 PatKostG", "§ 23 PatG"]),
        ],
    ),
    dict(
        id="pat_schema_fristversaeumung",
        label="Fristversäumung: Rechtsfolge und Rechtsbehelf (§§ 123, 123a PatG; §§ 6, 7 PatKostG)",
        kategorie="Patent: Verfahren, Fristen, Rechtsmittel",
        beschreibung="Klausurraster für jede versäumte Frist oder Zahlung: Welche Frist (gesetzlich oder amtsseitig, Zahlungsfrist), wann lief sie ab, welche Rechtsfolge tritt kraft Gesetzes ein, und welcher Rechtsbehelf hilft: Weiterbehandlung (ohne Verschulden), Wiedereinsetzung (ohne Verschulden des Vertreters), Nachfrist mit Zuschlag bei Jahresgebühren, oder gar nichts (Einspruchsfrist, Nachanmeldefrist der inneren Priorität).",
        norms=["§ 123 PatG", "§ 123a PatG", "§ 6 PatKostG", "§ 7 PatKostG"],
        steps=[
            step("A. Frist bestimmen", "Art der Frist (gesetzlich: Prüfungsantrag, Einspruch, Beschwerde, Priorität; amtsseitig: Bescheidfristen; Zahlungsfrist: §§ 6, 7 PatKostG), Fristbeginn (Zustellung, Anmeldetag, Veröffentlichung, Fälligkeit), Fristende nach §§ 187 ff. BGB mit Wochenend- und Feiertagsregel; Zahlungstag nach der PatKostZV.",
                 concepts=["pat_fristen", "pat_faelligkeit"], norms=["§ 3 PatKostG", "§ 6 Abs. 1 PatKostG", "§ 7 Abs. 1 PatKostG"]),
            step("B. Rechtsfolge der Versäumung", "Rücknahmefiktion der Anmeldung (§ 35a Abs. 1 S. 2, § 58 Abs. 3 PatG, § 6 Abs. 2 PatKostG), Rechtsbehelf gilt als nicht erhoben (§ 6 Abs. 2 PatKostG), Erlöschen des Patents (§ 20 Abs. 1 Nr. 2 PatG), Verlust der Priorität (§ 41 Abs. 1 S. 3 PatG), Zurückweisung (§ 48 PatG).",
                 concepts=["pat_zahlungsfristen", "pat_jahresgebuehren"], norms=["§ 6 Abs. 2 PatKostG", "§ 20 Abs. 1 Nr. 2 PatG", "§ 58 Abs. 3 PatG"], cases=["pat_bpatg_einspruchsgebuehren_gemeinsam", "pat_bpatg_saegeblatt"]),
            step("C. Rechtsbehelf wählen", children=[
                step("1. Jahresgebühr: Nachfrist mit Zuschlag (§ 7 Abs. 1 PatKostG)", "Bis Ablauf des sechsten Monats nach Fälligkeit mit 50 EUR Zuschlag; danach Erlöschen und nur noch Wiedereinsetzung.",
                     concepts=["pat_jahresgebuehren"], norms=["§ 7 PatKostG"], cases=["pat_bpatg_saegeblatt"]),
                step("2. Weiterbehandlung (§ 123a PatG)", "Nur Anmeldeverfahren, nur amtsseitig gesetzte Fristen, nach Zurückweisung: Antrag, Nachholung und 100 EUR binnen eines Monats nach Zustellung; kein Verschuldensmaßstab; Frist nicht verlängerbar.",
                     concepts=["pat_weiterbehandlung"], norms=["§ 123a PatG"], cases=["pat_bpatg_weiterbehandlung", "pat_bpatg_weiterbehandlung_ii"]),
                step("3. Wiedereinsetzung (§ 123 PatG)", "Unverschuldete Versäumung (Vertreterverschulden zugerechnet, Büroversehen entschuldbar bei Organisation und Kontrolle); Antrag mit Begründung und Nachholung binnen zwei Monaten nach Wegfall des Hindernisses, spätestens ein Jahr; Glaubhaftmachung; Zwischenbenutzungsrecht Dritter (Abs. 5).",
                     concepts=["pat_wiedereinsetzung"], norms=["§ 123 PatG"], cases=["pat_bgh_verdickerpolymer_ii", "pat_bpatg_weiterbehandlung"],
                     hinweis="Ausgeschlossen (§ 123 Abs. 1 S. 2 PatG): Einspruchsfrist und Einspruchsgebühr, Beschwerdefrist des Einsprechenden gegen die Aufrechterhaltung, Nachanmeldefrist bei innerer Priorität (§ 7 Abs. 2, § 40 PatG); ebenso die Weiterbehandlungsfrist (§ 123a Abs. 3 PatG)."),
                step("4. Kein Rechtsbehelf", "Einspruchsfrist (§ 59 PatG) und Nachanmeldefrist der inneren Priorität (§ 40 PatG): Versäumung ist endgültig; Ausweg Nichtigkeitsklage bzw. Neuanmeldung ohne Priorität. Bei der Unionspriorität (§ 41 PatG) ist Wiedereinsetzung heute möglich (§ 123 Abs. 7 PatG; Mehrfach-Funkgerät betrifft die alte Rechtslage).",
                     concepts=["pat_einspruch", "pat_prioritaet"], norms=["§ 123 Abs. 1 PatG", "§ 59 Abs. 1 PatG"], cases=["pat_bpatg_mehrfach_funkgeraet"]),
            ]),
            step("D. Zuständigkeit und Rechtsmittel", "Entscheidung durch die Stelle, die über die versäumte Handlung zu befinden hat (§ 123 Abs. 3 PatG); Beschwerde zum Juristischen Beschwerdesenat (§ 73 PatG), Gebühr 200 EUR (Nr. 401 300).",
                 concepts=["pat_beschwerde", "pat_bpatg_aufbau"], norms=["§ 123 Abs. 3 PatG", "§ 73 PatG"]),
        ],
    ),
]
